sapcc/helm-charts

- global/prometheus-alertmanager/templates/config.yaml
- system/kube-monitoring/charts/prometheus-frontend/node.alerts
- system/kube-monitoring/charts/prometheus-frontend/templates/config.yaml
These alert definitions come from the legacy Swift, but since they apply to the control plane rather than the Swift service, I feel more comfortable putting them in here than into the Swift chart etc.
> add some alert definitions for node health (CPU usage, TCP connections)

- openstack/content-repo/templates/_scheduledjob.yaml
- openstack/content-repo/templates/configmap.yaml
- openstack/content-repo/templates/job.yaml
- openstack/content-repo/templates/secrets.yaml
- openstack/content-repo/values.yaml
* Adding support for client ssl auth
* Certs go to secrets
* Config will no be mounted to /etc/http-import/config
* certs can be found in /etc/http-import/secret
> Content Repo - Client SSL auth support

- openstack/swift/charts/swift_drive_autopilot/templates/configmap.yaml
- openstack/swift/charts/swift_drive_autopilot/values.yaml
This simplification is made possible by two changes:
1. The autopilot will not complain about an unmatching glob on
`/dev/sd[a-z][a-z]` when there are fewer than 26 drives.
2. The autopilot guarantees (both by documentation and by test coverage)
that swift-ids will always be assigned in order, so we can just put
`swift-01` through `swift-99` into the pool, and it will only use the
lowest-numbered IDs (e.g. `swift-01` through `swift-12` if there are 12
eligible drives).
@d044166 You okay with this? If so, I will merge. (Please don't merge yourself, I need to bump the image version on the autopilot in all regions.)
> unify swift-drive-autopilot config across clusters

- openstack/swift/charts/swift_drive_autopilot/templates/configmap.yaml
- openstack/swift/charts/swift_drive_autopilot/values.yaml
The `drive-autopilot.yaml` now renders like this:
```yaml
chroot: /coreos
drives:
- /dev/sd[a-z]
- /dev/sd[a-z][a-z]
chown:
user: "1000"
group: "1000"
keys:
- secret: DEFINED_IN_REGION_CHART
swift-id-pool: 
- swift-01
- swift-02
- swift-03
- swift-04
- swift-05
- swift-06
- swift-07
- swift-08
- swift-09
- swift-10
- swift-11
- swift-12
- swift-13
- swift-14
- swift-15
- swift-16
- swift-17
- swift-18
- swift-19
- swift-20
- spare
- swift-21
- swift-22
- swift-23
- swift-24
- swift-25
- swift-26
- swift-27
- swift-28
- swift-29
- swift-30
- swift-31
- swift-32
- swift-33
- swift-34
- swift-35
- swift-36
- swift-37
- swift-38
- swift-39
- swift-40
- spare
- swift-41
- swift-42
- swift-43
- swift-44
- swift-45
- swift-46
- swift-47
- swift-48
- swift-49
- swift-50
- swift-51
- swift-52
- …
```
> add spare disks to swift-drive-autopilot config

- global/prometheus/values.yaml
- system/kube-monitoring/charts/prometheus-collector/values.yaml
- system/kube-monitoring/charts/prometheus-frontend/values.yaml
Use [latest Prometheus](https://github.com/prometheus/prometheus/releases/tag/v1.5.1). It already runs happily in staging. 
Ok @majewsky?
> Prometheus v1.5.1

- system/kube-monitoring/charts/prometheus-collector/aggregation.rules
- system/kube-monitoring/charts/prometheus-frontend/swift.rules
move rule avg:swift_cluster_storage_used_percent_gauge{} to separate swift.rules in prom. frontend
Looks good @majewsky?
/cc @reimannf More swift rules could go here `system/kube-monitoring/charts/prometheus-frontend/swift.rules`
> move swift rule to sep. file in prom frontend

- openstack/swift/templates/_utils.tpl
- openstack/swift/templates/account-daemonset.yaml
- openstack/swift/templates/container-daemonset.yaml
- openstack/swift/templates/object-daemonset.yaml
- openstack/swift/templates/recon-cron-daemonset.yaml
- openstack/swift/templates/replicators-daemonset.yaml
This should make it easier to reorder the services into new daemonsets in the next step.
> [swift] reduce code duplication among daemonset yamls

- global/prometheus/prometheus.yaml
Background is, that prometheus global keeps metrics for a longer time frame, which allows a better prediction of the swift cluster utilisation like here https://grafana.eu-de-1.cloud.sap/dashboard/db/swift-capacity, which is currently only one week.
> Swift used percentage to prometheus global

- openstack/swift/templates/etc/_nginx.conf.tpl
All the other OpenStack services already have HTTP/2 courtesy of Kubernetes' ingress-controller, and it apparently gives a nice free speed boost when the client understands and advertises HTTP/2.
BTW, I know that this change looks suspiciously small, but it's really all that's needed. I rolled out [an identical change](https://github.com/majewsky/system-configuration/commit/7b34ebcee09ad0510d96ad7853e8c901a4241b80) on my private systems last week.
> enable afterburner

- system/kube-system/charts/ingress/templates/default-backend-deployment.yaml
- system/kube-system/charts/ingress/templates/ingress-controller-configmap.yaml
- system/kube-system/charts/ingress/templates/ingress-controller-daemonset.yaml
- system/kube-system/charts/ingress/templates/ingress-service.yaml
- system/kube-system/charts/ingress/values.yaml
***WIP - DO NOT MERGE***
Does it make sense to try [0.9.0-beta.1](https://github.com/kubernetes/ingress/blob/master/controllers/nginx/Changelog.md#09-beta1) of the ingress controller as this version includes https://github.com/kubernetes/ingress/pull/36,
@databus23?
Would test in staging after lunch if you agree.
> update ingress controller to 0.9.0-beta.2 and add prometheus scrape annotations to service

- openstack/limes/charts/postgresql/Chart.yaml
- openstack/limes/charts/postgresql/README.md
- openstack/limes/charts/postgresql/templates/NOTES.txt
- openstack/limes/charts/postgresql/templates/_helpers.tpl
- openstack/limes/charts/postgresql/templates/deployment.yaml
- openstack/limes/charts/postgresql/templates/pvc.yaml
- openstack/limes/charts/postgresql/templates/secrets.yaml
- openstack/limes/charts/postgresql/templates/svc.yaml
- openstack/limes/charts/postgresql/values.yaml
- openstack/limes/templates/collect-deployment.yaml
- openstack/limes/templates/configmap.yaml
- openstack/limes/templates/migrate-deployment.yaml
- openstack/limes/templates/seed.yaml
- openstack/limes/values.yaml
The API part is not yet deployed because it is not yet implemented.
The PostgreSQL subchart is a direct copy of `common/postgresql`. (I couldn't figure out yet how to include that directory as a subchart directly.)
> expand Limes chart to deploy limes-collect and limes-migrate

- openstack/swift/bin/swift-start
- openstack/swift/templates/account-caretaker-collect-daemonset.yaml
- openstack/swift/templates/account-caretaker-mergify-deployment.yaml
- openstack/swift/templates/caretaker-configmap.yaml
- openstack/swift/values.yaml
Support `swift-account-caretaker` with multiple keystone backends in a shared swift cluster approach
> [swift] account-caretaker support for multiple keystone backends

- system/kube-system/charts/ingress/values.yaml
No longer region-specific. OK @databus23?
> ingress controller: enable virtual host traffic status module

- openstack/limes/templates/api-service.yaml
Requires latest Limes image. Will test and merge this when I have time.
> collect Prometheus HTTP metrics to limes-serve

- openstack/swift/templates/etc/_nginx.conf.tpl
There were issues with high latency connections and downlaoding large
objects from swift. There disbaling that for now
> [swift] disable http2 in nginx

- openstack/monasca/templates/etc/monasca-agent/conf.d/_prometheus.yaml.tpl
Adding service_type : hypervisor_type, this will helps us distinguish between KVM, QEMU, VMWare.
> Renaming service to service_type

- openstack/limes/templates/seed.yaml
@majewsky: maybe this helps?
added roles, introduced dependencies, refactored the domain role-assignments a bit, so it is visually more obvious in what domains is actually being seeded, enabled cc3test administrators to be resource_admins
> limes-seed

- openstack/swift/templates/_utils.tpl
- openstack/swift/templates/account-caretaker-collect-daemonset.yaml
- openstack/swift/templates/etc/_rsyncd.conf.tpl
- openstack/swift/templates/memcached-service.yaml
- openstack/swift/templates/proxy-deployment.yaml
- openstack/swift/templates/proxy-service.yaml
- openstack/swift/templates/replicators-daemonset.yaml
- openstack/swift/templates/rsyncd-daemonset.yaml
- openstack/swift/templates/servers-daemonset.yaml
- openstack/swift/templates/statsd-exporter-daemonset.yaml
- openstack/swift/templates/workers-daemonset.yaml
- openstack/swift/values.yaml
* statsd_exporter daemonset
* all daemonsets use HostNetwork
* template daemonset_annotation for tolerations
* template statsd_annotation for prometheus scraping
* use prometheus annotation and std container also for proxy
* Remove enable_statsd flag
> [swift] statsd_exporter daemonset and HostNetwork

- global/prometheus/templates/petset.yaml
- global/prometheus/values.yaml
- system/kube-monitoring/charts/prometheus-collector/templates/deployment.yaml
- system/kube-monitoring/charts/prometheus-collector/values.yaml
- system/kube-monitoring/charts/prometheus-frontend/templates/petset.yaml
- system/kube-monitoring/charts/prometheus-frontend/values.yaml
**WIP - DO NOT MERGE**
Prometheus v1.6.x deprecated the flags `-storage.local.memory-chunks` & `-storage.local.max-chunks-to-persist` in favor of `-storage.local.target-heap-size`.
https://prometheus.eu-de-1.cloud.sap/graph?g0.range_input=1h&g0.expr=container_memory_usage_bytes%7Bpod_name%3D~%22prometheus-.*%22%7D%2F1024%2F1024%2F1024&g0.tab=1 could give us an indication what could be reasonable values here. 
What do you think @BugRoger?
> bump prometheus to v1.6.1

- openstack/keystone/templates/etc/_keystone.conf.tpl
- openstack/keystone/values.yaml
See https://docs.openstack.org/developer/keystone/event_notifications.html#opting-out-of-certain-notifications
Automatically excluded are:
"identity.authenticate.success"
"identity.authenticate.pending"
"identity.authenticate.failed"
However, we see that a large number of messages are coming
through with type "identity.authenticate" and status "success",
which are not automatically excluded. This commit fixes that.
> Keystone: disable "identity.authenticate" CADF notifications

- system/kube-monitoring/charts/prometheus-frontend/networking-dvs.alerts
@auhlig 
Please confirm the below : 
1. Would the region name show-up in the alarm ?
2. I am not sure if $label has to be prefixed to {{kubernetes_pod_name}} lable ?
3. How to add grafana networking-dvs dashboard to the descriptions as created for ALERT KubernetesApiServerLatency.
The staging networking-dvs link is : https://grafana.staging.cloud.sap/dashboard/db/neutron-dvs-agent
> Adding networking-dvs.alerts

- system/kube-monitoring/charts/prometheus-frontend/openstack-nova.alerts
@auhlig 
Below are the changes:
1. Adding kubernetes_pod_name to by clause for DVSPolling Alert, does this confirm the DVS Agent Name will be seen in description as defined ?
2.(min(rate(openstack_networking_dvs_plugins_ml2_drivers_mech_dvs_agent_dvs_agent_process_ports_timer_count[5m]))) had a missing left parenthesis while executing this in prometheus. will this execute fine now ?
3. is there a hierarchal flow for labels ?is the nova labels file ?
4. Can an alert have both severity as critical & warning ? else do i need to create 2 alerts ?
> Adding Tier, Context labels to the nova alerts

- openstack/swift/charts/swift_drive_autopilot/templates/configmap.yaml
- openstack/swift/charts/swift_drive_autopilot/values.yaml
Allows specifying non default drive globs like:
```
drives:
- "/dev/mapper/mpath[a-z]"
- "/dev/mapper/mpath[a-z][a-z]"
```
> [swift] Drive glob value for swift-drive-autopilot

- global/prometheus-alertmanager/templates/deployment.yaml
- global/prometheus-alertmanager/templates/service.yaml
- global/prometheus-alertmanager/values.yaml
- global/prometheus/values.yaml
- openstack/maia/values.yaml
- system/kube-monitoring/charts/prometheus-collector/values.yaml
- system/kube-monitoring/charts/prometheus-frontend/values.yaml
Will take care next week.
Maybe the update of the AM also solves the issue with the HA setup (**keeps fingers crossed**)
Prometheus 1.7 also introduces (beta) Openstack service discovery which also allows us to discover and scrape targets from Nova instances. [Prometheus docs](https://prometheus.io/docs/operating/configuration/#openstack_sd_config) Do we want to try that @BugRoger? I suggest to do that in the maia prometheus.
> Prometheus v1.7.1 and Prom AM v0.7.1

- openstack/horizon/templates/etc/_local-settings.tpl
Needed to make it easier to retrieve the password of the Administrator user for initial login on Windows.
> allowing Admin session password retrieval/decryption

- openstack/swift/templates/etc/_nginx.conf.tpl
- openstack/swift/values.yaml
Not sure whether this will ever be activated. That will not protect the masters, but at least we can protect the swift backend.
> Rate limiting option for nginx before hitting swift

- openstack/maia/templates/prometheus-deployment.yaml
- openstack/maia/templates/prometheus-pvc.yaml
- openstack/maia/values.yaml
Here you go @jobrs, @thgrs.
Do **not** roll out via the pipeline but via a manual `helm upgrade`, since the pod of the maia-prometheus petset needs to be deleted manually before introducing the deployment. This should recycle the existing pvc.
> convert maia prometheus to deployment

- system/kube-monitoring/charts/prometheus-frontend/README.md
- system/kube-monitoring/charts/prometheus-frontend/blackbox.alerts
- system/kube-monitoring/charts/prometheus-frontend/openstack-swift.alerts
- system/kube-monitoring/charts/prometheus-frontend/templates/_kubernetes.alerts.tpl
- system/kube-monitoring/charts/prometheus-frontend/templates/_node.alerts.tpl
Allows to specify more detailed information in addtion to the alert name,
which can be evaluated later, e.g. in the Alert Overview Dashboard.
That should make the label_remapping in the grafana health overview dashboard obsolete.
I think I found most of the relabels:
- pod
- kubernetes_io_hostname
- check
I could also not find anything obvious, which needs to be done in the alert manager.
> Introduce the meta label for alerts

- global/prometheus/prometheus.alerts
- global/prometheus/templates/_prometheus.yaml.tpl
- global/prometheus/templates/config.yaml
- global/prometheus/values.yaml
Currently the `up`-metric from the collector are federated through the frontend to the global prometheus. The alerting rule is triggered by this metric.
If the frontend is down, but the collector is still up, this will cause an alert, because the federation chain is broken.
Fix: Scrape (only) the up metric from the collector itself and alert on this.
Makes sense @BugRoger?
> Prom collector alerting

- system/kube-monitoring/charts/prometheus-frontend/openstack-cinder.alerts
Hi @auhlig 
Please validate the meta label for OpenstackCinderVolumeAttach, picked this metric since it generates alerts frequently.
> Adding meta label to OpenstackCinderVolumeAttach Metric

- openstack/content-repo/README.md
- openstack/content-repo/templates/job.yaml
With Kubernetes 1.8 there is the improved version of ScheduledJobs
available. The main advantage is that finished (succesful or failed)
jobs are deleted (successfulJobsHistoryLimit, successfulJobsHistoryLimit)
Only deploy them when the capability is available within the cluster and a schedule is specified
> Adding support for CronJobs

- openstack/elektra/templates/_env.tpl
- openstack/elektra/templates/_helpers.tpl
- openstack/elektra/templates/ingress.yaml
- openstack/elektra/values.yaml
(plus a convenience helper for no-conf-required internal keystone traffic, which would be better for the x509 support)
> added elektra ingress x509 SSO enablement 

- system/kube-monitoring/charts/prometheus-frontend/aggregation.rules
@auhlig Can you please merge this when all the frontend Promethei have been updated to 1.8.0? This only works on the newer version because of the usage of the `label_join()` function.
> adjust labels on consolidated Limes metrics

- global/prometheus/templates/_prometheus.yaml.tpl
- system/kube-monitoring/charts/prometheus-frontend/aggregation.rules
Reverts sapcc/helm-charts#213
This federates unaggregated timeseries. Please fix.
> Revert "Adding openstack_compute_instances metric to prometheus-global"

- openstack/arc/templates/api-ingress.yaml
- openstack/elektra/templates/ingress.yaml
- openstack/elektra/templates/secrets.yaml
- openstack/hermes/templates/api-ingress.yaml
- openstack/hermes/templates/api-secret.yaml
- openstack/limes/templates/api-ingress.yaml
- openstack/limes/templates/api-secret.yaml
- openstack/lyra/templates/ingress.yaml
- openstack/maia/templates/maia-ingress.yaml
- openstack/maia/templates/maia-secrets.yaml
- system/kube-system/charts/vice-president/values.yaml
Prepare transition to the vice president by annotating the ingress and, if the secret contains only the tls key,cert, by making it optional. 
Adding the annotation and removing the cert/key from the values in cc/secrets will actually switch the service to the vice-president. I will take care if none of the reviewers objects to the below changes.
> Inauguration round 1

- openstack/limes/templates/seed.yaml
- openstack/swift/templates/seeds.yaml
@ruvr Two questions:
1. I copy-pasted the parts relating to the "bn" domain and did `s/bn/bs/`. A second pair of eyes is much appreciated.
2. The `BS_DOMAIN_RESOURCE_ADMINS` part probably also needs to be set up in CAM. Can you take care, please?
> add new domain "bs" to Limes/Swift seeds

- openstack/utils/templates/_helpers.tpl
By default, log messages are propagated from a child to parent logger, so the root-logger logs everything a second time.
> Do not propagate log messages

- common/redis/templates/configmap.yaml
- common/redis/templates/deployment.yaml
This allows the caller of the chart to specify arbitrary redis configuration parameters.
> [redis] Allow more specific configuration of redis

- openstack/elektra/templates/seed.yaml
As far as I know, this was only used by the legacy resource management implementation and to create Swift accounts. Since Limes now handles both, I don't think anything else in Elektra needs to be a swiftreseller anymore.
@edda Are the above assumptions correct?
@abattye FYI (since your inquiry triggered the line of thought leading to this PR)
> remove Swift dependency from Elektra seed

- openstack/neutron/values.yaml
Hi @fwiesel 
As Neutron chart is independent of openstack-helm now, raising another PR.
> Adding openstack_neutron_monitor_sec_grp metric

- openstack/designate/templates/api-ingress.yaml
vice president won't pickup designate ingress until it's annotated. did designate move out of openstack-helm already in all regions? @dhoeller /cc @Carthaca
> add designate vp annotation

- openstack/swift/templates/seeds.yaml
The ironic user needs swiftoperator role in all the projects the baremetal images are loaded from.
> Swiftoperator role for ironic

- global/prometheus-alertmanager/values.yaml
- system/kube-monitoring/charts/prometheus-collector/values.yaml
- system/kube-monitoring/charts/prometheus-frontend/cluster.rules
- system/kube-monitoring/charts/prometheus-frontend/values.yaml
- system/kube-monitoring/values.yaml
prom v2.1.0 contains the fix for the nfs retention issue, so let's move back to the official img. also upgrade alertmanager. will test in staging on monday before rolling out further
> Prometheus v2.1.0, AM v0.13.0

- openstack/elektra/templates/ingress.yaml
- openstack/elektra/values.yaml
obviously we have to turn on `ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream` using the new ingress controller to enable sso again. off by default. enable only via regional values. i'll take care.
objections @edda?
/cc @ruvr
> fix sso with new ing ctrl

- openstack/grafana/templates/_grafana.ini.tpl
- openstack/grafana/templates/grafana-ingress.yaml
- openstack/grafana/values.yaml
- system/kube-system/charts/ingress/templates/ingress-cacrt-secret.yaml
- system/kube-system/charts/ingress/values.yaml
This PR enables authentication to Grafana via SSL client certificates. It subs out
the basic auth with proxy auth. Grafana now expects the user to be
passed in via the `X-Remote-User` header. This can be toggled with the
`tls_client_auth.enabled` flag in the Helm values. It defaults to off
and keeps things as they are.
The ingress is configured to verify SSL certificates using the
`nginx.ingress.kubernetes.io/auth-tls-*` annotations. This can be turned
on/off per ingress spec.
Additionally, this PR injects a bit of logic into the ingress config, to
copy the relevant part (the user-id) into the `X-Remote-User` header.
> Enables SSL Client Certificate Authentication for Grafana

- openstack/manila/values.yaml
Hi @Carthaca 
Please validate the changes:
share_type_id column is removed from shares table
prefix share_snapshots to size to overcome error in openstack_manila_snapshot metric
> Editing Metrics to support Pike release

- openstack/swift/templates/_utils.tpl
- openstack/swift/templates/etc/_proxy-server.conf.tpl
- openstack/swift/values.yaml
The image_version value is now be expected following that format:
`<openstack_release_name>-<image_version>`
Based on the OpenStack release name the intended pipeline and needed
filters are defined in `templates/etc/_proxy-server.conf.tpl`
> [swift] changed image_version handling

- system/kube-monitoring/charts/prometheus-collector/templates/_prometheus.yaml.tpl
The two phased check is necessary because the evaluation fails if `blackbox_exporter` does not exist.
Solves this https://github.com/sapcc/helm-charts/pull/269#discussion_r176355664
> Skip tcp probe if targets are not set

- system/kube-monitoring/charts/prometheus-collector/templates/_prometheus.yaml.tpl
This is to quickly filter through the probes without using the
jobname as the source of truth for the kind of query that happened.
Because it might be outdated and not reflecting the actual module used,
limits potential names for probe jobs and it uncomfortable query by regex.
> add module label to probe metrics

- openstack/elk/templates/fluent-daemonset.yaml
- openstack/elk/templates/fluent-systemd-daemonset.yaml
- openstack/swift/templates/replicators-daemonset.yaml
- openstack/swift/templates/rsyncd-daemonset.yaml
- openstack/swift/templates/servers-daemonset.yaml
- openstack/swift/templates/statsd-exporter-daemonset.yaml
- openstack/swift/templates/workers-daemonset.yaml
- system/kube-monitoring/charts/node-exporter/templates/daemonset.yaml
- system/kube-monitoring/charts/ntp-exporter/templates/daemonset.yaml
- system/kube-system/charts/container-linux-update-orchestrator/templates/update-agent.yaml
- system/kube-system/charts/node-problem-detector/templates/daemonset.yaml
- system/kube-system/charts/sysctl/templates/sysctl_ds.yaml
Now possible since we are on k8s 1.7 in all regions.
To roll this out:
1. Merge this PR.
2. Deploy all regions once with the old Concourse task (the one that does rolling upgrade manually).
3. When deployed, adjust the Concourse task to not do its own rolling upgrade, but use `k rollout status` instead. This needs coordination with @auhlig who is also using the Concourse task with daemonsets in kube-monitoring.
> [swift, elk, kube-mon.] use native k8s rolling update for daemonsets

- global/prometheus/interconnect.alerts
The idea is to have critical alerts when a lot of regions can’t connect
and a warning if one region can’t connect so that we have less alert fatigue.
The critical alert is not yet set critical because I don’t want to let
it loose over the weekend.
> Add interconnect alerts

- openstack/swift-utils/templates/seed.yaml
- openstack/swift/templates/etc/_dispersion.conf.tpl
- openstack/swift/templates/seeds.yaml
cc3test will be taken over by CAM, so we cannot provision users into there anymore.
> move the swift-dispersion user into Default

- openstack/neutron/templates/deployment-secgroup-entanglement-exporter.yaml
This adds the [security group entanglement exporter](https://github.com/sapcc/secgroup-entanglement-exporter) to the Neutron chart. The exporter generates a metric called "security group entanglement" that can be used to alert customers with security group setups that strain the DVS agent.
- The image for the exporter is produced by the openstack-neutron pipeline which I extended for this purpose.
- I added `.Values.secgroup_entanglement_exporter.image_tag` to all values files for all regions in cc/secrets, so no further action is required; this can be merged and deployed directly if you like.
cc @fwiesel to make him aware of the existence of the exporter
> deploy secgroup-entanglement-exporter

- openstack/swift/templates/_utils.tpl
- openstack/swift/templates/etc/_nginx.conf.tpl
- openstack/swift/templates/etc/_object-server.conf.tpl
- openstack/swift/templates/etc/_proxy-server.conf.tpl
- openstack/swift/values.yaml
Allows to avoid 408 client timeout occured by VMware snapshot creation process
> Add "client_timeout" option

- openstack/swift/templates/etc/_object-server.conf.tpl
- openstack/swift/templates/etc/_proxy-server.conf.tpl
- openstack/swift/values.yaml
* Increase S3 compatibility by additional allowed object headers
* bubble up s3 api switch and only deploy it on the seed cluster
> [swift] S3 API - Additional object server headers

- openstack/neutron/templates/etc/_neutron.conf.tpl
Listing 100 ports takes 4.5 seconds. Listing 500 ports takes just over 20 seconds. Listing more than that runs into the Ingress' timeout of 30 seconds. I ran into this problem with the DVS agent load test, where even `openstack port list` started running into 504 Gateway timeout at a sufficient size.
> set pagination_max_limit for Neutron

- openstack/swift/templates/etc/_nginx.conf.tpl
Log format is negotiable.
JFYI: Since [nginx 1.11.8](https://nginx.org/en/docs/http/ngx_http_log_module.html#log_format) it is possible to use pure json format with proper escaping.
> Add more fields for nginx access log

- openstack/swift/templates/support_seed.yaml
* Externalize seeding of support team permissions into seperate seed
to keep the main seed clear
* As the seeding looks more or less equal acroos the domains, do
some templating around it
//cc @ruvr
> [swift] support team seed

- openstack/arc/charts/postgresql/values.yaml
backup-tools:v0.5.14 has the following improvements for the backup-restore utility:
* backup-restore prints out the executed statements from the dump file,
* backup-restore keeps the restored dumpfile in `/tmp/newbackup<random>` for possible
Please merge and deploy on your own. Consider the postgres pod restart caused by that.
> [openstack][arc] bump backup image version

- openstack/lyra/charts/postgresql/values.yaml
backup-tools:v0.5.14 has the following improvements for the backup-restore utility:
* backup-restore prints out the executed statements from the dump file, 
* backup-restore keeps the restored dumpfile in `/tmp/newbackup<random> for possible 
Please merge and deploy on your own. Consider the postgres pod restart caused by that.
> [openstack][lyra] bump backup image version

- openstack/limes/charts/postgresql/values.yaml
backup-tools:v0.5.14 has the following improvements for the backup-restore utility:
* backup-restore prints out the executed statements from the dump file, 
* backup-restore keeps the restored dumpfile in `/tmp/newbackup<random> for possible 
Please merge and deploy on your own. Consider the postgres pod restart caused by that.
> [openstack][limes] bump backup image version

- openstack/elektra/charts/postgresql/values.yaml
backup-tools:v0.5.15 has the following improvements for the backup-restore utility:
* backup-restore prints out the executed statements from the dump file, 
* backup-restore keeps the restored dumpfile in `/tmp/newbackup<random> for possible 
backup-tools:v0.5.15 has the following improvements for the backup utility:
* only write success timestamps to prometheus if there was actually a success
Please merge and deploy on your own. Consider the postgres pod restart caused by that.
> [openstack][elektra] bump backup image version

- openstack/swift/etc/watcher.yaml
- openstack/swift/templates/etc/_proxy-server.conf.tpl
- openstack/swift/templates/etc/configmap.yaml
- openstack/swift/values.yaml
Add watcher middleware to pipeline once installed. Watcher is turned off by default and enabled via regional/cluster values.
> Add watcher middleware to swift

- common/mariadb/values.yaml
backup-tools:v0.5.15 has the following improvements for the backup-restore utility:
* backup-restore prints out the executed statements from the dump file, 
* backup-restore keeps the restored dumpfile in `/tmp/newbackup<random> for possible 
backup-tools:v0.5.15 has the following improvements for the backup utility:
* only write success timestamps to prometheus if there was actually a success
Please merge and deploy on your own. Consider the mariadb pod restart caused by that.
> [common][mariadb] bump backup image version

- system/kube-monitoring/charts/prometheus-frontend/openstack-swift.alerts
The "meta" attribute is shown on the alert dashboard, but summary/description are not shown. I adjusted phrasing in some placed to be more succinct because of the limited space in the alert dashboard's table.
> add "meta" attribute all Swift alerts

- openstack/neutron/templates/etc/_neutron.conf.tpl
This will configure the olso.cache module, which isn't directly used in neutron, but I would like to make use of it to avoid calls in the arista driver.
> [neutron] Configure olso.cache

- openstack/manila/templates/etc/_manila.conf.tpl
As far as I can see, it isn't directly used, but belongs to the standard set of libraries and might be indirectly used.
> [manila] Configure oslo.cache

- openstack/designate/templates/etc-configmap.yaml
- openstack/designate/templates/etc/_api-paste.ini.tpl
- openstack/designate/templates/etc/_watcher.yaml.tpl
- openstack/designate/values.yaml
Activated via regional values. prerequisite: installed watcher middleware. 
Looks good to you @dhoeller?
> add watcher middleware to designate. disabled by default.

- common/pgmetrics/templates/deployment.yaml
- common/pgmetrics/values.yaml
- common/postgresql/templates/deployment.yaml
- common/postgresql/templates/etc/_postgresql.conf.tpl
- common/postgresql/values.yaml
updates the metrics exporter to current version
exposes replication metrics for the clustered instances
> adds support for the pg_stat_statements extension

- openstack/manila/templates/api-deployment.yaml
- openstack/manila/templates/api-service.yaml
- openstack/manila/values.yaml
Else metrics of {ops, watcher, audit}-middleware are sent into nirvana. LGTY @Carthaca?
> add statsd container to manila api

- openstack/ironic/templates/api-deployment.yaml
- openstack/ironic/templates/etc-configmap.yaml
- openstack/ironic/templates/etc/_ironic.conf.tpl
- openstack/ironic/templates/etc/_watcher.yaml.tpl
- openstack/ironic/values.yaml
**NOTE:** requires https://github.com/sapcc/ironic/pull/3 before the watcher can be enabled. /cc @fwiesel
> add openstack-watcher-middleware to ironic. disabled by default

- global/prometheus-alertmanager/templates/config.yaml
We avoid the double filter, have much less complexity and we avoid accidental loss if we introduce new regions or clusters.
Please double check if you also think it will work as intended, I am not completely sure if I overlooked something.
> Reduce routing complexity

- global/prometheus-alertmanager/templates/config.yaml
- global/prometheus-alertmanager/values.yaml
Will merge tomorrow to avoid retriggering alerts during the night.
Routing and channels would for a pagerduty receiver would be generated by a snippet like:
```yaml
pagerduty_services:
- name: baremetal
service_key: DEFINED-IN-SECRETS
match:
service: ironic
tier: baremetal
```
> configurable pagerduty routing and channels via values

- system/kube-monitoring/charts/prometheus-collector/templates/_prometheus.yaml.tpl
This PR was mostly made to ensure that there are no typos.
The beforehand used name was anyway overwritten by the value 'baremetal/ironic' provided by the ipmi_sd service discovery.
Because we want to drop the label there, we have to change it here so that nothing changes for the metric’s consumers.
This change is necessary to unblock this PR:
https://github.com/sapcc/ipmi_sd/pull/7
> generic name 'baremetal/ironic' for ipmi job

- system/kube-monitoring/charts/prometheus-frontend/baremetal-ironic.alerts
too many warnings as of now. They would flood the grafana dashboard with new warnings
> [kube-monitoring] disables baremetal ironic warnings

- openstack/octobus/templates/seeds.yaml
- [Roles definition](https://github.com/businessbean/helm-charts/blob/5f849a48a98f6593921a6eccefef0fa8fd2736b7/openstack/octobus/templates/seeds.yaml#L39) for a regional service user based on CAM technical users
- use dns_zonemaster instead of dns_webmaster for self service sub domain management
> [octobus] regional service user

- global/prometheus-alertmanager/templates/config.yaml
- global/prometheus-alertmanager/values.yaml
**Do not merge**
Changes pagerduty alerts from `severity: critical` to a set of alertnames. Also allows regexes. 
Example: Only alert when many things are down
```
alerts:
- .*ManyDown
```
As discussed - WDYT @BugRoger?
TODO before merging:
> Rework alertmanager routing

- openstack/grafana-new/templates/_nginx.conf.tpl
- openstack/grafana-new/templates/grafana-deployment.yaml
- openstack/grafana-new/templates/grafana-etc-configmap.yaml
- openstack/grafana-new/templates/grafana-service.yaml
- openstack/grafana-new/templates/nginx-ingress.yaml
- openstack/grafana-new/values.yaml
This allows (optional) deployment of a grafana sidecar that contains a nginx server, that allows authentication-less display of dashboards.
the new ingress can be used for digital signage displays.
> added kiosk mode (nginx sidecar) for digital signage displays

- openstack/keystone/values.yaml
I would like to monitor that restricted roles like `resource_service` and `swiftreseller` do not get assigned to users and groups that I'm not aware of. I thought about writing an exporter that queries the Keystone API
for role assignments, but I guess it's way more efficient to just add a rule to the pgmetrics exporter of the Keystone DB.
@ruvr Opinions?
> add openstack_assignments_per_role metric to Keystone pgmetrics

- openstack/sap-seeds/templates/flavor-seed.yaml
Added the following flavors with 1:4 ratio:
m5.16xlarge
vCPU: 64
RAM: 256
m5.32xlarge
vCPU: 128
RAM: 512
m5.64xlarge
vCPU: 256
RAM 1024
Bye,
Frank
> added three new flavors with 1:4 ratio

- system/kube-monitoring/charts/prometheus-frontend/openstack-designate.alerts
Reverts sapcc/helm-charts#508
This breaks the pipline with error:
```
Checking helm-charts.git/system/kube-monitoring/charts/prometheus-frontend/openstack-designate.alerts
FAILED:
group "openstack-designate.alerts", rule 3, "OpenstackDesignateDnsUnboundEndpointNotAvailable": could not parse expression: parse error at char 61: could not parse remaining input "BY (region, end"...
group "openstack-designate.alerts", rule 4, "OpenstackDesignateDnsUnbound1Down": could not parse expression: parse error at char 53: could not parse remaining input "BY (region)"...
group "openstack-designate.alerts", rule 5, "OpenstackDesignateDnsUnbound2Down": could not parse expression: parse error at char 53: could not parse remaining input "BY (region)"...
```
> Revert "[alerts][designate] Alert if Unbound is down / not reporting metrics."

- openstack/backup-cleanup/Chart.yaml
- openstack/backup-cleanup/README.md
- openstack/backup-cleanup/bin/cleanup
- openstack/backup-cleanup/bin/exponential-backoff
- openstack/backup-cleanup/bin/sleep-for
- openstack/backup-cleanup/templates/bin-configmap.yaml
- openstack/backup-cleanup/templates/cleanup-deployment.yaml
- openstack/backup-cleanup/values.yaml
The periodic triggered script, will cleanup backup segments of static large
objects in Swift, because the segments are not marked for expirations. The
object expirer only remover the manifest files of the SLOs.
> cleanup deployment for expired slo backup segments

- global/prometheus-alertmanager/pagerduty.tmpl
- global/prometheus-alertmanager/slack.tmpl
- global/prometheus-alertmanager/templates/config.yaml
- system/kube-monitoring/charts/prometheus-frontend/README.md
- add cloudops link
- region should always be the openstack region
- introduce `cluster_type` to distinguish between bm, kubernikus, scaleout, .. clusters. no paging for kubernikus, scaleout clusters
> alerting: add cloudops link; region should always be the openstack region

- system/kube-monitoring/charts/oomkill-exporter/Chart.yaml
- system/kube-monitoring/charts/oomkill-exporter/templates/_helpers.tpl
- system/kube-monitoring/charts/oomkill-exporter/templates/daemonset.yaml
- system/kube-monitoring/charts/oomkill-exporter/values.yaml
- system/kube-monitoring/charts/prometheus-frontend/kubernetes-oomkill.alerts
This PR adds the oomkill exporter chart to kube-monitoring. See https://github.com/sapcc/kubernetes-oomkill-exporter for more details on the exporter.
> Adds oomkill exporter

- system/kube-monitoring/charts/event-exporter/Chart.yaml
- system/kube-monitoring/charts/event-exporter/templates/_helpers.tpl
- system/kube-monitoring/charts/event-exporter/templates/clusterrole.yaml
- system/kube-monitoring/charts/event-exporter/templates/clusterrolebinding.yaml
- system/kube-monitoring/charts/event-exporter/templates/configmap.yaml
- system/kube-monitoring/charts/event-exporter/templates/deployment.yaml
- system/kube-monitoring/charts/event-exporter/templates/serviceaccount.yaml
- system/kube-monitoring/charts/event-exporter/values.yaml
This PR adds kubernetes event exporter chart to kube-monitoring. See https://github.com/sapcc/kubernetes-eventexporter for details.
> Add event exporter chart

- system/kube-monitoring/charts/event-exporter/templates/clusterrole.yaml
- system/kube-monitoring/charts/event-exporter/templates/clusterrolebinding.yaml
- system/kube-monitoring/charts/event-exporter/values.yaml
With this PR rbac rules can be disabled in values file for eventexporter.
> Make rbac roles in eventexporter optional

- system/kube-monitoring/charts/prometheus-collector/aggregation.rules
It would be nice to have some longer period of cpu metrics also sliced by containers within a pod.
Please deny this PR if it is as it is for a reason...
> [prometheus] save container cpu metrics of pods

- openstack/neutron/templates/etc/_dnsmasq.conf.tpl
Logging the dhcp request allows us to debug if the vm/baremetal node at least managed to get network connectivity.
The file is also not rotated, so we end up with hundreds of MBs of log-files
> [neutron] Log dnsmasq to stdout

- global/prometheus-alertmanager/templates/config.yaml
This should avoid reporting kubernikus alerts in the channels used for the baremetal control plane for now.
> Add cluster_type to alert routing

- system/kube-monitoring/charts/ironic-exporter/templates/deployment.yaml
- system/kube-monitoring/charts/ironic-exporter/values.yaml
adds ap-jp-2 to list of ignored regions
> [kube-monitoring] bumps ironic-exporter version

- global/prometheus-alertmanager/templates/config.yaml
Reintroduces the functionality to inhibit on `context`. Here we are guarding the inhibition of alerts without `context` by using a regex matcher for a non-empty `context`.
Additionally, I removed the `context` from `alertname` inihibition, as this didn't work. The point of `context` is to group alerts with different names. So, by definition that did nothing.
I also noticed that the `info` inhibition should not work at all. There's an regex for `severity` in a non-regex matcher.
> add context inhibition

- system/kube-monitoring/charts/prometheus-collector/templates/_prometheus.yaml.tpl
Requested by Martin Vossen.
In a second step it would be good to overwrite the value of the label
component for the snmp-exporter source with the actual component
involved, e.g. "f5", or an abstract category, e.g. "loadbalancer".
> Added device and availability_zone label for snmp

- system/kube-monitoring/charts/prometheus-frontend/templates/config.yaml
- system/kube-monitoring/charts/prometheus-frontend/templates/deployment.yaml
This change defaults the `cluster` label to `region`. With this change every deployment of `tube-monitoring` has three labels: `region`, `cluster_type`, and `cluster`.
I also removed the `regionPrefix` annotations which we are not using anymore.
> Default cluster label to region, remove unused regionPrefix

- openstack/hermes/templates/etc/_logstash.conf.tpl
- system/kube-monitoring/charts/prometheus-frontend/openstack-hermes.alerts
Moving to monthly indexes. The currently daily indexes provide us no value, and cause significant problems around number of shards. We cannot backup properly in this situation, we cannot do a mass export successfully. 
The biggest negative of monthly is that if we need to delete older data to fit into volume sizes, we will always need to be ahead of the need by 2 months. In our largest regions we are making it to 7+ months before this. It will still need to be watched, alerted on, and acted on in a timely manner to make sure we don't get into a bad state. But I think the need for proper backups is a larger concern in this context.
> [hermes] move to monthly indexes

- openstack/nova/templates/hypervisors/hypervisors-vmware-configmap-vct.yaml
since it's not used by the DVS driver and breaks the NSX-T driver
@joker-official @Scsabiii
> [nova-compute-node] disable integration bridge

- global/prometheus-alertmanager/slack.tmpl
With go 1.11 its possible to re-assign template variables from higher scopes. This allows us to copy the GeneratorURL from the alerts to the outer template.
> Reintroduce GeneratorURL

- global/prometheus-alertmanager/slack.tmpl
This commit fixes a problem where resolved alerts are surpressed by still firing alerts.
The subject line now carries both in sections in that case:
e.g.
```
*[CRITICAL - 2]* *[RESOLVED - 1]* *[EU-DE-1]* SomeSillyAlert - Something silly happend
:fire: alert1
:fire: alert2
:white_check_mark: recovered alert
```
> Mixed (firing/resolved) slack notifications

- global/prometheus-alertmanager/slack.tmpl
- global/prometheus-alertmanager/templates/config.yaml
This commit changes the color of the slack notification when it contains both firing and resolved alerts from read (danger) to yellow (warning).
In a lot of cases a notification that carries a "resolved" and "firing" alert is an improvment: Some alerts have cleared while others are still firing. Marking them as yellow makes them easily distingushibale from alerts that only contain "firing" alerts which are never good.
> Use yellow color for mixed notifications

- openstack/blackbox/charts/blackbox-tests-canary/templates/deployment.yaml
- openstack/blackbox/values.yaml
Hi, I suggest to use the internal endpoint for the tests to remove the extra hop over ingress.
We don't want to test ingress, only manila api.
I replaced OS_VOLUME_API_VERSION, which is not used in this context
> [blackbox][manila] add OS_MANILA_ENDPOINT_TYPE with default internal

- system/kube-system/charts/disco/templates/clusterrolebinding.yaml
- system/kube-system/charts/disco/templates/config.yaml
- system/kube-system/charts/disco/templates/deployment.yaml
- system/kube-system/charts/disco/templates/rolebinding.yaml
- system/kube-system/charts/disco/templates/seed.yaml
- system/kube-system/charts/disco/values.yaml
The Disco operator is currently deployed in the scaleout clusters and requires an OpenStack user that is able to manage Designate records. This user shall be created via an OpenstackSeed.
However, AFAIK there's no openstack-seeder there to do the magic.
So there's a more general question for which I see 2 options:
(1) Deploy the Openstack seeder to the scaleout clusters.
(2) Openstack seeder just in controlplane. Means: One has to split charts. Seeds only in baremetal. Rest of the deployment in scaleout.
What do you think @ruvr, @BugRoger, @databus23?
> Adds OpenstackSeed for DISCO (Designate IngresS Cname Operator) user

- system/kube-monitoring/requirements.lock
- system/kube-monitoring/requirements.yaml
- system/kube-monitoring/templates/fluent-bit-config.yaml
- system/kube-monitoring/values.yaml
This PR adds the fluent-bit chart to kube-monitoring. It is for logging container and systemd messages into elasticsearch. For now this is focused on the scaleout klusters but should work everywhere.
> [kube-monitoring] Add fluent-bit chart

- system/kube-monitoring/values.yaml
* switch back to official container image as https://github.com/prometheus/node_exporter/pull/1098 was merged
* enable service unit tasks metrics
* fixes https://github.com/prometheus/node_exporter/issues/1049 - broken disk stats on 4.19
> [kube-monitoring] Update to prom/node-exporter:v0.17.0

- openstack/maia/templates/maia-ingress.yaml
- openstack/maia/templates/prometheus-deployment.yaml
- openstack/maia/templates/prometheus-service.yaml
- openstack/maia/values.yaml
To avoid confusion I merged the "prometheusv2" config section with the "prometheus" one. On that occasion I switched the volume type to RWO (less error prone).
For upcoming Prometheus versions, we will use another approach for upgrading Prometheus based on Arnos work on the P8S operator.
> merge prometheusv2 and prometheus config trees and make P8S volume RWO

- system/sentry/templates/_seed.py.tpl
I'd like the admin user to also be able to view events and issues. Note that I didn't run a test-deployment with this.
> Allow sentry admin user to read events when seeding sentry

- system/infra-monitoring/vendor/netapp-exporter/templates/netapp-graphite-db.yaml
- system/infra-monitoring/vendor/netapp-exporter/values.yaml
graphite-db in production region can take ~10GB mem
> [infra-monitoring][netapp] set graphite-db replicas to 0

- openstack/manila/templates/api-deployment.yaml
- openstack/manila/templates/nanny-deployment.yaml
- openstack/manila/templates/scheduler-deployment.yaml
- openstack/manila/templates/shares/_netapp-deployment.yaml.tpl
- openstack/manila/templates/shares/_netapp-nanny-deployment.yaml.tpl
- openstack/manila/values.yaml
values defined by looking at our GOLD regions
all deployments but manila-share can scale horizontally with the number of pods
> [manila] add resources requests

- global/prometheus-alertmanager/templates/config.yaml
0. stricter structure
1. less dynamic channel naming - why: simply reduce risk of non delivered messages (metric: alertmanager_notifications_failed_total)
2. Differ between Duty (alert) Channels and Notification Channels (some clean up needed to have no overlap)
3. Notification channels should have an owner which also defines filter on labels - contact if you wanna adopt something
4. dev-null get’s all the non-configured stuff
- add a alertchain test routing for pager duty
- add a cc-nanny channel
- concourse routes now to an existing channel
- made the webhooks required
- Discussion on changes were done on previous pull request https://github.com/sapcc/helm-charts/pull/634 (unfortunately killed by rebase on old master) 
- Second PullRequest is formal 
- want to merge on 22nd of March by …
> Larger channel clean up and restructuring

- system/kube-monitoring/charts/prometheus-collector/aggregation.rules
- system/kube-monitoring/charts/prometheus-frontend/templates/config.yaml
Federate completely-fair-scheduler metrics from prometheus-collector to frontend, so that you can visualize CPU utilization and limits in Grafana. This helps fine-tuning those limits and may later be used  to discover starvation caused by outdated limits.
> P8s monitor cpulimits

- system/prometheus-operator/.helmignore
- system/prometheus-operator/Chart.yaml
- system/prometheus-operator/requirements.lock
- system/prometheus-operator/requirements.yaml
- system/prometheus-operator/values.yaml
Chart for prometheus operator. Allows deployment independent from kube-monitoring. 
Prometheis, Rule CRDs and config will be a separate PR
> init prometheus operator

- openstack/neutron/values.yaml
Liberally adapted from Keystone, where this was fixed here:
https://github.com/sapcc/helm-charts/commit/b7b4181444929bd82c4a4de49f0a1d5bf9a2c2ba
> Use Postges with Flock Protection

- openstack/maia/templates/maia-deployment.yaml
- openstack/maia/values.yaml
for the maia app
lessons learned
- memory spikes can be shorter than the sampling interval not just in theory
- once throttling kicks in, the _throttled_ cpu seconds metrics is orders of magnitude higher than the cpu seconds metric (is this a problem with the measurement?)
> Maia resource limits

- openstack/neutron/templates/etc/_neutron-policy.json.tpl
- openstack/neutron/templates/seed.yaml
securitygroup_viewer -> can show / list security groups and their rules
securitygroup_admin -> can create / update / delete security groups and security group rules
I have modified our initial config.
> Two new roles for security group administration:

- system/kube-monitoring/charts/prometheus-frontend/metal-ironic.alerts
info alerts now catch all the error types independent from maintenance state
> [kube-monitoring] updates ironic hw alerts

- openstack/elektra/templates/ingress.yaml
This is a left-over from the stoneage. Other services use the SSO CA(s) found in secret `kube-system/ingress-cacrt`, so should elektra. 
Are you okay with this @edda, @andypf?
> elektra shall use kube-system/ingress-cacrt like other services

- system/exporter/nfs-exporter/Chart.yaml
- system/exporter/nfs-exporter/templates/deployment.yaml
- system/exporter/nfs-exporter/templates/secret.yaml
- system/exporter/nfs-exporter/values.yaml
- system/exporter/systemd-lldp-exporter/Chart.yaml
- system/exporter/systemd-lldp-exporter/templates/deployment.yaml
- system/exporter/systemd-lldp-exporter/values.yaml
I did not know the correct location please advise if this looks good to you and we reference these with requirements in the future
> Add additional exporters outside of kube-monitoring as it is currently refactored

- system/infra-monitoring/requirements.yaml
- system/infra-monitoring/templates/_prometheus.yaml.tpl
- system/infra-monitoring/values.yaml
- The file repository doesn't support versioning. Switch to charts.eu-de-2.cloud.sap for prometheus-server chart. 
**NOTE**: Pipelines need to do a `helm repo add sapcc https://charts.eu-de-2.cloud.sap` before updating dependencies.
- Prometheus server image is defined in base chart. Removed setting here to avoid fragmentation. Prometheus should be updated via the chart version.
- The annotation `__meta_kubernetes_service_annotation_prometheus_io_targets` shall be used to define a target prometheus for k8s resources discovered via service discovery. It's value is a comma-separated list of names of prometheus server instances. The idea to have a Prometheus server only scrape metrics that are deemed relevant for the intended use.
Example: …
> Infra prometheus alignment

- openstack/maia/requirements.lock
- openstack/maia/requirements.yaml
- The file repository doesn't support versioning. Switch to charts.eu-de-2.cloud.sap for prometheus-server chart. 
**NOTE**: Pipelines need to do a `helm repo add sapcc https://charts.eu-de-2.cloud.sap` before updating dependencies.
> use prometheus-server@charts.eu-de-2.cloud.sap

- global/concourse/templates/cleanup-cronjob.yaml
- global/concourse/templates/daemonset.yaml
Currently when a worker node is rebootet the init containers reformat the disk (because it is not mounted anymore) which causes inconsistencies when the worker comes back with the same name and no volumes.
> Concourse fixes

- openstack/neutron/templates/etc/_neutron_audit_map.yaml
- openstack/nova/templates/etc/_nova_audit_map.yaml.tpl
This refinement of the audit mapping files brings a few minor extensions
* refined mappings of some API details
* tag extensions for resources (neutron, nova)
On that occasion the audit-middleware should be updated to latest. That depends on https://github.com/sapcc/openstack-audit-middleware/pull/37
> extend audit event mapping rules for new OS version

- openstack/limes/aggregations/consolidation.rules
- openstack/limes/alerts/api.alerts
- openstack/limes/alerts/pod.alerts
- openstack/limes/alerts/roleassignment.alerts
- openstack/limes/templates/api-service.yaml
- openstack/limes/templates/prometheus-aggregations.yaml
- openstack/limes/templates/prometheus-alerts.yaml
- openstack/limes/values.yaml
Our new monitoring architecture allows independent deployment of Prometheus alerts and aggregation rules rather than having them in a crowded central pipeline.
This PR uses a `PrometheusRule` to deploy limes specific alerts and aggregations.
For now it will deploy the alerts, rules in addition to the existing ones (but without double alerting). 
Will contact you on thursday @majewsky
> independent limes alerts

- global/prometheus-openstack/templates/_prometheus.yaml.tpl
- openstack/swift/aggregations/swift-usage.rules
- openstack/swift/alerts/swift-api.alerts
- openstack/swift/alerts/swift-pod.alerts
- openstack/swift/alerts/swift-roleassignments.alerts
- openstack/swift/templates/_utils.tpl
- openstack/swift/templates/prometheus-aggregations.yaml
- openstack/swift/templates/prometheus-alerts.yaml
- openstack/swift/values.yaml
Our new monitoring architecture allows independent deployment of Prometheus alerts and aggregation rules rather than having them in a crowded central pipeline.
This PR uses a PrometheusRule to deploy swift specific alerts and aggregations.
For now it will deploy the alerts, rules in addition to the existing ones (but without double alerting).
Will contact you on thursday @reimannf.
> independent swift alerts

- system/kube-monitoring/values.yaml
This PR fixes exposure of filesystems within node exporter and adds `tmpfs` to ignored fs types. Without this not all devices/partitions are exposed. It also fixes an argument escaping issue.
> Fix node exporter filesystem

- openstack/neutron/templates/etc/_dhcp-agent.ini.tpl
The dhcp_domain option has been deprecated and now dns_domain is used.
We'll keep dhcp_domain in the helm charts until all regions are
upgraded to our newest neutron release.
> Add dns_domain config option

- global/prometheus-infra/README.md
- global/prometheus-infra/templates/_prometheus.yaml.tpl
Instead of maintaining the list of metrics that are federated from the regional prometheis to the global infra prometheus, this PR adds support for automatic federation of all metrics prefixed with `global:`. 
also adds basic documentation.
LGTY @artherd42
> federate global metrics

- global/prometheus-alertmanager/templates/config.yaml
The corresponding Slack channel (`#cc-os-castellum`) was already created.
> add castellum to alertmanager config

- common/postgresql/Chart.yaml
- common/postgresql/templates/_helpers.tpl
- common/postgresql/templates/alerts/_backup.alerts.tpl
- common/postgresql/templates/backup-alerts.yaml
- common/postgresql/templates/pgbouncer-deployment.yaml
- common/postgresql/templates/svc.yaml
- common/postgresql/values.yaml
As discussed @reimannf. Let's review tomorrow.
The postgresql chart should provide a set of generic Prometheus alerts via `PrometheusRule` custom resource. Alerts are templated and tied to the application using this chart.
> Common Postgresql chart with default Prometheus alerts

- common/mariadb/templates/_helpers.tpl
- common/mariadb/templates/alerts/_backup.alerts.tpl
- common/mariadb/templates/backup-alerts.yaml
- common/mariadb/templates/deployment.yaml
- common/mariadb/templates/secret.yaml
- common/mariadb/templates/service.yaml
- common/mariadb/values.yaml
This PR does:
(1) Introduce backup alerts for maria db. Same as in #784.
(2) The alert condition depends on the `app` label, thus it must be consistent and is now generated via a helper.
LGTY @reimannf?
> Mariadb chart with backup alerts

- global/quay/alerts/quay.alerts
- global/quay/templates/alerts.yaml
- global/quay/templates/deployment.yaml
- global/quay/values.yaml
Moves the quay alerts from the kube-monitoring swamp.
The pipeline (if there's one) might need to be extended by a alert validation step a la `promtool check rules helm-charts.git/global/quay/alerts/*.alerts`.
LGTY @databus23?
> Move Quay alerts from to new Prometheus

- openstack/barbican/templates/etc/_barbican-policy.json.tpl
Hi @frr2018,
member role allows the user to view and download the secrets\payloads, hence removing this role. It worked fine in QA, with appl user. Anton confirmed it works well the way it should.
Regards,
Rajiv
> [Barbican] Removing _member_ role

- system/kube-monitoring/charts/prometheus-frontend/admin-etcd-backup.alerts
- system/kube-monitoring/charts/prometheus-frontend/templates/config.yaml
This PR adds an alert if any etcd backup is failing in admin cluster.
> Add etcd backup alert for admin cluster

- openstack/elk/templates/etc/_fluent.conf.tpl
Process is used at other places and overwrites this field for
certain containers
> Rename process to logger

- openstack/swift-drive-autopilot/templates/_utils.tpl
- openstack/swift-drive-autopilot/templates/configmap.yaml
- openstack/swift-drive-autopilot/templates/daemonset.yaml
- openstack/swift-drive-autopilot/values.yaml
The `multipath-disks: true` node label constraints `swift-drive-autopilot-multipath` onto these nodes in particular. The `species: swift-storage-multipath` taint forces `swift-drive-autopilot` without `-multipath` off these nodes.
> split swift-drive-autopilot into two daemonsets for plain and multipath

- openstack/nova/templates/hypervisors/hypervisors-vmware-deployment-vct.yaml
- openstack/nova/templates/hypervisors/hypervisors-vmware-neutron-configmap-vct.yaml
- openstack/nova/values.yaml
With the switch to nsx-t, which is deployed by the neutron helm-chart,
we can get rid of the dvs-agent deployment in nova. Setting the variable
`neutron_dvs_agent_enabled` to `False` for a region, removes the
dvs-agent deployment. One might have to manuall delete the deployment of
the nova-compute pod though, because the vcenter-operator is not
supposed to delete stuff and most probably cannot update the deployment.
---
I rendered the template locally and it seems ok to me and also loads via `yaml.load_all()`. Still, I'd like to have someone have another look.
> [nova] Make dvs-agent inclusion configurable

- common/mariadb/templates/deployment.yaml
Currently the secret contains the root password of the maria db but isn't used. What this PR fixes: Uses the maria db root password from the secret.
> [common/mariadb] fix root password from secret

- openstack/limes/aggregations/consolidation.rules
- openstack/limes/alerts/pod.alerts
- system/kube-monitoring/charts/prometheus-collector/aggregation.rules
- system/kube-monitoring/charts/prometheus-frontend/openstack-limes.alerts
The old alert just checked if `predict_linear(memory usage, 8h) > 100%`. This often fires directly after deployments when pods' memory usage quickly rises during their startup, but then flattens out.
To avoid these misfirings, the alert now has a second condition, triggering only for current `memory usage > 70%`. Because the alert expresssion got quite unwieldy, I refactored part of it out into an aggregation rule.
@auhlig I'd appreciate a second pair of eyes checking the alert expressions.
One thing that I'm not sure about is if we want to move the aggregation rule to a more generic place, and have it apply to all containers. These pod-OOM alerts are just copy-pasted all over the place anyway, so it may be helpful to have this aggregated metric available for everyone.
> Limes: make the pod OOM alert less trigger-happy

- openstack/elektra/alerts/api.alerts
- openstack/elektra/alerts/puma.alerts
- openstack/elektra/templates/deployment.yaml
- openstack/elektra/templates/prometheus-alerts.yaml
- openstack/elektra/templates/service.yaml
- openstack/elektra/values.yaml
Move Elektras [existing alerts](https://github.com/sapcc/helm-charts/blob/master/system/kube-monitoring/charts/prometheus-frontend/openstack-elektra.alerts) to the PrometheusRule custom resource and adds the prometheus.io/targets annotation to the service, deployment.
Note that changing the annotation on the deployment causes a restart.
Validated manually.
LGTY @edda, @andypf?
> [Elektra] Move Prometheus alerts to CRD

- openstack/nannies/alerts/cinder/nanny-cinder.alerts
- openstack/nannies/alerts/nova/nanny-nova.alerts
- openstack/nannies/alerts/vcenter/nanny-vcenter.alerts
- openstack/nannies/templates/_neutron-nanny-service.yaml
- openstack/nannies/templates/cinder-nanny-service.yaml
- openstack/nannies/templates/nova-nanny-service.yaml
- openstack/nannies/templates/prometheus-alerts.yaml
- openstack/nannies/templates/vcenter-nanny-consistency-service.yaml
- openstack/nannies/templates/vcenter-nanny-service.yaml
- openstack/nannies/values.yaml
Move Nanny [existing alerts](https://github.com/sapcc/helm-charts/blob/master/system/kube-monitoring/charts/prometheus-frontend/openstack-nanny.alerts) to the PrometheusRule custom resource and adds the prometheus.io/targets annotation to the service.
EDIT: In the CI the nanny should check if the alerts are valid. See other pipelines for inspiration. It's basically just a `promtool check rules alerts/**/*.alerts`
Please make any changes you need @thgrs.
> Nanny alerts to PrometheusRule CRD

- openstack/neutron/alerts/api.alerts
- openstack/neutron/alerts/canary.alerts
- openstack/neutron/alerts/datapath.alerts
- openstack/neutron/alerts/neutron.alerts
- openstack/neutron/templates/asr_config_agents/_deployment-asr1k.yaml.tpl
- openstack/neutron/templates/deployment-secgroup-entanglement-exporter.yaml
- openstack/neutron/templates/nanny-service.yaml
- openstack/neutron/templates/prometheus-alerts.yaml
- openstack/neutron/templates/service-server.yaml
- openstack/neutron/values.yaml
Move Neutrons [existing alerts](https://github.com/sapcc/helm-charts/blob/master/system/kube-monitoring/charts/prometheus-frontend/openstack-neutron.alerts) to the PrometheusRule custom resource and adds the prometheus.io/targets annotation to the service. Validated manually.
Also fix naming of values in [asr1k deployment](https://github.com/sapcc/helm-charts/compare/neutron-alerts?expand=1#diff-7c604d3458cf5b88c166956f9a1f6e5d).
LGTY @abattye @notandy?
> [Neutron] Move Prometheus alerts to CRD

- openstack/designate/alerts/api.alerts
- openstack/designate/alerts/unbound.alerts
- openstack/designate/alerts/zone.alerts
- openstack/designate/templates/api-service.yaml
- openstack/designate/templates/prometheus-alerts.yaml
- openstack/designate/values.yaml
Move Designates [existing alerts](https://github.com/sapcc/helm-charts/blob/master/system/kube-monitoring/charts/prometheus-frontend/openstack-designate.alerts) to the PrometheusRule custom resource and adds the `prometheus.io/targets` annotation to the service. Validated manually.
Can you take a look @frr2018?
> [Designate] Move Prometheus alerts to CRD

- global/concourse/alerts/concourse.alerts
- global/concourse/templates/prometheus-alerts.yaml
- global/concourse/values.yaml
Move Concourse' [existing alerts](https://github.com/sapcc/helm-charts/blob/master/system/kube-monitoring/charts/prometheus-frontend/concourse.alerts) to the PrometheusRule custom resource. `prometheus.io/targets` annotation already present on service.
LGTY @jknipper?
> [Concourse] Move Prometheus alerts to CRD

- openstack/maia/alerts/api.alerts
- openstack/maia/alerts/maia.alerts
- openstack/maia/templates/jumpserver-deployment.yaml
- openstack/maia/templates/maia-service.yaml
- openstack/maia/templates/prometheus-alerts.yaml
- openstack/maia/templates/prometheus-service.yaml
- openstack/maia/templates/snmp-exporter-service.yaml
- openstack/maia/values.yaml
Move Maias [existing alerts](https://github.com/sapcc/helm-charts/blob/master/system/kube-monitoring/charts/prometheus-frontend/openstack-maia.alerts) to the PrometheusRule custom resource and adds the prometheus.io/targets annotation to the service. Validated manually.
LGTY @thgrs?
> [Maia] Move Prometheus alerts to CRD

- openstack/billing/alerts/api.alerts
- openstack/billing/templates/prometheus-alerts.yaml
- openstack/billing/values.yaml
Move Billing [existing alerts](https://github.com/sapcc/helm-charts/blob/master/system/kube-monitoring/charts/prometheus-frontend/openstack-billing.alerts) to the PrometheusRule custom resource. Validated manually.
> [Billing] Move Prometheus alerts to CRD

- system/kube-monitoring/charts/ns-exporter/alerts/probe.alerts
- system/kube-monitoring/charts/ns-exporter/templates/daemonset.yaml
- system/kube-monitoring/charts/ns-exporter/templates/prometheus-alerts.yaml
- system/kube-monitoring/charts/ns-exporter/values.yaml
Makes the ns-exporter ready for the new prometheus setup. LGTY @databus23?
Note: Changing the annotations will restart the exporter. Will that cause foo/needs coordination?
> [NS-exporter] Move Prometheus alerts to CRD

- openstack/swift/etc/sapcc-ratelimit.yaml
- openstack/swift/requirements.lock
- openstack/swift/requirements.yaml
- openstack/swift/templates/_utils.tpl
- openstack/swift/templates/etc/_proxy-server.conf.tpl
- openstack/swift/templates/etc/configmap.yaml
- openstack/swift/values.yaml
- Introduce [sapcc/openstack-rate-limit-middleware](https://github.com/sapcc/openstack-rate-limit-middleware). Disabled by default. 
- Uses redis backend. No persistence. Only memory. Will be deployed if above middleware is enabled.
-  There shall only be one rate limit middleware: If sapcc rate limit enabled the swift rate limit middleware will be disabled. 
- Rate limits as per [config](https://github.com/sapcc/helm-charts/compare/master...swift-ratelimit?expand=1#diff-a3ed9f52e02b1b6c2848c420565256c6)
**Requires**: https://github.com/sapcc/swift/pull/16
Next steps:
- `staging`, `qa-de-1` rollout + final test
Are you ok with this @reimannf?
> Swift ratelimit

- openstack/swift/requirements.lock
- openstack/swift/requirements.yaml
- openstack/swift/templates/_utils.tpl
- openstack/swift/values.yaml
Redis is not longer a `apps/v1beta2.StatefulSet` but a`Deployment` which allows us to use staging with k8s 1.7.7 again. Common redis chart was updated in #848. 
Test with `rocky` and `stein`.
> [Swift] Redis for ratelimit based on common/redis

- system/kube-monitoring/requirements.lock
- system/kube-monitoring/requirements.yaml
- system/kube-monitoring/values.yaml
Not deploying this in the evening. To be done tomorrow morning. Also bumps `kube-state-metrics` to [v1.6.0](https://github.com/kubernetes/kube-state-metrics/releases/tag/v1.6.0).
> Fix double scraping of metrics

- openstack/lyra/alerts/lyra.alerts
- openstack/lyra/charts/postgresql/templates/svc.yaml
- openstack/lyra/templates/api-deployment.yaml
- openstack/lyra/templates/prometheus-alerts.yaml
- openstack/lyra/templates/service.yaml
- openstack/lyra/templates/worker-deployment.yaml
- openstack/lyra/values.yaml
Move Lyras [existing alerts](https://github.com/sapcc/helm-charts/blob/master/system/kube-monitoring/charts/prometheus-frontend/openstack-lyra.alerts) to the PrometheusRule custom resource and adds the prometheus.io/targets annotation to the service. Validated manually.
> [Lyra] Move Prometheus alerts to CRD

- openstack/arc/alerts/api.alerts
- openstack/arc/alerts/canary.alerts
- openstack/arc/alerts/postgres.alerts
- openstack/arc/charts/mosquitto/templates/service.yaml
- openstack/arc/charts/postgresql/templates/svc.yaml
- openstack/arc/templates/api-service.yaml
- openstack/arc/templates/prometheus-alerts.yaml
- openstack/arc/values.yaml
Move Arcs [existing alerts](https://github.com/sapcc/helm-charts/blob/master/system/kube-monitoring/charts/prometheus-frontend/openstack-arc.alerts) to the PrometheusRule custom resource and adds the prometheus.io/targets annotation to the services. Validated manually.
While @databus23 is on vacation: Can you take a look @ArtieReus?
> [Arc] Move Prometheus alerts to CRD

- global/prometheus-alertmanager/templates/config.yaml
This should seperate the alerts by kubernetes cluster now that we have more than one per region.
> Add cluster label to inhibition rules and grouping

- openstack/nova/templates/etc/_nova-policy.json.tpl
They need a compute_admin_wsg role which
doest have the right to edit securitygroups and rules
but inherits all the other rights from the standard compute_admin role.
> Policyadjustement for BSO

- global/prometheus-infra/values.yaml
- global/prometheus-kubernetes/values.yaml
- global/prometheus-kubernikus/values.yaml
- global/prometheus-openstack/values.yaml
- system/kube-monitoring/charts/prometheus-frontend/values.yaml
- system/kube-monitoring/values.yaml
This PR hooks the new Prometheis to the Alertmanagers and retires our legacy ones.
> Activate alertmanagers for new Prometheis

- openstack/castellum/templates/_utils.tpl
With https://github.com/sapcc/castellum/commit/e59409179fc3adb495d0c55e0e5cc85a5fe314b3 rolled out, this is good to go from my side (except for the UI which I will work on next).
> enable quota autoscaling in prod regions

- openstack/nova/templates/api-metadata-deployment.yaml
- openstack/nova/templates/api-metadata-service.yaml
- openstack/nova/templates/etc-configmap.yaml
- openstack/nova/values.yaml
If the metadata APIs are enabled via setting `enabled_apis` including
"metadata", we don't have to spawn separate nova-api-metadata pods. This
is currently true in `eu-de-1` only, where we scaled down the deployment
of nova-api-metadata. To support the `eu-de-1` use-case, we were still
spawning metadata API workers in all other regions' nova-api pods. These
workers idled, but wasted memory.  This commit disables the idling
metadata workers in nova-api pods by default.
> [nova] Conditionally spawn api-metadata pods

- openstack/prometheus-openstack/templates/_openstack-prometheus.yaml.tpl
required because otherwise existing dashboard and alerts will not work properly
> add missing region label to all openstack metrics

- global/concourse/requirements.lock
- global/concourse/requirements.yaml
- global/concourse/values.yaml
This PR updates concourse to version 5.4.1 and hopefully fixes some issues we have with stale pipelines.
> Bump concourse to 5.4.1

- prometheus-exporters/ns-exporter/Chart.yaml
- prometheus-exporters/ns-exporter/alerts/probe.alerts
There is a new playbook and this alert should include the new link
> change playbook link to new playbook

- openstack/neutron/templates/etc/_neutron-policy.json.tpl
to update / delete / create securitygroups. Explizit denied rule caused too
much confusion from user perspective
> Removed explizit denied rule for the compute_admin_wsg role

- openstack/nova/templates/_helpers.tpl
- openstack/nova/templates/bin/_db-update-cells.tpl
This wasn't necessary before, because we just recently changed to cellv2
and had to migrate the old setup. But for new regions and the new labs,
we need this automated.
This also refactors the script a bit to re-use common functionality and
extends the for-loop to also include cell into the `grep`. This also
means, that the cell0 `database_connection` will now be updated if it
changes as well. This was already the case for cell1 and cell2.
Additionally, this commit updates the `cell0_db_path`-helper, but it was
unused before, so nothing needs changing.
> [nova] Automate initial cellv2 setup

- global/concourse/templates/backup-deployment.yaml
- global/concourse/values.yaml
This PR adds a separate backup deployment for postgres to concourse chart. It uses our very own backup-tools to create backups regularly.
> Add concourse psql backup

- global/prometheus-alertmanager/templates/config.yaml
The `slack_by_os_service` includes with this commit only productive regions and `qa-de-1` to avoid spamming the service specific channels with alerts from `staging`, which is in trouble most of the time.
If one is interested in `staging` alerts, join Slack channels `#alert-dev-[info|warning|critical]`
> slack_by_os_service without staging alerts

- system/prometheus-infra/templates/_prometheus-infra.yaml.tpl
Since the vasa-exporter has no label `app`, I've choosen the label `instance`, 'cause it is consistent in all regions.
> [infra-monitoring] vasa-exporter: changed federation regex

- system/infra-monitoring/vendor/netapp-cap-exporter/templates/secret.yaml
- system/infra-monitoring/vendor/netapp-cap-exporter/templates/service.yaml
- system/infra-monitoring/vendor/netapp-cap-exporter/values.yaml
Add annotation to the exporter's service, so that prometheus can scrape data.
> [infra-monitoring] Scrape netapp capacity exporter

- openstack/maia/templates/seed.yaml
* remove `/api/v1` path from the registered URL (since there are other possible prefixes)
* issue did not show up because Maia CLI always threw away that part (accidentally, fixed with Thanos switch)
* that Maia CLI fix will create issues if the catalog URL is not fixed, too
* tested that the change to the catalog does not break older Maia CLIs
> fix maia catalog entry

- openstack/manila/templates/api-deployment.yaml
During the loadtests i have seen that the timeout
for the liveness probe is not long enough. Therefore
kubernetes is constantly restarting the pod.
> Increased timeout for liveness probe

- openstack/swift/alerts/swift-api.alerts
- openstack/swift/etc/statsd-exporter.yaml
`timer_type` setting has been set for the individual metrics rather than as one of the `defaults` so that the other timing metrics don't get affected.
> Swift: use histogram for first-byte-timings

- system/infra-monitoring/vendor/arista-exporter/aggregations/network-arista.rules
- system/infra-monitoring/vendor/arista-exporter/alerts/network-arista.alerts
A playbook has to be added to this document for this alert:
https://operations.global.cloud.sap/docs/devops/alert/network/switch.html#arista
Critical Alert will be fired into alert-api-critical after 30min if sum of EFP slices is above 275%.
> [arista] tcam efp alert

- openstack/maia/Chart.yaml
- openstack/maia/requirements.yaml
- openstack/maia/values.yaml
use latest image with application credentials support by default i.e. in all regions (that do not specify another image version explicitly)
> [maia] enable app. cred. support in all regions

- openstack/manila/templates/api-ingress.yaml
Increased timeout in ingress because the manila-api
takes sometimes to long to respond. If this happens
ingress is killing the connection and reports http
504 to the client back.
> Increased timeout send and receive

- common/rabbitmq/templates/service.yaml
- common/rabbitmq/values.yaml
For CCM-12155. I validated the template syntax by adding an external IP to qa-de-1/values/hermes.yaml, running `helm diff upgrade` and checking the output.
> common/rabbitmq: add .Values.externalIPs attribute

- system/infra-monitoring/vendor/ipmi-exporter/values.yaml
- adds support for memory error metrics
- increases free-ipmi version to 1.6.4 (from 1.6.3)
- increases base img to ubuntu 19.04
- increases go image to go 1.11
> [infra-monitoring]ipmi_exporter: increases img version

- system/infra-monitoring/vendor/cablecheck-exporter/values.yaml
some improvements on cc-cablechecker - low noice on logfiles , can now handle multiple asw switches with repeating interface names
> [infra-monitoring] increases cablecheck exporter image

- prometheus-exporters/ntp-exporter/Chart.yaml
- prometheus-exporters/ntp-exporter/templates/daemonset.yaml
- prometheus-exporters/ntp-exporter/values.yaml
Container port changes from 9100 to 9559 because of this.
Since at least d015d5b, we use regular annotation-based service discovery for the ntp-exporter pods (instead of node-based service discovery) and thus don't need to bind to a host port anymore.
> bump ntp-exporter to v1.1.0

- system/kubernikus-monitoring/alerts/kluster.alerts
We have reports of false-positive alerts here when projects use quota autoscaling. Quota tracks usage closely in this case, so this alert may fire even though no manual intervention is required.
The fix uses that most projects have quota bursting enabled, so the backend quota (in Swift) will actually be 10% higher than the nominal quota (in Limes). Therefore there will be ample margin between backend quota and actual usage in projects with quota autoscaling.
@databus23 What do you think? Does this fix the problem for you, or do we still need CCM-12045 regardless?
> improve specificity of Kubernikus object-store quota alert

- openstack/neutron/templates/etc/_neutron.conf.tpl
At least in `eu-de-2`, it looks like the api-workers are running at full
CPU all the time. The amount of DB-connections should still work with 3
pgbouncers.
> [neutron] Increase the number of api_workers

- openstack/neutron/templates/statefulset-network-agent.yaml
for sites with 2 or more AZs: 
- 5 agents in `a` and `b` 
- 3 agents in others (if there are more AZs)
for single sites: 
- 10 agents
> [neutron] variable replicas count

- openstack/utils/templates/snippets/_debug.tpl
For this to work properly, a patch to oslo.service is necessary. We've
got our own fork of oslo.service that includes that patch already in the
upper-constraints for queens.
---
Services not having the patch will have socket path of `eventlet_backdoor-{pid}.socket` instead of `eventlet_backdoor.socket`.
> Add pid into backdoor socket path

- global/concourse/templates/worker-daemonset.yaml
- global/concourse/values.yaml
This PR changes max. garden containers per worker to 500, default is currently 250. It also changes netmask of used network to 10.254.0.0/16.
> Raise garden max containers for concourse workers

- openstack/ironic/values.yaml
Hi @BerndKue,
Group gauge gets postfixed to the metric name.
Regards,
Rajiv
> [Ironic-Alert] Adding openstack_ironic_nodes_conductor metric

- prometheus-rules/prometheus-kubernetes-rules/Chart.yaml
- prometheus-rules/prometheus-kubernetes-rules/alerts/health.alerts.tpl
This hopefully alerts us if this bug hits us: https://github.com/kubernetes/kubernetes/issues/84931.
I'm wondering if those alerts should be inhibited if the kubelet is down but couldn't figure out how to do it.
> Add alerts for kubelet bug and pods not ready

- global/concourse/values.yaml
This PR adds resource request to postgres and schedules database and web component on distinct nodepool.
> Add concourse postgres resource request, run on distinct nodepool

- global/concourse/alerts/concourse.alerts
This PR adds an alert to concourse chart when shm error occured in postgres database.
> Add concourse shm error alert

- openstack/swift/templates/etc/_proxy-server.conf.tpl
* remove keystone endpoint override hack, which is not needed in Train anymore as there is now keystone interface support
* remove pipeline valid prior to Rocky
* Remove old swift3 middleware traces as this is now official s3api
> [swift] cleanup

- openstack/neutron/templates/etc/_ml2-conf-aci.ini.tpl
Introduce templating to support yaml configuration of ACI bindings and address scopes . Has backward compatibility with old configuration format
> [neutron] ACI bindings rework

- openstack/neutron/templates/vct-nsxv3-agent-deployment.yaml
We still have crashlooping nsxv3-agent pods when the neutron-nsxv3-agent
container exits (e.g. when the process is killed manually or by
exception). Fabian Ruff found a bug, that should explain the behavior:
https://github.com/kubernetes/kubernetes/issues/68211#issuecomment-467032048
This bug also contains a workaround, that's implemented here: use a
projected configMap instead of mounting directly from the original ones.
This way, an updated configMap will not be seen by the restarting
container and thus will not lead to the crashloop we've seen.
> [neutron] Mount nsxv3-agent volumes from projected configMap

- openstack/neutron/templates/vct-nsxv3-agent-deployment.yaml
Reverts sapcc/helm-charts#1094
Warning  Failed                 2m               kubelet, minion7.cc.qa-de-1.cloud.sap  Error: failed to start container "neutron-nsxv3-agent": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/72570950-4739-11ea-9aa7-0a580ab4030f/volume-subpaths/etc-neutron/neutron-nsxv3-agent/0\\\" to rootfs \\\"/var/lib/docker/overlay2/94e6b613aae8d62480a753984c9239d5a44861bc0ea490347521e66b72b5dcc4/merged\\\" at \\\"/var/lib/docker/overlay2/94e6b613aae8d62480a753984c9239d5a44861bc0ea490347521e66b72b5dcc4/merged/etc/neutron\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory …
> Revert "[neutron] Mount nsxv3-agent volumes from projected configMap"

- system/infra-monitoring/templates/_prometheus-infra-collector.yaml.tpl
- system/infra-monitoring/values.yaml
- system/prometheus-infra/templates/_prometheus-infra.yaml.tpl
CPO esxi-exporter is deployed with its own pipeline.
The exporter is using atlas and therefore needs to be added to the prometheus config.
> added esxi-exporter to prometheus-infra-collector & federation

- prometheus-exporters/ntp-exporter/Chart.yaml
- prometheus-exporters/ntp-exporter/values.yaml
Dependencies were updated on the upstream repo, hence the bump.
/cc @majewsky
> ntp_exporter: bump version

- common/mariadb/templates/alerts/_mysql.alerts.tpl
To detect the mysqldump issues earlier. The MariaDBWaitingForLock alert will fire only when other writing queries  take place and time out. But the threshold 15, might be aggressive.
> [mariadb] warning alters when # of running threads is more than 15.

- common/mariadb/templates/alerts/_backup.alerts.tpl
Longer range to remove false positives due to backup container restart.
If the backup age has been older than 3 hours for 1 hour, it is 4 hours old now.
> [mariadb] refine backup alerts

- openstack/cinder/templates/api-deployment.yaml
- openstack/cinder/templates/backup_deployment.yaml
- openstack/cinder/templates/migration-job.yaml
- openstack/cinder/templates/scheduler-deployment.yaml
- openstack/cinder/templates/vcenter_datacenter_cinder_deployment.yaml
- openstack/cinder/templates/volumes/_netapp-deployment.yaml.tpl
- openstack/cinder/templates/volumes/_volume-deployment.yaml.tpl
This patch updates the openstack cinder charts to use the new
loci based container image.
> Update cinder to use loci image

- openstack/cinder/templates/backup_deployment.yaml
This patch changes the liveness probe for cinder backup container.
After we changed the base image from kolla to loci, the existing
liveness probe command for cinder backup failed.  This patch updates
the liveness probe command to work the same way as the cinder volume
container, which uses openstack-agent-liveness.
> cinder:  update liveness probe for backup

- openstack/tempest/cinder-tempest/templates/bin/_tempest-start-and-cleanup.sh.tpl
We've run into quota errors with cinder recently. There were a couple of
volumes in different states, but also groups and snapshots. We now try to
delete them after every run.
> [tempest][cinder] Add cleanup script

- openstack/glance/ci/test-values.yaml
- openstack/glance/templates/seeds.yaml
- openstack/ironic/ci/test-values.yaml
- openstack/ironic/templates/seed.yaml
- openstack/swift/templates/seeds.yaml
The recent region buildup showed these dependencies, so I move the ccadmin/master swiftoperator role_assignment from the swift seed to the dependent service seeds
> [seeds] glance and ironic depend on swift

- openstack/cinder/templates/backup_deployment.yaml
- openstack/cinder/templates/etc-configmap.yaml
- openstack/cinder/templates/etc/_rootwrap.conf.tpl
- openstack/cinder/templates/etc/_sudoers.tpl
This patch adds the /var/lib/openstack/bin directory to cinder rootwrap.conf
and adds a new volume mount to /etc/sudoers, which also adds the same
dir to the secure_path so that sudo commands has the openstack bin path
in the environment.
> cinder: Add missing path for rootwrap and sudoer

- openstack/cinder/templates/etc-configmap.yaml
This patch fixes an issue with the naming of the _sudoers.tpl file.
> cinder: fix etc-configmap

- openstack/neutron/templates/vct-nsxv3-agent-configmap.yaml
BB095's NSX Manager moves to it's own manager node
> Revert "Added exception for bb95 to use NSX-T from bb91"

- openstack/cinder/templates/volumes/_volume-deployment.yaml.tpl
This patch adds the /etc/sudoers to the cinder-volume-*
containers.  This is needed for privsep to be able to call
cinder-rootwrap during volume migration.
> cinder: fix sudoers for cinder-volume

- openstack/cinder/templates/etc/_cinder-policy.json.tpl
https://github.com/openstack/cinder/blob/4ea245640b0421246eef0cae1dd4fa11d31fc6ae/cinder/policies/backups.py#L28
> Fix export backup policy typo

- openstack/backup-replication/templates/_utils.tpl
- openstack/backup-replication/templates/replication-deployment.yaml
- openstack/backup-replication/values.yaml
- openstack/content-repo/ci/test-values.yaml
- openstack/content-repo/templates/mirror-cronjob.yaml
- openstack/content-repo/templates/mirror-deployment.yaml
- openstack/content-repo/values.yaml
By using `.Values.global.registry` in the backup-replication and content-repo charts.
Please only approve. I will merge this together with the corresponding PR on secrets.
> move swift-http-import image to Keppel

- openstack/nova/templates/etc/_nova-scheduler.conf.tpl
- openstack/nova/values.yaml
When scheduling a resizing instance prefer the host it's already running on. This hopes to reduce resource re-allocation.
Set the weigher multiplier to 1, enabled by default.
See sapcc/nova#141.
> [Nova] Add prefer_same_host_resize weigher & multiplier

- openstack/neutron/templates/asr_config_agents/_deployment-asr1k.yaml.tpl
- openstack/neutron/templates/deployment-aci-agent.yaml
- openstack/neutron/templates/deployment-f5-agent.yaml
- openstack/neutron/templates/deployment-ucs-bm-ml2-agent.yaml
- openstack/neutron/templates/loadbalancers/_deployment-f5.yaml.tpl
All our clusters run kubernetes >= 1.8. We don't need to safeguard for
older versions anymore. While the ifs didn't matter before, with helm
2.16 they started to matter, as our comparison between Float and String
broke and we would have to adapat the ifs with an integer cast anyways.
Therefore, we opted for removal.
> [neutron] Remove outdated kubernetes version checks

- openstack/keppel/requirements.lock
- openstack/keppel/requirements.yaml
- openstack/keppel/templates/_utils.tpl
- openstack/keppel/values.yaml
The only controversial part of this is the default rate limits (the `KEPPEL_RATELIMIT_...` variables).
> Keppel: add redis for token caching, rate limit tracking

- openstack/cinder/values.yaml
This patch overrides the default value for max_over_subscription_ratio
for the vmware volume driver from 20 to 2.
> CINDER: set max_over_subscription_ratio for vmware

- openstack/nova/values.yaml
We need to see in detail what the scheduler is doing in all regions.
> [nova] Turn on debug logging for scheduler

- openstack/cinder/values.yaml
After discussions of the current status in eu-de-1, we
agreed to update the max_over_subscription_ratio to 1.5
to limit the already overcommited netapp.
> [cinder] update the max_over_subscription_ratio to 1.5

- prometheus-exporters/ntp-exporter/Chart.yaml
- prometheus-exporters/ntp-exporter/values.yaml
My scheduled task for upgrading all the things came up, so ntp-exporter got the "upgrading all the things" treatment.
> bump ntp-exporter to 1.1.2

- common/rabbitmq/Chart.yaml
- common/rabbitmq/templates/alerts/_rabbitmq.alerts.tpl
It's useless if used as a label.
> [rabbitmq] Fix "for" condition on alerts

- openstack/tempest/cinder-tempest/values.yaml
This patch adjusts the concurrency value to 1 to avoid failures
related to quota overruns in cinder tempest tests.
> [cinder][tempest] set the concurrency to 1

- openstack/tempest/cinder-tempest/templates/bin/_tempest-start-and-cleanup.sh.tpl
This patch changes the loop from 1 to 8 to 1 to 18 for tempest project
names to ensure cleaning up cinder related resources after a tempest
run finishes.  This cleanup script was missing cleaning up for
project names like nova-tempest16.
> [cinder][tempest]  Do cleanup for all projects 1 through 18

- openstack/tempest/cinder-tempest/templates/bin/_tempest-start-and-cleanup.sh.tpl
This patch reverts the last change and adds volume type deletes
for projects named nova-tempestX.   nova-tempest-adminX doesn't exist
above #10.
> [cinder][tempest] Ensure volume types are deleted for nova-tempestX

- openstack/tempest/cinder-tempest/templates/bin/_tempest-start-and-cleanup.sh.tpl
Don't ask non admin accounts to delete group_types or volume types
> [cinder][tempest] non admins can't delete types or groups

- openstack/manila/values.yaml
In train release, the column share_network_id of share_servers table is
renamed to share_network_subset_id.
> [manila] fix share network metrics

- system/infra-monitoring/values.yaml
In order to reduce the query rate by the bios exporter I set the scrape interval to 1h.
> extended ironic_scrapeInterval in bios exporter

- openstack/cinder/templates/etc/_resource_filters.json.tpl
- volumes - enable partial match for name; enable filter user_id;
- snapshots - enable partial match for name.
> Extend Cinder API filtering for non-admin users:

- openstack/cinder/templates/vcenter_datacenter_cinder_configmap.yaml
- openstack/cinder/values.yaml
This patch adds a new cinder backend labelled vmware_low_iops
that will service the slower performing iops volumes.  By adding
this backend to the existing cinder-volume.conf, cinder will
fork another cinder volume service in the same container that will
service provisioning requests.   Since the default volume type is
vmware, this new backend won't get any provisioning requests unless
there is a new volume type associated with it's volume_backend_name.
With this patch we need a new cinder volume type created, named
'standard_hdd' with the following extra specs:
vmware:storage_profile : cinder_low_iops                                                          
vmware:vmdk_type : thick                                                                          
volume_backend_name : …
> [cinder] Add new vmware_low_iops backend

- openstack/cinder/templates/vcenter_datacenter_cinder_configmap.yaml
- openstack/cinder/values.yaml
This patch renames the new vmware_low_iops backend to 'standard_hdd'
Have to update the volume type
> [cinder] rename the new low_iops backend

- openstack/cinder/templates/vcenter_datacenter_cinder_configmap.yaml
- openstack/cinder/values.yaml
This patch updates the usage of the new backend name of
'standard_hdd' for all references, including enabled_backends
and the configmap dictionary.
> [cinder] fix the backend name usage for standard_hdd

- common/mariadb/templates/backup-etc-configmap.yaml
- common/mariadb/templates/backup-v2-deployment.yaml
- common/mariadb/templates/deployment.yaml
- common/mariadb/templates/service.yaml
- common/mariadb/values.yaml
- backup runs in an own pod (no longer as mariadb sidecar)
- adds readiness api to mariadb (via sidecar)
- this allows to set the mariadb pod into "not ready" while performing a restore
> [mariadb][backupv2] runs backup service via independent pod

- openstack/cinder/templates/vcenter_datacenter_cinder_configmap.yaml
- openstack/cinder/values.yaml
This patch makes the cinder-volume.conf enabled_backends
configurable.   This allows each region to optionally enable
the standard_hdd backend along with vmware backend.  This patch
makes the default value for enabled_backends=vmware.
If you want to enable the slow performing cinder backend,
then edit the secrets <region>/values/cinder.yml and add
backends:
enabled: vmware,standard_hdd
> [cinder] make enabled_backends configurable

- openstack/manila/values.yaml
Manila mariadb consumes at least 8G memory, since buffer_pool_size is
set to 8192M. And according to the doc, the total allocated memory is
about 10% larger than specified buffer pool size.
cf: https://mariadb.com/kb/en/innodb-buffer-pool/
> [manila] Make requested memory of mariadb match buffer pool size

- system/infra-monitoring/vendor/ipmi-exporter/alerts/metal-ironic.alerts
As requested by Ronny Werner, Martin Kautz, Christopher Mast
Since they need to get alerts for these types of failures right away.
> [ipmi-exporter][alerts] sets MetalIronicSensorCritical to 1s

- system/infra-monitoring/vendor/bm-cablecheck-exporter/alerts/bm-cablecheck.alerts
- system/infra-monitoring/vendor/bm-cablecheck-exporter/templates/alerts.yaml
- system/infra-monitoring/vendor/bm-cablecheck-exporter/values.yaml
- system/infra-monitoring/vendor/vpod-cablecheck-exporter/alerts/vpod-cablecheck.alerts
- system/infra-monitoring/vendor/vpod-cablecheck-exporter/templates/alerts.yaml
- system/infra-monitoring/vendor/vpod-cablecheck-exporter/values.yaml
added exclude=config_context to reduce api server cpu time
> [bm-cablecheck-exporter] V9, added exclude=config_context

- system/infra-monitoring/values.yaml
- system/infra-monitoring/vendor/bm-cablecheck-exporter/values.yaml
- system/infra-monitoring/vendor/vpod-cablecheck-exporter/values.yaml
[bm-cablecheck-exporter] V11
[vpod-cablecheck-exporter] V9
reduced polling time from 15m to 1m (collector provides now cached metrics, internally cablecheck will queried every 30m to reduct netbox/switch api load)
> [cablecheck-exporter] added cache mode

- system/infra-monitoring/values.yaml
- system/infra-monitoring/vendor/bm-cablecheck-exporter/values.yaml
- system/infra-monitoring/vendor/vpod-cablecheck-exporter/values.yaml
Reverts sapcc/helm-charts#1502
Aligned with @stefanhipfel due to wrong usage of caching. To decrease load on Netbox we further need to increase the scrapeInterval in the first place and switch over to our overall cache as in Atlas or a complete service discovery oriented approach.
> Revert "[cablecheck-exporter] added cache mode"

- system/infra-monitoring/vendor/netapp-cap-exporter/alerts/netapp-capacity.alerts
lower the cinder volume high udsage alert in all regions except one where we have to keep them higher due to already high usage
> [netapp-exporter] lower the cinder volume alerts

- openstack/neutron/Chart.yaml
- openstack/neutron/templates/statefulset-network-agent.yaml
Proposal to use only `component=agent` label for Pod anti affinity. 
Current approach takes into account all neutron pods which ends up in cases where scheduler assigns 3 network agents to the same node.
> [neutron] rework network-agent anti-affinity

- openstack/glance/templates/etc/_glance-api.conf.tpl
Hi @reimannf 
wrt 230 Gb server sizes, i found :
1. the chunk count reduced from 1219 to 477
2. upload speeds are up by 7Mbps
3. upload time reduced by ~30mins
I would like to know, if enabling these flags would impact swift ? swift-ratelimiting document explains operations per second only.
Regards,
Rajiv
> [Glance] enabling swift object size and object chunk size

- system/dynomite/templates/etc/_dynomite.yaml.tpl
There were issues with read and write consistency set to DC_ONE
esp. in DEL cases if the DELETE requests does not hit the dynomite
server responsible for the corresponding token.
Could be mitigated by setting the consistency to DC_QUORUM
https://github.com/Netflix/dynomite/wiki/Consistency
> [dynomite] set read and write consistency

- openstack/cinder/templates/type-seeds.yaml
This patch adds the 2 volume types to seed every deployment of
cinder with. This adds vmware and standard_hdd volume types and
all the extra specs for each volume type.
> [cinder] add volume type seeding

- system/elk/values.yaml
- system/elk/vendor/es-client/templates/_readonlyrest.yml.tpl
- system/elk/vendor/es-data/templates/_readonlyrest.yml.tpl
- system/elk/vendor/es-master/templates/_readonlyrest.yml.tpl
- system/elk/vendor/logstash/templates/_deployments.json.tpl
- system/elk/vendor/logstash/templates/_logstash.conf.tpl
- system/elk/vendor/logstash/templates/configmap.yaml
- system/elk/vendor/logstash/templates/deployment.yaml
- system/elk/vendor/logstash/templates/service.yaml
- system/elk/vendor/wall-e/templates/_delete_indices.yml.tpl
The setup is mostly a carbon copy of the existing `alerts-*` index. If you don't like the index name `deployments-*`, feel free to suggest a better one. Also, please have a look if I missed anything.
> elk: add the "deployments-*" index for tracking Helm releases

- openstack/cinder/values.yaml
This patch updates the unacknowledged_total_wait_for to 1 hour
from 10 minutes to help combat the infrequent alerts about
rpc messages not being collected.
> [cinder] update the rabbitq message wait queue time

- openstack/cinder/templates/etc/_cinder.conf.tpl
- openstack/cinder/values.yaml
This patch adds the new cinder.conf option for enabling soft sharding
migration of a volume on attach (allow_migration_on_attach)
setting configurable by secrets.  By default it's set to True.
> [cinder]  Add optional allow_migration_on_attach setting

- prometheus-exporters/oomkill-exporter/values.yaml
Get the klog_pod_oomkill metric into openstack and infra-collector Prometheus.
> oomkill-exporter to be scrapped by additional Prometheus

- system/infra-monitoring/vendor/atlas/templates/configmap.yaml
There was an issue reported that some alerts on the vpod channel where from not vpod servers, it was found that the query for the alerts was pulling some server which serial number coincided with the query 'CP' and those server were routed to the wrong slack channel, this will fix the issue by adding '-' to the atlas query so it ignores serial numbers.
> cp alerts query fix

- openstack/elastiflow/requirements.lock
- openstack/elastiflow/requirements.yaml
- openstack/elastiflow/templates/query-exporter-configmap.yaml
- openstack/elastiflow/templates/query-exporter-deployment.yaml
- openstack/elastiflow/templates/query-exporter-service.yaml
- openstack/elastiflow/values.yaml
elasticsearch master settings changed ;
- nodes to 3 replicasets from 1
- roles: master (only)
elasticsearch dedicated data notes;
- replicasets defaulted to 3
- roles: data + ingestion
resources used:
[blog post](https://medium.com/@thulasya/deploy-elasticsearch-on-kubernetes-via-helm-in-google-kubernetes-cluster-da722f3a8883)
[ES documentation](https://github.com/elastic/helm-charts/blob/master/elasticsearch/README.md)
> [Elastiflow] Settings to configure ES cluster formation

- openstack/nova/templates/api-deployment.yaml
- openstack/nova/templates/api-metadata-deployment.yaml
- openstack/nova/templates/api-metadata-service.yaml
- openstack/nova/templates/api-service.yaml
- openstack/nova/templates/etc-configmap.yaml
- openstack/nova/values.yaml
When having multiple cells, we disabled the standalone metadata service,
because that's not supported. Instead, one has to run the metadata
service "globally" as an api service. But this only means, one should
not use the "nova-api-metadata" executable to run the metadata service.
Therefore, we now run the metadata service in its own pod with the
nova-api executable.
We need to make sure we switch neutron to using the standalone api
endpoint everywhere before completely removing metadata from the api
service.
Afterwards, we should be able to switch both api and metadata to using
uwsgi. This is not possible with nova-api also having to spawn the
metadata service on a different port.
> [nova] Always start metadata service in own pod

- global/supernova/templates/contact-list-configmap.yaml
- global/supernova/templates/deployment.yaml
By putting this ConfigMap in a separate chart, we can use our standard deployment tooling, as explained in the new chart's README.
The new chart uses a different name for the ConfigMap, so as not to cause a collision when we first install it.
Please only approve, don't merge yet. I'm still preparing the requisite changes for the Concourse pipeline.
> split supernova-incident-contact-list chart from supernova chart

- openstack/swift/templates/proxy-deployment.yaml
A quick look at the `git log` suggests that we never had readiness probes here. The liveness probe has already existed in 2016. IMO the most likely explanation is that we didn't understand the difference between liveness and readiness probes way back when.
> add readiness probe to swift-proxy pods

- openstack/sre/templates/prometheus-alerts.yaml
This PR fixes one minor and one major problem and introduces the services' SLOs as a label to use it in the alert description.
---
I haven't tested it, I just templated the helm-chart.
To see the query in action, take a look at [prometheus](https://prometheus-openstack.eu-de-1.cloud.sap/graph?g0.range_input=1h&g0.expr=(1%20-%20global%3Aapi_errors_per_request_sli%3Aratio_rate2h)%20*10%20%3C%3D%20on%20(ingress%2Cregion)%20global%3Aapi_availability_warning_slo%3Apercent&g0.tab=1&g1.range_input=1h&g1.expr=(%20(1%20-%20global%3Aapi_errors_per_request_sli%3Aratio_rate2h)%20*%2010%20%20%3C%3D%20on%20(ingress%2C%20region)%20global%3Aapi_availability_warning_slo%3Apercent)%2B%20ignoring(slo)%20group_right%20count_values%20without()%20(%22slo%22%2C%20global%3Aapi_availability_warning_slo%3Apercent)% …
> [sre] Update alerts

- prometheus-exporters/vrops-exporter/alerts/vcenter.alerts
SSL Certificate Expiry in 30d == warning.
SSL Certificate Expiry in 15d == critical.
Operations playbook ready and added.
> vrops-exporter: add ssl cert alert

- prometheus-exporters/openstack-exporter/alerts/service.alerts
This patch adds a simple info alert for now for cinder.
The alert watches the amount of overcommit ratio left is
less than 0.5.
The amount of overcommit left is the difference between
the cinder configured max over subscription ratio and the
calculated overcommit ratio from allocated storage.
Typically the max oversubscription ratio is set to 1.5.
> [cinder] Add initial alert based on openstack-exporter

- openstack/nova/alerts/openstack-nova.alerts
- openstack/nova/values.yaml
vm_state for an instance stuck in "deleting" is "active". Instead, we
have to alert on an instance having the task_state "deleting" for too
long.
> [nova] Alert on task_state no vm_state

- prometheus-exporters/openstack-exporter/alerts/cinder.alerts
This patch updates the expression for tracking the amount of space
left before cinder reaches the max overcommit ratio.  The new
epxression matches when there is less than 10% overcommit ratio left
and shows the amount of space in TiB that equates to.
> [cinder] Update the expression for low overcommit warning

- openstack/ironic/templates/etc-configmap.yaml
- openstack/ironic/templates/etc/_ironic_conductor.conf.tpl
- openstack/ironic/templates/etc/_uefi_pxe_config.template.tpl
- openstack/ironic/values.yaml
To boot UEFI systems, ironic needs a special configuration This includes
a different PXE template and an additional boot file.
> add support for UEFI in ironic conductor

- prometheus-exporters/openstack-exporter/alerts/cinder.alerts
This patch increases the low overcommit ration from 10% to 20%
to help us catch the warnings earlier.
> [Cinder][Alert] Update low overcommit to 20%

- openstack/cinder/requirements.lock
- openstack/cinder/requirements.yaml
- openstack/cinder/templates/api-deployment.yaml
- openstack/cinder/templates/scheduler-deployment.yaml
This patch reverts the changes to the cinder charts that includes
support for jaeger.
I have to do a rollout on Monday of Cinder to all regions to update the max_oversubscription_ratio.
The diff on qa-de-1 shows a lot of changes regarding jaeger, which hasn't been fully vetted.
This patch removes the cinder changes that support jaeger for now.
> [Cinder]  This change removes jaeger components from cinder

- openstack/cinder/values.yaml
This updates the default max_oversubscription_ratio from 1.5
to 2.0
> [Cinder] Update max_oversubscription_ratio default

- system/infra-monitoring/vendor/atlas/templates/configmap.yaml
This sets the matching for neutron routers to role based rather than
name-based in order to stay independent from changing naming convention.
E.g. the naming convention for network devices has been changes, in such
matter that newly built devices will carry the tag 'rt' compared to
'asr' in the old convention.
> Atlas Netbox Service Discovery for neutron router

- system/infra-monitoring/vendor/vasa-exporter/alerts/vasa.alerts
Used wrong metric (percentage instead of percent).
> [infra-monitoring]: Fixed metric for vasa filesystem alert

- openstack/maia/templates/prometheus-alerts.yaml
This will ensure that the corresponding absent alerts will _always_ get routed to the appropriate Slack channel. More info [here](https://github.com/sapcc/absent-metrics-operator/blob/master/doc/playbook.md#tier-and-service-labels).
> openstack/maia: add service label to PromRule

- openstack/cinder/values.yaml
This patch updates the vmware_image_transfer_timeout_secs from
7200 seconds (2 hours) to 21600 seconds (6 hours).
Some large image -> volume tranfers can take a long time.
> [Cinder] Allow image tranfers of 6 hours

- openstack/cinder/values.yaml
This patch enables the low performance cinder backend named
'standard_hdd' everywhere.  We still have several regions
that have storage profiles that don't have datastores, due to
a bug in vmware.  Once the cinder-standard-hdd profile is fixed in
those regions, then the driver will report space available for
provisioning.  While the storage profile doesn't have datastores, the
cinder driver will simply report have 0 bytes available for
provisioning and the cinder scheduler will never pick that backend
for a new volume.
> [Cinder] Enable standard_hdd backend

- openstack/cinder/requirements.lock
- openstack/cinder/requirements.yaml
- openstack/cinder/templates/api-deployment.yaml
- openstack/cinder/templates/scheduler-deployment.yaml
- openstack/cinder/values.yaml
This commit adds jaeger agent to cinder-api and cinder-scheduler pods as
side containers, and set the agents as the osprofiler's backend. The
jaeger operator is added as dependency in the requirements.yaml file,
with condition `osprofiler.jaeger.enabled`.
> [Cinder] Integrate jaeger with cinder

- prometheus-exporters/vrops-exporter/alerts/host.alerts
- added playbook
- increased severity to warning
- action identical to alert EsxiHostWithAssociatedVMsNotResponding
> HostWithRunningVMsNotResponding increased severity to warning.

- system/kube-monitoring-admin-k3s/Chart.lock
- system/kube-monitoring-admin-k3s/Chart.yaml
- system/kube-monitoring-admin/Chart.lock
- system/kube-monitoring-admin/Chart.yaml
- system/kube-monitoring-kubernikus/Chart.lock
- system/kube-monitoring-kubernikus/Chart.yaml
- system/kube-monitoring-metal/Chart.lock
- system/kube-monitoring-metal/Chart.yaml
- system/kube-monitoring-scaleout/Chart.lock
- system/kube-monitoring-scaleout/Chart.yaml
- system/kube-monitoring-virtual/Chart.lock
- system/kube-monitoring-virtual/Chart.yaml
event-exporter has been bumped in all cluster types to deploy 0834de63ebb541f1c121733a00708dccc50b89c6.
> system/kube-monitoring*: bump event-exporter

- common/mariadb/Chart.yaml
- common/mariadb/ci/test-values.yaml
- common/mariadb/templates/_helpers.tpl
- common/mariadb/templates/backup-v2-deployment.yaml
- common/mariadb/templates/backup-verify-deploy.yaml
- common/mariadb/templates/deployment.yaml
- common/mariadb/values.yaml
possibility to use alternate registry, e.g. for keystone
pod-readiness has just been copied (just added a source_repo label) for now - I would prefer to do a fresh build
> [common][mariadb] use custom images from keppel

- openstack/cinder/templates/api-deployment.yaml
- openstack/cinder/templates/backup_deployment.yaml
- openstack/cinder/templates/migration-job.yaml
- openstack/cinder/templates/scheduler-deployment.yaml
- openstack/cinder/templates/vcenter_datacenter_cinder_deployment.yaml
- openstack/cinder/templates/volumes/_netapp-deployment.yaml.tpl
- openstack/cinder/templates/volumes/_volume-deployment.yaml.tpl
This patch updates the Cinder helm charts to use keppel registry
and namespace.
> [Cinder] Migrate to keppel

- openstack/keystone/ci/test-values.yaml
- openstack/keystone/requirements.lock
- openstack/keystone/requirements.yaml
- openstack/keystone/templates/deployment-api.yaml
- openstack/keystone/templates/etc/_keystone.conf.tpl
This PR integrates osprofiler with jaeger into keystone service. When enabled (via secrete values), the api pods will be running with a sidecar container jaeger-agent, which is responsible to send the collected profiling spans to the jaeger system.
> [keystone] inetgrate osprofiler/jaeger

- prometheus-exporters/vrops-exporter/alerts/host.alerts
Removed HostMemoryBallooning alert. The alert is no longer needed according to David Hoeller.
> removed ballooning alert

- prometheus-exporters/openstack-exporter/alerts/cinder.alerts
This patch updates the cinder low overcommit ration alert from
info to warning.  Also adds the link to the playbook.
> [cinder] Upgrade the low overcommit alert to warning

- openstack/keystone/templates/daemonset-keep-image-pulled.yaml
similar to what keppel has for postgres.
technically only db readiness image is stored in keppel, but theoretically db restarts will be a bit faster if mariadb and metrics are pre-pulled on all nodes.
> [keystone] added image puller ds for keppel

- prometheus-exporters/openstack-exporter/alerts/cinder.alerts
This patch adds a new critical alert for cinder pool storage
overcommit ratio reaching 10% or less leftover.
> [Cinder] Add critical alert for overcommit <10% left

- openstack/cinder/values.yaml
This patch enables the new custom setting for selecting
the best datastore via random method.
> [cinder] Enable select random best datastore

- openstack/swift/templates/proxy-deployment.yaml
Seems the base line has been raised after py3 conversion
> [swift] bump memory for the collector

- system/infra-monitoring/values.yaml
Reverts sapcc/helm-charts#1911
Needs to be specified per region until we are rolled out.
> Revert "[prometheus-infra] decreased scrape interval"

- openstack/nova/templates/etc/_nova.conf.tpl
Starting with Rocky, nova-consoleauth gets deprecated and there is
an option `[workaround]enable_consoleauth = True` which needs to be
set in order to keep nova using it. This is mainly needed for
shellinaboxproxy which is not yet adapted to use db tokens.
> [nova] add workaround for keeping consoleauth enabled

- openstack/nova/templates/etc/_nova-scheduler.conf.tpl
We default to 1, because parallel scheduling can make things
problematic, but leave it configurable in case we see performance
problems.
This is a new setting in rocky.
> [nova] Set scheduler workers to 1

- openstack/nova/templates/etc/_nova-scheduler.conf.tpl
- openstack/nova/values.yaml
There is a new CPUWeigher introduced in Rocky, so we add a configuration
in case we need to use it somewhere.
Defaults to 1.0 so that it doesn't have any effect by default.
> [nova] add cpu_weight_multiplier

- openstack/cinder/requirements.lock
- openstack/cinder/requirements.yaml
This patch updates some of cinder's dependencies to versions
that use keppel instead of quay.
> [cinder] update cinder requirements for keppel

- system/infra-monitoring/vendor/bm-cablecheck-exporter/values.yaml
In na-us-1 the cable-checker for baremetal has been stuck for some time. I had a look at it and found out that at a node different mac addresses are used than the ones in netbox for the host.
I had also checked if the macs are different on the hardware, but negative.
A fix deployed in the new image version I uploaded.
> new cable-checker version

- openstack/cinder/templates/etc/_cinder.conf.tpl
- openstack/cinder/values.yaml
also adjust max_connections & connect_timeout for mariadb and pool_size for sqlalchemy;
> [cinder] reduce the workers per pod, but increase replicas;

- system/prometheus-infra/templates/_prometheus-infra.yaml.tpl
Reverts sapcc/helm-charts#1948
> Revert "[prometheus-infra.scaleout] just ignore vrops_virtualmachine production metrics"

- openstack/cinder/templates/api-deployment.yaml
- openstack/cinder/templates/etc-configmap.yaml
- openstack/cinder/templates/etc/_api_uwsgi.ini.tpl
- openstack/cinder/templates/etc/_cinder.conf.tpl
- openstack/cinder/values.yaml
By setting "api.use_uwgi = true" in a region, we can run cinder-api via
uWSGI instead of the eventlet WSGI server. This can be more performant,
but when choosing the number of workers, we have to bear in mind, that
there are no greenthreads in them - in the eventlet server, there were
100 greenthreads in each process.
This also means, that the number of DB connections required per worker
should decrease significantly - in theory to the number of workers, but
we've seen manila-api use 2 connections per worker, so this needs to be
tested.
> [cinder] Optionally run cinder-api via uWSGI

- openstack/neutron/templates/asr_config_agents/_deployment-asr1k.yaml.tpl
neutron-server and the asr1k agents should be restarted on a configmap
change, hence we need to include the configmap hash.
> Add asr1k config map hash to neutron deployments

- openstack/cinder/templates/api-ingress.yaml
- openstack/cinder/values.yaml
The Vice-API and functionality of vice-president will be shut down by
30th September 2020. There's a new solution based on cert-manager for
certificate issuance.
> [cinder] Switch from vice-president to tls-acme

- openstack/octavia/values.yaml
Returning an empty set is an error for the mysql metrics collector.
Therefore, if there is no PENDING load balancer we need _some_ result that doesn't add to the count of PENDING load balancers but makes for a valid result that doesn't trip up the mysql metrics collector.
> [Octavia] Fix alert octavia_loadbalancers_pending

- openstack/cinder/values.yaml
Customers are seeing create volume from image failures for
large volumes of 2Tb.   The current timeout is set to 6 hours, but
that is insufficient for a 2Tb volume, which should take around 18.5
hours.
This patch updates the timeout to 20 hours.
> [Cinder] Update the image copy timeout to 20 hours

- openstack/nova/values.yaml
These filters were completely removed in Rocky, and baremetal
scheduling is going to be done based on flavor's extra properties
resource:CUSTOM_*
> [nova] remove BareMetalExact* filters

- prometheus-exporters/ns-exporter/alerts/probe.alerts
Shoot networks are some kind of broken. As the alternative would be to silence them every night, I propose to make them an `warning` instead. So the support only reacts to them during the business hours.
> Treat shoot networks in a special way

- prometheus-exporters/openstack-exporter/templates/openstack-exporter-openstack-config.yaml
When openstack-exporter added dynamic loading of collectors,
we need to add the collectors entry in the config, so it loads
the collectors we want to run.
This patch adds in the cinder collector in the config.
> [openstack-exporter]  Add collectors section to config

- openstack/nova/templates/bin/_db-migrate.tpl
The --local_cell parameter was initially introduced [1] to help
upgrading nova to cellv2.
That's been done since a while ago, so we need to remove this
parameter again so that db migrations will run against all the
cells databases and cell0.
[1] https://github.com/sapcc/helm-charts/commit/34943d0ecb260d76dd50c451a27d3d6139eebb26
> nova db-migrate: remove --local_cell parameter

- openstack/vcenter-operator/templates/deployment.yaml
> openstack/vcenter-operator: fix deprecated API versions

- global/percona_cluster/templates/statefulset.yaml
> global/percona_cluster: fix deprecated API versions

- system/elastiflow/templates/elasticsearch-exporter-deployment.yaml
- system/elastiflow/templates/logstash-exporter-deployment.yaml
- system/elastiflow/templates/query-exporter-deployment.yaml
- system/elastiflow/vendor/elasticsearch-exporter/templates/deployment.yaml
- system/elastiflow/vendor/elasticsearch/templates/_helpers.tpl
- system/elastiflow/vendor/elasticsearch/templates/ingress.yaml
- system/elastiflow/vendor/elasticsearch/templates/statefulset.yaml
- system/elastiflow/vendor/kibana/templates/_helpers.tpl
- system/elastiflow/vendor/kibana/templates/deployment.yaml
- system/elastiflow/vendor/kibana/templates/ingress.yaml
- system/elastiflow/vendor/logstash/templates/_helpers.tpl
- system/elastiflow/vendor/logstash/templates/statefulset.yaml
> openstack/elastiflow: fix deprecated API versions

- prometheus-exporters/esxi-exporter/templates/deployment.yaml
> prometheus-exporters/esxi-exporter: fix deprecated API versions

- prometheus-exporters/openstack-exporter/alerts/cinder.alerts
Add a new alert for cinder to detect specifically when the free capacity
or total capacity is 0.  This happens when the storage profile is
totally consumed or when the storage profile has no datastores.
This can happen when the storage profile is broken due to io filters
being offline.
> [cinder]  Add CinderBackendStorageEmptyCritical

- prometheus-exporters/openstack-exporter/alerts/cinder.alerts
This patch adds new CinderBackendShardLowFreeSpaceWarning
alert.  This alerts when the amount of free space is less
than 25% remaning.  This should cover both thin provisioned
and thick provisioned backends.
> [cinder] Add CinderBackendShardLowFreeSpaceWarning

- openstack/maia/templates/maia-deployment.yaml
- openstack/maia/templates/maia-ingress.yaml
> openstack/maia: fix deprecated API versions

- openstack/hermes/templates/api-deployment.yaml
- openstack/hermes/templates/api-ingress.yaml
- openstack/hermes/templates/elasticsearch-deployment.yaml
- openstack/hermes/templates/elasticsearch-exporter-deployment.yaml
- openstack/hermes/templates/es-manager-deployment.yaml
- openstack/hermes/templates/es-manager-ingress.yaml
- openstack/hermes/templates/kibana-deployment.yaml
- openstack/hermes/templates/logstash-deployment.yaml
- openstack/hermes/templates/wall-e-deployment.yaml
> openstack/hermes: fix deprecated API versions

- system/dns/charts/bind1/templates/deployment.yaml
- system/dns/charts/bind2/templates/deployment.yaml
- system/dns/charts/unbound1/templates/deployment.yaml
- system/dns/charts/unbound2/templates/deployment.yaml
> system/dns: fix deprecated API versions

- system/datahub/templates/ingress.yaml
> system/datahub: fix deprecated API versions

- openstack/octavia/templates/octavia-housekeeping.yaml
> openstack/octavia: fix deprecated API versions

- common/prometheus-alertmanager-base/Chart.yaml
- common/prometheus-alertmanager-base/templates/ingress.yaml
> common/prometheus-alertmanager-base: fix deprecated API versions

- openstack/cinder/templates/api-deployment.yaml
- openstack/cinder/templates/api-ingress.yaml
- openstack/cinder/templates/backup_deployment.yaml
- openstack/cinder/templates/scheduler-deployment.yaml
- openstack/cinder/templates/vcenter_datacenter_cinder_deployment.yaml
- openstack/cinder/templates/volumes/_netapp-deployment.yaml.tpl
- openstack/cinder/templates/volumes/_volume-deployment.yaml.tpl
> openstack/cinder: fix deprecated API versions

- prometheus-exporters/nfs-exporter/Chart.yaml
- prometheus-exporters/nfs-exporter/templates/deployment.yaml
> prometheus-exporters/nfs-exporter: fix deprecated API versions

- system/kube-fip-controller/Chart.yaml
- system/kube-fip-controller/templates/deployment.yaml
> system/kube-fip-controller: fix deprecated API versions

- prometheus-exporters/systemd-lldp-exporter/Chart.yaml
- prometheus-exporters/systemd-lldp-exporter/templates/deployment.yaml
> prometheus-exporters/systemd-lldp-exporter: fix deprecated API versions

- global/pulsar/Chart.yaml
- global/pulsar/templates/ingress.yaml
> global/pulsar: fix deprecated API versions

- common/prometheus-server/CHANGELOG.md
- common/prometheus-server/Chart.yaml
- common/prometheus-server/templates/ingress.yaml
- common/prometheus-server/templates/thanos/prometheus-thanosCompactorStatefulset.yaml
- common/prometheus-server/templates/thanos/prometheus-thanosQueryDeployment.yaml
- common/prometheus-server/templates/thanos/prometheus-thanosStoreStatefulset.yaml
> common/prometheus-server: fix deprecated API versions

- system/sentry/charts/postgresql/templates/deployment.yaml
- system/sentry/charts/redis/templates/deployment.yaml
- system/sentry/ci/test-values.yaml
- system/sentry/templates/cron-deployment.yaml
- system/sentry/templates/ingress.yaml
- system/sentry/templates/operator-deployment.yaml
- system/sentry/templates/pruning-deployment.yaml
- system/sentry/templates/server-deployment.yaml
- system/sentry/templates/worker-deployment.yaml
- system/sentry/values.yaml
> system/sentry: fix deprecated API versions

- system/container-linux-update-operator/templates/update-agent.yaml
- system/container-linux-update-operator/templates/update-operator.yaml
> system/container-linux-update-operator: fix deprecated API versions

- system/ntp-timeserver/charts/ntp/templates/deployment.yaml
> system/ntp-timeserver: fix deprecated API versions

- system/conntrack-nanny/templates/daemonset.yaml
> system/conntrack-nanny: fix deprecated API versions

- system/bind/templates/deployment.yaml
> system/bind: fix deprecated API versions

- global/wham/templates/deplyoment.yaml
- global/wham/templates/ingress.yaml
> global/wham: fix deprecated API versions

- openstack/db-backup-v2/templates/deploy.yaml
- openstack/db-backup-v2/templates/dex-ingress.yaml
> openstack/db-backup-v2: fix deprecated API versions

- openstack/openstack-seeder/templates/deployment.yaml
> openstack/openstack-seeder: fix deprecated API versions

- openstack/kos-operator/templates/deployment.yaml
> openstack/kos-operator: fix deprecated API versions

- openstack/nova/templates/etc/_nova.conf.tpl
- openstack/nova/values.yaml
If we fail to connect to cinder, we might get into an invalid state the
nanny has to fix. Let's retry a couple more times to try and keep these
inconsistencies to a minimum. Default is 3.
The specific inconsistency we've seen is that a volume was set to state
"detaching" by nova-api, but then nova-compute failed to actually get
the volume from cinder and thus couldn't update or roll back the state.
> [nova] Increase http_retries for cinder

- prometheus-exporters/vrops-exporter/alerts/host.alerts
- added notInMaintenance as condition
- removed $labels.value to prevent multiple firing alerts
> [vrops-exporter] Adjusted HostWithVMsNotResponding alert

- system/multicloudtest/templates/cronjob.yaml
- system/multicloudtest/values.yaml
should avoid more than one running pod
cleanup of errored jobs
> more sophisticated pod handling

- prometheus-exporters/snmp-exporter/alerts/f5.alerts
@artherd42 
Requesting approval to promote the “NetworkF5MemoryDrop” alert to level “Critical”
Playbook is published and handover to Accenture for 24x7 support completed earlier today.
> Promoting F5 memory drop alert to Critical

- system/infra-monitoring/values.yaml
too many requests on remote boards. Therefore, reduce interval of BIOS and CABLECHECK exporters.
> update scrapeInterval and scrapeTimeout cable&bios

- prometheus-exporters/vrops-exporter/templates/vrops-inventory-deployment.yaml
> prometheus-exporters/vrops-exporter: fix deprecated API versions

- prometheus-exporters/jumpserver-exporter/templates/jumpserver-deployment.yaml
> prometheus-exporters/jumpserver-exporter: fix deprecated API versions

- prometheus-exporters/vrops-exporter/templates/collector-configmap.yaml
Added 3 stats to get vrops db partition disk size
"vrops_db_disk_usage_gigabytes" , "vrops_db_disk_capacity_gigabytes" and "vrops_db_disk_usage_percent"
Requesting for a review -Thanks
> stats to get vrops-vm db disk size

- system/elk/vendor/es-client/templates/deployment.yaml
- system/elk/vendor/es-client/templates/ingress.yaml
- system/elk/vendor/es-data/templates/deployment.yaml
- system/elk/vendor/es-exporter/templates/deployment.yaml
- system/elk/vendor/es-manager/templates/deployment.yaml
- system/elk/vendor/es-manager/templates/ingress.yaml
- system/elk/vendor/es-master/templates/deployment.yaml
- system/elk/vendor/es-query-exporter/templates/deployment.yaml
- system/elk/vendor/fluent-scaleout/templates/daemonset.yaml
- system/elk/vendor/fluent-systemd/templates/daemonset.yaml
- system/elk/vendor/fluent-vcenter/templates/deployment.yaml
- system/elk/vendor/fluent/templates/daemonset.yaml
- system/elk/vendor/kibana/templates/deployment.yaml
- system/elk/vendor/kibana/templates/ingress.yaml
- system/elk/vendor/logstash/templates/deployment.yaml
- system/elk/vendor/wall-e/templates/deployment.yaml
> system/elk: fix deprecated API versions

- openstack/swift/templates/etc/_account-server.conf.tpl
- openstack/swift/templates/etc/_container-server.conf.tpl
- openstack/swift/templates/etc/_object-server.conf.tpl
- openstack/swift/values.yaml
* Disabling of request logging for account, container and object server is disabled by default now
* Double `fallocate_reserve` to 2%
> [swift] don't log requests to backend server anymore

- prometheus-exporters/openstack-exporter/alerts/cinder.alerts
This patch updates the alerts for several of the
cinder low storage / empty storage alerts from info
to warning/critical
TODO:
The empty storage playbook is being updated by Gergely
> Upgrade the alerts for cinder storage

- openstack/cinder/templates/etc/_resource_filters.json.tpl
For Cinder train the /etc/cinder/resource_filters.json file
needs the entry for volume type, otherwise end users can't
even get a list of volume types.
Without it non admins that run "cinder type-list" get the
following error.
ERROR: Invalid filters is_public are found in query options.
The feature/requirement was backported to train
https://github.com/openstack/cinder/blob/stable/train/etc/cinder/resource_filters.json#L14
> [Cinder] Add required resource filter for volume type

- openstack/lyra/charts/postgresql/templates/deployment.yaml
> openstack/lyra: fix deprecated API versions

- global/concourse/templates/backup-deployment.yaml
- global/concourse/templates/git-resource-proxy.yaml
- global/concourse/templates/webhook-broadcaster-ingress.yaml
- global/concourse/templates/webhook-broadcaster.yaml
> global/concourse: fix deprecated API versions

- system/elk/vendor/fluent/templates/_pattern.tpl
Unauthenticated or Rate limit rejected requests to S3 are logged with
the following requestpath: `/container/object` instead of Swift usual
pattern `/v1/AUTH_123/container/object`
To not loose the specific fields, adopt the match.
> [elk] Capture Swift S3 request paths as well

- openstack/swift/templates/proxy-deployment.yaml
- openstack/swift/templates/proxy-service.yaml
- openstack/swift/values.yaml
1. Enable `externalTrafficPolicy: Local` for swift proxy services
to announce routes to service only on nodes which run the pods.
This requires a service of `Type: NodePort`.
2. Pin swift-proxy pods to storage nodes to bring traffic closer
to the storage nodes (in case the replica resides on the same
node as the proxy pod).
> [swift] Capability externalTrafficPolicy: Local

- openstack/hermes/alerts/hermes.alerts
The old link is wrong the new one is working
It also seems that `{{ $labels.service }} {{ $labels.check }}`  are empty but I don't know what should be there and what should be there instead.
> Fix hermes playbook link

- openstack/cinder/requirements.lock
- openstack/cinder/requirements.yaml
- openstack/cinder/templates/api-deployment.yaml
- openstack/cinder/templates/etc-configmap.yaml
- openstack/cinder/templates/etc/_api-paste.ini.tpl
- openstack/cinder/templates/etc/_ratelimit.yaml.tpl
- openstack/cinder/values.yaml
- no global limits at the moment; only (target-) project limits now.
- each individual endpoint has to be specified, no support for wildcards
- http 429 is returned when limit is hit; or 403 if blacklisted.
- json message is returned when limiting takes place
- rate-limiting settings ignored when backend (redis) is not reachable
> [cinder] prepare rate-limiting middleware:

- global/prometheus-alertmanager-operated/Chart.yaml
- global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl
request by @BerndKue to ad for active directory alerts / there will be separate team on taking care (critical will follow); reused vpod settings because vpod routing is dead/covered in metal
> [alertmanager] replace deprecated vpod by ad

- openstack/cinder/templates/vcenter_datacenter_cinder_configmap.yaml
This patch adds a section to the cinder backends definitions
to allow creating a custom backend define for a region.
The region's values/cinder.yml would contain
backends:
custom_backend: |
[custom_backend_name]
volume_backend_name = my_custom_backend
volume_driver = cinder.volume.drivers.something.custom
This will allow us to add custom backends against qa-de-1 for example to enable the pure storage driver.
> [Cinder] Allow for defining a custom cinder backend

- system/infra-monitoring/vendor/vcenter-exporters/alerts/vcenter-host.alerts
With the new policy the cluster can now have 2 failover hosts.
> [vcenter-exporter] Increased failover node limit to 2

- openstack/nova/templates/api-deployment.yaml
- openstack/nova/templates/api-metadata-deployment.yaml
- openstack/nova/templates/bigvm-deployment.yaml
- openstack/nova/templates/cell2-conductor-deployment.yaml
- openstack/nova/templates/conductor-deployment.yaml
- openstack/nova/templates/hypervisors/_ironic-deployment.yaml.tpl
- openstack/nova/templates/hypervisors/_kvm-deployment.yaml.tpl
- openstack/nova/templates/hypervisors/hypervisors-vmware-deployment-vct.yaml
- openstack/nova/templates/placement-api-deployment.yaml
- openstack/nova/templates/scheduler-deployment.yaml
- openstack/nova/templates/sentry.yml
- openstack/nova/templates/vspc-deployment.yaml
- openstack/nova/values.yaml
Instead of manually updating/adding the "sentry_dsn" key in/to the
secrets after adding its project to sentry, we now tell the
sentry-operator to add the project and provide the DSN to us via
k8s secret.
We also add the `SENTRY_DSN` environment variable to all services, that
didn't have it before.
> [nova] Switch to sentry-operator

- openstack/cinder/templates/etc/_ratelimit.yaml.tpl
This patch fixes the ratelimit.yml file.   The rate limiting wasn't
working with cinder on some urls, because the blocks declaring
the uris were getting re-declared for the different actions GET vs POST.
The actions need to be in the same declaration block for the uri.
> [Cinder] Fix rate limit

- prometheus-exporters/elastic-query-exporter/alerts/logs.alerts
- prometheus-exporters/elastic-query-exporter/files/exporter.cfg
Loglevel INFO, playbook needs to be added, no VM info in alert
> [elastic-query-exporter] Add alert for unexpected VM power down

- prometheus-exporters/openstack-exporter/alerts/cinder.alerts
The alerts that the openstack-exporter is sending goes to the
os tier currently.  Changing them all to the vmware tier.
> [Cinder] Update the cinder storage tier to vmware

- prometheus-exporters/vrops-exporter/alerts/datastore.alerts
- prometheus-exporters/vrops-exporter/alerts/host.alerts
- prometheus-exporters/vrops-exporter/alerts/virtualmachine.alerts
+ better information on alerts (vcenter instead of datacenter)
> [vrops-exporter] only powered on VMs for alert VMsOnFailoverHost

- openstack/nova/alerts/openstack/nova.alerts
- 'host' label is reserved for db service host with new exporter
> [nova] update alert labels s/host/nova_host/g

- prometheus-exporters/elastic-query-exporter/alerts/logs.alerts
- prometheus-exporters/elastic-query-exporter/files/exporter.cfg
* adjust alert expression
* remove alert timeout as this is an event based alert
* add syslog message in alert description
* node.nodename removed from alert description
as exporter can't parse out nested fields yet
ESXi name will be in syslog message, as will affected VM
* remove aggs from query needed before for aggs based metric
> [elastic-query-exporter] Switch to search result based metric

- prometheus-exporters/openstack-exporter/values.yaml
The info log level is overly quiet.  This patch ups the loglevel
to DEBUG
> [openstack-exporter]  Change default log level to DEBUG

- openstack/neutron/alerts/nsxt.alerts
The NSXTExporterNoData alert doesn't work, if the exporter stopped
exporting for a longer period of time, because prometheus can only see
things as absent, if they ever reported.
We now build a query matching all running nsxv3-agent pods to one
nsxv3_agent of the nsxv3_cluster_management_last_successful_data_fetch
metric. If we can't find a metric reported by a running pod, we fire an
alert.
> [neutron] Add NSXTExporterNoMetrics alert

- openstack/swift/templates/_utils.tpl
- openstack/swift/templates/health-exporter-deployment.yaml
- openstack/swift/templates/memcached-deployment.yaml
- openstack/swift/templates/object-expirer-deployment.yaml
- openstack/swift/templates/proxy-daemonset.yaml
- openstack/swift/templates/proxy-deployment.yaml
- openstack/swift/templates/s3-cache-prewarmer-deployment.yaml
- openstack/swift/values.yaml
Swift proxies can be deployed as
* Deployment
* Daemonset
* Both
New value sets:
* proxy_deployment_*
* proxy_daemonset_* 
Resource request and limits have to be specified per swift cluster
Other changes
* Remove `resources.enabled` value
* Move `proxy_on_nodes` to flatten
> [swift] Deployment options for Proxy: Deployment, Daemonset or Both

- openstack/octavia/requirements.lock
- openstack/octavia/templates/etc/_octavia.conf.tpl
The housekeeping pod exists but housekeeping is never configured in the config. That's why we have many thousands of deleted load balancers just lying around.
Edit: There are in fact default values, but the expiry age is one week.
> [Octavia] Add housekeeping

- common/mariadb/Chart.yaml
- common/mariadb/templates/alerts/_backup-v2.alerts.tpl
- we currently have nova with up to 3, soon 4 db instances and existing
count alerts did not fire as expected due to multiple instances in use.
- replace storage error alerts with verify restore failed.
> [backupv2] adjusted the alerts.

- openstack/swift/templates/proxy-deployment.yaml
- openstack/swift/values.yaml
Option to create swift proxy deployments per AZ.
The initial amount of replicas per AZ can be specified, otherwise default to 0.
Scheduling
* Only schedule on nodes current az
* Do not schedule to storage nodes (missing tolerations)
* Prefere to be scheduled on nodes not yet running this proxy from a deplyoment
> [swift] proxy deplyoment per Availabilty Zone

- openstack/swift/aggregations/openstack/consolidation.rules
- prometheus-exporters/elastic-query-exporter/alerts/logs.alerts
Raise severity to critical for 
* VMPoweredDownDuringFailedHostMigration
* OctobusVCSALogShippingNotWorking
> [elastic-query-exporter] Raise severity to critical for 2 alerts

- openstack/nova/templates/api-deployment.yaml
- openstack/nova/templates/api-metadata-deployment.yaml
Setting the hostname for the containers, so that nova api services
will get registered correctly in the database.
> [nova] set hostname in deployment spec

- openstack/hermes/files/policy.json
Implements the indexID override, introduced in https://github.com/sapcc/hermes/pull/51
> [hermes]: introduce a new policy for cluster scope

- openstack/utils/templates/_helpers.tpl
- system/jaeger-operator/ci/test-values.yaml
- system/jaeger-operator/templates/operator.yaml
This PR clears old osprofiler setup with flamegraph-redis.
Also in the old setup, both global value `global.osprofiler.enabled` and service local `osprofiler.enabled` are checked in the helper function definition. It is bit confusing to control the integration of osprofiler, since osporfiler is not enabled for all services and one has to edit different places. **With this PR, osprofiler integration can only be enabled explicitly by the service local value `osprofiler.enabled`.**
This change will affect number of services with osprofiler integration in helm chart: `keystone`, `cinder`, `nova`, `nuetron` and `ironic`. Therefore I am asking the service owners to review this PR and be aware of the changes.
> [osprofiler] clean up helper functions

- openstack/cronus/files/nginx.tmpl
- openstack/cronus/templates/cronus/_config.yaml.tpl
- openstack/cronus/values.yaml
This will enable cronus SMTP listener to get an info about the real client IP address
> [cronus]: enable PROXY protocol support

- openstack/octavia/ci/test-values.yaml
- openstack/octavia/templates/etc/_octavia.conf.tpl
- openstack/octavia/templates/octavia-seed.yaml
Octavia didn't use service passwords before, but derived its passwords from the master password.
> [Octavia] Don't fall back to deriving master password

- openstack/nova/templates/seed.yaml
Instead of using the ironic service user to access Ironic, we want to
use the nova service, because that makes it easier to deploy new ironic
user passwords. This will be done in 2 steps:
1) give the nova service user the appropirate roles to be baremetal admin
2) change the username/password to use the nova user
This is step 1).
> [nova] Prepare accessing Ironic via nova user

- openstack/cinder/templates/seed.yaml
This patch removes the cinder nanny from the cinder seed template
as it already exists in the nannies chart.
> [Cinder]  Remove the cinder nanny from seed

- openstack/cinder/templates/seed.yaml
This patch removes the dependent cinder_nanny user role assignments
for the seeder.  These are done in the nannies charts now.
> [Cinder] remove cinder_nanny seeder roles

- prometheus-exporters/network-generic-ssh-exporter/templates/_config.yaml.tpl
- system/infra-monitoring/vendor/atlas/templates/configmap.yaml
For audit purposes there needs to be a continuous monitoring of the configured NTP servers. We do that utilising OS specific commands on the ssh_exporter. The atlas SD has to be expanded to include core routers, with different parameters per OS.
> Monitor configured NTP servers (fqdn) for audit purposes

- openstack/swift/templates/_utils.tpl
- openstack/swift/templates/etc/_proxy-server.conf.tpl
- openstack/swift/values.yaml
Esp. during high load situations, e.g. replication, there can be situations
where a proxy request calling out to its backend servers running in the
node_timeout. This leads to long runners and nginx timeout kicked in too
early. The result was a 504 for the client and a swift proxy request finishing
after that timeout.
> [swift] increase nginx proxy timeout

- global/prometheus-alertmanager-operated/Chart.yaml
- global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl
this is mainly to handle multi-tier alerts by service
> [alertmanager] rm tier from generic service routing

- system/prometheus-infra/templates/_prometheus-infra.yaml.tpl
This will stop thousands of auth alerts
> [cronus]: monitor /healthz location in order to avoid auth alerts

- openstack/cinder/templates/etc/_resource_filters.json.tpl
This patch updates cinder's resource_filters.json
file to include name in the volume filter keys.
The train release removed a deprecated feature
that causes the openstack client to not filter
volumes correctly as it doesn't support microversions
in the cinder api.
> [cinder] add name to resource filter

- openstack/cinder/templates/etc/_cinder.conf.tpl
This patch doubles the rpc_response_timeout.   All regions have
already been updated manually to 600.
> [cinder] Update the default rpc_response_timeout to 600

- prometheus-exporters/netapp-exporter/charts/netapp-cap-exporter/alerts/netapp-capacity.alerts
add a critical alert when flexvols reach 8.5tb usage and use a new playbook
@chuan137 - please wait with pulling this in and rolling it out
> [na cap exp] add critical alert for flexvols

- openstack/cinder/templates/vcenter_datacenter_cinder_deployment.yaml
This should make the cinder-volume pods restart if one of their
configmaps changes, but the deployment doesn't. This follows the
principle already in use by Nova.
> [cinder] Add configmap hashes as annotations

- system/multicloudtest/templates/config.yaml
- system/multicloudtest/templates/cronjob.yaml
- system/multicloudtest/values.yaml
- Additional config map that holds the test configuration for all hyperscaler in one region.
- Regions, Zone, NAT IPs and other region specifics are configured via secrets
- Mounted into the same directory as other config files, adapted the run command
> [Multicloudtest] Adds regional test configuration

- openstack/swift/templates/_utils.tpl
- openstack/swift/templates/envoy-bin-configmap.yaml
- openstack/swift/templates/envoy-deployment.yaml
- openstack/swift/templates/etc/_haproxy.cfg.tpl
- openstack/swift/templates/etc/envoy-cluster-configmap.yaml
- openstack/swift/templates/etc/haproxy-cluster-configmap.yaml
- openstack/swift/templates/proxy-deployment.yaml
- openstack/swift/templates/proxy-internal-service.yaml
- openstack/swift/values.yaml
Add support for NodePort on proxy-internal-service
* Optional NodePort for proxy internal service
* Proxy Deployment AntiAffinity will recognize this
* Mention option in `values.yaml`
HAProxy config to loadbalance swift proxies
* If multiple upstreams are defined, loadbalance them
* `/healthcheck` removes unavailable upstreams from loadbalancing
* check down servers only every 30s (allows specifying all k8s nodes in the cluster if NodePort is active on service)
* If none are defined, use k8s cluster internal DNS for the swift-proxy-internal service
* make upstream consumption a `define`
//cc @majewsky
> [Swift] support HAProxy builtin load balancing 

- openstack/keystone/templates/etc/_policy.yaml.tpl
It is too difficult to set up the new policies so that they don't break anything. Restore access to the level it was before and to set the base for further improvements.
Use policies from the old json file to restore access to the service to pre-change level.
> [keystone] fix policies by copying them from json

- openstack/keystone/templates/etc/_wsgi-keystone.conf.tpl
According to CCM-18723, sometimes keystone fails to respond, with the
following message logged at the ingress controller:
upstream prematurely closed connection while reading response header from upstream
As per https://trac.nginx.org/nginx/ticket/1484#comment:4, it
might be a known issue and increasing KeepAliveTimeout for
keystone-api's apache might help.
> [keystone] Increase KeepAliveTimeout to fix keepalive requests

- openstack/nova/templates/flavor-seed.yaml
- openstack/sap-seeds/templates/flavor-seed.yaml
**nova/flavors: Remove 15 discontinued flavors**
The discontinued BigVM flavors remain, until replaced with matching HANA flavors.
Some of the removed flavors will be replaced with new flavors in a later commit.
---
**nova/flavors: Move OS default flavors to sap-seed**
Move "m1.medium", "m1.large", "m1.xlarge" from nova to sap-seeds flavor-seed list, unifying the lists into one.
Two flavors where not moved but removed:
- `m1.tiny` is discontinued
- `m1.small` was a duplicate and already existed in the sap-seed.
---
**nova/flavors: Rename & alias flavors to g/c/m scheme**
Rename all public, non-hana-used flavors to the new naming scheme and add the old name(s) as "config:alias" extra_spec.
This effectively deprecates the old flavor names, however they will still appear in `openstack flavor …
> nova/flavors: Introduce new g/c/m naming scheme

- openstack/keystone/templates/etc/_mpm_event.conf.tpl
Fixes CCM-18723
Listener process serves MaxRequestsPerChild requests, shuts down,
closes all open connections, we run into the race condition described
in the bugreport. Using the default value will remove this limitation
> [keystone] Use default MaxRequestsPerChild (0)

- openstack/neutron/templates/configmap-etc-apod.yaml
- openstack/neutron/templates/etc/_ml2-conf.ini.tpl
- openstack/neutron/templates/statefulset-network-agent-apod.yaml
- openstack/neutron/templates/statefulset-network-agent.yaml
This PR implements the following logic to support aPods:
- Enables per-apod network-agents Statefulset if `.Values.agent.apod` is true and aPods are provided in values, eg:
```
apods:
qa-az-1a:
- apXXX
qa-az-1b:
- apYYY
```
- `neutron-etc-apod` configmap contains config files for each aPod
- Existing agents will not be scheduled on aPod VMs (based on node label)
> [neutron] create network agents per aPod

- openstack/swift/bin/haproxy-start
- openstack/swift/templates/haproxy-deployment.yaml
- openstack/swift/templates/proxy-deployment.yaml
Remove the K8S Node hosting this HAProxy from the server list
Reason: Healthchecks against the NodePort on the local machine will use kube-proxy
and therefor end up on swift-proxy annouced by the Endpoint for the NodePort Service.
This leads to the situation that the server running this haproxy is considered healthy
and all subsequent request with that target will also use kube-proxy, which obfuscates
the real target for a request.
Worst case, the HAProxy looses one swift-proxy target to load balance to, if a
swift-proxy runs on the same K8S node as HAProxy does. Soft anti-affinity rules try
to avoid sceduling HAProxy to a node with swift-proxy and vice versa.
> [Swift] HAProxy - Modified server list

- openstack/glance/templates/etc/_glance-api.conf.tpl
- openstack/glance/values.yaml
workers.
- needed for https://github.com/sapcc/glance_store/pull/2
- set 4 workers per replica as 10 by default caused issues
- increase number of replicas as number of workers was reduced.
> [glance] set the number of threads for glance_store and set number of

- openstack/sap-seeds/templates/flavor-seed.yaml
We want to deploy the HANA flavors more urgently to prod than the aliases. Gardener is still testing aliases in qa-de-1.
Revert commits:
- 8aa311a294301a636b5f190bbea772733a18c660
- 3cfbe46c250acd1c40610e4ee3aa078948f013af
> nova/flavors: Revert "Rename & alias flavors to g/c/m scheme"

- openstack/nova/values.yaml
A maximum of two hosts can fail before memory reservations start to
prevent memory-reserved VMs from spawning.
If the max-hosts setting fails for some reason, the fallback config
says that spawning reserved-memory VMs is prohibited after 80% of
_available_ memory is used up.
> nova/memoryreservation: Set reservation-limits config defaults

- openstack/cinder/templates/api-deployment.yaml
- openstack/cinder/templates/backup_deployment.yaml
- openstack/cinder/templates/scheduler-deployment.yaml
- openstack/cinder/templates/vcenter_datacenter_cinder_deployment.yaml
- openstack/cinder/values.yaml
This patch parameterizes the imagePullPolicy to allow a region to
change the default of 'IfNotPresent' to something else.  This allows
for testing patches against qa-de-3 and have the deployment always pull
the image, thus avoiding stale cached images.
> Allow updating imagePullPolicy

- openstack/cinder/templates/backup_deployment.yaml
After trying this in qa-de-3, the backup service didn't deploy. I
believe it's due to this templating format.
> [cinder] Fix the cinder backup_deployment template

- prometheus-exporters/vrops-exporter/alerts/host.alerts
Changed the count of powered on VMs (VM collector) to the amount of running VMs on the host (host collector). This metric only considers powered on VMs. 
https://docs.vmware.com/en/vRealize-Operations-Manager/8.3/com.vmware.vcom.core.doc/GUID-C3CAAE15-2E83-431F-8F2D-C5297A3B6EA9.html : `This excludes powered off VMs as they do not impact ESXi performance.`
In that way we don't miss the critical alert, in case the VM collector doesn't work as expected.
> vrops-exporter: HostWithRunningVMsNotResponding changed running VM metric

- prometheus-exporters/elastic-query-exporter/files/elasticsearch_octobus_vmdown.cfg
Temporary exclusion until Tars logs to its own index
> [elastic-query-exporter] Exclude tars logs

- openstack/neutron/templates/etc/_neutron.conf.tpl
This PR disables filter-validation API extension. We need it because we have lots of scripts and custom changes in our API so we cannot be sure that everything works well with "unknown" Neutron's fields.
By default this option `filter_validation` enabled: https://github.com/sapcc/neutron/blob/stable/ussuri-m3/neutron/conf/common.py#L127
Related to release notes:
```
---
prelude: >
Perform validation on filter parameters on listing resources.
features:
- |
Starting from this release, neutron server will perform validation on
filter parameters on list requests. Neutron will return a 400 response
if the request contains invalid filter parameters.
The list of valid parameters is documented in the neutron API reference.
Add an API extension ``filter-validation`` to indicate this new API …
```
> Disable filter-validation extension.

- openstack/swift/templates/etc/_proxy-server.conf.tpl
- openstack/swift/values.yaml
Large Glance images may include 100s of segments per container.
Deletion of such images sometimes often fails with 'HTTP 409 Conflict'
response from Swift. Enabling this option seem to resolve the problem.
The delete_container_retry_count parameter is used during a bulk delete of objects
and their container. This would frequently fail because it is very likely that
all replicated objects have not been deleted by the time the middleware got a
successful response. It can be configured the number of retries. And the
number of seconds to wait between each retry will be 1.5**retry
> [swift-proxy] enable 'delete_container_retry_count' for bulk operations.

- prometheus-exporters/vrops-exporter/alerts/datastore.alerts
New (local) NVMe swap datastore. According to Thomas Thimm no critical alert needed. As requested, created separate alert with 85% threshold.
> vrops-exporter: nvme datastore utilization alert

- openstack/cinder/templates/etc/_cinder.conf.tpl
This patch adds the coordination section to the cinder.conf
to enable tooz memcached based coordinated locks for each cinder
service.
> [cinder] Added the memcached coordination config

- openstack/swift-utils/alerts/caretaker.alerts
- openstack/swift-utils/ci/test-values.yaml
- openstack/swift-utils/templates/account-caretaker-mergify-deployment.yaml
- openstack/swift-utils/templates/caretaker-configmap.yaml
- openstack/swift-utils/templates/prometheus-alerts.yaml
- openstack/swift-utils/values.yaml
With https://github.com/sapcc/swift-account-caretaker/pull/18 swift-account-caretaker
can emit statsd metrics for the number of Swift Accounts which are orphan.
Collect them with the statsd-exporter and create alerting for it.
> [swift-utils] Collect metrics from caretaker

- openstack/sap-seeds/templates/flavor-seed.yaml
Looks like Flavor do not work in vSphere with odd RAM numbers
> Fixing odd RAM values to even RAM values

- openstack/neutron/templates/daemonset-metadata-agent.yaml
- openstack/neutron/templates/statefulset-network-agent-apod.yaml
* with aPod setup amount of cp nodes will increase drastically, and it does not make sense to run metadata agents as DaemonSet there, hence it will run as a sidecar
* if apod is enabled in the region, metadata agents are not scheduled on apod nodes
> [neutron] run metadata agent as sidecar on apod nodes

- common/pgmetrics/Chart.yaml
- common/pgmetrics/templates/deployment.yaml
Hi @majewsky 
Please validate this PR, i saw sentry mentioned in the DOOP dashboard. Later i found few of your services still use pgmetrics.
Regards,
Rajiv
> [common][pgmetrics] use metrics image from dockerhub mirror

- system/kube-system-kubernikus/Chart.lock
- system/kube-system-kubernikus/Chart.yaml
This PR adds the [metrics-server](https://github.com/sapcc/helm-charts/tree/master/system/metrics-server) and [vertical pod autoscaler](https://github.com/sapcc/helm-charts/tree/master/system/vertical-pod-autoscaler) to the kube-system-kubernikus chart.
> [kube-system-kubernikus] adds metrics-server, vpa in recommendation mode

- openstack/cinder/templates/etc/_cinder.conf.tpl
This patch adds the nova section to cinder.conf to
tell cinder to use the nova admin interface when making
callbacks to nova.   This is so we don't get message notification
errors due to policy permissions.
> [Cinder] Update cinder.conf to use admin endpoint

- openstack/keystone/templates/etc/_keystone.conf.tpl
Nova and others hopefully forward the global request id, and this should
allow us to identify the original api call causing the local request.
Since keystone is not calling out to other services, the header won't be set in the ingress so the change is limited to logging only.
> [Keystone] log global_request_id

- openstack/cinder/templates/api-ingress.yaml
- openstack/cinder/templates/etc/_cinder.conf.tpl
This sets the value in the ingress and log it with a g-prefix to differentiate
it from the normal request id. If the request comes over nova-api, nova will forward the request-id to cinder.
Cinder should forward the very same id then to other services (e.g. glance, or back to nova in case of call-backs)
It has been added after the normal logging-context string:
logging_context_format_string = %(process)d %(levelname)s %(name)s [%(request_id)s %(user_identity)s] %(instance)s%(message)s
If the request did not came in over ingress (e.g. internally by the service) it will render to gNone
> [Cinder] Set Openstack Request Id in Ingress

- prometheus-exporters/vrops-exporter/alerts/host.alerts
Reverts sapcc/helm-charts#2408 because vROps returns the last number of virtual machines on the host despite disconnected host.
> Revert "vrops-exporter: HostWithRunningVMsNotResponding changed running VM metric"

- openstack/nova/templates/api-ingress.yaml
- openstack/nova/templates/etc/_nova.conf.tpl
- openstack/nova/templates/placement-ingress.yaml
Various openstack services support forwarding a global request id since Pike.
This sets the value in the ingress and log it with a g-prefix to differentiate
it from the normal request id.
> [nova] Set Openstack Request Id in Ingress

- openstack/ironic/templates/api-ingress.yaml
- openstack/ironic/templates/etc/_ironic.conf.tpl
Nova (and hopefully other services) forward a global request id since Pike.
This sets the value in the ingress and log it with a g-prefix to differentiate
it from the normal request id.
It has been added after the normal logging-context string:
logging_context_format_string = %(process)d %(levelname)s %(name)s [%(request_id)s %(user_identity)s] %(instance)s%(message)s
If the request did not came in over ingress (e.g. internally by the service) it will render to gNone
> [Ironic] Set Openstack Request Id in Ingress

- system/elk/vendor/fluent/templates/_fluent.conf.tpl
The log format for many openstack applications has been changed
to print a global request id, which is fairly strict in its format (req-<uuid>).
To be sure, that we do not parse something else as the global request id, the expression is equally strict.
The value is stored in global_requestid instead of adding it as another request id.
This allows us to easily identify the global request id in the search as it is its own field.
The logs are currently still printing the msecs twice. E.g. time,msecs.msecs.
In order to be able to remove that redundancy, make the .number field optional
> [ELK] Optionally parse global_request_id and duplicate msecs

- openstack/neutron/templates/etc/_neutron-policy.json.tpl
This PR adds rules `create_port:fixed_ips:ip_address` and `create_port:fixed_ips:subnet_id` to fix 403 error when you try to create port in RBAC shared network:
```
HttpException: 403: Client Error for url: https://network-3.qa-de-1.cloud.sap/v2.0/ports, (rule:create_port and (rule:create_port:fixed_ips and (rule:create_port:fixed_ips:subnet_id and rule:create_port:fixed_ips:ip_address))) is disallowed by policy
```
These rules exist before but only in Ussuri release they were fixed and start working. As result we had problem with default value of rule `create_port:fixed_ips:ip_address` because by default it does not allow `ip_address` (https://github.com/openstack/neutron/blob/master/neutron/conf/policies/port.py#L124)
> Add rules create_port:fixed_ips:ip_address and create_port:fixed_ips:subnet_id to fix 403 error in Ussuri release

- openstack/sap-seeds/templates/flavor-seed.yaml
VMware requires flavor RAM sizes to be a multiple of four MiB.
> flavors: Make HANA RAM sizes multiple-of-4

- openstack/sap-seeds/templates/flavor-seed.yaml
IDs were changed to 300s.
Flavors with >128 vCPUs need socket setting and newer vmware version.
This is the first flavor with "hw:cpu_cores" set to 3.
> nova/flavors: Add attrs for hana_c384_m5835 & ID update

- openstack/neutron/requirements.lock
- openstack/neutron/templates/etc/_neutron-policy.json.tpl
This PR adds new policies that were added in Ussuri release. Without this fix, `allowed_address_pairs` will not work.
> Add new policies for Ussuri release

- openstack/swift/templates/etc/_proxy-server.conf.tpl
This enables support for application credential access rules available since Keystone Train.
This has the benefit, that you can create for the same user, multiple credentials which allow only access to a certain container within Swift. One can hand out access to different containers to different application, without entering the User in the container ACL
Example for allow container listing in container test and download of all objects in container test:
```
openstack application credential create ac1 --role swiftoperator --access-rules '[
{
"method": "GET",
"path": "/v1/AUTH_<PROJECT_ID>/test",
"service": "object-store"
},
{
"method": "GET",
"path": "/v1/AUTH_<PROJECT_ID>/test/**",
"service": "object-store"
}
]'
```
> [Swift] application credential access rules

- openstack/neutron/templates/etc/_neutron-policy.json.tpl
This PR provides to the end-user simple access for BGPVPNs. The end-user should be able to:
1. get own bgpvpn by ID
2. get list of own bpgvpns
3. create/update/delete/get router associations for own bgpvpns
To get bgpvpn or association the end-user must have role `network_viewer` and be owner of this resource. To create/update/delete router association the end-user must have role `network_admin` and be owner of this resource.
> Change policy.json to show bgpvpn for the end-user and give him control for router associations.

- openstack/neutron/templates/etc/_neutron.conf.tpl
This PR temporarily decreases the number of threads for `oslo.privsep` library to `1` (defaults to the number of CPU cores in the system). Full description of option here: https://docs.openstack.org/neutron/ussuri/configuration/neutron.html#privsep
This option was added in the commit: https://github.com/openstack/oslo.privsep/commit/f368430f13183c3d09d68c80184d854449da2e87 and we updated the library with Ussuri release. 
Need to check will this fix resolves the problem with `OSError: Premature eof waiting for privileged process` or not. Example of error:
```
OSError: Premature eof waiting for privileged process
File "oslo_messaging/rpc/server.py", line 165, in _process_incoming
res = self.dispatcher.dispatch(message)
File "oslo_messaging/rpc/dispatcher.py", line 276, in dispatch
return …
```
> Add option thread_pool_size for neutron to decrease number of threads for privsep library.

- openstack/neutron/templates/statefulset-network-agent.yaml
This option will allow us to distinctively disable the controlplane
agents. Required for regions where we have fully switched to the apod
design.
---
Dictated but not read.
> [neutron] Add opt to disable controlplane agents

- openstack/swift/templates/etc/_proxy-server.conf.tpl
- openstack/swift/templates/etc/_swift.conf.tpl
- openstack/swift/values.yaml
If `X-System-Catalog` is retrieved from `keystonemiddleware`, the default 8KB allowed header size might be an issue in regions with larger catalogs.
> [Swift] max_header_size = 16384

- openstack/neutron/templates/statefulset-network-agent.yaml
- openstack/neutron/values.yaml
With a defaultfilter the controlplane will be set to true whenever it's
false, essentially taking away the option to set it to false. Therefore
we now add it to our default values andset it to true. Now we should be
able to override it.
> [neutron] Don't override controlplane value

- openstack/nova/templates/migration-job.yaml
- openstack/nova/templates/online-migration-job.yaml
- openstack/nova/templates/update-cells-job.yaml
This fixes a problem, where the labels where put directly under metadata
instead of a metadata.labels in all our Jobs.
> [nova] Put metadata labels under labels key

- prometheus-exporters/network-generic-ssh-exporter/alerts/asr.alerts
- prometheus-exporters/snmp-exporter/alerts/snmp-asr.alerts
NetworkAsrRedundancyReplicationErrors: Measures if there are failures observed when replicating NAT sessions.
NetworkAsrHighCpuUtilization: Indicated >80% CPU Utilization for more than 20mi
NetworkAsrBgpPeerDown: Alerts if a peering to the Core routers, to ACI or within the Neutron Mesh went down
NetworkAsrNatGatekeeperCacheOverflow: Alerts if the Gatekeeper Cache is exhausted
NetworkAsrInterfaceOverUtilization: Playbook to be moved
NetworkAsrHighQfpCpuUtilization
> Define new Neutron ASR alerts

- system/kube-system-metal/Chart.yaml
- system/kube-system-metal/values.yaml
The value can be set in each ingress where required, otherwise it will print a hypen '-'
It is currently set in various openstack services, and allows us to correlated more easily the request
between the nginx and the upstream service
> [nginx-ingress] Log global_request_id variable

- system/kube-system-metal/values.yaml
This fixes 4d1707fe8c7347c17b6b1765ed7cba638cf862d1
> [nginx-ingress] proxy_alternative_upstream_name is not yet a variable

- system/elk/vendor/fluent/templates/_fluent.conf.tpl
The previous version was buggy due to a '1' at the end of the request path,
so it is rather unlikely that we rely on the nameing of the values here.
The new version parses all the fields defined in the default access-logs
as they are named in the ingress nginx definition.
Additionally the global_request_id will be parsed, if set.
It strips the prefix "req-" in case it is there, so we can search just for the uuid,
and ensure that it matches the openstack logs, where we strip the "greq-" prefix.
> [ELK] Parse nginx ingress access logs and global-request-id

- openstack/neutron/templates/etc/_neutron.conf.tpl
- openstack/neutron/templates/ingress-server.yaml
Nova (and hopefully other services) forward a global request id since Pike.
This sets the value in the ingress and log it with a g-prefix to differentiate
it from the normal request id.
It has been added after the normal logging-context string:
logging_context_format_string = %(process)d %(levelname)s %(name)s [%(request_id)s %(user_identity)s] %(instance)s%(message)s
If the request did not came in over ingress (e.g. internally by the service) it will render to gNone
> [Neutron] Set Openstack Request Id in Ingress

- openstack/swift/templates/etc/_proxy-server.conf.tpl
- openstack/swift/values.yaml
As per doc:
To speed up the bulk delete process, multiple deletes may be executed in
parallel. Avoid setting this too high, as it gives clients a force multiplier
which may be used in DoS attacks. The suggested range is between 2 and 10.
Glance image deletion logic was rewritten to use bulk deletions along
with retry mechanism: https://github.com/sapcc/glance_store/commit/467a09a93ae1421949d0b6c62f060141307d8f71
While this has reduced the number of conflict errors, there are still
some cases happening in regions with the most load.
> [swift] add configurable 'delete_concurrency' for bulk deletions.

- openstack/octavia/values.yaml
verification.
The load_balancer table is big and changes a lot.
This should reduce the number of failed backup verifications.
> [octavia] use tags and session_persistence tables for db backup

- openstack/nova/templates/etc/_nova.conf.tpl
Starting with queens, it's possible to configure authentication values
in the [cinder] section of nova.conf. We didn't do that until know,
because we didn't notice until recently, where some sentry events told
us about this.
Usually, these auth values are not necessary as volume operations happen
with the user token and thus its auth or the [service_user] section's
auth value if the user-token expired. But there are situations where
Nova has to act without user-token e.g. on startup where Nova continues
interrupted deletions of instances and might have to detach volumes.
> [nova] Configure authentication to Cinder

- openstack/neutron/templates/asr_config_agents/_deployment-asr1k.yaml.tpl
- openstack/neutron/templates/deployment-aci-agent.yaml
- openstack/neutron/templates/deployment-f5-agent.yaml
This PR will add additional labels for neutron `asr1k`, `f5`, `aci` agents. How it was before:
```
name=neutron-asr1k-agent-01,pod-template-hash=7d57f7c4d7
name=neutron-asr1k-agent-02,pod-template-hash=6d98fc7c85
name=neutron-asr1k-agent-03,pod-template-hash=77487554d9
```
How it will be:
```
application=neutron,component=asr1k-agent,name=neutron-asr1k-agent-01,pod-template-hash=7d57f7c4d7
application=neutron,component=asr1k-agent,name=neutron-asr1k-agent-02,pod-template-hash=6d98fc7c85
application=neutron,component=asr1k-agent,name=neutron-asr1k-agent-03,pod-template-hash=77487554d9
```
So we will be able to filter pods by type of agent.
> Add labels for filtering neutron agents

- openstack/swift/requirements.lock
- openstack/swift/templates/servers-daemonset.yaml
* Adding readiness probe for server pods to speed up deployments w/o general 60s wait time
* update redis chart requirement
> Swift readiness probe for swift_server pods

- system/kube-system-metal/values.yaml
nginx-ingress-external-controller seems to be more strict with unset variables,
so we simply set the global_request_id to a default '-'
> [nginx-ingress] Set a default for global_request_id

- openstack/cinder/templates/etc/_cinder.conf.tpl
- openstack/cinder/templates/seed.yaml
To use the os-server-external-events endpoint of Nova, e.g. for
informing Nova about the extension of an attached volume, Cinder needs
to use proper credentials and also needs the cloud_compute_admin role in
the token's scope.
> [cinder] Configure access to Nova

- openstack/blackbox/charts/blackbox-tests-integrity/alerts/vmware-host.alerts
covered by a vrops alert called `HostWithRunningVMsNotResponding`
https://github.com/sapcc/helm-charts/blob/0abc46b82f29c4de50a1317f930cc7fd695c3e87/prometheus-exporters/vrops-exporter/alerts/host.alerts#L4-L21
> [blackbox-test-integrity] removed ESXiHostWithAssociatedVMsNotResponding alert

- prometheus-exporters/vrops-exporter/alerts/host.alerts
https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vcenterhost.doc/GUID-96BD6016-4BE7-4B1C-8269-568D1555B08C.html
> [vrops-exporter] vCLS agent VMs excluded from VMsOnFailoverHost alert

- prometheus-exporters/vrops-exporter/alerts/nsxt.alerts
This is the first proof of concept to cover pre-made alerts from vrops.
> [vrops-exporter] added NSXTManagementServiceHasFailed

- prometheus-exporters/vrops-exporter/alerts/host.alerts
We must set HostWithRunningVMsNotResponding alert to info for now to solve an inconsistency.
> HostWithRunningVMsNotResponding alert set to warning

- prometheus-exporters/vrops-exporter/alerts/host.alerts
Excluded vCLS agent VMs for HostWithRunningVMsNotResponding alert. 
https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vcenterhost.doc/GUID-96BD6016-4BE7-4B1C-8269-568D1555B08C.html
> Excluded vCLS agent VMs

- openstack/keystone/templates/etc/_keystone.conf.tpl
During the upgrade to train messaging configuration got lost. Restore that configuration and remove old unnecessary checks around it.
> [keystone] reenable messaging

- openstack/nova/values.yaml
There are multiple problems we want to fix by not snapshotting a VM
before cloning its root disk.
1) Snapshotting with volumes attached can fail, because there's not
enough space for the full snapshot on the vVOL backend.
2) Snapshotting an instance can fail, if there's an old/buggy
VMware-tools version running inside a Windows guest.
3) Snapshotting can fail, if one of the volumes is on a storage having
IO profiles.
Most of the problems stem from the fact, that we attach volumes in
dependent mode, which means they are snapshotted together with the
instance.
Since Cinder only does a clone without snapshot and we haven't seen
problems with that, we will switch Nova to do the same.
> [nova] Don't snapshot a VM before cloning its disk

- openstack/nova/templates/hypervisors/hypervisors-kvm-kq.yaml
- openstack/nova/templates/hypervisors/hypervisors-kvm-kt.yaml
- openstack/nova/templates/hypervisors/hypervisors-kvm.yaml
- openstack/nova/values.yaml
We currently don't have the capacity to run any KVM hypervisors and thus
don't have to include the templates into our charts. It also hurts us,
as helm-diff finds changes for images, which the image-cache in the CI
tries to cache, but that are no longer updated/built and thus caching
never completes.
This commit also enables finding images for the CI entrypoint in the
kos-template for KVM hypervisors via the isImageTransportTemplating
value.
> [nova] Disable KVM hypervisor templates

- system/infra-monitoring/values.yaml
Query times out in Prometheus. Tested the scrape time locally via port-forwarding.
> [esxi-host-exporter] Increased scrape time

- common/rabbitmq/Chart.yaml
- common/rabbitmq/values.yaml
Default RabbitMQ cpu limit seems not to be enough sometimes as
we see container_cpu_cfs_throttled_seconds_total metric
accumulating for several Openstack services.
> Increate default RabbitMQ cpu limit to 5.

- openstack/neutron/alerts/api.alerts
- openstack/neutron/templates/configmap-etc-api.yaml
- openstack/neutron/templates/configmap-etc.yaml
- openstack/neutron/templates/deployment-rpc-server.yaml
- openstack/neutron/templates/deployment-server.yaml
- openstack/neutron/templates/etc/_api-paste.ini.tpl
- openstack/neutron/templates/etc/_neutron.conf.tpl
- openstack/neutron/templates/etc/_uwsgi.ini.tpl
- openstack/neutron/templates/service-server.yaml
- openstack/neutron/values.yaml
This PR adds the ability to run neutron-server in uWSGI application server
* Exports uwsgi metrics with memory, request, worker details to the statsd exporter to be ingested via prometheus
* Adds overloaded and socket queue congestion alerts
* neutron is configured to use heartbeat_in_pthread
* https://opendev.org/openstack/oslo.messaging/commit/22f240b82fffbd62be8568a7d0d3369134596ace
* This is to improve the `AMQP server on neutron-rabbitmq is unreachable` errors, it causes the oslo.messaging to run the regular heartbeat messages in a python thread instead on depending to be scheduled by eventlet.
* supported since train: https://docs.openstack.org/releasenotes/puppet-oslo/train.html
* enabled by default since wallaby: https://docs.openstack.org/releasenotes/oslo.messaging/wallaby.html, …
> [neutron] Introduce option to run neutron-api in uwsgi

- openstack/cinder/templates/migration-job.yaml
This patch adds the image version to the cinder migration
metadata job name.  This enables migration job to run only
when the image version changes.
> [Cinder] Fix migration job naming

- prometheus-exporters/elastic-query-exporter/alerts/logs.alerts
Better syslog field parsing is requested from Octobus team.
Until then we have to exclude these hosts from logshipping monitoring.
> [elastic-query-exporter] Exclude Swift ESX nodes

- common/prometheus-server/CHANGELOG.md
- common/prometheus-server/Chart.yaml
- common/prometheus-server/templates/prometheus-server.yaml
In our control plane Infra-Collector prometheus PodMonitors are not being scraped. Enabling the pod service discovery does not work, as we already have a job for this. Enabling the SD would cause pods being scraped twice.
Thus I would like to enable the podMonitorSelector by default.
> [common/promServer] Enables podMonitorSelector by default

- openstack/nova/templates/auto-assign-aggregates-kq.yaml
query was not running since we upgraded our k8s clusters to 1.15
> [nova] re-enables "nova-auto-assign-aggregates"

- openstack/cronus/Chart.yaml
- openstack/cronus/files/nginx.tmpl
- openstack/cronus/values.yaml
Reuse the latest ingress-nginx 3.36.0 helm-chart to set the regional hostname returned by nginx SMTP proxy on EHLO.
Was:
```
$ openssl s_client -crlf -quiet -connect cronus.qa-de-1.cloud.sap:587 -starttls smtp
EHLO localhost
250-cronus
```
Now:
```
$ openssl s_client -crlf -quiet -connect cronus.qa-de-1.cloud.sap:587 -starttls smtp
EHLO localhost
250-cronus-qa-de-1-cloud-sap
```
> [cronus]: sync the nginx template from upstream

- system/maintenance-controller/Chart.yaml
- system/maintenance-controller/templates/manager.yaml
controller-runtime exposes go runtime/app metrics by default on port 8080
> maintenance-controller: enable metrics scraping

- openstack/cinder/values.yaml
This patch enables the Cinder Affinity/AntiAffinity filter.
This enables users to ensure that volumes can be created on the same
cinder host as another cinder volume, or opposite of another cinder
volume.
cinder create --hint same_host=<volume UUID> ....
cinder create --hint different_host=<volume UUID> ...
> [Cinder] Enable AffinityFilter

- prometheus-exporters/elastic-query-exporter/alerts/logs.alerts
* Add monitoring swift nodes as they're now parsed to node.nodename
* Only alert when host is not in maintenance mode
* Use block scalar style for better readability
> [elastic-query-exporter] Adjust Octobus logshipping alert

- system/kube-monitoring-scaleout/values.yaml
- system/kube-system-admin-k3s/Chart.lock
- system/kube-system-admin-k3s/Chart.yaml
- system/kube-system-kubernikus/Chart.lock
- system/kube-system-kubernikus/Chart.yaml
- system/kube-system-kubernikus/values.yaml
- system/kube-system-metal/Chart.lock
- system/kube-system-metal/Chart.yaml
- system/kube-system-metal/values.yaml
- system/kube-system-scaleout/Chart.lock
- system/kube-system-scaleout/Chart.yaml
- system/kube-system-virtual/Chart.lock
- system/kube-system-virtual/Chart.yaml
The payed docker hub accounts are expired and we are not supposed to use docker hub anymore.
> kube-system-*: Remove pull secret injector

- openstack/swift/alerts/openstack/api.alerts
* Relax OpenstackSwiftUsedSpaceGrow to 2 days, as it may be only temporary groth
* New Info Alert for Used Space = 66%
* New Info Alert if granted quota exceeds capacity by 25%
* New Warning Alert if granted quota exceeds capacity by 50%
> [swift] New capacity and overbooking alerts

- ci/config.yaml
- system/kube-system-scaleout/Chart.lock
- system/kube-system-scaleout/Chart.yaml
- system/kube-system-scaleout/values.yaml
**DO NOT MERGE**
This PR catapults our ingress controllers in scaleout clusters into 2021. 
We can only go for `3.36.0` though as this is the last version supporting k8s 1.19 clusters.
Messy: The chart was renamed from `nginx-ingress` to `ingress-nginx` 🤷  which causes some value foo and requires careful deployment coordination.
> [kube-system-scaleout] ingress-nginx to 3.36.0

- prometheus-exporters/elastic-query-exporter/alerts/logs.alerts
This will be reverted as soon as syslog config is corrected via automation
> [elastic-query-exporter] Disable log shipping alerts for apods

- common/mariadb/Chart.yaml
- common/mariadb/templates/deployment.yaml
- common/mariadb/values.yaml
Not all deployments using MariaDB have a priorityClass, thus I propose setting the default in the values so that it can be omitted if not required
> [MariaDB] Makes priorityClass optional

- openstack/glance/requirements.lock
- openstack/glance/requirements.yaml
Binlog files are now purged after 60 minutes instead of directly after rotation. This is required for the database replication into the datahubdb to work.
> [Glance] Bumps mariadb chart to increase binlog file retention

- openstack/keystone/requirements.lock
- openstack/keystone/requirements.yaml
Binlog files are now purged after 60 minutes instead of directly after rotation. This is required for the database replication into the datahubdb to work.
> [Keystone] Bumps mariadb requirement to increase binlog file retention

- openstack/neutron/templates/etc/_ml2-conf-aci.ini.tpl
This option is used to override hostgroup AZs on a per-binding-host
basis.
> Support host_azs in ACI config

- prometheus-exporters/vrops-exporter/alerts/datastore.alerts
Exclude local datastore from alerting if host is in maintenance.
> [vrops-exporter] adjust datastore alerts to exclude hosts in MM

- openstack/neutron/templates/etc/_ml2-conf-aci.ini.tpl
This option will allow the driver to finalize portbindings on certain
hostgroups and will make binding dummy ports easier.
> Support finalize_binding in ACI config

- openstack/sap-seeds/templates/flavor-seed.yaml
@dhoeller @joker-at-work cc3test required custom flavor for server create (regular/hana) reasons : 
1. with hana flavor required to increase cc3test project quota as we spawning large VMs for checking new server create. 
2. with hana flavor putting load on BB with new test server create with large VMs ( which will got double after adding mount_volume check for BB) 
3. with hana/regular flavour lots of logic to put in code to pickup as smallest flavor as possible.
> added custom flavor for cc3test server create(regular/hana)

- openstack/swift/templates/haproxy-deployment.yaml
This introduces one haproxy deployment per AZ and per aPod.
Addtionally it creates a deployemnt per AZ for controlplane nodes for the transition period.
haproxy which should be scheduled to aPods, use nodeSelector `kubernetes.cloud.sap/apod`.
haproxy which should be scheduled to ControlPlane nodes use nodeSelector `failure-domain.beta.kubernetes.io/zone` and nodeAffinity not having label `kubernetes.cloud.sap/apod`.
The controlplane node handling should be removed after aPod Design is globally established.
Sceanrio 1 (aPod only)
```
haproxy_deploy_az1_apod1
haproxy_deploy_az1_apod2
haproxy_deploy_az2_apod3
```
Sceanrio 2 (aPod and ControlPlane)
```
haproxy_deploy_az1_apod1
haproxy_deploy_az1_cp
haproxy_deploy_az2_apod2
haproxy_deploy_az2_cp
```
Sceanrio 2 (ControlPlane only)
``` …
```
> [Swift] haproxy deployemnts per AZ/aPod

- openstack/nova/requirements.lock
- openstack/nova/requirements.yaml
Binlog files are now purged after 60 minutes instead of directly after rotation. This is required for the database replication into the datahubdb to work.
Also brings 
* [mariadb] reduce readiness probe initial delay
* [mariadb] change lifecycle pod script to sleep 1 between db pings.
> [Nova] Bumps mariadb requirement to increase binlog retention

- openstack/keystone/alerts/openstack/keystone.alerts
@BerndKue @rajivmucheli : please approve this and run keystone pipeline to get rid of absent metrics alerts
> metrics moved from cp to scaleout cluster

- openstack/ironic/templates/_conductor-deployment.yaml.tpl
- With rollingupdate, the new conductor pod will register itself as a new host in ironic db. Once it is up and running the old conductor pod will be terminated, and calls unregister host.
- increases timeout for liveness check
> [ironic]conductor: uses recreate strategy

- system/doop-central/templates/configmap.yaml
- system/gatekeeper-config/ci/test-values.yaml
- system/gatekeeper-config/templates/config-pod-labels.yaml
- system/gatekeeper-config/values.yaml
- system/gatekeeper/templates/constraint-pod-labels.yaml
Since there is [some Slack routing](https://github.com/sapcc/helm-charts/blob/master/global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl) that matches on `tier` or `service` only. I have made the policy such that only one of these labels is required.
However, when `tier == os` then service is also required and its value must be valid.
> system/gatekeeper: validate value of service label on Pods

- openstack/neutron/values.yaml
In at least one region, the dhcp-agent is regularly throttled a lot,
which makes ports hang in DOWN state for a longer period of time until
they are finally provisioned on the dhcp-agent.
> neutron: Increase dhcp-agent cpu limits to 1 cpu

- prometheus-rules/prometheus-kubernetes-rules/Chart.yaml
- prometheus-rules/prometheus-kubernetes-rules/alerts/health.alerts.tpl
- prometheus-rules/prometheus-kubernetes-rules/templates/_helpers.tpl
I checked the helm template rendering using:
```sh
helm template --dry-run prometheus-kubernetes-rules ./prometheus-rules/prometheus-kubernetes-rules
```
and it gave the expected output:
```yaml
labels:
tier: "{{ if $labels.label_tier }}{{ $labels.label_tier}}{{ else }}k8s{{ end }}"
service: "{{ if $labels.label_service }}{{ $labels.label_service}}{{ else }}resources{{ end }}"
```
/cc @majewsky
> Use tier and service labels from Pod for KubernetesPodRestartingTooMuch

- openstack/neutron/values.yaml
Network agents still suffer under slow buildup, therefore we add more
resources to them. The dhcp-agent should have at least 1 core, but can
consume up to 4, depending on how much is being used (they still run one
dnsmasq and haproxy per network). We also increase the limit of the
linuxbridge-agent to get it to build up faster.
> [neutron] Increase network agent resource requests

- system/bind/templates/deployment.yaml
We do not want to set the podAntiAffinity to tie it to bind1/2 since it is for a different region.
> [system][bind] adding the ability to remove podAntiAffinity for bind3

- prometheus-exporters/image-usage-exporter/Chart.yaml
There was an update to the exporter switching the image filter logic from whitelist to blacklist.
> Image Usage: bump version

- openstack/cinder/values.yaml
We want to have cinder enforce that 20% of the overall storage
on a backend is reserved.  This means that cinder will only allow
allocating up to 80% of the total storage on a backend.  This will
be more meaningful when datastores as pools is rolled out as then
each datastore can only be allocated to a max of 80% capacity.
> [Cinder] Set an overall reserved_percentage to 20%

- global/prometheus-infra/templates/_prometheus.yaml.tpl
- prometheus-exporters/snmp-exporter/_snmp-exporter-pxgeneric.yaml
- prometheus-exporters/snmp-exporter/generator/pxgeneric-generator.yaml
- prometheus-exporters/snmp-exporter/px.alerts/snmp-pxdlrouternxos.alerts
- prometheus-exporters/snmp-exporter/px.alerts/snmp-pxgeneric.alerts
- prometheus-exporters/snmp-exporter/templates/alerts.yaml
- prometheus-exporters/snmp-exporter/templates/configmap.yaml
- prometheus-exporters/snmp-exporter/values.yaml
- system/infra-monitoring/templates/_prometheus-infra-collector.yaml.tpl
- system/infra-monitoring/vendor/atlas/templates/configmap.yaml
We are getting IOS XR devices in PX. Some MIBs are equal over NXOS, IOS
XE and IOS XR. I am creating a new SNMP exporter module that covers
these MIBs, move all alerts and dashboard to the new metric and then
keep only the OS specific MIBs to the according OS specific snmp
exporter modules.
> Create snmp exporter module for OS independent MIBs

- openstack/keppel/templates/_utils.tpl
To match the respective code change in
sapcc/keppel#26.
> keppel: replace URL parameters with FQDN parameters

- common/mariadb/Chart.yaml
- common/mariadb/templates/alerts.yaml
- common/mariadb/templates/alerts/_health.alerts.tpl
- common/mariadb/values.yaml
We need this alert to be reacted on with high priority.
In most cases not ready DB means the respective service/API is
completely down.
> [common][mariadb] promote DBNotReady alert to critical.

- system/infra-monitoring/vendor/atlas/templates/configmap.yaml
I'm adding a new atlas discovery config for the new ASR9K routers.
The netbox url is this one [here](https://netbox.global.cloud.sap/dcim/devices/?q=rt&status=active&role=core-router&mac_address=&has_primary_ip=&local_context_data=&virtual_chassis_member=&console_ports=&console_server_ports=&power_ports=&power_outlets=&interfaces=&pass_through_ports=&cf_DC+Label=).
This config is tested and can discover both ASR9901 and ASR9902 routers in all regions.
> Added support in atlas for asr9k

- openstack/glance/templates/etc/_glance-policy.yaml.tpl
- openstack/glance/templates/seeds.yaml
This role explicitly allows user to set image visibility to public.
> [Glance] Introduce image_publicize_admin role

- openstack/neutron/templates/etc/_dnsmasq.conf.tpl
We don't expose openstack.$region.cloud.sap or its subdomains for
customers to register, but only use it locally in the current network
and on the local dnsmasq. Therefore, we want to configure dnsmasq to
also not recurse queries for this domain if they cannot be answered
locally.
This is supposed to fix a problem one of gardener's customers has, as
they use the search-domain for everything with less than 5 dots (i.e.
ndots 5 setting) and thus do multiple queries to the network's DNS
server for a "normal" domain like "www.googleapis.com".
> [neutron] Set search domain as local in dnsmasq

- prometheus-exporters/network-generic-ssh-exporter/templates/_config.yaml.tpl
- prometheus-exporters/network-generic-ssh-exporter/values.yaml
- system/infra-monitoring/vendor/atlas/templates/configmap.yaml
@swagner-de can you please have a look at this PR. This works only for the router stats (not peers) using the `show ntp stats` results. This doesn't need any changes to the ssh-exporter.
> Added support for asr9k (not peers) in ssh-exporter

- openstack/nova/templates/bigvm-deployment.yaml
- openstack/nova/values.yaml
We're going to phase out nova-bigvm in favor of HANA-only clusters and
thus need to selectively disable nova-bigvm deployments in certain
regions where this is already the case.
> [nova] Add option to disable nova-bigvm deployment

- openstack/neutron/templates/etc/_asr1k-global.ini.tpl
This will fix mistakenly not ignoring the az-hint
> Correct order of `default` call.

- openstack/swift/etc/statsd-exporter.yaml
With `statsd_exporter` 0.9.0 TTLs per mapping were introduced. This leads now to expiration of counters, which was not the case previously although we had the global TTL setting.
https://github.com/prometheus/statsd_exporter/blob/master/CHANGELOG.md#090--2019-03-11
To avoid absent alert flapping in underutilized regions, the async pending metrics do not expire with this setting.
> [Swift] do not expire async pending metrics

- openstack/vcf/configs/.gitignore
- openstack/vcf/templates/configmap.yaml
- openstack/vcf/templates/deployment.yaml
The config files for every pulumi stack is read from secrets repo and imported to a configmap. They are then mounted into the production pod. Each time the config file is modified, run pipeline to populate the changes to production pod.
> [vcf] mount config files to production pod 

- openstack/cinder/requirements.lock
- openstack/cinder/requirements.yaml
This patch updates the cinder helm chart to use rabbitmq chart 0.2.6
> [Cinder] Update rabbitmq from 0.2.0 to 0.2.6

- openstack/cronus/templates/cronus/_config.yaml.tpl
- openstack/cronus/values.yaml
since golang doesn't preserve map's order
> [cronus]: change backends map to a slice

- common/rabbitmq/Chart.yaml
- common/rabbitmq/ci/test-values.yaml
- common/rabbitmq/templates/_helpers.tpl
- common/rabbitmq/templates/deployment.yaml
- common/rabbitmq/values.yaml
- openstack/designate/values.yaml
- openstack/keystone/values.yaml
images.
Alternate region is used in a similar way like for keystone or mariadb
charts. In case Keppel down in the region - the service won't be able to
start.
Also bump chart.
> [common][rabbitmq] use keppel for rabbit images

- system/infra-monitoring/vendor/px-exporter/alerts/px-k8s.alerts
If the label_replace() regex is not matching, there results a metric
with an empty label set that is then aggregated by the sum() and
triggers an alert.
Let's filter on the regex on the label first, so we make sure it will
later match.
> Assure label_replace() regex always matches

- prometheus-exporters/pvc-exporter/templates/alerts/_pvc-usage.alerts.tpl
Alert on INFO level was missed recently, causing all openstack service
metrics go missing in eu-de-1 and no alerting possible.
> [prometheus-exporters] increase PVC full severity to Warning.

- openstack/manila/templates/type-seeds.yaml
Also remove share type BTP_Backup, it's not used in production.
> [manila] add hypervisor_storage_hanalytics in share type seeds

- openstack/nova/values.yaml
This filter checks for cpu compatability for live-migrations.
It requires that the corresponding filter is in the image
used for the deployment.
> [nova] Add CpuInfoMigrationFilter

- common/prometheus-server/CHANGELOG.md
- common/prometheus-server/Chart.yaml
- common/prometheus-server/templates/_helpers.tpl
- common/prometheus-server/templates/podmonitors/pod-sd.yaml
- common/prometheus-server/templates/servicemonitors/endpoint-sd.yaml
- common/prometheus-server/values.yaml
prep to drop high cardinality openstack_http_response_* metrics
> drop some metrics from pod-sd and endpoint-sd

- prometheus-exporters/vrops-exporter/alerts/host.alerts
As requested by operations team.
- Playbook linked
- InfraOps informed
> Raise HADetectedAPossibleHostFailure to critical

- openstack/cinder/values.yaml
This will force all thin provisioned regions to not allow
overprovisioning as compared to free space available.
> [Cinder] set default max_oversubscription to 1

- prometheus-exporters/snmp-exporter/generator/f5customer-generator.yaml
1.3.6.1.4.1.3375.2.1.14.2.2.1.2.2 is the second index of sysCmSyncStatusDetailsDetails, which looks like this:
`SNMPv2-SMI::enterprises.3375.2.1.14.2.2.1.2.2 = STRING: "cluster-02-qa-de-1 (In Sync): All devices in the device group are in sync"`
This allows us to use the cluster id string as a label for all metrics in the scrape config.
> [snmp-exporter] add f5 customer oid for cluster name

- openstack/cinder/values.yaml
This patch adds the SAPLargeVolumeFilter to the list of cinder
scheduler filters.  This forces all volumes > 2TB to not land
on vvol datastores.
> [Cinder] Add the SAPLargeVolumeFilter

- openstack/manila/requirements.lock
- openstack/manila/requirements.yaml
most likely to be done after xena upgrade
[rabbitmq] increase timeout for readiness probe to 3 sec
[rabbitmq] harmonize component label across charts
[mysql_exporter] remove mysql_database_size default metric as there is
pvc_exporter and respective alert now
[sql_exporter] allow to define additional custom metric sources in
values
[common][mysql_exporter] an attempt to add nova cell2 as a second
source for querying.
> [manila] helm outdated-dependencies update

- prometheus-exporters/vrops-exporter/alerts/datastore.alerts
@richardtief @rmueller-b1 
`VmfsDataStoreCapacity` alerts are turned off because a change is implemented in Openstack so that `Cinder` now has control over scheduling new volumes. It is also set so that a datastore is only filled to about 80%. We still monitor the average utilization of all datastores in a vCenter, but no longer monitor the datastores themselves.
> [alerts] rm VmfsDataStoreCapacity* for B1

- prometheus-exporters/openstack-exporter/alerts/cinder.alerts
- prometheus-exporters/openstack-exporter/requirements.lock
- prometheus-exporters/openstack-exporter/requirements.yaml
Since we moved to datastores as pools, this alert doesn't
make much sense.
> [Cinder] Remove the backend shard low overcommit critical

- common/mariadb/Chart.yaml
- common/mariadb/templates/backup-v2-deployment.yaml
- common/mariadb/templates/service.yaml
to remove multiple targets warnings.
Also put scrape annotations only to the deployment
> [mariadb-backup] removes unnecessary prometheus port scrape

- prometheus-rules/prometheus-kubernetes-rules/Chart.yaml
- prometheus-rules/prometheus-kubernetes-rules/alerts/health.alerts.tpl
As discussed 1:1 with Arno, it's true that these are inconsistent with the "tier" and "service" labels already present on alerts. But since we already have lots of metrics with a "service" label, setting "service" as a pod label would either break the existing metrics or vice versa.
> reinstate the "alert-tier" and "alert-service" labels for pod alerts

- openstack/manila/templates/shares/_share-netapp.conf.tpl
20 is the sweet spot for us.
Roughly calculated out of:
max 5000 volumes (NetApp limit on certain models)
max 256 SVMs (due to 2 lifs per svm and max 512 lifs NetApp limit)
@frr2018 fyi
to be deployed after xena upgrade
> [manila] reduce default number of volumes per svm

- prometheus-exporters/vrops-exporter/alerts/nsxt.alerts
1.  NSXTMgmtNodeImageFilesystemCapacityCritical uplifted to critical.
2. NSXTMgmtNodeLogFilesystemCapacityCritical uplifted to warning.
3. NSXTTransportNodeConnectivityNotUP uplifted to critical.
Above alerts are verified and discussed in global infraops meeting.
> Change severity of few NSXT alerts.

- openstack/keystone/values.yaml
Enable authenticate.success CADF messages and also remove mention of the non-existing authenticate.failure
> Enable authenticate.success CADF messages

- prometheus-exporters/vrops-exporter/alerts/host.alerts
Most alerts are for hosts in maintenance. This PR should reduce the noisy alert channels.
> [vrops-exporter] no alerting for hosts in maintenance

- openstack/keystone/values.yaml
Reverts sapcc/helm-charts#3152
The messages are too chatty and might overwhelm our systems. They will be reenabled soon after other changes get in
> Revert "Enable authenticate.success CADF messages"

- openstack/swift/templates/prometheus-alerts.yaml
- openstack/swift/templates/s3-cache-prewarmer-deployment.yaml
Last week's prewarming issues in Amsterdam made me wonder why we did not see any alerts. Turns out, not only did we not define an alert, the metric delivery was not working either. The default for `-listen` is `localhost:8080` instead of `:8080`, so Prometheus could not reach the metrics endpoint.
> swift: deliver metrics/alerts for s3-cache-prewarmer

- openstack/nova/values.yaml
We wanted to use those metrics to detect hanging nova-compute hosts, but
they were to unreliable for that and are responsible for some of the
slow queries logged by mariadb. Therefore, we remove them again.
> [nova] Remove some metrics not used in alerts

- prometheus-exporters/openstack-exporter/Chart.yaml
- prometheus-exporters/openstack-exporter/alerts/cinder.alerts
- prometheus-exporters/openstack-exporter/requirements.lock
- prometheus-exporters/openstack-exporter/requirements.yaml
This patch rewrites the cinder alerts for low storage available.
The new alerts rely on the newer openstack exporter that reports
on each individual datastore and how much free space is available
leftover until the reserved percentage is met.
> [Openstack-exporter]  upgraded the cinder alerts for pools

- prometheus-exporters/openstack-exporter/requirements.lock
- prometheus-exporters/openstack-exporter/requirements.yaml
The requirements.yaml had a local path to the openstack utils
dependency, which was causing CI to fail.  This patch updates
the requirements.yaml to point to a real url for the repository
> Update openstack exporter requirements

- prometheus-exporters/network-generic-ssh-exporter/templates/_config.yaml.tpl
> Added new metric for fetching the arp drop due to input queue full - Neutron routers (asr1k/c8500)
> New metric for arp drop due to input queue full

- openstack/keystone/templates/etc/_keystone.conf.tpl
Currently the lifesaver middleware grants 100 credits to a user and
takes 5-10 per failed operation, which allows only 10-20 failed
operations per minute. We can easily handle more than that, and some
failed operations are generated by cli, non-perfect terraform scripts
and just by simple small errors, that users should not be punished for.
Raise the amount of credits that the user is granted and make refill of
the credits faster. This will allow 5 times failed operations per minute
more.
> [keystone] Tolerate more errors in the lifesaver

- openstack/glance/templates/migration-job.yaml
Helm doesn't handle an update of jobs graciously as
it tries to change immutable fields.
The workaround is to change the name of the resource,
which results in the deletion and recreation
of said job, which causes it to run on
more often
> [glance] Change job name between versions

- openstack/elektra/Chart.yaml
- openstack/elektra/templates/deployment.yaml
To avoid multiple elektra pod scheduling on the same node
> [elektra] add podAntiAffinity

- openstack/octavia/alerts/octavia.alerts
With the new documentation system (hugo), playbook links with html at the end
usually work, but for some reason they don't for the stuck_pending link.
In order to enforce a uniform format (and not confuse future contributors), I
remove .html on every octavia playbook link.
> [octavia] Remove .html from playbook links

- openstack/nova/values.yaml
We want our pods to be easier to schedule onto nodes by only requesting
4 instead of 8 CPUs. For that to work, we reduce the number of spawned
worker processes inside the pods. To still achieve the same amount of
resources, we double the number of pods.
> [nova] Reduce workers in api and increase replicas

- prometheus-exporters/snmp-exporter/generator/f5physical-generator.yaml
The physical F5s do not run HA, they are standalone devices, no failover, no config sync.
> Remove HA related OIDs form f5physical generator

- prometheus-exporters/openstack-exporter/Chart.yaml
- prometheus-exporters/openstack-exporter/requirements.lock
- prometheus-exporters/openstack-exporter/requirements.yaml
This patch updates the openstack-exporter requirement for openstack
utils chart to 0.3.4
> [openstack-exporter] update latest openstack utils chart

- openstack/manila/requirements.lock
- openstack/manila/requirements.yaml
- openstack/manila/templates/etc/_manila.conf.tpl
- openstack/manila/templates/shares/_netapp-deployment.yaml.tpl
bump rabbit, maria and utils requirements with new affinity
add maintenance affinity for manila shares
reduce rpc pool connection ttl to 10 mins from default 20 mins
reduce the max time between rabbit reconnections from 30 sec to 3 sec
> [manila] improvements for stability due to maintenance/restarts

- openstack/manila/templates/shares/_netapp-deployment.yaml.tpl
```
/ # rabbitmqadmin -H $RABBIT_HOST -u admin -p $RABBIT_PASSWORD list bindings | grep manila-share-netapp-abc123
|                         | manila-share.manila-share-netapp-abc123@abc123             | manila-share.manila-share-netapp-abc123@abc123             |
| openstack               | manila-share.manila-share-netapp-abc123@abc123             | manila-share.manila-share-netapp-abc123@abc123             |
```
- activatedgeek/rabbitmqadmin:latest is for rabbit 3.6, we should probably in-house this
- I manually tried this in our staging region
> [manila] make sure manila-share is bound to rabbitmq

- prometheus-exporters/vrops-exporter/alerts/host.alerts
Taken maintenance mode into consideration when firing a native vrops alert.
> [vrops-exporter] Excluding MM hosts from vROps alerting

- openstack/manila/templates/bin-configmap.yaml
- openstack/manila/templates/bin/_fetch_rabbitmqadmin.sh.tpl
- openstack/manila/templates/shares/_netapp-deployment.yaml.tpl
fetches the rabbitmqadmin command directly from the running rabbit instance on init
followup to 5080b1eae46911b97dc2d010cb3b29afb0cdb420
which does not work, because in a deployment if the sidecar container liveness fails
only the affected container is restarted, not all of them (which is true only for
kind pod)
> [manila] share service liveness via rabbitmqadmin

- prometheus-exporters/vrops-exporter/templates/collector-configmap.yaml
Additional metrics request bei VMware to monitor vMotion activities and correlations.
> [vrops-exporter] Adding Cluster Metrics for vMotion Monitoring

- openstack/maia/templates/etc/_maia_scrape_config.yaml.tpl
These labels are maintained at the pod level to direct k8s alerts to the service-specific Slack channel, so scraping via pod SD will pick them up. They are an internal implementation detail of our alerting setup and should not be exposed to customers.
> maia: drop labels "alert_tier" and "alert_service" on ingestion

- openstack/nova/requirements.lock
- openstack/nova/requirements.yaml
- openstack/nova/templates/hypervisors/hypervisors-vmware-deployment-vct.yaml
We bump the utils chart here to get the
"kubernetes_maintenance_affinity" helper, so we can easily define the
affinity to operational nodes (compared to nodes waiting to upgrade) for
starts/restarts during k8s node maintenance.
> [nova] Reduce nova-compute restart during k8s node maintenance

- system/sentry/charts/postgresql/README.md
- system/sentry/charts/postgresql/templates/deployment.yaml
- system/sentry/charts/postgresql/templates/secrets.yaml
- system/sentry/charts/postgresql/templates/svc.yaml
- system/sentry/charts/postgresql/values.yaml
- system/sentry/requirements.lock
- system/sentry/requirements.yaml
Besides cleaning up the chart a bit, the primary motivation is to upgrade the postgres-exporter. There are two separate metrics pods in Sentry, both on ancient postgres-exporter versions:
- the pgmetrics chart includes the sentry-pgmetrics deployment using postgres-exporter v0.4.6 (the current version is v0.10.1)
- the postgres chart includes a sidecar container in the sentry-postgresql deployment at postgres-exporter v0.1.1 (!)
Since it's a bad idea anyway to stuff too many sidecars into the Postgres pod (since then every change to the sidecar requires restarting the DB), this PR gets rid of the second postgres-exporter entirely. Note that this causes a DB restart at deploy time.
There will be a separate PR in the secrets repo for the respective values.yaml change.
> sentry: update pgmetrics chart to 0.3.0

- global/prometheus-alertmanager-operated/Chart.yaml
- global/prometheus-alertmanager-operated/ci/test-values.yaml
- global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl
- prometheus-rules/prometheus-kubernetes-rules/Chart.yaml
- prometheus-rules/prometheus-kubernetes-rules/alerts/health.alerts.tpl
- prometheus-rules/prometheus-kubernetes-rules/alerts/kubelet.alerts.tpl
- prometheus-rules/prometheus-kubernetes-rules/alerts/maintenance.alerts.tpl
This PR introduces a new inhibition rule to prevent alerts for nodes in maintenance.
This is opt-in, by setting the label `inhibited-by: node-maintenance` on the alert that should be inhibited.
> Inhibit alerts for nodes in maintenance

- global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl
Hi @auhlig 
HSM Metrics are created by snmp exporter. I intend to create hsm.alerts file [here](https://github.com/sapcc/helm-charts/tree/master/prometheus-exporters/snmp-exporter/alerts)  post this PR is merged.
Please validate if this PR.
Regards,
Rajiv
> [HSM] Add Slack routing

- common/rabbitmq/Chart.yaml
- common/rabbitmq/templates/alerts/_health.alerts.tpl
most openstack services deploy for auditing an aliased version
with 'notifications' suffix. This change prevents the alert for the
rabbitmq without 'notifications' from firing if the 'notifications'
rabbitmq is not ready.
e.g.
```
(kube_pod_status_ready_normalized{condition="true",pod=~"manila-rabbitmq-notifications.*",pod!~"manila-rabbitmq-notifications-notifications.*"} < 1)
```
ugly, because this depends on the domain knowledge of how we usually name the audit alias
> [rabbitmq] improve too broad matching of health alert

- openstack/cinder/templates/etc/_cinder.conf.tpl
This patch adds the %(resource)s to the log context in each cinder log
entry.  Various places in cinder debug log entries adds the
resource=volume_ref attribute.  For example:
https://github.com/sapcc/cinder/blob/stable/train-m3/cinder/volume/manager.py#L332-L333
https://github.com/sapcc/cinder/blob/stable/train-m3/cinder/volume/drivers/vmware/vmdk.py#L1201-L1202
https://github.com/sapcc/cinder/blob/stable/train-m3/cinder/volume/drivers/vmware/vmdk.py#L2900
This will result in the volume id being added to the log entry whenever
the LOG.debug() has the kwarg of resource=volume.  This will help
with tracking down what volume was being operated on in the logs.
> [Cinder] Add the resource entry to log context

- openstack/keystone/values.yaml
The load is higher now and the default limits are now used instead
> [keystone-rabbitmq] use the default limits

- openstack/nova/templates/_helpers.tpl
- openstack/nova/templates/api-deployment.yaml
- openstack/nova/templates/api-metadata-deployment.yaml
- openstack/nova/templates/migration-job.yaml
- openstack/nova/templates/online-migration-job.yaml
- openstack/nova/templates/placement-api-deployment.yaml
- openstack/nova/templates/update-cells-job.yaml
Scripts can change partly due to code change or configuration
values (cells), which would result in an annotation change.
But k8s doesn't do updates of jobs, so we end up with a deployment
failure.
By deriving the name from the hashed script (instead of the config)
we run the job newly on each change of the script or the image version.
> Nova: Derive name from job-script hash

- prometheus-exporters/vrops-exporter/alerts/host.alerts
re-increase the severity of `HostWithRunningVMsNotResponding`. Back after a problem.
> [vrops-exporter] host alert severity increased

- common/rabbitmq/Chart.yaml
- common/rabbitmq/templates/headless-service.yaml
- common/rabbitmq/templates/poddisruptionbudget.yml
- common/rabbitmq/templates/pvc.yaml
- common/rabbitmq/templates/statefulset.yaml
- common/rabbitmq/values.yaml
By default, this change doesn't change anything, except it
will raise an error when a deployment with more than one
replica with persistence enabled is requested, as this doesn't work.
One has to use a statefulset for that, but it is *not* a clustered
setup. The use-case is a special one for notifications:
We currently create for each service a single independent
rabbitmq, and the consumer connects to each of them.
If one goes down, no notifications can be send (over rabbitmq).
This allows us to spin up a statefulset with several independent
on the consumer side, let the producers connect to any of them,
and the consumer to all of them.
When one instance is down, the producer(s) can reconnect to
any of the remaining ones.
A Pod disruption budget ensures that at least one is up.
Clustering …
> Rabbitmq: Option for statefulSet without clustering

- common/rabbitmq/templates/statefulset.yaml
We (partly) use the statefulset to get predictable unique
hostnames, and all having the same one is breaking things
> [rabbitmq] Do not set hostname for statefulset

- openstack/nova/templates/hypervisors/hypervisors-vmware-configmap-vct.yaml
The vcenter-operator exposes the variable datastore_hagroup_regex if a
cluster contains datastores matching its regex. We use this to enable
the functionality in Nova, that splits ephemeral root disks between
hagroups.
> [nova] Support setting datastore_hagroup_regex for vmware

- prometheus-exporters/openstack-exporter/alerts/cinder.alerts
This patch contains the new cinder alerts for low free space
and datastores that can accept a maximum size volume.
> [Cinder]  New cinder alerts.

- openstack/cinder/requirements.lock
- openstack/cinder/requirements.yaml
This patch updates the helm chart for cinder.  It updates
the requirements for
mariadb to 0.3.49
mysql_metrics to 0.2.7
memcached to 0.0.10
rabbitmq to 0.3.2
rabbitmq_notifications to 0.3.2
> [Cinder] Update cinder chart's requirements

- openstack/nova/requirements.lock
- openstack/nova/requirements.yaml
Update to get affinity settings for k8s node reinstall.
With that we also get a faster readiness-check, relaxed probe timeouts
and RabbitMQNotReady alert updates to not trigger on the
notifications-rabbitmq being down.
> [nova] Bump rabbitmq dependency to 0.3.2

- openstack/nova/requirements.lock
- openstack/nova/requirements.yaml
We update to get affinity settings for k8s nodes getting reinstalled.
By upgrading, we also get more warning logs to help in optimizing the
DBs and remove the DEX dependency for maridb-backup by using sap_id
oauth.
> [nova] Bump mariadb dependency to 0.3.50

- prometheus-exporters/vrops-exporter/alerts/host.alerts
TARS no longer monitoring this alert hence alert moved to critical channel so Infraops colleagues can free-up failover hosts from running VMs.
> VMsOnFailoverHost alert uplifted to critical

- prometheus-exporters/vrops-exporter/alerts/vcenter.alerts
We encountered a small gap in the vrops_vcenter_summary_certificate_expiry_date metric, which caused a false resolve message.
> VcsaSslCertificateExpiry closing small gaps

- global/concourse/templates/git-resource-proxy.yaml
- global/concourse/templates/webhook-broadcaster-ingress.yaml
> [concourse]: migrate ingress to v1

- common/prometheus-pushgateway/templates/ingress.yaml
> [prometheus-pushgateway]: migrate ingress to v1

- openstack/blackbox/charts/blackbox-tests-certificates/templates/cc3test-ingress.yaml
> [blackbox]: migrate ingress to v1

- openstack/neutron/templates/ingress-server.yaml
- openstack/neutron/templates/sftp-ingress.yaml
> [neutron]: migrate ingress to v1

- openstack/cinder/requirements.lock
- openstack/cinder/requirements.yaml
The utils chart got an update to include %(resource)s in the logging
format string, which we want for Cinder.
> [cinder] Bump utils chart for format string

- openstack/maia/templates/maia-ingress.yaml
> [maia]: migrate ingress to v1

- openstack/hermes/templates/api-ingress.yaml
- openstack/hermes/templates/es-manager-ingress.yaml
> [hermes]: migrate ingress to v1

- openstack/cinder/requirements.lock
- openstack/cinder/requirements.yaml
This patch updates cinder requirement for Mariadb 0.3.50
> [Cinder] Upgrade mariadb to 0.3.50

- openstack/glance/templates/ingress.yaml
> [glance]: migrate ingress to v1

- openstack/barbican/templates/ingress.yaml
> [barbican]: migrate ingress to v1

- system/sentry/charts/postgresql/templates/svc.yaml
- system/sentry/templates/ingress.yaml
> [sentry]: migrate ingress to v1

- openstack/barbican/templates/api-deployment.yaml
- openstack/barbican/values.yaml
The pod will receive the shutdown request at the same time as
the as the endpoint-controller, which will then propagate the
change to the kube-proxy.
That in turn means that the pod will still receive requests
from other clients while being in the process of being shut down.
This leads then to connection errors during the time that
event propagates through the network stack of kubernetes.
To avoid that, we delay the actual shutdown by a fixed period,
which should, if not eliminate, but reduce the number of those errors
> [Barbican] Shutdown delay to avoid connection resets

- openstack/glance/templates/deployment.yaml
- openstack/glance/values.yaml
The pod will receive the shutdown request at the same time as
the as the endpoint-controller, which will then propagate the
change to the kube-proxy.
That in turn means that the pod will still receive requests
from other clients while being in the process of being shut down.
This leads then to connection errors during the time that
event propagates through the network stack of kubernetes.
To avoid that, we delay the actual shutdown by a fixed period,
which should, if not eliminate, but reduce the number of those errors
> [Glance] Shutdown delay to avoid connection resets

- prometheus-exporters/kube-state-metrics-exporter/Chart.yaml
- prometheus-exporters/kube-state-metrics-exporter/ci/test-values.yaml
- prometheus-exporters/kube-state-metrics-exporter/templates/servicemonitor.yaml
- prometheus-exporters/kube-state-metrics-exporter/values.yaml
Namespace was always set to `any`. This leads to every prometheus pulling in the whole metrics of the cluster, even if they aren't needed. Instead of dropping it multiple times we should make this configurable here.
Still defaults to `any`, if nothing is set.
> [kube-metrics-exporter] configurable namespace

- system/doop-central/templates/ingress.yaml
> [doop-central]: migrate ingress to v1

- openstack/castellum/templates/api-ingress.yaml
> [castellum]: migrate ingress to v1

- openstack/clair/templates/ingress.yaml
> [clair]: migrate ingress to v1

- openstack/keppel/templates/ingress-api.yaml
> [keppel]: migrate ingress to v1

- openstack/limes/templates/api-ingress.yaml
> [limes]: migrate ingress to v1

- openstack/swift/templates/ingress.yaml
> [swift]: migrate ingress to v1

- openstack/utils/Chart.yaml
- openstack/utils/templates/snippets/_pre_stop_graceful_shutdown.tpl
- openstack/utils/values.yaml
Add a common way to handle the propagation delay of a pod termination
gracefully.
In order to get around the race between the kubernetes stop sending
new connections to a pod, and the pod accepting them,
add a delay to the shutdown of the pod.
Ideally, this would be replaced with some insight into the actual
state of forwarding, but until then we have to wait
> [openstack/utils] Add pre_stop_graceful_shutdown snippet

- system/audit-logs/vendor/logstash-audit-external/templates/ingress.yaml
> [audit-logs]: migrate ingress to v1

- openstack/utils/Chart.yaml
- openstack/utils/templates/snippets/_pre_stop_graceful_shutdown.tpl
- openstack/utils/values.yaml
The global default doesn't seem to take hold
reliably, so we have to put it as an argument
to the function
> [openstack/utils] Fixup pre_stop_graceful_shutdown defaults

- openstack/barbican/requirements.lock
- openstack/barbican/requirements.yaml
- openstack/barbican/templates/api-deployment.yaml
- openstack/barbican/values.yaml
> [Barbican] Use shutdown delay snippet to avoid connection failures

- openstack/glance/requirements.lock
- openstack/glance/requirements.yaml
- openstack/glance/templates/deployment.yaml
- openstack/glance/values.yaml
> [Glance] Use shutdown delay snippet to avoid connection failures

- openstack/neutron/Chart.lock
- openstack/neutron/Chart.yaml
- openstack/neutron/templates/deployment-server.yaml
> [Neutron] Use shutdown delay snippet to avoid connection failures

- system/kube-parrot/Chart.yaml
- system/kube-parrot/templates/daemonset.yaml
- system/kube-parrot/values.yaml
if globalRegion is enabled, creates Daemonset per region with specific BGP AS values
> [kube-parrot] support global region

- openstack/cinder/requirements.lock
- openstack/cinder/requirements.yaml
- openstack/cinder/templates/api-deployment.yaml
> [Cinder] Use shutdown delay snippet to avoid connection failures

- openstack/keystone/templates/bin/_keystone_api.sh.tpl
The pod will receive the shutdown request at the same time as
the as the endpoint-controller, which will then propagate the
change to the kube-proxy.
That in turn means that the pod will still receive requests
from other clients while being in the process of being shut down.
This leads then to connection errors during the time that
event propagates through the network stack of kubernetes.
To avoid that, we delay the actual shutdown by a fixed period,
which should, if not eliminate, but reduce the number of those errors
> [Keystone] Shutdown delay to avoid connection failures

- openstack/designate/requirements.lock
- openstack/designate/requirements.yaml
- openstack/designate/templates/api-deployment.yaml
> [Designate] Use shutdown delay snippet to avoid connection failures

- openstack/designate/templates/api-ingress.yaml
> [designate]: migrate ingress to v1

- prometheus-exporters/vrops-exporter/alerts/vccluster.alerts
As discussed in the InfraOps weekly call.
InfraOps is aware, alert is working as expected.
> Raise VCClusterDRSNotFullyAutomated to critical

- common/mariadb/Chart.yaml
- common/mariadb/templates/deployment.yaml
- common/memcached/Chart.yaml
- common/memcached/templates/deployment.yaml
- common/postgresql/templates/deployment.yaml
- common/redis/Chart.yaml
- common/redis/templates/deployment.yaml
An annotation change means a restart, which is currently not
well handled.
This reverts commit 6dbbc0d7c2accad0cb158de1c49a31566eadda68.
> Revert "avoid de-scheduling of databases"

- openstack/nova/templates/cell2-conductor-deployment.yaml
- openstack/nova/templates/conductor-deployment.yaml
- openstack/nova/templates/etc/_nova-scheduler.conf.tpl
- openstack/nova/templates/hypervisors/_ironic-deployment.yaml.tpl
- openstack/nova/templates/hypervisors/hypervisors-vmware-configmap-vct.yaml
- openstack/nova/templates/scheduler-deployment.yaml
- openstack/nova/values.yaml
We've added a patch to oslo.messaging, that allows us to track the
number of RPC calls per called function and also if this call errored
out. This functionality can be enabled by setting statsd_enabled in the
DEFAULT section.
This change adds the possibility to enable this functionality for
nova-scheduler, nova-conductor and nova-compute pods (both ironic and
vmware).
> [nova] Optionally enable RPC metrics collection

- openstack/manila/templates/api-ingress.yaml
> [manila]: migrate ingress to v1

- global/pulsar/templates/ingress.yaml
> [pulsar]: migrate ingress to v1

- common/cypress-dashboard/templates/ingress.yaml
> [cypress-dashboard]: migrate ingress to v1

- global/supernova/templates/ingress.yaml
> [supernova]: migrate ingress to v1

- px/bird/Chart.yaml
- px/bird/templates/_configmap-bird.tpl
- px/bird/templates/_deployment-bird.tpl
- px/bird/templates/_deployment_header.tpl
- px/bird/templates/_nad_multus.tpl
- px/bird/templates/_service_pxrs.tpl
- px/bird/templates/bird.yaml
- px/bird/values.yaml
PX deployments, configmaps, nads, etc. were rendered by handcrafted
python scripts, in some cases k8s manifests were written by hand. In
order to abandon that script infrastructure, we move everything over to
helm and secrets.
Previous rendered manifests where these templates are based on can be
found here:
https://github.wdf.sap.corp/cc/px-cfg/tree/4da52beca51319b4ef2959751a72d881f3dd9388/kubernetes
Old pythonic templates are to be found here:
https://github.wdf.sap.corp/cc/px-cfg/tree/4da52beca51319b4ef2959751a72d881f3dd9388/kubernetes/template
> Migrate all PX k8s manifests to helm

- prometheus-exporters/openstack-exporter/alerts/cinder.alerts
This patch changes the tier from os to vmware to send the
alerts to infraops
> [openstack-exporter]  Fix the tier for cinder alerts

- openstack/lyra/templates/ingress.yaml
- openstack/lyra/templates/omnitruck-ingress.yaml
The next version of kubernetes 1.22 removes support for the `Ingress` resource
in version `networking.k8s.io/v1beta1`.
need to happen when migrating to `networking.k8s.io/v1`
Please review and them them at you own discretion. Happy hacking!
Note: This PR was mass created so please validate and test the changes before rolling it to production.
> lyra: migrate ingress to v1

- prometheus-exporters/openstack-exporter/alerts/cinder.alerts
This patch updates the paths of the cinder playbook filenames.
The playbook files were renamed to remove _ to -
> [Openstack-exporter] update the cinder playbook filenames

- openstack/nova/templates/cell2-conductor-deployment.yaml
- openstack/nova/templates/conductor-deployment.yaml
- openstack/nova/templates/etc-configmap.yaml
- openstack/nova/templates/hypervisors/_ironic-deployment.yaml.tpl
- openstack/nova/templates/scheduler-deployment.yaml
without a specific mapping every rpc method would create its own metric in prometheus. e.g.:
- oslo_messaging_attach_volume_event
- oslo_messaging_object_action_exception
- ...
we rather want one metric: 'oslo_messaging_events' with labels method and type e.g.:
- oslo_messaging_events{method: attach_volume, type: event}
- oslo_messaging_events{method: object_action, type: exception}
> [nova] adds mapping for rpc metrics collection

- openstack/swift/templates/_utils.tpl
- openstack/swift/templates/proxy-daemonset.yaml
- openstack/swift/templates/replicators-daemonset.yaml
- openstack/swift/templates/rsyncd-daemonset.yaml
- openstack/swift/templates/servers-daemonset.yaml
- openstack/swift/templates/statsd-exporter-daemonset.yaml
- openstack/swift/templates/workers-daemonset.yaml
Before rollout:
```
$ k label vpa swift-{proxy-cluster-3,replicators,rsyncd,servers,statsd-exporter,workers} app.kubernetes.io/managed-by=Helm
$ k annotate vpa swift-{proxy-cluster-3,replicators,rsyncd,servers,statsd-exporter,workers} meta.helm.sh/release-name=swift meta.helm.sh/release-namespace=swift
```
> swift: no VPA magic

- global/prometheus-alertmanager-operated/Chart.yaml
- global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl
The new `slack_by_k8s_service` is a direct copy of `slack_by_os_service`. I want to split out Gatekeeper alerts that currently only end up in #cc-k8s-info since that channel is has so much noise in it that it's completely useless for me.
> alertmanager: deliver alerts to Slack channel #cc-k8s-gatekeeper

- prometheus-exporters/openstack-exporter/alerts/cinder.alerts
Instead of warning on < 3, we now alert on < 2.
Critical on <1
> [Cinder] Adjust cinder alert metrics

- global/volta/templates/ingress.yaml
> [volta]: migrate ingress to v1

- openstack/db-backup-v2/templates/dex-ingress.yaml
> [db-backup-v2]: migrate ingress to v1

- openstack/kos-operator/templates/clusterrole.yaml
> [kos-operator]: migrate ingress to v1

- openstack/baremetal-temper/templates/ingress.yaml
> [baremetal-temper]: migrate ingress to v1

- global/wham/templates/ingress.yaml
> [wham]: migrate ingress to v1

- prometheus-exporters/cloudprober/templates/ingress.yaml
> [cloudprober]: migrate ingress to v1

- openstack/octavia/templates/octavia-api-ingress.yaml
Falling back to something newer (v1) makes no sense.
v1beta1 and v1 were confused here.
We're on v1 everywhere now, so remove conditional entirely.
> [Octavia] Fix wrong Ingress API-versioning

- system/ccauth/templates/ingress.yaml
> [ccauth]: migrate ingress to v1

- openstack/grafanasix/templates/grafana-ingress.yaml
- openstack/grafanasix/templates/nginx-ingress.yaml
> [grafanasix]: migrate ingress to v1

- openstack/nova/templates/api-ingress.yaml
- openstack/nova/templates/console-ingress.yaml
- openstack/nova/templates/placement-ingress.yaml
> [nova]: migrate ingress to v1

- openstack/nova/templates/console-ingress.yaml
Instead of using a configuration-snippet,
we can use the rewrite-target as in the
example in the documentation:
https://kubernetes.github.io/ingress-nginx/examples/rewrite/
We need to replace nginx.ingress.kubernetes.io
with ingress.kubernetes.io as the ingress is configured
to take the latter non-default annotation prefix
> [nova] Use ingress rewrite-target

- prometheus-exporters/statsd-exporter/templates/ingress.yaml
> [statsd-exporter]: migrate ingress to v1

- system/infra-monitoring/vendor/blackbox-exporter/templates/ingress.yaml
- system/infra-monitoring/vendor/cloudprober-exporter/templates/ingress.yaml
> [infra-monitoring]: migrate ingress to v1

- openstack/nova/values.yaml
We introduced the default_hw_version to define a minimum version
supported by all ESXi during upgrade, so that vMotion between ESXis and
clusters is possible no matter if they are upgraded already or not. The
minimal supported version at the time was vmx-13. We now upgraded to
newer versions of ESXi and thus update default_hw_version to what the
ESXis would use as default currently: vmx-18.
> [nova] Update default_hw_version to vmx-18

- prometheus-exporters/network-generic-ssh-exporter/alerts/asr.alerts
Neutron router to core and Neutron to Neutron peering alerts moved from info to critical channel
> neutron bgp alerts moved to critical channel

- openstack/designate/values.yaml
for now until the high memory consumption for dumps is fixed
> [designate] disable mariadb backup verify

- openstack/nova/values.yaml
With filtering happing in placement, it's already ensured that the
resources in the flavor - MEMORY_MB and DISK_GB in placement - can be
fulfilled by the host. Therefore, we don't need these filters in the
scheduler anymore.
This came up because baremetal flavors use resource group based
scheduling and set MEMORY_MB, VCPU and DISK_GB to 0 in the request to
placement via flavor property. Still, a baremetal host could not be
scheduled because of 1 GiB difference between placement and the flavor's
disk setting.
> [nova] Disable RamFilter and DiskFilter in scheduler

- openstack/keystone/templates/ingress-api.yaml
> [keystone]: migrate ingress to v1

- openstack/ironic/values.yaml
Ironic creates a lot of conductors, and each of them
keep a max_pool_size number of connections open.
By setting it to 1, the pool will be minimal,
and most connections will be short-lived
> [ironic] Change db pool params

- openstack/utils/Chart.yaml
- openstack/utils/templates/_hosts.tpl
We have (at least) two users in the mariadbs.
The root user and the service specific user
This change makes the service use the service-specific
user, and leaves the root user for administrative tasks
> openstack.utils.db_url_mysql: Use dbUser credentials instead of root

- openstack/sap-seeds/templates/_flavors_hana_exclusive.tpl
We set the default VMX-HW Version in Nova for new VMs to 18. We do not change the VMX-HW Version if a VM gets resized in Nova, except the VMs which get resized from a Flavor with < 128 vCPUs to a Flavor with > 128 vCPUs. For them the resize will change the VMX-HW version to the defined one in the flavor because otherwise the VM would not start up.
> Increasing VMX-HW Version to 18 for all flavors

- openstack/sap-seeds/templates/_flavors_hana_exclusive.tpl
- openstack/sap-seeds/values.yaml
When deploying the sap-seeds with use_hana_exclusive set, we did not
include the legacy flavors that are not applicable to
CUSTOM_HANA_EXCLUSIVE_HOST-enabled hosts. But there's at least one
region where we now need to also include those flavors, because one of
the AZs will never get a CUSTOM_HANA_EXCLUSIVE_HOST-enabled host.
Therefore, we move the legacy flavors to their own template for
inclusion, include them unconditionally if the hana_no_exclusive list is
used and based on the setting
hana_exclusive_contains_legacy_bigvm_flavors also in the hana_exclusive
case.
> [sap-seeds] Optionally add legacy bigvm flavors

- openstack/nova/templates/etc/_nova-scheduler.conf.tpl
Instead of hard-coding query_placement_for_availability_zone,
decide it based on the default-filters configuration.
If there is no AvailabilityZone Filter, we need to use
placement for that.
> [nova] Query placement for AZ or AZ-Filter

- system/gatekeeper/ci/test-values.yaml
- system/gatekeeper/templates/constraint-vulnerable-images.yaml
I've left the policy message to use `image` instead of `imageID`. Let me know if you want ID in the message.
> GkVulnerableImages: use image ID

- prometheus-exporters/openstack-exporter/alerts/cinder.alerts
This patch updates the logic for the
CinderShardFreeSpaceWarning
CinderShardFreeSpaceCritical
alerts.   This new alert tracks the total number of pools vs the number
of pools left over that have < 30% of storage space left.  If there are
< 2 then we get a warning.  If there is < 1 then we get a critical.
Still need to update this to critical once ops approves.
> [Cinder] Update CinderShardFreeSpaceWarning

- px/lg/templates/deployment.yaml
In each region we use the respective registry instead of keppel in
eu-de-1
> [px/lg] Using local registry for images

- px/lg/templates/deployment.yaml
- px/lg/values.yaml
Both lg deployments were roughly the same, however one is supposed to be
started in privileged mode. Introduced the values attribute and consumed
it in a  simple condition in the deployment.
> Mistakenly duplicated deployments

- openstack/neutron/templates/configmap-etc-cc-fabric.yaml
- openstack/neutron/templates/deployment-cc-fabric-agent.yaml
- openstack/neutron/values.yaml
Adding deployments for driver pod, additional configmap for driver
specific configuration and adjusting value file to include platforms
running as well as actual driver configuration showing the fabric
layout.
> Add CC-fabric driver manifests

- openstack/utils/Chart.yaml
- openstack/utils/templates/_helpers.tpl
This is required because jaeger-agent was pointed to another image in the previous commit
>  Bump utils version

- openstack/utils/Chart.yaml
- openstack/utils/templates/_hosts.tpl
The host-name for mariadb is only by convention correct.
It is actually determined by .Values.mariadb.name as
can be verified by looking at the helpers.tpl macro named
'fullName', which is used as the name of the service
> [openstack/utils] Fix mariadb name

- openstack/nova/templates/cell2-conductor-deployment.yaml
- openstack/nova/templates/conductor-deployment.yaml
- openstack/nova/templates/hypervisors/_ironic-deployment.yaml.tpl
- openstack/nova/templates/hypervisors/hypervisors-vmware-deployment-vct.yaml
- openstack/nova/templates/scheduler-deployment.yaml
When we have prometheus.io/port annotation and multiple containers, then
prometheus will use that port for both containers and scrape the same
metrics just with different container labels. The solution is to remove
the annotation and rely on prometheus finding the right port by its name
"metrics", according to [0].
[0] https://operations.global.cloud.sap/docs/support/playbook/kubernetes/target_scraped_multiple_times.html#usage-or-prometheusioport-annotation-with-multiple-ports
> [Nova] Prevent double scraping of metrics

- openstack/swift/templates/object-expirer-deployment.yaml
The service discovery is invoked for every endpoint port found in the correponding endpoints object and in both cases the port annotation is used to override the port. This will cause the same metrics to be collected twice with different container labels.
Solution: Remove the prometheus.io/port annotation from your pod or service spec and give the target port the name metrics.
> [swift] Avoid multiple scrapes of prometheus targets

- px/lg/templates/deployment.yaml
We do not care about the specific note plancement. With the current
tolerations the lg gets placed in the PX node which we'd like to avoid.
> [px/lg] Remove tolerations for looking glas

- common/mariadb/Chart.yaml
- common/mariadb/templates/deployment.yaml
let prometheus find the container with the port "metrics" by itself and scrape the pod once instead 3 times (for each container)
> [mariadb] Prevent trible scraping of metrics

- global/prometheus-alertmanager-operated/Chart.yaml
- global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl
there is a managed service split within tier net - this setup isn't final and the sequence hack is dirty, but necessary
> [alertmanager] pagerduty network split by alert type

- openstack/manila/templates/api-service.yaml
prom is looking at the port named `metrics` and gets confused by
specifying a port annotation if the service has more than 2 ports
needs a go from @databus23, needs an underlying prom 'chart rodeo'
> [manila] prevent double scraping of api

- openstack/nova/values.yaml
We've tested it a little on some regions and it looks fine, so we want
to have it everywhere.
> [nova] Enable oslo.messaging metrics by default

- openstack/nova/templates/api-deployment.yaml
- openstack/nova/templates/api-metadata-deployment.yaml
- openstack/nova/templates/api-metadata-service.yaml
- openstack/nova/templates/api-service.yaml
- openstack/nova/values.yaml
The config-value portMetrics suggests, that the port
is configurable. That is not the case, as it isn't
passed to the stats-exporter
> [Nova] Remove faulty config value

- system/unbound/templates/config.yaml
- log servfail responses
- max ttl for negative cache to 100 sec vs. 3600 by default
- cache max ttl to 8 hours vs. 24 hours by default
> [unbound] config updates:

- px/bird/templates/_deployment_header.tpl
- px/bird/templates/bird.yaml
- px/bird/values.yaml
We used to pin PX to certain AZs where we knew the apods were cabled to
PX, however if more apods come in within an AZ and not all are cabled
to PX, this is going to break.
We now specify explicitly which apod to run on. We also moved some
logic regarding the placement in AZs from the chart to the k8s
scheduler. The intention is that we have one instance from each PX
domain running in each AZ. Subsequently, if we have more than 1 AZ in a
region we define an podAntiAffinity on the combined service and domain
label, so a service's domain will never be placed in the same AZ.
> Pin PX on specific apods that are cabled to PX switches

- openstack/nova/templates/consoleauth-deployment.yaml
- openstack/nova/templates/etc/_nova.conf.tpl
- openstack/nova/values.yaml
Console-auth is deprecated, so we disable it via
setting the replica count to zero (before removing
it eventually completely)
> [nova] Disable console-auth

- common/prometheus-server/templates/podmonitors/pod-sd.yaml
- common/prometheus-server/templates/servicemonitors/endpoint-sd.yaml
In case there is more than one port with metrics,
we need to give them distinct names. This change takes all
ports either named `metrics` (as before), but also ports with a suffix separated by a hyphen as prometheus metrics ports.
> [prometheus] Allow -* suffix for named metrics ports

- system/infra-monitoring/vendor/px-exporter/px.alerts/px.alerts
Changed severity from critical to warning as this alert is redundant and not handeled by k8s.
> Update severity PXTransportRouterPrefixExportCountZero

- global/prometheus-kubernetes-global/values.yaml
- global/prometheus-openstack/values.yaml
to allow proper scheduling k8s should be aware of the memory load expected by these global prometheis instances.
Otherwise prometheus could end up running on a node with a very limited amount of memory available causing it to permanently crash.
> [prometheus-global] memory requests for global prometheis

- common/mariadb/templates/_helpers.tpl
Prior to this change, helm would not complain about the value
to be unset, but mariadb would never start up, as the preStart
hook would never complete.
Hence require the password, as it won't work without it.
> [mariadb] Require root_password to be set

- openstack/keppel/templates/seed.yaml
- openstack/limes/templates/seed.yaml
- openstack/swift/templates/prometheus-alerts.yaml
- openstack/swift/templates/seeds.yaml
To be prepared for the swift reseller role rename, adding the new `cloud_objectstore_admin` role already to the service accounts and add a new alert.
> Adding cloud_objectstore_admin role to swift/limes/keppel seeds

- system/kube-monitoring-metal/templates/_frontend-prometheus.yaml.tpl
after https://github.com/sapcc/helm-charts/commit/beb675c3eb0ba237d50c2cf956f0d4a1dbf81472 we do not aggregate cpu metrics anymore but also do not federate them thus they are not showing up in the prom.
this should re-enable the federation of the cpu metrics.
> Re - federate cpu metrics

- openstack/utils/Chart.yaml
- openstack/utils/templates/_ini_sections.tpl
The code now requires an explicit
```
postgresql:
enabled: false
```
which is a bit annoying since everything is switched to mariadb
> [openstack/utils] Do not require postgresql to be set

- openstack/octavia/templates/octavia-worker-deployment.yaml
It needs to be on the pod, not on the deployment, because only pod labels are exposed as a Prometheus metric. While I was at it, I added a comment to document the purpose of the label.
> octavia: fix "f5-device-model" label

- openstack/cinder/templates/api-service.yaml
This removes the prometheus.io/port from the chart and changes it to
a spec named metrics.
This is related to discussion on slack:
https://operations.global.cloud.sap/docs/support/playbook/kubernetes/target_scraped_multiple_times/#usage-or-prometheusioport-annotation-with-multiple-ports
> [Cinder] remove prometheus.io/port

- openstack/ironic/templates/seed.yaml
We are migrating to CCloud conform role namings and introduced a new Swift reseller role:
`cloud_objectstore_admin`. To make the migration as smooth as possible, the new role will
be already assigned to the `service` user in the Default domain.
Removal off the old role assignment will happen later.
> [Ironic] Additional swift reseller role

- openstack/nova/templates/seed.yaml
The nova service user is used e.g. when retrying to delete an instance
on nova-compute restart. If the customer has a DNS name assigned to
their port, deleting of the port and thus the server will fail, if the
nova service user doesn't have the appropriate role.
> [nova] Add cloud_dns_admin role to nova service user

- common/mariadb/Chart.yaml
- common/mariadb/templates/deployment.yaml
- common/mariadb/templates/initdb-configmap.yaml
- common/mariadb/templates/initdb/_init.sql.tpl
- common/mariadb/values.yaml
Instead of having repetitive free-form init.sql scripts,
provide the fields `databases` and `users`, which allow
the user of the script to create the databases and users
uniformly.
> [mariadb] Common user/db creation script

- openstack/cinder/templates/api-service.yaml
This patch removes the quote from the value to ensure it's an int
> [Cinder]  Fix the port value for pod scrapes

- openstack/cronus/templates/cronus/_config.yaml.tpl
- openstack/cronus/values.yaml
new config option to whitelist a list of get params
> [cronus]: reject only unknown GET parameters

- openstack/swift/templates/prometheus-alerts.yaml
Same as for cloud_objectstore_admin/swiftreseller. For now, no assignments are known.
> swift: add role assignment alert for cloud_objectstore_viewer

- openstack/nova/templates/etc-configmap.yaml
The latter key is the one actually used, but the former
is a more complete sudoers config, so we rather go with that one
> [nova] Remove duplicate sudoers key

- openstack/nova/Chart.yaml
- openstack/nova/templates/_helpers.tpl
- openstack/nova/templates/etc-configmap.yaml
- openstack/nova/templates/placement-configmap.yaml
- openstack/nova/templates/placement-db-finalize-split-job.yaml
- openstack/nova/templates/placement-db-split-job.yaml
- openstack/nova/templates/placement-db-unsplit-job.yaml
- openstack/nova/templates/pod-exec-rbac.yaml
- openstack/nova/values.yaml
Based on #3223
Moves all tables from `nova_api` to the one specified in `placementdbName` as soon as a `placementdbPassword` is specified.
The operations are idempotent, and can be reverted with a deployment with the value `placement.unsplit=true`.
No downtime required, as the alias is there practically immediately.
The backup still needs to be adjusted.
> [nova] Split out placement database

- openstack/manila/alerts/openstack/manila.alerts
The snapshots with status 'error', 'creating', 'deleting' are not
interesting, alert only on those in 'available' and 'error_deleting'.
> [manila] update alert OpenstackManilaShareSnapshotsMissing
