sapcc/helm-charts

openstack/sap-seeds/templates/_flavors_hana_exclusive.tpl

We introduced CUSTOM_MEMORY_RESERVABLE_MB as resource to guard against a
cluster not getting overloaded with memory reservation and thus not
being able to sustain more failed nodes than we have failover hosts.
This is fine if we run mixed workloads on a BB and the smaller VMs can
fill up the space not available to hana_* flavors.
With regions switching to hana-only BBs, this hinders spawning new
hana_* flavors and keeps those hana-only BBs less utilized than we want.
Therefore, we remove the requirement on CUSTOM_MEMORY_RESERVABLE_MB from
the hana_* flavors if we run with hana-only BBs.

[sap-seeds] Hana-only BB regions don't need CUSTOM_MEMORY_RESERVABLE_MB

---

common/mariadb/values.yaml

The field is required to be set in the fullName macro,
but defining the value to 'DEFINED-IN-COMPONENT-CHART' will
simply cause that value to be used if it isn't defined.
Rather fail with a clean error message, then with a garbage
output

[mariadb] Undefine name field

---

openstack/nova/templates/bin/_db-online-migrate.tpl

If placement gets deployed by its own service,
we can't have nova mess with its tables

[nova] Disable online migrations with placement

---

openstack/neutron/values.yaml

This metric can be used in a global dashboard and to alert on exhausting
segments.
Also checked if queries are optimized using indexes:
```
MariaDB [neutron]> explain select COUNT(*) from aci_port_binding_allocations GROUP BY host;
+------+-------------+------------------------------+-------+---------------+---------+---------+------+-------+-------------+
| id   | select_type | table                        | type  | possible_keys | key     | key_len | ref  | rows  | Extra       |
+------+-------------+------------------------------+-------+---------------+---------+---------+------+-------+-------------+
|    1 | SIMPLE      | aci_port_binding_allocations | index | NULL          | PRIMARY | 1542    | NULL | 88948 | Using index | …
```

[neutron] add free/total segment count metric

---

px/bird/templates/_deployment_header.tpl
px/bird/templates/bird.yaml
px/bird/values.yaml

In cases were we have to tear down an AZ or simply apods are not
available in every AZ, we need to be able to explicitly tell the chart
to not care about disjunct AZ scheduling for the PX domains.
This commit introduces a flag that does just that.

[PX] Allow scheduling in a single AZ even if site is multi-AZ

---

openstack/cinder/templates/backup_deployment.yaml
openstack/cinder/templates/vcenter_datacenter_cinder_deployment.yaml

This patch updates the deployment for cinder backup and
cinder volume to import the k8s metadata labels, which
include application, component, release_name

[Cinder] Update charts to include standard metadata_labels

---

system/metis/templates/metis-api-seeds.yaml

Role `cloud_inventory_user` is used to retrieve CCLoud Inventory data from Metis

[Metis] Adds seeds for cloud_inventory_viewer

---

common/rabbitmq/CHANGELOG.md
common/rabbitmq/Chart.yaml
common/rabbitmq/templates/bin/_rabbitmq-start.tpl
common/rabbitmq/templates/deployment.yaml
common/rabbitmq/templates/statefulset.yaml
common/rabbitmq/values.yaml

- Updating rabbitmq docker image to 3.10.5-management 
(release note: https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.10.5).
- using TCP socket check for the readinessProbe instead of deprecated rabbitmqctl node_health_check 
(resone: https://github.com/rabbitmq/cluster-operator/blob/43e7c05c4e5cf47322ef11b1b98b2bb70bf32a12/internal/resource/statefulset.go#L586-L604)
- adding CHANGELOG

[common/rabbitmq] update rabbitmq to 3.10.5-management version 

---

openstack/keystone/requirements.lock
openstack/keystone/requirements.yaml

[keystone] Update rabbitmq to 3.10

---

openstack/glance/templates/deployment.yaml
openstack/glance/templates/migration-job.yaml
openstack/glance/templates/proxysql-configmap.yaml
openstack/glance/values.yaml

This change should route all db queries through a pod-local
side-car to handle the connection resets of a restarting
mariadb
It requires the credentials in .Values.mariadb.users

[glance] Add proxysql side-cars

---

openstack/cinder/templates/backup_configmap.yaml
openstack/cinder/templates/backup_deployment.yaml

This patch fixes a templating problem with the backup_deployment
template.  The template had a template inside a template which caused
rendering of the inner template to fail.

[Cinder] Fixed a problem with backup_deployment template

---

openstack/cinder/templates/api-deployment.yaml
openstack/cinder/templates/backup_deployment.yaml
openstack/cinder/templates/migration-job.yaml
openstack/cinder/templates/proxysql-configmap.yaml
openstack/cinder/templates/scheduler-deployment.yaml
openstack/cinder/templates/vcenter_datacenter_cinder_deployment.yaml
openstack/cinder/templates/volumes/_netapp-deployment.yaml.tpl
openstack/cinder/templates/volumes/_volume-deployment.yaml.tpl
openstack/cinder/values.yaml

This PR adds the necessary snippets to enable proxysql side-car pods, without enabling them by default.
Functionally, it should behave the same after the change has been merged, until the mode is activated by setting `proxysql.mode=unix_socket`

[cinder] Added proxysql side-cars

---

openstack/barbican/templates/api-deployment.yaml
openstack/barbican/templates/proxysql-configmap.yaml
openstack/barbican/values.yaml

As the upgrade job runs as a helm-chart hook,
it cannot be combined with the unix_socket mode:
The hook runs before the required configuration change
is rolled out
This change requires the credentials for the
database user to be set under ".Values.mariadb.users..."

[barbican] Enable proxysql-side-car for the api

---

openstack/utils/Chart.yaml
openstack/utils/templates/snippets/_set_ingress_cors_annotations.tpl
openstack/utils/values.yaml

Our dashboard wants to start talking to OpenStack services' APIs
directly from the user's browser. Since browsers don't allow
cross-origin requests without the server explicitly setting certain
headers, we configure our Nginx ingress to enable CORS headers and
configure them.
We use k8s annotations [0] and Nginx ingress instead of the
cors-middleware from oslo.middleware, because not having to call the
backend seems much more efficient.
[0] https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#enable-cors

[openstack/utils] Add snippet for CORS annotations

---

openstack/nova/ci/test-values.yaml
openstack/nova/requirements.lock
openstack/nova/requirements.yaml
openstack/nova/templates/api-ingress.yaml
openstack/nova/values.yaml

The dashboard will start consuming Nova's API directly from the user's
browser and needs cross-origin requests to be allowed for that.

[nova] Enable CORS headers for nova-api

---

openstack/cinder/requirements.lock
openstack/cinder/requirements.yaml
openstack/cinder/templates/api-ingress.yaml
openstack/cinder/values.yaml

The dashboard will start consuming Cinder's API directly from the user's
browser and needs cross-origin requests to be allowed for that.

[cinder] Enable CORS headers for cinder-api

---

common/rabbitmq/Chart.yaml
common/rabbitmq/templates/statefulset.yaml

The statefulset only allows the template to be changed,
but not the volumeClaimTemplate. So we hard-code it to the
old value in order to avoid having to recreate everything

[rabbitmq] Make volumeClaimTemplate labels fix

---

common/mariadb/Chart.yaml
common/mariadb/templates/db-exec-rbac.yaml
common/mariadb/templates/pre-change-job.yaml
common/mariadb/values.yaml

The idea is to roll-out new users with new credentials in a pre-upgrade hook
so that they are available to the actual deployment making use of it.
Users (or databases) cannot be deleted this way (much less rolled back).
The cleanup is left to a later iteration, which may make use of an expiry policy.
Instead of having custom init scripts with slightly different patterns,
the fields `databases` and `users` are there to create and update them.
This also allows for uniform access to other macros, such as side-car
containers, which need knowledge about the users and the databases as well.
By using a job which executes the change within the container
of the database, we can change the credentials of any user
without fearing a lockout.
The job will be executed on upgrade and rollback and since …

[mariadb] Pre-upgrade hook for db/user creation

---

common/rabbitmq/Chart.yaml
common/rabbitmq/templates/_helpers.tpl
common/rabbitmq/templates/bin/_rabbitmq-start.tpl

In order to fails more cleanly, an invalid password (starting with '"')
will now fail to render.
The shell escape function was not escaping the backslash.

[common/rabbitmq] Validate input for users and escape "\"

---

system/prometheus-infra/templates/_prometheus-infra.yaml.tpl

federating up metrics into scaleout produces false-positive PrometheusMultipleTargetsScrapes alerts

remove up metric federation

---

common/mariadb/Chart.yaml
common/mariadb/templates/initdb/_init.sql.tpl

The value was previously unquoted, but mariadb rejects that

[maridb] Quote global.dbPassword

---

common/region_check/Chart.yaml
common/region_check/templates/region-check-job.yaml

If another hook fails, the region check won't get deleted
despite having succeeded, despite the hook-succeeded annotation.
A subsequent deployment will then fail due to the existing
region check job. Adding 'before-hook-creation' takes care of that.

[region_check] Delete before creation too

---

common/mariadb/Chart.yaml
common/mariadb/templates/initdb/_init.sql.tpl

The old code may be redundant if the user is already under
.Values.users.
This fixes a problem when he mariadb instance contains a hypen
(i.e. nova-api), which is not a valid database name.
It was previously not triggered as the init-code was replaced
by a custom-initmap.

[mariadb] Avoid old logic for new users

---

common/mariadb/Chart.yaml
common/mariadb/templates/initdb/_init.sql.tpl

If a custom-initmap has been provided,
then chances are the convention won't apply

[mariadb] Avoid name=user=db convention with custom-initmap

---

openstack/nova/requirements.lock
openstack/nova/requirements.yaml
openstack/nova/templates/_console_deployment.yaml.tpl
openstack/nova/templates/_helpers.tpl
openstack/nova/templates/api-deployment.yaml
openstack/nova/templates/api-metadata-deployment.yaml
openstack/nova/templates/bigvm-deployment.yaml
openstack/nova/templates/bin/_db-migrate.tpl
openstack/nova/templates/bin/_db-online-migrate.tpl
openstack/nova/templates/cell2-conductor-deployment.yaml
openstack/nova/templates/conductor-deployment.yaml
openstack/nova/templates/consoleauth-deployment.yaml
openstack/nova/templates/db-migrate-job.yaml
openstack/nova/templates/db-online-migrate-job.yaml
openstack/nova/templates/etc/_nova.conf.tpl
openstack/nova/templates/proxysql-configmap.yaml
openstack/nova/templates/scheduler-deployment.yaml
openstack/nova/values.yaml

This makes use of the proxysql side-car snippets.

[nova] Add ProxySQL side-cars

---

common/mariadb/Chart.yaml
common/mariadb/templates/initdb/_init.sql.tpl

dbUser may be unset, especially if the mariadb.users
type of initialisation is used

[mariadb] Handle unset dbUser

---

openstack/utils/Chart.yaml
openstack/utils/templates/_hosts.tpl

All services where setting a dbUser and dbName in the current
chart. That works for a single instance, but not in general.
Instead use the logic that the first database listed
under mariadb.databases is the default database,
and that there is user with the same key (but not necessarily
the same name) as the database.

[openstack/utils] Use first dbname & user as default

---

global/prometheus-alertmanager-operated/Chart.yaml
global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl

We've recently split off the Placement service from Nova and want its
alerts to go into its own channel.

[alertmanager] Add placement service to slack os services

---

prometheus-exporters/network-generic-ssh-exporter/alerts/asr.alerts

Turns out Cisco's hackfix that preallocates ports to NAT on bootup is
not working always as some devices allocate less than the expected 45k.
This is just to get an overview, playbooks for a crit alert will follow.

[neutron-asr] Info-Alert for to few NAT allocated ports

---

openstack/octavia/Chart.yaml
openstack/octavia/templates/etc/_octavia.conf.tpl

- Disable new Prometheus listener protocol (for now)
The deactivation config option is defined [here](https://github.com/sapcc/octavia/blob/stable/yoga-m3/octavia/common/config.py#L87).
- Set appVersion to "yoga" so that helm releases with different Openstack releases can be distinguished

Octavia yoga config

---

openstack/glance/Chart.lock
openstack/glance/Chart.yaml
openstack/glance/values.yaml

[glance] Remove notification rabbitmq

---

openstack/barbican/Chart.lock
openstack/barbican/Chart.yaml
openstack/barbican/values.yaml

[barbican] Remove notification rabbitmq

---

openstack/designate/Chart.lock
openstack/designate/Chart.yaml
openstack/designate/values.yaml

[designate] Remove notification rabbitmq

---

openstack/keystone/Chart.lock
openstack/keystone/Chart.yaml
openstack/keystone/values.yaml

[keystone] Remove notification rabbitmq

---

openstack/cinder/values.yaml

This patch changes the default Capacity Weigher to
stack volumes on a datastore instead of spreading them out.
This will help prevent smaller volumes from landing on the
most free datastores in a shard.  This will help keep the
newer created/most free datastores for the largest of volumes.

[Cinder] Stack volumes instead of spreading out

---

common/prometheus-server/CHANGELOG.md
common/prometheus-server/Chart.yaml
prometheus-rules/prometheus-kubernetes-rules/Chart.yaml
prometheus-rules/prometheus-kubernetes-rules/alerts/health.alerts.tpl
prometheus-rules/prometheus-kubernetes-rules/templates/_helpers.tpl

I propose that we use `cc/support-group` and `cc/service` label keys when annotating kubernetes resources to avoid any clashes with existing (pod) labels.
Those labels can then be used in alert definitions to populate `support_group` and `service` labels in alerts that can be used for alert routingin alertmanager
I adapted the generic alerts to support old `alert-service` and `alert-tier` labels as well with preference for the newer label keys.
Wdyt?

Consult cc/support-group and cc/service pods labels for pod alerts

---

openstack/cinder/templates/etc/_cinder.conf.tpl
openstack/cinder/values.yaml

This patch adds the ability to set the cinder option
to disable incremental backups.  The patch defaults
the option to On.

[Cinder] Disable incremental backups

---

openstack/cinder/Chart.lock
openstack/cinder/Chart.yaml
openstack/cinder/values.yaml

[cinder] Remove notification rabbitmq

---

openstack/ironic/templates/etc/_ipxe_config.template.tpl
openstack/ironic/templates/etc/_pxe_config.template.tpl
openstack/ironic/templates/etc/_uefi_pxe_config.template.tpl

templates now need to contain the pxe_append_params so that kernel
params including the ipa-api-url are set properly as part of the
deployment process

ironic (i)pxe templates: add kernel_append_params

---

system/prometheus-infra/templates/_prometheus-infra.yaml.tpl

Neutron Routers form an active/standby pair. Often times we want to aggregate
metrics for the pair and I am tired of using `label_replace` in my queries so I
guess the more straightforoward approach is to define that label on metric
insertion.

[prometheus-infra][neutron-routers] Add label to identify pair

---

system/gatekeeper/lib/add-support-labels.rego
system/gatekeeper/lib/helm-release.rego
system/gatekeeper/templates/constrainttemplate-deprecated-api-version.yaml
system/gatekeeper/templates/constrainttemplate-forbidden-clusterwide-objects.yaml
system/gatekeeper/templates/constrainttemplate-high-cpu-requests.yaml
system/gatekeeper/templates/constrainttemplate-images-from-correct-registry.yaml
system/gatekeeper/templates/constrainttemplate-images-from-non-keppel.yaml
system/gatekeeper/templates/constrainttemplate-ingress-annotations.yaml
system/gatekeeper/templates/constrainttemplate-outdated-image-bases.yaml
system/gatekeeper/templates/constrainttemplate-owner-info-on-helm-releases.yaml
system/gatekeeper/templates/constrainttemplate-pci-forbidden-images.yaml
system/gatekeeper/templates/constrainttemplate-pod-labels.yaml
system/gatekeeper/templates/constrainttemplate-prometheus-scrape-annotations.yaml
system/gatekeeper/templates/constrainttemplate-prometheusrule-alert-labels.yaml
system/gatekeeper/templates/constrainttemplate-region-value-missing.yaml
system/gatekeeper/templates/constrainttemplate-resource-limits.yaml
system/gatekeeper/templates/constrainttemplate-vulnerable-images.yaml
system/gatekeeper/tests/run.sh

This serves as a proposal for how we may structure Rego library modules in this chart going forward.
*Update:* In order to gauge how much we can do in library modules, I also moved the helm-manifest-parser calls into a module.

system/gatekeeper: move support label rendering to a lib module

---

openstack/barbican/templates/etc/_barbican_audit_map.yaml

@rajivmucheli here is the change requested from Anton. Please approve, then we can merge, deploy, and test. Thanks!

[barbican] audit map exclude payload member for secrets endpoint

---

system/kube-system-admin-k3s/Chart.yaml
system/kube-system-admin-k3s/templates/ingress-cacrt-secret.yaml
system/kube-system-admin-k3s/values.yaml

Multiple Ingresses are annotated with `ingress.kubernetes.io/auth-tls-secret: kube-system/ingress-cacrt` but there is no secret `ingress-cacrt` deployed in admin-k3s cluster. This leads to TLS errors in the ingress controller `kube-system-traefik`.

[kube-system-admin-k3s] ingress-cacrt added

---

system/kube-system-admin-k3s/Chart.yaml
system/kube-system-admin-k3s/values.yaml

By using the Traefik TLSOption resource in Kubernetes, we setup a default set of options that should apply to all ingresses. To achieve that, we created a TLSOption resource with the name default. There may exist only one TLSOption with the name default (across all namespaces) - otherwise they will be dropped. To explicitly use this TLSOption (and using the Kubernetes Ingress resources) we'll have to allow IngressRoute to reference resources in namespaces other than theirs.
https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#serverstransport-reference

[kube-system-admin-k3s] allowCrossNameSpace for IngressRoute CRD

---

openstack/cronus/templates/cronus/deployment.yaml
openstack/cronus/templates/cronus/statefulset.yaml
openstack/cronus/values.yaml

This will give a flexibility to switch between CGO and GO resolvers.

[cronus]: add an ability to set GODEBUG env variable

---

openstack/octavia/templates/_helpers.tpl
openstack/octavia/templates/octavia-migration-job.yaml

The job spec changed, so the name has to changed irregardless
if we enable proxysql or not to avoid an error in the helm deployment
(The spec of an existing job cannot be changed)
Also stop the proxysql sidecar only if the upgrade was successful

[octavia] Fix migration job wrt. proxysql

---

global/prometheus-alertmanager-operated/Chart.yaml

bump version to get the new kube-secrets

[alertmanager] gcp instance moves in datacenter

---

openstack/nova/templates/api-deployment.yaml
openstack/nova/templates/etc-configmap.yaml

With Xena, we're easily able to configure the "API unexpected exception"
message by setting the "support" config option in the "release" file [0]. We
do this here and point to the "Contact Us" site of our documentation
instead of upstream's bug tracker.
We only have to do this for the nova-api Deployment, because that's the
only user-facing site. nova-api-metadata is called through Neutron and
shouldn't forward the messages of Nova directly.
[0] https://github.com/sapcc/nova/blob/b0efa22cd37073d49519ddff02bdb69e5df4d5a7/nova/version.py#L62-L63

[nova] Change API unexpected exception message

---

openstack/nova/templates/_cell_secret.yaml.tpl
openstack/nova/templates/cells-secrets.yaml

With the Xena upgrade, we lose the API endpoint os-cells as cells v1 are
getting removed. We had previously extended that endpoint to let the
vcenter-operator retrieve connection information per cell and expose
these to its templates for configured nova-compute-bb* into the right
cell.
Our new approach is to expose the same information as k8s Secret per
cell, identified by the appropriate labels. The information is basically
the same, only lacking information about the UUID of the cell, as that's
a Nova-runtime-internal and not a configurable.

Nova: Add a secret per cell

---

common/owner-info/Chart.yaml
common/owner-info/ci/test-values.yaml
common/owner-info/templates/configmap.yaml
common/owner-info/values.yaml

To support the introduction of our new support structure.
@onuryilmaz I'm including you as reviewer since you will likely be the one consuming these fields. @BugRoger can tell you more when you talk next time.

owner-info: add "support-group" and "service" fields

---

system/gatekeeper-config/templates/_utils.tpl
system/gatekeeper-config/templates/constraint-outdated-image-bases.yaml
system/gatekeeper-config/templates/constraint-vulnerable-images.yaml
system/gatekeeper/lib/image-check.rego
system/gatekeeper/templates/constrainttemplate-outdated-image-bases.yaml
system/gatekeeper/templates/constrainttemplate-vulnerable-images.yaml

The structure of the new lib module mostly follows the helm-manifest-parser helper module that already exists. I'm also using the opportunity to make an improvement by covering init containers in addition to regular containers. This is WIP because I need to add test coverage for init containers.

gatekeeper: move doop-image-checker invocation to a lib module (WIP)

---

system/gatekeeper-config/templates/_utils.tpl
system/gatekeeper-config/templates/constraint-high-cpu-requests.yaml
system/gatekeeper-config/templates/constraint-images-from-correct-registry.yaml
system/gatekeeper-config/templates/constraint-images-from-non-keppel.yaml
system/gatekeeper-config/templates/constraint-pci-forbidden-images.yaml
system/gatekeeper-config/templates/constraint-pod-labels.yaml
system/gatekeeper-config/templates/constraint-resource-limits.yaml
system/gatekeeper/lib/traversal.rego
system/gatekeeper/templates/constrainttemplate-high-cpu-requests.yaml
system/gatekeeper/templates/constrainttemplate-images-from-correct-registry.yaml
system/gatekeeper/templates/constrainttemplate-images-from-non-keppel.yaml
system/gatekeeper/templates/constrainttemplate-pci-forbidden-images.yaml
system/gatekeeper/templates/constrainttemplate-pod-labels.yaml
system/gatekeeper/templates/constrainttemplate-resource-limits.yaml
system/gatekeeper/tests/fixtures/images-from-non-keppel/deployment-mixed.yaml
system/gatekeeper/tests/fixtures/images-from-non-keppel/pod-owned.yaml
system/gatekeeper/tests/suite.yaml

The logic mostly comes from GkImagesFromNonKeppel, and is now generalized to all policies that check pod specs or container specs.
@SuperSandro2000 I want to get this topic done this week if possible, which means I would have to merge tomorrow. If you get the chance to look at this today, I'd be grateful. If you don't get the chance, I'll merge this tomorrow at my own risk. In any case, I will perform detailed verification in QA to check that the policy behavior does not change in unintended ways.

gatekeeper: add "traversal" lib module for finding pod and container specs

---

system/gatekeeper/lib/add-support-labels.rego
system/gatekeeper/tests/fixtures/deprecated-api-version/helm-release-clean.in.yaml
system/gatekeeper/tests/fixtures/deprecated-api-version/helm-release-deprecated-1.16.in.yaml
system/gatekeeper/tests/fixtures/deprecated-api-version/helm-release-deprecated-1.22.in.yaml
system/gatekeeper/tests/fixtures/deprecated-api-version/helm-release-deprecated-1.25.in.yaml
system/gatekeeper/tests/fixtures/deprecated-api-version/helm-release-deprecated-1.26.in.yaml
system/gatekeeper/tests/fixtures/libtest-add-support-labels/helm-release-filled.in.yaml
system/gatekeeper/tests/fixtures/owner-info-on-helm-releases/configmap-no-owner-pending-upgrade.in.yaml
system/gatekeeper/tests/fixtures/owner-info-on-helm-releases/configmap-pass.in.yaml
system/gatekeeper/tests/fixtures/region-value-missing/helm-release-no-region.in.yaml
system/gatekeeper/tests/fixtures/region-value-missing/helm-release-pass.in.yaml

This requires the helm-manifest-parser change in <https://github.com/sapcc/gatekeeper-addons/commit/a57c7b037c729789ce7912b4a391111f7acd1cd6>.

gatekeeper: parse owner-info of Helm releases from manifest instead of values

---

openstack/placement/ci/test-values.yaml
openstack/placement/templates/stamp-alembic-job.yaml
openstack/placement/values.yaml

This corresponds to the placement db stamp step
in the migration step: https://github.com/openstack/placement/blob/master/placement_db_tools/mysql-migrate-db.sh#L302
The stamp job won't overwrite existing stamps,
so it can be removed after the first 'proper' deployment
It won't do that automatically by looking at the version
in order to allow to combine this change with an upgrade
in a later change

[placement] Stamp initial db version if not stamped

---

common/mariadb/Chart.yaml
common/mariadb/templates/backup-etc-configmap.yaml
common/mariadb/templates/initdb/_init.sql.tpl
common/mariadb/values.yaml

Instead of using the root-user, use a dedicated user with
its own connection limit in order to isolate the
backup process from the main application

[common/mariadb] Use backup-user with connection limit

---

system/unbound/templates/config.yaml

Increasing the rrset and msg cache because we see in the bigger regions that the cache is evicted before the TTL runs out.

Increasing rrset cache from 4MB to 100MB

---

openstack/utils/Chart.yaml
openstack/utils/proxysql_sidecar.md
openstack/utils/templates/_proxysql.tpl
openstack/utils/templates/_proxysql_configmap.yaml.tpl

The max_connections are on a per-process basis,
while the proxysql config assumes a single process
per pod.
This change allows the caller of the container macro
pass a scale-factor, which specifies the number of
processes in the pod.

[utils] Add scalefactor for connections

---

openstack/nova/Chart.lock
openstack/nova/Chart.yaml
openstack/nova/values.yaml

We have already migrated in all regions
the services to the central audit rabbitmq
So we can now undeploy the now unused one

[nova] Remove per-service notification rabbitmq

---

openstack/nova/Chart.lock
openstack/nova/Chart.yaml
openstack/nova/templates/api-deployment.yaml
openstack/nova/templates/api-metadata-deployment.yaml
openstack/nova/templates/cell2-conductor-deployment.yaml
openstack/nova/templates/conductor-deployment.yaml
openstack/nova/templates/etc/_nova-scheduler.conf.tpl
openstack/nova/templates/etc/_nova.conf.tpl
openstack/nova/templates/scheduler-deployment.yaml
openstack/nova/values.yaml

As sqlalchemy pool sets the limits per process,
we need to scale the number of connections with the number of
processes to have the same limit per pod.

[nova] Scale max-connections with number of processes

---

openstack/nova/templates/_helpers.tpl

Not only the script but also other settings from
proxysql can create changes to the job, which
is not supported by helm/kubernetes as
those fields are considered immutable

[nova] Hash proxysql settings in job-name

---

common/rabbitmq/Chart.yaml
common/rabbitmq/templates/deployment.yaml

Fixes an issue when `/var/lib/rabbitmq/.cookie` is has 0660 permissions on container startup.
With a fix the `/var/lib/rabbitmq/.cookie` file has 0400 permissions and rabbitmq doesn't complain.
see https://github.com/docker-library/rabbitmq/issues/171

[rabbitmq]: fix cookie permissions

---

openstack/placement/templates/etc-configmap.yaml
openstack/placement/templates/etc/_policy.yaml.tpl

While we run placement without policy overrides in Rocky, we have to add some overrides to keep things working when upgrading to Yoga. The reason for that is, that Rocky's default policy is to allow any "role:admin" user to access Placement, while in Yoga only admins with system-scoped tokens can access the important parts.
We change this default, to include our cloud_compute_admin role for admin APIs, too.
It should be fine to roll this file out with Rocky, too, because oslo.policy and placement should not know about a policy.yaml in that version.
The new defaults include a reader mode and users being able to get a usages overview of their own project to accommodate for Nova switching the Quota to counting via Placement in Yoga.

[placement] Add policy.yaml for Yoga

---

openstack/neutron/templates/etc/_dnsmasq.conf.tpl
openstack/neutron/values.yaml

This allows us to chose and override dnsmasq options more easily without having to modify the template

[neutron] Move dnsmasq options to values

---

openstack/cronus/templates/cronus/_config.yaml.tpl
openstack/cronus/values.yaml

This PR adds a Cronus config for "null" backends, that accept and silently drop any incoming mail, usable for project setup testing.
see https://github.wdf.sap.corp/cc/secrets/pull/9858
and https://github.wdf.sap.corp/cronus/issues/issues/201

cronus - adding null backend config

---

openstack/cinder/values.yaml

This patch moves the CapacityFilter to the last filter to run as well as adding a new SAPPoolDownFilter, which will filter out all pools that are not marked as 'up' by the vmware driver.

[Cinder] Add new SAPPoolDownFilter to default filters

---

system/infra-monitoring/vendor/windows-exporter/alerts/wsus-win-exporter.alerts

would recommend to use the service name properly.
windows-exporter is generic and also used for ad alerts.

make wsus the service

---

openstack/keystone/templates/_helpers.tpl
openstack/keystone/templates/cronjob-2faproxy.yaml
openstack/keystone/templates/deployment-2faproxy.yaml
openstack/keystone/templates/ingress-api.yaml
openstack/keystone/templates/rbac-2faproxy.yaml
openstack/keystone/templates/secret-2faproxy.yaml
openstack/keystone/templates/service-2faproxy.yaml
openstack/keystone/values.yaml

Add an intermedite reverse proxy deployment to the keystone chart between ingress and the keystone api that processes /v3/auth/tokens requests and enforces opt-in 2fa authentication in the form of tls client certificates.
Unless `2fa.enabled` is set to `true` no changes during deployment are expected.

Add 2faproxy to keystone chart

---

system/kube-monitoring-metal/Chart.lock
system/kube-monitoring-metal/Chart.yaml

Checked all other versions and they are in pars with the other kube-monitoring Charts. Upping kube-monitoring-stack solely therefore.

[kube-monitoring-metal] upping promstack

---

system/kube-monitoring-metal/Chart.lock
system/kube-monitoring-metal/Chart.yaml
system/kube-monitoring-metal/values.yaml

don't use kube-state-monitoring from kube-prometheus-stack anymore. Pulling in own version with dedicated config

[kube-monitoring-metal] kube-state-monitoring to dedicated chart

---

openstack/placement/templates/_helpers.tpl
openstack/placement/templates/db-migrate-job.yaml
openstack/placement/templates/db-online-migrate-job.yaml

When running Placement on its own images, Placement is responsible for migrating the DB. This is done via the placement-manage command.
We add 2 Jobs here - one for migrated the schema and one for doing any necessary data migrations.
Both Jobs only run if they find "placement-manage" in the path and thus will only do any work once we upgrade Placement to Yoga and its own images.

[placement] Add db migration jobs

---

openstack/placement/values.yaml

With switching to loci-based images, we forgot to update the wsgi file location changed, too.

[placement] Update wsgi_file for loci image

---

openstack/placement/templates/etc/_placement.conf.tpl

Even though it looked like Placement would overwrite the oslo.policy's default to "policy.yaml" in [0], this doesn't seem to work. Therefore, we explicitly set the policy_file option now.
[0] https://github.com/sapcc/placement/blob/17cb78c072b2cd7d10b59194b0f167629858fda9/placement/conf/base.py#L38

[placement] Set policy file path

---

openstack/nova/alerts/kubernetes/nova.alerts

More often than not, the alert fires without real reason nowadays and thus produces alert-fatigue. We now increase the time the condition has to be true to make the alert fire to 60min. We won't get alerted early, but we will still get notified of persisting problems.
If this proves to be too long, we will probably remove the alert in the future. It's a very broad alert-condition and the cc3test suite should provide similar information.

[nova] Increase OpenstackNovaComputeIdle wait time

---

openstack/nova/templates/console-deployment.yaml

With the commit "[nova] Remove consoleauth support" 996518a8 we removed the consoleauth-deployment.yaml - but contained not only the deployment for consoleauth, but also the deployments of the different consoles. Since we still need the consoles, we add them back now in their own file.

[nova] Add console deployments back again

---

common/mariadb/Chart.yaml
common/mariadb/templates/etc-configmap.yaml
common/mariadb/values.yaml

The Performance Schema is a feature for monitoring MariaDB/MYSQL Server execution at a low level. The Performance Schema has these characteristics:
The Performance Schema provides a way to inspect internal execution of the server at runtime. It is implemented using the [PERFORMANCE_SCHEMA](https://dev.mysql.com/doc/mysql-perfschema-excerpt/8.0/en/performance-schema.html) storage engine and the performance_schema database. The Performance Schema focuses primarily on performance data. This differs from INFORMATION_SCHEMA, which serves for inspection of metadata.
The Performance Schema monitors server events. An “event” is anything the server does that takes time and has been instrumented so that timing information can be collected. In general, an event could be a function call, a wait for …

[MariaDB] - Enable Performance Schema

---

openstack/utils/Chart.yaml
openstack/utils/templates/_coordination.tpl
openstack/utils/templates/_ini_sections.tpl

Add a shared ini-section snippet and related snippets for volume
mounts, pvc, and volumes which may be activated
by setting coordinationBackend=file

[openstack/utils] Add coordination section and pvc

---

openstack/manila/Chart.lock
openstack/manila/Chart.yaml
openstack/manila/templates/api-deployment.yaml
openstack/manila/templates/coordination-pvc.yaml
openstack/manila/templates/etc/_manila.conf.tpl
openstack/manila/templates/scheduler-deployment.yaml
openstack/manila/values.yaml

Instead of using the memcached driver, we can use
the PVC which should be more robust with respect
to restarts of the nodes

[manila] Integrate locking via pvc

---

openstack/swift/templates/proxy-daemonset.yaml
openstack/swift/templates/replicators-daemonset.yaml
openstack/swift/templates/rsyncd-daemonset.yaml
openstack/swift/templates/servers-daemonset.yaml
openstack/swift/templates/workers-daemonset.yaml

This is based on my own experience driving deployments in a way that does not make them a huge time sink. The most controversial part is probably the `maxUnavailable: 2` on the swift-servers, but this is also the most important in terms of reducing the time required to complete a deployment.

swift: roll daemonsets faster

---

openstack/nova/values.yaml

Instead of allowing only 8 GiB VMs on the small HVs, we now allow 16 GiB, too, because this currently fits in nearly all regions. In the regions it doesn't fit, we assume that most 16 GiB VMs will not be migrated in the near future and thus not clog the small HVs.

[nova] Allow 16 GiB VMs on small HVs

---

openstack/cinder/templates/etc/_cinder.conf.tpl

This patch updates the default volume size to 10Tib from 2 Tib

[Cinder] Default volume size is 10Tib

---

openstack/cinder/values.yaml

This patch changes the default capacity weigher to spread volumes out over datastores from stacking.  We have to do this short term to help buy time for allowing volume snapshots on datastores.  Stacking causes datastores to get full quickly.  When a datastore is full snapshotting fails due to not having space to do the snapshot, which is a full clone.

[Cinder] Rollback volume stacking on datastores

---

common/memcached/Chart.yaml
common/memcached/templates/alerts/_memcached.alerts.tpl

it is required for the on-call alert routing
- support information added to label
- chart must fail if the Values.alerts.support_group is not set in the parent chart

[memchached] add support info for alerts

---

openstack/cinder/alerts/openstack-cinder.alerts

This patch adds the new support_group label to the cinder alerts

Add support_group label

---

common/mariadb/Chart.yaml
common/mariadb/templates/alerts/_backup-v2.alerts.tpl
common/mariadb/templates/alerts/_health.alerts.tpl
common/mariadb/templates/alerts/_mysql.alerts.tpl
common/mariadb/values.yaml

- it is required for the on-call alert routing
- service owners have to define that for their MariaDB instance

[mariadb] support_group label added to alerts template

---

common/mariadb/Chart.yaml
common/mariadb/templates/initdb/_init.sql.tpl
common/mariadb/values.yaml

Metis does not require backups. Thus, I have no backup user password set and creation of the backup user is skipped. 
Now the deploy fails because it wants to add grants to a non-existing user:
```
k logs metisdb-mariadb-pre-change-nx5wj
ERROR 1133 (28000) at line 9: Can't find any matching row in the user table
command terminated with exit code 1
```
My proposal is to move the grant to the values.yaml instead of having it hard-wired

[mariadb] moves grants for backup user to values

---

openstack/maia/Chart.yaml
openstack/maia/values.yaml

it was using the wrong directive and that's why alertmanager couldn't be set up fqdn helper should be happy now

[maia] get ingress to actually be there

---

prometheus-exporters/openstack-exporter/Chart.lock
prometheus-exporters/openstack-exporter/Chart.yaml
prometheus-exporters/openstack-exporter/alerts/cinder.alerts
prometheus-exporters/openstack-exporter/values.yaml

This patch adds the support_group label.
This patch changes the CinderPoolDown alert to CinderPoolOvercommited as we only care if a pool is overcommited.

[openstack-exporter][cinder] Update cinder alerts

---

openstack/placement/Chart.lock
openstack/placement/Chart.yaml
openstack/placement/values.yaml

We need to bump the mariadb and memcached chart to get support for setting the support_group label on the included alerts and we also have to include the owner-info chart for getting support for setting support_group on the k8s objects' alerts.

[placement] Add support_group label to all alerts

---

openstack/cinder/Chart.lock
openstack/cinder/Chart.yaml
openstack/cinder/values.yaml

We need to bump mariadb and memcached chart versions to get support for setting the support_group label on the included alerts and we also have to include the owner-info chart for getting support for setting suport_group on the k8s objects' alerts.
Bumping mariadb to >= 0.6.0 needs an explicit password set for the backup user.

[cinder] Add support_group label to all alerts

---

openstack/limes/values.yaml

See description in the code comment.

limes: ignore small Swift inconsistencies in limes_overspent_project_quota_count metric

---

openstack/maia/Chart.yaml
openstack/maia/templates/etc/_maia_scrape_config.yaml.tpl

snmp was too inclusive and has no use without project_id

[maia] project filtering for snmp

---

openstack/placement/values.yaml

We didn't have logging for placement on INFO since we switched from Nova-based images on Rocky to Placement's own images on Yoga, because we forgot to switch over the logger definition. With fixing the logger here, we get back INFO-level logging and by that global request ids back in the log lines of all requests.

[placement] Set logging to INFO

---

openstack/nova/alerts/openstack/nova.alerts

There are cases when we still have duplicate BDM entries or general BDM entries without connection_info. This is one of the cases, where volume detachment will fail.
We build this alert to become aware of such problems. This alert is also the first of its kind using oslo_messaging_events metric. We would like to see if we can build alerts based on that metrics and if this helps us.

[nova] Add alert for failing detach_volume RPCs

---

common/mariadb/Chart.yaml
common/mariadb/templates/alerts/_mysql.alerts.tpl
common/mariadb/templates/etc-configmap.yaml
common/mariadb/values.yaml

e.g. having a slow query every 7 minutes (seen in manila) would make this alert flap around a lot, smoothen a bit by increasing the rate to 30 min

[common][mariab] make slow queries alert less flappy

---

openstack/ironic/templates/console-configmap.yaml

Prior this change, nginx would expire the url for all requests. The problem here is that the javascript app running in the browser will periodically do a POST request with a session id and possibly commands
to the url, and the validation will break that.
To make matters worse, the app won't close the session normally, keeping the shell on the server running
until it timeouts.
The session-id replaces the authenticated url as a secret, so we do not need to validate the POST requests anymore.
In similar vein, validating the url for static resources is superfluous, and we can pass those requests right through.

[Ironic] Limit authentication to initial connection

---

px/bird/templates/_deployment_header.tpl
px/bird/templates/bird.yaml
px/bird/values.yaml

We have regions where PX was only build on Arista, yet the apods on the
Arista-Farbic still have a no-schedule taint. We need to be able to set
a toleration, hence introducing a switch.

[PX] Add switch to tolerate arista fabric no-schedule taint

---

system/metis/Chart.yaml
system/metis/templates/_replication-etc-configmap.tpl
system/metis/templates/metis-etc-configmap.yaml
system/metis/templates/metis-secrets.yaml
system/metis/templates/replication-deployment.yaml
system/metis/templates/sync-deployment.yaml
system/metis/templates/sync-etc-configmap.yaml
system/metis/templates/sync-secrets.yaml
system/metis/values.yaml

Changes:
- sync-pod replace replication. Pulls full backup + increments from swift instead of pulling dump from DB.
- metis pod: adds config required for guestOS collection from vCenter

[metis] adds sync-pod, adds config for vcenter guestOS sync to metis

---

prometheus-exporters/vrops-exporter/templates/collector-configmap.yaml

The "OnlineCapacityAnalytics" metrics are not reliable for monitoring current capacity. As suggested by VMware we should solely use the "capacity" metrics.
Metric keys were tested manually in qa-de-1.

[vrops-exporter] Avoid using Analytics Metrics

---

openstack/designate/templates/api-deployment.yaml

- liveness to use /healthcheck oslo middleware
- readiness to additionally check if DB is up

[designate] rework readiness and liveness probes

---

openstack/maia/Chart.yaml
openstack/maia/templates/etc/_maia_scrape_config.yaml.tpl
openstack/maia/values.yaml

given the amount of data returned by single matches in large regions respective queries should be as minimal as possible. This will reduce scrape times to a minimum. Only implemented for prometheus-vmware targets, as it is only needed there
Additionally: neo federate is in a dedicated job now if applicable

[maia] scrape jobs with single match query

---

openstack/cinder/alerts/openstack-cinder.alerts

Since we have potentially long attachment times, we should be warned if a volume is stuck in attaching state for more than 1 hour.

[cinder] Update cinder attaching alert to 1 hour

---

openstack/nova/Chart.lock
openstack/nova/Chart.yaml
openstack/nova/values.yaml

0.7.2 lowers severity of the slow-query alert to INFO.
0.7.3 reduces flappiness by calculating rate over 30m instead of 5m.
0.7.4 makes the slow-query time threshold configurable, and sets a default of 5 seconds (the literal value was 3s previously).
Override that default with 8s based on the following sample data from eu-de-1:
```
$ cat [...]-slow.log | grep Query_time | cut -d ' ' -f 3 \
| sort -h | cut -d '.' -f 1 | uniq -c
35 3
3515 4
1693 5
47 6
5 7   <- there seems to be a marked cutoff after here
1 9
2 10
2 11
2 12
2 14
2 15
1 16
1 199
1 200
1 204
```
The huge times are backup queries.

[nova] Bump mariadb 0.7.4 for slow query warnings

---

openstack/octavia/values.yaml

Added for mariadb, memcached and rabbitmq [here](https://github.com/sapcc/helm-charts/pull/4295), but aliased subchart rabbitmq_notifications was missing

[Octavia] Add support_group for subchart rabbitmq_notifications

---

prometheus-exporters/elastiflow-query-exporter/Chart.lock
prometheus-exporters/elastiflow-query-exporter/Chart.yaml
prometheus-exporters/elastiflow-query-exporter/values.yaml
prometheus-exporters/elk-query-exporter/Chart.lock
prometheus-exporters/elk-query-exporter/Chart.yaml
prometheus-exporters/elk-query-exporter/values.yaml
prometheus-exporters/octobus-query-exporter/Chart.lock

- Adding owner info to charts elk-query-exporter, elastiflow-query-exporter
-  creates Chart.lock for octobus-query exporter.
FYI @Kuckkuck @notque

[elastic-query-exporters] adds owner info

---

openstack/nova/templates/_console_deployment.yaml.tpl
openstack/nova/templates/_helpers.tpl
openstack/nova/templates/api-deployment.yaml
openstack/nova/templates/api-metadata-deployment.yaml
openstack/nova/templates/bigvm-deployment.yaml
openstack/nova/templates/cell2-conductor-deployment.yaml
openstack/nova/templates/conductor-deployment.yaml
openstack/nova/templates/db-migrate-job.yaml
openstack/nova/templates/db-online-migrate-job.yaml
openstack/nova/templates/hypervisors/_ironic-deployment.yaml.tpl
openstack/nova/templates/hypervisors/_kvm-deployment.yaml.tpl
openstack/nova/templates/hypervisors/hypervisors-vmware-deployment-vct.yaml
openstack/nova/templates/scheduler-deployment.yaml

Once we're not on Rocky anymore, we will use the loci images instead of the ones built by kolla. To facilitate that change, we use the container_image_nova helper introduced a long time ago everywhere, but change it to check the image-version.

[nova] Switch to loci images in Xena

---

common/mariadb/Chart.yaml
common/mariadb/values.yaml

The version contains the following 
Fixes for the following [security vulnerabilities](https://mariadb.com/kb/en/cve/):
[CVE-2022-32082](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-32082)
[CVE-2022-32089](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-32089)
[CVE-2022-32081](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-32081)
[CVE-2018-25032](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-25032)
[CVE-2022-32091](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-32091)
[CVE-2022-32084](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-32084)
Full Release Notes can be found: https://mariadb.com/kb/en/mariadb-10517-release-notes/

[MariaDB] - Security Patches - upgrade to 10.5.17

---

openstack/neutron/templates/configmap-etc-cc-fabric.yaml
openstack/neutron/templates/etc/_ml2-conf-aci.ini.tpl
openstack/neutron/templates/etc/_ml2-conf-cc-fabric.ini.tpl

Both drivers will have a configuration option to let them handle l3 gateways by default.

Make l3 gateway handling configurable for aci/cc-fabric

---

openstack/nova/templates/bin/_db-migrate.tpl

This functionality got removed between Rocky and Xena and according to the removing commit, was actually no longer necessary since Liberty.

[nova] Don't run null_instance_uuid_scan on db

---

prometheus-exporters/netapp-exporter/charts/netapp-cap-exporter/alerts/netapp-capacity.alerts

When aggregate not reachable, the alert should also be fired.

fix aggregate offline alerts

---

openstack/nova/templates/etc/_nova.conf.tpl

Nova has a high amount of open memcached connections in prod. This might be related to keystonemiddleware not using oslo.cache but an old in-house CacheClient implementation.
There is a good explanation of this issue when upstream enabled oslo.cache in Zed by default [1].
Neutron has already enabled this in prod a long time ago [2].
[1] https://github.com/sapcc/keystonemiddleware/commit/788d3c4969e3446778496f3a9055f654602ae2c1
[2] https://github.com/sapcc/helm-charts/commit/0a0f884ebeb6f9e2e9d944bac89d1cbc3561f2de

[nova] use oslo.cache MemcacheClientPool for keystone_auth tokens

---

prometheus-rules/prometheus-vmware-rules/alerts/host.alerts
prometheus-rules/prometheus-vmware-rules/alerts/vccluster.alerts
prometheus-rules/prometheus-vmware-rules/alerts/vcenter.alerts

As requested by Operations.
Not needed alerts:
- HostDiskSpaceUsageWarning
- HostRootFilesystemUnhealthy
- VCenterDiskSpaceUsageWarning
Alert duplicate:
- VCenterRedundancyLostFailoverHostMissing

Remove not needed alerts

---

openstack/nova/templates/etc/_nova-policy.yaml.tpl

System-scoped endpoints got their "target" dict set to an empty dict which made our previous way to write the policy break. Instead of having only "rule:owner", we now also allow "rule:projectless" for view, member and admin rules. This makes sure that these roles are also allowed to use non-project endpoints e.g. listing availability zones where the target is empty.
Previously, those endpoints did not set an explicit target and thus got
the default: the token's project_id.

[nova] Update policy for system-scoped endpoints

---

openstack/cc3test/Chart.yaml
openstack/cc3test/alerts/compute.alerts

fixing playbook link for alert OpenstackComputeCanaryCreateHanaServerDown to point to the new documentation under https://operations.global.cloud.sap/docs/support/playbook/nova/alerts/cc3test-alert-create-server-bb/

[cc3test] fix playbook link for nova alerts

---

openstack/ironic/templates/console-configmap.yaml

The match was missing the part which contained
the verification code.

[ironic] Fix shellinabox console

---

common/prometheus-monitors/Chart.yaml
common/prometheus-monitors/README.md
common/prometheus-monitors/ci/test-values.yaml
common/prometheus-monitors/templates/_helpers.tpl
common/prometheus-monitors/templates/podmonitor.yaml
common/prometheus-monitors/templates/servicemonitor.yaml
common/prometheus-monitors/values.yaml

For proper alert routing we require certain labels to be attached to a metric (e.g. region, cluster_type). Many Pod|ServiceMonitors in this repository do not set these labels. The problem is that every chart maintainer must be aware of these mandatory labels for alert routing.
Previously this was not an issue, since most pods/services were scraped by one scrape job discovering targets via the prometheus scrape annotations.
This Subchart should provide a similarly convenient  option of adding a Pod|ServiceMonitor with a certain set of defaults and the option to further adjust the scrape configuration.
Example metric with default relabelings:
https://prometheus-infra-collector.qa-de-1.cloud.sap/graph?g0.expr=metis_replication_restart_counter%7Bpod%3D~%22mariadb-sync-nova-api.*%22%7D&g0.tab=1 …

[prometheus-monitors] subchart for Pod|ServiceMonitors with default relabelings

---

prometheus-rules/prometheus-vmware-rules/alerts/vccluster.alerts

Every NSX-T Management Cluster consists out of 3 nodes. Each node must be placed on a different host. The alert triggers, if we have less than 3 hosts with enough resources.

Adding VCClusterHasNotEnoughResourcesToDistributeNSXTControllers alert

---

openstack/keystone/templates/pdb.yaml

policy/v1beta1 API version of PodDisruptionBudget will no longer be served in v1.25
Ref : https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125

[Keystone] Migrate pdb manifests to use the policy/v1 API version

---

openstack/cc3test/templates/cronjob-api.yaml
openstack/cc3test/templates/cronjob-automation.yaml
openstack/cc3test/templates/cronjob-baremetal.yaml
openstack/cc3test/templates/cronjob-blockstorage-volume-hana.yaml
openstack/cc3test/templates/cronjob-blockstorage-volume-regular.yaml
openstack/cc3test/templates/cronjob-blockstorage.yaml
openstack/cc3test/templates/cronjob-certificate.yaml
openstack/cc3test/templates/cronjob-compute-server-hana.yaml
openstack/cc3test/templates/cronjob-compute-server-regular.yaml
openstack/cc3test/templates/cronjob-compute.yaml
openstack/cc3test/templates/cronjob-datapath.yaml
openstack/cc3test/templates/cronjob-datastore.yaml
openstack/cc3test/templates/cronjob-dns.yaml
openstack/cc3test/templates/cronjob-fileshare.yaml
openstack/cc3test/templates/cronjob-hermes.yaml
openstack/cc3test/templates/cronjob-integrity.yaml
openstack/cc3test/templates/cronjob-key-manager.yaml
openstack/cc3test/templates/cronjob-loadbalancer.yaml
openstack/cc3test/templates/cronjob-neutron-fip.yaml
openstack/cc3test/templates/cronjob-neutron.yaml

if the tests do not return 0 kubernetes might just restart them over and over and trying to set a exit status 0 within the tests seems to confuse pytest, so simply set it after executing the test, so that always exit 0 is returned to kubernetes to make it happy

cc3test: set a defined exit code for the pytest tests

---

openstack/clair/ci/test-values.yaml
openstack/clair/templates/configmap.yaml
openstack/clair/templates/deployment-indexer.yaml
openstack/clair/templates/deployment-matcher.yaml
openstack/clair/templates/etc/_config.yaml.tpl
openstack/clair/templates/ingress.yaml
openstack/clair/templates/service-indexer.yaml
openstack/clair/templates/service-matcher.yaml

This allows us to scale each component individually and drop the unused notifier.

openstack/clair: split combo deployment into split openstack

---

openstack/cc3test/alerts/block-storage.alerts

- OpenstackCinderCreateVolumeShardDown
- direct link to the playbook instead of the parent folder
- https://jira.tools.sap/browse/CCC-34265

[cc3test] playbook path updated for cinder alert

---

openstack/nova/templates/etc/_nova.conf.tpl

These settings have defaults we do not want - e.g. 16 x CPU overcommit and 1.5 x RAM overcommit. They are only used to set defaults when a new ComputeNode object is created and during an online data migration when upgrading to Xena if they are set to None or 0. The allocation ratios can then overwritten by the nova-compute service later on.

[nova] Set initial allocation ratios

---

openstack/nova/shellinabox/10_default_server.conf

The header is set by default in the docker image,
and stops us from using the console in an iframe
as Elektra does.

[nova] Unset X-Frame-Options in shellinabox

---

openstack/maia/templates/etc/_maia_scrape_config.yaml.tpl

Based on a customer request, I added the metric `keppel_manifests_with_unclean_vuln_status_count` in af5e6d6f2. Our pgmetrics end up in prometheus-openstack, so this needs to be federated into Maia.

maia: add federation for Keppel metrics

---

openstack/octavia/templates/_helpers.tpl
openstack/octavia/templates/octavia-migration-job.yaml

This is better than using discriminators (based on image tags) in the job name, since the image tag may not change when other dependencies change.

[Octavia] Annotate migration job as hook

---

common/thanos/Chart.yaml
common/thanos/ci/test-values.yaml
common/thanos/templates/_thanos_helpers.tpl
common/thanos/templates/alerts/_thanos-compactor.alerts.tpl
common/thanos/templates/alerts/_thanos-query.alerts.tpl
common/thanos/templates/alerts/_thanos-store.alerts.tpl
common/thanos/templates/alerts/thanos-alerts.yaml
common/thanos/templates/ingress-grpc.yaml
common/thanos/templates/ingress.yaml
common/thanos/templates/thanos-objectstore.yaml
common/thanos/templates/thanos-storeendpoint.yaml
common/thanos/templates/thanos.yaml
common/thanos/values.yaml

Enabling the common chart to deploy multiple Thanos along Prometheus. This can be done either via the list `names: []` or via a list of targets to create Thanos `global.targets: []`.

[common thanos] Enablement to create multiple thanos

---

system/vmware-monitoring/Chart.yaml
system/vmware-monitoring/alerts/vrops-exporter.alerts
system/vmware-monitoring/ci/test-values.yaml
system/vmware-monitoring/templates/_helper.tpl
system/vmware-monitoring/templates/alerts.yaml
system/vmware-monitoring/templates/collector-configmap.yaml
system/vmware-monitoring/templates/inventory-configmap.yaml
system/vmware-monitoring/templates/vrops-exporter-deployment.yaml
system/vmware-monitoring/templates/vrops-inventory-deployment.yaml
system/vmware-monitoring/templates/vrops-inventory-exporter-deployment.yaml
system/vmware-monitoring/values.yaml

Merge `vrops-exporter` and `prometheus-vmware` to create resources for multiple monitoring targets. 
The chart requires the newly implemented dependency prometheus-server 7.1.0 and thanos 0.2.0, which are capable of creating multiple resources. 
vrops-exporter alerts are still deployed with this chart. They will be moved to a separate chart in the future.

Introducing vmware-monitoring

---

openstack/cerebro/templates/domain-ccadmin-seed.yaml
openstack/cerebro/values.yaml

Adding technical TCC_CEREBRO_001 user to all regions in the CCADMIN domain, with the necessary permissions for Cerebro operations.

cerebro: Add ccadmin domain technical user and role assignments

---

openstack/octavia/values.yaml

This PR increases limit and request resources for two containers in octavia-worker pod based on graphics because we have CPU throttling and as result OOMkiller kills the containers.

[octavia] Increate limits for containers in octavia-worker pods.

---

common/memcached/Chart.yaml
common/memcached/templates/alerts/_memcached.alerts.tpl
common/memcached/values.yaml

This alert is not actionable, as it is at best a hint for possible performance degradations - yielded connections are connections doing multiple requests in batches and memcached interrupting to read from that same connection to give other connections a change to get processed and not starve out.
We also make the threshold for the alert configurable as different services might have different thresholds.

memcached: Move yielded connections alert to info

---

openstack/cinder/templates/etc/_cinder.conf.tpl
openstack/cinder/values.yaml

This patch adds the cinder.conf setting of
sap_allow_independent_snapshots to default to True. This allows all cinder snapshots to go through the scheduler to pick which pool (datastore) the snapshot will live on.

[Cinder] Enable independent snapshots by default

---

openstack/neutron/templates/statefulset-network-agent-apod.yaml

Right now there is a not too small chance that any 2 network agents of a
network in a single-site region or an az-local network end up on the
same hypervisor. That is because we only use anti-affinity on hostname
level, but not on the physical host level.
To make this a little less likely, let us add a higher-weighted
anti-affinity on the physical host level. That way we avoid scheduling
on the same machine a long as there are enough machines available. In
case there are not, we will still schedule but just on another VM. These
are all soft affinities, so nothing will stay in pending.
Unfortunately we cannot just reduce the amount of replicas, as the
number of physical machines varies between regions. If a physical
machine were to be taken out, that would reduce the number of replicas
and …

[neutron] Avoid that network agents are co-scheduled on the same machine

---

openstack/nova/Chart.lock
openstack/nova/Chart.yaml
openstack/nova/values.yaml

This reduces the alert-level to info by updating the memcached chart and also sets the threshold for triggering the alert in Nova to a higher threshold, because looking at the current levels we didn't see any service degradation.

[nova] memcached alert becomes info-level and less triggery

---

openstack/nova/values.yaml

With ESXi ignoring an upper-case character at the start and a number at the end of a password for counting the used and required character classes, we need to use every class at least twice to make the password fit the policy. Nova recently added code to make this possible, so we're setting the password_all_group_samples setting here to enable it.

[nova] Set password_all_group_samples to 2

---

openstack/nova/templates/hypervisors/hypervisors-vmware-deployment-vct.yaml

We had the terminationGracePeriodSeconds key set in the definition of a container, but it's a setting for the whole pod and thus needs to be set directly under the "spec".

[nova] Set terminationGracePeriodSeconds properly for nova-compute

---

openstack/cinder/templates/etc/_cinder.conf.tpl
openstack/cinder/values.yaml

This patch updates the cinder helm chart to enable the new cinder ability to allow independent cinder clones. This means that volumes created from another volume can be scheduled on a different pool (datastore) on the same backend as the source volume.
By default cinder doesn't allow this.

[Cinder] Enable independent clone by default

---

openstack/keystone/templates/deployment-2faproxy.yaml

We used to inject http://keystone.monsoon3.svc.kubernetes.qa-de-2.cloud.sap:5000/v3 via secrets but this requires a dns lookup and a working coredns in the clusters.
By using the service ip directly we remove a dependency and make the keystone datapath more robust

keystone: avoid dns dependency for 2faproxy

---

openstack/ironic/values.yaml

Since it is working in some regions, we might as well open the option to enable it in all regions.
We still need to configure it on a host-by-host
basis, so the impact of this change is close to zero by itself.

[ironic] Enable idrac-redfish and redfish

---

openstack/nova/Chart.lock
openstack/nova/Chart.yaml

This updates the mariadb image version to include security patches.

[nova] Bump mariadb dependency to 0.7.5

---

system/unbound/templates/config.yaml

by default hosts that are down, eg. they did not respond during the one probe  at  a  time period,  are  marked as down and it may take infra-host-ttl time to get probed again.

[unbound] enable infra-keep-probing reduce host ttl from 15 to 10 mins.

---

openstack/cinder/Chart.lock
openstack/cinder/Chart.yaml

This patch updates the mariadb chart to 0.7.5 for cinder.

[Cinder] Update mariadb chart to 0.7.5

---

common/prometheus-server/CHANGELOG.md
common/prometheus-server/Chart.yaml
common/prometheus-server/templates/_helpers.tpl
common/prometheus-server/templates/thanos/thanos-seed.yaml
common/prometheus-server/values.yaml
system/thanos-seeds/.helmignore
system/thanos-seeds/Chart.yaml
system/thanos-seeds/ci/test-values.yaml
system/thanos-seeds/templates/_helpers.tpl
system/thanos-seeds/templates/seed.yaml
system/thanos-seeds/values.yaml

introduced system/thanos-seeds chart
prometheus-server is not taking care of seed deployment anymore. prometheus-server helpers changed to meet requirements. helper file is used by system/thanos-seeds too. new directive introduced thanosSeeds

[prometheus] dedicated seed deployment

---

system/prometheus-infra/Chart.yaml
system/prometheus-infra/alerts/prometheus.alerts
system/prometheus-infra/templates/_prometheus-infra.yaml.tpl
system/prometheus-infra/values.yaml
system/vmware-monitoring/Chart.yaml
system/vmware-monitoring/templates/servicemonitors/infra-frontend.yaml

* as we are in the same cluster, we deploy service monitors instead of directly instrumenting the federation target instance (prometheus-infra-frontend)
* federation will be in place until it is fully replaced by thanos everywhere

use smons for prometheus-infra-frontend

---

system/elastiflow/values.yaml

This init container only changes file permissions on a mounted volume. It does not need to run in privileged mode as far as I can see.

elastiflow: drop unnecessary privileges on initContainer

---

system/infra-monitoring/vendor/px-exporter/px.alerts/px.alerts

[PX] Adjust transport router down alert
The PXTransportRouterBgpDown fires upon loss of at least one peering to
he transport router. To reduce the number of self healing alerts the
alert fires now after 60 minutes.
Additionally, we add PXTransportAllRouterBgpDown as another cirtical
alert firing after 1 minute. This alert triggers when connectivity to
all transport routers is lost.

I544510 pxalerting

---

common/prometheus-server/CHANGELOG.md
common/prometheus-server/Chart.yaml
common/prometheus-server/templates/alertmanager-config.yaml
common/prometheus-server/templates/alertmanager-sso-secret.yaml
common/prometheus-server/templates/alerts/prometheus-alerts.yaml
common/prometheus-server/templates/alerts/prometheus-thanos-alerts.yaml
common/prometheus-server/templates/cluster-role-binding.yaml
common/prometheus-server/templates/cluster-role.yaml
common/prometheus-server/templates/ingress-internal.yaml
common/prometheus-server/templates/ingress.yaml
common/prometheus-server/templates/podmonitors/kube-dns.yaml
common/prometheus-server/templates/podmonitors/pod-sd.yaml
common/prometheus-server/templates/prometheus-server.yaml
common/prometheus-server/templates/service-account.yaml
common/prometheus-server/templates/service.yaml
common/prometheus-server/templates/servicemonitors/apiserver.yaml
common/prometheus-server/templates/servicemonitors/cadvisor.yaml
common/prometheus-server/templates/servicemonitors/endpoint-sd.yaml
common/prometheus-server/templates/servicemonitors/kubelet.yaml
common/prometheus-server/templates/servicemonitors/node-exporter.yaml
common/prometheus-server/templates/servicemonitors/prometheus.yaml
common/prometheus-server/templates/thanos/thanos-config-secret.yaml
common/prometheus-server/templates/thanos/thanos-seed.yaml
common/prometheus-server/templates/vpa.yaml

The order can cause the targets to be preferred to the set name. For example, if a prometheus needs the targets additionally as for scrape jobs, multiple prometheus instances of the targets are created by default. What is not wanted.

common/prometheus-server: order of coalescence corrected

---

common/rabbitmq/CHANGELOG.md
common/rabbitmq/Chart.yaml
common/rabbitmq/templates/bin/_rabbitmq-start.tpl
common/rabbitmq/templates/deployment.yaml
common/rabbitmq/templates/statefulset.yaml
common/rabbitmq/values.yaml

added a switch to activate rabbitmq-prometheus plugin instead of the side car exporter. to activate collect metrics with plugin please set your values to:
```
metrics:
port: 9150
enabled: false
sidecar:
enabled: false
```
RabbitMQ-prometheus plugin provides different naming schema of the metrics as the side car RabbitMQ exporter.
metrics can be found: https://github.com/rabbitmq/rabbitmq-prometheus/blob/master/metrics.md
default values still using metrics sidecar exporter

[rabbitmq] add support for rabbitmq-prometheus

---

openstack/neutron/values.yaml

This option asks the NSX-T agent to provision default infrastructure
Policy Rules for:
* DHCP
* ICMP
* Metadata Service
These can co-exists with the (same) management based security section/rules.
In a second step, the old section based rules will be deleted by the infrastructure team.

[neutron] NSX-T: enable global provisioning of NSX-T Infra policy rules

---

openstack/swift-drive-autopilot/templates/daemonset.yaml

The restriction for `qa` can go after it soaked in that regions a while

Temporary test kernel.panic_on_oops=0 in qa

---

openstack/sap-seeds/templates/_flavors_hana_exclusive.tpl
openstack/sap-seeds/templates/_flavors_hana_no_exclusive.tpl

Nova's VMware driver uses the number given in `hw:cpu_cores` to set the CoresPerSocket VMware setting for the VM[1]. While I think that's probably a misunderstanding of what CoresPerSocket means by the original author (description in [2], compare with "numCoresPerSocket" in [3]), and should probably be fixed in the driver, let's do the quick fix first and adjust the values for the flavors.
We thus use the NUMA node CPU number for the HANA flavors, which means 48 for most HANA flavors/BBs and 56 for the 12TiB flavors & BBs. This aligns with the trait names CUSTOM_NUMASIZE_C48_M729 and CUSTOM_NUMASIZE_C56_M1459 respectively.
Also, add the same "hw:cpu_cores" for all smaller HANA flavors, because otherwise they too get smeared all over the sockets and who wants to clean that mess up, really. …

[sap-seeds] Fix cores-per-socket for HANA flavors

---

global/prometheus-alertmanager-operated/Chart.yaml
global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl

Inhibits `KubernikusEtcdBackupFailed` if `KubernikusKlusterLowOnObjectStoreQuota`
Necessary label `kluster_name` on the alerts is deployed:
E.g.
https://alertmanager.scaleout.eu-de-1.cloud.sap/#/alerts?silenced=false&inhibited=false&active=true&filter=%7Balertname%3D%22KubernikusKlusterLowOnObjectStoreQuota%22%7D
https://alertmanager.scaleout.eu-de-1.cloud.sap/#/alerts?silenced=false&inhibited=false&active=true&filter=%7Balertname%3D%22KubernikusEtcdBackupFailed%22%7D

[alertmanager] Inhibit dependent kubernikus alerts

---

prometheus-rules/prometheus-vmware-rules/alerts/datastore.alerts

The alert was pointing to a non-existing link. Corrected it that it jumps to the correct playbook.

Corrected broken link for NVMeDataStoreAlmostFullyUtilised

---

openstack/octavia/alerts/octavia.alerts
openstack/octavia/values.yaml

Change octavia_seconds_since_last_nonpending_status in two ways:
- Add `vip.network_id` field, so that it's more easily noticeable when one stuck LB clogs an entire tenant (tenants map to networks).
- Consolidate field names: Rename `octavia_host` to `loadbalancer_host` and `current_status` to `loadbalancer_status`, so that these related fields appear together in the metrics overview.
As far as I know the `octavia_seconds_since_last_nonpending_status` metric is not consumed by any automation.

[octavia] Pending LBs metric: Consolidate field names, add network ID

---

openstack/neutron/templates/etc/_neutron-policy.json.tpl

The check rule:owner is much faster than the check rule:network_owner, as rule:network_owner needs to look up a network in neutron, which means another DB query + dict buildup in python. rule:owner only looks up fields that are already available on the port that the policy is checked for.
The rule network_owner_or_owner is mainly used by get_ports, so hopefully this increases the performance for port lists in Neutron for ports in non-shared networks by users that are scoped to a project.
Co-Authored-By: Johannes Kulik <johannes.kulik@sap.com>

[neutron] Flip network_owner_or_owner policy for performance

---

prometheus-rules/prometheus-vmware-rules/alerts/datastore.alerts
prometheus-rules/prometheus-vmware-rules/alerts/nsxt.alerts
prometheus-rules/prometheus-vmware-rules/alerts/virtualmachine.alerts

For better analyses and accountability I would like to adjust the service labels of some alerts from the compute support group according to their service group (compute, storage, network).
@geisslet I hope the service label is free to choose and won't affect routing/paging.

Adjusted service labels for compute alerts

---

openstack/glance/Chart.lock
openstack/glance/Chart.yaml
openstack/glance/templates/deployment.yaml
openstack/glance/templates/etc/_glance-api.conf.tpl
openstack/glance/values.yaml

Sqlalchemy has a pool per process, and for each worker a process is started. To maintain the same number of maximum connections in proxysql, we need to multiply the number by the number of workers
Also, update proxysql by a minor version

[glance] Bump proxysql and scale by workers

---

openstack/ironic/Chart.lock
openstack/ironic/templates/api-deployment.yaml
openstack/ironic/templates/inspector-deployment.yaml
openstack/ironic/templates/pxe-deployment.yaml

The pod will receive the shutdown request at the same time as
the as the endpoint-controller, which will then propagate the
change to the kube-proxy.
That in turn means that the pod will still receive requests
from other clients while being in the process of being shut down.
This leads then to connection errors during the time that
event propagates through the network stack of kubernetes.
To avoid that, we delay the actual shutdown by a fixed period,
which should, if not eliminate, but reduce the number of those errors

[Ironic] Shutdown delay to avoid connection resets

---

system/sentry/Chart.lock
system/sentry/Chart.yaml
system/sentry/charts/postgresql/templates/deployment.yaml
system/sentry/charts/postgresql/values.yaml
system/sentry/ci/test-values.yaml
system/sentry/values.yaml

This bumps backup-tools from 0.6.5 to 0.7.0 and moves it into a separate pod, so it can be upgraded in the future without having to restart the postgres container.
The new pgbackup chart is already deployed and tested across all regions in my own services (Castellum, Limes, Keppel, Tenso).
This also fixes the lack of backup monitoring and alerts for Sentry.
Please merge this together with the respective companion PR in cc/secrets.

sentry: use new common/pgbackup chart

---

openstack/neutron/templates/vct-nsxv3-agent-configmap.yaml

In 96cea43ef5 we changed all VCenterTemplate objects to include a vcenter label. All other templates use the "host" variable to set the "vcenter" label, except the nxv3-agent-configmap, which uses the "vcenter_name" variable.
We change the configmap to use the "host" variable to make the label consistent over all VCenterTemplates.

[neutron] Use "host" variable for "vcenter" label

---

openstack/ironic/templates/etc/_ironic_conductor.conf.tpl
openstack/ironic/values.yaml

This setting allows us to enable or disable the erasure of the disk
during the cleaning of a node. For now, we want to disable this. Later we
can then enable it again. The other cleaning steps shouldn't cause major
issues but by enabling automated cleaning for some regions blocks we can
test if we find any other issues.
@stefanhipfel please make sure that makes sense. I'm still not very familiar with helm.

Ironic: Add setting to controll disk erase

---

openstack/nova/templates/hypervisors/hypervisors-vmware-configmap-vct.yaml
openstack/nova/values.yaml

Previously, we were enabling vnc for all hypervisors globally, but we rather do not want to do that for vmware, where mks is preferred
We set the vnc value for for the compute node,
which overrides the value in nova.conf

[nova] Enable/Disable vnc on hypervisor level

---

openstack/lyra/Chart.lock
openstack/lyra/Chart.yaml
openstack/lyra/ci/test-values.yaml
openstack/lyra/values.yaml

This bumps backup-tools from 0.6.5 to 0.7.0 and moves it into a separate pod, so it can be upgraded in the future without having to restart the postgres container.
This new setup is already deployed and tested in my own services (Castellum, Keppel, Limes and Tenso).
Since this will restart the postgres container anyway, I took the liberty of bumping Postgres from 12.11 to 12.13. This is a bugfix release with no incompatibilities, my own services are already running on 12.13 without any issues.
Merge this together with the respective companion PR in cc/secrets.

lyra: use new common/pgbackup chart

---

openstack/arc/Chart.lock
openstack/arc/Chart.yaml
openstack/arc/charts/postgresql/README.md
openstack/arc/charts/postgresql/templates/deployment.yaml
openstack/arc/charts/postgresql/templates/secrets.yaml
openstack/arc/charts/postgresql/templates/svc.yaml
openstack/arc/charts/postgresql/values.yaml
openstack/arc/ci/test-values.yaml
openstack/arc/values.yaml

This bumps postgres-exporter from 0.8.0 to 0.10.1 and backup-tools from 0.6.5 to 0.7.0, and moves them into separate pods, so they can be upgraded in the future without having to restart the postgres container.
Merge this together with the respective companion PR in cc/secrets.

arc: use common/pgmetrics and common/pgbackup charts

---

openstack/grafanasix/Chart.lock
openstack/grafanasix/Chart.yaml
openstack/grafanasix/values.yaml

This bumps backup-tools from 0.6.5 to 0.7.0 and moves it into a separate pod, so it can be upgraded in the future without having to restart the postgres container.
This change is already rolled out to prod for Arc, Castellum, Elektra, Keppel, Limes, Lyra, Sentry and Tenso.
Note that this only generates a diff in grafanasix-author; the other Grafanas do not have a database backup.
Merge this together with the respective companion PR in cc/secrets.

grafanasix: use new common/pgbackup chart

---

openstack/glance/Chart.lock
openstack/glance/Chart.yaml

There is a race between the startup of proxysql
and the poststarthook trying to access it.
The updated dependency will fix that.
Also update proxysql to the latest minor version
for various bugfixes

[glance] Update utils with proxysql startup fixes

---

openstack/manila/Chart.lock
openstack/manila/Chart.yaml
openstack/manila/ci/test-values.yaml
openstack/manila/templates/api-deployment.yaml
openstack/manila/templates/bin/_db_migrate.sh.tpl
openstack/manila/templates/etc/_wsgi-manila.conf.tpl
openstack/manila/templates/migration-job.yaml
openstack/manila/templates/proxysql-configmap.yaml
openstack/manila/templates/scheduler-deployment.yaml
openstack/manila/templates/shares/_netapp-deployment.yaml.tpl
openstack/manila/templates/shares/_netapp-ensure-deployment.yaml.tpl
openstack/manila/values.yaml

As this chart works with a pre-upgrade hook,
care has to be taken when using
proxysql.mode=unix_socket
The pre-upgrade hook works with the configmap using the old values,
while the chart would be rendered with the new values.
The only mode that works with both is
proxysql.mode=host_alias
So when either switching from no proxysql to unix_socket
or the other way around, a deployment in with the host_alias mode
is needed in between.

[manila] Add ProxySQL side-cars

---

openstack/glance/templates/_helpers.tpl
openstack/glance/templates/deployment.yaml
openstack/glance/templates/migration-job.yaml

Jobs cannot be changed, so all settings need
result in a new job-name.

[glance] Generate job-name from proxysql settings

---

openstack/sap-seeds/templates/_flavors_hana_exclusive.tpl
openstack/sap-seeds/templates/_flavors_hana_no_exclusive.tpl

If `hw:cpu_cores` is larger than the amount of actual CPUs in the flavor our topology is not even suggested in `nova/virt/hardware.py`, and the variant with maximum cores (i.e. cores-per-socket = 1) is selected by nova instead.
Fix the half-socket flavor `hana_c24_m365` to only request 24 cores-per-socket through the `hw:cpu_cores` extra spec.

[sap-seeds] Fix cores-per-socket > total cores

---

px/bird/Chart.lock
px/bird/Chart.yaml
px/bird/templates/_deployment_header.tpl
px/bird/templates/podmonitor.yaml

px pods are scraped from the prometheus infra-collector by annotations via the job `pods`. Custom relabeling should not be done on a default scrape job. Since we enable `pod-sd` in #4566 and the scrape job `pods` is [omitted](https://github.com/sapcc/helm-charts/pull/4566/commits/a7eb11f5a4d84c9c9955696eee1c5fb14fb5ff17), the custom relabeling is now meaningfully assigned to the px chart.

px: added podmonitor for custom relabeling

---

openstack/sap-seeds/templates/flavor-seed.yaml

This flavor is needed for customers wanting to run MongoDB which is charged by RAM and needs a lot of CPU.
Start the 400+ flavorid range for special flavors.
Start using the s_ prefix for special customer flavors.

[sap-seeds] Add s_c64_m64 special private flavor

---

prometheus-exporters/openstack-exporter/alerts/cinder.alerts

The info alerts are basically being ignored and some of these alerts are pretty critical for visibility.  Changing these alerts to warning so they get into the right slack channel with visibility.

Change some alerts to warnings

---

common/rabbitmq/CHANGELOG.md
common/rabbitmq/Chart.yaml
common/rabbitmq/templates/_helpers.tpl

Use short hostnames instead of the fqdn,
and rely on the DNS for Services discovery
from kubernetes to resolve it
For normal pods, that should be just a cosmetic change but for the KVM use-case, which runs on baremetal, it allows us to resolve and use external ips
with the same configuration

[common/rabbitmq] Shorter hostnames

---

openstack/cc3test/alerts/block-storage.alerts
openstack/cc3test/alerts/compute.alerts

as the hana_cc3test flavor used for the tests can run on both regular and hana hosts we do not need separate tests for them - this commit adjusts the alerts accordingly and makes sure they will still match to the old behaviour as well - this compatibility will be dropped once the unified tests are rolled out everywhere

[cc3test] combine hana and regular server tests into one

---

openstack/barbican/Chart.lock
openstack/barbican/Chart.yaml
openstack/barbican/values.yaml

included releases:
rabbitmq 0.5.0 which adds support for prometheus-rabbitmq plugin
rabbitmq 0.5.1 which uses short hostname instead of FQDN for rabbitmq

[barbican] update dependency of rabbitmq to 0.5.1

---

openstack/grafanasix/values.yaml

This is redundant with cc/secrets.

grafanasix: do not select an existingClaim by default

---

openstack/designate/Chart.lock
openstack/designate/Chart.yaml
openstack/designate/values.yaml

include releases:
rabbitmq 0.5.0 which adds support for prometheus-rabbitmq plugin
rabbitmq 0.5.1 which uses short hostname instead of FQDN for rabbitmq

[designate] update dependency of rabbitmq to 0.5.1

---

px/bird/templates/_deployment_header.tpl
px/bird/templates/_podmonitor.tpl
px/bird/templates/bird.yaml

Since we deploy the same release with 2 domains, so 2 times we
would deploy the pmon twice as well. Let's just make sure we deploy the
pmon on domain 1 and everything works fine.

[PX] Only deploy PodMonitor once and in px namespace 

---

px/bird/templates/bird.yaml
px/bird/templates/podmonitor.yaml

Carve the podmonitor again out of the bird.yaml file and deploy it for every domain found usning loops to find out which domains exists. Previous chart did not deploy the podmonitor at all, since it was in a conditional that requires pxmon to be present.

[PX] Deploy podmonitor with each domain, per domain

---

system/metis/values.yaml

- dedicated metis user for metis schema
- grafana user for use as a Datasource
- replication schema used by the sync pods
- limits privileges for read only user

[metis] adds more users, and schema

---

system/bind/templates/config.yaml

There is not neccessarily a bash in the image, and the script gets called via sh externally anyhow.
Additionally hostname -i is deprecated and to work it requires working name resolution but could return a different IP than the local one. 
Anyhow, because rndc uses localhost by default, the parameter can be omitted completely.

[dns][bind] health check

---

system/bind/templates/config.yaml

Will enable querying the server name and region using
`dig CH TXT id.server`

[dns][bind] adding serverid with region

---

system/unbound/templates/config.yaml

add server name and region to config, so we can query them using
`dig CH TXT id.server`

[dns][unbound] adding serverid with region

---

openstack/cinder/Chart.lock
openstack/cinder/Chart.yaml
openstack/cinder/values.yaml

include releases:
rabbitmq 0.5.0 which adds support for prometheus-rabbitmq plugin
rabbitmq 0.5.1 which uses short hostname instead of FQDN for rabbitmq

[cinder]update dependency of rabbitmq to 0.5.1

---

openstack/nova/Chart.lock
openstack/nova/Chart.yaml

There is a race between the startup of proxysql
and the poststarthook trying to access it.
The updated dependency will fix that.
Also update proxysql to the latest minor version
for various bugfixes

[nova] Update utils with proxysql startup fixes

---

global/prometheus-infra/Chart.yaml
global/prometheus-infra/alerts/prometheus.alerts

old thanos version which produced this error is not around anymore.

[prometheus-infra-global] alert not longer needed

---

openstack/swift-drive-autopilot/templates/daemonset.yaml
openstack/swift/templates/etc/_haproxy.cfg.tpl
openstack/swift/templates/haproxy-deployment.yaml
openstack/swift/values.yaml

- swift-drive-auto-pilot: disable `kernel.panic_on_oops` in all regions
- swift HAProxy:
- lower maxconn from 4000 to 2000
- increase default replicas per AZ from 2 to 4
- increase cpu and memory requests

[Swift] kernel.panic_on_oops=0 and more resources for HAProxy

---

common/memcached/Chart.yaml
common/memcached/values.yaml

MemcacheD Security patch and Version upgrade from 1.5.12 to 1.6.18
- Exporter is the latest
- No interim upgrade requires
- The upgrade involves cold boot (clearing the data)

[MemcacheD] - Security Patch and Version upgrade to 1.6.18

---

openstack/nova/templates/etc/_api_uwsgi.ini.tpl

To re-allow uWSGI testing in qa-de-2.

[nova] Fix nova-api-wsgi path for loci images

---

global/prometheus-kubernetes-global/Chart.yaml
global/prometheus-kubernetes-global/values.yaml

It replaces kube_pod_container_resource_requests_cpu_cores and kube_pod_container_resource_requests_memory_bytes in version 2 of kube-state-metrics.

Federate kube_pod_container_resource_requests

---

openstack/cc3test/alerts/datastore.alerts

Update DatastoreNotAccessibleFromHost alert. Alert does not fire anymore, if the whole datastore is inaccessible. There are dedicated alerts for this case.

Update DatastoreNotAccessibleFromHost Alert

---

openstack/arc/Chart.lock
openstack/arc/Chart.yaml
openstack/lyra/Chart.lock
openstack/lyra/Chart.yaml

This updates backup-tools from 0.7.0 to 0.8.1, with the following changes:
- All usage of python-swiftclient is replaced with native Go code, thereby reducing CPU consumption and memory usage spikes.
- Backups are streamed directly into Swift instead of going through the local filesystem first.
Furthermore, the Helm chart has been extended with a configurable memory limit that is raised in the big regions (see companion PR in cc/secrets). This should permanently fix the current backup pod instability in eu-de-1/2.

arc, lyra: bump pgbackup to 0.1.7

---

openstack/cinder/templates/api-deployment.yaml
openstack/cinder/templates/etc/_cinder.conf.tpl

We observed hanging agents like reported in https://bugs.launchpad.net/oslo.messaging/+bug/1961402 in manila and neutron.
The bug was introduced in wallaby, so we disable it by default.
But wsgi needs that setting, so we override in that case via environment according to https://docs.openstack.org/oslo.config/xena/reference/drivers.html#module-oslo_config.sources._environment
Similarly like already done in neutron 58520f04d86e6479e8fa02e265bb7619e91ed10f

[cinder] disable heartbeat_in_pthread for non wsgi

---

openstack/cronus/templates/cronus/deployment.yaml

Now that we are using cert manager to generate client certs, the "tls.crt" and "tls.key" are hardcoded. This change maps the cert and key to the backend name.
This also makes sense as it will avoid any collisions between the backend certs.

adding in a key/path mapping to the tls crt and key

---

openstack/octavia/alerts/octavia.alerts

I like to have the id of everything handy, as most of our tooling works well with uuids but takes a longer time with names. Therefore we now have the loadbalancer id together with the loadbalancer name in the alert text, same as we already do for our network alerts.

[octavia] Add loadbalancer id to "stuck in" alert

---

common/mariadb/Chart.yaml
common/mariadb/values.yaml

Avoid to spamming alerts channels by slow logs by backup execution 
Image version has been changed from "20220802151433" to new image "20230209133906"

[MariaDB] - Backup Slow log fix

---

openstack/manila/templates/etc/_manila.conf.tpl
openstack/manila/values.yaml

Since the Victoria release of OpenStack, oslo.messaging supports an RPC endpoint called "oslo_rpc_server_ping" [0]. This endpoint can be used to implement a generic RPC check to see if a server is still receiving messages/rpc calls via rabbitmq.
[0] https://github.com/sapcc/oslo.messaging/commit/82492442f3387a0e4f19623ccfda64f8b84d59c3

[manila] Enable oslo.messaging's ping endpoint

---

system/audit-logs/Chart.lock
system/audit-logs/Chart.yaml
system/audit-logs/vendor/fluent-audit-container/Chart.yaml
system/audit-logs/vendor/fluent-audit-container/templates/_fluent.conf.tpl

Log ingestions breaks if some contain a label app and others app.kubernetes.io/name 
Renaming app to app_ avoids this issue during log ingestion

[audit-logs] renames kube-api requestObject label app to app_

---

common/prometheus-server/CHANGELOG.md
common/prometheus-server/Chart.yaml
common/prometheus-server/templates/thanos/storeendpoint.yaml
common/prometheus-server/values.yaml

the storeendpoint must be created in the respective thanos namespace, otherwise the operator would complain about thanos not being available

storeendpoint namespace like thanos

---

openstack/nova/Chart.lock

This includes the revert of the premature switch to `topology.kubernetes.io/zone` in 3a66513 (which reverts 3987bc7), and a fix for template values validation for proxysql (https://github.com/sapcc/helm-charts/commit/fcab93396dc77fc42c8cce6dc3fd9febe6d7ca36).

[nova] Update utils chart dependency to 0.7.4

---

system/vmware-monitoring/templates/collector-configmap.yaml

Covered by native metric summary|cert_expiry_date

Remove custom metric summary|CPO vCSA Certificate Remaining Days

---

prometheus-exporters/snmp-exporter/px.alerts/snmp-pxdl.alerts

Some of these alerts are self healing after 10-15 minutes, so we do not need to page people for that. After 15 min the alert fires.

[PX] PXTransportDlWanLinkProbesHighLatency to 15m

---

system/infra-monitoring/vendor/px-exporter/px.alerts/px.alerts

PXTransportRouterBgpDown is now split into two alerts, namely in:
1) PXTransportAllRouterBgpDown which fires after 0 seconds when all connectivity to the transport router is lost on instance 1 and 2 on the respective services and domain.
2) PXTransportRedundancyLostRouterBgpDown fires after 15 minutes when redundancy to the transport router is lost, i.e., only one instance peering is up.

[PX] Refining alert PXTransportRouterBgpDown

---

px/lg/templates/deployment.yaml
px/lg/values.yaml

To address DOOP warnings the looking glas deployments now have cpu and
memory resource limits

[px/lg] Add kubernetes resource limits

---

system/hubcopter/templates/configmap-html.yaml
system/hubcopter/templates/configmap.yaml
system/hubcopter/templates/deployment-api.yaml
system/hubcopter/templates/ingress.yaml
system/hubcopter/templates/service.yaml
system/hubcopter/values.yaml

Instead of constructing IDs in one structure from values of another structure, both structures are nested together.
I also removed several `required` calls that were ineffective because a default value was given in the Chart's `values.yaml`.
I also updated said default value to match what the code expects. The new behavior now is to not deploy any instances at all if none are configured explicitly, which is safe (albeit useless).

hubcopter: simplify values structure

---

openstack/nova/values.yaml

Since the Victoria release of OpenStack, oslo.messaging supports an RPC endpoint called "oslo_rpc_server_ping" [0]. This endpoint can be used to implement a generic RPC check to see if a server is still receiving messages/rpc calls via rabbitmq.
We enable this endpoint for Nova, so we can do availability checks on its services - manually for now, but we might extend this to be called automatically and alert on it.
[0] https://github.com/sapcc/oslo.messaging/commit/82492442f3387a0e4f19623ccfda64f8b84d59c3

[nova] Enable oslo.messaging's ping endpoint

---

system/unbound/Chart.yaml
system/unbound/ci/test-values.yaml
system/unbound/templates/config.yaml

- enable prefetch to keep cache up-to-date
- enable serving expired for stale, expired data
- also make linter happy; switch to api v2 chart

[unbound] config update:

---

openstack/nova/templates/etc/_nova-scheduler.conf.tpl
openstack/nova/values.yaml

The scheduler decides according to the image properties on which hypervisor to put the vm.
That requires hw_architecture to be set, but for convenience we can set a default architecture in the schedulers config

[nova] Set image default architecture for scheduler

---

system/infra-monitoring/vendor/px-exporter/px.alerts/px.alerts

There was no grace time for this alerts as we deemed a situation in which the router server is up but all transport router peers are gone as very critical. What we did not think about if the container receives a SIGTERM, bird in turn properly closes all BGP sessions orderly but the exporter still exposes metrics. While we would not alert on no metrics, we alert on metrics indicating sessions down. From SIGTERM to container deleted it takes no longer than 90 secs, so increasing this threshold to 2min.

[PX] Increase grace time for PXTransportAllRouterBgpDown

---

common/thanos/Chart.yaml
common/thanos/templates/_thanos_helpers.tpl
common/thanos/templates/alerts/_thanos-ruler.alerts.tpl
common/thanos/templates/alerts/thanos-alerts.yaml
common/thanos/templates/ingress.yaml
common/thanos/templates/ruler/_alertmanager.yaml.tpl
common/thanos/templates/ruler/alertmanager-config.yaml
common/thanos/templates/ruler/alertmanager-sso-secret.yaml
common/thanos/templates/ruler/ruler.yaml
common/thanos/templates/ruler/service-account.yaml
common/thanos/templates/ruler/service.yaml
common/thanos/templates/servicemonitor.yaml
common/thanos/values.yaml

This PR enables the common/thanos chart to specify a Thanos Ruler. This is intended to sit alongside a Thanos Query deployment and evaluate alerting and aggregations rules across prometheus.

common/thanos: thanos ruler functionality added

---

openstack/nova/templates/bin/_db-online-migrate.tpl
openstack/nova/templates/db-online-migrate-job.yaml

While most of the online data migrations run in the API DB and break out to the different cells as necessary, there's at least one migration running in the local cell only: migrate_empty_ratio [0]
Therefore, we explicitly run the online_data_migrations command again with the "nova-cell2.conf" added, so we run in cell2.
[0] https://github.com/sapcc/nova/blob/a4469a15d302914a5a34f344fe3aa5efe638ce1a/nova/objects/compute_node.py#L524-L525

[nova] Run online_data_migrations in cell2

---

openstack/cc3test/alerts/cc3test-absent.alerts

wait a bit longer for now to really avoid false positives

[cc3test] avoid false alerts due to the statsd pod restarting

---

openstack/elektra/templates/seed.yaml

There is a new cloudshell cluster in QA region. For the dashboard of QA regions, I would like to use this cluster.

[elektra] use separate webcli endpoint for qa regions

---

openstack/nova/templates/db-migrate-job.yaml
openstack/nova/templates/db-online-migrate-job.yaml
openstack/nova/templates/etc-secret.yaml

This should just fix the jobs, the other specs will get updated accordingly.
- Instead of pasting the credentials into serveral files, rely on the default include path pattern.
- Instead of having the credentials for the dbs in a configmap, put them in a secret.
- Instead of mounting all files individually, create a projected volume in the spec which contains them.

[nova] Fixup PR #4766: DB access for Jobs with projected volumes

---

openstack/cc3test-seeds/alerts/cc3test-quota.alerts

this is to avoid potential false positives

[cc3test] make the 75% resource alerts less sensitive

---

openstack/nova/templates/bin-configmap.yaml

The file isn't use anymore, so we might as well remove it from the configmap

[nova] Remove common.sh

---

openstack/nova/templates/etc/_rootwrap.conf.tpl

The checked in rootwrap.conf is based on the one from kolla, but since we switched to loci images the paths are not correct.

[nova] Use rootwrap.conf from loci image

---

openstack/arc/Chart.lock
openstack/arc/Chart.yaml
openstack/lyra/Chart.lock
openstack/lyra/Chart.yaml
openstack/lyra/values.yaml

This upgrades https://github.com/sapcc/backup-tools from 0.8.0 to 0.9.1, including a cleanup of all code towards current best practices. Starting with 0.9.x, backup-tools releases are validated by E2E tests in Concourse.
*Update:* This now also bumps the pgmetrics chart to update prometheus-exporter to 0.11.1 and set `support_group` on all alerts.

arc/lyra: bump pgbackup chart from 0.1.7 to 0.1.10

---

global/concourse-main/Chart.lock
global/concourse-main/Chart.yaml

This upgrades https://github.com/sapcc/backup-tools from 0.8.0 to 0.9.1, including a cleanup of all code towards current best practices. Starting with 0.9.x, backup-tools releases are validated by E2E tests in Concourse.

concourse: bump pgbackup chart from 0.1.7 to 0.1.10

---

system/sentry/Chart.lock
system/sentry/Chart.yaml

This upgrades https://github.com/sapcc/backup-tools from 0.7.0 to 0.9.1, including a cleanup of all code towards current best practices and a replacement of python-swiftclient usage with native Go code. Overall, everything should be a bit cleaner and more modern. Starting with 0.9.x, backup-tools releases are validated by E2E tests in Concourse.

sentry: bump pgbackup chart from 0.1.4 to 0.1.10

---

openstack/nova/bin/iptables-restore.mock
openstack/nova/templates/_console_deployment.yaml.tpl
openstack/nova/templates/api-deployment.yaml
openstack/nova/templates/api-metadata-deployment.yaml
openstack/nova/templates/bigvm-deployment.yaml
openstack/nova/templates/conductor-deployment.yaml
openstack/nova/templates/etc-configmap.yaml
openstack/nova/templates/etc/_nova-api-metadata.conf.tpl
openstack/nova/templates/etc/_nova-api.conf.tpl
openstack/nova/templates/etc/_nova-bigvm.conf.tpl
openstack/nova/templates/etc/_nova-conductor.conf.tpl
openstack/nova/templates/etc/_nova-console.conf.tpl
openstack/nova/templates/etc/_nova-scheduler.conf.tpl
openstack/nova/templates/scheduler-deployment.yaml

Instead of injecting the config for the databases in each config
use the default config dir logic and put place the config
under /etc/nova/nova.conf.d/db.conf, where all *.conf files
will be loaded.
Since the database config contains the db credentials, place
the file in a secret.
Use a projected volume to bind it all together.
Remove
- `policy.yaml` from nova-scheduler
-  iptables-restore completely
as they are not used

[nova] Split out db with projected volumes plus minor cleanups

---

system/elastiflow/ci/test-values.yaml
system/elastiflow/templates/filebeat-deployment.yaml
system/elastiflow/templates/filebeat-service.yaml
system/elastiflow/values.yaml
system/elastiflow/vendor/logstash/templates/statefulset.yaml
system/elastiflow/vendor/logstash/values.yaml

Testing one service for both sflow and netflow events. With the named ports the traffic for sflow should be forwarded to logstash and the netflow events should be send to the logstash

[elastiflow] enables sflow

---

system/infra-monitoring/templates/_prometheus-infra-collector.yaml.tpl

The apic-exporter is scraped by a servicemonitor. I believe this is a leftover from the previous version of the exporter

[infra-prom] removes dedicated apic-exporter scrape job

---

openstack/utils/Chart.yaml
openstack/utils/templates/_env.tpl
openstack/utils/values.yaml

The snippet should take care of setting all the environment variables,
taking the defaults from utils, allowing an chart level override, but
also one on an application-level.
It requires a python user-customization file merge in sapcc/loci#15,
and additionally, the process cannot be run as root,
as a root process in a container is more restricted than a non-root user
one.
All settings from pyroscope can be set via the `PYRO_*` environment
variables.
Additionally, there is the `PYRO_APP_SUBSET` variable,
which is a regular expression, which needs to match the hostname,
for the agent to be come active.
The idea is, that you can thereby select a subset of the application
instances to be sampled for a potential A/B split.

Add env-vars snippet for pyroscope

---

openstack/swift/aggregations/openstack/consolidation.rules

To allow automatic node reinstallations or reboots through the maintenance controller it is helpfull that everyone can rely on a single metric which indicates, whether it is safe to proceed with the next node in the queue.

[Swift] swift_avoid_node_reboot metric

---

openstack/sap-seeds/Chart.lock
openstack/sap-seeds/templates/_flavors_hana_exclusive.tpl
openstack/sap-seeds/templates/_flavors_hana_no_exclusive.tpl
openstack/sap-seeds/templates/_helpers.tpl
openstack/sap-seeds/templates/flavor-seed.yaml
openstack/sap-seeds/values.yaml

We want to be able to allow users to target another hypervisor (libvirt) in the future, so for compatability reasons, the existing flavors need to target vsphere.
We chose flavors over image attributes as it is more explicit, and we only want allow boot-from-volume on KVM, while the existing flavors have root-disks.
As a side-effect, it "breaks" forcing those non-baremetal flavor to a baremetal host.

[sap-seeds] Extract common flags to snippets, set hypervisor to vmware

---

prometheus-exporters/openstack-exporter/alerts/cinder.alerts

for warning it will fire when <= 2 datastores are low on space critical it will fire when <= 1 datastores are low on space

[Cinder] Modify the CinderFreeSpace alerts

---

system/kubernikus-monitoring/Chart.yaml
system/kubernikus-monitoring/alerts/operator.alerts

We are seeing a lot of hammertime alerts for deleted e2e clusters due to stale `kubernikus_hammertime_status`. The `kubernikus_kluster_info` metrics does not suffer from stale metrics so by joinging with the metric we avoid this false positives

kubernikus-monitoring: filter stale metrics

---

openstack/cinder/templates/etc/_cinder.conf.tpl
openstack/cinder/values.yaml

Since the Victoria release of OpenStack, oslo.messaging supports an RPC endpoint called "oslo_rpc_server_ping" [0]. This endpoint can be used to implement a generic RPC check to see if a server is still receiving messages/rpc calls via rabbitmq.
[0] https://github.com/sapcc/oslo.messaging/commit/82492442f3387a0e4f19623ccfda64f8b84d59c3

[cinder] Enable oslo.messaging's ping endpoint

---

openstack/keystone/templates/deployment-api.yaml

Pulling keystone-statsd from the region where keystone runs might lead to circular dependency: keystone image cannot be obtained, because image service cannot run, because keystone is not available.
Pull keystone-statsd components from another region to avoid the dependency.

Pull keystone-statsd from dockerHubMirrorAlternateRegion

---

prometheus-exporters/network-generic-ssh-exporter/templates/_config.yaml.tpl
system/atlas/templates/configmap.yaml

Prometheus labels should be used to _differentiate the characteristics of the thing that is being measured_.
(https://prometheus.io/docs/practices/naming/#labels) In this case the label contained the actual value that was being measured. This should hence be 3 individual metrics, where their value carries the measured state. Also simplified the regex a bit.
ACI leafs currently carry the platform NXOS in our inventory which is technically incorrect. However this is what the SD will feed into prometheus, so I deleted the aci-leaf device type. `terminal length 0` will be executed as init command and will return an error, yet that will be ignored.

Fix ACI endpoint learning metrics

---

prometheus-rules/prometheus-vmware-rules/alerts/datastore.alerts

Change VMFS Datastore Capacity Alert tier from OS to VMware and reduce severity from Warning to Info

Change VMFS DS Capacity Alert tier and Severity

---

prometheus-exporters/openstack-exporter/alerts/cinder.alerts

This patch renames CinderShardMaxVolumeSizeInfo to CinderShardMaxVolumeSize as well creates a warning where < 2 datastores match and a critical alert where there are no datastores that can create a max size volume.

[Cinder] Created critical alert for CinderShardMaxVolumeSize

---

prometheus-rules/prometheus-vmware-rules/alerts/host.alerts

1. changing power state for HostNotResponding alerts to not "Powered Off". Not reponding hosts usually respond an unknown powerstate. However just filtering for "Unknown" will not cover "Powered On" hosts, in case the powerstate gets reported correctly.
2. Removing not responding hosts from HADetectedAPossibleHostFailure to prevent alert duplcation.

Updating HostNotResponding alerts

---

openstack/nannies/templates/manila-nanny-deployment.yaml

follow move of netapp metrics from infra-collector to prometheus-storage

[nannies] manila: switch prom host

---

openstack/neutron/Chart.lock
openstack/neutron/Chart.yaml
openstack/neutron/values.yaml

Now with memcached 1.6.18 and memcached-exporter 0.11.2

[neutron] Bump memcached chart dependency to 0.1.1

---

openstack/neutron/Chart.lock
openstack/neutron/Chart.yaml
openstack/neutron/values.yaml

included releases:
rabbitmq 0.5.0 which adds support for prometheus-rabbitmq plugin 
rabbitmq 0.5.1 which use short hostname instead of FQDN for rabbitmq

[neutron] update dependency of rabbitmq to 0.5.1

---

system/descheduler/Chart.yaml
system/descheduler/values.yaml
system/kube-monitoring-metal/Chart.yaml
system/kube-monitoring-metal/values.yaml
system/kube-system-global/Chart.yaml
system/kube-system-global/values.yaml
system/kube-system-metal/Chart.yaml
system/kube-system-metal/values.yaml
system/metrics-server/Chart.yaml
system/metrics-server/values.yaml
system/prometheus-operator/Chart.yaml
system/prometheus-operator/values.yaml

I want to start tearing down the `ccloud-k8sgcr-mirror`. I plan to merge this at the end of next week latest, until someone objects.

remove remaining references to k8s.gcr.io

---

openstack/ironic/values.yaml

hopefully fixes mysql-metrics errors like
```
Column 'retired' must be type text (string)
```

[ironic] remove NULL from openstack_ironic_nodes_list_gauge

---

openstack/utils/Chart.yaml
openstack/utils/templates/snippets/_kubernetes_entrypoint.tpl

Moving the logic to an initcontainer means we do not have to build in the executable in the main image and can share that image among services.
Also, a missing dependency won't get mixed up with "normal" program failures.

[openstack/utils] Snippet for kubernetes-entrypoint in initcontainer

---

openstack/manila/Chart.lock
openstack/manila/Chart.yaml
openstack/manila/templates/api-deployment.yaml
openstack/manila/templates/migration-job.yaml
openstack/manila/templates/scheduler-deployment.yaml

Moving the logic to an initcontainer means we do not have to build
in the executable in the main image and can share that image among
services.
Also, a missing dependency won't get mixed up with normal program
failures.

[manila] Move kubernetes-entrypoint to init containers

---

openstack/manila/templates/shares/_netapp-deployment.yaml.tpl
openstack/manila/templates/shares/_netapp-ensure-deployment.yaml.tpl

The kubernetes-entrypoint doesn't seem to like a tailing ',' as it then looks for a resource with an empty name

[manila] Fixup c83a39, no tailing ','

---

openstack/glance/Chart.lock
openstack/glance/Chart.yaml
openstack/glance/templates/deployment.yaml
openstack/glance/templates/migration-job.yaml

Moving the logic to an initcontainer means we do not have to build
in the executable in the main image and can share that image among
services.
Also, a missing dependency won't get mixed up with normal program
failures.

[glance] Move kubernetes-entrypoint to init containers

---

openstack/barbican/Chart.lock
openstack/barbican/Chart.yaml
openstack/barbican/templates/api-deployment.yaml
openstack/barbican/templates/migration-job.yaml

Moving the logic to an initcontainer means we do not have to build in the executable in the main image and can share that image among services.
Also, a missing dependency won't get mixed up with normal program failures.

[barbican] Move kubernetes-entrypoint to init containers

---

openstack/glance/templates/_helpers.tpl

The job needs to be immutable, so any change to it should be a different job(-name).

[glance] Change the job-name when the init-container changes

---

openstack/ironic/Chart.lock
openstack/ironic/Chart.yaml
openstack/ironic/templates/_conductor-deployment.yaml.tpl
openstack/ironic/templates/api-deployment.yaml
openstack/ironic/templates/db-migration-job.yaml
openstack/ironic/templates/inspector-conductor-deployment.yaml
openstack/ironic/templates/inspector-db-migration-job.yaml
openstack/ironic/templates/inspector-deployment.yaml

Moving the logic to an initcontainer means we do not have to build
in the executable in the main image and can share that image among
services.
Also, a missing dependency won't get mixed up with normal program
failures.

[ironic] Move kubernetes-entrypoint to init containers

---

openstack/manila/templates/api-deployment.yaml

42424 is the default uid and gid coming from loci
directly going for the workaround provided by
https://github.com/kubernetes/examples/issues/260

[manila] adding init to manila-api for nfs permissions

---

prometheus-exporters/openstack-exporter/alerts/cinder.alerts

This patch temporarily downgrades the  CinderShardMaxVolumeSize alerts to info.  We are going to test out stacking for 2 weeks in ap-cn-1 and see how it goes.  So for the duration we decided in the storage meeting to downgrade the max volume size alerts to info.

[Cinder] Downgrade CinderShardMaxVolumeSize alerts

---

openstack/ironic/templates/db-migration-job.yaml

Only lower-case characters are allowed

[ironic] Make random job-name lowercase

---

system/vmware-monitoring/templates/collector-configmap.yaml

Capacity metrics needed for "Percent Cluster Resource" admission control policy.

Adding capacity metrics

---

prometheus-rules/prometheus-vmware-rules/alerts/datastore.alerts

Ephemeral datastore is not a part of SDRS Cluster

EPH DS not part of SDRS Cluster

---

openstack/nova/values.yaml

The .name value is not evaluated by the rabbitmq chart, so remove it, or replace it with nameOverride in cell2, where we need a sensible value

[openstack/nova] Change misleading rabbitmq-defaults

---

openstack/neutron/values.yaml

Our neutron deployments often time out. Let's assume all neutron-server pods are not completely busy at the time of deployment we can try to replace multiple pods at the same time.
Refresher:
`maxUnavailable` is an optional field that specifies the maximum number of Pods that can be unavailable during the update process. `maxSurge` is an optional field that specifies the maximum number of Pods that can be created over the desired number of Pods.
With maxUnavailble = 10% we cut out 10% of our capacity and hence roll over quicker. On top of that we can borrow some control plane resources during the deployment with maxSurge set to 25%. In conjunction, that allows us to roll 35% of our servers at the same time.

[neutron] Quicker deployments through adjusting maxSurge/Unavailable

---

openstack/sap-seeds/templates/flavor-seed.yaml

The current Openstack-Seeder cannot deal with zero-sized disks because it treats 0 as "empty" and prunes the key from the input flavor spec.
As a band-aid we set disk-size to 1 GiB for the KVM testing flavor, but this needs to be reverted before the rollout of KVM since KVM flavors shouldn't have ephemeral root disks at all.

[sap-seeds] Set disk for "forced" flavor to 1 GiB

---

system/infra-monitoring/Chart.lock
system/infra-monitoring/Chart.yaml
system/infra-monitoring/ci/test-values.yaml
system/infra-monitoring/templates/_prometheus-infra-collector.yaml.tpl

* metrics were previously dropped to ensure a stable environment (high cardinality, low resources available)
* technically reverts #a88e363 #062a6e5, additionally to #3cd790f

prombump, bringing back hw metrics

---

prometheus-exporters/ipmi-exporter/Chart.yaml
prometheus-exporters/ipmi-exporter/alerts/metal-esxi.alerts
prometheus-exporters/ipmi-exporter/templates/alerts.yaml

The newly introduced Thanos Rule component is intended to allow the evaluation of Prometheus Rules across multiple Prometheis. In this case, metrics from the infra-collector and the numerous vmware Prometheis are needed to evaluate the rules. Therefore, they are labeled on the regional Thanos Rule.

ipmi-exporter: move metal-esxi alerts to thanos-ruler regional

---

system/elastiflow/alerts/elastiflow.alerts
system/elk/alerts/elk.alerts
system/opensearch-logs/alerts/opensearch.alerts

the alert is firing often in the last weeks due to node
maintenance in the region. Yellow status of the cluster
itself is not so problematic, as the cluster is able to
resync. If one or more nodes is also facing volume attach
issues then this can become a problem.
This additional condition should improve this alert, as
the OnDuty only needs to check once the cluster is actually
missing elastic cluster nodes.

system/elastic: add sts metric to cluster yellow alert

---

common/thanos/Chart.yaml
common/thanos/templates/ruler/ruler.yaml

External labels are needed for the Thanos Rule to get alerts routed properly.

common/thanos: external rule labels added

---

openstack/nova/values.yaml

Instead of reporting the most free space on any managed datastore, which leads to a lot of changes in Placement, we limit the max_unit value to a little bit above the biggest DISK_GB allocation we currently have.

[nova] Limit max_unit for DISK_GB resource on VMware

---

openstack/utils/Chart.yaml
openstack/utils/templates/_affinity.tpl
openstack/utils/templates/_topology.tpl
openstack/utils/values.yaml

topologySpreadConstraints lets us define, how the pods should
be spread across different topologies, like nodes, racks, or in our case
(availability-)zones.
The topology key is by default the deprecated
"failure-domain.beta.kubernetes.io/zone", but can be switched via the
global value `.global.topology_key`.
By spreading the pods out, we reduce the risk of a downtime
due to all pods being affected by a problem in one zone.
The scheduler should handle it with best effort.
This also a preparation for [Topology Aware Routing](https://kubernetes.io/docs/concepts/services-networking/topology-aware-routing/),
when configured, would allow us prioritize communication within a zone.
But for that to make even sense, the (usually api) nodes
need to be spread out a bit.

[openstack/utils] Templates to spread pods across AZs

---

openstack/maia/templates/etc/_maia_scrape_config.yaml.tpl
prometheus-exporters/netapp-exporter/charts/netapp-cap-exporter/aggregations/netapp-cap.rules

The metrics should report sizes that are consistent with `df` on the client side. For volumes/shares that have logical space reporting/enforcement enabled, the metrics openstack_manila_share_used_bytes should report the logical used bytes.

[maia] aggregate Manila share used bytes with logical used bytes

---

prometheus-rules/prometheus-vmware-rules/alerts/datastore.alerts

As discussed, this will use only the string with the first dash in it for lable matching to make it work for e.g. `node042-ap133-nvme-7`

[compute-alerting] Fix DatastoreDisconnected* alerts

---

prometheus-exporters/network-generic-ssh-exporter/templates/_config.yaml.tpl

adding parser for ssh exporter to monitor tx/rx errors captured via command 'show system internal epm counters zmq' on aci leaf switches

parser for monitoring zmq errors on aci leaf switches

---

openstack/cinder/Chart.lock
openstack/cinder/Chart.yaml

This patch updates cinder's mariadb chart to help fix some false positive alerts for slow db queries.

[cinder] Update mariadb chart to 0.7.8

---

openstack/neutron/templates/vct-nsxv3-agent-configmap.yaml
openstack/neutron/templates/vct-nsxv3-agent-deployment.yaml

The NSX-t/v driver is the only option we currently have, so drop the check. This means less dependencies between the vcenter-operator and the chart.

[neutron] Assume NSX-T Always Enabled

---

openstack/glance/Chart.lock
openstack/glance/Chart.yaml
openstack/glance/ci/test-values.yaml
openstack/glance/templates/deployment.yaml
openstack/glance/templates/service.yaml

Use topologySpreadConstraints to spread the api pods over the zones in a best effort manner to improve the situation in the situation of a zone is down (kubernetes may not rebalance, or cannot due to inbalance)
Use topology aware routing service-annotation to make use of the distributed placement and prefer communicating to nodes in the same AZ
In regions with a single AZ, the annotations are not set.

[glance] Topology aware scheduling and spreading

---

openstack/nova/values.yaml

When fetching hypervisors from Nova's API, newer API versions (2.88+) return an "uptime" field in the response. To fill this field, nova-api makes an RPC call to each hypervisor. Since some of the drivers (namely Ironic and VMware) do not implement the `get_host_uptime()` call and thus end up raising a `NotImplementedError`. Making the RPC call for every hypervisor is slow and since our hypervisors don't implement it also clog the logs. Therefore, we disable the RPC call and always return `None` for the field.

[nova] Disable uptime RPC call in hypervisor details

---

openstack/neutron/templates/asr_config_agents/_deployment-asr1k.yaml.tpl
openstack/neutron/templates/etc/_asr1k.conf.tpl

We introduced to disable scheduling on a particular agent in the asr1k code. This feature can be used either if an agent is supposed to be decomissioned or if we do not want to increase the load on an agent.
However that is an important difference for the capacity calculation, hence we employ different annotations on the pod, depending of the purpose. If an agent is to be torn down and never used again, `decomissioning` must be used. It indicates that the agent should not ne included in the capacity calculation.
If we just intend to prevent any additional load on the agent, `scheduling_disabled` must be used. The agent shall than still be considered as capacity available.

[neutron] Options to indicate and configure decomssioning or no schedule

---

openstack/neutron/templates/asr_config_agents/_deployment-asr1k.yaml.tpl

These need to be labels instead of annotations because only those get exported to Prometheus (`kube_pod_labels`).

neutron: fix labels on asr1k pods

---

system/vmware-monitoring/templates/collector-configmap.yaml

- Adds keys to the vrops-exporter-collector-config to generate the Prometheus metrics
Custom tags for the VMware objects that allow mapping to e.g.: OpenStack --> ~~added as a label on the resource metrics to be able to filter by~~ or exposed as an own, separate metric

Expose custom Cinder tag/state information

---

openstack/maia/Chart.yaml
openstack/maia/values.yaml

The multiple scrape alerts from maia prometheus are evaluated by prometheus-openstack. This led to duplicate alert notifications several times in the past. Since we know what we are doing, these alerts can be disabled for maia.

maia: disable multiple scrape alerts

---

openstack/cc3test/alerts/compute.alerts
prometheus-rules/prometheus-vmware-rules/alerts/host.alerts
prometheus-rules/prometheus-vmware-rules/alerts/vcenter.alerts

update playbook reference for vcenterapidown, hostwithrunningvmsnotresponding, hostnotresponding, vasaproviderdown

update links for compute vmware ops playbooks

---

common/prometheus-alertmanager-base/notification-templates/email.tmpl
global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl

This commit:
- disables grouping of alerts for cc_email_receiver route
- adds a basic html email template for KubernikusKlusterLowOnObjectStoreQuota alerts

[cc_email_receiver] no alert grouping + email template

---

global/prometheus-kubernetes-global/Chart.yaml
global/prometheus-kubernetes-global/alerts/federation.alerts
global/prometheus-kubernikus-global/Chart.yaml
global/prometheus-kubernikus-global/alerts/prometheus.alerts

Updated the support group and service to forward alerts. None of the alerts are critical, so I reduced them to warning.

prometheus-kubernetes|kubernikus-global: alert routing updated

---

openstack/hermes/templates/etc/_audit.json.tpl

Increasing ES replicas to 1 in the index template. We cannot merge this until the Single Node is removed, when we are ready to remove it.

[hermes] increase es replicas to 1 

---

system/audit-logs/Chart.lock
system/audit-logs/Chart.yaml
system/audit-logs/vendor/logstash-audit-external/Chart.yaml
system/audit-logs/vendor/logstash-audit-external/templates/_logstash.conf.tpl

To enable "job_events" log aggregator on AWX we need to control the number of fields generated to avoid overloading the receiving ELK stack. Fields observed to contain host or user specific data therefore need to be excluded.

[logstash-audit] Remove host specific fields from event_data

---

prometheus-exporters/snmp-exporter/alerts/f5.alerts

Adding playbook link to the `NetworkF5SyncFailed` alert.
Fixing alert formatting.

[alert][snmp-exporter] add playbook link to f5 config sync alert

---

common/prometheus-server/CHANGELOG.md
common/prometheus-server/Chart.yaml
common/prometheus-server/templates/_helpers.tpl
common/prometheus-server/values.yaml

When we extend prometheus kubernetes with thanos, thanos swift containers are rendered with the same name. To avoid this, we append the appropriate cluster type to the name.

common/prometheus-server: adds option to name swift containers uniquely

---

openstack/octavia/templates/etc/_octavia.conf.tpl

This PR persists values that we set in one of the Germany gold regions when DB connections were piling up (possibly due to many concurrent status updates).

[Octavia][mariadb] Increase DB connection capacity

---

openstack/cinder/Chart.lock
openstack/cinder/Chart.yaml
openstack/cinder/templates/api-deployment.yaml
openstack/cinder/templates/api-service.yaml
openstack/cinder/templates/backup_deployment.yaml
openstack/cinder/templates/vcenter_datacenter_cinder_deployment.yaml

Use topologySpreadConstraints to spread the api pods over the zones in a best effort manner to improve the situation in the situation of a zone is down (kubernetes may not rebalance, or cannot due to inbalance)
Use topology aware routing service-annotation to make use of the distributed placement and prefer communicating to nodes in the same AZ
In regions with a single AZ, the annotations are not set.
Option to change the AZ affinity with global.topology_key to something non-deprecated (i.e. topology.kubernetes.io/zone)
Add AZ affinity for cinder-backup deployment

[cinder] Topology aware scheduling and spreading + AZ update

---

openstack/neutron/templates/etc/_ml2-conf.ini.tpl

We use linuxbridge only on the network-agents to bind the dchp/metadata/dns ports. Those come with their own linuxbridge config in openstack/neutron/templates/configmap-etc-apod.yaml decoupled from the neutron-server or ml2-agent config config. We do not use ovs for ml2 bindings at all.

[neutron] Remove unused sections

---

openstack/keystone/values.yaml

provide a simple way to get project info in prom.
E.g. I have a project_id and I want to get the project name and domain name.
Before we abused other metrics like 'limes_project_quota' with a higher performance impact since it has more than one datapoint per project.

[keystone] add projects metric

---

ci/lint-chart.sh

While in general it is a good practice to avoid running
processes as root unless necessary, the main
gain of doing so here is that it won't place
files as the root user in the local chart
directory.
The script can be run by any user,
but then the user ends up with files
owned by root in their own directory.
Running it with the callers user
gives us downloaded charts owned
by the same user

[ci-lint-chart] Run linter as non-root user

---

openstack/octavia/alerts/octavia.alerts

Due to the `max()` function we aggregate all metrics and only show if an
agent's heartbeat is older than 120 secs, not which one. I guess this is
not intended as even the alert description uses the `octavia_host`
label.

[octavia] Fix alert to include agent name

---

system/kube-monitoring-scaleout/Chart.lock
system/kube-monitoring-scaleout/Chart.yaml

In order to include it in the unified Thanos setup, prometheus-server will be managed and operated by observability team in the future. For this purpose, it will be removed from kube-monitoring and transferred to its own Helm Chart.

kube-monitoring-scaleout: removes prometheus-server

---

openstack/octavia/values.yaml

This PR is a dependency for https://github.com/sapcc/octavia-f5-provider-driver/pull/170

[Octavia] Add default HTTP2 profile

---

openstack/nova/Chart.lock
openstack/nova/Chart.yaml
openstack/nova/templates/_console_deployment.yaml.tpl
openstack/nova/templates/_helpers.tpl
openstack/nova/templates/api-deployment.yaml
openstack/nova/templates/api-metadata-deployment.yaml
openstack/nova/templates/bigvm-deployment.yaml
openstack/nova/templates/cell2-conductor-deployment.yaml
openstack/nova/templates/conductor-deployment.yaml
openstack/nova/templates/db-migrate-job.yaml
openstack/nova/templates/db-online-migrate-job.yaml
openstack/nova/templates/hypervisors/_ironic-deployment.yaml.tpl
openstack/nova/templates/hypervisors/_kvm-deployment.yaml.tpl
openstack/nova/templates/hypervisors/hypervisors-vmware-deployment-vct.yaml
openstack/nova/templates/scheduler-deployment.yaml

Moving the logic to an initcontainer means we do not have to build
in the executable in the main image and can share that image among
services.
Also, a missing dependency won't get mixed up with normal program
failures.

[nova] Move kubernetes-entrypoint to init containers + cleanup

---

openstack/nova/templates/hypervisors/hypervisors-vmware-configmap-vct.yaml
openstack/nova/values.yaml

Users often forget to confirm a resize after the vm has been successfully resized.
Automatically confirming brings the VMs back to a standard state and clean up the copy of the root disk.
The time-frame was chosen to be a weekend plus one day to be hopefully as short as possible without messing up anyany manual process going on, which might get delayed over a weekend.

[nova] Automatically confirm resize after three days

---

openstack/nova/Chart.lock
openstack/nova/Chart.yaml
openstack/nova/ci/test-values.yaml
openstack/nova/templates/_console-service.yaml.tpl
openstack/nova/templates/_console_deployment.yaml.tpl
openstack/nova/templates/api-deployment.yaml
openstack/nova/templates/api-metadata-deployment.yaml
openstack/nova/templates/api-metadata-service.yaml
openstack/nova/templates/api-service.yaml
openstack/nova/templates/cell2-conductor-deployment.yaml
openstack/nova/templates/conductor-deployment.yaml
openstack/nova/templates/console-shellinabox-deployment.yaml
openstack/nova/templates/hypervisors/hypervisors-vmware-deployment-vct.yaml
openstack/nova/templates/scheduler-deployment.yaml
openstack/nova/templates/vspc-deployment.yaml
openstack/nova/templates/vspc-service.yaml

Use topologySpreadConstraints to spread the api pods over the zones in a best effort manner to improve the situation in the situation of a zone is down (kubernetes may not rebalance, or cannot due to inbalance)
Use topology aware routing service-annotation to make use of the distributed placement and prefer communicating to nodes in the same AZ
In regions with a single AZ, the annotations are not set.

[nova] Topology aware scheduling and spreading + AZ update

---

openstack/nova/templates/etc/_nova-scheduler.conf.tpl
openstack/nova/values.yaml

We want VMs to not move between shards on resize if possible, because this takes a long time for VMs having volumes attached because of the amount of data needing migration. We already prefer the same host on resize, but if that's not possible e.g. because of resizing to HANA or away from a small VM, the same shard should be used.
To accommodate that, we set the weight for the
`PreferSameShardOnResizeWeigher` to 200. This still prefers the same host if possible, which is advantageous because of less ephemeral disk copying/duplication, but prefer the same shard over the right RAM class. E.g., the right RAM class with more space in another shard would now, with weight 100 on the `HvRamClassWeigher` have a weight of 1xx, while the weight of the wrong RAM class in the same shard would now be …

[nova] Support and configure weights for PreferSameShardOnResizeWeigher

---

system/bind/templates/config.yaml
system/bind/values.yaml

We hit the limit of parallel SOA queries to mdns -- the default in bind is 20.
These settings allow more queries in parallel, allowing for faster zone syncs.
Details on the values can be found in https://kb.isc.org/docs/aa-01313

[bind] allow more SOA queries, but limit notifies

---

system/bind/Chart.yaml
system/bind/templates/deployment.yaml
system/bind/templates/pvclaim.yaml

reverting changes from commit e804f5678a67e39f7bcf64d83ef7b224d06da730 "use non-deprecated topology labels" as it currently prevents deployment.

[bind] reverting topology labels

---

common/mariadb/Chart.yaml
common/mariadb/values.yaml

new base image created for backup and readiness pod due to security issue. Both images are now clean.

[mariadb] updates backupv2 base image

---

common/memcached/Chart.yaml
common/memcached/values.yaml

The updated versions are clean as per Trivy

[memcached] bump imageTag versions of library/memcached and prom/memcached-exporter

---

common/postgresql/templates/deployment.yaml
common/postgresql/values.yaml
openstack/keppel/values.yaml

We observed problems with this limit on prod:
```
ERROR: during "GET /keppel/v1/accounts/<redacted>/repositories": pq: could not resize shared memory segment "/PostgreSQL.710526079" to 4194304 bytes: No space left on device
```
I tested the change in qa-de-1/keppel:
```shellSession
$ k exec keppel-postgresql-745557b9d7-w6wrj -- df -h /dev/shm
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           256M   20K  256M   1% /dev/shm
```

common/postgres: add sharedMemoryLimit parameter, use in Keppel

---

openstack/sap-seeds/values.yaml

Since the purpose of the "forced" flavor is to be able to force a deployment to any Ironic node, it must not have any resource requests. Since Nova's Xena update, Ironic hypervisors report only their CUSTOM_* resource and no disk, memory or vcpus. Therefore, the "forced" flavor would not work anymore.

[sap-seeds] "forced" flavor requires no resources

---

openstack/ironic/templates/redfish-certrobot-cronjob.yaml
openstack/ironic/templates/redfish-certrobot-secret.yaml
openstack/ironic/values.yaml

The cronjob runs a script, which checks
the certificates and replaces them, if
- the issuer is not matching an expected one
- the common name or the SAN is not matching/containing the hostname
- the expiry date is within a certain grace period

Ironic: Add Cronjob to manage BMC certs

---

openstack/octavia/Chart.lock
openstack/octavia/Chart.yaml

All notification messages are send to the hermes rabbitmq, and the consumer has been removed from the notification rabbitmq from octavia.

[octavia] Drop unused notification rabbitmq

---

openstack/barbican/Chart.lock
openstack/barbican/Chart.yaml

adding vendor's feature enhancements and bug fixes: rabbitmq-3.11.15-management
[ChangeLog](https://www.rabbitmq.com/changelog.html)

[barbican] update dependency on rabbitmq to version 0.5.2

---

openstack/octavia/Chart.lock
openstack/octavia/Chart.yaml

mariadb 0.7.5 -> 0.7.7
- a8725d6f5cbcf047c8101f7c87ac2e51a8e21435 backup slow log fix
- 956519b7aa371cafb8584ab6a38aa6e6fef36c75 fixes slow_query log setting in backup tool (#4787)
memcached 0.0.11 -> 0.1.0
- ff9ae0838ea666688a5ee0c2bdc818dfdd33b9f1 Move yielded connections alert to info
- f9ec2655a2e2fa6fa8b745112d21416d93cd305d Security Patch and Version upgrade to 1.6.18
rabbitmq 0.4.4 -> 0.5.1
- 9df22ade734c5917caf5eec18c1fbc7ee94a6320 add support for rabbitmq-prometheus
- b37ff0be1c1c81933b3f44ca3478b641c25b0e51 Shorter hostnames
utils 0.7.0 -> 0.8.0 (Edit: After rebasing utils is now on 0.10.1)
- 3987bc736873001d1f8a36558d55a195a9873c4f fix deprecated match key in node affinity
- 7a948411d5327e842a347ada112024e6e2dab0c3 Retry failing proxysql post-start config
- …

[Octavia] Bump subcharts, update chart version

---

common/mariadb-galera/CHANGELOG.md
common/mariadb-galera/README.md
common/mariadb-galera/docker/kopia/Dockerfile
common/mariadb-galera/helm/Chart.yaml
common/mariadb-galera/helm/README.md.gotmpl
common/mariadb-galera/helm/scripts/backup/common-functions-extended.sh
common/mariadb-galera/helm/scripts/backup/kopia/entrypoint-backup.sh
common/mariadb-galera/helm/scripts/backup/kopia/entrypoint-restore.sh
common/mariadb-galera/helm/scripts/backup/restic/entrypoint-backup.sh
common/mariadb-galera/helm/scripts/backup/restic/entrypoint-restore.sh
common/mariadb-galera/helm/scripts/mariadb-galera/entrypoint-galera.sh
common/mariadb-galera/helm/templates/configmap-mariadb-my.cnf.yaml
common/mariadb-galera/helm/templates/job-kopia-restore.yaml
common/mariadb-galera/helm/templates/job-restic-restore.yaml
common/mariadb-galera/helm/templates/statefulset-mariadb.yaml
common/mariadb-galera/helm/values.yaml

- documentation added
- optional binary log file purging after full backup
- to free up disk space on the log persistent volume
- keep the binlog backups small and fast
- binlog filename and position added to snapshot tags
- binlog file size limited to 100MB
- to limit the required disk space on the backup job container
- my.cnf configmap name fixed
- var/tmp/binlog folder added to Kopia image

Point in time recovery option added

---

openstack/nova/Chart.lock
openstack/nova/Chart.yaml
openstack/nova/values.yaml

included releases:
rabbitmq 0.5.0 which adds support for prometheus-rabbitmq plugin
rabbitmq 0.5.1 which use short hostname instead of FQDN for rabbitmq

[nova] update dependency of rabbitmq to 0.5.1

---

openstack/octavia/values.yaml

This reverts commit cd70a01627f20d20e6a2c127cb1bba3aa826ada4.
This PR disables HTTP 2 profile by default. Because of this check https://github.com/sapcc/octavia-f5-provider-driver/blob/stable/yoga-m3/octavia_f5/restclient/as3objects/service.py#L353 it disables HTTP 2 at all and we can enable it only in one region.

Revert "[Octavia] Add default HTTP2 profile (#3861)"

---

openstack/cerebro/Chart.lock
openstack/cerebro/Chart.yaml
openstack/cerebro/values.yaml

Using older owner-info versions generates a Gatekeeper violation because of the missing support group reference. Since this release contains only seeds, we should be fine falling back to @viennaa's support group association.

openstack/cerebro: update owner-info to v0.2.0

---

openstack/keystone/Chart.yaml
openstack/keystone/values.yaml

Keystone will be used to authenticate using js fetch()-like methods.
The default settings are fine and nothing needs to be configured per-region

Enable cors for keystone by default

---

px/bird/templates/_deployment_header.tpl
px/bird/templates/bird.yaml
px/bird/values.yaml

Some physical hosts are miscabled and we must not schedule PX pods on
these hosts, as PX VLANs are unavailable there.
We must prevent the scheduler from selecting these nodes.

[PX] Add option to prevent pods from being scheduled on certain nodes

---

openstack/hermes/templates/etc/_logstash.conf.tpl

It used to stand for version 6. We are on version 7 now, and it's an unneccesary relic.

remove old -6 from index names

---

openstack/keppel/templates/deployment-janitor.yaml

Having a lot of new manifests might send the janitor into CrashLoopBackoff otherwise

openstack/keppel: match janitor cpu limits/requests, increase memory

---

openstack/archer/templates/seed.yaml

Limes uses OS_INTERFACE=internal, and changing this here is way easier than adding an extrawurst in Limes.

archer: add "internal" endpoint to service catalog

---

openstack/neutron/templates/etc/_ml2-conf-aci.ini.tpl

The l3 out under which we have to configure the nullroute has a
different naming than the l3 outs we usually use, hence we have to pass
its name to the driver.

Add config option to name the nullroute l3 out to aci config

---

common/mariadb/Chart.yaml
common/mariadb/templates/alerts/_health.alerts.tpl

The critical alert should not fire if any mariadb is not ready, it should fire if no mariadb pods are ready.
Which is is difference, because there may be a NotReady pod still lingering around next to a working Ready pod.
We observed this on rabbitq with a pod stuck in Terminating due a node not being safely drained.
see similar commit
fc6402dfca1d98fdab0872d4269ee51f36f29f10

[mariadb] improve MariaDBNotReady alert

---

openstack/cinder/templates/etc/_resource_filters.json.tpl

This patch updates the Cinder resource filters to allow users to do an inexact search on volume and backup for the description.

Cinder: Allow inexact volume/backup search by desc

---

openstack/content-repo/alerts/content-repo.alerts
openstack/content-repo/templates/check-deployment.yaml
openstack/content-repo/templates/mirror-deployment.yaml
openstack/content-repo/templates/statsd-deployment.yaml
openstack/content-repo/values.yaml

Set ownership and alert channel from `swift` to `repo` to reflect future working model.
//cc @majewsky im unsure whether the Slack channel need to be created first?

[content-repo] move ownership from swift to repo

---

openstack/neutron/Chart.lock
openstack/neutron/Chart.yaml
openstack/neutron/templates/configmap-etc.yaml
openstack/neutron/templates/deployment-server.yaml
openstack/neutron/templates/etc/_api-paste.ini.tpl
openstack/neutron/templates/etc/_ratelimit.yaml.tpl
openstack/neutron/values.yaml

Based on openstack-watcher and openstack-rate-limit middleware, neutron api should be rate limited. In a first step the technial possiblities should be enabled. This requires the installation of the middleware dependencies via loci pipeline (https://github.com/sapcc/neutron/pull/48)
Per default neutron api rate limiting is disabled. Furthermore the service project is whitelisted (no rate limits apply) and for all other projects only a dummy target uri (named placeholer) is defined. As results no rate limits are applied after all.

Introduce possibility to rollout neutron api rate limiting

---

openstack/keystone/templates/bin/_keystone_tempest.sh.tpl
openstack/keystone/templates/configmap-etc.yaml
openstack/keystone/values.yaml

This reverts commit https://github.com/sapcc/helm-charts/commit/d5cd90e52eff03a12a0975a1e3009819a34ec28a. It also removes mentions of train and train-specific bits, because, turns out, they are really train-specific and not required today.

keystone: remove more references to train

---

system/kube-system-global/templates/ingress-external-public-service-monitor.yaml
system/kube-system-metal/templates/ingress-external-public-service-monitor.yaml

…lerts
critical alert needs alert routing

[kube-system] add support group to IngressExternalPublicServiceDown alerts

---

openstack/octavia/templates/etc/_esd.json.tpl

3505ef545 added the `cc_esd_udp_stateless` ESD that can be set on listeners for activating stateless UDP load balancing. However, that ESD name didn't adhere to the new naming convention for special tags that was established not too long ago with the addition of the `ccloud_special_l4_deactivate_snat` tag. That tag is not implemented via an ESD, but instead directly in code (see [1] and [2]), which is why I failed to take it into account when adding the `cc_esd_udp_stateless` ESD. Since LoBs are already using the `cc_esd_udp_stateless` ESD, I don't want to just rename it, but instead introduce a new alternative one and remove the other one from the docs.
[1] https://github.com/sapcc/octavia-f5-provider-driver/blob/stable/yoga-m3/octavia_f5/common/constants.py#L61
[2] …

[Octavia] Add stateless UDP ESD with correct naming convention

---

system/prometheus-kubernetes/Chart.lock
system/prometheus-kubernetes/Chart.yaml
system/prometheus-kubernetes/values.yaml
system/thanos-seeds/Chart.yaml
system/thanos-seeds/templates/seed.yaml
system/thanos-seeds/values.yaml

This PR enables Thanos for Kubernetes Prometheis. 
- added thanos dependency
- adjusted thanos-seed naming to distinguish seed names from different clusters

prometheus-kubernetes: thanos enabled

---

common/mariadb-galera/CHANGELOG.md
common/mariadb-galera/README.md
common/mariadb-galera/docker/kopia/Dockerfile
common/mariadb-galera/helm/Chart.yaml
common/mariadb-galera/helm/README.md.gotmpl
common/mariadb-galera/helm/scripts/backup/common-functions-extended.sh
common/mariadb-galera/helm/scripts/backup/kopia/entrypoint-backup.sh
common/mariadb-galera/helm/scripts/backup/kopia/entrypoint-restore.sh
common/mariadb-galera/helm/scripts/backup/restic/entrypoint-backup.sh
common/mariadb-galera/helm/scripts/backup/restic/entrypoint-restore.sh
common/mariadb-galera/helm/scripts/mariadb-galera/entrypoint-galera.sh
common/mariadb-galera/helm/templates/configmap-mariadb-my.cnf.yaml
common/mariadb-galera/helm/templates/job-kopia-restore.yaml
common/mariadb-galera/helm/templates/job-restic-restore.yaml
common/mariadb-galera/helm/templates/statefulset-mariadb.yaml
common/mariadb-galera/helm/values.yaml

- documentation added
- optional binary log file purging after full backup
- to free up disk space on the log persistent volume
- keep the binlog backups small and fast
- binlog filename and position added to snapshot tags
- binlog file size limited to 100MB
- to limit the required disk space on the backup job container
- my.cnf configmap name fixed
- var/tmp/binlog folder added to Kopia image

[mariadb-galera] Point in time recovery option added

---

system/thanos-metal/Chart.yaml
system/thanos-metal/values.yaml

all but metal and scaleout are queried directly since it would be a 1:1 relationship with a query in between.

add new thanos endpoints for regional query

---

px/arp-discovery/Chart.yaml
px/arp-discovery/templates/deamonset.yaml
px/arp-discovery/templates/nad.yaml
px/arp-discovery/templates/podmonitor.yaml
px/arp-discovery/values.yaml

We now have had multiple occasions when a pod was rescheduled to a host
that had either a host misconfiguration or the connected switch was
misconfigured. This resulted in the VLAN not being available and hence
the route servers being unreachable. We want to use this deployment as a
site survey to find out were this vlan is misconfigured. As IPs are a
limited resource in the peering nets, we rely on ARP/l2 only.

[PX] Add chart to temporary check on all nodes if PX vlans are present

---

common/redis/values.yaml

The RedisDB for services using openstack-rate-limiting is heavily throttled in all regions: Average ratio of throttled CPU seconds/used CPU seconds is above > 80%. Total used cpu (if there is no limit) is above 200% regions in the stages qa, bronze and silver. For eu-de-1 this value is higher than 400%.

Redis increase CPU limit and request

---

common/thanos/Chart.yaml
common/thanos/templates/dummy-grpc-ingress.yaml
common/thanos/templates/ingressroute-grpc.yaml
common/thanos/values.yaml

traefik part of the chart was not able to handle the newer helpers made for the multiple deployment. adopted it and made serviceName configurable. Since we are only using it in one cluster, it should default to our used name.

traefik logic adapted to multiple scheme

---

common/thanos/Chart.yaml
common/thanos/templates/ingress.yaml
common/thanos/values.yaml

the admin and customer cluster both need different special handling, which needs some inline explanation

setting ingressClassName and adding traefik documentation

---

openstack/nova/values.yaml

The default in Nova is to use 80% of the cluster's memory for bigvms. Since we switched to having 2 failover hosts, we no longer need to reserve 20% memory being able to overcommit and thus can fill the whole available cluster with big vms.

[Nova] nova-bigvm uses 100% of memory

---

openstack/sap-seeds/templates/_flavors_deleted.tpl
openstack/sap-seeds/templates/flavor-seed.yaml

We need this flavor (and possibly more in the future) with the proper
extra-specs to update old VMs via script. Hence the new extra file
"_flavors_deleted.tpl" to contain them with information on when to
remove them again.

nova/flavors: Reintroduce disabled m5.192xlarge

---

openstack/sap-seeds/templates/_flavors_deleted.tpl

Fix "nova/flavors: Reintroduce disabled m5.192xlarge"

---

openstack/cc3test/alerts/cc3test-runtime.alerts

it creates a lot of false alerts due to decomissioned bb's and their stale metrics etc - so lets disable it for now until we have found a better way of handling this

[cc3test] disable CC3TestCanaryTestsNotRunning for now

---

common/prometheus-server/CHANGELOG.md
common/prometheus-server/Chart.yaml
common/prometheus-server/templates/ingress-internal.yaml
common/prometheus-server/templates/ingress.yaml
common/prometheus-server/values.yaml

if this isn't set, it will pick up traefik in certain clusters which won't work

ingress should always be nginx

---

system/logs/templates/alerts/_fluent-bit-systemd-alerts.tpl
system/logs/vendor/fluent/templates/alerts/_fluent-alerts.tpl
system/logs/vendor/logstash-external/templates/alerts/_logstash-alerts.tpl

In order to standardize labels between Prometheis the `cluster_type` label value for metal clusters will be renamed for the infra-prometheis from `controlplane` to `metal`.
This PR prepares the _system/logs_ alerts for this change.

refac(clusterType): switch logs alerts to clusterType=metal

---

system/logs/templates/alerts/_fluent-bit-systemd-alerts.tpl
system/logs/vendor/fluent/templates/_controlplane.conf.tpl
system/logs/vendor/fluent/templates/_prometheus.conf.tpl
system/logs/vendor/fluent/templates/alerts/_fluent-alerts.tpl
system/logs/vendor/logstash-external/templates/alerts/_logstash-alerts.tpl

In order to standardize labels between Prometheis the cluster_type label value for metal clusters will be renamed for the infra-prometheis from controlplane to metal.
This PR makes sure that metrics created by fluent follow this convention.

refac(clusterType): use cluster_type=metal for metal cluster

---

openstack/sap-seeds/templates/flavor-seed.yaml

The forced flavor, used for spawning tests on baremetal and elsewhere, still needs a proper disk size because images request a "min_disk" size in their attributes for the VM.
64GiB is the most common size for regular OS images, with most other sizes being smaller.

nova/flavor: Increase "forced" disk size to 64GiB

---

openstack/octavia/templates/etc/_esd.json.tpl

In this PR I'm adding new ESD ( listener tag) with custom fastl4 profile that contains a fix for recently discovered issue with Big-IP not re-accelerating flows which have been idle for more than 22 seconds. In summary, the custom fastl4 profile disables flow aging which means idle flows will not be evicted from HW acceleration.
The custom profile itself was tested extensively in eu-de-2 in recent weeks, with no issues or impact.
This is urgently needed for Hana Cloud listeners which commonly use idle connections to the Hana DB (connection pools).
The issue in general is under active investigation at F5 and this ESD tag is considered a workaround but it needs to be made available now, due to the timeline of onboarding HC onto Converged Cloud and Archer service.
The corresponding fastl4 …

[octavia] - Add ESD listener tag for custom fastl4 profile

---

common/prometheus-server/CHANGELOG.md
common/prometheus-server/Chart.yaml
common/prometheus-server/templates/prometheus-server.yaml

example for infra-monitoring:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
labels:
+     common-chart: prometheus-server-7.2.14
prometheus: infra-collector
name: infra-collector
```

common/prometheus-server: adds chart and release labels

---

system/vmware-monitoring/templates/collector-configmap.yaml

- Include the HANA exclusive key from the OpenStack Nova traits in the vrops-exporter-collector-config (ClusterPropertiesCollector) for generating the Prometheus metrics

[vmware-monitoring] Expose custom HANA exclusive information

---

common/mariadb/Chart.yaml
common/mariadb/values.yaml

Patch includes:
- Mariadb upgrade from 10.5.17 to 10.5.21
- mysqld-exporter upgrade from v0.12.1 to v0.14.0

[MariaDB] - Security Patches upgrade to 10.5.21

---

openstack/nova/alerts/metrics-metal/nova.alerts
openstack/nova/templates/prometheus-alerts.yaml

We want the alert to only fire if the service is not disabled. Our main metric comes from prometheus-kubernetes, while the `nova_compute_service_status` metric containing the service status (0 for disabled, 1 for enabled) comes from prometheus-openstack. Both metrics are available in `metrics.metal.$region.cloud.sap`, so we move the rule into that Thanos instance.
To support Thanos, we need to extend our alert template. We detect thanos by the prefix "metrics-" for the directory. The docs [0] state, that we need to set a different label and then everything should work.
[0] https://operations.global.cloud.sap/docs/architecture/monitoring/alerts/#thanos-rulesthanosrules

[Nova] Move OpenstackNovaComputeIdle into Thanos

---

prometheus-rules/prometheus-vmware-rules/alerts/vccluster.alerts

- Modify the VCClusterDRSNotFullyAutomated expression to accommodate the HANA-exclusive custom attribute, which is now populated from the OpenStack Nova side instead of manual efforts as before
- The old manually added custom attribute will be removed from all VCs

[prometheus-vmware-rules] Update VCClusterDRSNotFullyAutomated alert

---

openstack/cc3test/templates/cronjob-automation-purger.yaml
openstack/cc3test/templates/cronjob-automation.yaml
openstack/cc3test/templates/cronjob-baremetal-purger.yaml
openstack/cc3test/templates/cronjob-baremetal.yaml
openstack/cc3test/templates/cronjob-blockstorage-purger.yaml
openstack/cc3test/templates/cronjob-blockstorage-volume.yaml
openstack/cc3test/templates/cronjob-blockstorage.yaml
openstack/cc3test/templates/cronjob-certificate.yaml
openstack/cc3test/templates/cronjob-compute-purger.yaml
openstack/cc3test/templates/cronjob-compute-server.yaml
openstack/cc3test/templates/cronjob-compute.yaml
openstack/cc3test/templates/cronjob-datastore.yaml
openstack/cc3test/templates/cronjob-dns-purger.yaml
openstack/cc3test/templates/cronjob-dns.yaml
openstack/cc3test/templates/cronjob-fileshare-purger.yaml
openstack/cc3test/templates/cronjob-fileshare.yaml
openstack/cc3test/templates/cronjob-hermes.yaml
openstack/cc3test/templates/cronjob-integrity.yaml
openstack/cc3test/templates/cronjob-key-manager-purger.yaml
openstack/cc3test/templates/cronjob-key-manager.yaml
openstack/cc3test/templates/cronjob-loadbalancer-purger.yaml
openstack/cc3test/templates/cronjob-loadbalancer.yaml
openstack/cc3test/templates/cronjob-neutron-purger.yaml
openstack/cc3test/templates/cronjob-neutron.yaml

before we were always running all the different tests with the scope set to the complete tests directory which resulted in a lot of unneeded code execution (fixtures and parametrizations for all tests, even the ones not run by a certain job) and with this change we reduce the scope for each job to only the subdirectory (or subdirectories) the corresponding tests are defined in ... this is possible now as we have properly separated all the code

[cc3test] reduce the scope of the test jobs to subdirs

---

openstack/swift-drive-autopilot/values.yaml
openstack/swift-utils/alerts/caretaker.alerts
openstack/swift-utils/values.yaml
openstack/swift/alerts/kubernetes/pod.alerts
openstack/swift/alerts/openstack/api.alerts
openstack/swift/templates/prometheus-alerts.yaml
openstack/swift/values.yaml
system/gatekeeper/tests/gatekeeper-policies/fixtures/pod-security/swift-drive-autopilot.yaml
system/gatekeeper/tests/gatekeeper-policies/fixtures/pod-security/swift-servers.yaml

This should only be merged once the new support group has been set up.
@databus23 @geisslet FYI

swift: move owner-info and alert routing to new support group "storage"

---

openstack/ironic/values.yaml

Increase the designate-propagation-timeout (from default 10m to 20m) for larger regions
Decrease the polling interval from 10s to 5s for more responsiveness

[ironic] Tune certrobot values

---

system/prometheus-infra/Chart.yaml
system/prometheus-infra/templates/_prometheus-infra.yaml.tpl

the exporter has been deleted and this clears it from the federate config

chore(prom-infra): remove image-usage-exporter job from config

---

prometheus-exporters/netapp-exporter/Chart.lock
prometheus-exporters/netapp-exporter/Chart.yaml
prometheus-exporters/netapp-exporter/charts/netapp-cap-exporter/Chart.yaml
prometheus-exporters/netapp-exporter/charts/netapp-cap-exporter/aggregations/netapp-castellum.rules
prometheus-exporters/netapp-exporter/values.yaml

We move the queries from Castellum to here. Also monitor the snapshot usage to avoid snapshot spill to active share.

Aggregated rules consumed by Castellum

---

openstack/vcf/templates/deployment.yaml
openstack/vcf/values.yaml

Internal subprocesses are oom killed because of mem limit.

[vcf] increase mem requests/limits

---

prometheus-rules/prometheus-vmware-rules/alerts/vccluster.alerts

- Adjust the VCClusterDRSNotFullyAutomated expression to explicitly check if the HANA-exclusive time series vector is set to _**true**_

[prometheus-vmware-rules] Revise VCClusterDRSNotFullyAutomated alert

---

openstack/ironic/templates/redfish-certrobot-cronjob.yaml

Kubernetes is strict in what values it accepts,
and for env keys and values it only accepts strings. Numbers need to be quoted so they have the right type

[ironic] Quote env values to ensure strings

---

openstack/sap-seeds/templates/_flavors_hana_exclusive.tpl

For decommissioning old BBs we need to move these VMs away. This patch allows to migrate VMs with these flavors onto HANA BBs. (After the old VMs are updated with the new flavor info.)

nova/flavor: Allow old bigVM flavors on HANA BBs

---

openstack/swift/alerts/openstack/api.alerts

put this warning to the group fixing stuff.
if compute needs the alert greenhouse/ alert overview or a separate routing can be enabled.
pls contact me

change support group for OpenstackSwiftDiskFailures

---

openstack/sap-seeds/templates/_flavors_deleted.tpl
openstack/sap-seeds/templates/_flavors_hana_exclusive.tpl
openstack/sap-seeds/templates/_flavors_hana_no_exclusive.tpl
openstack/sap-seeds/values.yaml

- Use correct vmware extra-specs template
- Move the flavors to _flavors_deleted.tpl
Also, remove the usage of hana_exclusive_contains_legacy_bigvm_flavors config value for hana-exclusive regions, because we don't want to delete flavors anymore if old VMs still refer to them.

nova/flavors: Fix Unlist m5.96xlarge & x1.32xlarge

---

openstack/neutron/values.yaml

Due to billing by usage, not by quota, we must expose used routers
drilled down by AZ.
The agent table carries the AZ by agent, if the AZ is 'nova' that
indicates a stretched agent, [see here](https://github.com/sapcc/asr1k-neutron-l3/blob/5dbad6b9d10bd99cf39e7da1e16700ed648bf7b1/asr1k_neutron_l3/common/asr1k_constants.py#L36).
If a router is not assigned to an l3 agent, it can also not be in used,
so I assume the `INNER JOIN` here should be fine.

[neutron] Expose used router count by AZ using database exporter

---

global/prometheus-alertmanager-operated/Chart.yaml
global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl

tier is removed from some alerts already so the previous routing filter to octobus caused gaps

rm tier filter for octobus routing

---

openstack/nova/values.yaml

The query used the disused and now mostly-empty `instance_types`
table, which made the metric report no values (or only a very few
ancient instances in some regions).
Use instance_extra instead and parse the flavor name out of the JSON.
The query is a bit more expensive this way (it doubled in time from
the query without any join).

nova/metrics: Fix empty instances gauge

---

openstack/neutron/templates/asr_config_agents/_deployment-asr1k.yaml.tpl
openstack/neutron/templates/deployment-aci-agent.yaml
openstack/neutron/templates/deployment-server.yaml

Since /development volume is not used at all, and can be impediment for service failover, reference to it is removed.

[neutron] Remove all references to /development volume

---

openstack/neutron/templates/etc/_uwsgi.ini.tpl

This option will create a unix domain socket for each worker that will print out tracebacks if a worker runs into harakiri. With harakiri-verbose we'll also see the tracebacks in our standard logs, which hopefully will allow us to better debug them.

Enable py-tracebacker for Neutron UWSGI

---

system/infra-monitoring/Chart.lock
system/infra-monitoring/Chart.yaml
system/infra-monitoring/values.yaml

With Thanos, it is no longer necessary to have `kube-state metrics` available in multiple Prometheus. Kubernetes Prometheus keeps these metrics available so that they only need to be maintained in one place. Dependent services have been adjusted accordingly so that no absent metric alerts are generated.

infra-monitoring: kube-state-metrics removed

---

common/prometheus-server/CHANGELOG.md
common/prometheus-server/Chart.yaml
common/prometheus-server/templates/alerts/_prometheus-thanos-rule.alerts.tpl
common/prometheus-server/templates/alerts/_prometheus.alerts.tpl
common/prometheus-server/templates/alerts/prometheus-alerts.yaml
common/prometheus-server/values.yaml

This is due to the removal of `kube-state-metrics` from the non-Kubernetes prometheus.

prometheus-server: get PrometheusMultiplePodScrape alerts evaluated

---

openstack/designate-nanny/templates/job.yaml

volume mounts are not needed at this point and lead to a conflict. thus removed.

[designate-nanny] remove conflicting volume mounts

---

common/thanos/Chart.yaml
common/thanos/ci/test-values.yaml
common/thanos/templates/thanos-objectstore.yaml
common/thanos/values.yaml

Compaction is done on ephemeral storage and it tends to use gigabytes. If it is more than 25Gi a pvc needs to be added. In case of bigger node an overwrite exists.

[Thanos] request ephemeral storage by default

---

common/thanos/Chart.yaml
common/thanos/templates/alerts/_thanos-store.alerts.tpl

lots of missing alerts due to a non existent metric name
replaced with latest mixin:
https://monitoring.mixins.dev/thanos/#thanosstoreseriesgatelatencyhigh

replaced metric to match

---

common/postgresql/templates/etc/_postgresql.conf.tpl

This will sort the stringList shared_preload_libraries before renderning.
If a parent chart is using more than one extension, the rendering
of the extensions will be completely random and generates useless diffs.
e.g.
```
-     = 'pg_stat_statements,pgcrypto'\t\t# (change requires restart)\npg_stat_statements.max
+     = 'pgcrypto,pg_stat_statements'\t\t# (change requires restart)\npg_stat_statements.max
```

[common/postgresql] Sort shared_preload_libraries list before rendering

---

common/mariadb/Chart.yaml
common/mariadb/templates/alerts/_mysql.alerts.tpl
common/mariadb/values.yaml

Reason: The 10.5.21 release blocking connection on various system
Reverting back the following PRs:
[MariaDB] - Security Patches upgrade to 10.5.21: https://github.com/sapcc/helm-charts/pull/5313 
rename metric in alert: https://github.com/sapcc/helm-charts/pull/5339

[MariaDB] - Rolling back Security Patches 10.5.21 to 10.5.17

---

system/audit-logs/Chart.lock
system/audit-logs/Chart.yaml
system/audit-logs/vendor/ocb-datain-static-probes/Chart.yaml
system/audit-logs/vendor/ocb-datain-static-probes/alerts/_ocb-datain.alerts
system/audit-logs/vendor/ocb-datain-static-probes/templates/probes.yaml

This will allow adding more probe targets and respective alerts via entries in the secrets.
Once this is deployed, we can remove the redundant probes from the `probe-exporter`

feat(audit-logs): add probes and alerts for all endpoints

---

system/prometheus-infra/Chart.lock
system/prometheus-infra/Chart.yaml
system/prometheus-infra/values.yaml

With Thanos, it is no longer necessary to have `kube-state-metrics` available in multiple Prometheus. Kubernetes Prometheus keeps kube_ metrics available so that they only need to be maintained in one place. Dependent services have been adjusted accordingly so that no absent metric alerts are generated.

prometheus-infra.scaleout: kube-state-metrics removed

---

openstack/utils/Chart.yaml
openstack/utils/templates/_coordination.tpl

a non standard openstack chart may be named different from the
conventional state path

[utils] allow to override coordination mount path

---

common/prometheus-server/CHANGELOG.md
common/prometheus-server/Chart.yaml
common/prometheus-server/templates/_helpers.tpl
common/prometheus-server/templates/thanos/README.md
common/prometheus-server/templates/thanos/_thanos.yaml.tpl
common/prometheus-server/values.yaml
system/thanos-seeds/Chart.yaml
system/thanos-seeds/templates/seed.yaml
system/thanos-seeds/values.yaml

the directive previously had no impact. setting these values will now result in actually configuring swift the way it is specified in the config.
as thanos-seeds are leveraging the same helper class, they need to follow the pattern. went for a simple copy approach to not overfill the template with too many if-else patterns to differentiate and still provide the old behaviour

[prometheus] userName and containerName configurable

---

system/elastiflow/Chart.yaml
system/elastiflow/alerts/infra-frontend/elastiflow.alerts
system/elastiflow/alerts/scaleout/elastiflow.alerts
system/elastiflow/templates/prometheus-alerts.yaml
system/elastiflow/values.yaml

With Thanos, it is no longer necessary to have kube-state metrics available in multiple Prometheus. Kubernetes Prometheus keeps these metrics available so that they only need to be maintained in one place. Dependent services have been adjusted accordingly so that no absent metric alerts are generated.

elastiflow: move alerts partially to Thanos Rule

---

common/thanos/Chart.yaml
common/thanos/templates/_thanos_helpers.tpl
common/thanos/values.yaml

when having a name crunch with thanos and prometheus and different containeres are used, the auto generated storage-config-secret is not matching.

adjustable storage config name

---

system/opensearch-logs/Chart.yaml
system/opensearch-logs/alerts/infra-frontend/opensearch.alerts
system/opensearch-logs/alerts/scaleout/opensearch.alerts
system/opensearch-logs/templates/prometheus-alerts.yaml
system/opensearch-logs/values.yaml

With Thanos, it is no longer necessary to have kube-state-metrics available in multiple Prometheus. Kubernetes Prometheus keeps kube_ metrics available so that they only need to be maintained in one place. Dependent services have been adjusted accordingly so that no absent metric alerts are generated.

opensearch-logs: move alerts partially to Thanos Rule

---

openstack/nova/Chart.lock
openstack/nova/Chart.yaml
openstack/nova/values.yaml

Enable `set_main_container` config for mariadb chart, giving the
mariadb container 75% of its pod's resources.
mariadb chart changes (newest-to-oldest):
- Rolling back Security Patches 10.5.21 to 10.5.17
- Enable VPA for mariadb container (#5443)
- metric was renamed (#5339)
- Security Patches upgrade to 10.5.21
- Mariadb upgrade from 10.5.17 to 10.5.21
- mysqld-exporter upgrade from v0.12.1 to v0.14.0
- improve MariaDBNotReady alert
- updates backupv2 base image (#5128)
- use non-deprecated topology labels (#5087)
- explicitly add some namespace metadata
- version bump for slow log alert fix
- fixes slow_query log setting in backup tool (#4787)
- Backup Slow log fix
- Security Patches upgrade to 10.5.17

[nova] Update mariadb to 0.7.16 & Configure VPA

---

openstack/neutron/templates/etc/_neutron.conf.tpl
openstack/neutron/values.yaml

We recently introduced a configuration option for `OwnerCheck`'s cache expiration time in Neutron. This commit exposes the possibility to set said option, defaulting to not setting it in the
`/etc/neutron/neutron.conf` at all and thus using the default from Neutron.

[neutron] Make owner_check_cache_expiration_time configurable

---

openstack/nova/Chart.lock
openstack/nova/Chart.yaml

This moves the main-container annotation to the right place.

[Nova] Bump mariadb chart to 0.7.17

---

common/memcached/Chart.yaml
common/memcached/templates/deployment.yaml
common/memcached/values.yaml

- to support K8s setups without preconfigured PriorityClass objects
- will be used for integration tests

[memcached] priorityClassName made optional

---

openstack/designate-nanny/values.yaml

The nanny was oom killed and cpu limits lead to timeouts fetching the AXFR from designate.

[designate-nanny] increasing resource limits to prevent crashes and OOM

---

openstack/poller/values.yaml

Due to the way the chart is, we need to comment out these values that are not used/required. Instead, we should not just loop over all keystone kv pairs, and instead have them more hardcoded. IMO this would provide a more user-friendly use of the chart

Poller: comment out values that are optional

---

openstack/cinder/Chart.lock
openstack/cinder/Chart.yaml

This patch updates the mariadb chart to 0.7.12 to help prevent false positives with CinderMariaDBNotReady alerts.

[Cinder] Update mariadb chart to 0.7.12

---

openstack/trust-manager/Chart.lock
openstack/trust-manager/Chart.yaml
openstack/trust-manager/templates/sapcc-bundle.yaml
openstack/trust-manager/values.yaml

Instead of having to build our own images with the certificates baked in, we can centrally declare them all and just mount them in the way described here:
https://cert-manager.io/docs/tutorials/getting-started-with-trust-manager/

[trust-manager] Central way to manage certificate trust bases

---

openstack/nova/templates/api-ingress.yaml

Using `configuration-snippet` is disabled for security reasons. Setting the OpenStack request-id is by now integrated into the ingress itself.

[Nova] Remove configuration-snippet ingress annotation

---

openstack/placement/templates/placement-ingress.yaml

Using `configuration-snippet` is disabled for security reasons. Setting the OpenStack request-id is by now integrated into the ingress itself.

[Placement] Remove configuration-snippet ingress annotation

---

openstack/neutron/templates/ingress-server.yaml

Using `configuration-snippet` is disabled for security reasons. Setting the OpenStack request-id is by now integrated into the ingress itself.

[Neutron] Remove configuration-snippet ingress annotation

---

global/prometheus-alertmanager-operated/Chart.yaml
global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl

Same as for my own services that were already moved. This was discussed with the Swift service owners (cc @sumitarora2786).

alertmanager: move Swift alerts from #cc-os-swift to #cc-swift

---

openstack/ironic/templates/api-ingress.yaml

Using `configuration-snippet` is disabled for security reasons. Setting the OpenStack request-id is by now integrated into the ingress itself.

[Ironic] Remove configuration-snippet ingress annotation

---

openstack/trust-manager/values.yaml

the label `name` is apparently the old version of
`kubernetes.io/metadata.name`.

[trust-manager] Fix label selector for monsoon3 namespace

---

prometheus-rules/prometheus-kubernetes-rules/Chart.yaml
prometheus-rules/prometheus-kubernetes-rules/alerts/health.alerts.tpl
prometheus-rules/prometheus-kubernetes-rules/alerts/kubelet.alerts.tpl

* fire critical only when 5 or more nodes are down/notready
* ignore storage nodes since they are handled by other team

[prome-k8s-rules] bump manykubelet/node alert

---

openstack/utils/Chart.yaml
openstack/utils/templates/_linkerd.tpl

While they might also seem to fit directly into the common/linkerd-support chart, they don't, because the snippets would not be helpful for all the charts consuming the linkerd-support chart. Specifically those in common/ would not be able to access them if their parent chart includes linkerd-support. Having the chart as extra dependency is also not wanted. Therefore, we add these helper snippets here to use them in the openstack charts.
There are 2 annotation helpers defined for which more documentation can be found in the README of the linkerd-support chart.
Instead of having to put the 3-4 lines in every template, these snippets allow us to add only one and also update it centrally.
---
For reference, I tried to add it into `linkerd-support` in #5556

[utils] Add linkerd helpers

---

openstack/keystone/Chart.yaml
openstack/keystone/values.yaml

This is a part of the effort to get rid of vulnerabilities in dependencies. Keystone is getting upgraded to zed

keystone: upgrade to zed

---

common/memcached/templates/deployment.yaml
common/memcached/values.yaml

adding support for linkerd annotation to memcached helm chart the annotation can be activated by setting up the following values to true :
```
.Values.global.linkerd_enabled = true
.Values.global.linkerd_requested = true
```
if the previous values are set globally in the top level Chart, you can deactivate the annotation for this particular chart by overriding: `.Values.linkerd.enabled` to `false` (default true)
for more information about linkerd please find:
https://github.com/sapcc/helm-charts/tree/master/common/linkerd-support
splitting PR: https://github.com/sapcc/helm-charts/pull/5532 into multiple PRs per helm chart

[memcached] add linkerd annotation

---

common/rabbitmq/Chart.yaml
common/rabbitmq/templates/deployment.yaml
common/rabbitmq/templates/headless-service.yaml
common/rabbitmq/templates/service.yaml
common/rabbitmq/templates/statefulset.yaml
common/rabbitmq/values.yaml

adding support for linkerd annotation to rabbitmq helm chart the annotation can be activated by setting up the following global values to true :
```
.Values.global.linkerd_enabled = true
.Values.global.linkerd_requested = true
```
if the previous values are set globally in the top level Chart, you can deactivate the annotation for this particular chart by overriding:` .Values.linkerd.enabled` to `false` (default true)
for more information about linkerd lease find:
https://github.com/sapcc/helm-charts/tree/master/common/linkerd-support
splitting PR: https://github.com/sapcc/helm-charts/pull/5532 into multiple PRs per helm chart

[rabbitmq] add linkerd annotation

---

common/mariadb/Chart.yaml
common/mariadb/templates/backup-ingress.yaml
common/mariadb/templates/backup-v2-deployment.yaml
common/mariadb/templates/backup-verify-deploy.yaml
common/mariadb/templates/deployment.yaml
common/mariadb/templates/service.yaml
common/mariadb/values.yaml

adding support for linkerd annotation to mariadb helm chart the annotation can be activated by setting up the following values to true:
```
.Values.global.linkerd_enabled = true
.Values.global.linkerd_requested = true
```
if the previous values are set globally in the top level Chart, you can deactivate the annotation for parts of the chart as the following:
- deactivate linkerd annotations for mariadb pod` Values.linkerd.mariadb.enabled = false `(default true)
- deactivate linkerd annotations for the backup pod `Values.linkerd.backup.enabled = false` (default true)
for more information about linkerd please find:
https://github.com/sapcc/helm-charts/tree/master/common/linkerd-support
splitting PR: https://github.com/sapcc/helm-charts/pull/5532 into multiple PRs per helm chart

[mariadb] add linkerd annotation

---

openstack/nova/Chart.lock
openstack/nova/Chart.yaml

The new versions of the above-mentioned charts support linkerd annotations.

[Nova] Bump rabbitmq, memcached, mariadb for linkerd

---

common/memcached/Chart.yaml

version bumping was forgotten in commit
"[memcached] add linkerd annotation" / 1b829661b4a172b4e7615ad784dd109a9e9262f5
bumping up the version to 0.2.0

[memcached] bumping the version for activating linkerd

---

openstack/cinder/alerts/openstack-cinder.alerts

This patch updates the queried timeout from 15 seconds to 2 minutes to help prevent false issues.  Sometimes vcenter is just busy and
deleting a volume can take a bit of time.   2 minutes seems like a
decent amount of time to allow for the action to complete.

[Cinder] increase CinderVolumeInDeletingState time

---

openstack/designate/Chart.lock
openstack/designate/Chart.yaml
openstack/designate/bin/db-migrate
openstack/designate/templates/_helpers.tpl
openstack/designate/templates/api-deployment.yaml
openstack/designate/templates/bin-configmap.yaml
openstack/designate/templates/bin/_db-migrate.sh.tpl
openstack/designate/templates/central-deployment.yaml
openstack/designate/templates/mdns-deployment.yaml
openstack/designate/templates/migration-job.yaml
openstack/designate/templates/producer-deployment.yaml
openstack/designate/templates/proxysql-configmap.yaml
openstack/designate/templates/sink-deployment.yaml
openstack/designate/templates/worker-deployment.yaml
openstack/designate/values.yaml

This change should route all db queries through a pod-local
side-car to handle the connection resets of a restarting
mariadb
It requires the credentials in .Values.mariadb.users

[designate] Add proxysql side-cars

---

openstack/neutron/Chart.lock
openstack/neutron/Chart.yaml
openstack/neutron/values.yaml

We have now a central one for all services, and neutron is already sending to the new one, so we can drop the old one: It is only wasting resources.

[neutron] Drop per-service rabbitmq-notifications

---

openstack/placement/Chart.lock
openstack/placement/Chart.yaml
openstack/placement/templates/_helpers.tpl
openstack/placement/templates/db-migrate-job.yaml
openstack/placement/templates/db-online-migrate-job.yaml
openstack/placement/templates/placement-api-deployment.yaml
openstack/placement/values.yaml

The snippets replace the system ca trust-bundle with a centrally managed one by trust-manager in k8s. 
This eliminates the need for patching the images to contain the company internal CA.

[openstack/placement] Make use of trust-bundle snippets

---

openstack/placement/Chart.lock
openstack/placement/Chart.yaml

The dependency was incorrectly adding a volume mount of the proxysql when proxysql has been disabled

[openstack/placement] Fix trust-bundle without proxysql

---

system/kube-system-virtual/values.yaml

fixes the `Prometheus is scraping kube-system-virtual-velero pods in namespace kube-system multiple times. This is likely caused due to incorrectly placed scrape annotations.` alert

Fix velero pod annotation to avoid double scraping

---

openstack/glance/Chart.lock
openstack/glance/Chart.yaml
openstack/glance/templates/_helpers.tpl
openstack/glance/templates/deployment.yaml
openstack/glance/templates/migration-job.yaml

[openstack/glance] Make use of trust-bundle snippets

---

openstack/nova/Chart.lock
openstack/nova/Chart.yaml
openstack/nova/ci/test-values.yaml
openstack/nova/templates/_console_deployment.yaml.tpl
openstack/nova/templates/api-deployment.yaml
openstack/nova/templates/api-metadata-deployment.yaml
openstack/nova/templates/bigvm-deployment.yaml
openstack/nova/templates/cell2-conductor-deployment.yaml
openstack/nova/templates/conductor-deployment.yaml
openstack/nova/templates/console-shellinabox-deployment.yaml
openstack/nova/templates/db-migrate-job.yaml
openstack/nova/templates/db-online-migrate-job.yaml
openstack/nova/templates/hypervisors/_ironic-deployment.yaml.tpl
openstack/nova/templates/hypervisors/_kvm-deployment.yaml.tpl
openstack/nova/templates/hypervisors/hypervisors-vmware-deployment-vct.yaml
openstack/nova/templates/scheduler-deployment.yaml
openstack/nova/templates/vspc-deployment.yaml
openstack/nova/values.yaml

[openstack/nova] Make use of trust-bundle snippets

---

common/rabbitmq/Chart.yaml
common/rabbitmq/templates/alerts/_health.alerts.tpl

The critical alert should not fire if any rabbitmq is not ready, it should fire if no rabbitmq pods are ready.
Which is is difference, because there may be a NotReady pod still lingering around next to a working Ready pod.
We observed this with a pod stuck in Terminating due a node not being safely drained.

[rabbitmq] improve RabbitMQNotReady alert

---

common/thanos/Chart.yaml
common/thanos/templates/_thanos_helpers.tpl
common/thanos/templates/sd-configmap.yaml
common/thanos/templates/thanos.yaml
common/thanos/values.yaml

This change will move away from thanos-operator functionality to get more control over container args. Query discovery is ensured via helm lookup function on Kubernetes Services.

common/thanos: query deployment overrides

---

openstack/manila/values.yaml

I need these to collect the respective usage data in Limes.
Otherwise this would require extensive shenanigans to join in the respective labels from the share metrics, which would put unreasonable strain on the Prometheus server.
Note that I have not tested this; I'm just going by what is already working in the corresponding share metrics queries, since the `share_instances` table is already joined into this query anyway.

manila: add share_type_id to snapshot size/count metrics

---

openstack/ironic/Chart.lock
openstack/ironic/Chart.yaml
openstack/ironic/templates/_conductor-deployment.yaml.tpl
openstack/ironic/templates/api-deployment.yaml
openstack/ironic/templates/db-migration-job.yaml
openstack/ironic/templates/inspector-conductor-deployment.yaml
openstack/ironic/templates/inspector-db-migration-job.yaml
openstack/ironic/templates/inspector-deployment.yaml
openstack/ironic/templates/pxe-deployment.yaml
openstack/ironic/templates/pxe-setup-job.yaml
openstack/ironic/templates/redfish-certrobot-cronjob.yaml
openstack/ironic/templates/security-group-setup.yaml
openstack/ironic/values.yaml

[openstack/ironic] Make use of trust-bundle snippets

---

openstack/designate/templates/migration-job.yaml

Only if proxysql is actually deployed can we make use of it in the pre-upgrade job, as the configmap gets created in the actual deployment.

[designate] Fix chicken-and-egg with proxysql in pre-upgrade job

---

openstack/manila/Chart.lock
openstack/manila/Chart.yaml
openstack/manila/templates/api-deployment.yaml
openstack/manila/templates/migration-job.yaml
openstack/manila/templates/scheduler-deployment.yaml
openstack/manila/templates/shares/_netapp-deployment.yaml.tpl
openstack/manila/templates/shares/_netapp-ensure-deployment.yaml.tpl

[openstack/manila] Make use of trust-bundle snippets

---

openstack/octavia/templates/octavia-migration-job.yaml

We can only do the pre-upgrade job with proxysql enabled, if proxysql has already been installed, as the configmap hasn't been created yet.

[octavia] Do not enable proxysql pre-upgrade

---

openstack/barbican/Chart.lock
openstack/barbican/Chart.yaml
openstack/barbican/templates/api-deployment.yaml
openstack/barbican/templates/ingress.yaml
openstack/barbican/templates/service.yaml
openstack/barbican/values.yaml

This adds the `linkerd-support` chart as dependency and also adds the annotations to all `Deployment`, `Service` and `Ingress` objects. `Job` objects are out of the picture for now

[Barbican]Add basic linkerd support

---

openstack/hermes/templates/etc/_logstash.conf.tpl

There have been exception such as:
```bash
[WARN ] 2023-11-23 02:02:22.080 [[main]>worker0] mutate - Exception caught while applying mutate filter {:exception=>"Invalid FieldReference: `%{[initiator][project_id]}`",
:backtrace=>[
"org/logstash/ext/JrubyEventExtLibrary.java:154:in `include?'",
"/usr/share/logstash/logstash-core/lib/logstash/util/decorators.rb:35:in `block in add_fields'",
"org/jruby/RubyArray.java:1821:in `each'",
"/usr/share/logstash/logstash-core/lib/logstash/util/decorators.rb:33:in `block in add_fields'",
"org/jruby/RubyHash.java:1415:in `each'", 
"/usr/share/logstash/logstash-core/lib/logstash/util/decorators.rb:30:in `add_fields'", 
"/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:198:in `filter_matched'", …
```

fix(hermes): swap logstash mutate of initiator project/domain

---

global/thanos-global/Chart.yaml
global/thanos-global/alerts/thanos-global.alerts
global/thanos-global/templates/alerts.yaml

Global should be able to reach 9 stores, not checking all vmware stores and ignoring special clusters. This is a sanity check and does not show, which store is missing exactly

adding global stores alert

---

openstack/placement/Chart.lock
openstack/placement/Chart.yaml
openstack/placement/templates/placement-api-deployment.yaml
openstack/placement/templates/placement-api-service.yaml
openstack/placement/templates/placement-ingress.yaml
openstack/placement/values.yaml

We need to bump the mariadb chart and the memcached chart, which brings in a new memcached version 1.6.21 in addition to linkerd support.
We do not support Job objects here, yet, as it's still open how we will do the shutdown of linkerd.

[Placement] Add basic linkerd support

---

openstack/neutron/templates/etc/_ml2-conf-aci.ini.tpl

In the driver we do now support no port-selectors, if a host never has
to go into baremetal mode. This commit will omit the port_selectors key
if they are unset.
The policy group was inferred to be the same name as the VPC profile's
first binding's name. This failed when our subgroups got multiple
bindings which lead to an empty string being rendered into the config.
This shouldn't go unnoticed so we prompt the user to supply an explicit
pc-group only if port selectors are set. Policy groups are not needed if
port-selectors are unset, as no disassembling of the VPC profile will
happen.

Improve empty port-selector and multiple subgroup bindings hadling

---

openstack/designate/Chart.lock
openstack/designate/Chart.yaml
openstack/designate/templates/api-deployment.yaml
openstack/designate/templates/api-ingress.yaml
openstack/designate/templates/api-service.yaml
openstack/designate/templates/central-deployment.yaml
openstack/designate/templates/mdns-deployment.yaml
openstack/designate/templates/mdns-service.yaml
openstack/designate/templates/producer-deployment.yaml
openstack/designate/templates/sink-deployment.yaml
openstack/designate/templates/worker-deployment.yaml
openstack/designate/values.yaml

This adds the linkerd-support chart as dependency and also adds the
annotations to all Deployment, Service, Daemonset and Ingress objects.
linkerd is disabled by default and needs to be enabled per region.
We depend on the utils chart for the annotation snippets and the
conditions so our templates stay more compact and thus better readable.
Supporting charts versions are bumped to support this change.
Chart version bumped to 0.2.1

[designate] Add basic linkerd support

---

openstack/cinder/Chart.lock
openstack/cinder/Chart.yaml
openstack/cinder/templates/api-deployment.yaml
openstack/cinder/templates/api-ingress.yaml
openstack/cinder/templates/api-service.yaml
openstack/cinder/templates/backup_deployment.yaml
openstack/cinder/templates/scheduler-deployment.yaml
openstack/cinder/templates/vcenter_datacenter_cinder_deployment.yaml
openstack/cinder/values.yaml

This adds the `linkerd-support` chart as dependency and also adds the annotations to all `Deployment`, `Service` and `Ingress` objects.
linkerd is disabled by default and needs to be enabled per region.
We depend on the `utils` chart for the annotation snippets and the conditions so our templates stay more compact and thus better readable.

[Cinder] Update chart to include linkerd

---

openstack/manila/Chart.lock
openstack/manila/Chart.yaml
openstack/manila/templates/api-deployment.yaml
openstack/manila/templates/api-ingress.yaml
openstack/manila/templates/api-service.yaml
openstack/manila/templates/scheduler-deployment.yaml
openstack/manila/templates/shares/_netapp-deployment.yaml.tpl
openstack/manila/templates/shares/_netapp-ensure-deployment.yaml.tpl
openstack/manila/values.yaml

This adds the linkerd-support chart as dependency and also adds the
annotations to all Deployment, Service, Daemonset and Ingress objects.
linkerd is disabled by default and needs to be enabled per region.
We depend on the utils chart for the annotation snippets and the
conditions so our templates stay more compact and thus better readable.
Supporting charts versions are bumped to support this change.
Chart version bumped to 0.3.11

Add linkerd support, bump chart and supporting charts versions

---

system/auditbeat/Chart.yaml
system/auditbeat/Dockerfile.exporter
system/auditbeat/Makefile
system/auditbeat/templates/auditbeat-daemonset.yaml
system/auditbeat/values.yaml

The upstream Dockerfile is using an outdated version of Python and has old versions of requirements.
This PR provides a new `Dockerfile.exporter` which uses Python 3.10 and installs latest versions of the requirements.

chore(auditbeat): update exporter image

---

openstack/manila-nanny/Chart.lock
openstack/manila-nanny/Chart.yaml
openstack/manila-nanny/templates/deployment.yaml
openstack/manila-nanny/values.yaml

This adds the linkerd-support chart as dependency and also adds the
annotations to Deployment.
linkerd is disabled by default and needs to be enabled per region.
We depend on the utils chart for the annotation snippets and the
conditions so our templates stay more compact and thus better readable.
Supporting charts versions are bumped to support this change.
Chart version bumped to 0.1.1

[manila-nanny] adding basic linkerd support

---

openstack/ironic/Chart.lock
openstack/ironic/Chart.yaml
openstack/ironic/templates/_conductor-deployment.yaml.tpl
openstack/ironic/templates/_console-ingress.yaml.tpl
openstack/ironic/templates/_console-service.yaml.tpl
openstack/ironic/templates/api-deployment.yaml
openstack/ironic/templates/api-ingress.yaml
openstack/ironic/templates/api-service.yaml
openstack/ironic/templates/hpa-conductor.yaml
openstack/ironic/templates/inspector-conductor-deployment.yaml
openstack/ironic/templates/inspector-deployment.yaml
openstack/ironic/templates/inspector-ingress.yaml
openstack/ironic/templates/inspector-service.yaml
openstack/ironic/templates/pxe-deployment.yaml
openstack/ironic/templates/pxe-service.yaml
openstack/ironic/values.yaml

This adds the `linkerd-support` chart as dependency and also adds the annotations to all `Deployment`, `Service` and `Ingress` objects. `Job` objects are out of the picture for now

[Ironic] Add basic linkerd support

---

openstack/barbican/Chart.lock
openstack/barbican/Chart.yaml
openstack/placement/Chart.lock
openstack/placement/Chart.yaml

[barbican] Bump utils dependency for proxysql update

---

openstack/glance/Chart.lock
openstack/glance/Chart.yaml

[glance] Bump utils dependency for proxysql update

---

openstack/ironic/Chart.lock
openstack/ironic/Chart.yaml

[ironic] Bump utils dependency for proxysql update

---

system/logs/values.yaml

It looks like the cronus nodes in the scaleout clusters have a taint `dedicated=cronus`, causing no fluent bit on the nodes and not logging being shipped

adding cronus toleration for logging

---

openstack/manila/Chart.lock
openstack/manila/Chart.yaml

[manila] Bump utils dependency for proxysql update

---

openstack/keystone/values.yaml

This should make it easier to get cross-service metric dashboards, such as the proxysql one.

[keystone] Add service info to owner-info

---

openstack/octavia/values.yaml

This should make it easier to get cross-service metric dashboards, such as the proxysql one.

[octavia] Add service info to owner-info

---

openstack/octavia/templates/_helpers.tpl
openstack/octavia/templates/octavia-api-deployment.yaml
openstack/octavia/templates/octavia-housekeeping.yaml
openstack/octavia/templates/octavia-migration-job.yaml
openstack/octavia/templates/octavia-worker-deployment.yaml

The explanation in the deleted code comment that jobs cannot be recreated was correct at the time, in commit 24c84622a6, because the job was created as a regular manifest object instead of a hook object.
As of now, the job has a `hook-delete-policy: before-hook-creation`, so job spec immutability is not a concern.
We found this issue while I was explaining the GkVulnerableImages check to Benjamin Ludwig, and we saw that dozens of old images are kept from being GC'd because these jobs are still referencing them.

octavia: fix jobs being left over after redeployment

---

openstack/keystone/templates/daemonset-keep-image-pulled.yaml

The old value was 5 and has practically never been revisited. Change it to 10% so it scales with the cluster size.

[keystone] Set keep-image-pulled maxUnavailable to 10%

---

openstack/neutron/values.yaml

This should make it easier to get cross-service metric dashboards, such as the proxysql one.

[neutron] Add service info to owner-info

---

prometheus-exporters/openstack-exporter/alerts/cinder.alerts

This patch updates the cinder alerts for FreeSpace to ensure we filter out the pools that are down. We only want to use pools that are 'up'

[Cinder] Update Cinder alerts

---

common/prometheus-alertmanager-base/Chart.yaml
common/prometheus-alertmanager-base/templates/alertmanager.yaml

the operator will obey the version set and set flags accordingly
https://github.com/prometheus-operator/prometheus-operator/blob/9fe4c212cb085356ae24591fd3075e728196b213/pkg/alertmanager/statefulset.go#L311-L320
If this is not set, it will use the default: https://github.com/prometheus-operator/prometheus-operator/blob/30148709865dcd8a56c59363dcb953f117d0d0ce/pkg/operator/defaults.go#L21
This PR will make sure, that an operator upgrade is not breaking the AM again based on versioning flags, if it is covered in code.
Version the previous to current version increased by one to ensure cluster functionality as is.

explicitly set am version

---

openstack/octavia/templates/etc/_esd.json.tpl
openstack/octavia/values.yaml

In this PR I am removing an obsolete esd `hcm_rmk_restrict_internal` from octavia esd templates and from DB metrics queries.
This esd was introduced back in 2020 for HCM specific security use case (redirecting users to specific web pages based on their IPs). This was only ever used in ap-ae-1 and ap-sa-1.
I verified that the policy is not used any more on any listeners and I also confirmed with HCM (Dave McElhinney) that it is not needed any more as the use case is no longer valid.

[octavia] - remove obsolete esd

---

openstack/sap-seeds/templates/_flavors_deleted.tpl

Includes low-cpu HANA- & "x1.64xlarge" & "xclarity" flavors.
VMs with hard-deleted flavors cannot be fully managed anymore and more importantly don't get the CUSTOM_HANA_EXCLUSIVE:forbidden trait, so they are sitting on hana-only BBs taking up space. Updating their flavor info enables us to move them away.
gmp_m1946_c128 & x1.64xlarge were not technically a HANA flavors, but still get the same treatment because of their size (~2TiB & ~4TiB respectively). Currently there are only 3 gmp_m1946_c128 VMs left (one in each ap-jp-1, eu-de-2 & na-us-1) and 1 x1.64xlarge VM (na-us-2) and no new ones can be created, so it shouldn't be too disruptive.
The old HANA flavors are still limited by their NUMASIZE trait to their old hardware. This may need changing in the future depending on how long we'll …

nova/flavors: Add back GMP- & other deleted flavors

---

openstack/octavia/Chart.lock
openstack/octavia/templates/octavia-api-deployment.yaml
openstack/octavia/templates/octavia-housekeeping.yaml
openstack/octavia/templates/octavia-migration-job.yaml
openstack/octavia/templates/octavia-worker-deployment.yaml
openstack/octavia/values.yaml

Also update the job-name to include more fields to monitor for a change.

[openstack/octavia] Make use of trust-bundle snippets

---

system/unbound/templates/deployment.yaml

bad:
```yaml
- -arg1 value1
- -arg2 value2
```
good:
```yaml
- -arg1
- value1
- -arg2
- value2
```

[unbound][dnstap] -- args names/values need to be separate list items

---

common/prometheus-alertmanager-base/CHANGELOG.md
common/prometheus-alertmanager-base/Chart.yaml
common/prometheus-alertmanager-base/ci/test-values.yaml
common/prometheus-alertmanager-base/templates/alertmanager.yaml
common/prometheus-alertmanager-base/values.yaml

version in the AM CRD can now be set differently from .Chart.AppVersion Used to avoid newer features which are hard coded

allow am crd to have a different version

---

openstack/neutron/Chart.lock
openstack/neutron/Chart.yaml

[neutron] Bump utils dependency for proxysql update

---

openstack/keystone/Chart.lock
openstack/keystone/Chart.yaml

[keystone] Bump utils dependency for proxysql update

---

openstack/designate/Chart.lock
openstack/designate/Chart.yaml

[designate] Bump utils dependency for proxysql update

---

openstack/utils/Chart.yaml
openstack/utils/values.yaml

Set trust-bundle feature to off by default, as described in the original commit message, to provide backwards compatibility.

Set trust-bundle to off by default

---

openstack/cinder/Chart.lock
openstack/cinder/Chart.yaml

[cinder] Bump utils dependency for proxysql update

---

system/unbound/templates/deployment.yaml

Set it only if .Values.unbound.dnstap.hec_splunk_server_uuid is defined.

[unbound][dnstap] -- make the -server_uid HEC splunk cmdline arg optional

---

openstack/neutron/Chart.lock
openstack/neutron/Chart.yaml

The prior version had the trust-bundle enabled by default, this reverts that behaviour.

[neutron] Use newer utils version with disabled by default trust-bundle

---

openstack/sap-seeds/templates/_flavors_deleted.tpl

The size threshold for BigVMs is >=1024 and not >1024, so these 3
flavors will also need the BigVM treatment, or VMs' migrations will
be rejected.
The flavors don't have the NUMASIZE ratio that their resource
extra-spec requires (C48_M729), but:
- there are so few VMs of these flavors,
- the CPU is _less_ than the ratio, so we won't run into contention,
- there are much more C48_M729 clusters available than the
alternative, C49_M1459

nova/flavors: Add BigVM extra-specs to =1TiB flavors

---

openstack/designate-nanny/templates/deployment.yaml
openstack/designate-nanny/values.yaml

Our dnsglobal setup uses a different auth_url scheme, so adding it to the values of each region and taking it from there. Also adding errors when parameters are missing sounds like a good idea.

[designate-nanny] using the auth_url from values to support global setup

---

openstack/designate-nanny/ci/test-values.yaml
openstack/designate-nanny/templates/deployment.yaml
openstack/designate-nanny/values.yaml

cannot use the makro in values.yaml, reverting for now and setting explicitly in secrets.

[designate-nanny] using makro for keystone url at proper location

---

openstack/utils/Chart.yaml
openstack/utils/templates/_trust_bundle.tpl

The defaults seem to differ between implementations, so we rather want to set it explicitly to make sure it is picked up as expected.

[openstack/utils] Set SSL_CERT_FILE specifically

---

common/thanos/Chart.yaml
common/thanos/templates/_thanos_helpers.tpl

Query store api's are added to the service discovery file in different orders. This quickly becomes disorganized if many targets are involved (global). This PR sorts the targets alphabetically.

common/thanos: sort query store apis

---

common/thanos/Chart.yaml
common/thanos/templates/alerts/_thanos-compactor.alerts.tpl
system/thanos-metal/Chart.lock
system/thanos-metal/Chart.yaml
system/thanos-metal/alerts/thanos-regional.alerts
system/thanos-metal/templates/alerts_regional.yaml

alert needs to move to respective regional thanos. since it is pushed to every thanos it is missing the kube_pod_info. We want it centrally only
Using the opportunity to upgrade.

moving alert to regional and version bump

---

common/thanos/Chart.yaml
common/thanos/templates/thanos-objectstore.yaml
common/thanos/templates/thanos.yaml

The upstream Thanos image has changed the default user in the container image to 1001 instead of 0 (root).
https://github.com/thanos-io/thanos/pull/6107
As we are dependent on user 0 in our environment, we explicitly set it to 0.

common/thanos: set default user to 0 (root)

---

openstack/octavia/alerts/octavia.alerts
openstack/octavia/values.yaml

This PR is for AZ-aware LB usage reporting with Limes. Limes will probably want to `sum by (loadbalancer_availabilityzone)` or something and set label `loadbalancer_status!="DELETED"`.
Neutron added a dedicated metric for this in #5374, but the already existing `octavia_loadbalancers_count_gauge` should work fine, since our Grafana/Plutono dashboards all use this metric with `sum()`. The only place that has to be changed is the `OpenstackOctaviaLoadbalancerErrored` alert, see below.
---
Also:
- Fix `OpenstackOctaviaLoadbalancerErrored` alert: Since `octavia_loadbalancers_count_gauge` is labelled by status and host (and now also project and AZ), `rate()` will calculate the rate of `ERROR` LB count per status and host (and project and AZ), but we are interested in the *overall* `ERROR` LB …

[octavia] Add project/AZ metric labels for AZ-aware LB usage reporting

---

openstack/octavia/templates/octavia-worker-deployment.yaml

When the worker does not have an availability zone set, the label will be empty.
@majewsky please keep this in mind and check whether this behavior is okay.

[Octavia] Add availability zone to worker pod labels

---

openstack/neutron/templates/seed.yaml
openstack/neutron/values.yaml

One of many commits towards being able to do easier password rotations. The Neutron user can now be changed via helm-chart.

[neutron] Parameterize neutron service user

---

openstack/limes/templates/_utils.tpl

We need to change user with credentials to enable a interruption free deployment.
First, roll-out new user with new password, then remove old user.

[limes] Make rabbitmq user configurable

---

openstack/octavia/values.yaml

If `availability_zone` is `null`, it is filtered out by Prometheus. Therefore, select "any" instead, which corresponds to [the enum symbol used by Limes](https://pkg.go.dev/github.com/sapcc/go-api-declarations/limes#AvailabilityZone) and is already used in #5752
This is a follow-up PR to #5671

[octavia] Fix usage reporting: Select 'any' when no AZ

---

prometheus-exporters/netapp-exporter/charts/netapp-cap-exporter/aggregations/netapp-castellum.rules

Like with the other "for Castellum" metrics, this moves code ownership for these rules to the Manila team.
For reference, the existing implementation in Castellum is at <https://github.com/sapcc/castellum/blob/e41fe9ea6e89e91b50d26f18d92dcc9eee8573a4/cmd/netapp-scout/api.go#L105-L151>. I carried over most of the explanation comments, but those are obviously influenced by my limited understanding of the subject matter, so feel free to extend or reword them as necessary.

netapp-exporter: evaluate Castellum exclusion rules in PromQL

---

common/prometheus-server/CHANGELOG.md
common/prometheus-server/Chart.yaml
common/prometheus-server/templates/vpa.yaml
common/prometheus-server/values.yaml

specifying some dedicated values in our config repository lead to overwriting of the whole maxAllowed list. This uses a map instead of a list now and will prohibit this behaviour.

allow individual mapping

---

openstack/neutron/templates/seed.yaml

The username was still hardcoded to neutron for the cloud_dns_admin role, now it's parameter!

[neutron] Parameterize neutron user in seeds

---

openstack/nova/templates/etc/_nova_audit_map.yaml.tpl

Adjust to Service vs. Server as it's a service. Then it will need tested, and validated as a solution to handle these events from the endpoint change from /enable to relying on put and delete on the /uuid
Put contains the details listed here for an update: https://docs.openstack.org/api-ref/compute/#update-compute-service
However delete does not contain the host, or other information in the response, just the UUID of the service.
https://docs.openstack.org/api-ref/compute/#delete-compute-service
This is a test to validate the data returned, and to try to sort out the best solution for auditors to follow the path of activity from these compute-services

[nova] audit_map adjust os-services mapping

---

openstack/nova/values.yaml

We've seen 4 times CPU overcommit being too high and leading to problems for VMs since the VMware driver also counts hyperthreading cores as full VCPUS.

[Nova] Reduce cpu_allocation_ratio to 3

---

openstack/neutron/Chart.lock
openstack/neutron/Chart.yaml
openstack/neutron/templates/_helper.tpl
openstack/neutron/templates/daemonset-metadata-agent.yaml
openstack/neutron/templates/deployment-aci-agent.yaml
openstack/neutron/templates/deployment-cc-fabric-agent.yaml
openstack/neutron/templates/deployment-ironic-agent.yaml
openstack/neutron/templates/deployment-nsxv3-logstash.yaml
openstack/neutron/templates/deployment-rpc-server.yaml
openstack/neutron/templates/deployment-server.yaml
openstack/neutron/templates/deployment-ucs-bm-ml2-agent.yaml
openstack/neutron/templates/job-migration.yaml
openstack/neutron/templates/sftp-deployment.yaml
openstack/neutron/templates/statefulset-network-agent-apod.yaml
openstack/neutron/templates/statefulset-network-agent.yaml
openstack/neutron/templates/statefulset-swift-injector.yaml
openstack/neutron/templates/vct-nsxv3-agent-deployment.yaml
openstack/neutron/values.yaml

Also update the job-name to include more fields to monitor for a change.

[openstack/neutron] Make use of trust-bundle snippets

---

openstack/sap-seeds/templates/flavor-seed.yaml

As new-style replacement for ~m1.10xlarge.

nova/flavors: Add g_c48_m192

---

openstack/sap-seeds/ci/test-values.yaml
openstack/sap-seeds/templates/_flavors_hana_no_exclusive.tpl
openstack/sap-seeds/values.yaml

Needed for Limes' upcoming 2024 quota revamp.
Only for nova-bigvm-enabled regions, since we only need it in qa-de-1 first.

nova/flavors: Separate instance quota for hana-flavors

---

openstack/keystone/Chart.yaml
openstack/keystone/templates/deployment-api.yaml
openstack/keystone/templates/deployment-cron.yaml
openstack/keystone/templates/job-bootstrap.yaml

```yaml
- name: DEPENDENCY_JOBS
value: "keystone-job-migration-e3b0-zed-20231213110943","keystone-job-bootstrap-e3b0-zed-20231213110943"
```
```yaml
- name: DEPENDENCY_JOBS
value: "keystone-job-migration-e3b0-zed-20231213110943,keystone-job-bootstrap-e3b0-zed-20231213110943"
```

[keystone] invalid yaml for DEPENDENCY_JOBS env var fixed

---

prometheus-exporters/snmp-exporter/px.alerts/snmp-pxdl.alerts
prometheus-exporters/snmp-exporter/px.alerts/snmp-pxswitch-multi-az.alerts
prometheus-exporters/snmp-exporter/px.alerts/snmp-pxswitch.alerts
system/infra-monitoring/vendor/px-exporter/alerts/infra-collector/px.alerts

PX is in the process of transitioning from Chris Frank's team to the WAN
team. As a consequence alerting should also go to them.

[PX] Deliver alerts to WAN team

---

openstack/hermes/templates/logstash-etc-configmap.yaml

I think doing it on succeed was too aggressive and causes the config map to not be available.

[hermes] modify hooks to refresh configmap

---

openstack/maia/values.yaml

I don't see the annotation when checking values on the release. I'm quite confused what is missing, just reordering which shouldn't matter.

[maia] adjusting values order annotation isn't triggering

---

openstack/sap-seeds/templates/_flavors_deleted.tpl

Fix for
6ea87996 nova/flavors: Add back GMP- & other deleted flavors
Typo for the one flavor to be allowed instead of forbidden on hana-exclusive hosts.

nova/flavors: Allow gmp_m1946_c128 on hana-exclusive hosts

---

common/inventory-updater/templates/service.yaml
common/inventory-updater/values.yaml
prometheus-exporters/arista-exporter/values.yaml
prometheus-exporters/ipmi-exporter/ci/test-values.yaml
prometheus-exporters/ipmi-exporter/values.yaml

To subclassify alerts, tickets, policy violations, resource consumption,
etc. within the realm of a single support group.
https://github.com/sapcc/helm-charts/blob/65c0a486f5edd9f29c7d0d033222918651aa12a1/common/owner-info/README.md#L42
Without it, some alerts produce non-informative messages, e.g.
> GkVulnerableImagesForFoundation - Vulnerable images in prod deployments of None

Foundation exporters: maintain `owner-info.service`

---

system/unbound/templates/deployment.yaml

As per https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/#sidecar-containers-and-pod-lifecycle
The dnstap container serves a clear supporting role.
Also, if enabled, it should be available before the main unbound container starts.
All in all, it ticks all the boxes as far as sidecar containers described in the above URL go.
The patch basically moves the dnstap container out of the "containers:" section
and into the "initContainers:" one and sets its restartPolicy to Always.

[unbound][dnstap] -- let's run dnstap in a sidecar container

---

openstack/hermes/ci/test-values.yaml
openstack/hermes/templates/logstash-deployment.yaml
openstack/hermes/templates/logstash-service.yaml
openstack/hermes/values.yaml

My proposal:
Disabling linkerd for the namespace and activating it only for logstash, because the namespace activation blocks the helm post-deploy and job pods. At the moment the post-deploy and job pods are using the toolbox image, which has no linkerd support. Switching to an own image is increasing the complexity.

[hermes] activate linkerd only for logstash

---

openstack/neutron/templates/statefulset-network-agent-apod.yaml
openstack/neutron/templates/statefulset-network-agent.yaml

The linux-bridge-agent and dhcp-agent used to share their /var/run/netns directory with each other. This results in two things:
1. The network namespaces are generally not usable in the linux-bridge-agent
2. When the dhcp-agent container restarts, the netns files are still present, even when the namespaces themselves are gone
Generally, only the dhcp-agent interacts with the network namespaces. The netns are managed by it and it also puts interfaces inside the netns. The bridge-agent only puts interfaces provided to it into a bridge. This is possible with and without the knowledge of the netns from the dhcp-agent.
When the dhcp-agent restarts it can no longer recreate the network namespaces, as the namespaces themselves are gone, but the files are still there. It'll try to use these …

[neutron] Don't share netns between dhcp/bridge agent

---

openstack/neutron/values.yaml

vpa is already eneabled in the neutron chart, now we add it for the mariadb dependancy

[ neutron ] Enable vpa for mariadb

---

prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/aggregations/netapp-aggr.yaml
prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/alerts/netappsd.yaml
prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/etc/rest.custom_volume.yaml
prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/etc/rest.iscsi_session.yaml
prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/etc/rest.limited.yaml
prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/templates/_harvest.yaml.tpl
prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/templates/_helpers.tpl
prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/templates/_start-poller.sh.tpl
prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/templates/configmap.yaml
prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/templates/deployment.yaml
prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/templates/secret.yaml
prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/templates/service.yaml
prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/templates/serviceaccount.yaml
prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/values.yaml
prometheus-exporters/netapp-exporter/values.yaml

changes due to netappsd updated to [v2](https://github.com/sapcc/netappsd/tree/v2), where netappsd master controls worker's replica, based on discovered filers.

update harvest: autoscale worker replicas 

---

openstack/swift/templates/etc/_container-server.conf.tpl

Creating this PR to make changes in container-sharder to overwrite the default recon candidate value, which is 5 as of now. Setting value to -1 will help.

Added recon_candidates_limit to overwrite default value of 5

---

common/thanos/Chart.yaml
common/thanos/templates/thanos-objectstore.yaml

when rolling out new compactors they often will be stuck in ContainerCreating with multi-attach volume errors. Since they are not mission critical, we can easily take the short downtime and bring them down first, ensuring a working rollout.

compactor multi attach fixed

---

common/prometheus-server/Chart.yaml
common/prometheus-server/templates/servicemonitors/prometheus.yaml

If a prometheus label exists on a metric, then it should have the form `prometheus="<namespace/prometheus-name>"`, as each prometheus attaches an external label of the same name to each metric. Otherwise duplicate metrics will be created.

common/prometheus-server: align on prometheus label

---

openstack/hermes/templates/etc/_logstash.conf.tpl

The cleanup wasn't happening for the unavailable fields, leading to events going into an "unavailable" index which gives us two different dump indexes. This change removes what looks like an incorrect grouping of the domain_mapping if. Please take a look and validate.

[hermes] fix logstash conf metis cleanup

---

system/prometheus-crds/Chart.yaml
system/prometheus-crds/crds/alertmanagerconfigs.monitoring.coreos.com.yaml
system/prometheus-crds/crds/alertmanagers.monitoring.coreos.com.yaml
system/prometheus-crds/crds/podmonitors.monitoring.coreos.com.yaml
system/prometheus-crds/crds/probes.monitoring.coreos.com.yaml
system/prometheus-crds/crds/prometheusagents.monitoring.coreos.com.yaml
system/prometheus-crds/crds/prometheuses.monitoring.coreos.com.yaml
system/prometheus-crds/crds/prometheusrules.monitoring.coreos.com.yaml
system/prometheus-crds/crds/scrapeconfigs.monitoring.coreos.com.yaml
system/prometheus-crds/crds/servicemonitors.monitoring.coreos.com.yaml
system/prometheus-crds/crds/thanosrulers.monitoring.coreos.com.yaml

everything above v0.70.0 is introducing subresources which are not working with VPA sticking with v0.70.0 for now
see https://github.com/prometheus-operator/prometheus-operator/issues/6291

rollback to last working version

---

openstack/cronus/templates/nebula/_config.yaml.tpl

postfixDNS is not part of the postfix values but has its own layer. Moving it up one level.

Move postfixDNS one level up

---

openstack/nova/alerts/metrics-metal/nova.alerts

This alert was very generic as it checked the CPU consumption of a pod against a hard limit. By now, we have services time and time again that do not see enough load i.e. are idling most of the time. Therefore, this alerts creates seemingly only false notifications by now.
Initially, we introduced this alert to find services that do not react to RPC messages anymore. This hasn't occurred for a long time. If we need this kind of monitoring again, we should look into the RPC ping endpoint available from `oslo.messaging` and maybe into monitoring the number of greenthreads or Lock waiters.
Even though there's no alert left for the "metrics-metal" source, we keep it in place to make it easy to add new alerts again.

[Nova] Resolve OpenstackNovaComputeIdle alert

---

prometheus-exporters/kube-state-metrics-exporter/Chart.yaml
prometheus-exporters/kube-state-metrics-exporter/templates/servicemonitor.yaml

If a prometheus label exists on a metric, then it should have the form `prometheus="<namespace/prometheus-name>"`, as each prometheus attaches an external label of the same name to each metric. Otherwise duplicate metrics will be created.

kube-state-metrics exporter: align on external prometheus label

---

system/kube-monitoring-admin-k3s/Chart.lock
system/kube-monitoring-admin-k3s/Chart.yaml
system/kube-monitoring-kubernikus/Chart.lock
system/kube-monitoring-kubernikus/Chart.yaml
system/kube-monitoring-metal/Chart.lock
system/kube-monitoring-metal/Chart.yaml
system/kube-monitoring-scaleout/Chart.lock
system/kube-monitoring-scaleout/Chart.yaml
system/kube-monitoring-virtual/Chart.lock
system/kube-monitoring-virtual/Chart.yaml

aligns with the prometheus label

kube-monitoring-*: upgrade kube-state-metrics-exporter

---

common/mariadb-galera/CHANGELOG.md
common/mariadb-galera/README.md
common/mariadb-galera/helm/Chart.yaml
common/mariadb-galera/helm/scripts/mariadb-galera/common-functions-extended.sh
common/mariadb-galera/helm/scripts/mariadb-galera/liveness.sh
common/mariadb-galera/helm/scripts/mariadb-galera/readiness.sh
common/mariadb-galera/helm/templates/_helpers.tpl
common/mariadb-galera/helm/templates/configmap-mariadb-my.cnf.yaml
common/mariadb-galera/helm/templates/storageclass.yaml
common/mariadb-galera/helm/tests/01-default-statefulset_test.yaml
common/mariadb-galera/helm/tests/02-services-mariadb-galera_test.yaml
common/mariadb-galera/helm/tests/03-configmap-mariadb_test.yaml
common/mariadb-galera/helm/tests/04-configmap-mariadb-my-cnf_test.yaml
common/mariadb-galera/helm/values.yaml

- to allow migrations from another MariaDB service in the same K8s cluster
- gtidDomainId default set to 10817 to avoid server_id collisions for async replication setups
- gtidDomainId check removed, we want to support ids other than 1 or 2 to avoid async replication problems
- unit test rules updated
- DB logon removed from the liveness check to avoid pod restarts only because the credentials are wrong
- checkdbconnection added to still check if MariaDB provides a usable endpoint

[mariadb-galera] db migration options added

---

system/vmware-monitoring/Chart.yaml
system/vmware-monitoring/values.yaml

This should fix the issue of pod evictions due to an overshooting of ephemeral-storage. It is going to decrease the amount of compactor pods in state Error or ContainerStatusUnknown drastically.

avoid eph storage overutilisation

---

system/vmware-monitoring/templates/collector-configmap.yaml

Following VM metrics have been added - memory_workload_percentage, virtual_disk_average_commands_per_seconds, network_usage_rate_kilobytes_per_second, system_os_uptime_latest, system_powered_on

adding VM metrics

---

openstack/prometheus-openstack/Chart.yaml
openstack/prometheus-openstack/values.yaml
system/infra-monitoring/Chart.yaml
system/infra-monitoring/values.yaml
system/prometheus-infra/Chart.yaml
system/prometheus-infra/values.yaml
system/prometheus-kubernetes/Chart.yaml
system/prometheus-kubernetes/values.yaml
system/storage-monitoring/Chart.yaml
system/storage-monitoring/values.yaml
system/vmware-monitoring/Chart.yaml
system/vmware-monitoring/values.yaml

vpa activated for the leftover Prometheis. The maxAllowed values are giving a reasonable headroom to breathe as of the current workload.

enabling prometheus vpa

---

common/prometheus-server/CHANGELOG.md
common/prometheus-server/Chart.yaml
common/prometheus-server/templates/alerts/_prometheus-thanos-rule.alerts.tpl
common/prometheus-server/templates/alerts/_prometheus.alerts.tpl
common/prometheus-server/values.yaml

VPA alerts must not be installed in any prometheus but (kubernikus and kubernetes) or (the regional thanos ruler).
If thanos alerts are enabled, they are deployed to the thanos ruler.
Independently they still were deployed to prometheus-kubernetes if VPA is set to Auto. Explicitly prohibiting this will not deploy these unfulfillable alerts.

deployment for native vpa alerts

---

openstack/sap-seeds/templates/_flavors_hana_exclusive.tpl

The upcoming CPU reservation change in nova renames these two config vars. The old name should be removed after the rollout.

nova: Rename config vars for CPU reservation

---

system/unbound/templates/deployment.yaml

This patch "reverts" a08f217d82d2cb0286c17989d1a6e165c02d87a3 conditionally during runtime.
The diff between this commit and the one preceding a08f217d82d2cb0286c17989d1a6e165c02d87a3 looks much less busy and is actually understandable:
```diff
diff --git a/system/unbound/templates/deployment.yaml b/system/unbound/templates/deployment.yaml
index bf5c85f83..6f6d3e241 100644
--- a/system/unbound/templates/deployment.yaml
+++ b/system/unbound/templates/deployment.yaml
@@ -95,16 +95,10 @@ spec:
volumeMounts:
- name: unbound-conf
mountPath: /etc/unbound
-{{ if ge (int .Capabilities.KubeVersion.Minor) 29 }}
-      initContainers:
-{{ end }}
{{ if .Values.unbound.dnstap.enabled }}
- name: dnstap
image: {{ required ".Values.global.registryAlternateRegion is missing" …
```

[unbound][dnstap] -- let dnstap run as a sidecar on k8s 1.29 onwards

---

system/metis/Chart.yaml
system/metis/templates/metis-etc-configmap.yaml

The prometheus Ingresses will be 2FA protected soon.
I removed `certPath` and `keyPath`. I'm not sure if the application will fail if they are no longer present. Please vaildate.

metis: move to prometheus service url

---

prometheus-exporters/statsd-exporter/templates/service.yaml

as the introduction of the new phase label might result in partial false alerts until we have rolled out the change to all regions and updated the alerts accordingly, we will simply drop it initially and reenable it later when everything is prepared everywhere

[cc3test] intially drop new phase label

---

openstack/prometheus-openstack/Chart.yaml
openstack/prometheus-openstack/values.yaml

VPA is requesting .2 CPU more, giving way more room to avoid continuous adjustments

moar power for the big guy

---

system/unbound/ci/test-values.yaml
system/unbound/templates/bind-rpz-proxy-config.yaml
system/unbound/templates/bind-rpz-proxy-secrets.yaml
system/unbound/templates/deployment.yaml
system/unbound/values.yaml

Sadly unbound does not support TSIG AXFR to pull RPZ zones.
As a workaround we will be starting a bind container that will be pulling the RPZ zones from the primaries per TSIG AXFR.
Unbound will be pulling those zones from bind "anonymously"

[unbound] -- introducing the bind-rpz-proxy sidecar

---

system/unbound/templates/config.yaml

We're using the Bind server running in the bind-rpz-proxy container as our sole primary.
It will be pulling the RPZ zones from the actual primaries using TSIG AXFR.
Unbound will then pull them anonymously via 127.0.0.1@55353 since unbound does not support TSIG AXFRs.

[unbound] -- introducing rpz filtering

---

common/prometheus-server/CHANGELOG.md
common/prometheus-server/Chart.yaml
common/prometheus-server/values.yaml

this is fixed with kubernetes>=1.28.5, but we are not there yet furthermore this is reasonable for scheduling

ephemeral requests to avoid pod eviction

---

system/unbound/templates/config.yaml

We can only declare a variable once.
If we want to change its value we use a simple assignment operator.

[unbound] -- fixed the module-config construction

---

system/unbound/Chart.yaml
system/unbound/templates/bind-rpz-proxy-secrets.yaml
system/unbound/templates/etc/_unbound.bind-rpz-proxy.named.conf.rpz.tpl
system/unbound/templates/etc/_unbound.bind-rpz-proxy.rndc.key.tpl
system/unbound/templates/etc/_unbound.bind-rpz-proxy.tsig.key.tpl

Apparently `stringData:` is broken by design [1]. We should avoid it.
The issue is that removing a stringData key will not remove it from the k8s secret object. It will just get reset to an empty string.
Might be a security issue to some extend.
But, also, using such a secret as a volume will result in orphaned empty files. That *might* break easily offended software.
Also, bumped the chart's `version` and `appVersion`.
[1] https://github.com/kubernetes/kubernetes/issues/89938#issuecomment-1033085353

[unbound][bind-rpz-proxy] -- move the secrets from stringData to data

---

common/rabbitmq/Chart.yaml
common/rabbitmq/templates/bin/_rabbitmq-start.tpl
common/rabbitmq/templates/deployment.yaml
common/rabbitmq/templates/statefulset.yaml

couple with liveness initial delay
In lab regions, with less cpu/memory resource power, the default
60 seconds are sometimes not long enough to bring up the service.

[rabbitmq] make start wait timeout configurable

---

system/unbound/templates/etc/_unbound.bind-rpz-proxy.named.conf.rpz.tpl
system/unbound/templates/etc/_unbound.bind-rpz-proxy.rndc.key.tpl
system/unbound/templates/etc/_unbound.bind-rpz-proxy.tsig.key.tpl

double quoting was breaking the secrets-injector
It was resulting into something like:
```
key "{{ resolve \"vault+kvv2:///secrets/path/to/keyname\" }}" {
...
}
```
The secrets-injector was, understandingly, not happy with that.

[unbound][bind-rpz-proxy] -- secrets-injector double quoting 

---

system/audit-logs/Chart.lock
system/audit-logs/Chart.yaml
system/audit-logs/values.yaml
system/audit-logs/vendor/audit-poller/Chart.yaml
system/audit-logs/vendor/audit-poller/values.yaml

This bumps the fluentD, logstash and audit-poller images.

chore(audit-poller): bump image versions

---

openstack/manila/values.yaml

Castellum needs to skip resizing a share  if it is snapmirror target.

[manila] add snapmirror label to openstack_manila_shares_size_gauge

---

system/unbound/templates/bind-rpz-proxy-config.yaml
system/unbound/templates/bind-rpz-proxy-secrets.yaml
system/unbound/templates/deployment.yaml

Apparently we cannot share one configMap/secret across multiple releases.
We will have to create dedicated configMaps/secrets for each release we have. IOW one for unbound1 and one for unbound2.
Otherwise the first release will get deployed but the second one will fail with:
```
Error: UPGRADE FAILED: Unable to continue with update: Secret "bind-rpz-proxy-secrets" in namespace "dns-recursor" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "unbound2": current value is "unbound1"
```

[unbound][bind-rpz-proxy] -- dedicated configMap/secret per release

---

prometheus-exporters/openstack-exporter/alerts/cinder.alerts

- Ensure that the datastore count of all shards is taken into consideration, not just the free percentage
- Simplify the expression and improve readability

[openstack-exporter] Revise CinderShardFreeSpace alerts

---

openstack/sap-seeds/templates/_flavors_hana_exclusive.tpl

Needed for Limes' upcoming 2024 quota revamp.
Now also for hana-exclusive regions.

nova/flavors: Separate instance quota for hana-flavors everywhere

---

openstack/sap-seeds/templates/_flavors_deleted.tpl

Followup to #6098. We do in fact have prices for these specific 4 flavors, so we can put them as separate instance quotas without causing problems for Billing.
For the other flavors, Frank has tentatively agreed to do another push to get the customers off them.
I'm also defining a new extra spec for Limes here, which I will use to keep the capacity calculation from reporting more capacity on these flavors than absolutely necessary.

add quota:separate etc. to selected old HANA flavors

---

openstack/keystone/templates/etc/_policy.yaml.tpl

When `.Values.tempest.enabled` evaluates to true:
```diff
-     "identity:delete_project": "(rule:cloud_admin or (rule:admin_required and project_id:%(project_id)s)) and http://prodel.prodel.svc/check-delete_project/%(project_id)s"
+     "identity:delete_project": "(rule:cloud_admin or (rule:admin_required and project_id:%(project_id)s)) and (domain_id:abcdefghabcdefghabcdefghabcdefgh or http://prodel.prodel.svc/check-delete_project/%(project_id)s)"
```
When `.Values.tempest.enabled` evaluates to false:
```diff
-     "identity:delete_project": "(rule:cloud_admin or (rule:admin_required and project_id:%(project_id)s)) and http://prodel.prodel.svc/check-delete_project/%(project_id)s"
+     "identity:delete_project": "(rule:cloud_admin or (rule:admin_required and project_id:%(project_id)s)) …
```

Do not require Prodel check in Tempest domains

---

openstack/sap-seeds/templates/_flavors_hana_exclusive.tpl

VMs may not reserve 100% of the CPUs of an ESXI host and so we make a
safety offset. 5% is a guess.

nova/flavors: Only reserve 95% of HANA VMs' CPUs

---

common/rabbitmq/Chart.yaml
common/rabbitmq/templates/deployment.yaml
common/rabbitmq/templates/statefulset.yaml

useful to not have to specify the container name for
`kubectl logs` or `kubectl exec`
@Kuckkuck fyi

[rabbitmq] add default container annotation

---

common/prometheus-monitors/Changelog.md
common/prometheus-monitors/Chart.yaml
common/prometheus-monitors/README.md
common/prometheus-monitors/templates/_helpers.tpl
common/prometheus-monitors/templates/podmonitor.yaml
common/prometheus-monitors/templates/servicemonitor.yaml
common/prometheus-monitors/values.yaml

Currently this helper chart gives some presets for adding very simple Pod|ServiceMonitors.
This change adds the option to add more than one endpoint to be scraped. In order to keep this compatible with existing usages the new value `additionalEndpoints` is introduced.

feat(prometheus-monitors): allow configuration of additional targets

---

openstack/utils/Chart.yaml
openstack/utils/templates/_coordination.tpl

to not have the injected annotations show up in helm diff each time

[utils] add owner info explicitly to coordination pvc

---

openstack/manila/alerts/openstack/rabbitmq.alerts

If a service is disabled we don't want to get false positives
on queuing messages.

[manila] take service status into account for rabbit alerts

---

common/rabbitmq/CHANGELOG.md
common/rabbitmq/Chart.yaml
common/rabbitmq/templates/deployment.yaml
common/rabbitmq/templates/pvc.yaml
common/rabbitmq/templates/statefulset.yaml

`fsGroupChangePolicy: "OnRootMismatch"`does not work for NFS mounts
(also see kubernetes/examples/issues/260)

[rabbitmq] fix permissions if persistence is enabled

---

openstack/glance/ci/test-values.yaml
openstack/glance/templates/deployment.yaml
openstack/glance/templates/etc/_glance-api.conf.tpl
openstack/glance/templates/etc/_glance-registry.conf.tpl
openstack/glance/templates/etc/_secrets.conf.tpl
openstack/glance/templates/etc/_swift-store.conf.tpl
openstack/glance/templates/migration-job.yaml
openstack/glance/templates/secrets.yaml

- Secrets config will be projected into /etc/glance/glance.conf.d/

[glance] move configuration with credentials into own secrets

---

system/vmware-monitoring/templates/collector-configmap.yaml

- Include the compute status disabled and decommissioning key from the OpenStack Nova traits in the vrops-exporter-collector-config (ClusterPropertiesCollector) for generating the Prometheus metrics

[vmware-monitoring] Expose compute status disabled and decommissioning information

---

openstack/neutron/Chart.lock
openstack/neutron/Chart.yaml
openstack/neutron/templates/_helper.tpl
openstack/neutron/templates/job-migration.yaml

We bump the `utils` chart and switch to "utils.script.job_finished_hook" to include the commands to stop `proxysql` and linkerd at the end of our Jobs.

[neutron] Support linkderd in Jobs

---

openstack/barbican/templates/api-deployment.yaml
openstack/barbican/templates/etc-configmap.yaml
openstack/barbican/templates/etc/_barbican.conf.tpl
openstack/barbican/templates/etc/_secrets.conf.tpl
openstack/barbican/templates/migration-job.yaml
openstack/barbican/templates/secrets.yaml

- Secrets config will be projected into /etc/barbican/barbican.conf.d/
- And /luna/barbican_lunaclient.sh

[barbican] move configuration with credentials into own secrets

---

openstack/placement/Chart.lock
openstack/placement/Chart.yaml
openstack/placement/templates/db-migrate-job.yaml
openstack/placement/templates/db-online-migrate-job.yaml

We bump the `utils` chart and switch to "utils.script.job_finished_hook" to include the commands to stop `proxysql` and `linkerd` at the end of our Jobs.
With updating `utils`, we also get the trust-bundle only overwriting "/etc/ssl/certs/ca-certificates.crt" instead of all of "/etc/ssl/certs".

[Placement] Support linkerd in Jobs

---

openstack/cinder/values.yaml

This patch enables linkerd for cinder in all regions.

[Cinder] Enable linkerd everywhere

---

openstack/neutron/templates/etc/_ml2-conf-aci.ini.tpl
openstack/neutron/values.yaml

To make sure only one worker in a pod syncs the ACI allocations we now have a file that is used to check if anyone else in that pod (i.e. with the same config) did already sync the allocations table.

[neutron] Configure ACI sync allocations done marker

---

openstack/designate-nanny/templates/deployment.yaml
openstack/designate-nanny/templates/secret.yaml
openstack/designate/ci/test-values.yaml
openstack/designate/templates/seeds.yaml

[designate-nanny] add username to secret, change ref for seeder
By adding the username to the secret, rotation of username and password become an atomic operation, as both are bundled in a secret.
In addition the seeder gets its own field for the initial password, because it will not be able to resolve the new injector reference yet.

[designate-nanny] add username to secret, for reliable rotation

---

prometheus-exporters/netapp-exporter/charts/netapp-cap-exporter/aggregations/netapp-castellum.rules

In the aggregation rule `netapp_volume_exclusion_reason_offline`, we are currently reporting a share as `offline` if ANY of its volume is `offline`. In the DR or migration scenario, there can be multiple volumes for a share, and one of its volumes has `online` state and the others `offline`. We should drop such shares and allow them resizable by Castellum. Using the `unless` operator, we query metrics for `online` volumes on the right side and drop them if their labels (`share_id`, `project_id`) matched to the left.

[netapp] fix metrics for offline volumes

---

openstack/cinder/templates/type-seeds.yaml

This patch updates the cinder volume type seeds
to match what is in production.  There were several missing items for each type.

[Cinder] Update type-seeds

---

openstack/cinder/Chart.lock
openstack/cinder/Chart.yaml
openstack/cinder/templates/migration-job.yaml

We bump the `utils` chart and switch to "utils.script.job_finished_hook" to include the commands to stop `proxysql` and `linkerd` at the end of our Jobs.
With updating `utils`, we also get explicit owner-info on the coordination PVC.

[cinder] Support linkerd in Jobs

---

openstack/cc3test/Chart.yaml
openstack/cc3test/alerts/ccloud-limes.alerts

As discussed in Slack: https://convergedcloud.slack.com/archives/CE5NDBQDC/p1711359842260729

cc3test: do not alert Limes when Keystone is down

---

common/rabbitmq/CHANGELOG.md
common/rabbitmq/Chart.yaml
common/rabbitmq/values.yaml

Update the default image of rabbitMQ from version 3.11.15-management to version 3.13.0-management.
Change-Id: I503dc55b693d1843bfc1f2a5abea7f3f4d88654a

[rabbitmq] update image to 3.13.0-management

---

openstack/ironic/ci/test-values.yaml
openstack/ironic/templates/seed.yaml
openstack/neutron/templates/etc/_ironic_neutron_agent.ini.tpl
openstack/nova/templates/etc/_nova-compute-ironic.conf.tpl

Reverts sapcc/helm-charts#6200
This breaks Nova's helm-chart as the secrets are not in line with this change.

Revert "[ironic] harmonize ironic service user/password"

---

openstack/nova/Chart.lock
openstack/nova/Chart.yaml

We bump the chart to enable linkerd in it. With bumping the chart, we also move the config into a Secret and remove the prometheus annotations that would lead to double scraping with linkerd adding a second container.

[Nova] Bump mysql_metrics chart for linkerd

---

openstack/nova/templates/hypervisors/_ironic-deployment.yaml.tpl

When moving secrets into Secrets we missed to add cell-specific config to nova-compute-ironic pods. This lead to the driver not starting up because it couldn't reach rabbitmq.

[Nova] Fix ironic pods not having cell config

---

openstack/nova/templates/api-metadata-deployment.yaml

`nova-api-metadata` uses the same `api-paste.ini` as `nova-api` and thus requires the `nova_audit_map.yaml` file to be present.
In theory, we do not need a lot of the stuff in `api-paste.ini` for `nova-api-metadata` as the latter isn't really customer-facing. This could be changed in a follow-up. For now, we want things to work again.

[Nova] Add back nova_audit_map.yaml to nova-api-metadata

---

openstack/nova/templates/cell2-conductor-deployment.yaml

With moving to a projected configmap we accidentally got rid of `statsd-exporter.yaml`. We now change the cell2 conductor to read the file from `statsd-etc` volume like the cell1 conductor does.

[Nova] Cell2 conductor needs statsd-exporter.yaml

---

openstack/nova/templates/etc/_nova-scheduler.conf.tpl

For regions where nova_bigvm_enabled = true, HANA flavors should be identified by looking at the flavor.memory_mb instead of the trait:CUSTOM_HANA_EXCLUSIVE_HOST extra spec.

[nova] set hana_detection_strategy for bigvm-enabled regions

---

common/rabbitmq/Chart.yaml
common/rabbitmq/templates/_helpers.tpl
common/rabbitmq_cluster/Chart.yaml
common/rabbitmq_cluster/templates/_helpers.tpl

- because it is not compatible with the "new" secrets-injector
- urlquery will have to be applied to individual secrets inside vault references
- also bump charts

[rabbitmq][rabbitmq_cluster] remove urlquery from herlper templates

---

openstack/utils/Chart.yaml
openstack/utils/templates/_hosts.tpl
openstack/utils/templates/_ini_sections.tpl

- because it is not compatible with the "new" secrets-injector
- urlquery will have to be applied to individual secrets inside vault references
- also bump chart

[utils] remove urlquery from templates and helper scripts

---

openstack/cinder/Chart.lock
openstack/cinder/Chart.yaml

This patch updates the cinder chart for mysql metric to 0.3.2 for linkerd support

[Cinder] Update mysql metric chart

---

openstack/neutron/Chart.lock
openstack/neutron/Chart.yaml

Bumping mysql_metrics chart for linkerd support 
Chart bump includes:
* mysql_metrics config moving to secret
* If the port is named 'metrics' the port annotation is not needed
and would only lead to all containers being scraped.
But we e.g. don't want this for the recently added linkerd container.

[neutron] Bump mysql_metrics chart for linkerd

---

openstack/nova/templates/hypervisors/hypervisors-vmware-configmap-vct.yaml
openstack/nova/templates/hypervisors/hypervisors-vmware-deployment-vct.yaml
openstack/nova/templates/hypervisors/hypervisors-vmware-secret-vct.yaml

Since we have to move out all passwords into Secret objects, the vcenter-operator-provided vCenter password needs to be moved out of the ConfigMap template and into a new Secret template.

[Nova] Provide vCenter username and password via Secret

---

common/mariadb/Chart.yaml
common/mariadb/templates/backup-verify-deploy.yaml
common/mariadb/templates/configuredb-configmap.yaml
common/mariadb/templates/pre-change-job.yaml

add helm hooks to configurator script configmap to be sure that teh configmap is created and updated befor triggering the job.
upgrade order :
1. initdb_secret
2. configuredb_configmap
3. pre-chage-job 
adapt backup verify deployment to use secrets.

[mariadb] add helmhooks to fix upgrade order

---

openstack/octavia/Chart.lock
openstack/octavia/Chart.yaml
openstack/octavia/templates/proxysql-configmap.yaml
openstack/octavia/templates/proxysql-secret.yaml
openstack/octavia/values.yaml

-- rabbitmq to version 0.6.9 (rabbitmq version 3.13.0)
- switch to set the new mariadb values initdb_secret instead of initdb_configmaps
- update rabbitmq to 3.13.0-management

[Octavia][mariadb][rabbitmq][utils] bump up mariadb,rabbitmq, utils for Octavia

---

openstack/cinder/Chart.lock
openstack/cinder/Chart.yaml
openstack/cinder/templates/proxysql-configmap.yaml
openstack/cinder/templates/proxysql-secret.yaml
openstack/cinder/values.yaml

Bump up subcharts :
-- rabbitmq to version 0.6.10 (rabbitmq version 3.13.0)
-- mariadb to version 0.9.1
Switch to set the new mariadb values initdb_secret instead of initdb_configmaps
Replace proxysql config map with proxysql secret
Activate detailed metrics

[cinder][mariadb][rabbitmq][utils] Bump up mariadb,rabbitmq, utils for Cinder

---

openstack/ironic/Chart.lock
openstack/ironic/Chart.yaml
openstack/ironic/templates/proxysql-configmap.yaml
openstack/ironic/templates/proxysql-secret.yaml
openstack/ironic/values.yaml

-- rabbitmq to version 0.6.10 (rabbitmq version 3.13.0)
- switch to set the new mariadb values initdb_secret instead of initdb_configmaps
- update rabbitmq to 3.13.0-management

[ironic][mariadb][rabbitmq][utils] bump up mariadb,rabbitmq, utils for ironic

---

openstack/octavia/Chart.lock
openstack/octavia/Chart.yaml

update dependencies of octavia to rabbitmq 0.6.10 which uses data field in the secret instead of StringData.

[octavia][rabbitmq] bumpup rabbitmq to version 0.6.10

---

openstack/domain-seeds/templates/domain-default-seed.yaml
openstack/domain-seeds/values.yaml

- "docker-registry" and "quay" have been obsoleted by Keppel years ago
- "gaas" is not used anymore after #6283
Please merge together with the respective secrets PR.

domain-seeds: remove obsolete user accounts

---

openstack/utils/Chart.yaml
openstack/utils/templates/_proxysql_secret.yaml.tpl

add annotation to proxysql secret to set helm pre upgrade hook weit of -10 to proxysql secret, that to force the creation in case of a job needs the secret to be created before running.
option activated by set value `proxysql.forceSecretCreation` to true

[utils] add helm pre-upgrade weight to proxysql secret

---

openstack/neutron/Chart.lock
openstack/neutron/Chart.yaml
openstack/neutron/templates/proxysql-configmap.yaml
openstack/neutron/templates/proxysql-secret.yaml
openstack/neutron/values.yaml

-- rabbitmq to version 0.6.10 (rabbitmq version 3.13.0)
- switch to set the new mariadb values initdb_secret instead of initdb_configmaps
- update rabbitmq to 3.13.0-management

[neutron][mariadb][rabbitmq][utils] bump up mariadb,rabbitmq, utils for neutron

---

openstack/octavia/Chart.lock
openstack/octavia/Chart.yaml
openstack/octavia/templates/octavia-migration-job.yaml

- bump up to use utils v0.16.1
- force creating proxysql secret before starting the migration job
- add an or condition to configure proxysql in the job if any values are set in vaules in proxysql map, that to fix the first run issue caused by the lookup function on K8S secret which is not created on K8S side while helm generating the templates

[octavia] bump utils to 0.16.1, fix migration job

---

openstack/neutron/values.yaml

When reporting segment usage we only need to report usage for hostgroups that are still in use. Since the aci sync allocation rewrite[0], we do a proper allocation table cleanup, but we still keep segments in the table that are in use, so these decommissioned hostgroups look like 100% full.
Therefore we now only look at currently active hostgroups by filtering for physical_networks mentioned in the ml2_vlan_allocations, which is also kept up to date, but does not keep orphans.
[0] https://github.com/sapcc/networking-aci/commit/b9294849093932d8f04555636290458fa60421ab

[neutron] Disregard decommissioned segments in alert

---

openstack/octavia/values.yaml

octavia helmchart upgrade failed after switching to secret because the migration job creates the proxysql sidecar only if it found proxysql secret which is not created at the first run.
Ignoring that will cause octavia configuration to be build with proxysql sockets in the connection string 
but without creating the sidecar in the first run which causing the migration job to fail and prevents the upgrade.
Change-Id: Ic37a0149a466cd8a8ad999adb8d56e23a05694ff

[octavia] force secret creation of proxysql

---

openstack/nova/templates/hypervisors/hypervisors-vmware-secret-vct.yaml

The previous version contained the indentation also in the INI-style config file - which is not allowed in INIs. Therefore, we now have to make it a bit uglier by dedenting the content section.

[Nova] Fix moving vCenter secrets to Secret

---

openstack/nova/Chart.lock
openstack/nova/Chart.yaml
openstack/nova/templates/proxysql-configmap.yaml
openstack/nova/templates/proxysql-secret.yaml
openstack/nova/values.yaml

-- rabbitmq to version 0.6.9 (rabbitmq version 3.13.0) 
- switch to set the new mariadb values initdb_secret instead of initdb_configmaps 
- activate detailed metrics

[nova][mariadb][rabbitmq][utils] bump up mariadb,rabbitmq, utils for nova

---

common/rabbitmq/Chart.yaml
common/rabbitmq/templates/_helpers.tpl
common/rabbitmq/templates/bin/_rabbitmq-start.tpl

add a condition to not escape vault injector links 
use the same macro to create guest user

[rabbitmq] fix escaping for secret-injector links

---

openstack/cinder/templates/vcenter_datacenter_cinder_secret.yaml

We missed to encode the `data` values to base64. Since we know how to do it from Nova's helm-chart, we mimic that approach even though there might be a better one by teaching the `vcenter-operator` to expose `textwrap.dedent()` to templates.

[Cinder] Fix VCenterTemplate Secret base64 encoding

---

openstack/cinder/templates/volumes/_volume-deployment.yaml.tpl

We used the wrong way to access `Template.BasePath` and thus helm couldn't get that value and failed.

[Cinder] Fix rendering "volume_deployment"

---

common/pgbackup/Chart.yaml
common/pgbackup/ci/test-values.yaml
common/pgbackup/templates/deployment.yaml
common/pgbackup/templates/secret.yaml
common/pgbackup/values.yaml

Using the existing `global.region` value, as well as the new `global.vaultBaseURL` value, and by just always using the public Keystone endpoint, this removes the need to configure anything related to Swift authentication at all.

pgbackup: remove configuration for Swift credentials

---

openstack/octavia/templates/secrets-worker.yaml

Change scope back to global by using `{{- with $ }}`
This is a follow-up to #6127

[octavia] Fix worker secret: range changes scope

---

common/pgbackup/Chart.yaml
common/pgbackup/templates/deployment.yaml
common/pgmetrics/Chart.yaml
common/pgmetrics/templates/deployment.yaml
common/postgresql-ng/Chart.yaml
common/postgresql-ng/templates/deployment.yaml

These charts (or their users) declare default resource requests that are almost always too large for the labs and thus at best pointless (if overridden by the VPA) or actively harmful (if they impact scheduling).

common/postgresql-ng et al: never put explicit resource requests on labs

---

openstack/neutron/templates/deployment-cc-fabric-agent.yaml
openstack/neutron/templates/etc/_ml2-conf-cc-fabric.ini.tpl
openstack/neutron/templates/secret-cc-fabric.yaml

With https://github.com/sapcc/networking-ccloud/pull/139 merged, the
driver supports reading credentials from a dedicated file. We use this
to pass the credentials along to the container as a secret, rather than
a configmap.

[neutron][cc-fabric] Pass switch credentials as secret to deployment

---

openstack/ironic/templates/_conductor-configmap-secret.yaml.tpl
openstack/ironic/templates/_conductor-deployment.yaml.tpl
openstack/ironic/templates/api-deployment.yaml
openstack/ironic/templates/db-migration-job.yaml
openstack/ironic/templates/etc/_inspector_secrets.conf.tpl
openstack/ironic/templates/etc/_ironic.conf.tpl
openstack/ironic/templates/etc/_ironic_inspector.conf.tpl
openstack/ironic/templates/etc/_secrets.conf.tpl
openstack/ironic/templates/inspector-db-migration-job.yaml
openstack/ironic/templates/inspector-deployment.yaml
openstack/ironic/templates/secrets.yaml

- Common secrets will be projected into /etc/ironic/ironic.conf.d/ and /etc/ironic-inspector/ironic-inspector.conf.d/

[ironic] move configuration with credentials into own secrets

---

openstack/neutron/templates/statefulset-network-agent-apod.yaml
openstack/neutron/values.yaml

The network agents are build, one deployment per apod from
$.Values.global.apods. This implements a temporary possibility to
disable an apod without having to touch the global variables, just for
the neutron deployment.

[neutron] Allow to disable network agent locally

---

openstack/manila/Chart.lock
openstack/manila/Chart.yaml
openstack/manila/templates/migration-job.yaml
openstack/manila/templates/proxysql-configmap.yaml
openstack/manila/templates/proxysql-secret.yaml
openstack/manila/values.yaml

Bump up subcharts :
-- rabbitmq to version 0.6.10 (rabbitmq version 3.13.0)
Switch to set the new mariadb values initdb_secret instead of initdb_configmaps
Replace proxysql config map with proxysql secret
Activate detailed metrics

[manila][mariadb][rabbitmq][utils] Bump up mariadb,rabbitmq, utils for Manila

---

openstack/cinder/templates/vcenter_datacenter_cinder_deployment.yaml

We accidentally used the non-existent `--config-map` instead of `--config-file` as option to `openstack-agent-liveness`.

[Cinder] Fix cinder-volume livenessProbe command

---

openstack/keystone/templates/bin/_bootstrap.tpl
openstack/keystone/templates/bin/_db-sync.tpl
openstack/keystone/templates/bin/_repair_assignments.tpl
openstack/keystone/templates/configmap-bin.yaml
openstack/keystone/templates/deployment-api.yaml
openstack/keystone/templates/deployment-cron.yaml
openstack/keystone/templates/etc/_keystone.conf.tpl
openstack/keystone/templates/etc/_secrets.conf.tpl
openstack/keystone/templates/job-bootstrap.yaml
openstack/keystone/templates/job-migration.yaml
openstack/keystone/templates/secret-bin.yaml
openstack/keystone/templates/secrets.yaml

- Secrets config will be projected into /etc/keystone/keystone.conf.d/
- Urlquery cannot be used in templates, should be used in vault references

[keystone] move configuration with credentials into own secrets

---

openstack/cinder/Chart.lock
openstack/cinder/Chart.yaml
openstack/cinder/values.yaml

This user provides passwordless access to the DB from localhost, so we can administer the DB without having to read and rotate a secret.
With bumping the mariadb chart we also get some fixes regarding Secrets in.

[Cinder] Enable ccroot user for mariadb

---

openstack/nova/Chart.lock
openstack/nova/Chart.yaml
openstack/nova/values.yaml

This user provides passwordless access to the DB from localhost, so we can administer the DB without having to read and rotate a secret.
With bumping the mariadb chart we also get some fixes regarding Secrets in.

[Nova] Enable ccroot user for mariadb

---

openstack/archer/Chart.yaml
openstack/archer/templates/deployment-ni.yaml

With the migration to k8s secrets, the rabbitmq transport_url is no longer part of neutron.conf. Therefore the neutron password needs to be mounted as well.

[Archer] Mount Neutron RabbitMQ Password

---

openstack/ironic/values.yaml

This user provides passwordless access to the DB from localhost, so we
can administer the DB without having to read and rotate a secret.
This was introduced in version 0.10.0 from the mariadb chart

ironic: enable ccroot user for mariadb

---

openstack/tempest/octavia-tempest/templates/bin/_tempest-start-and-cleanup.sh.tpl
openstack/tempest/octavia-tempest/values.yaml
openstack/tempest/tempest-base/templates/_tempest-pod.yaml.tpl

This PR adds provisioning status reset for stuck Octavia load balancers with the direct query to MariaDB.

[tempest][octavia] Add status reset for octavia-tempest.

---

openstack/archer/Chart.lock
openstack/archer/Chart.yaml
openstack/archer/ci/test-values.yaml
openstack/archer/templates/configmap-f5.yaml
openstack/archer/templates/deployment-f5.yaml
openstack/archer/templates/deployment-ni.yaml
openstack/archer/templates/deployment.yaml
openstack/archer/templates/etc/_archer.ini.tpl
openstack/archer/templates/secret.yaml
openstack/archer/templates/seed.yaml
openstack/archer/values.yaml

This PR switches archer to secrets injector.
Needs to be rolled out along with https://github.wdf.sap.corp/cc/secrets/pull/14154

[archer] bump dependencies, switch to secrets-injector

---

openstack/octavia/templates/secrets.yaml

The migration job runs as a pre-upgrade hook and it needs the octavia-secrets secret. Therefore this secret needs to be created at pre-upgrade hook time as well, and with a lower weight than the migration job, so that it is guaranteed to exist before the migration job runs.

[octavia] Create secret as pre-upgrade hook (for migration job)

---

openstack/octavia/templates/secrets.yaml

We tried to make the `octavia-secrets` Secret part of the pre-upgrade phase so the migration job can run as pre-upgrade hook in ce8cfe40fbe99c76de1bfe1d93f05ee670d88c86. This didn't work, because we put in the annotations as labels instead.

[octavia] Fix creating secret as pre-upgrade hook

---

openstack/manila/values.yaml

This user provides passwordless access to the DB from localhost, so we
can administer the DB without having to read and rotate a secret.

[manila] enable mariadb ccroot user

---

openstack/ironic/templates/_conductor-deployment.yaml.tpl

We used the wrong way to access `Template.BasePath` and thus helm couldn't get that value and failed.

[Ironic] Fix rendering "ironic_conductor_deployment"

---

openstack/ironic/templates/secrets.yaml

We have the same issue as octavia in #6377 and #6382 and copy their
homework.
The migration job runs as pre-upgrade hook and it needs the
ironic-secret secret. Therefore the secret needs to be available during
the pre-upgrade hook time. It needs to have a lower weight than the
migration job, so that is executed before the migration job.
This needs to happen as an annotation

[ironic] fix creating secrets as pre-upgrade hook

---

openstack/octavia/templates/etc/_octavia-worker.conf.tpl
openstack/octavia/templates/etc/_octavia.conf.tpl
openstack/octavia/templates/etc/_secrets-worker.conf.tpl
openstack/octavia/templates/etc/_secrets.conf.tpl
openstack/octavia/templates/octavia-worker-deployment.yaml

Several values are still not in secrets and so cannot be interpolated by the secrets-injector. Those are:
- `password` in the `[service_auth]` group, making Octavia unable to authenticate
- `vcmp_urls` in the `[networking]` group
Also: A few secrets volume mounts were missing

Octavia: Move missing values to secrets

---

prometheus-exporters/octobus-query-exporter/Chart.lock
prometheus-exporters/octobus-query-exporter/Chart.yaml
prometheus-exporters/octobus-query-exporter/vendor/octobus-query-exporter-global/Chart.yaml
prometheus-exporters/octobus-query-exporter/vendor/octobus-query-exporter-global/templates/_helper.tpl
prometheus-exporters/octobus-query-exporter/vendor/octobus-query-exporter-global/templates/secret.yaml

see helm docs:
An important detail to keep in mind when naming templates: template names are global. If you declare two templates with the same name, whichever one is loaded last will be the one used. Because templates in subcharts are compiled together with top-level templates, you should be careful to name your templates with chart-specific names.

fix(ocb-qe): named template with unique names

---

openstack/ironic/templates/_conductor-configmap.yaml.tpl
openstack/ironic/templates/_conductor-deployment.yaml.tpl

The ipxe config does not contain any secrets but handling it as a
k8s secret breaks helm as it will interpret jinja syntax that is
supposed to be interpreted by ironic later on.

[ironic] change ipxe back to configmap

---

openstack/ironic/templates/etc/_ipxe_config.template.tpl

The `ipxe_config.template` is a jinja2 template interpreted by Ironic code. Since both Helm and jinja2 use `{{` and `}}` as deliminator for variables in the template, helm tries to interpret the jinja2 template. To prohibit that, we "escaped" the `{{` and `}}` by telling helm to put strings of `{{` and `}}` into the template.
With us not using much helm templating in this file, there's a better readable way to do it: raw strings. We put basically the whole file into a raw string, only ending the raw string where we need actual templating from helm, starting it again right afterwards.
See also https://go.dev/ref/spec#String_literals and https://pkg.go.dev/text/template#hdr-Examples

[Ironic] Put the ipxe_config.template in a raw string

---

openstack/octavia/templates/etc/_secrets.conf.tpl

`.Values.global.user_suffix` is unset, so remove it

[octavia] Fix: Remove user_suffix which expands to <no value>

---

openstack/octavia/templates/octavia-worker-deployment.yaml
openstack/octavia/values.yaml

This PR removes `driver-agent` from Octavia because we disable it in https://github.com/sapcc/octavia-f5-provider-driver/pull/251

[octavia] Remove driver-agent side-car because we do not use it anymore.

---

openstack/octavia/values.yaml

The second selection (after UNION) is missing a field to compensate for the loadbalancer_project field introduced in #6233

[octavia] Fix pending LBs metric

---

openstack/nannies/templates/cinder-nanny-deployment.yaml

Cinder moved their secrets and by that also their DB connection URL into a Secret named `cinder-secrets` under the key `secrets.conf`. This is usually mounted in `/etc/cinder/cinder.conf.d/secrets.conf`. We update the cinder-nanny to mount that Secret into the same place. This should make any cinder-manage commands work again, but since our custom code relies on a different config file, we have to update it, too.

[nannies] Mount DB secret in cinder-nanny

---

openstack/nova/templates/seed.yaml

For switching nova-compute-ironic to use the `nova` user instead of the `ironic` user, there are 2 more role assignments which are missing from the `nova` user:
* cloud_image_admin
* cloud_objectstore_admin

[nova] seed roles required by nova-compute-ironic

---

common/mariadb-galera/CHANGELOG.md
common/mariadb-galera/README.md
common/mariadb-galera/helm/Chart.yaml
common/mariadb-galera/helm/README.md.gotmpl
common/mariadb-galera/helm/scripts/backup/kopia/entrypoint-backup.sh
common/mariadb-galera/helm/scripts/haproxy/haproxy.cfg
common/mariadb-galera/helm/scripts/mariadb-galera/common-functions-extended.sh
common/mariadb-galera/helm/scripts/mariadb-galera/entrypoint-galera.sh
common/mariadb-galera/helm/scripts/mariadb-galera/pre-stop-hook.sh
common/mariadb-galera/helm/templates/_helpers.tpl
common/mariadb-galera/helm/templates/alerts/_kubernetes.tpl
common/mariadb-galera/helm/templates/alerts/_mariadb.tpl
common/mariadb-galera/helm/templates/configmap-mariadb-job.yaml
common/mariadb-galera/helm/templates/configmap-mariadb-my.cnf.yaml
common/mariadb-galera/helm/templates/configmap-mariadb.yaml
common/mariadb-galera/helm/templates/configmap-proxysql.conf.yaml
common/mariadb-galera/helm/templates/job-mariadb-config.yaml
common/mariadb-galera/helm/templates/poddisruptionbudget.yaml
common/mariadb-galera/helm/templates/secrets.yaml
common/mariadb-galera/helm/templates/service.yaml
common/mariadb-galera/helm/templates/statefulset-mariadb.yaml
common/mariadb-galera/helm/templates/statefulset-proxysql.yaml
common/mariadb-galera/helm/tests/01-default-statefulset_test.yaml
common/mariadb-galera/helm/tests/02-services-mariadb-galera_test.yaml
common/mariadb-galera/helm/tests/04-configmap-mariadb-my-cnf_test.yaml
common/mariadb-galera/helm/values.yaml

- gmcast.segment per region to avoid unnecessary replication traffic between regions
- externalIPs for Galera backend service if rolled out as internal ClusterIP service
- loadBalancerIP support added for the externalIP
- externalIPs are required for Galera communication outside of the Kubernetes cluster
- unit tests for the service and the my.cnf configmap added
- global.db_region support added to support subchart setups
- getNetworkPort function fixed
- create backup credentials only if backup is enabled
- several Galera network options added to be able to tweak WAN connections
- limit to one pod per region if multiRegion is enabled
- multiRegion.bootstrap option added for manual bootstrapping after complete shutdowns
- documentation extended with multiRegion infos
- changelog updated
- …

[mariadb-galera] multi region option added for MariaDB Galera

---

openstack/neutron/templates/secret-neutron-cisco-ucs-bm.yaml
openstack/neutron/values.yaml

Without the if we create a secret which might just contain a newline, which the vault-injector currently doesn't like. The secret is only used by the ucsm deployment file, so we can use the same condition.

Only use UCS secret when driver is enabled

---

openstack/limes-auto/Chart.lock
openstack/limes-auto/Chart.yaml
openstack/limes-auto/templates/configmap-overrides.yaml
openstack/limes-auto/values.yaml
openstack/limes/templates/seed.yaml
openstack/limes/values.yaml

The intention here is to deliver quota-overrides.json from the secrets repo into prod without human intervention (only gated on validation). Quota overrides are supposed to be maintained by the respective service owners (e.g. the network-api team for Neutron and Octavia quotas), so involving us in the deployment is an unnecessary complication.
This is a different deployment pattern than Limes itself, so it needs to be located in a different chart.
This first step does not do anything on its own, but after this chart is deployed, I will switch Limes to using the quota-overrides.json from here instead of from its own chart.

openstack/limes-auto: init at 0.1.0

---

common/prometheus-alertmanager-base/Chart.yaml
common/prometheus-alertmanager-base/templates/alertmanager.yaml
common/prometheus-alertmanager-base/values.yaml

If set to `OnNamespace`, the operator injects a label matcher matching the  namespace of the AlertmanagerConfig object for all its routes and inhibition  rules. `None` will not add any additional matchers other than the ones specified in the AlertmanagerConfig. Default is `OnNamespace`.

am-alertmanagerConfigMatcherStrategy

---

openstack/ironic/templates/_conductor-deployment.yaml.tpl

- the credentials that the liveness probe was using are no longer in the
ironic.conf but now in the secrets.conf
- remove the vall to rabbitmq to not leak RO rabbitmq credentials to
anyone having k8s read access to the pod. The openstack-agent-liveness
should be enough for the liveness check

[ironic] fix liveness probe with secrets

---

openstack/ironic/templates/_conductor-deployment.yaml.tpl

in #6433 we dropped the "-" in the command which breaks the
chart, instead of adding it we switch to the "array" style.
This hopefully makes syntax error more prominent.

[ironic] fix YAML Syntax

---

prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/templates/deployment_worker.yaml

Probes restarts worker container but not the pod. The worker fetches a new filer to work on after being restarted, but the harvest poller still works on the old filer. Besides, the master is responsible for restarting the pod after introducing [this] commit.
[this]: https://github.com/sapcc/netappsd/commit/a6bf05fc96a71a26312cb2522a25938a412e8fe6

[netapp-exporter] remove probes on worker container

---

openstack/ironic/values.yaml

We need to configure the central rabbitmq and set some sensible defaults
for other settings that we got from nova, apart from the queue size
which seems to be 100 for productive regions for most OpenStack
services.

[ironic] audit set default settings

---

openstack/manila-nanny/alerts/manila.alerts

to avoid flapping because the metrics are not present on nanny restart
and take a while to be generated.
So we take rate([15m]) to look back over the values
of the last 15 minutes and remove duplicates by grouping by
share_id.

[manila-nanny] smoothen affinity alerts

---

openstack/neutron/templates/statefulset-network-agent-apod.yaml
openstack/neutron/templates/statefulset-network-agent.yaml

We skip outbound linkerd proxying for port 22,53,80,443 to better debug networks from the network viewpoint of our network agents. Especially port 22 will allow us to use the network agent as jumphost again.

[neutron] Skip ports for linker on network-agent

---

common/mariadb-galera/CHANGELOG.md
common/mariadb-galera/README.md
common/mariadb-galera/helm/Chart.yaml
common/mariadb-galera/helm/templates/configmap-mariadb-my.cnf.yaml
common/mariadb-galera/helm/tests/01-default-statefulset_test.yaml
common/mariadb-galera/helm/tests/04-configmap-mariadb-my-cnf_test.yaml
common/mariadb-galera/helm/values.yaml

- to avoid stale reads if required
- [wsrep_sync_wait](https://mariadb.com/kb/en/galera-cluster-system-variables/#wsrep_sync_wait)

[mariadb-galera] wsrep_sync_wait option for Galera added

---

openstack/manila/values.yaml

This parameter controls how often share manager polls the back end of the server migration status ([1]). Default value is 900 seconds. This PR set the interval to 300 seconds globally.
[1]:
https://github.com/sapcc/manila/blob/3aff6a6621bf265780db5ef3370741d1aac915e4/manila/share/manager.py#L116-L121

[manila] manager to check svm migration progress more often

---

openstack/keystone/Chart.yaml
openstack/keystone/templates/bin/_bootstrap.tpl
openstack/keystone/templates/bin/_db-sync.tpl
openstack/keystone/templates/bin/_repair_assignments.tpl
openstack/keystone/templates/job-bootstrap.yaml
openstack/keystone/templates/job-migration.yaml

For using linkerd in Job-spawned Pods, we have to add a snippet at the
end that will tell the linkerd-proxy sidecar to stop. This snippet is
integrated - together with the proxysql snippet - into
"utils.script.job_finished_hook" in the utils chart starting with
version 0.14.6.
Since we need a version bump, we also get:
add owner info explicitly to coordination pvc
mount a trust-bundle at subpath
Ref : https://github.com/sapcc/helm-charts/commit/ed8e6ec64a39159a01105220d7512570419151c1
Closed PR : https://github.com/sapcc/helm-charts/pull/6414

[Keystone] Enable linkerd jobs

---

openstack/limes/templates/deployment-collect.yaml

ApplyComputedProjectQuota has a larger RAM footprint when it runs.

limes: more RAM headroom for limes-collect

---

openstack/cc3test-seeds/Chart.yaml
openstack/cc3test-seeds/alerts/cc3test-quota.alerts

they are no longer needed since limes is auto increasing now. Leaving 99% as a safeguard

removing pre auto-update quota alerts

---

openstack/limes/templates/_utils.tpl
openstack/limes/templates/configmap.yaml
openstack/limes/templates/deployment-collect.yaml
openstack/limes/values.yaml

FYI, the reloader annotation is documented in <https://github.com/stakater/Reloader?tab=readme-ov-file#configmap>.

limes: use quota overrides from limes-auto deployment

---

system/cc-ceph/Chart.yaml
system/cc-ceph/templates/cephcluster.yaml
system/cc-ceph/values.yaml

Otherwise the osd will end up taking all memory until the node crashes

Ceph: Add limits to osd pods

---

openstack/ceph-seed/Chart.lock
openstack/ceph-seed/Chart.yaml
openstack/ceph-seed/ci/test-values.yaml
openstack/ceph-seed/templates/seed.yaml
openstack/ceph-seed/values.yaml

Introduce a seed chart, which will be running in "metal" clusters, to configure ceph service and endpoints.

ceph: add ceph service account and endpoints

---

openstack/ironic/Chart.lock
openstack/ironic/Chart.yaml

- MariaDB - use standardised labels
- Memcached - use standardised labels
- owner-info - use stable version number with SemVer
- RabbitMQ - use standardised labels
- linkerd - use stable version number with SemVer

[ironic] update dependencies

---

system/vmware-monitoring/Chart.yaml
system/vmware-monitoring/values.yaml

avoid crashing pods due to eph. storage overusage

enable data volume for vmware prometheis

---

system/cc-ceph/values.yaml

bluefs_buffered_io ... The default is better.
bdev_flock_retry... Checking the code. It's probably harmless.

remove unneeded ceph global config values

---

system/cc-ceph/Chart.yaml
system/cc-ceph/templates/certificate.yaml
system/cc-ceph/templates/record.yaml
system/cc-ceph/templates/service.yaml

regarding `Values.objectstore.service.externalIP `: we expect only 1 externalIP to be set

[cc-ceph] create records and cert

---

system/cc-ceph/Chart.yaml
system/cc-ceph/templates/_helpers.tpl

split with empty delimiter behaves weird

ceph: avoid using split for escape helper

---

openstack/octavia/templates/secrets-worker.yaml

In some regions the worker secrets are created correctly for every worker. But in some regions only one secret is created.
I suspect that this is because the worker secret template is missing a document separator (`---`) within the range construct. For example `octavia-worker-configmap.yaml` and `octavia-worker-deployment.yaml` have the separator within the range, respectively.
According to the helm templating guide[1] in many cases one of the separators (`---` and `...`) can be omitted, which might be (part of) the reason why this templating worked in some regions, e.g. qa-de-1.
[1] https://helm.sh/docs/chart_template_guide/yaml_techniques/#embedding-multiple-documents-in-one-file

[Octavia] Fix: Sometimes there's only one secret

---

openstack/placement/Chart.lock
openstack/placement/Chart.yaml
openstack/placement/values.yaml

This user provides passwordless access to the DB from localhost, so we can administer the DB without having to read and rotate a secret.
With bumping the mariadb chart we also get some fixes regarding Secrets in.

[Placement] Enable ccroot user for mariadb

---

prometheus-exporters/netapp-exporter/charts/netapp-cap-exporter/alerts/netapp-capacity.alerts

Storage team already got a monitoring for this, reducing duplicates.
We (compute-storage-api) keep this just as a backup,
therefore dropped to info and only after 2 days.

[netapp-exporter] remove manila inode alerts

---

system/cc-ceph/Chart.yaml
system/cc-ceph/templates/cephobjectstore.yaml

This fixes the `https://rook-ceph-rgw-ceph-objectstore-XXX.rook-ceph.svc:443/admin/user?format=json&uid=cosi": tls: failed to verify certificate: x509: certificate is valid for *.XXX, XXX, not rook-ceph-rgw-ceph-objectstore-XXX.rook-ceph.svc`

ceph: fix hosting.dnsNames placement

---

system/cc-ceph/Chart.yaml
system/cc-ceph/templates/ceph-config-override.yaml
system/cc-ceph/values.yaml

This is undocumented option, at least it's not listed in https://docs.ceph.com/en/latest/radosgw/config-ref/
But this option is available in ceph source code:
```
ceph$ grep -r rgw_s3_auth_order
src/rgw/rgw_auth_s3.h:    boost::split(result, cct->_conf->rgw_s3_auth_order,
src/common/options/rgw.yaml.in:- name: rgw_s3_auth_order
```

ceph: override the default auth order

---

openstack/manila/templates/shares/_share-netapp.conf.tpl

SVM migrate is supporting this, so we allow more volumes in
a vserver to avoid scattering volumes of the same customers
into too much different vservers on the same host.
This is especially interesting for customers that are creating many,
but small volumes.

[manila] increase max_shares_per_share_server to 50

---

system/cc-ceph/Chart.yaml
system/cc-ceph/templates/cephobjectstore.yaml

since the CephCluster's network provider is "host", we need to isolate 80/443 port listeners from each other
https://github.com/sapcc/helm-charts/blob/2ad73ac764c7cc83bfdbbf8f8ca33d43e7020b3c/system/cc-ceph/templates/cephcluster.yaml#L41-L42

ceph: introduce rgw pod anti affinity

---

openstack/ironic/templates/etc/_ironic_conductor.conf.tpl
openstack/ironic/values.yaml

This only affects deployments with a virtual-media interface.
It is a missing input for creating a bootable iso with the ironic-python-agent inside.
The kernel and ramdisk are already specified, this just is the bootloader used in the ISO created on the fly containing also the token or certificate for authentication
This value can be overidden by setting a deploy-config value for "bootloader".

[ironic] Configure ESP with default bootloader

---

system/gatekeeper/templates/constrainttemplate-vulnerable-images.yaml
system/gatekeeper/tests/gatekeeper-policies/fixtures/vulnerable-images/pod-vulnerable-in-linkerd.yaml
system/gatekeeper/tests/gatekeeper-policies/response-config.yaml
system/gatekeeper/tests/gatekeeper-policies/suite.yaml

As a service owner, I don't want linkerd violations spamming my Greenhouse view if I cannot do anything about them myself until linkerd is centrally updated.

GkVulnerableImages: group violations for linkerd sidecar pods under service "linkerd"

---

common/rabbitmq/CHANGELOG.md
common/rabbitmq/Chart.yaml
common/rabbitmq/templates/_helpers.tpl

- defined functions are shared across all subcharts
- hardcoded values will lead to wrong results

[rabbitmq] sharedservices.labels component name fixed

---

common/mariadb/Chart.yaml
common/mariadb/templates/_helpers.tpl

- defined functions are shared across all subcharts
- hard-coded values will lead to wrong results

[mariadb] sharedservices.labels component name fixed

---

prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/alerts/netappsd.yaml

In some cases, the building block number is missing in the filer's hostname. For example,
https://github.wdf.sap.corp/cc/secrets/blob/da7b06bb9f63afd7057e56a4898eb02ceab6cde9/eu-de-1/values/manila-vendor.yaml#L9

[neatpp] use `cluster` instead of `filer` labels

---

system/kube-monitoring-admin-k3s/Chart.lock
system/kube-monitoring-admin-k3s/Chart.yaml
system/kube-monitoring-kubernikus/Chart.lock
system/kube-monitoring-kubernikus/Chart.yaml
system/kube-monitoring-scaleout/Chart.lock
system/kube-monitoring-scaleout/Chart.yaml
system/kube-monitoring-virtual/Chart.lock
system/kube-monitoring-virtual/Chart.yaml

Bumps the version and fixes some CVE, see https://github.com/fluent/helm-charts/pull/508

Bump fluent-bit in kube-monitoring-* charts

---

openstack/cc3test/templates/cronjob-api.yaml
openstack/cc3test/templates/cronjob-automation-purger.yaml
openstack/cc3test/templates/cronjob-automation.yaml
openstack/cc3test/templates/cronjob-baremetal-purger.yaml
openstack/cc3test/templates/cronjob-baremetal.yaml
openstack/cc3test/templates/cronjob-blockstorage-purger.yaml
openstack/cc3test/templates/cronjob-blockstorage-volume.yaml
openstack/cc3test/templates/cronjob-blockstorage.yaml
openstack/cc3test/templates/cronjob-certificate.yaml
openstack/cc3test/templates/cronjob-compute-purger.yaml
openstack/cc3test/templates/cronjob-compute-server.yaml
openstack/cc3test/templates/cronjob-compute.yaml
openstack/cc3test/templates/cronjob-datapath.yaml
openstack/cc3test/templates/cronjob-datastore.yaml
openstack/cc3test/templates/cronjob-dns-purger.yaml
openstack/cc3test/templates/cronjob-dns.yaml
openstack/cc3test/templates/cronjob-fileshare-purger.yaml
openstack/cc3test/templates/cronjob-fileshare.yaml
openstack/cc3test/templates/cronjob-hermes.yaml
openstack/cc3test/templates/cronjob-integrity.yaml
openstack/cc3test/templates/cronjob-key-manager-purger.yaml
openstack/cc3test/templates/cronjob-key-manager.yaml
openstack/cc3test/templates/cronjob-loadbalancer-purger.yaml
openstack/cc3test/templates/cronjob-loadbalancer.yaml
openstack/cc3test/templates/cronjob-network-segmentation.yaml
openstack/cc3test/templates/cronjob-neutron-purger.yaml
openstack/cc3test/templates/cronjob-neutron.yaml

ports that are skipped 
22,443,9125

[cc3test]: skipped few inbound and outbound ports for linkerd to make compute and other tests working

---

openstack/limes/templates/deployment-collect.yaml

This is getting out of hand. I will make a ticket to investigate the ridiculously high memory usage.

limes: increase collector memory limit yet again

---

openstack/tempest/manila-tempest/templates/bin/_tempest-start-and-cleanup.sh.tpl

with introduction of deferred deletion, it can happen that tempest
is not able to delete the share group types in time (because a share
group with defer deleted shares is still existing).
Cover that in the cleanup phase to start freshly on the next iteration.

[tempest][manila] cleanup share group types

---

openstack/sap-seeds/templates/flavor-seed.yaml

Use a new CUSTOM_HW_SAPPHIRE_RAPIDS trait to distinguish the new generation. The flavor may change in the future, or use a true automatic COMPUTE_ flavor from nova, but use a manual trait to get started.

nova/flavors: Add general-purpose sapphire-rapids flavors

---

openstack/nova/values.yaml

We want old general purpose flavors to land on old hardware if possible. Therefore, we increase the weight of the SapphireRapidsWeigher - which decreases their priority.
I decided to use the same value as we use for
`hv_ram_class_weight_multiplier` as they seem to be pretty similar in what they want to achieve to me. I still want CUSTOM_DECOMMISSIONING to be higher. Going lower than 100, we might end up on small sapphire rapids (which can exist in theory) much easier.

[Nova] Set sapphire_rapids_weight_multiplier

---

openstack/neutron/templates/etc/_dhcp-agent.ini.tpl

Add option to configure IPv6 router advertisements for our DHCP agents.

[neutron] Enable IPv6 RAs in DHCP agent

---

openstack/ironic/py/ironic-node-update.py

No idea, why this works and the one before didn't.
The prior version worked locally, but not within the kos-operator where the code was compiled and executed.
That resulted in the function _filtered_patch not being found.

[ironic] Fixup to switching to idrac-redfish

---

common/prometheus-server/CHANGELOG.md
common/prometheus-server/Chart.yaml
common/prometheus-server/templates/_alertmanager_relabel.yaml.tpl

Introducing a new alert label that makes it possible to group alerts in ServiceNow by alertname, region and cluster. This ensures that multiple incidents are no longer generated for one alert, which also led to multiple tickets and notifications etc.
Requested by @geisslet

common/prometheus-server: add new alert label `incident_group_key`

---

openstack/octavia/values.yaml

Similar to Neutron (#6406), enable ccroot DB user (mariadb chart feature introduced in #6297).

[Octavia] Enable ccroot DB user

---

openstack/ironic/Chart.lock
openstack/ironic/Chart.yaml

Before all dependencies would set the same label, the one of mariadb now each component sets their own label

[ironic] fix labels of dependencies

---

openstack/ironic/py/ironic-node-update.py
openstack/ironic/templates/etc/_ironic_conductor.conf.tpl
openstack/ironic/values.yaml

The esp_image_path needs to be local to the conductor, the driver_info.bootloader can be remote.
One option might be to add it simply to the image, but this seems quicker.

[ironic] Fix bootloader location

---

openstack/archer/templates/configmap-f5.yaml

Due to the need to be "nice" to the long running connections commonly used between for example IBP and HanaCloud, we crafted the "noaging" fastL4 profile, with adjusted PVA handling, TCP idle timeout and TCP keep alive interval.
Profile name is `cc_fastL4_noaging_profile` and it's already rolled out to all Archer Big-IPs globally.

[archer] - update fastl4 profile name

---

openstack/keystone/templates/etc/_keystone.conf.tpl

It was decided not to block the user for 60 seconds, but rather for 1 second, because keystone can hold many requests by itself.

keystone: refill credits every second

---

common/memcached/Chart.yaml
common/memcached/values.yaml

- default 0,1 is even less than the limit for metrics container.
- cpu-throttled at least for nova in large regions.

[memcached] increase default cpu limit to 0,5

---

openstack/limes/templates/deployment-api.yaml

The limes API Pod gets OOM killed. This PR increase the limit from 500Mi to ~~1Gi~~ 700Mi.

limes: Increase RAM limit
