openstack/cc3test-seeds/templates/user-seed.yaml

@artherd42 : Please approve this.

added ccadmin/master project seed

---

openstack/cc3test/templates/cronjob-key-manager.yaml

added cron job for barbican test

---

openstack/cronus/templates/cronus/_config.yaml.tpl
openstack/cronus/values.yaml

This PR adds a configuration for queue activation.

[cronus]: add queue activation config

---

openstack/swift/alerts/openstack/api.alerts

openstack/swift/alerts/openstack/api.alerts | update playbook links to rm html ending

---

openstack/cinder/Chart.lock
openstack/cinder/Chart.yaml

[cinder] Remove region check

---

openstack/cc3test/alerts/ccloud-hermes.alerts

added hermes canary alert

---

openstack/hermes/alerts/hermes.alerts

@notque : please approve this, alert moved to cc3test: https://github.com/sapcc/helm-charts/commit/465cbcd78fd00f7d09bf7cbf1088488c7ae1ff2b

remove blackbox hermes alert moved to cc3test

---

openstack/cc3test/alerts/key-manager.alerts

added alert for canary barbican

---

openstack/cc3test/alerts/dns.alerts

added alert for desginate check

---

openstack/cc3test/alerts/dns.alerts

added dns create subzone check alert

---

openstack/cc3test/templates/cronjob-network.yaml

added nxst checks

---

common/prometheus-server/CHANGELOG.md
common/prometheus-server/Chart.yaml
common/prometheus-server/templates/_helpers.tpl
common/prometheus-server/templates/prometheus-server.yaml

README adjusted with missing information

[prometheus-server] thanos prefix removed

---

openstack/manila/Chart.lock
openstack/manila/Chart.yaml
openstack/manila/values.yaml

Define support_group for mariadb alerts.

[manila] upgrade mariadb chart

---

openstack/maia/templates/etc/_maia_scrape_config.yaml.tpl

@artherd42 @notque : please approve this.

as with cc3test, all VMs prefix with "cc3test"

---

openstack/cc3test/alerts/ccloud-jump-server.alerts

it should be clear which jump server we are talking about

[cc3test] dedicated name

---

prometheus-exporters/jumpserver-exporter/alerts/jumpserver.alerts

jumpserver-exporter/alerts/jumpserver.alerts hugo documentation update 

---

prometheus-exporters/redfish-exporter/alerts/metal-redfish-esxi.alerts

redfish-exporter/alerts/metal-redfish-esxi.alerts hugo documentation update

---

prometheus-exporters/snmp-exporter/alerts/snmp-arista.alerts

snmp-exporter/alerts/snmp-arista.alerts hugo documentation update

---

openstack/swift/templates/etc/_proxy-server.conf.tpl
openstack/swift/templates/seeds.yaml

Any objections regarding a soonish rollout?

[swift] remove deprecated role swiftoperator

---

openstack/nova/Chart.lock
openstack/nova/Chart.yaml
openstack/nova/values.yaml

Add support_group to mariadb, rabbitmq & memcached.
Add owner-info to chart.

[nova] Add support group & owner info

---

openstack/octavia/Chart.lock
openstack/octavia/Chart.yaml

Includes support_group information, among other updates.

[Octavia] Bump chart dependencies

---

prometheus-exporters/openstack-exporter/alerts/cinder.alerts

David said the alerts needed to be changed to update the support_group to compute

[cinder] Change support_group to compute

---

prometheus-exporters/vrops-exporter/alerts/datastore.alerts

Promoting the SDRS alert to Warning /Critical status and removed the info alert .

Promoting the SDRS alert to Warning /Critical

---

global/prometheus-alertmanager-operated/Chart.yaml
global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl

preparation of generic service routing; qa group alerts without infos

D072896 [AM] service routing

---

prometheus-exporters/octobus-query-exporter/alerts/logs.alerts

octobus-query-exporter/alerts/logs.alerts hugo documentation update

---

openstack/maia/Chart.yaml
openstack/maia/templates/etc/_maia_scrape_config.yaml.tpl

https://documentation.global.cloud.sap/docs/customer/monitoring/operational-metrics--maia/metrics-metrics/#virtual-machine-metrics

[maia] accurate specification of vrops metrics

---

openstack/maia/Chart.yaml
openstack/maia/templates/etc/_maia_scrape_config.yaml.tpl

Reverts sapcc/helm-charts#4234
Request header is getting to long with this in place

Revert "[maia] accurate specification of vrops metrics"

---

openstack/keystone/templates/deployment-api.yaml

similar to bcc9e42b4da7f0c02412da67bfcef2c071efc100

[keystone] check if DB is up as a part of readiness check

---

openstack/manila/alerts/openstack/manila.alerts
openstack/manila/values.yaml

Use duration gauge in expression.

[manila] fix flapping SVM alert

---

openstack/hermes/templates/etc/_logstash.conf.tpl

tag_on_failure must be an array.

[hermes] fixes error on tag_failure

---

openstack/placement/Chart.yaml

We rolled placement out with yoga already, but we failed to update the appVersion in the process.

[placement] Update appVersion to yoga

---

openstack/nova/shellinabox/10_default_server.conf
openstack/nova/shellinabox/revproxy.lua
openstack/nova/templates/console-deployment.yaml
openstack/nova/templates/console-shellinabox-configmap.yaml
openstack/nova/templates/console-shellinabox-deployment.yaml
openstack/nova/templates/console-shellinabox-secret.yaml
openstack/nova/templates/etc/_config.lua.tpl
openstack/nova/values.yaml

This implements the shellinabox proxy in nginx
as lua scripts, and also solves proxying kvm
for dell hosts.
The existing custom solution in nova only proxies
to a single host, and cannot be changed easily
to multiple.
For the Dell KMS, it also needs to
proxy websockets, which is simply a configuration
option in nginx, but would otherwise need
to be implemented in the python proxy

[nova] Shellinabox & Dell KMS Proxy in Nginx

---

openstack/cronus/templates/cronus/_config.yaml.tpl

added for cronus reject cache ttl

ttl reject added

---

prometheus-rules/prometheus-vmware-rules/alerts/datastore.alerts

Adjustment to change warning threshold from 85 % to 80 %

Adjustment to change warning threshold

---

prometheus-rules/prometheus-vmware-rules/alerts/datastore.alerts

Adjustment to Meta, description and summery

Adjustment to Meta, description and summery

---

openstack/ironic/alerts/openstack-ironic.alerts

Ref: <https://github.com/sapcc/limes/commit/85f914cd4c00d6412e5e913c944c3cd5bc0def1b>

ironic: clarify instructions on OpenstackIronicUnmatchedNodes alert

---

openstack/octavia/Chart.lock
openstack/octavia/Chart.yaml

This time with `Chart.lock`...

[Octavia] Bump subcharts

---

system/logs/Chart.lock
system/logs/Chart.yaml
system/logs/vendor/fluent/Chart.yaml
system/logs/vendor/fluent/templates/_controlplane.conf.tpl

[neutron][logs] more generic name for neutronHost

---

global/prometheus-alertmanager-operated/Chart.yaml
global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl

[alertmanager] adjust labs routing per group

---

system/kubernikus-monitoring/Chart.yaml
system/kubernikus-monitoring/alerts/api.alerts
system/kubernikus-monitoring/alerts/operator.alerts

As discussed in today's Kubernetes Weekly meeting.

downgrade Kubernikus alerts to WARNING

---

openstack/cerebro/templates/domain-ccadmin-seed.yaml

Updated technical users to match CAM access level

cerebro: update group users

---

system/vmware-monitoring/Chart.lock
system/vmware-monitoring/Chart.yaml
system/vmware-monitoring/ci/test-values.yaml
system/vmware-monitoring/values.yaml

#4446 needs to be merged before

adding cerebro remote_write target

---

openstack/cronus/templates/cronus/deployment.yaml
openstack/cronus/templates/cronus/statefulset.yaml

Reverts sapcc/helm-charts#4454

Revert "cronus - fixing tolerations template"

---

openstack/cronus/templates/nebula/_config.yaml.tpl
openstack/cronus/values.yaml

nebula - new postfix flags

---

prometheus-exporters/apic-exporter/alerts/apichealth.alerts
prometheus-exporters/apic-exporter/alerts/exporter.alerts

Send notification to slack channel #cc-exporters instead to moni channel

[apic-exporter] updates alert service for general exporter health alerts

---

global/prometheus-infra/alerts/interconnect.alerts

instead to moni channels which will be retired soon

Send notifications to cc-exporter slack channel

---

common/prometheus-server-pre7/CHANGELOG.md
common/prometheus-server-pre7/Chart.yaml
common/prometheus-server-pre7/values.yaml
common/prometheus-server/CHANGELOG.md
common/prometheus-server/Chart.yaml
common/prometheus-server/values.yaml

The kubeapiserver metrics have been renamed

Change kubeAPIServer.allowedMetrics

---

prometheus-exporters/octobus-query-exporter/alerts/events.alerts

Adding playbook link for the alert

Adding playbook link for the alert

---

global/prometheus-alertmanager-operated/Chart.yaml
global/prometheus-alertmanager-operated/ci/test-values.yaml
global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl
global/prometheus-alertmanager-operated/values.yaml

to have the ack button working we need to separate the routes unfortunately to use the channel specific webhook

D072896 ack button support groups

---

common/prometheus-alertmanager-base/Chart.yaml
common/prometheus-alertmanager-base/templates/_helpers.tpl
common/prometheus-alertmanager-base/templates/alerts/_alertmanager.alerts.tpl
common/prometheus-alertmanager-base/values.yaml

Alertmanager: fix channel emit for alerts

---

system/gatekeeper-config/templates/constraint-pod-security.yaml

As discussed in the Kubernetes Weekly meeting.

GkPodSecurity: enforce in prod

---

prometheus-rules/prometheus-vmware-rules/alerts/host.alerts
prometheus-rules/prometheus-vmware-rules/alerts/vccluster.alerts
prometheus-rules/prometheus-vmware-rules/alerts/virtualmachine.alerts

Disabling some compute info alerts

---

openstack/cc3test/templates/cronjob-blockstorage-purger.yaml
openstack/cc3test/values.yaml

Split purger into their own pods

[cc3test] : Split purger into their own pods

---

openstack/ironic/templates/_conductor-deployment.yaml.tpl
openstack/ironic/templates/api-deployment.yaml
openstack/ironic/templates/etc/_ironic.conf.tpl
openstack/ironic/templates/inspector-conductor-deployment.yaml
openstack/ironic/templates/inspector-deployment.yaml
openstack/ironic/templates/proxysql-configmap.yaml
openstack/ironic/values.yaml

[ironic] Add proxysql side-cars snippets

---

openstack/blackbox/vendor/blackbox-tests-datapath/alerts/ntp-datapath.alerts

blackbox: update playbook links to rm html ending (hugo)

---

openstack/cc3test/alerts/dns.alerts

cc3test: update playbook links to rm html ending

---

openstack/neutron/alerts/api.alerts

neutron: update playbook links to rm html ending

---

prometheus-exporters/network-generic-ssh-exporter/alerts/asr.alerts

network-generic-ssh-exporter/alerts/asr.alerts hugo documentation update

---

prometheus-exporters/netapp-exporter/charts/netapp-cap-exporter/alerts/netapp-capacity.alerts

charts/netapp-cap-exporter/alerts/netapp-capacity.alerts hugo documentation update 

---

openstack/nova/alerts/openstack/nova.alerts

helm-charts/openstack/nova/alerts/openstack/nova.alerts | update play book links to rm html ending

---

openstack/ironic/alerts/openstack-ironic.alerts

ironic: update playbook links to rm html ending

---

openstack/utils/Chart.yaml
openstack/utils/templates/_proxysql.tpl

See individual commits for details.
In one PR, as it is a pain to bump the dependencies for the charts for each minor update.

Proxysql maintenance

---

system/vmware-monitoring/templates/collector-configmap.yaml

Adding mem|guest_usage to vrops-exporter

---

openstack/maia/templates/etc/_maia_scrape_config.yaml.tpl

Adding three new metrics for: cronus email success rate, error rate, and total rate

exposing new email provider rate metrics via maia

---

openstack/utils/Chart.yaml
openstack/utils/templates/_proxysql_configmap.yaml.tpl

'not' needs brackets
and I'm unsure about the .Values (at least I got no render errors any more)

[utils] attempted fix of proxysql_configmap snippet

---

prometheus-rules/prometheus-vmware-rules/alerts/nsxt.alerts

Alert resolves itself always within 20-30m.

Increasing wait time for NSXTClusterControlStatusDegraded

---

openstack/sap-seeds/templates/nova-seed.yaml
openstack/sap-seeds/values.yaml

[SAP-Seeds] disable project seeding of a particular domain

---

prometheus-exporters/network-generic-ssh-exporter/aggregations/ssh-exporter-neutron-router.rules
prometheus-exporters/snmp-exporter/aggregations/snmp-exporter-neutron-router.rules

This will allow us to make a decision if we can retire certain models.

[neutron] Include model in per cluster metrics

---

openstack/neutron/templates/statefulset-network-agent-apod.yaml
openstack/neutron/templates/statefulset-network-agent.yaml

The neutron network agent for the yoga release also requires additional security capabilities ( SYS_ADMIN, DAC_OVERRIDE, DAC_READ_SEARCH, SYS_PTRACE) which are only enabled for the ussuri release.

Yoga Update: Neutron Network Agent Security Capabilities

---

openstack/octavia/alerts/octavia.alerts

[octavia] LoadBalancerStuckInPending: Rename dashboard link

---

system/audit-logs/Chart.lock
system/audit-logs/Chart.yaml
system/audit-logs/vendor/fluent-audit-container/Chart.yaml
system/audit-logs/vendor/fluent-audit-container/templates/_fluent.conf.tpl

Second iteration. This time we check if the record has the app label If it does we copy the value to app_ and remove the original

[audit-logs] renames app label if present

---

openstack/swift/templates/etc/_proxy-server.conf.tpl

Do not merge before https://github.com/sapcc/swift-addons/pull/3 .

Swift: enable write restriction middleware

---

prometheus-rules/prometheus-vmware-rules/alerts/nsxt.alerts

NSXTSslCertificateExpiry

---

system/prometheus-infra/Chart.yaml
system/prometheus-infra/templates/_prometheus-infra.yaml.tpl

Reverts sapcc/helm-charts#4734

Revert "prometheus-infra: split federation job"

---

openstack/cinder/Chart.lock
openstack/cinder/Chart.yaml
openstack/cinder/templates/api-deployment.yaml
openstack/cinder/templates/backup_deployment.yaml
openstack/cinder/templates/coordination-pvc.yaml
openstack/cinder/templates/etc/_cinder.conf.tpl
openstack/cinder/templates/scheduler-deployment.yaml
openstack/cinder/templates/vcenter_datacenter_cinder_deployment.yaml
openstack/cinder/templates/volumes/_netapp-deployment.yaml.tpl
openstack/cinder/templates/volumes/_volume-deployment.yaml.tpl
openstack/cinder/values.yaml

[cinder] Switch coordination driver to "file"

---

prometheus-exporters/cronus-exporter/alerts/cisco/cronus.alerts

create new alert for esa_bulk and separate esa transaction alert

new alert for cisco bulk

---

common/mariadb/Chart.yaml
common/mariadb/values.yaml

pipeline image build did not contain the latest fixes from the git repo

[mariadb] fixes slow_query log setting in backup tool

---

prometheus-rules/prometheus-vmware-rules/alerts/host.alerts

Creating new alert for Storage path check up for a give n host in a cluster.

Storage Path check up for a host in cluster 

---

prometheus-exporters/network-generic-ssh-exporter/templates/_config.yaml.tpl

new device also needs to be created in system/atlas/templates/configmap.yaml

Adding EndPoint learning state filter for ACI leaf

---

prometheus-exporters/netapp-exporter/Chart.lock
prometheus-exporters/netapp-exporter/Chart.yaml
prometheus-exporters/netapp-exporter/charts/netapp-cap-exporter/Chart.yaml
prometheus-exporters/netapp-exporter/charts/netapp-cap-exporter/templates/aggregations.yaml
prometheus-exporters/netapp-exporter/charts/netapp-cap-exporter/templates/alerts.yaml
prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/Chart.yaml
prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/templates/_helpers.tpl
prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/templates/aggregations.yaml
prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/templates/alerts.yaml
prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/templates/deployment.yaml
prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/values.yaml
prometheus-exporters/netapp-exporter/charts/netapp-perf-exporter/Chart.yaml
prometheus-exporters/netapp-exporter/charts/netapp-perf-exporter/templates/aggregations.yaml
prometheus-exporters/netapp-exporter/charts/netapp-perf-exporter/templates/deployment.yaml
prometheus-exporters/netapp-exporter/charts/netapp-perf-exporter/templates/service.yaml
prometheus-exporters/netapp-exporter/charts/netapp-perf-exporter/values.yaml
prometheus-exporters/netapp-exporter/values.yaml

services are created only if explicitly set in netapp-perf-exporter

[netapp-exporter] using single prometheus directive

---

prometheus-rules/prometheus-kubernetes-rules/Chart.yaml
prometheus-rules/prometheus-kubernetes-rules/aggregations/frontend/utilization.rules

I'm almost certain that these queries work as intended. :)

summarize resource utilization by support-group and service

---

prometheus-rules/prometheus-vmware-rules/alerts/datastore.alerts

Downgrading EPH Datastore Capacity Warning and Critical Alert to Info Channel

Downgrade EPH DS Capacity Alerts to Info

---

openstack/ironic/alerts/openstack-ironic.alerts

[ironic] adjust playbook link for OpenstackIronicNodeInCleanFailedState

---

openstack/neutron/Chart.yaml

neutron change appVersion to yoga

neutron change appVersion to yoga

---

openstack/placement/Chart.lock
openstack/placement/Chart.yaml
openstack/placement/templates/_helpers.tpl
openstack/placement/templates/db-migrate-job.yaml
openstack/placement/templates/db-online-migrate-job.yaml
openstack/placement/templates/etc-configmap.yaml
openstack/placement/templates/etc/_placement.conf.tpl
openstack/placement/templates/etc/_uwsgi.ini.tpl
openstack/placement/templates/placement-api-deployment.yaml

See individual commits for more information

[placement] Move kubernetes-entrypoint to init containers + minor cleanup

---

common/mariadb/Chart.yaml
common/mariadb/templates/db-exec-rbac.yaml
common/mariadb/templates/pre-change-job.yaml

it is already implicitly included as shown in the helm diff steps

[mariadb] explicitly add some namespace metadata

---

prometheus-rules/prometheus-vmware-rules/alerts/datastore.alerts

Raise VMFS DS Capacity to  warning channel with 85% threshold

Raise VMFS DS Capacity to warning channel

---

openstack/nova/templates/etc/_nova-policy.yaml.tpl

Accidental duplicate/copy-paste error from os-hypervisors:list.

nova policy: Add os-hypervisors:list-detail

---

prometheus-exporters/openstack-exporter/alerts/cinder.alerts

Renamed the CinderShardFreeSpace to CinderShardFreeSpaceSSD Created CinderShardFreeSpaceStandardHDD critcal alert

[openstack-exporter] Alert for cinder standard_hdd

---

system/gatekeeper/templates/constrainttemplate-pod-security.yaml
system/gatekeeper/tests/fixtures/pod-security/falco.yaml
system/gatekeeper/tests/suite.yaml

Deployed and verified in s-qa-de-1 and works as expected.

system/gatekeeper: add pod security exceptions for falco

---

system/infra-monitoring/Chart.yaml
system/infra-monitoring/templates/_prometheus-infra-collector.yaml.tpl
system/infra-monitoring/values.yaml

Only in qa as a PoC, so subject to change before going to production.

[infra-monitoring] Add job for linux kvm machines

---

global/prometheus-alertmanager-operated/Chart.lock
global/prometheus-alertmanager-operated/Chart.yaml
global/prometheus-alertmanager-operated/values.yaml

Add required owner-info dependency to alertmanager-operated

[Alertmanager]: add owner-info dependency

---

system/vmware-monitoring/alerts/vrops-exporter.alerts

https://ci1.eu-de-2.cloud.sap/teams/monitoring/pipelines/vmware-monitoring/jobs/validate-helm-charts/builds/65

Fixed indentation

---

openstack/cronus/templates/cronus/pvc.yaml
openstack/cronus/templates/cronus/statefulset.yaml

This reverts commit 86953a15b52d009571fbe8367da272fe4e4a5ef9.

Revert "[cronus] mount file buffer pvc as ReadWriteMany"

---

system/doop-central/templates/ingress.yaml

Required for Greenhouse DOOP plugin

CORS support for doop api ingress

---

openstack/utils/Chart.yaml
openstack/utils/templates/_affinity.tpl
openstack/utils/templates/_topology.tpl
openstack/utils/values.yaml

- Use default instead of value as the default value from global is not properly merged
- Add service annotations for topology aware routing
- Add the annotations only in regions with more than one az

[openstack/utils] Topology refinement

---

openstack/octavia/templates/octavia-api-deployment.yaml
openstack/octavia/templates/octavia-api-service.yaml

@fwiesel I noticed after merging #5008 that you introduced typos. Let me know if any of these were intentional (e. g. due to mistyped names that have become technical debt or something...)

[Octavia] Fix typos

---

global/prometheus-alertmanager-operated/ci/test-values.yaml
global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl

Added TOM alerts for the SRC team.

Added TOM alerts that belong to SRC team

---

prometheus-exporters/snmp-exporter/px.alerts/snmp-pxdl.alerts
system/infra-monitoring/vendor/px-exporter/px.alerts/px.alerts

- [PX] remove old N7k alerts and references
- [PX] Use more concise alert description, make use of alert summary

[PX] Cleanup alert messages (and delete N7k alerts)

---

openstack/nova/shellinabox/10_default_server.conf
openstack/nova/shellinabox/revproxy.lua
openstack/nova/templates/_console-service.yaml.tpl
openstack/nova/templates/_console_deployment.yaml.tpl
openstack/nova/templates/console-configmap.yaml
openstack/nova/templates/console-deployment.yaml
openstack/nova/templates/console-ingress.yaml
openstack/nova/templates/console-shellinabox-configmap.yaml
openstack/nova/templates/console-shellinabox-deployment.yaml
openstack/nova/templates/console-shellinabox-secret.yaml
openstack/nova/templates/etc/_nova.conf.tpl
openstack/nova/templates/hypervisors/_ironic-deployment.yaml.tpl
openstack/nova/templates/hypervisors/hypervisors-vmware-deployment-vct.yaml

Support web consoles for cell2

---

system/kube-monitoring-scaleout/Chart.yaml
system/kube-monitoring-scaleout/templates/falco_functional_test.yaml

Adding functional test to  scaleout cluster

Falco functional test cronjob

---

openstack/sap-seeds/templates/flavor-seed.yaml

- x1.memory -> m_c8_m128
- x1.2xmemory -> m_c16_m256
- x1.4xmemory -> m_c32_m512

nova/flavors: Rename & alias x1.* to m_* names

---

openstack/cronus-seed/values.yaml

email route

---

ci/lint-chart.sh

- to fix linting problems
- to use recent versions of the related tools

chart-testing bumped to 3.8.0

---

global/concourse-main/Chart.lock
global/concourse-main/Chart.yaml
global/concourse-main/values.yaml

This also bumps
* postgresql to 11.20
* ha-proxy ingress to 1.10.2

Upgrade concourse to version 7.9.1

---

openstack/cronus/templates/nebula/_config.yaml.tpl

Adding new flag accessKeyRotationDays under aws for key rotation check

Key rotation age

---

openstack/cronus/values.yaml

key rotation

---

prometheus-rules/prometheus-kubernetes-rules/Chart.yaml
prometheus-rules/prometheus-kubernetes-rules/alerts/pod.alerts.tpl

- to detect containers with lower or higher than requested RAM usage
- to detect pods that have no CPU or RAM requests configured

[alert] pod resource usage alerts added

---

global/prometheus-alertmanager-operated/Chart.yaml
global/prometheus-alertmanager-operated/ci/test-values.yaml
global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl

add foundation && begin of pd /b1 fade out housekeeping

add foundation && pd /b1 fade out housekeeping

---

openstack/keystone/templates/seed-2faproxy.yaml
openstack/keystone/values.yaml

So far I used application credentials tied to my user which is not suitable for production.

2faproxy: Add OpenstackSeed for service user creation

---

system/kube-monitoring-admin-k3s/Chart.lock
system/kube-monitoring-admin-k3s/Chart.yaml
system/kube-monitoring-kubernikus/Chart.lock
system/kube-monitoring-kubernikus/Chart.yaml
system/kube-monitoring-metal/Chart.lock
system/kube-monitoring-metal/Chart.yaml
system/kube-monitoring-scaleout/Chart.lock
system/kube-monitoring-scaleout/Chart.yaml
system/kube-monitoring-virtual/Chart.lock
system/kube-monitoring-virtual/Chart.yaml

- to activate the pod resources alerts from
- https://github.com/sapcc/helm-charts/pull/5130

[alerts]prometheus-kubernetes-rules version bumped

---

prometheus-rules/prometheus-kubernetes-rules/Chart.yaml
prometheus-rules/prometheus-kubernetes-rules/alerts/pod.alerts.tpl

pod alerting templating fixed

---

system/kube-monitoring-admin-k3s/Chart.lock
system/kube-monitoring-admin-k3s/Chart.yaml
system/kube-monitoring-kubernikus/Chart.lock
system/kube-monitoring-kubernikus/Chart.yaml
system/kube-monitoring-metal/Chart.lock
system/kube-monitoring-metal/Chart.yaml
system/kube-monitoring-scaleout/Chart.lock
system/kube-monitoring-scaleout/Chart.yaml
system/kube-monitoring-virtual/Chart.lock
system/kube-monitoring-virtual/Chart.yaml

- to use the version that contains the rule syntax fixes

[alerts] prometheus-kubernetes-rules version bumped

---

common/rabbitmq/CHANGELOG.md
common/rabbitmq/Chart.yaml
common/rabbitmq/values.yaml

contains some bug fixes and usability improvements 
Changelog: https://www.rabbitmq.com/changelog.html

[rabbitmq] update rabbitmq to 3.11.15-managemant

---

openstack/neutron/Chart.lock
openstack/neutron/Chart.yaml
openstack/neutron/templates/deployment-rpc-server.yaml
openstack/neutron/templates/deployment-server.yaml
openstack/neutron/templates/etc/_neutron.conf.tpl
openstack/neutron/values.yaml

Please, have a look at the individual commits for more details.

[neutron] Move defaults for workers to values &  scale proxysql accordingly

---

openstack/designate/Chart.lock
openstack/designate/Chart.yaml

adding vendor's feature enhancements and bug fixes: rabbitmq-3.11.15-management
[ChangeLog](https://www.rabbitmq.com/changelog.html)

[designate] update dependency on rabbitmq to version 0.5.2

---

system/kube-monitoring-admin-k3s/Chart.lock
system/kube-monitoring-admin-k3s/Chart.yaml
system/kube-monitoring-kubernikus/Chart.lock
system/kube-monitoring-kubernikus/Chart.yaml
system/kube-monitoring-metal/Chart.lock
system/kube-monitoring-metal/Chart.yaml
system/kube-monitoring-scaleout/Chart.lock
system/kube-monitoring-scaleout/Chart.yaml
system/kube-monitoring-virtual/Chart.lock
system/kube-monitoring-virtual/Chart.yaml

[alert] activate the updated prometheus-kubernetes-rules

---

openstack/nova/Chart.lock
openstack/nova/Chart.yaml

adding vendor's feature enhancements and bug fixes: rabbitmq-3.11.15-management
[ChangeLog](https://www.rabbitmq.com/changelog.html)

[nova] update dependency on rabbitmq to version 0.5.2

---

openstack/sap-seeds/templates/flavor-seed.yaml

As per request from S4 via Frank Roeder & David Hoeller.

Add Nova flavor m_c20_m160

---

common/prometheus-alertmanager-base/Chart.yaml
common/prometheus-alertmanager-base/templates/alerts/_alertmanager.alerts.tpl

* channel notification alerts to slack: cc-alerts and stop spamming obs warning channel
* pump chart version

[alert manager]: update ALM alerts

---

global/prometheus-alertmanager-operated/Chart.lock
global/prometheus-alertmanager-operated/Chart.yaml

[alertmanager]: bump version of base chart dependency

---

system/gatekeeper/.gitignore
system/gatekeeper/Makefile
system/gatekeeper/ci/test-values.yaml
system/gatekeeper/templates/configmap-doop-analyzer.yaml
system/gatekeeper/templates/deployment-doop-analyzer.yaml
system/gatekeeper/tests/doop-analyzer-rules/M201-M202-merge-cluster-mentions/input.json
system/gatekeeper/tests/doop-analyzer-rules/M201-M202-merge-cluster-mentions/output.json
system/gatekeeper/tests/doop-analyzer-rules/M211-M212-merge-region-mentions/input.json
system/gatekeeper/tests/doop-analyzer-rules/M211-M212-merge-region-mentions/output.json
system/gatekeeper/tests/doop-analyzer-rules/M221-M222-merge-altregion-mentions/input.json
system/gatekeeper/tests/doop-analyzer-rules/M221-M222-merge-altregion-mentions/output.json
system/gatekeeper/tests/doop-analyzer-rules/M301-merge-ccloudshell-pods/input.json
system/gatekeeper/tests/doop-analyzer-rules/M301-merge-ccloudshell-pods/output.json
system/gatekeeper/tests/doop-analyzer-rules/M401-M402-merge-deployment-pods/input.json
system/gatekeeper/tests/doop-analyzer-rules/M401-M402-merge-deployment-pods/output.json
system/gatekeeper/tests/doop-analyzer-rules/M401-merge-daemonset-pods/input.json
system/gatekeeper/tests/doop-analyzer-rules/M401-merge-daemonset-pods/output.json
system/gatekeeper/tests/doop-analyzer-rules/M403-merge-deployment-pods-with-long-names/input.json
system/gatekeeper/tests/doop-analyzer-rules/M403-merge-deployment-pods-with-long-names/output.json
system/gatekeeper/tests/doop-analyzer-rules/M404-merge-job-pods/input.json
system/gatekeeper/tests/doop-analyzer-rules/M404-merge-job-pods/output.json
system/gatekeeper/tests/doop-analyzer-rules/M405-merge-statefulset-pods/input.json
system/gatekeeper/tests/doop-analyzer-rules/M405-merge-statefulset-pods/output.json
system/gatekeeper/tests/doop-analyzer-rules/M501-merge-kubernikus-klusters/input.json
system/gatekeeper/tests/doop-analyzer-rules/M501-merge-kubernikus-klusters/output.json
system/gatekeeper/tests/doop-analyzer-rules/M502-merge-grafana-operator-instances/input.json
system/gatekeeper/tests/doop-analyzer-rules/M502-merge-grafana-operator-instances/output.json
system/gatekeeper/tests/doop-analyzer-rules/R101-M101-helm-releases/input.json
system/gatekeeper/tests/doop-analyzer-rules/R101-M101-helm-releases/output.json
system/gatekeeper/tests/doop-analyzer-rules/run.sh

~@SuperSandro2000 I have not added all the test cases yet, but the test machinery is available for you to review.~ All tests have been added. I shuffled the rules around a bit from the first draft because of ordering dependencies that the tests uncovered.

gatekeeper: add doop-analyzer

---

openstack/manila-nanny/aggregations/manila.rules
openstack/manila-nanny/alerts/manila.alerts
openstack/manila-nanny/templates/alerts.yaml
openstack/manila-nanny/templates/deployment.yaml
openstack/manila-nanny/values.yaml

The new nanny is merged here https://github.com/sapcc/openstack-nannies/pull/78

[manila-nanny] add nanny for checking affinity

---

common/memcached/Chart.yaml
common/memcached/values.yaml

image Vulnerability Status is clean

[common][memcached] bump version to 1.6.21-alpine

---

system/gatekeeper-config/templates/constraint-owner-info-on-helm-releases.yaml

As per approved schedule, this change shall be rolled out on Monday, 2023-08-28.
@SuperSandro2000 Please make a note to roll this out in my stead on Monday.

gatekeeper: enforce GkOwnerInfoOnHelmReleases in scaleout gold

---

prometheus-exporters/poller/templates/_config.yaml.tpl
prometheus-exporters/poller/values.yaml

- config file - adding new conditions for nonmandatory values.
- values - removing dummy values that fail the poller startup check.

poller config fix

---

system/vmware-monitoring/Chart.lock
system/vmware-monitoring/Chart.yaml
system/vmware-monitoring/values.yaml

the other one is to be removed after migration

adding new cerebro endpoint

---

system/vmware-monitoring/Chart.yaml
system/vmware-monitoring/templates/vrops-exporter-deployment.yaml

This was tested for one existent tag with the label_replace function and therefore needs further testing as relabel config, with multiple tags of different categories etc.
It might be possible to generalize it even more to create new labels for all objects in the tag json, although it could be difficult for multiple tags of the same category.

[vrops-exporter] Extract tag from summary|tagJson

---

prometheus-rules/prometheus-vmware-rules/alerts/datastore.alerts

- Refine the regex pattern for label matching to improve readability and enhance clarity

[prometheus-vmware-rules] Revise Cinder alert

---

openstack/hermes/templates/logstash-deployment.yaml

Tested it, looks good, no duplication.

increase hermes logstash replicas from 1 to 3

---

openstack/limes/alerts/openstack/api.alerts

Companion PR for https://github.com/sapcc/limes/pull/359

limes: replace domain/project discovery metrics with new keystone-sync metric

---

openstack/manila/alerts/openstack/manila.alerts

waiting for accompanying ops docu change

[manila] stuck alerts

---

common/mariadb-galera/docker/sysbench/Dockerfile
common/mariadb-galera/docker/sysbench/bin/entrypoint.sh

- focus on MySQL benchmarks and JSON reporting

sysbench Docker image added

---

openstack/utils/Chart.yaml
openstack/utils/templates/_affinity.tpl

fixing indentation bug for kubernetes_pod_AZ_spread function

---

openstack/backup-replication/templates/_utils.tpl
openstack/backup-replication/templates/cronjob.yaml
openstack/backup-replication/templates/prometheus-alerts.yaml
openstack/backup-replication/templates/replication-configmap.yaml
openstack/backup-replication/templates/secret.yaml
openstack/backup-replication/templates/statsd-configmap.yaml
openstack/backup-replication/templates/statsd-deployment.yaml
openstack/backup-replication/templates/statsd-service.yaml
openstack/backup-replication/values.yaml

This is backwards-compatible with the existing values.yaml files, but I will also clean these out in a PR for secrets.

backup-replication: remove a ton of useless variability

---

openstack/keystone/Chart.lock
openstack/keystone/Chart.yaml
openstack/keystone/templates/_helpers.tpl
openstack/keystone/templates/deployment-api.yaml
openstack/keystone/templates/deployment-cron.yaml
openstack/keystone/templates/job-migration.yaml

Jobs cannot be changed, so all settings need result in a new job-name.

[Keystone] Generate job-name from proxysql settings

---

openstack/cronus/values.yaml

removed ou=postfix from baseDN

Adjusted baseDN for postfix search

---

openstack/designate-nanny/templates/config.yaml
openstack/designate-nanny/templates/job.yaml
openstack/designate-nanny/values.yaml

new version, config now read by nanny from yaml file generated via charts

[designate-nanny] new nanny version and new configuration

---

openstack/designate-nanny/templates/job.yaml

yaml was invalid due to paste buffer added to template by mistake...

[designate-nanny] fixing paste buffer mistake in volume claim

---

common/mariadb/Chart.yaml
common/mariadb/templates/deployment.yaml
common/mariadb/values.yaml

Service owner can set enabled: True to enable, by default its false

[mariadb][common] Enable VPA for mariadb container

---

prometheus-exporters/ipmi-exporter/alerts/metal-ironic.alerts

[ipmi-exporter] remove the region label

---

openstack/manila/Chart.lock
openstack/manila/Chart.yaml
openstack/manila/templates/api-deployment.yaml
openstack/manila/templates/api-ingress.yaml
openstack/manila/templates/api-service.yaml
openstack/manila/templates/bin-configmap.yaml
openstack/manila/templates/etc-configmap.yaml
openstack/manila/templates/migration-job.yaml
openstack/manila/templates/scheduler-deployment.yaml
openstack/manila/templates/seeds.yaml
openstack/manila/templates/shares/_netapp-configmap.yaml.tpl
openstack/manila/templates/shares/_netapp-deployment.yaml.tpl
openstack/manila/templates/shares/_share-netapp.conf.tpl
openstack/manila/templates/type-assignment-seeds.yaml
openstack/manila/templates/type-seeds.yaml
openstack/manila/values.yaml

make more options configurable
Most of the things are separated by the chart name
and will change when used in an dependent chart with different name.

[manila] prep for antelope chart

---

common/mariadb/Chart.yaml
common/mariadb/templates/deployment.yaml

Move main-container annotation to the mariadb deployment

---

openstack/manila-antelope/.helmignore
openstack/manila-antelope/Chart.lock
openstack/manila-antelope/Chart.yaml
openstack/manila-antelope/values.yaml

to be run in parallel, modelled as depedent chart

[manila] add chart for antelope release

---

system/infra-monitoring/Chart.lock
system/infra-monitoring/Chart.yaml
system/infra-monitoring/templates/_prometheus-infra-collector.yaml.tpl
system/infra-monitoring/templates/scrapeconfig-jumpserver.yaml

jumpserver scrapeConfig adapted to new netbox plugin updating Thanos dependency to latest available

moving jumpserver to scrapeConfig

---

openstack/prometheus-openstack/Chart.lock
openstack/prometheus-openstack/Chart.yaml
system/prometheus-kubernetes/Chart.lock
system/prometheus-kubernetes/Chart.yaml
system/storage-monitoring/Chart.lock
system/storage-monitoring/Chart.yaml

absent(thanos_bucket_store_series_gate_queries_duration_seconds_bucket) would always fire, let's get rid of it

bump thanos to get rid of absent alert

---

openstack/pyroscope/.helmignore
openstack/pyroscope/Chart.lock
openstack/pyroscope/Chart.yaml
openstack/pyroscope/values.yaml

Grafana pyroscope is more current but AGPL 3.0 instead of Apache 2.0

[pyroscope] Wrapper for pyroscope-io/pyroscope

---

openstack/poller/values.yaml

The chart had invalid values as defaults. I believe these values are also optional. IMO, For optional values, no default should be supplied, for required values that do not have a valid default, we should rather use the required function.

removing invalid defaults

---

openstack/hermes/elktools/templates/elasticsearch-restore.yaml
openstack/hermes/templates/_hermes.conf.tpl
openstack/hermes/templates/etc/_logstash.conf.tpl

setting one conf, only using opensearch

switch to one variable group for host

---

openstack/ironic/Chart.lock
openstack/ironic/Chart.yaml

Ironic: update chart dependencies

---

system/kubernikus-admin-k3s/Chart.yaml
system/kubernikus-admin-k3s/values.yaml
system/kubernikus-metal/Chart.yaml
system/kubernikus-metal/values.yaml

Bumps kubernikus image in control plane to latest version, supports k8s 1.28.3.

Bump kubernikus image in control plane

---

global/thanos-global/Chart.lock
global/thanos-global/Chart.yaml
openstack/prometheus-openstack/Chart.lock
openstack/prometheus-openstack/Chart.yaml
system/infra-monitoring/Chart.lock
system/infra-monitoring/Chart.yaml
system/prometheus-infra/Chart.lock
system/prometheus-infra/Chart.yaml
system/prometheus-kubernetes/Chart.lock
system/prometheus-kubernetes/Chart.yaml
system/storage-monitoring/Chart.lock
system/storage-monitoring/Chart.yaml
system/thanos-metal/Chart.lock
system/thanos-metal/Chart.yaml
system/thanos-scaleout/Chart.lock
system/thanos-scaleout/Chart.yaml
system/vmware-monitoring/Chart.lock
system/vmware-monitoring/Chart.yaml

Latest greatest.
Ease debugging and avoid hunting errors which occur due to different versions.

bump to latest common chart

---

openstack/utils/Chart.yaml
openstack/utils/templates/_proxysql.tpl

Included template at the wrong level of conditions, so it would always appear if proxysql is enabled or not

[openstack/utils] Fix trust-bundle in proxysql

---

system/kube-system-virtual/Chart.yaml
system/kube-system-virtual/values.yaml

Fix velero pod annotation to avoid double scraping (try 3)

---

openstack/designate-nanny/templates/deployment.yaml

enabling the pods to get scraped

[designate-nanny] add prometheus scraping to designate-nanny pod

---

common/mariadb-galera/helm/.helmignore
common/mariadb-galera/helm/tests/statefullset-mariadb_test.yaml

add the first unit tests example to test mariadb-galera cluster
statefulset

 [mariadb-galera] add unit testing for statefulset

---

common/mariadb-galera/CHANGELOG.md
common/mariadb-galera/README.md
common/mariadb-galera/helm/Chart.yaml
common/mariadb-galera/helm/templates/cronjob-kopia-backup.yaml
common/mariadb-galera/helm/templates/deployment-haproxy.yaml
common/mariadb-galera/helm/templates/deployment-kopia-server.yaml
common/mariadb-galera/helm/templates/job-kopia-restore.yaml
common/mariadb-galera/helm/templates/job-mariadb-config.yaml
common/mariadb-galera/helm/templates/statefulset-mariadb.yaml
common/mariadb-galera/helm/templates/statefulset-proxysql.yaml
common/mariadb-galera/helm/values.yaml

[mariadb-galera] linkerd annotation support added

---

common/mariadb-galera/CHANGELOG.md
common/mariadb-galera/README.md
common/mariadb-galera/helm/Chart.yaml

- chart version bumped and uploaded

[mariadb-galera] fixes from 0.20.4 added

---

system/plutono/Chart.yaml
system/plutono/templates/plutono-ingress.yaml

to align with https://github.com/sapcc/helm-charts/pull/5469

plutono: re-adds ingress annotations

---

openstack/octavia/values.yaml

Enabling linkerd in values.yaml

Enabling linkerd in values.yaml

---

prometheus-exporters/ironic-exporter/ci/test-values.yaml
prometheus-exporters/ironic-exporter/templates/deployment.yaml

Not testing for required values causes confusing errors, and we need to add values for the ci to test.

[ironic-exporter] Raise error on missing values and add ci values

---

common/owner-info/Chart.yaml
common/owner-info/templates/configmap.yaml

see https://helm.sh/docs/topics/charts_hooks/#the-available-hooks

owner-info: properly clean up configmap when doing helm uninstall

---

openstack/cronus/values.yaml

Reverts sapcc/helm-charts#5731

Revert "Cronus - under owner-info I've added service to resolve greenhouse alert"

---

common/prometheus-server/CHANGELOG.md
common/prometheus-server/Chart.yaml
common/prometheus-server/templates/alerts/_prometheus.alerts.tpl

Avoid over sensitive alerting.

soften out of order condition

---

openstack/neutron/templates/asr_config_agents/_deployment-asr1k.yaml.tpl
openstack/neutron/templates/deployment-aci-agent.yaml
openstack/neutron/templates/deployment-cc-fabric-agent.yaml
openstack/neutron/templates/deployment-ironic-agent.yaml
openstack/neutron/templates/deployment-nsxv3-logstash.yaml
openstack/neutron/templates/deployment-rpc-server.yaml
openstack/neutron/templates/deployment-server.yaml
openstack/neutron/templates/deployment-ucs-bm-ml2-agent.yaml
openstack/neutron/templates/sftp-deployment.yaml
openstack/neutron/templates/statefulset-network-agent-apod.yaml
openstack/neutron/templates/vct-nsxv3-agent-deployment.yaml
openstack/neutron/values.yaml

This PR adds annotation required for VPA and modifies values file to support it.

[neutron] Add VPA support

---

system/unbound/ci/test-values.yaml
system/unbound/templates/deployment.yaml
system/unbound/values.yaml

use the "latest" tag as a placeholder
use proper production tags in your secrets
set the image pull policy to "Always"
"IfNotPresent" does not work reliably with the "latest" tag

[unbound] -- restructured the image/image_tag values

---

openstack/octavia/templates/octavia-api-deployment.yaml
openstack/octavia/templates/octavia-f5-as3-deployment.yaml
openstack/octavia/templates/octavia-housekeeping.yaml
openstack/octavia/templates/octavia-worker-deployment.yaml
openstack/octavia/values.yaml

This adds VPA support to Octavia and enables it. It is adding annotations to Deployment objects.

Adding VPA annotations and support in values

---

openstack/cinder/templates/_helpers.tpl
openstack/cinder/templates/api-deployment.yaml
openstack/cinder/templates/backup_deployment.yaml
openstack/cinder/templates/migration-job.yaml
openstack/cinder/templates/scheduler-deployment.yaml
openstack/cinder/templates/vcenter_datacenter_cinder_deployment.yaml
openstack/cinder/values.yaml

Please look at the individual commits for detail.

Fix migration job name, move kubernetes-entrypoint logic to init-container, plus cleanup

---

openstack/keystone/Chart.yaml
openstack/keystone/values.yaml

- to avoid sub chart rendering if disabled

[keystone] mariadb_galera.enabled value added

---

openstack/nova/templates/_console_deployment.yaml.tpl
openstack/nova/templates/api-deployment.yaml
openstack/nova/templates/api-metadata-deployment.yaml
openstack/nova/templates/bigvm-deployment.yaml
openstack/nova/templates/cell2-conductor-deployment.yaml
openstack/nova/templates/conductor-deployment.yaml
openstack/nova/templates/console-shellinabox-deployment.yaml
openstack/nova/templates/hypervisors/_ironic-deployment.yaml.tpl
openstack/nova/templates/hypervisors/_kvm-deployment.yaml.tpl
openstack/nova/templates/hypervisors/hypervisors-vmware-deployment-vct.yaml
openstack/nova/templates/scheduler-deployment.yaml
openstack/nova/templates/vspc-deployment.yaml
openstack/nova/values.yaml

This adds optional VPA support to Nova. VPA support can be enabled/disabled through values.yaml file.
More details about VPA here https://operations.global.cloud.sap/docs/devops/kubernetes/resource-mgmt/

[nova] Adding VPA support

---

openstack/prometheus-openstack/Chart.lock
openstack/prometheus-openstack/Chart.yaml
system/infra-monitoring/Chart.lock
system/infra-monitoring/Chart.yaml
system/prometheus-infra/Chart.lock
system/prometheus-infra/Chart.yaml
system/prometheus-kubernetes/Chart.lock
system/prometheus-kubernetes/Chart.yaml
system/storage-monitoring/Chart.lock
system/storage-monitoring/Chart.yaml
system/vmware-monitoring/Chart.lock
system/vmware-monitoring/Chart.yaml

bringing in softened out of order samples alert

bump to latest common

---

openstack/cinder/templates/backup_deployment.yaml

[cinder] Fix the indentation of the init-containers in the backup

---

openstack/utils/Chart.yaml
openstack/utils/templates/_trust_bundle.tpl

Fixup to "Set SSL_CERT_FILE specifically", we do not want to set the variable unless explicilty requested.

[openstack/utils] Makex "Set SSL_CERT_FILE specifically" conditional

---

openstack/glance/Chart.lock
openstack/glance/Chart.yaml
openstack/glance/templates/_helpers.tpl
openstack/glance/templates/deployment.yaml
openstack/glance/templates/migration-job.yaml
openstack/glance/values.yaml

- Enable trust-bundle explicitly (as the default is false).
- Set env variable to ensure the cert bundle is used.

[glance] Fix trust-bundle

---

common/prometheus-server/Chart.yaml
common/prometheus-server/templates/vpa.yaml
common/prometheus-server/values.yaml

big regions need to be adapted, if they need 10GB memory or more for their Prometheus

setting vpa defaults

---

system/thanos-metal/Chart.yaml
system/thanos-metal/alerts/thanos-regional.alerts
system/thanos-metal/templates/alerts_regional.yaml

formatting fixed
name should not be prefixed with alerts-

formatting and name

---

prometheus-rules/prometheus-controlplane-rules/Chart.yaml
prometheus-rules/prometheus-controlplane-rules/templates/prometheus-sre-rules.yaml
prometheus-rules/prometheus-controlplane-rules/values.yaml

https://github.wdf.sap.corp/cc/team-observability/issues/121

slo based alerts for api availability

---

openstack/hermes/values.yaml

Simple adjustment to make it saner to view the globals settings in values.

[hermes] merge global settings in values

---

openstack/hermes/templates/api-ingress.yaml

Error in the annotations starting with an if statement for another value

[hermes] fix if statement on ingress annotations

---

openstack/hermes/Chart.lock
openstack/hermes/Chart.yaml

[hermes] remove es chart

---

openstack/ironic/values.yaml

This increases the frequency to three times.

[ironic] Run certrobot now Mo,Wed,Fri at 8am

---

openstack/hermes/templates/etc/_audit.json.tpl

keyword to filterable fields for hermes.

[hermes] add keyword to audit es template

---

openstack/maia/Chart.lock
openstack/maia/Chart.yaml

Missing Chart, that's the problem.

[maia] linkerd chart adding

---

openstack/hermes/templates/etc/_audit.json.tpl

Added missing keyword fields we require for doing aggregations and sorting.

[hermes] additional keyword audit mapping required

---

openstack/neutron/templates/etc/_neutron-policy.json.tpl

Allow listing of neutron flavors to everyone.

[neutron] Policy to allow public flavor listings

---

system/kube-system-admin-k3s/Chart.lock
system/kube-system-admin-k3s/Chart.yaml
system/kube-system-admin-k3s/values.yaml

let's test it in qa env first.

Bump cert-manager chart version

---

system/bind/values.yaml

updating bind images to latest version

[dns][bind] updating image version

---

system/digicert-issuer/Chart.yaml
system/digicert-issuer/templates/clusterrole.yaml
system/digicert-issuer/templates/deployment.yaml
system/digicert-issuer/templates/role.yaml
system/digicert-issuer/values.yaml
system/kube-system-admin-k3s/values.yaml
system/kube-system-global/values.yaml
system/kube-system-kubernikus/values.yaml
system/kube-system-metal/values.yaml
system/kube-system-scaleout/values.yaml
system/kube-system-virtual/values.yaml

Bump with the recent [changes](https://github.com/sapcc/digicert-issuer/pull/10)

Bump digicert-issuer version

---

system/kube-system-admin-k3s/Chart.yaml
system/kube-system-global/Chart.yaml
system/kube-system-kubernikus/Chart.yaml
system/kube-system-metal/Chart.yaml
system/kube-system-metal/values.yaml
system/kube-system-scaleout/Chart.yaml
system/kube-system-virtual/Chart.yaml
system/kube-system-virtual/values.yaml

Follow-up for the https://github.com/sapcc/helm-charts/pull/5944

Update def issuer

---

common/linkerd-support/Chart.yaml
common/linkerd-support/templates/namespace-annotation.yaml

This should fix helm rollback.

linkerd-support: delete hook job before creating it

---

prometheus-exporters/openstack-exporter/templates/openstack-exporter-openstack-config.yaml
prometheus-exporters/openstack-exporter/templates/openstack-exporter-seed.yaml

this will allow manila backend collector to get the pool detail metrics && service list metrics
https://github.com/sapcc/openstack-exporter/pull/17/files

manila backend metrics (pool detail) && service list

---

common/rabbitmq/Chart.yaml
common/rabbitmq/templates/bin-secret.yaml
common/rabbitmq/templates/deployment.yaml
common/rabbitmq/templates/statefulset.yaml

The script contains credentials, and is therefore a secret.

[rabbitmq] Move setup script to secret

---

common/redis/Chart.yaml
common/redis/templates/_helpers.tpl
common/redis/templates/deployment.yaml
common/redis/templates/metrics-deployment.yaml
common/redis/values.yaml

Also, simplify some templating to remove useless variability.

common/redis: replace library/redis with base-images/redis

---

prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_siem_error.cfg

Increased the SrcSiemRulesUpdaterLogError time to 1h of continuing alert

Increased the SrcSiemRulesUpdaterLogError time to 1h of continuing alert

---

global/thanos-global/Chart.lock
global/thanos-global/Chart.yaml
openstack/prometheus-openstack/Chart.lock
openstack/prometheus-openstack/Chart.yaml
system/infra-monitoring/Chart.lock
system/infra-monitoring/Chart.yaml
system/prometheus-infra/Chart.lock
system/prometheus-infra/Chart.yaml
system/prometheus-kubernetes/Chart.lock
system/prometheus-kubernetes/Chart.yaml
system/storage-monitoring/Chart.lock
system/storage-monitoring/Chart.yaml
system/thanos-metal/Chart.lock
system/thanos-metal/Chart.yaml
system/thanos-scaleout/Chart.lock
system/thanos-scaleout/Chart.yaml
system/vmware-monitoring/Chart.lock
system/vmware-monitoring/Chart.yaml

upgrade thanos to latest common chart

---

global/thanos-global/Chart.lock
global/thanos-global/Chart.yaml
openstack/prometheus-openstack/Chart.lock
openstack/prometheus-openstack/Chart.yaml
system/infra-monitoring/Chart.lock
system/infra-monitoring/Chart.yaml
system/prometheus-infra/Chart.lock
system/prometheus-infra/Chart.yaml
system/prometheus-kubernetes/Chart.lock
system/prometheus-kubernetes/Chart.yaml
system/storage-monitoring/Chart.lock
system/storage-monitoring/Chart.yaml
system/thanos-metal/Chart.lock
system/thanos-metal/Chart.yaml
system/thanos-scaleout/Chart.lock
system/thanos-scaleout/Chart.yaml
system/vmware-monitoring/Chart.lock
system/vmware-monitoring/Chart.yaml

upgrade thanos across the releases

---

global/thanos-global/Chart.lock
global/thanos-global/Chart.yaml
openstack/prometheus-openstack/Chart.lock
openstack/prometheus-openstack/Chart.yaml
system/infra-monitoring/Chart.lock
system/infra-monitoring/Chart.yaml
system/prometheus-infra/Chart.lock
system/prometheus-infra/Chart.yaml
system/prometheus-kubernetes/Chart.lock
system/prometheus-kubernetes/Chart.yaml
system/storage-monitoring/Chart.lock
system/storage-monitoring/Chart.yaml
system/thanos-metal/Chart.lock
system/thanos-metal/Chart.yaml
system/thanos-scaleout/Chart.lock
system/thanos-scaleout/Chart.yaml
system/vmware-monitoring/Chart.lock
system/vmware-monitoring/Chart.yaml

compactor deploy strategy changed

thanos bump

---

global/prometheus-alertmanager-operated/Chart.lock
global/prometheus-alertmanager-operated/Chart.yaml
global/prometheus-alertmanager-operated/values.yaml

bringing in clusterLabel change with updated prometheus-operator

switch to latest version

---

openstack/cronus/templates/nebula/_config.yaml.tpl

In relation to https://github.wdf.sap.corp/cc/secrets/pull/13597

Add PostfixDNS configuration

---

system/kube-monitoring-admin-k3s/Chart.lock
system/kube-monitoring-admin-k3s/Chart.yaml
system/kube-monitoring-kubernikus/Chart.lock
system/kube-monitoring-kubernikus/Chart.yaml
system/kube-monitoring-metal/Chart.lock
system/kube-monitoring-metal/Chart.yaml
system/kube-monitoring-scaleout/Chart.lock
system/kube-monitoring-scaleout/Chart.yaml
system/kube-monitoring-virtual/Chart.lock
system/kube-monitoring-virtual/Chart.yaml
system/kube-system-admin-k3s/Chart.lock
system/kube-system-admin-k3s/Chart.yaml
system/kube-system-global/Chart.lock
system/kube-system-global/Chart.yaml
system/kube-system-kubernikus/Chart.lock
system/kube-system-kubernikus/Chart.yaml
system/kube-system-metal/Chart.lock
system/kube-system-metal/Chart.yaml
system/kube-system-scaleout/Chart.lock
system/kube-system-scaleout/Chart.yaml
system/kube-system-virtual/Chart.lock
system/kube-system-virtual/Chart.yaml
system/prometheus-operator/Chart.lock
system/prometheus-operator/Chart.yaml
system/prometheus-operator/values.yaml

newer crds are breaking, see details in #5988

rolling back to latest working version

---

common/pgbackup/Chart.yaml
common/postgresql-ng-test/Chart.lock
common/postgresql-ng-test/Chart.yaml
common/postgresql-ng/bin/init-generate-secrets.sh
common/postgresql-ng/docker/entrypoint.sh
common/postgresql-ng/templates/_helpers.tpl
common/postgresql-ng/templates/configmap.yaml
common/postgresql-ng/templates/deployment.yaml
common/postgresql-ng/values.yaml

postgres-ng: more fixes

---

system/plutono/Chart.yaml
system/plutono/templates/plutono-deployment.yaml

Adjusted config to deal with the breaking changes

plutono: upgrade git-sync to v4

---

system/vmware-monitoring/Chart.yaml
system/vmware-monitoring/templates/collector-configmap.yaml

Enables https://github.com/sapcc/vrops-exporter/pull/266

vmware-monitoring: SDRSPropertiesCollector added

---

openstack/manila/Chart.lock
openstack/manila/Chart.yaml
openstack/manila/values.yaml

- [manila] bump utils + rabbitmq
- [manila] enable rabbitmq persistence

[manila] rabbit persist

---

prometheus-exporters/octobus-query-exporter/vendor/octobus-query-exporter-global/files/queries/logshipping/logshipping_vmwaretooling.cfg

- Include query to enable memory leak logs document count metric

[octobus-query-exporter] Add ES query

---

system/validation/values.yaml

validation test: make sure there is always a disable reason

[cc3test] latest validation test version

---

system/kubernikus-admin-k3s/Chart.lock
system/kubernikus-admin-k3s/Chart.yaml
system/kubernikus-admin-k3s/values.yaml

Includes these changes https://github.com/sapcc/kubernikus/commit/4fdd798ce08ecf0a65c8e8989828322c9d709ab1

Enable soft-anti-affinity for newly created nodes in openstack

---

openstack/sap-seeds/templates/_flavors_hana_exclusive.tpl

There are issues with large reservations.

nova/flavors: Disable CPU reservation temporarily

---

system/metis-api/values.yaml
system/metis/values.yaml

see https://github.com/sapcc/helm-charts/blob/73c77c60d1ecb2520e6ae69224477bb033be9844/common/linkerd-support/values.yaml#L4

metis,metis-api: don't overwrite linkerd-enabled

---

common/prometheus-server/Chart.yaml
common/prometheus-server/templates/ingress.yaml

common/prometheus-server: unify ingress oauth annotations

---

openstack/neutron/templates/etc/_dhcp-agent.ini.tpl

defaulting to False
More info here:
https://github.com/sapcc/neutron/commit/d5301166b3afa89fe2cee3e7fd9de43750509729

[neutron] -- introducing the edns_client_fingerprint option

---

system/plutono/Chart.lock
system/plutono/Chart.yaml
system/plutono/templates/_plutono.ini.tpl
system/plutono/templates/plutono-deployment.yaml
system/plutono/values.yaml

plutono: moved to postgresql-ng

---

prometheus-exporters/openstack-exporter/Chart.lock
prometheus-exporters/openstack-exporter/Chart.yaml
prometheus-exporters/openstack-exporter/templates/openstack-exporter-deployment.yaml
prometheus-exporters/openstack-exporter/values.yaml

This patch adds linkerd chart dependency and by default enables the value of
linkerd_requested = true

[Openstack Exporter] add linkerd support

---

openstack/utils/Chart.yaml
openstack/utils/templates/_helpers.tpl
openstack/utils/templates/_linkerd.tpl

Please see the individual commits' messages for details.

[openstack/utils] Support linkerd Job shutdown and add `job_finished_hook`

---

openstack/neutron/templates/statefulset-network-agent-apod.yaml
openstack/neutron/templates/statefulset-network-agent.yaml
openstack/neutron/templates/statefulset-swift-injector.yaml

Our stateful deployments still miss linkerd annotations
Basic support has been added in
https://github.com/sapcc/helm-charts/pull/5606/files

I544510 linkerd annotations neutron

---

openstack/maia/Chart.yaml
openstack/maia/templates/etc/_maia_scrape_config.yaml.tpl

The ingress is with 2FA enabled since today.

maia: use prometheus-infra-internal

---

openstack/manila/templates/api-deployment.yaml
openstack/manila/templates/bin/_db_migrate.sh.tpl
openstack/manila/templates/etc-configmap.yaml
openstack/manila/templates/etc/_healthz.tpl
openstack/manila/templates/etc/_manila.conf.tpl
openstack/manila/templates/etc/_secrets.conf.tpl
openstack/manila/templates/migration-job.yaml
openstack/manila/templates/scheduler-deployment.yaml
openstack/manila/templates/secrets.yaml
openstack/manila/templates/shares/_netapp-configmap-secret.yaml.tpl
openstack/manila/templates/shares/_netapp-deployment.yaml.tpl
openstack/manila/templates/shares/_netapp-ensure-deployment.yaml.tpl
openstack/manila/templates/shares/_share-netapp-secret.conf.tpl
openstack/manila/templates/shares/_share-netapp.conf.tpl

- Configs with secrets will be projected into /etc/manila/manila.conf.d/
- And /etc/manila/backend-secret.conf

[manila] move configuration with credentials into own secrets

---

prometheus-exporters/openstack-exporter/alerts/cinder.alerts

- Re-add backend label for Alertmanager availability, restoring functionality for AICloudGuard remediation

[openstack-exporter] Revise CinderShardFreeSpace alerts

---

openstack/designate-nanny/Chart.yaml
openstack/designate-nanny/templates/deployment.yaml
openstack/designate-nanny/values.yaml

Adding the dependency and annotation for linkerd

[designate-nanny] adding linkderd annotations to deployment

---

openstack/elektra/templates/seed.yaml

Hi,
I created a separate PR this time to test if there are any issues with `_` in the btp_fp domain.
Regards,
Rajiv

[Elektra] Add BTP_FP Domain to elektra seeds

---

openstack/designate/templates/seeds.yaml

Values started to not being interpolated correctly - removing " fixes parser errors it seems.

[designate] fix for failing interpolation of values in the template

---

openstack/cc3test/Chart.yaml
openstack/cc3test/alerts/ccloud-hermes.alerts
openstack/cc3test/alerts/ccloud-maia.alerts

Maia and Hermes, do not alert when Keystone is down

cc3test: do not alert Hermes or Maia when Keystone is down

---

system/thanos-metal/Chart.yaml
system/thanos-metal/values.yaml
system/thanos-scaleout/Chart.yaml
system/thanos-scaleout/values.yaml

more and more compactors are fully utlizing the 25G eph storage.
This shall avoid ongoing maintenance efforts

enabling volumes

---

openstack/placement/Chart.lock
openstack/placement/Chart.yaml
openstack/placement/templates/proxysql-configmap.yaml
openstack/placement/templates/proxysql-secret.yaml

- switch to set the new mariadb values initdb_secret instead of initdb_configmaps

[placement][mariadb][rabbitmq][utils] bump up mariadb, utils for placement

---

common/mariadb/Chart.yaml
common/mariadb/templates/_helpers.tpl
common/mariadb/templates/deployment.yaml
common/mariadb/templates/secret.yaml

[mariadb] fetch metrics data source from secret

---

system/greenhouse-ccloud/Chart.yaml
system/greenhouse-ccloud/templates/alerts-plugin.yaml
system/greenhouse-ccloud/templates/doop-plugin.yaml
system/greenhouse-ccloud/templates/heureka-plugin.yaml
system/greenhouse-ccloud/templates/teams2slack-plugin.yaml

**DO NOT MERGE** this will be done after the CRDs have been migrated

feat(greenhouse): rename pluginconfig crds

---

openstack/octavia/templates/etc/_octavia-worker.conf.tpl
openstack/octavia/templates/etc/_octavia.conf.tpl
openstack/octavia/templates/etc/_secrets-worker.conf.tpl
openstack/octavia/templates/etc/_secrets.conf.tpl
openstack/octavia/templates/octavia-api-deployment.yaml
openstack/octavia/templates/octavia-housekeeping.yaml
openstack/octavia/templates/octavia-migration-job.yaml
openstack/octavia/templates/octavia-worker-deployment.yaml
openstack/octavia/templates/secrets-worker.yaml
openstack/octavia/templates/secrets.yaml

- Secrets config will be projected into /etc/octavia/octavia.conf.d/

[octavia] move configuration with credentials into own secrets

---

common/mariadb/Chart.yaml
common/mariadb/templates/initdb/_configuredb.sh.tpl

remove the cat command which exposes the secrets in the configurator script.

[mariadb] remove exposing secret in configurator

---

openstack/manila-nanny/alerts/manila.alerts
prometheus-exporters/netapp-exporter/charts/netapp-cap-exporter/alerts/netapp-capacity.alerts

need netapp filer access and knowledge to solve those

[netapp-exporter] move some alerts to storage

---

openstack/ironic/Chart.lock
openstack/ironic/Chart.yaml

allows local connections without a password

Ironic: upgrade mariadb to 0.10.1

---

system/greenhouse-ccloud/templates/alerts-plugin.yaml

indentation was the actual problem here

fix(greenhouse): not multiline string but yaml list

---

openstack/manila/Chart.lock
openstack/manila/Chart.yaml

[manila] upgrade mariadb to 0.10.1

---

openstack/barbican/Chart.lock
openstack/barbican/Chart.yaml

[barbican] upgrade mariadb to 0.10.1

---

openstack/designate/Chart.lock
openstack/designate/Chart.yaml

[designate] upgrade mariadb to 0.10.1

---

openstack/keppel/Chart.lock
openstack/keppel/Chart.yaml
openstack/keystone/Chart.lock
openstack/keystone/Chart.yaml
openstack/limes/Chart.lock
openstack/limes/Chart.yaml
openstack/swift-drive-autopilot/Chart.lock
openstack/swift-drive-autopilot/Chart.yaml
openstack/swift-utils/Chart.lock
openstack/swift-utils/Chart.yaml
openstack/swift/Chart.lock
openstack/swift/Chart.yaml
system/kube-system-metal/Chart.lock
system/kube-system-metal/Chart.yaml

and avoiding cycling keppel dependency

[limes, keppel] switch from chartmuseum to oci registry

---

openstack/cc3test/alerts/file-shares.alerts

updated manila playbook links inside alerts

[cc3test]: updated manila playbook links inside alerts

---

common/rabbitmq/CHANGELOG.md
common/rabbitmq/Chart.yaml
common/rabbitmq/templates/_helpers.tpl
common/rabbitmq/templates/alerts.yaml
common/rabbitmq/templates/bin-secret.yaml
common/rabbitmq/templates/custom-conf-configmap.yaml
common/rabbitmq/templates/deployment.yaml
common/rabbitmq/templates/headless-service.yaml
common/rabbitmq/templates/poddisruptionbudget.yml
common/rabbitmq/templates/pvc.yaml
common/rabbitmq/templates/service.yaml
common/rabbitmq/templates/servicemonitor.yaml
common/rabbitmq/templates/statefulset.yaml

Add standardised labels to all objects, according to https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels

[rabbitmq] Add standardised labels to all objects

---

common/mariadb/Chart.yaml
common/mariadb/templates/_helpers.tpl
common/mariadb/templates/alerts.yaml
common/mariadb/templates/backup-etc-secret.yaml
common/mariadb/templates/backup-v2-deployment.yaml
common/mariadb/templates/backup-verify-deploy.yaml
common/mariadb/templates/client-secret.yaml
common/mariadb/templates/configuredb-configmap.yaml
common/mariadb/templates/deployment.yaml
common/mariadb/templates/etc-configmap.yaml
common/mariadb/templates/initdb-secret.yaml
common/mariadb/templates/pre-change-job.yaml
common/mariadb/templates/secret.yaml
common/mariadb/templates/service.yaml

Add standardised labels to all Kubernetes objects according to 
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels and
https://helm.sh/docs/chart_best_practices/labels/

[mariadb] Add standardised labels

---

common/mariadb-galera/README.md
common/mariadb-galera/docker/haproxy/Dockerfile
common/mariadb-galera/docker/haproxy/bin/common-functions.sh
common/mariadb-galera/docker/haproxy/bin/entrypoint.sh
common/mariadb-galera/docker/haproxy/config/haproxy.cfg
common/mariadb-galera/helm/README.md.gotmpl

- based on our MariaDB image
- to be able to run custom mysql healthchecks that support Galera

[mariadb-galera] Dockerfile for HAProxy added

---

openstack/castellum/files/policy.yaml
openstack/castellum/templates/seed.yaml
openstack/castellum/values.yaml

Merge this when we roll out autogrow quota distribution to prod.

castellum: deactivate quota autoscaling

---

openstack/limes/templates/configmap.yaml

Companion for https://github.com/sapcc/limes/pull/444

limes: adjust policy for removal of PUT quota API

---

system/cc-ceph/ci/test-values.yaml
system/cc-ceph/templates/ceph-config-override.yaml
system/cc-ceph/values.yaml

This PR adds support for keystone config override

ceph: add keystone config-override

---

openstack/manila/templates/shares/_share-netapp.conf.tpl

see https://github.com/sapcc/manila/blob/3aff6a6621bf265780db5ef3370741d1aac915e4/manila/share/driver.py#L47

[manila] fix share from snapshot config option

---

system/cc-ceph/Chart.yaml
system/cc-ceph/templates/_helpers.tpl
system/cc-ceph/templates/ceph-config-override.yaml

add a helper to escape the password

ceph: escape password following the CEPH specs

---

global/prometheus-alertmanager-operated/Chart.yaml
global/prometheus-alertmanager-operated/ci/test-values.yaml
global/prometheus-alertmanager-operated/templates/am-config-route-slack.yaml
global/prometheus-alertmanager-operated/values.yaml

bring back the alert metal channels

global alertmanager: fix slack alert channel templates

---

prometheus-exporters/octobus-query-exporter/vendor/octobus-query-exporter-global/alerts/infra-frontend/logs.alerts

- Update expression
- Add playbook path

[octobus-query-exporter-global] Revise OctoBusVMwareToolingInstanceLogDiscrepancy alert

---

common/memcached/Chart.yaml
common/memcached/templates/_helpers.tpl

- defined functions are shared across all subcharts
- hardcoded values will lead to wrong results

[memcached] sharedservices.labels component name fixed

---

global/prometheus-alertmanager-operated/Chart.yaml
global/prometheus-alertmanager-operated/templates/am-config-route-slack.yaml
global/prometheus-alertmanager-operated/values.yaml

[alertmanager] add capacity-ops support_group

---

openstack/cc3test/alerts/ccloud-jump-server.alerts

it should be fine to fix such problems the next working day

[cc3test] lower CC3TestJumpServerDown to warning

---

openstack/manila/templates/shares/_share-netapp.conf.tpl

revive 16949cf7bf650395086f3ce48c8a3e288729a8cc
instead of changing the code: https://github.com/sapcc/manila/pull/174

[manila] disable replica transfer size check

---

prometheus-rules/prometheus-vmware-rules/alerts/host.alerts

VMsOnFailoverHost severity updated from warning to critical

VMsOnFailoverHost update severity

---

openstack/ironic/py/ironic-node-update.py

The logic was reversed, so I set all non-idrac nodes to idrac, and idrac to ipxe

[ironic] Fixup reverse logic in switch all dell nodes

---

openstack/limes/templates/_utils.tpl
openstack/limes/templates/deployment-data-metrics.yaml

Belongs to <https://github.com/sapcc/limes/pull/471>.

limes: add data-metrics deployment

---

system/validation/templates/deployment.yaml

[cc3test]: skipped few inbound and outbound ports for linkerd to make validation test running

---

openstack/nova/values.yaml

Adding ResizeVcpuMaxUnitFilter to the default_filters

[nova] enable ResizeVcpuMaxUnitFilter

---

openstack/manila/templates/type-seeds.yaml

we'll start with a offering to dedicated clients

[manila] make standard type private

---

system/greenhouse-ccloud/ci/test-values.yaml
system/greenhouse-ccloud/templates/disco-plugins.yaml
system/greenhouse-ccloud/templates/ingress-plugins.yaml

Lets start with a new new plugin config and adopt qa and eu-de-2 later

[greenhouse-ccloud]: Manage ingress and disco plugin configs

---

system/opentelemetry-operator/templates/logs-collector.yaml
system/opentelemetry-operator/values.yaml

Reverts sapcc/helm-charts#6689

Revert "[opentelemetry] base64enc for secrets"

---

.github/CODEOWNERS
common/mysql_metrics/Chart.lock
common/mysql_metrics/Chart.yaml
common/mysql_metrics/templates/_helpers.tpl

add an option when set value `db_type: "galera"` to use mariadb-galera
endpoint. 
Change-Id: I647cdca07475316e839c5bba41fc41f666c78b55
Fix CODEOWNER

[mysql-metrics]add option for galera endpoint

---

prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/etc/rest.custom_snapshot.yaml
prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/templates/_start-poller.sh.tpl
prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/templates/configmap.yaml
prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/templates/deployment_worker.yaml
prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/values.yaml

netapp_snapshot_size
netapp_snapshot_create_time

[netapp] add snapshot size metrics

---

common/mariadb-galera/.gitignore
common/mariadb-galera/CHANGELOG.md
common/mariadb-galera/README.md
common/mariadb-galera/helm/Chart.yaml
common/mariadb-galera/helm/templates/statefulset-mariadb.yaml
common/mariadb-galera/helm/templates/statefulset-proxysql.yaml
common/mariadb-galera/helm/tests/01-default-statefulset_test.yaml
common/mariadb-galera/helm/tests/08-containerimages_test.yaml

- to avoid container/pod startup problems
- unit tests added

fix-fs-permissions init container image path fixed

---

common/memcached/Chart.yaml
common/memcached/ci/test-values.yaml
common/memcached/templates/configmap.yaml
common/memcached/templates/deployment.yaml
common/memcached/templates/secrets.yaml
common/memcached/values.yaml

- optionally allows to set username and password
- that pair will be mounted into sasl_pwdb
- memcached will be started with '-S' sasl enabled
- bump chart

[memcached] enable SASL (Simple Authentication and Security Layer)

---

openstack/keystone/Chart.lock
openstack/keystone/Chart.yaml

bump up mariadb-galera in dependenciesi to version 0.29.1
Change-Id: I6920cd4285bb01f8bf04b071f4d0dcc0f72f2d22

[keystone]bump up mariadb-galera in dependencies

---

common/mysql_metrics/Chart.yaml
common/mysql_metrics/templates/_helpers.tpl

fix helper function to not add a new line to mysql database connection
Change-Id: I15bcbb8440599880e21bfb7ce9b3bc6954678ebb

[mysql-metrics]remove newline from helper function

---

prometheus-exporters/network-generic-ssh-exporter/alerts/asr.alerts

Metric Absent alerting for NetworkAsrHighMemoryUtilization

Metric Absent alerting for NetworkAsrHighMemoryUtilization

---

openstack/maia/Chart.lock
openstack/maia/Chart.yaml

Prometheus v2.53.1
Thanos v0.35.1

maia: upgrade prometheus and thanos versions

---

openstack/cronus/Chart.lock
openstack/cronus/Chart.yaml
openstack/cronus/values.yaml

bump rabbitmq dependency chart to 0.7.3
Fix for RabbitMQRPCUnackTotal alert, add standard labels

[rabbitmq][Cronus] Use prometheus plugin for rabbitmq metrics

---

prometheus-exporters/netapp-exporter/charts/netapp-cap-exporter/alerts/netapp-capacity.alerts
prometheus-exporters/openstack-exporter/aggregations/manila.rules
prometheus-exporters/openstack-exporter/alerts/manila.alerts
prometheus-exporters/openstack-exporter/templates/aggregations.yaml

back to default, tight capacity situation has improved

[netapp-exporter][manila] ManilaAvailabilityZoneUsageHigh alert update

---

system/opensearch-logs/templates/config/_internal_users.yml.tpl
system/opensearch-logs/templates/config/_roles.yml.tpl
system/opensearch-logs/templates/config/_roles_mapping.yml.tpl

this is the helm-charts part of an opensearch user that will be provided by a helm rollout in helm-charts
@d042653
see https://github.wdf.sap.corp/cc/secrets/pull/14850

I748122 opensearch user oraboskvm

---

common/mariadb-galera/CHANGELOG.md
common/mariadb-galera/README.md
common/mariadb-galera/helm/Chart.yaml
common/mariadb-galera/helm/tests/01-default-statefulset_test.yaml
common/mariadb-galera/helm/tests/02-services-mariadb-galera_test.yaml
common/mariadb-galera/helm/values.yaml

linkerd uses this list for inbound ports configuration

[mariadb-galera] Add MariaDB mysql port 3306 to the db containers ports

---

openstack/nova/Chart.yaml
openstack/nova/templates/vspc-service.yaml

to advertise the /32 IP to upstream

[nova-vspc] set service externalTrafficPolicy to Local

---

openstack/arc/templates/api-service.yaml
openstack/arc/values.yaml

to advertise the /32 IP to upstream

[arc] set service externalTrafficPolicy to Local

---

openstack/keppel/templates/seed.yaml

Ref: https://github.com/sapcc/keppel/pull/406

openstack/keppel: advertise LIQUID support

---

openstack/maia/Chart.yaml
openstack/maia/alerts/openstack/maia-prom.alerts

MaiaPrometheusDown is now a `critical` alert.

maia: reviewing and updating alerts

---

openstack/openstack-seeder/Chart.lock
openstack/openstack-seeder/Chart.yaml

Chartmuseum will go away soon.

openstack-seeder: remove chartmuseum

---

system/doop-central/alerts/infra-frontend/violation.alerts

As discussed in the Secure Engineering workgroup.

doop-central: add GkHighlyVulnerableImages alert

---

common/mariadb/Chart.yaml
common/mariadb/templates/_helpers.tpl
common/mariadb/templates/initdb/_init.sql.tpl

Additionally add single quotation to support usage of all special symbols

[mariadb] Add secrets resolving for MariaDB passwords

---

openstack/ironic/templates/seed.yaml

Add a new flavor that is only present in qa-de-1.
Also fix a spelling misstake with the 8S8T flavor

[Ironic] add new QA only flavor

---

common/mariadb/Chart.yaml
common/mariadb/templates/config/_backup_config.yaml.tpl

Quote username and password values with a single quote

[mariadb][backup] Use resolve helper for backup_v2 secrets

---

openstack/ironic/Chart.lock
openstack/ironic/Chart.yaml

- mariadb
- memcached
- mysql_metrics
- rabbitmq
- utils

[ironic] upgrade dependencies

---

openstack/manila/alerts/kubernetes/pod.alerts
openstack/manila/alerts/metrics-metal/pod.alerts
openstack/manila/templates/prometheus-alerts.yaml
openstack/manila/values.yaml

see the individual commit messages

[manila] reduce OpenstackManilaSharePodScaledDown in decom

---

openstack/utils/Chart.yaml
openstack/utils/templates/_hosts.tpl

utils: Add resolve for usernames of mysql and F5 and remove "identity.password_for_user"

---

prometheus-exporters/cronus-exporter/templates/_config.yaml.tpl
prometheus-exporters/cronus-exporter/templates/secrets.yaml

to resolve exporter issues in qa de 1

change secrets from config map to env vars

---

openstack/utils/Chart.yaml
openstack/utils/templates/_hosts.tpl

Use resolve secret with urlquery, because it's an oslo.db connection

[utils] Add support for secrets-injector for db_url_pxc function

---

openstack/keystone/values.yaml

resolves throttling issues triggered by s3tokens

[keystone] remove cpu limits

---

system/greenhouse-ccloud/Chart.yaml
system/greenhouse-ccloud/templates/ceph-operations-storage-pluginpreset.yaml

Adds the `ceph-operations` PluginPreset to ccloud org on Greenhouse

feat(gh-ccloud): Add ceph-operations PluginPreset to ccloud org

---

openstack/manila/Chart.lock
openstack/manila/Chart.yaml
openstack/manila/ci/test-values.yaml

mainly updates mariab chart, should not contain any breaking
changes

[manila] dep up

---

openstack/manila/Chart.lock
openstack/manila/Chart.yaml
openstack/manila/values.yaml

metrics sidecar has been removed

[manila] update rabbitmq

---

openstack/limes/templates/configmap-liquids.yaml
openstack/limes/templates/deployment-liquids.yaml
openstack/limes/values.yaml

Before merging, please merge the respective secrets PR and run the validate-secrets job in CI. Otherwise this will crashloop on deploy to QA due to incomplete config.

limes: add liquid-cinder and liquid-manila

---

system/greenhouse-ccloud/Chart.yaml
system/greenhouse-ccloud/templates/kube-monitoring-storage-pluginpreset.yaml
system/greenhouse-ccloud/templates/thanos-storage-pluginpreset.yaml
system/greenhouse-ccloud/values.yaml

* only scope to storage clusters
* add necessary overrites

feat(thanos): storage fixes

---

openstack/elektra/templates/seed.yaml

Please merge this if (and only if) https://github.com/sapcc/elektra/pull/1412 is merged.

elektra: remove cloud_resource_admin role assignment

---

system/greenhouse-ccloud/Chart.yaml
system/greenhouse-ccloud/templates/thanos-storage-pluginpreset.yaml

fix(thanos): label correction

---

prometheus-exporters/cronus-updater/templates/_config.yaml.tpl
prometheus-exporters/cronus-updater/templates/secrets.yaml

as its being used here
https://github.wdf.sap.corp/cronus/cronus-updater/pull/37/files#diff-2dfb22d0f1851594f707e84219604126ddd4e8c58485b3b9f6a17b81f79aaaabR164

smtp pass as env var

---

openstack/castellum/templates/_utils.tpl

As discussed with @Carthaca @chuan137 @viennaa in Slack.

castellum: use thanos-metal for Manila queries

---

system/greenhouse-ccloud/Chart.yaml
system/greenhouse-ccloud/templates/kube-monitoring-storage-pluginpreset.yaml

inhibition rule needs to this to match

feat(kube-state-metrics): add cluster label

---

system/greenhouse-extras-storage/Chart.yaml
system/greenhouse-extras-storage/templates/metrics-ingress-internal.yaml
system/greenhouse-extras-storage/templates/metrics-ingress.yaml
system/greenhouse-extras-storage/values.yaml

* introducing metrics.st1 urls

feat(thanos): adjusting ingress for thanos

---

prometheus-exporters/blackbox-exporter/Chart.yaml
prometheus-exporters/blackbox-exporter/templates/deployment.yaml

the reloader moved its image to ghcr

Update blackbox exporter configmap reload

---

openstack/hermes/templates/etc/_logstash.conf.tpl

Log and correct malformed project_ids, trying to get more detail on where the data is coming from that is causing a problem with arrays in target project_id

[hermes] log malformed target project_id

---

openstack/limes/alerts/openstack/api.alerts

add alert: OpenstackLimesIneffectiveQuotaOverride

---

openstack/utils/Chart.yaml
openstack/utils/templates/_hosts.tpl

db_host_mysql and db_url_mysql should preserve the past behavior (mariadb)

[utils] Preserve the behavior of db_host_mysql and db_url_mysql functions

---

system/absent-metrics-operator/Chart.yaml
system/absent-metrics-operator/values.yaml

includes https://github.com/sapcc/absent-metrics-operator/pull/224

absent-metrics-operator: update to most recent image

---

openstack/designate/Chart.lock
openstack/designate/Chart.yaml
openstack/designate/templates/_helpers.tpl
openstack/designate/templates/etc/_secrets.conf.tpl
openstack/designate/values.yaml

* Add pxc-db chart as a dependency, conditional on pxc_db.enabled
* Add designate.db_url helper
* Update utils chart to 0.19.1
* Update mysql_metrics chart to 0.3.6

[designate][pxc-db] Add pxc-db chart dependency and sample values

---

openstack/maia/Chart.lock
openstack/maia/Chart.yaml

Prometheus `v2.54.1`
Thanos `v0.36.1`

maia: upgrade prometheus and thanos

---

openstack/ironic/templates/seed.yaml

New flavor for HPE Superdome
https://netbox.global.cloud.sap/dcim/devices/31450/inventory/

Adding HPE Superdome

---

openstack/ceph-seed/Chart.yaml
openstack/ceph-seed/templates/seed.yaml
system/cc-ceph/Chart.yaml
system/cc-ceph/templates/ceph-config-override.yaml
system/cc-ceph/values.yaml

Add initial support for barbican KMS

[ceph] add barbican config support

---

system/cc-ceph/Chart.yaml
system/cc-ceph/templates/cephobjectstore.yaml

fix `tls: failed to verify certificate: x509: certificate is valid for` reconciliation issue

[ceph] advertise endpoints for local reconciliation

---

common/pxc-db/Chart.yaml
common/pxc-db/templates/cluster.yaml
common/pxc-db/values.yaml

Default value in the operator is 10

[pxc-db] Add backoffLimit option for backup jobs and set it to 1

---

common/pxc-db/Chart.yaml
common/pxc-db/templates/_helpers.tpl
common/pxc-db/templates/cluster.yaml

These labels will be used in alerts

[pxc-db] Add missing app and name labels to pxc and pxc-haproxy sts

---

openstack/kmip/Chart.lock
openstack/kmip/ci/test-values.yaml
openstack/kmip/templates/secrets.yaml
openstack/kmip/templates/service.yaml
openstack/kmip/values.yaml

kmip switch to externalIP

---

openstack/designate/Chart.lock
openstack/designate/Chart.yaml

* Fixes application labels
* Sets 4-day TTL for local binlogs
* Fixes init-db RoleBinding name
* Sets backoffLimit for backup job to 1

[designate][pxc-db] Bump pxc-db dependency

---

openstack/octavia/templates/etc/_octavia-worker.conf.tpl

More detail in Octavia issue https://github.wdf.sap.corp/cc/octavia-issues/issues/55

[octavia] rename unsafe mode to unchecked

---

global/thanos-global/Chart.yaml
global/thanos-global/alerts/thanos-global.alerts

* added more precise alert with warning severity for non reachable store
* adding generic alert for non queryable Greenhouse Thanos

greenhouse added; alerting refined

---

common/pxc-db/Chart.yaml
common/pxc-db/ci/test-values.yaml
common/pxc-db/templates/_helpers.tpl
common/pxc-db/templates/alerts.yaml
common/pxc-db/templates/alerts/_pxc.alerts.tpl

Based on the percona_cluster alerts

[pxc-db] Add alerts for MySQL Galera cluster

---

openstack/billing/templates/seeds.yaml
openstack/billing/values.yaml
openstack/limes/templates/prometheus-alerts.yaml

limes: upgrade Plutus user from readonly to readwrite

---

system/cc-ceph/Chart.yaml
system/cc-ceph/templates/cephobjectstore-placement-pools.yaml
system/cc-ceph/values.yaml

[ceph] fix pool placement yaml

---

openstack/limes/alerts/openstack/api.alerts

Companion for https://github.com/sapcc/limes/pull/586.

add alert: OpenstackLimesCinderCapacityWithUnknownVolumeType

---

openstack/manila/templates/shares/_share-netapp.conf.tpl

see https://review.opendev.org/c/openstack/manila/+/803622

[manila] add flexgroup config options

---

openstack/manila/values.yaml

borrowed from 0fdc5c9798d9e259b19148172e6bd17c96e97bd6

[manila] adjusting maxSurge/Unavailable

---

openstack/maia/Chart.yaml
openstack/maia/templates/etc/_maia_scrape_config.yaml.tpl

the more general expression includes metrics 'netapp_snapmirror.*:maia' into federation

[maia][storage] add netapp_snapmirror.*:maia metrics

---

openstack/manila/Chart.lock
openstack/manila/Chart.yaml
openstack/manila/templates/etc/_healthz.tpl
openstack/manila/templates/etc/_secrets.conf.tpl
openstack/manila/templates/seeds.yaml
openstack/manila/templates/shares/_share-netapp-secret.conf.tpl

- **[manila] bump utils**
- **[manila] support secrets-injector**

[manila] secrets injector support

---

openstack/glance/Chart.lock
openstack/glance/Chart.yaml
openstack/glance/ci/test-values.yaml

There are no major changes introduced

[Glance] upgrade to Openstack Dalmatian

---

openstack/designate/Chart.lock
openstack/designate/Chart.yaml

Update following charts:
- utils: 0.19.3 -> 0.19.6
- pxc-db: 0.1.7 -> 0.1.12
- linkerd-support: 1.0.0 -> 1.1.0
- rabbitmq: 0.11.0 -> 0.11.3

[designate] update dependencies

---

openstack/designate/Chart.lock
openstack/designate/Chart.yaml

[designate][pxc-db] Update pxc-db dependency to 0.1.13

---

common/prometheus-server/CHANGELOG.md
common/prometheus-server/Chart.yaml
common/prometheus-server/values.yaml

fix apiserver histogram scraping

---

openstack/hermes/templates/etc/_logstash.conf.tpl

testing on branch first in qa. slightly difficult because we're catching malformed events, and it triggers when we hit one, but hopefully it being correct as it's global, and checking everything, will solve the issue regardless.

replace with global logger.

---

system/bind/ci/test-values.yaml
system/bind/templates/deployment.yaml
system/bind/values.yaml

Also, use the "latest" tag in the helm charts.
The secrets will define the actual versions.

[bind] redesigned the image versioning structure

---

openstack/barbican/Chart.yaml
openstack/barbican/templates/api-deployment.yaml
openstack/barbican/templates/etc/_barbican_lunaclient.sh.tpl
openstack/barbican/values.yaml

upgrades lunaclient version to 10.7.2, enables STC dir, firmware 7.7.1 needs 001/token_v2.db

[HSM] bump lunaclient version to r9.1

---

system/cc-ceph/templates/ceph-config-override.yaml
system/cc-ceph/templates/ceph-keystone-secret.yaml
system/cc-ceph/templates/cephobjectstore.yaml
system/cc-ceph/values.yaml

Enable keystone integration using rook CRD

[ceph] enable keystone definition in CRD

---

system/bind/templates/deployment.yaml
system/bind/templates/etc/_secret_env.tpl
system/bind/templates/secrets.yaml

Some of our bind images are started using env vars.
Some of these are secret.
We now have a dedicated secret to pull these from.

[bind] introducing secret_env

---

common/mysql_metrics/Chart.yaml
common/mysql_metrics/templates/deployment.yaml
common/mysql_metrics/values.yaml

Update to the latest build with vulnerability fixes
Set kubectl.kubernetes.io/default-container annotation

[mysql_metrics] Update to the latest 0.5.8 ts build

---

openstack/limes/files/policy.yaml

limes: update policy for sapcc/limes#600

---

common/mariadb/Chart.yaml
common/mariadb/templates/backup-v2-deployment.yaml
common/mariadb/templates/backup-verify-deploy.yaml
common/mariadb/templates/deployment.yaml
common/mariadb/values.yaml

- default value added
- config added for backup deployments

[mariadb] priorityClassName updated to new naming convention

---

common/memcached/Chart.yaml
common/memcached/templates/deployment.yaml
common/memcached/values.yaml

[memcached] priorityClassName updated to new naming convention

---

openstack/maia/Chart.yaml
openstack/maia/templates/_helper.tpl
openstack/maia/templates/etc/_maia_scrape_config.yaml.tpl
openstack/maia/values.yaml

https://github.wdf.sap.corp/cc/ceph-project/issues/49

federate ceph metrics

---

common/pxc-db/Chart.yaml
common/pxc-db/templates/cluster.yaml
common/pxc-db/values.yaml

[pxc-db] priorityClassName updated to new naming convention

---

system/awx-crawler/Chart.yaml
system/awx-crawler/templates/job.yaml
system/awx-crawler/templates/pvc.yaml
system/awx-crawler/values.yaml

- Added container `./src` code
- Added helm `values.yaml`, `Chart.yaml` and `./templates`

Add awx-api-crawler for monitoring

---

openstack/barbican/alerts/openstack-barbican.alerts

[Barbican] update loop time for secret expiry alerts

---

common/mariadb/CHANGELOG.md
common/mariadb/Chart.yaml
common/mariadb/templates/_helpers.tpl
common/mariadb/templates/alerts.yaml
common/mariadb/templates/alerts/_mysql.alerts.tpl
common/mariadb/templates/backup-etc-secret.yaml
common/mariadb/templates/backup-ingress.yaml
common/mariadb/templates/backup-v2-deployment.yaml
common/mariadb/templates/backup-v2-serviceaccount.yaml
common/mariadb/templates/backup-verify-deploy.yaml
common/mariadb/templates/client-secret.yaml
common/mariadb/templates/configuredb-configmap.yaml
common/mariadb/templates/db-backup-v2-role.yaml
common/mariadb/templates/db-backup-v2-rolebinding.yaml
common/mariadb/templates/db-exec-rbac.yaml
common/mariadb/templates/deployment.yaml
common/mariadb/templates/etc-configmap.yaml
common/mariadb/templates/initdb-secret.yaml
common/mariadb/templates/pre-change-job.yaml
common/mariadb/templates/pvc.yaml
common/mariadb/templates/secret.yaml
common/mariadb/templates/service.yaml
common/mariadb/values.yaml

* Updates MariaDB to the 10.5.27 version

[mariadb] Update MariaDB to the 10.5.27 version

---

px/arp-discovery/templates/deamonset.yaml
px/bird/templates/_deployment-bird.tpl

Add class names as defined in https://operations.global.cloud.sap /docs/devops/kubernetes/priority-classes/
* arp-discovery: critical-infrastructure
* bird: critical-payload
* lookingGlass: default value (lowest prio)

[px] feat: Add priority class names

---

openstack/designate/Chart.lock
openstack/designate/Chart.yaml

* mysql_metrics updated to 0.4.1
* memcached and rabbitmq rolled back to last working versions

[designate] rollback selector label changes

---

openstack/manila/Chart.lock

contains priorityClassName critical-infrastructure update

[manila] bump deps

---

common/pxc-db/Chart.yaml
common/pxc-db/values.yaml

* Update mysqld-exporter to v0.16.0
* Enable innodb_tablespaces collector

[pxc-db] Update mysqld-exporter to v0.16.0

---

common/mariadb/CHANGELOG.md
common/mariadb/Chart.yaml
common/mariadb/values.yaml

* mysqld-exporter version bumped to `0.16.0`
* `collect.info_schema.innodb_tablespaces` collector enabled

[mariadb] Update mysqld-exporter to 0.16.0

---

openstack/elektra/values.yaml

this will update the cam link in elektra

upgrade cam link for elektra

---

system/vmware-monitoring/Chart.yaml
system/vmware-monitoring/templates/collector-configmap.yaml

- Change the no swap DS metric to NVMe

[vmware-monitoring] Modify host system properties metric

---

global/prometheus-alertmanager-operated/Chart.yaml
global/prometheus-alertmanager-operated/templates/am-config-route-slack.yaml

Added a route and receiver for CC KVM test channel alerts (#alert-kvm-test)

Updated to receive alerts for CC test channel

---

common/pxc-db/Chart.yaml
common/pxc-db/templates/cluster.yaml

Add labels to PerconaXtraDBCluster resources
These labels will be passed to kube-state-metrics timeseries

[pxc-db] Add labels to PerconaXtraDBCluster resources

---

prometheus-rules/prometheus-vmware-rules/alerts/datastore.alerts

Please review this new missing swap DS alert. thanks!

adding new swap ds alert

---

system/percona-xtradb-cluster-operator/Chart.lock
system/percona-xtradb-cluster-operator/Chart.yaml
system/percona-xtradb-cluster-operator/values.yaml

Add PerconaXtraDBCluster metrics
Add PerconaXtraDBClusterBackup metrics

[pxc-operator] Add kube-state-metrics to collect CR status

---

openstack/designate/Chart.lock
openstack/designate/Chart.yaml

* percona_cluster 1.1.7 -> 1.1.8: change priority class
* pxc-db 0.1.17 -> 0.1.20
* utils 0.19.7 -> 0.21.0: add Galera monitor to ProxySQL

[designate] Bump DB chart dependencies

---

openstack/kmip/Chart.lock
openstack/kmip/templates/deployment.yaml
openstack/kmip/templates/service.yaml
openstack/kmip/values.yaml

more details : https://github.com/sapcc/PyKMIP/commit/dd6a5d66af98a24b0aacf70b977f3291ee6a8725#diff-390cb380ccb8638b205433011f46c823f367c5bfafad64225c7417d6e79ae96c

[KMIP] Introduce kmip-restapi container

---

openstack/manila/templates/api-deployment.yaml
openstack/manila/templates/migration-job.yaml
openstack/manila/templates/scheduler-deployment.yaml
openstack/manila/templates/shares/_netapp-deployment.yaml.tpl
openstack/manila/templates/shares/_netapp-ensure-deployment.yaml.tpl
openstack/manila/values.yaml

ensure and memcached have lower priority: a degraded service would work

[manila] add priority class settings

---

system/cc-ceph/templates/cephobjectstore-extra.yaml
system/cc-ceph/templates/cephobjectstore-placement-pools.yaml
system/cc-ceph/templates/cephobjectstore.yaml
system/cc-ceph/templates/certificate-extra.yaml
system/cc-ceph/templates/record-extra.yaml
system/cc-ceph/templates/service-extra.yaml
system/cc-ceph/values.yaml

add support for [Rook rgw multi-instance  setup](https://rook.io/docs/rook/latest-release/Storage-Configuration/Object-Storage-RGW/object-storage/#object-multi-instance).

[ceph] support multi-instance rgw

---

common/pxc-db/Chart.yaml
common/pxc-db/templates/_helpers.tpl
common/pxc-db/templates/alerts/_backup.alerts.tpl
common/pxc-db/templates/cluster.yaml

* Add app and name labels for backup jobs and pitr deployment
* Use app label in backup alert expressions
* Fix pxc_binlog alerts

[pxc-db] Add app and name labels for backup jobs and pitr deployment

---

openstack/designate/Chart.lock
openstack/designate/Chart.yaml

Bump designate pxc-db chart dependecy
Includes fixes in labels and alerts

[designate][pxc-db] Bump chart dependency

---

common/mysql_metrics/CHANGELOG.md
common/mysql_metrics/Chart.yaml
common/mysql_metrics/ci/test-values.yaml
common/mysql_metrics/values.yaml

Update sql-exporter version to 0.5.9 (2025-01-07)

[mysql_metrics] Update sql-exporter version to 0.5.9

---

prometheus-exporters/cloudprober/Chart.lock
prometheus-exporters/cloudprober/Chart.yaml
prometheus-exporters/cloudprober/values.yaml

The base image has reached End of Support Life and will not receive further security updates.

chore: bump image version

---

system/unbound/templates/deployment.yaml
system/unbound/templates/hec-secrets.yaml

[unbound] take hec secrets from k8s secret

---

openstack/ironic/templates/seed.yaml

for node001r-gp900.cc.qa-de-1.cloud.sap

add lenovo SR675V3 with Nvidia L40S flavor

---

common/memcached/CHANGELOG.md
common/memcached/Chart.yaml
common/memcached/values.yaml

* bumped memcached version
* bumped memcached-exporter version

[memcached] memcached version bumped to 1.6.34-alpine3.21

---

prometheus-exporters/octobus-query-exporter/Chart.lock
prometheus-exporters/octobus-query-exporter/Chart.yaml
prometheus-exporters/octobus-query-exporter/values.yaml
prometheus-exporters/octobus-query-exporter/vendor/octobus-query-exporter/Chart.yaml
prometheus-exporters/octobus-query-exporter/vendor/octobus-query-exporter/alerts/infra-frontend/logs.alerts
prometheus-exporters/octobus-query-exporter/vendor/octobus-query-exporter/alerts/region/jump.alerts

[octobus-query-exporter] fix jumpserver alert, mv alert to regional thanos ruler

---

system/cc-ceph/Chart.lock
system/cc-ceph/Chart.yaml

ceph: update rook from 1.16.0 to 1.16.1

---

system/cc-ceph/Chart.yaml
system/cc-ceph/templates/certificate-extra.yaml
system/cc-ceph/templates/certificate.yaml
system/cc-ceph/templates/record-extra.yaml
system/cc-ceph/templates/record.yaml
system/cc-ceph/templates/service-extra.yaml
system/cc-ceph/templates/service.yaml
system/cc-ceph/values.yaml

skip wildcard DNS records and certs, skip NodePort svc with externalIPs

ceph: add skip for dnsNames wildcard, and skip external service

---

global/oauth-proxy/ci/test-values.yaml
global/oauth-proxy/templates/deployment.yaml
global/oauth-proxy/values.yaml

This should allow us to alert on failing authentications

[oauth-proxy]: enable metrics

---

system/greenhouse-ccloud/Chart.yaml
system/greenhouse-ccloud/templates/teams.yaml

the URL query parameter has changed and cannot be templated

feat(greenhouse): remove joinURL templating

---

openstack/limes/values.yaml

@Varsius Please double-check the liquid-nova configuration. I'm especially unsure whether we need `ignored_traits` from the start.

limes: add liquid-nova deployment

---

openstack/masakari/templates/configmap-backup.yaml
openstack/masakari/templates/configmap-upload.yaml
openstack/masakari/templates/cronjob-backup.yml
openstack/masakari/templates/database-pvc.yaml
openstack/masakari/templates/pvc-backup.yml
openstack/masakari/templates/secrets.yaml
openstack/masakari/values.yaml

This pull request will add a CronJob who takes care of backing up the SQlite DB for masakari.

Masakari backup

---

openstack/manila/aggregates/storage/limes.rules

we move the function definition away from limes and take
ownership in manila

[manila] add metrics for limes capacity plugin

---

.github/workflows/helm-lint.yaml
.github/workflows/helm-push.yaml

fix(ci): disable helm lint & helm push

---

system/cc-ceph/Chart.lock
system/cc-ceph/Chart.yaml

upgrade rook to the latest version

[ceph] upgrade rook to 1.16.2

---

system/cc-ceph/Chart.yaml
system/cc-ceph/templates/prysm-diskhealth-exporter-ds.yaml
system/cc-ceph/templates/prysm-diskhealth-exporter-svc.yaml
system/cc-ceph/templates/prysm-diskhealth-exporter-svcmonitor.yaml
system/cc-ceph/templates/rgw-exporter-deployment.yaml
system/cc-ceph/templates/rgw-exporter-secret.yaml
system/cc-ceph/templates/rgw-exporter-service.yaml
system/cc-ceph/values.yaml

- rgw usage values moved from prysm under prysm.rgwMetrics
- initial daemonset for diskhealth metrics
- new value settings in prysm.diskHealth

[cc-ceph] prysm diskhealth and rgw usage

---

openstack/nova/values.yaml

Enable option implemented in https://github.com/sapcc/nova/pull/518

[nova] enable disable_db_only_delete

---

openstack/aurora/Chart.yaml
openstack/aurora/templates/deployment.yaml
openstack/aurora/templates/ingress.yaml
openstack/aurora/templates/secret.yaml
openstack/aurora/templates/service.yaml
openstack/aurora/values.yaml

This PR adds a new folder `aurora` containing helm charts for aurora dashborad.

chore(aurora): adds helm charts for aurora dashboard

---

global/prometheus-alertmanager-operated/Chart.yaml
global/prometheus-alertmanager-operated/values.yaml
system/gatekeeper-config/Chart.yaml
system/gatekeeper-config/values.yaml

This PR introduces the `workload-management` support group to the alertmanager and gatekeeper.

introduce workload management support group

---

system/cc-ceph/Chart.yaml
system/cc-ceph/templates/rgw-exporter-deployment.yaml

use annotation instead of labels, fixes previous #7773

[prysm] restart deployment on secret update, fix annotation

---

openstack/nova/templates/etc/_nova-scheduler.conf.tpl

See: https://github.com/sapcc/nova/pull/502

[nova] Add external scheduler flags in nova config

---

system/cc-ceph/Chart.yaml
system/cc-ceph/templates/rgw-exporter-deployment.yaml

follow-up to the https://github.com/sapcc/helm-charts/pull/7742

[ceph] fix empty annotation for ceph/prysm exporter

---

global/andromeda/Chart.lock

Bumped the Chart deps so development and testing can continue (see #7779).

[andromeda] bumped chart deps

---

system/greenhouse-ccloud/templates/disco-plugins.yaml

We want to be able to template the complete recordName.

feat(greenhouse): Use recordName in disco

---

openstack/limes/values.yaml

limes: liquid nova config: add ignored_traits 

---

system/gatekeeper/templates/constrainttemplate-pod-security.yaml

Followup for #7737. @timojohlo Does this look good to you?

GkPodSecurity: restrict otel exception to the relevant clusters

---

global/andromeda/templates/_helpers.tpl
global/andromeda/templates/configmap-liquid-server.yaml
global/andromeda/templates/deployment-liquid-server.yaml
global/andromeda/templates/etc/_liquid-policy.json.tpl
global/andromeda/templates/liquid-server-ingress.yaml
global/andromeda/templates/liquid-server-service.yaml

Tested on qa-de-3, looks good.

[andromeda] Liquid Server pod

---

system/greenhouse-ccloud/Chart.yaml

follow up of https://github.com/sapcc/helm-charts/commit/38126d48a83a60a500c4cf531d1e5a44926a7ee8
bump chart version

[greenhouse] thanos bump greenhouse chart version

---

openstack/nova/templates/etc/_nova-policy.yaml.tpl
openstack/nova/values.yaml

There isn't really much to do up front. Somethings got deprecated, but we still need them for now, so a cleanup will happen in a PR after the upgrade.

[Nova] Prepare for bobcat upgrade

---

system/greenhouse-ccloud/Chart.yaml
system/greenhouse-ccloud/templates/thanos-pluginpreset.yaml

[greenhouse] thanos preset fix template flow

---

system/cc-ceph/Chart.yaml
system/cc-ceph/templates/blockrbdpool.yaml
system/cc-ceph/templates/blockstorageclass.yaml
system/cc-ceph/values.yaml

new pool for block

---

system/greenhouse-ccloud/Chart.yaml
system/greenhouse-ccloud/ci/test-values.yaml
system/greenhouse-ccloud/templates/kubeconfig-generator-plugin.yaml

…#7856)"
This reverts commit 1e3d582e32c7e28f806334378f1d3021ef9aeae1.

Revert "feat(gh-ccloud): configurable clusters for config generator (#7856)"

---

openstack/nova/templates/bump-compute-service-version-xena.yaml
openstack/nova/templates/hypervisors/hypervisors-ironic-kt.yaml

[Nova] more patches for the bobcat upgrade

---

prometheus-rules/prometheus-kubernetes-rules/Chart.yaml
prometheus-rules/prometheus-kubernetes-rules/alerts/health.alerts.tpl

Looks like I did a copy-paste error there last week.

prometheus-kubernetes-rules: fix desc for PodNotSchedulable

---

openstack/manila/templates/type-seeds.yaml

as per ADR 71
similarily also adjusting private types 'hypervisor storage' and 'integration'
and preparing the bigger new tbd type 'standard' (ADR 70)

[manila] bigger shares of type 'default'

---

system/jupyter-cron-reports/templates/cornjob-monthly-ticket-analysis-report.yaml

This is a cornjob template for ticket analysis script that runs monthly.

cornjob-monthly-ticket-analysis-report.yaml

---

openstack/keystone/templates/secret-fernet.yaml

[keystone] don't use template for fernet key secret and use b64enc

---

prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/aggregations/maia.yaml

update unless condition by including more labels to compare

[netapp-harvest-exporter] fix snapmirror maia metrics

---

system/calico-cni/Chart.yaml
system/calico-cni/templates/alerts.yaml
system/calico-cni/values.yaml
system/digicert-issuer/Chart.yaml
system/digicert-issuer/templates/deployment.yaml
system/digicert-issuer/templates/podmonitor.yaml
system/digicert-issuer/templates/prometheus-alerts.yaml
system/digicert-issuer/values.yaml
system/go-pmtud/Chart.yaml
system/go-pmtud/templates/alerts.yaml
system/go-pmtud/values.yaml
system/secrets-injector/Chart.yaml
system/secrets-injector/templates/alerts.yaml
system/secrets-injector/values.yaml

The charts in question are used in Greenhouse clusters. Prometheus uses different labels to select the resources.

Adds option to modify prometheus label selectors 

---

openstack/neutron/templates/configmap-ovn-db-raft.yaml
openstack/neutron/templates/deployment-ovn-northd.yaml
openstack/neutron/templates/etc/_ml2-conf.ini.tpl
openstack/neutron/templates/pdb-ovn-db-raft.yaml
openstack/neutron/templates/service-ovn-db.yaml
openstack/neutron/templates/statefulset-ovn-db-raft.yaml

this add the following parts of OVN:
* ovsdb northbound
* ovsdb southbound
* northd
and updates the ml2-conf.ini to use the ovn ml2 driver

[neutron] add ovn controlplane

---

openstack/limes-campfire/ci/test-values.yaml
openstack/limes-campfire/templates/_utils.tpl
openstack/limes-campfire/templates/deployment.yaml
openstack/limes-campfire/templates/secret.yaml
openstack/limes/ci/test-values.yaml
openstack/limes/templates/seed-campfire.yaml
openstack/limes/templates/seed.yaml

@VoigtS As discussed on Friday. Two followups will be necessary:
- The pipeline needs to be adjusted to deploy into all regions.
- The templating in this PR needs to be extended further to support the global region deployments. I did not do that in this PR to keep the change reviewable.

limes-campfire: regional deployments

---

system/unbound/templates/prometheus-alerts.yaml

It will fire if the traffic in the past minute is less than 10% of the 24h average.

[unbound] introducing the DNSUnbound{1,2}LowTraffic prometheus alert

---

openstack/keppel-trivy/Chart.lock
openstack/keppel-trivy/ci/test-values.yaml
openstack/keppel-trivy/templates/deployment-server.yaml
openstack/keppel-trivy/templates/secret.yaml
openstack/keppel-trivy/values.yaml
openstack/keppel/Chart.lock
openstack/keppel/templates/_utils.tpl
openstack/keppel/templates/secret.yaml
openstack/keppel/values.yaml

Also, switch to autogenerated passwords.

keppel/trivy: bump Redis chart to 2.0.0

---

openstack/barbican/templates/etc/_secrets.conf.tpl

https://docs.openstack.org/releasenotes/barbican/2024.1.html

[Barbican] adapt sql_connection for openstack dalmatian

---

openstack/glance/Chart.lock
openstack/glance/Chart.yaml
openstack/glance/values.yaml

* use ROW binlog format instead of MIXED
This should help to avoid getting RETURNING statements in binary logs

[glance][mariadb] use ROW binlog format

---

common/mariadb/CHANGELOG.md
common/mariadb/Chart.yaml
common/mariadb/README.md
common/mariadb/scripts/common-functions.sh
common/mariadb/scripts/mariadb-cronjob-maintenance.sh
common/mariadb/templates/_helpers.tpl
common/mariadb/templates/configmap-mariadb-maintenance.yaml
common/mariadb/templates/cronjob-mariadb-maintenance.yaml
common/mariadb/values.yaml

- maintenance job added
- currently the [analyze table](https://mariadb.com/kb/en/analyze-table/) task is supported
- the [README.md](README.md#analyzetable) is updated with the new maintenance job details

[mariadb] maintenance job added

---

system/plutono/Chart.lock
system/plutono/Chart.yaml
system/plutono/templates/plutono-deployment.yaml
system/plutono/values.yaml

chore(deps): update dependencies and image versions in Pluton

---

openstack/designate/templates/etc/_designate-policy.yaml.tpl

- remove unused target
- adjust delete to work with dalmatian
- adjust shared zones rules

[designate] adjust policy

---

global/git-cert-shim/Chart.yaml

update git-cert-shim version

---

system/cc-ceph/Chart.yaml
system/cc-ceph/templates/prysm-rgw-sidecar-webhook-cert.yaml
system/cc-ceph/templates/prysm-rgw-sidecar-webhook-deploy.yaml
system/cc-ceph/templates/prysm-rgw-sidecar-webhook-issuer.yaml
system/cc-ceph/templates/prysm-rgw-sidecar-webhook-mutating-webhook.yaml
system/cc-ceph/templates/prysm-rgw-sidecar-webhook-svc.yaml
system/cc-ceph/values.yaml

init support for mutating webhook for rgw sidecar

Prysm webhook init

---

global/andromeda/templates/deployment-akamai-reports.yaml

Introduces a new deployment for the recently added "Akamai reports" binary.

[andromeda] new "akamai reports" bin deployment

---

prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_kubernikus_expired_client.cfg

fix(prometheus-exporter): fixes problem where the query 'query_opensearch_kubernikus_expired_client' was crashing

---

system/greenhouse-ccloud/Chart.yaml
system/greenhouse-ccloud/templates/perses-pluginpreset.yaml
system/greenhouse-ccloud/values.yaml

This PR adds Perses plugin-preset to greenhouse ccloud organization.

Add Perses plugin-preset to greenhouse ccloud org

---

system/greenhouse-ccloud/Chart.yaml
system/greenhouse-ccloud/templates/perses-pluginpreset.yaml

Fix Perses plugin-preset in greenhouse ccloud org

---

common/pxc-db/Chart.yaml
common/pxc-db/values.yaml

* bump mysqld-exporter to latest release v0.17.1

[pxc-db] bump mysqld-exporter to latest release v0.17.1

---

common/mariadb/CHANGELOG.md
common/mariadb/Chart.yaml
common/mariadb/templates/cronjob-mariadb-maintenance.yaml

[mariadb] maintenance job configmap name fixed

---

openstack/limes-campfire/templates/secret.yaml

limes-campfire: fix keystone password reference in global

---

common/mariadb/CHANGELOG.md
common/mariadb/Chart.yaml
common/mariadb/templates/configmap-mariadb-maintenance.yaml

[mariadb] maintenance job configmap condition fixed

---

openstack/keystone/Chart.lock
openstack/keystone/Chart.yaml

- maintenance job configmap condition fixed

[keystone] MariaDB chart version bumped to 0.16.9

---

openstack/swift-utils/templates/seed.yaml

[swift] fix swift domain list type (srs #485)

---

system/cc-ceph/Chart.yaml
system/cc-ceph/templates/prysm-rgw-sidecar-webhook-mutating-webhook.yaml

- added UPDATE operation, to react on

[prysm] mutatign webhook add UPDATE op

---

openstack/billing/ci/test-values.yaml
openstack/billing/templates/seeds.yaml
openstack/keppel/ci/test-values.yaml
openstack/keppel/templates/support_seed.yaml
openstack/limes/ci/test-values.yaml
openstack/limes/templates/support_seed.yaml

`helm diff` was empty - this is homologous to the old expression

[limes+keppel+billing] use c_domains_without_support_projects (srs #485)

---

openstack/designate/Chart.lock
openstack/designate/Chart.yaml
openstack/designate/templates/_helpers.tpl
openstack/designate/templates/etc/_secrets.conf.tpl
openstack/designate/values.yaml

* use ini_sections.default_transport_url helper for rabbitmq url
* remove now unused rabbitmq_cluster dependency

[designate][rabbitmq] use ini_sections.default_transport_url helper

---

prometheus-exporters/opensearch-logs-query-exporter/values.yaml

chore(opensearch-query-exporter): bump version to 2025022808113

---

prometheus-exporters/opensearch-logs-query-exporter/values.yaml

bump version to 20250228144915

chore(opensearch-query-exporter): bump version to 20250228144915

---

system/logs/values.yaml

fix(logs): adds openstack.enabled: false default

---

common/mariadb/CHANGELOG.md
common/mariadb/Chart.yaml
common/mariadb/scripts/docker-entrypoint.sh
common/mariadb/templates/deployment.yaml
common/mariadb/templates/entrypoint-configmap.yaml

* use custom entrypoint script for mariadb deployment
* remove non-optional `healthcheck` user creation

[mariadb] use custom entrypoint script for mariadb deployment

---

prometheus-rules/prometheus-vmware-rules/Chart.yaml
prometheus-rules/prometheus-vmware-rules/alerts/datastore.alerts

- Change the severity from info to warning

[prometheus-vmware-rules] Update VMFSDatastoreHostcountMismatch alert

---

openstack/manila/Chart.lock
openstack/manila/Chart.yaml
openstack/manila/values.yaml

the metis user requires 'replication replica' to access the binlog

feat(manila): add grants for user metis

---

system/metis-api/Chart.lock
system/metis-api/Chart.yaml

reload the api pod once the database secret was changed

feat(metis-api): bump dependencies

---

system/metis/Chart.lock
system/metis/Chart.yaml
system/metis/templates/metis-deployment.yaml

This will reload the metis deployment when the secret is changed.

feat(metis): bump deps & reload on secrets change

---

common/memcached/CHANGELOG.md
common/memcached/Chart.yaml
common/memcached/values.yaml

* update memcached-exporter to 0.15.1

[memcached] update memcached-exporter to 0.15.1

---

common/mariadb/CHANGELOG.md
common/mariadb/Chart.yaml
common/mariadb/scripts/docker-entrypoint.sh
common/mariadb/scripts/mariadb-set-root-password.sh
common/mariadb/templates/configmap-set-root-password.yaml
common/mariadb/templates/deployment.yaml
common/mariadb/templates/secret.yaml

* start database with init.sql to update root password

[mariadb] set root password on every database start

---

.github/CODEOWNERS
common/rabbitmq_cluster/Chart.yaml
common/rabbitmq_cluster/templates/_helpers.tpl
common/rabbitmq_cluster/templates/cluster.yaml
common/rabbitmq_cluster/templates/secrets.yaml

Create custom secret in required format and use it for rabbitmq-cluster

[rabbitmq_cluster] Add support for secrets-injector

---

openstack/ironic/templates/_conductor-deployment.yaml.tpl
openstack/ironic/templates/etc/_ironic.conf.tpl
openstack/ironic/templates/etc/_netrc.tpl

- **[ironic] ironic fix mounts**
- **[ironic] remove setting of pybasedir**
- **[ironic] remove quotes from secret**

moar ironic fixes

---

openstack/elektra/bin/init-generate-token-secret.sh
openstack/elektra/templates/rbac.yaml

Preparation for the upcoming rails token rotation.
- Extend role to be able to patch the secret
- Remove check for the old secret since vault reference doesn't exist anymore.

chore(elektra): preparation for the rails token rotation

---

openstack/ironic/templates/seed.yaml

ProLiant DL560 Gen11 as hv and bm

[ironic] add flavors for hpe 4s1t

---

system/opensearch-logs/templates/config/_roles.yml.tpl

fix(opensearch): changes role permissions for data role onto alerts and deployment index

---

global/andromeda/Chart.yaml
global/andromeda/templates/deployment-liquid-server.yaml

reload deployment on secrets rotation

[andromeda] reload andromeda liquid server on secret update

---

system/logs/templates/_external-config.tpl

Removes debug exporter from external inputs.

fix(logs): removes debug exporter from external inputs

---

system/logs/templates/_external-config.tpl

fix(logs): sets condition for when JSONBody is allowed to be parsed

---

system/prometheus-operator/Chart.lock
system/prometheus-operator/Chart.yaml

+ linkerd and owner info chart update

prometheus-operator: update version to v0.81.0

---

.github/CODEOWNERS

add @s10 as shared services (rabbitmq, mariadb, memcached) and utils codeowner

[CODEOWNERS] add @s10 as shared services and utils codeowner

---

common/rabbitmq/CHANGELOG.md
common/rabbitmq/Chart.yaml
common/rabbitmq/ci/test-values.yaml
common/rabbitmq/templates/_helpers.tpl
common/rabbitmq/templates/deployment.yaml
common/rabbitmq/templates/statefulset.yaml
common/rabbitmq/values.yaml

* Add [user-credential-updater](https://github.com/sapcc/rabbitmq-user-credential-updater) sidecar container
* Use sidecar container for runtime password updates

[rabbitmq] Add credential-updater sidecar

---

prometheus-exporters/blackbox-exporter/Chart.yaml
prometheus-exporters/blackbox-exporter/values.yaml

blackbox-exporter: bump to v0.26.0

---

openstack/utils/Chart.yaml
openstack/utils/templates/_ini_sections.tpl

[utils] Update logging template strings for yoga and beyond

---

common/memcached/CHANGELOG.md
common/memcached/Chart.yaml
common/memcached/values.yaml

- mem leak bugfix
- bumped memcached version

[memcached] version bumped to 1.6.38-alpine3.21

---

openstack/nova/Chart.lock
openstack/nova/Chart.yaml
openstack/nova/values.yaml

Bump Nova dependencies to the most recent versions. See the commit messages for more details.

Bump Nova Dependencies

---

common/nats/Chart.yaml
common/nats/README.md
common/nats/templates/service.yaml

Needed for the migration to Calico.

[nats] calico prep

---

global/andromeda/Chart.lock
global/andromeda/values.yaml

Depends on #8245 (NATS dependency must be bumped to 0.19.0)

[andromeda] NATS calico prep

---

openstack/elektra/ci/test-values.yaml
openstack/elektra/templates/seed.yaml

Reverts sapcc/helm-charts#8314

Revert "Revert "[elektra] seed generic domains using global.domains_seeds""

---

openstack/limes/templates/deployment-collect.yaml

limes: set LIMES_BLOCK_EXPIRY_NOTIFICATIONS temporarily

---

system/logs/vendor/logstash-external/templates/_logstash.conf.tpl

Resolves a small syntax error
---------

fix(logs): fixes logstash external if statement

---

openstack/keystone/Chart.lock
openstack/keystone/Chart.yaml

- needed type: LoadBalancer for percona_cluster and memcached in case of external IPs.

[keystone] bump chart requirements.

---

openstack/designate/Chart.lock
openstack/designate/Chart.yaml

needed type: LoadBalancer for percona_cluster and memcached in case of external IPs.

[designate] bump chart requirements.

---

system/cc-ceph/Chart.yaml
system/cc-ceph/values.yaml

- sidecarEnvConfig set to disable by default

[prysm] sidecarEnvConfig set to disable by default

---

system/cc-ceph/Chart.yaml
system/cc-ceph/templates/prysm-rgw-sidecar-webhook-deploy.yaml
system/cc-ceph/values.yaml

- added sidecar image to webhook

[prysm] added sidecar image to webhook

---

system/vmware-monitoring/Chart.yaml
system/vmware-monitoring/templates/collector-configmap.yaml

Add below VM properties:
- metric_suffix: "net_4000_ip" key: "net:4000|ip_address"
- metric_suffix: "net_4001_ip" key: "net:4001|ip_address"
- metric_suffix: "net_4002_ip" key: "net:4002|ip_address"

Update VMPropertiesCollector to collect the VM net ip address

---

common/rabbitmq/CHANGELOG.md

Update v0.17.1 release changelog

[rabbitmq] update chart changelog

---

system/greenhouse-ccloud/Chart.yaml
system/greenhouse-ccloud/templates/_helper.tpl
system/greenhouse-ccloud/values.yaml

Greenhouse global Thanos can take additional stores.

greenhouse-ccloud: introduce additional stores

---

openstack/cc3test-seeds/templates/project-seed.yaml

(cc3test) fix role assignment for users

---

system/logs/templates/_openstack-config.tpl

otel-logs will parse the container date automatically. Time parsing app logs is too error prone.

[logs] remove all time parsing

---

system/logs/templates/_containerd-config.tpl
system/logs/templates/_openstack-config.tpl

Fix info in logs: "one or more statements were modified to include their paths context, please rewrite them accordingly"
Issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22744

[logs] fix context

---

common/mariadb/CHANGELOG.md
common/mariadb/Chart.yaml
common/mariadb/scripts/mariadb-rename-check-constraints.sh
common/mariadb/templates/rename-check-constraints-configmap.yaml
common/mariadb/templates/rename-check-constraints-job.yaml
common/mariadb/values.yaml

Add optional `mariadb-check-constraints` job
This job renames constraints with names like `CONSTRAINT_*`

[mariadb] Add optional mariadb-check-constraints job

---

openstack/keppel/templates/seed.yaml
openstack/keppel/templates/support_seed.yaml
openstack/swift/templates/support_seed.yaml

just a small improvement that was requested on another service, would like to do this consistently

[keppel + swift] harden iaas- checks

---

system/cc-ceph/Chart.yaml
system/cc-ceph/templates/prysm-rgw-sidecar-servicemonitor.yaml
system/cc-ceph/templates/prysm-rgw-sidecar-svc.yaml

- servicemonitor for opslog sidecar

[prysm] servicemonitor for opslog sidecar

---

openstack/designate/Chart.yaml
openstack/designate/ci/test-values.yaml
openstack/designate/templates/api-deployment.yaml
openstack/designate/templates/central-deployment.yaml
openstack/designate/templates/mdns-deployment.yaml
openstack/designate/templates/producer-deployment.yaml
openstack/designate/templates/sink-deployment.yaml
openstack/designate/templates/worker-deployment.yaml

This PR adds stakater/Reloader annotations to all Designate deployments.

[designate] add reloader annotation to all services deployments

---

openstack/designate/Chart.lock
openstack/designate/Chart.yaml
openstack/designate/templates/api-deployment.yaml
openstack/designate/templates/etc/_api-paste.ini.tpl
openstack/designate/values.yaml

[designate] add auto-generated secret reference for redis used by

---

openstack/cronus/templates/cronus/ingress.yaml

This PR adds a second domain name for the Cronus gateway service.

[cronus] add alternative service domain name

---

openstack/limes/templates/_utils.tpl
openstack/limes/templates/ingress-api.yaml
openstack/limes/templates/ingress-liquids.yaml
openstack/limes/templates/prometheus-alerts.yaml
openstack/limes/templates/seed-catalog.yaml
openstack/limes/templates/seed-grants.yaml
openstack/limes/templates/seed.yaml
openstack/limes/templates/support_seed.yaml
openstack/limes/values.yaml

Reverts sapcc/helm-charts#8447
Need to check how I can get `common/pg_backup` working together with the values we need for limes.

Revert-Revert [limes] use global.is_global_region in helm-charts

---

common/rabbitmq/CHANGELOG.md
common/rabbitmq/Chart.yaml
common/rabbitmq/values.yaml

- several cluster fixes and enhancements

[rabbitmq] version bumped to 4.0.8-management

---

openstack/glance/templates/seeds.yaml

just a small improvement that was requested on another service, would like to do this consistently

[glance] harden iaas- checks

---

system/cc-ceph/Chart.yaml
system/cc-ceph/templates/ceph-config-override.yaml

[ceph] use global values for ceph-config-override.yaml

---

openstack/limes/templates/configmap.yaml

Removing a superfluous dot within the string

[limes] fix mail dashboardInfo string

---

system/liquid-ceph/Chart.yaml
system/liquid-ceph/templates/deployment.yaml

Signed-off-by: Andrei Ivashchenko <aiivashchenko@users.noreply.github.com>
On-behalf-of: SAP <andrei.ivashchenko@sap.com>

Change allow domain flag

---

openstack/manila/Chart.yaml
openstack/manila/values.yaml

Hopefully this improves memory situation

[manila] mysql_metrics: set main container for vpa

---

system/sentry/Chart.lock
system/sentry/Chart.yaml

[Sentry] bump postgresql chart version to 1.3.1

---

system/percona-xtradb-cluster-crds/crds/perconaxtradbclusterbackups.pxc.percona.com.yaml
system/percona-xtradb-cluster-crds/crds/perconaxtradbclusterrestores.pxc.percona.com.yaml
system/percona-xtradb-cluster-crds/crds/perconaxtradbclusters.pxc.percona.com.yaml
system/percona-xtradb-cluster-operator/Chart.lock
system/percona-xtradb-cluster-operator/Chart.yaml

* update pxc-operator to 0.17.0 release
* update pxc crds to 0.17.0 release
* update kube-state-metrics chart to 5.32.0

[pxc-operator] update to 0.17 release

---

system/unbound/templates/deployment.yaml

[unbound] purged the privileged security context

---

system/metis/Chart.yaml
system/metis/templates/_replication-etc-configmap.tpl
system/metis/templates/alerts.yaml
system/metis/templates/ingress.yaml
system/metis/templates/metis-deployment.yaml
system/metis/templates/metis-etc-configmap.yaml
system/metis/templates/metis-secrets.yaml
system/metis/templates/sync-etc-configmap.yaml
system/metis/templates/sync-secrets.yaml
system/metis/templates/sync-statefulset.yaml
system/metis/values.yaml

- use .Release.Namespace instead of hard-coded value
- use .backup.namespace instead of hard-coded value
- load backup source db user from env

feat(metis): load replication source user from env, fix namespaces

---

prometheus-rules/prometheus-vmware-rules/Chart.yaml
prometheus-rules/prometheus-vmware-rules/alerts/datastore.alerts

Changed NVMeSwapDatastoreMissing modified PromQL and messages content/format

NVMeSwapDatastoreMissing changed PromQL and messages

---

prometheus-exporters/poller-simulator/templates/_config.yaml.tpl

Reverts sapcc/helm-charts#8568

Revert "Simulator poller rhea, fixing wrong condition"

---

openstack/neutron/templates/etc/_neutron_audit_map.yaml

increasing coverage of the neutron audit map. please review and point out any that may be missing.
You understand the service better than I, I am looking at unmapped resources in the system and using the neutron api reference to try and fix issues.

[neutron] update hermes audit map with unmapped resources

---

system/vmware-monitoring/Chart.yaml
system/vmware-monitoring/templates/collector-configmap.yaml

Adjusted configmap for custom metrics collecting license information.
| Name                          | Value Example               | Type   | Description                     |
|-------------------------------|-----------------------------|--------|---------------------------------|
| Custom\|License\|Key          | xxxx-xxxx-xxxx-xxxx-xxxx    | string | Host license key                |
| Custom\|License\|Used         | 10                          | int    | Number of licenses used         |
| Custom\|License\|Limit        | 4000                        | int    | Total license limit             |
Check out for details on custom metrics: [vrops-custom-importer](https://github.tools.sap/cia/vrops-custom-importer)

Added vrops metric

---

system/gatekeeper/lib/add-support-labels.rego
system/gatekeeper/lib/helm-release.rego
system/gatekeeper/lib/image-check.rego
system/gatekeeper/lib/traversal.rego
system/gatekeeper/lib/validation.rego
system/gatekeeper/templates/constrainttemplate-deprecated-api-version.yaml
system/gatekeeper/templates/constrainttemplate-forbidden-clusterwide-objects.yaml
system/gatekeeper/templates/constrainttemplate-high-cpu-requests.yaml
system/gatekeeper/templates/constrainttemplate-images-from-correct-registry.yaml
system/gatekeeper/templates/constrainttemplate-images-from-non-keppel.yaml
system/gatekeeper/templates/constrainttemplate-ingress-annotations-migration.yaml
system/gatekeeper/templates/constrainttemplate-ingress-annotations.yaml
system/gatekeeper/templates/constrainttemplate-libtest-add-support-labels.yaml
system/gatekeeper/templates/constrainttemplate-libtest-traversal.yaml
system/gatekeeper/templates/constrainttemplate-outdated-image-bases.yaml
system/gatekeeper/templates/constrainttemplate-outdated-mirrors.yaml
system/gatekeeper/templates/constrainttemplate-owner-info-on-helm-releases.yaml
system/gatekeeper/templates/constrainttemplate-pci-forbidden-images.yaml
system/gatekeeper/templates/constrainttemplate-pod-labels.yaml
system/gatekeeper/templates/constrainttemplate-pod-security.yaml
system/gatekeeper/templates/constrainttemplate-prometheus-scrape-annotations.yaml
system/gatekeeper/templates/constrainttemplate-prometheusrule-alert-labels.yaml
system/gatekeeper/templates/constrainttemplate-region-value-mismatch.yaml
system/gatekeeper/templates/constrainttemplate-region-value-missing.yaml
system/gatekeeper/templates/constrainttemplate-restrict-monsoon3-namespace.yaml
system/gatekeeper/templates/constrainttemplate-unmanaged-pods.yaml
system/gatekeeper/templates/constrainttemplate-vulnerable-images.yaml

Requires https://github.com/open-policy-agent/gatekeeper/issues/3907 to be fixed and released
https://github.com/open-policy-agent/gatekeeper/blob/master/test/bats/tests/templates/k8srequiredlabels_template_regov1.yaml#L29-L32

gatekeeper: Migrate to rego v1

---

openstack/neutron/templates/etc/_neutron.conf.tpl
openstack/neutron/values.yaml

Add support to enable Open Stack Domain / project based custom DNS settings in neutron.conf

[neutron] adding support for customdns setting in neutron.conf

---

system/infra-monitoring/Chart.yaml
system/infra-monitoring/vendor/windows-exporter/alerts/ad-win-exporter.alerts

Extending alert time for this service

[win-exporter] aatpsensor takes longer to come up after reboot.

---

system/greenhouse-ccloud/Chart.yaml
system/greenhouse-ccloud/templates/perses-pluginpreset.yaml
system/greenhouse-ccloud/values.yaml

[greenhouse] enable selfmonitoring on Perses pluginpreset

---

system/greenhouse-ccloud/Chart.yaml
system/greenhouse-ccloud/templates/perses-pluginpreset.yaml

linked to https://github.com/cloudoperators/greenhouse-extensions/pull/836

fix(perses-pluginpreset): 🐛 update serviceMonitor selector matchLabels

---

system/greenhouse-ccloud/templates/alerts-plugin.yaml
system/greenhouse-ccloud/templates/ceph-operations-storage-pluginpreset.yaml
system/greenhouse-ccloud/templates/cert-manager-pluginpreset.yaml
system/greenhouse-ccloud/templates/digicert-issuer-pluginpreset.yaml
system/greenhouse-ccloud/templates/doop-plugin.yaml
system/greenhouse-ccloud/templates/heureka-plugin.yaml
system/greenhouse-ccloud/templates/kube-monitoring-pluginpreset.yaml
system/greenhouse-ccloud/templates/kubeconfig-generator-plugin.yaml
system/greenhouse-ccloud/templates/kvm-monitoring-pluginpreset.yaml
system/greenhouse-ccloud/templates/logshipper-plugins.yaml
system/greenhouse-ccloud/templates/perses-global.yaml
system/greenhouse-ccloud/templates/perses-pluginpreset.yaml
system/greenhouse-ccloud/templates/plutono-global.yaml
system/greenhouse-ccloud/templates/plutono-pluginpreset.yaml
system/greenhouse-ccloud/templates/repo-guard-plugin.yaml
system/greenhouse-ccloud/templates/teams2slack-plugin.yaml
system/greenhouse-ccloud/templates/thanos-global.yaml
system/greenhouse-ccloud/templates/thanos-pluginpreset.yaml

.spec.disabled was never used and removed

fix(greenhouse-ccloud): remove deprecated field from plugins

---

prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_dbconnection_error.cfg
prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_dboperational_error.cfg
prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_esxi_exporter_login_error.cfg
prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_logstash_derby_error.cfg
prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_manila.cfg
prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_memcached_toozconnection_error.cfg
prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_octobus_exporter_error.cfg
prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_opensearch.cfg
prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_openstack_glance.cfg
prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_px_bird.cfg
prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_rabbitmq_econnrefused_error.cfg
prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_rabbitmq_timeout_error.cfg
prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_rabbitmq_vhost_connect_error.cfg
prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_siem_error.cfg
prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_snmp.cfg

Reverts sapcc/helm-charts#8558

Revert "fix(opensearch-logs-query-exporter): change index to logstash"

---

openstack/limes/alerts/openstack/api.alerts

Companion PR for this one, don't merge individually: https://github.com/sapcc/limes/pull/711

[limes] replace alerting of capacitors with service_type

---

system/vrops-custom-importer/Chart.lock
system/vrops-custom-importer/Chart.yaml
system/vrops-custom-importer/README.md
system/vrops-custom-importer/ci/test-values.yaml
system/vrops-custom-importer/templates/job.yaml
system/vrops-custom-importer/templates/secrets.yaml
system/vrops-custom-importer/values.yaml

- vrops-custom-importer is running as job on defined interval
- values.yaml provides structure of values, values are defined on internal location

[Compute-Monitoring] - Chart for vrops-custom-importer

---

openstack/vmware-rebalancer-deps/Chart.yaml
openstack/vmware-rebalancer-deps/values.yaml

fix: wm-50 use self build vernemq image

---

openstack/designate/Chart.yaml
openstack/designate/templates/api-deployment.yaml
openstack/designate/templates/central-deployment.yaml
openstack/designate/templates/mdns-deployment.yaml
openstack/designate/templates/producer-deployment.yaml
openstack/designate/templates/sink-deployment.yaml
openstack/designate/templates/worker-deployment.yaml

* add deployment.reloader.stakater.com/pause-period annotations
* set 60s pause period for all designate deployments

[designate] add pause-period annotation for reloader

---

openstack/limes/alerts/openstack/api.alerts

Companion for <https://github.com/sapcc/limes/pull/713>. Please merge together.

limes: adjust metric names

---

openstack/hermes/templates/keystone-seed.yaml
openstack/maia/templates/seed.yaml

just a small hardening - I applied this to all other service seeds, too.

[maia+hermes] harden iaas checks

---

system/plutono/templates/_plutono.ini.tpl

@richardtief As discussed just now.

plutono: fix postgres user

---

openstack/cc3test/templates/cronjob-api.yaml
openstack/cc3test/templates/cronjob-automation.yaml
openstack/cc3test/templates/cronjob-baremetal.yaml
openstack/cc3test/templates/cronjob-blockstorage-volume.yaml
openstack/cc3test/templates/cronjob-blockstorage.yaml
openstack/cc3test/templates/cronjob-compute-kvm.yaml
openstack/cc3test/templates/cronjob-compute-server.yaml
openstack/cc3test/templates/cronjob-compute.yaml
openstack/cc3test/templates/cronjob-datapath.yaml
openstack/cc3test/templates/cronjob-datastore.yaml
openstack/cc3test/templates/cronjob-dns.yaml
openstack/cc3test/templates/cronjob-fileshare.yaml
openstack/cc3test/templates/cronjob-hermes.yaml
openstack/cc3test/templates/cronjob-integrity.yaml
openstack/cc3test/templates/cronjob-key-manager.yaml
openstack/cc3test/templates/cronjob-loadbalancer.yaml
openstack/cc3test/templates/cronjob-network-segmentation.yaml
openstack/cc3test/templates/cronjob-neutron.yaml
openstack/cc3test/templates/cronjob-object-store.yaml

[cc3test] added activeDeadlineSeconds label to restart the long running pods

---

openstack/placement/Chart.lock
openstack/placement/Chart.yaml

Updates mariadb to 10.6.21 and set max_connection_errors options to avoid prevent blocking database connections because of the failed monitor checks or other network issues
* update memcached to 0.6.10

[placement] bump shared dependencies

---

system/greenhouse-ccloud/Chart.yaml
system/greenhouse-ccloud/templates/kube-monitoring-pluginpreset.yaml

greenhouse-ccloud: use cluster label from values

---

system/logs/templates/opentelemetry-logs-collector.yaml

fix(logs): fixes issue with duplicate telemetry configs

---

openstack/maia/templates/seed.yaml
openstack/maia/values.yaml

Add Maia global seed support, should have done this at the same time as hermes. My mistake. Appreciate it.

[maia] global seed support

---

system/cc-ceph/templates/cephobjectstore-placement-pools.yaml

PG increase for data pool - start with region-premium

PG increase for data pool

---

openstack/cinder/Chart.lock
openstack/cinder/Chart.yaml

This fixes 4 CVES in mariadb.
https://github.com/sapcc/helm-charts/blob/master/common/mariadb/CHANGELOG.md#v0242---20250527

[Cinder] Update Mariadb chart to 0.24.2

---

.github/CODEOWNERS

* cleaned up errors (aligned with respective individuals)
* updated network api collaborators

github: codeowners file cleanup

---

prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/Chart.yaml
prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/values.yaml

fix netappsd: check if installed device is nil in device bay before
extract its id.

[netapp-harvest-exporter] update netappsd version

---

openstack/swift-utils/templates/seed.yaml

in preparation for: https://github.wdf.sap.corp/cc/secrets/pull/17181
Remove iaas-* domains from the list of customer_domains

to remove iaas-* domains from customer_domains

---

openstack/manila/templates/etc/_manila.conf.tpl

See https://github.com/sapcc/manila/pull/263

[cortex] Add external scheduler conf opts to manila

---

prometheus-rules/prometheus-vmware-rules/Chart.yaml
prometheus-rules/prometheus-vmware-rules/alerts/virtualmachine.alerts

increasing severity to warning for alert : NSXTMgmtVMsOddDistribution  & NSXTMgmtVMsOddDistributionSDRSAntiaffinity

increasing severity to warning for alert : NSXTMgmtVMsOddDistribution 

---

openstack/swift-utils/templates/seed.yaml

This might be what Sumit is trying to do in #8995.

swift-utils: fix caretaker role assignment

---

openstack/cinder/templates/seed.yaml

[cinder] remove v2 api endpoint

---

prometheus-exporters/ns-exporter/alerts/probe.alerts

follow-up ticket here: https://github.wdf.sap.corp/cc/neutron-issues/issues/85

fix:  ns-exporter adjust alerts

---

openstack/designate/Chart.lock
openstack/designate/Chart.yaml
openstack/designate/templates/bin/_db-migrate.sh.tpl
openstack/designate/templates/migration-job.yaml

* add missing linkerd and proxysql sidecar containers to db migration jobs
* bump openstack/utils dependency to 0.27.1

[designate] add missing linkerd and proxysql sidecars to jobs

---

system/cc-ceph-csi/Chart.yaml
system/cc-ceph-csi/templates/storageclass.yaml

fix ceph rt and mgmt redundancy profiles

fix ceph rt and mgmt redundancy profiles

---

system/cc-ceph/templates/prysm-diskhealth-exporter-ds.yaml

- extended mnt for diskhealth, device to osd mapping

[prysm][diskhealth] mnt extended

---

openstack/designate/templates/etc/_designate.conf.tpl

- use public keystone interface
- verify certificate

[designate] config changes for global:

---

system/surveyor/templates/deployment-worker.yaml

As added in sapcc/surveyor#62.

surveyor: add SURVEYOR_IMAGE_PULL_PLATFORM_FILTERS

---

openstack/nova/Chart.lock
openstack/nova/Chart.yaml

This reverts commit 777a84e8ee300fa89baba680f174b68c6f0eb91f.

Revert "[nova] Bump rabbitmq to fix certificate"

---

openstack/limes/templates/configmap-liquids.yaml

This is being added by sapcc/go-bits#239.

openstack/limes: add policy rule for liquid:change_commitments

---

openstack/archer/templates/configmap-ni.yaml
openstack/archer/templates/deployment-ni.yaml

fixes network injection for non-http services

[archer] fix network injection upstream target, support ip/hostname

---

common/mysql_metrics/CHANGELOG.md
common/mysql_metrics/Chart.yaml
common/mysql_metrics/values.yaml

* sql-exporter version updated to to 0.8.0 (2025-07-07)

[mysql_metrics] update sql-exporter version to 2025-07-07

---

common/mariadb/CHANGELOG.md
common/mariadb/Chart.yaml
common/mariadb/values.yaml

Update `maria-back-me-up` to `20250722132533` tag with newer base image

[mariadb][backup-v2] update maria-back-me-up version

---

system/greenhouse-ccloud/templates/_silence.conf.tpl

updated _silence.conf template with ceph related silences

[ceph] update _silence.conf.tpl

---

system/rook-crds/crds/cephblockpoolradosnamespaces.ceph.rook.io.yaml
system/rook-crds/crds/cephblockpools.ceph.rook.io.yaml
system/rook-crds/crds/cephbucketnotifications.ceph.rook.io.yaml
system/rook-crds/crds/cephbuckettopics.ceph.rook.io.yaml
system/rook-crds/crds/cephclients.ceph.rook.io.yaml
system/rook-crds/crds/cephclusters.ceph.rook.io.yaml
system/rook-crds/crds/cephfilesystemmirrors.ceph.rook.io.yaml
system/rook-crds/crds/cephfilesystems.ceph.rook.io.yaml
system/rook-crds/crds/cephfilesystemsubvolumegroups.ceph.rook.io.yaml
system/rook-crds/crds/cephobjectrealms.ceph.rook.io.yaml
system/rook-crds/crds/cephobjectstores.ceph.rook.io.yaml
system/rook-crds/crds/cephobjectstoreusers.ceph.rook.io.yaml
system/rook-crds/crds/cephobjectzonegroups.ceph.rook.io.yaml
system/rook-crds/crds/cephobjectzones.ceph.rook.io.yaml
system/rook-crds/crds/cephrbdmirrors.ceph.rook.io.yaml

rook upgrade to 1.17.5

---

system/rook-crds/Chart.yaml

rook upgrade bump chart version

rook upgrade bump chart version

---

global/bots4devsupport/templates/deployment.yaml
global/bots4devsupport/templates/secrets.yaml

add   aicoreAuthUrl, aicoreBaseUrl, aicoreResourceGroup

adding secrets in deployment.yaml and secrets.yaml for bots4devsupport

---

global/thanos-global/Chart.lock
global/thanos-global/Chart.yaml
global/thanos-global/values.yaml

brings in the vpa disabling change and the requests are closer to the limit

request to real load and vpa disabled

---

prometheus-rules/prometheus-vmware-rules/Chart.yaml
prometheus-rules/prometheus-vmware-rules/alerts/host.alerts

cleanup of prometheus host alert following deployment of thanos ruler alert
bump of chart version

cleanup of prometheus host alert

---

global/oauth-proxy/templates/deployment.yaml
global/oauth-proxy/values.yaml

replace bitnami image with official upstream image

[oauth-proxy]: use upstream container images

---

system/perses/Chart.yaml
system/perses/values.yaml

fix(perses): disable TLS as it is not required

---

system/infra-monitoring/Chart.yaml
system/infra-monitoring/ci/test-values.yaml
system/infra-monitoring/templates/scrapeconfig-jumpserver.yaml
system/infra-monitoring/templates/secret-jumpserver-node-exporter.yaml
system/infra-monitoring/values.yaml

using the httpSDConfig directive is not working, therefore switching to upper which was successful in testing

switch to upper basicAuth directive

---

.github/workflows/helm-push.yaml
common/linkerd-support/Chart.yaml
common/linkerd-support/templates/namespace-annotation.yaml

Add linkerd-support to ghcr.io as discussed internally.

[linkerd-support] add linkerd-support to ghcr.io

---

system/perses/Chart.yaml
system/perses/values.yaml

fix(perses): Adds linkerd configuration and disable secret access

---

system/perses/Chart.yaml
system/perses/values.yaml

fix(perses): add SKIP_TLS_VERIFY environment variable to resolve k8s-sidecar issue

---

system/perses/Chart.yaml
system/perses/templates/datasource-configmap.yaml
system/perses/values.yaml

feat(perses): add configurable datasource settings for perses

---

openstack/keystone/Chart.lock
openstack/keystone/Chart.yaml

* updates mariadb to 10.11.13
* updates memcached to 1.6.39
* updates sql-exporter to 0.8.0 (2025-07-07)

[keystone] update shared chart dependencies

---

openstack/manila-nanny/templates/secrets.yaml

vault kvv3 path can be resolved without helper

[manila-nanny] update netapp api secrets

---

openstack/cronus/Chart.lock
openstack/cronus/Chart.yaml

Requirement: https://github.wdf.sap.corp/cronus/issues/issues/1490

[cronus] Update dependency versions of RabbitMQ and fix typo in the Chart description

---

system/kube-system-metal/Chart.yaml
system/kube-system-metal/templates/ingress-external-public-service-monitor.yaml
system/kubernikus-monitoring/Chart.yaml
system/kubernikus-monitoring/alerts/kluster.alerts
system/kubernikus-monitoring/alerts/operator.alerts

This is split off from #9446 and includes only those files that @Nuckal777 can approve.

change some more playbook links to absolute URLs

---

common/mariadb/CHANGELOG.md
common/mariadb/Chart.yaml
common/mariadb/values.yaml

- several critical (InnoDB) fixes

[mariadb] version bumped to 10.11.14

---

system/perses/Chart.lock
system/perses/Chart.yaml

feat(perses): update dependencies to latest versions

---

common/prometheus-server/CHANGELOG.md
common/prometheus-server/Chart.yaml
common/prometheus-server/templates/alerts/_prometheus.alerts.tpl

* Bump Prometheus to latest version
* Adjust VPA alerting to show affected container

prom bump and alert container blaming

---

system/metal-settings/Chart.yaml
system/metal-settings/bios_versions/dell/poweredge-r640/2_22_2.yaml
system/metal-settings/bios_versions/dell/poweredge-r660/2_4_4.yaml
system/metal-settings/bios_versions/dell/poweredge-r860/2_4_4.yaml
system/metal-settings/bios_versions/hpe/proliant-dl380-gen11/u54_2_50.yaml
system/metal-settings/templates/bios_settings.yaml
system/metal-settings/templates/bios_versions.yaml

for Dell PowerEdge R640, R660, R860 and HPE ProLiant DL380 Gen11

Add BIOS version YAML files

---

system/percona-xtradb-cluster-crds/crds/perconaxtradbclusterbackups.pxc.percona.com.yaml
system/percona-xtradb-cluster-crds/crds/perconaxtradbclusterrestores.pxc.percona.com.yaml
system/percona-xtradb-cluster-crds/crds/perconaxtradbclusters.pxc.percona.com.yaml
system/percona-xtradb-cluster-operator/Chart.lock
system/percona-xtradb-cluster-operator/Chart.yaml

* update pxc-operator to 0.18.0 release
* update pxc crds to 0.18.0 release
* update kube-state-metrics chart to 6.1.4

[pxc-operator] update to 0.18.0 release

---

openstack/manila/Chart.lock
openstack/manila/Chart.yaml

* update mariadb chart - updates MariaDB to 10.11.14
* update pxc-db chart

[manila] bump database dependencies

---

openstack/kmip/Chart.lock
openstack/kmip/Chart.yaml

* Updates MariaDB to 10.11.14
* Bumps chart version

[kmip] update shared chart dependencies

---

prometheus-rules/prometheus-vmware-rules/Chart.yaml
prometheus-rules/prometheus-vmware-rules/alerts-scaleout-ruler/host.alerts

updated query to remove false positive in the alert

Thanos ruler VMware update to alert host in maintenance mode for more than 10 days

---

openstack/octavia/alerts/octavia.alerts

This PR adds OOM kill alerts for Octavia's PODs

Add Octavia OOM alerts

---

prometheus-exporters/apic-exporter/alerts/apicfaults.alerts

adding new alert for ACI BGP monitoring

adding new alert for ACI BGP monitoring

---

px/bird/templates/_deployment-bird.tpl
px/bird/templates/_helpers.tpl
px/bird/templates/bird.yaml
px/bird/templates/configmap-cleanup-host-networking.yaml
px/bird/templates/configmap-init-host-networking.yaml
px/bird/templates/configmap-init-network.yaml
px/bird/values.yaml

- **[PX] Be less dependent on SCI labels**
- **Allow host-networking**

Adjust PX charts to run in host networking

---

system/logs/Chart.lock
system/logs/Chart.yaml

linked to https://github.com/cloudoperators/greenhouse-extensions/pull/1154

[logs] update operator image to fix json validation error

---

system/cc-ceph/Chart.yaml
system/cc-ceph/templates/cephcluster.yaml

mon spread is not possible per custom count

revert mon setting

---

global/thanos-global/Chart.yaml
global/thanos-global/values.yaml

Added `openstack` ds to `cc-b0-qa-de-1`

[thanos-global] - added openstack datasource on cc-b0-qa-de-1

---

global/andromeda/alerts/andromeda.alerts

These alarms are based on the new Akamai metrics collector (`andromeda-akamai-metrics` binary).

[andromeda] akamai metrics collector alarms

---

.github/CODEOWNERS

kengou left the org
adding uwe-mayer

fix(codeowners): replace kengou with uwe-mayer

---

openstack/hermes/templates/api-deployment.yaml
openstack/hermes/templates/logstash-deployment.yaml

Enable annotations on the reloader.

[hermes] enable reloader for configmap/secrets

---

global/thanos-global/Chart.yaml
global/thanos-global/values.yaml

lower thanos global limits to 24gb and disable VPA by default

[thanos] lower resources + vpa off

---

global/percona_cluster/Chart.yaml
global/percona_cluster/values.yaml

* bump mysqld-exporter image to 0.18.0
* chart version updated

[percona-cluster] bump mysqld-exporter to 0.18.0

---

system/thanos-metal/Chart.yaml
system/thanos-metal/values.yaml
system/thanos-scaleout/Chart.lock
system/thanos-scaleout/Chart.yaml
system/thanos-scaleout/values.yaml

currently facing the issue of not having all historical data, hence disabling the distributed mode for queries which not absolutely need it.

chore(thanos): no distribution for lower queries
