- openstack/keystone/templates/etc/_policy.yaml.tpl
A normal project admin should not be able to give themselves and others these roles.
The CoreDNS team is granting them per ticket:
https://documentation.global.cloud.sap/docs/customer/networking/dns/dns-start-roles/
> [keystone] blocklist dns_hostmaster, dns_zonemaster, dns_mailmaster

- system/secrets-injector/templates/webhook.yaml
Exclude also the terraform state, as it is not even parseable by the injector because it is gzip encoded.
> Extend matchConditions to secrets-injector webhook

- openstack/ironic/templates/etc/_ironic_conductor.conf.tpl
- openstack/ironic/values.yaml
The default of 15minutes is quite sporty for our use-case. Increasing the the timeout to 1.5hours to be on the safe-side.
> [ironic] Increase timeout for ramdisks

- common/memcached/Chart.yaml
- common/memcached/templates/service.yaml
- common/memcached/values.yaml
- 1.6.21 is 1-year old by now.
- external_ip needed for global designate/keystone
> [memcached] bump version to 1.6.28; add external_ip option.

- openstack/manila-nanny/alerts/manila.alerts
- openstack/manila/alerts/kubernetes/pod.alerts
- openstack/manila/alerts/openstack/manila.alerts
having no context invokes inhibition with other alerts that
have no context and should therefore be avoided
> [manila] add and update context of alerts

- openstack/manila/values.yaml
Enable `set_main_container` config for mariadb chart, giving the
mariadb container 75% of its pod's resources.
> [manila] configure vpa for mariadb

- openstack/manila/alerts/openstack/manila.alerts
```
labels.no_alert_on_absence in body must be of type starting
```
> [manila] fix prom alert OpenstackManilaApiRatelimitExceeded

- openstack/keystone/Chart.yaml
- openstack/keystone/templates/etc/_policy.yaml.tpl
This set of patches allows project admins to manage their projects and role assignments on these projects without having to scope to the subprojets
> Keystone: subproject management

- openstack/hermes/templates/etc/_logstash.conf.tpl
duplicating the keys so one can be used in conf, in secret, while seed doesn't use the resolve
> [hermes] use conf key for resolve

- openstack/limes/alerts/openstack/capacity.alerts
This depends on the `limes_autogrow_quota_overcommit_threshold_percent` metric which is introduced by <https://github.com/sapcc/limes/pull/484>.
> limes: alert when extremely high usage disables quota overcommit

- openstack/keppel/ci/test-values.yaml
- openstack/keppel/templates/seed.yaml
- openstack/keppel/templates/support_seed.yaml
This is a cleanup that I've been meaning to do for a while, and it still needs to be done for the other services. Instead of having the customer domain list hardcoded everywhere, I had it added to values/globals.yaml to reference across the board.
> keppel: use customer_domains list from values/globals.yaml

- common/mariadb/Chart.yaml
- common/mariadb/templates/etc-configmap.yaml
- common/mariadb/values.yaml
- to support network setups that close idle connections after some time
- default values kept at `0`
- documentation snippets added
- tested locally with `helm template`
> [mariadb]: tcp_keepalive options added

- .github/CODEOWNERS
- common/mariadb-galera/CHANGELOG.md
- common/mariadb-galera/README.md
- common/mariadb-galera/helm/Chart.yaml
- common/mariadb-galera/helm/templates/statefulset-mariadb.yaml
- common/mariadb-galera/helm/templates/statefulset-proxysql.yaml
- common/mariadb-galera/helm/tests/01-default-statefulset_test.yaml
- common/mariadb-galera/helm/values.yaml
our Backplane  NFS driver does not support the change of fsGroup in case of root mismatch that's why we need to change the owner of the root directory of the volumes if we want to use persistent volumes with none root containers.
add privileged init container with all persistent volume mounted on it, which runs chown -R over all mounts.
Change-Id: I8c0d7dd94d7d24f4cd2ef1a7e2af10ed11d6139d
> [mariadb-galera] fix persistent volume permissions

- system/unbound/templates/config.yaml
If we're going to be logging the dns traffic then we will most likely want to see both the queries and the responses.
> [unbound] let log_client_response_messages default to "yes"

- openstack/limes/aggregations/openstack/consolidation.rules
- openstack/limes/alerts/openstack/capacity.alerts
As explained in the code comments, the `last_over_time(...[15m])` fixes one type of flapping, but then introduces a different type.
Because this proliferation of wrapping all metrics in several layers of sanitization causes alert expressions to become just outright unreadable, I have split all of this off into aggregation rules.
> limes: less flapping on capacity alerts

- openstack/keystone/Chart.lock
- openstack/keystone/Chart.yaml
pump up dependencies to mariadb-galera 0.27.1
- add feature to fix persistent volume fs permissions
Change-Id: Ic78187936d14c1c4f7b44f5e590917ea95ea908f
> [keystone]pump up mariadb-galera dependencies

- openstack/neutron/templates/deployment-server.yaml
- openstack/neutron/templates/etc/_uwsgi.ini.tpl
We set the environment variable DISABLE_EVENTLET_PATCHING, which is honored by our own drivers and disables calls to
`eventlet.monkey_patch()`.
Additionally, we switch away from letting uWSGI use the WSGI file `neutron-api`. The reason is, that `neutron.cmd.eventlet` uses `eventlet.monkey_patch()` unconditionally - and is imported in the `neutron-api` WSGI file. We switch instead to an `eval` setting for uWSGI, because this makes it immediately visible what we're calling. The code we're calling is also just three lines.
All of this only happens if we run with uWSGI. If we use the old eventlet-wsgi server, we need the monkey-patching.
> [Neutron] Disable eventlet patching in neutron-server

- openstack/keystone/templates/etc/_policy.yaml.tpl
The old ones worked only on a subset of scopes
> Keystone: fix variable names in policy.yaml

- system/kube-monitoring-metal/Chart.lock
- system/kube-monitoring-metal/Chart.yaml
Removes the `MissingServiceEndpoints` alert from kube-monitoring-metal umbrella chart.
> Bump kube-monitoring-metal, remove endpoint alert

- system/unbound/templates/config.yaml
That should help with troubleshooting if somebody complains they cannot resolve stuff. It can be they've hit a blocklisted entry.
TODO: We might want to toggle the logging on RPZ zone basis, e.g. log blocklisted actions and stay quiet on allowlisted ones.
> [unbound] let unbound log the RPZ actions

- system/unbound/templates/config.yaml
We might want to log just the blocklisting actions.
> [unbound] make it possible to toggle the RPZ logging on a zone basis

- openstack/designate-nanny/templates/deployment.yaml
until image transport somehow works in the global pipeline, lets always pull the image.
> [designate-nanny-global] change pull policy in global setup

- openstack/octavia/alerts/octavia.alerts
OctaviaLoadBalancerStuckinPending alerts are considered critical alerts and get paged. Yet, due to some specific workloads regarding kubernikus e2e tests and shoot networks the alarm fires a lot without indicating an actual data plane problem.
We create a specific alert targeting e2e and shoot LBs and consider assign them severity "warning". Thus they won't get paged, but will still be visible in the #alert-network-api-warning and #cc-os-octavia slack channels
We also remove the redundant waiting 1s condition as the metric already implies seconds.
> [octavia] Create additional LBStuckinPending alert

- openstack/sap-seeds/templates/flavor-seed.yaml
We now want larger general purpose flavors to keep their cores together instead of spreading them across sockets.
The underlying hypervisor topology is unrelated to the values that are settable: Valid cores-per-socket numbers are the ones that result in integer socket counts with the total number of CPUs, with a maximum of 64 cores.
E.g. with 96 vCPUs possible cores-per-socket values are:
48, 32, 24, 16, 12, 8, 6, 4, 3, 2, 1
The resulting socket-size can be larger than the socket-size of the underlying hardware. The number of _NUMA nodes_ is influenced by the underlying hardware, and the number of NUMA nodes can curiously enough be greater than the number of sockets.
> nova/flavors: Minimal socket count for flavors >= 64vCPUs

- openstack/sap-seeds/templates/_flavors_hana_no_exclusive.tpl
Two HANA flavors still had vmx-15 set, but vmx-18 is the default now, so let's make it consistent. It's not strictly needed though.
> nova/flavors: Use vmx-18 for all HANA flavors

- openstack/nova/templates/etc/_nova-scheduler.conf.tpl
The configuration for the `SapphireRapidsWeigher` and for the `DecommissioningWeigher` was set in the values file but no template used them. Therefore, the weight for these weighers was never changed away from 1.
> [Nova] Actually configure some weigh multipliers

- openstack/keystone/templates/etc/_policy.yaml.tpl
This was missed when subproject management policies were added in #6720 and some users got affected
> Keystone: add back a check for domain id to list_projects API

- common/rabbitmq/CHANGELOG.md
- common/rabbitmq/Chart.yaml
- common/rabbitmq/templates/alerts/_rabbitmq.alerts.tpl
RabbitMQRPCUnackTotal alert should support both sidecar exporter metric name and prometheus plugin
> [rabbitmq] Fix RabbitMQRPCUnackTotal alert

- system/cc-ceph/Chart.yaml
- system/cc-ceph/values.yaml
revert #6694 due to massive logging of
`debug 2024-07-05T10:03:15.659+0000 7fcb75509700  0 rgw OpsLogFile: ERROR: failed to log RGW ops log file entry `
> Revert ceph enable rgw logs

- openstack/octavia/alerts/octavia.alerts
Fix a typo in the alert matching definition, it was `c3test` which is incorrect.
> [octavia] Match cc3test alerts correctly

- openstack/keystone/Chart.lock
- openstack/keystone/Chart.yaml
bump up keystone helmchart dependencies to use mesql_metrics helm chart version 0.3.4
- fix new line issue in connection string
Change-Id: I44e6614c1db9a292bf1e634ccfa65da090b6f93e
> [keystone]bump up mysql_metrics to version 0.3.4

- common/rabbitmq/CHANGELOG.md
- common/rabbitmq/ci/test-values.yaml
- common/rabbitmq/templates/bin/_rabbitmq-start.tpl
- common/rabbitmq/values.yaml
Add an option to execute rabbitmqctl enable_feature_flag all on rabbitmq-server startup.
It only needed and might be used on instances with persistence enabled. This also makes downgrades impossible.
> [rabbitmq] Add an option to enable all stable feature flags in the RabbitMQ instance

- openstack/cinder/values.yaml
Stop using deprecated management API sidecar exporter
> [rabbitmq][Cinder] Use RabbitMQ prometheus plugin metrics

- system/cc-ceph/templates/cephobjectstore-placement-pools.yaml
- system/cc-ceph/templates/cephpool.yaml
- system/cc-ceph/templates/default_rgw_pools.yaml
- system/cc-ceph/values.yaml
Fixes ceph-analyzer warnings. See https://github.com/cobaltcore-dev/cloud-storage/issues/18
> add nodelete noresize to pools

- openstack/nova/values.yaml
This mysql metric exposes instances that are in error state because the last live-migration failed.
> [nova] add openstack_compute_errored_live_migration_gauge metrics

- openstack/hermes/Chart.lock
- openstack/hermes/Chart.yaml
- openstack/hermes/alerts/openstack/api.alerts
- openstack/hermes/values.yaml
Bump rabbitmq dependency chart to 0.7.2
Update RabbitMQRPCUnackTotal alert to use prometheus plugin metric names
> [rabbitmq][Hermes] Don't use metrics sidecar container in Hermes

- prometheus-exporters/network-generic-ssh-exporter/alerts/asr.alerts
This Absent metric is not needed as there will be alert generated automatically based on metric absence
> AbsentNetworkAsrHighMemoryUtilization

- prometheus-exporters/network-generic-ssh-exporter/templates/_config.yaml.tpl
We have some actions that lock the datastore more often than others. If
such actions occur, the api performance of the device degrades severely.
To monitor such occuerences and also gather intelligence, we implement
this hacky way to do log watching. Why? Because running it through our
regular log infra does not allow us to graph the timing between 2
events.
> [ssh-exporter] Hackaround to get statistics about netconf datastores

- common/mariadb/Chart.yaml
- common/mariadb/values.yaml
- fixes issue that swift segments do not contain ttl
- updates to go version 1.22
- updates to latest go lint
> bumps backupv2 image version

- openstack/barbican/templates/etc/_barbican-api-paste.ini.tpl
- openstack/barbican/templates/etc/_barbican_audit_map.yaml
- openstack/hermes/templates/etc/_logstash.conf.tpl
@rajivmucheli This is the configuration to test the read audit events for Barbican. I need this deployed in QA first before we deploy this completely to test and validate. We need to see what the load is, if it works correctly, and if we can handle the load. 
It may also be that we only require a subset of events with read, and then will need to add to the logstash conf to drop other events. 
So next steps are, can you please deploy this change just to a QA region for evaluation? If it makes sense, and we agree, we can deploy to all regions. If it has issues, or we need to make additional config changes, we can do so.
> [barbican] enable get audit events

- openstack/cinder/Chart.lock
- openstack/cinder/Chart.yaml
Fix for RabbitMQRPCUnackTotal alert (0.7.2), add standard labels (0.6.13, 0.7.1)
This PR will also disable rabbitmq-exporter container and turn on prometheus plugin ( https://github.com/sapcc/helm-charts/pull/6759 )
0.7.2 change is needed for this transition to work properly
> [rabbitmq][Cinder] bump rabbitmq dependency chart to 0.7.3

- prometheus-exporters/network-generic-ssh-exporter/alerts/asr.alerts
- prometheus-exporters/snmp-exporter/alerts/snmp-asr.alerts
Alert "NetworkAsrDynamicNatStopWorking" is no longer required.
"NetworkAsrInterfaceOverUtilization" alert expression updated to include inbound traffic check
> neutron_playbook_update

- common/rabbitmq/CHANGELOG.md
- common/rabbitmq/Chart.yaml
- common/rabbitmq/templates/statefulset.yaml
statefulsets are immutable. Can't use shared service tags.
> [Rabbitmq] fix statefulset immutable with shared service tags

- openstack/keystone/Chart.yaml
- openstack/keystone/templates/etc/_secrets.conf.tpl
In some cases we have clustername different than the Database name e.g **keystone-global** for that we need to use `database_name_to_connect`to get the database name, to be built in the connection string.
Change-Id: I1c9ecf9ad53401a0092d4efeb8f8d5af3d6339f3
> [keystone][mariadb-galera]use database name instead of clustername

- prometheus-exporters/openstack-exporter/alerts/cinder.alerts
- Triggers an alert if either the capacity ratio falls below 30%
or if the number of available storage units per shard meets the specified threshold
> [openstack-exporter] Update CinderShardFreeSpace alerts

- openstack/nova/templates/etc/_nova-scheduler.conf.tpl
- openstack/nova/values.yaml
We want BBs dedicated to certain customers to be preferred by these customers over generally available BBs. This makes sure that as much as possible generally available resources are available. We still want BBs marked for decommissioning to be freed, though.
> [Nova] Add weight for AggregateMultitenancyIsolation weigher

- common/rabbitmq/CHANGELOG.md
- common/rabbitmq/Chart.yaml
- common/rabbitmq/templates/statefulset.yaml
- remove shared service labels from volumeClaimTemplates, it's immutable
- return mutable shared service labels to statefulset metadata
> [rabbitmq] remove shared service labels from immutable volumeClaimTemplates

- system/doop-central/values.yaml
- system/gatekeeper/lib/add-support-labels.rego
- system/gatekeeper/templates/constrainttemplate-vulnerable-images.yaml
- system/gatekeeper/tests/gatekeeper-policies/suite.yaml
This makes the vulnerability status accessible as a label on the DOOP metrics.
I am using a rather generic name here, rather than the more specific "vulnerability_status" or "vuln_status". This label will now have to appear on all DOOP metrics, so I want to use a name that might be useful for other types of violations as well.
> GkVulnerableImages: add "status" field to object identity

- common/rabbitmq/CHANGELOG.md
- common/rabbitmq/Chart.yaml
- common/rabbitmq/templates/bin/_rabbitmq-start.tpl
- common/rabbitmq/templates/deployment.yaml
- common/rabbitmq/templates/statefulset.yaml
- common/rabbitmq/values.yaml
Remove support of the insecure rabbitmq-exporter sidecar container:
1. Sidecar uses plaintext credentials in environment variables
2. Sidecar utilises Management API metrics
3. Management API metrics will not be supported in future RabbitMQ releases
Always use rabbitmq prometheus plugin instead
> [rabbitmq] Remove support of the insecure rabbitmq-exporter sidecar

- openstack/designate-nanny/values.yaml
There have been frequent OOM kills observed. This should give enough headroom.
> [designate-nanny] adjusting memory due to OOMs observed

- openstack/keystone/Chart.lock
- openstack/keystone/Chart.yaml
Bump up mariadb-galera in dependencies to 0.29.3 with a small fix for linkerd timeout
> [keystone][mariadb-galera] bump up mariadb-galera in dependencies

- common/prometheus-alertmanager-base/Chart.yaml
- common/prometheus-alertmanager-base/templates/alertmanager.yaml
This PR adds a second label to all notification metrics so that we not only have the type of notification, but also the `receiver_name` to which the notification belongs. Due to the proliferation of Slack channels, this is necessary to properly diagnose errors based on metrics - currently we get one metric for all Slack channels, regardless of the fact that they may represent completely different notification paths.
> common/alertmanager: receiver name on metrics

- openstack/keppel/templates/support_seed.yaml
The domain is called "btp_fp", so we need to do the same string replacement like in `openstack/keppel/templates/seed.yaml`.
> keppel: fix reference to monsoon3/domain-btp-fp-seed

- common/rabbitmq/CHANGELOG.md
- common/rabbitmq/Chart.yaml
- common/rabbitmq/templates/_helpers.tpl
add support for secret injector links in the transport helper scripts
Change-Id: I8a0bc32e816d1e856645835ea6a0c5863521c73a
> [rabbitmq] add secret-injector support to helper

- openstack/barbican/templates/etc/_barbican_audit_map.yaml
Problem:
The audit middleware is attempting to log the binary payload when retrieving secrets from Barbican. This causes a UnicodeDecodeError as the binary data cannot be decoded as UTF-8, leading to incomplete audit logs and potential error flooding.
Solution:
Update the audit mapping for Barbican to specifically exclude payload recording for the secret payload retrieval endpoint. This change allows the audit middleware to log the occurrence of the request and its metadata without attempting to include the binary payload itself.
@rajivmucheli This is my attempted fix. We'd need to test it, but I believe this will work.
> [barbican] update audit map to skip binary payload of secret retreival

- prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/alerts/storage.yaml
The limit per filer is 5000. Adding a info alert when volume count is
above 4500.
> [netapp] add alert for manila filer when number of volumes is close to limit

- common/mariadb/Chart.yaml
- common/mariadb/ci/test-values.yaml
- common/mariadb/templates/_helpers.tpl
- common/mariadb/templates/alerts/_mysql.alerts.tpl
- common/mariadb/templates/deployment.yaml
- common/mariadb/templates/secret.yaml
- common/mariadb/values.yaml
Remove DATA_SOURCE_NAME secret, use MYSQLD_EXPORTER_PASSWORD and constructed mysqld.address option
Update alerts:
The metric mysql_info_schema_threads_seconds has been renamed to mysql_info_schema_processlist_seconds with exporter v0.14.0+ see prometheus/mysqld_exporter#603
> [mariadb] update mysqld-exporter to version 0.15.1

- openstack/hermes/templates/etc/_logstash.conf.tpl
Modify Logstash filter to correctly identify project IDs in Keystone audit events. When target.id exists and target.typeURI is "data/security/project", move target.id to target.project_id. This ensures consistent handling of project identifiers across different audit event types.
> [hermes] keystone transform target.id to target.project_id

- openstack/keppel/templates/seed-catalog.yaml
- openstack/keppel/templates/seed.yaml
- openstack/limes/templates/_utils.tpl
- openstack/limes/templates/configmap-liquids.yaml
- openstack/limes/templates/deployment-liquids.yaml
- openstack/limes/templates/ingress-liquids.yaml
- openstack/limes/templates/seed-catalog.yaml
- openstack/limes/templates/seed.yaml
- openstack/limes/templates/service-liquids.yaml
- openstack/limes/values.yaml
The seed split thing is because the openstack-seeder domain seeds are currently in shambles, and by splitting off the catalog seeds into their own seed objects, I can apply them separately without having to depend on any seed dependencies.
> add liquid-swift deployment to Limes, deploy Keppel/Limes catalog entries via separate seeds

- prometheus-exporters/snmp-exporter/Chart.lock
- prometheus-exporters/snmp-exporter/Chart.yaml
- prometheus-exporters/snmp-exporter/alerts/snmp-hsm.alerts
- prometheus-exporters/snmp-exporter/values.yaml
fixes configuration error in HSM alerts introduced by https://github.com/sapcc/helm-charts/commit/f0277f967b163bb2cdba5a0555e552a79cb1673f
> feat(snmp-exporter): add service to owner-info

- common/mariadb/Chart.yaml
- common/mariadb/templates/_helpers.tpl
- common/mariadb/templates/deployment.yaml
No need to target cluster service for pod-only mysqld-exporter scrapes
> [mariadb] mysqld-exporter scrapes localhost pod-local mysql target

- common/rabbitmq/CHANGELOG.md
- common/rabbitmq/Chart.yaml
- common/rabbitmq/templates/_helpers.tpl
- common/rabbitmq/templates/alerts.yaml
- common/rabbitmq/templates/bin-configmap.yaml
- common/rabbitmq/templates/custom-conf-configmap.yaml
- common/rabbitmq/templates/deployment.yaml
- common/rabbitmq/templates/headless-service.yaml
- common/rabbitmq/templates/poddisruptionbudget.yml
- common/rabbitmq/templates/pvc.yaml
- common/rabbitmq/templates/service.yaml
- common/rabbitmq/templates/servicemonitor.yaml
- common/rabbitmq/templates/statefulset.yaml
- common/rabbitmq/values.yaml
- Update RabbitMQ to version 3.13.6-management
- Add `helm.sh/chart` label
- `app.kubernetes.io/version` is now an application version
> [rabbitmq] Update RabbitMQ to 3.13.6, add helm.sh/chart label

- openstack/ironic/templates/_conductor-deployment.yaml.tpl
- openstack/ironic/templates/api-deployment.yaml
- openstack/ironic/templates/inspector-conductor-deployment.yaml
- openstack/ironic/templates/inspector-deployment.yaml
- openstack/ironic/templates/pxe-deployment.yaml
Setting the default container for all deployments so we see a useful log
instead of linkerd.
> [ironic] add default containers

- openstack/utils/Chart.yaml
- openstack/utils/templates/_hosts.tpl
- openstack/utils/templates/_ini_sections.tpl
- openstack/utils/templates/snippets/_proxysql.cfg.tpl
- with a new secret-injector we cannot use urlquery over new secret vault references.
- with a new helper function we work around it by adding 'resolve' on the fly with optional urlquery at the end where it is needed.
- this patch also uses new helper for places where we had urlquery before. This would allow to simplify the values inside the secrets repo.
> [utils] add helper to resolve secrets that need urlquery function

- common/mysql_metrics/Chart.yaml
- common/mysql_metrics/ci/test-values.yaml
- common/mysql_metrics/templates/_helpers.tpl
- common/mysql_metrics/templates/etc/_config.yml.tpl
We use single quoted literal strings to avoid any unnecessary escaping
go-mysql DSN itself doesn't require any escaping for username and password
> [mysql_metrics] Use resolve for mysql-metrics connection string

- openstack/octavia/values.yaml
This PR enables HTTP2 profile for all of the regions by default because F5 were upgraded.
> [octavia] Enable HTTP2 profile by default everywhere.

- prometheus-rules/prometheus-controlplane-rules/Chart.lock
- prometheus-rules/prometheus-controlplane-rules/Chart.yaml
- prometheus-rules/prometheus-controlplane-rules/values.yaml
The owner-info dependency belongs in the top-level chart, and only there. At best, putting it in a subchart will be ignored. At worst, it will override the owner-info of the top-level chart.
> fix misplaced owner-info

- system/greenhouse-ccloud/templates/_predefinedfilters.conf.tpl
- system/greenhouse-ccloud/templates/alerts-plugin.yaml
Allow configuration of filter tabs in Alerts via predefinedFilters. Part of: https://github.com/cloudoperators/greenhouse-extensions/issues/258
> feat(alerts): added predefindedFilters to pluginConfig for alerts

- openstack/nova/Chart.lock
- openstack/nova/Chart.yaml
- openstack/nova/ci/test-values.yaml
Main goal is to get the versions with secrets-injector support, but if there are other sensible improvements, we take them, too.
bump mariadb from 0.10.1 to 0.14.1
* Add standardised labels
* bump backupv2 image version
* update mysqld_exporter to 0.15.1
* mysqld_exporter scrapes from localhost
* support secrets-injector
bump mysql_metrics from 0.3.2 to 0.3.5
* support secrets-injector
bump rabbitmq from 0.6.9 to 0.11.0
* switch Secret from stringData to data
* add standardised labels
* support secrets-injector
* support new and old metrics in RabbitMQRPCUnackTotal alert
* remove rabbitmq-exporter sidecar in favor of rabbitmq prometheus plugin
* update rabbitmq from 3.13.0 to 3.13.6
bump memcached from 0.1.5 to 0.4.0
* add linkerd annotation
* add standardised labels
* bump …
> [Nova] Bump versions of dependencies

- openstack/manila/aggregates/openstack/castellum.yaml
- openstack/manila/templates/prometheus-aggregates.yaml
- openstack/manila/values.yaml
Metrics to list shares that are in "error" status and shares that are
snapmirror targets. Currently, Castellum calls manila API's to filter
those shares. We provides these metrics for better performance.
> [manila] metrics for castellum's exclusion resons

- openstack/manila/aggregates/storage/castellum.rules
Follow up of migrating netapp exporters to netapp harvest
The rules are duplicated in previous PR. The identical rules does not produce multiple metrics. With this pr, we migrate the rules to use harvest metrics, producing different set of labels. And there will be two set of castellum metrics.
> [manila] use harvest metrics in castellum rules

- openstack/keppel-auto/Chart.lock
- openstack/keppel-auto/Chart.yaml
- openstack/keppel-auto/ci/test-values.yaml
- openstack/keppel-auto/templates/configmap-managed-accounts.yaml
- openstack/keppel-auto/values.yaml
Similar to the limes-auto chart, this is for automatic deployments of certain configuration files, specifically the seed configuration for managed accounts.
On its own, this deployment will do nothing until we change the main Keppel chart to consume this configmap.
> keppel-auto: init

- common/memcached/Chart.yaml
- common/memcached/ci/test-values.yaml
- common/memcached/templates/_helpers.tpl
- common/memcached/templates/secrets.yaml
Use urlquery both for username and password
* These values are consumed literally in urlqueried form by memcached
* These values should be urlqueried in `[cache]` section of the services configuration and consumed literally there, because they can't contain `$` sign.
> [memcached] Use resolve for  sasl-db secret string

- openstack/limes/alerts/openstack/api.alerts
- openstack/limes/templates/deployment-collect.yaml
Companion for https://github.com/sapcc/limes/pull/535
- alert when the limes_quota_override_syncs metric indicates problems
- do not restart the collector on changes to the config file, since the new job reloads the config file on each run anyway
> limes: adjust for new ApplyQuotaOverrides cronjob

- openstack/cc3test/alerts/ccloud-prometheus.alerts
I want the alert to be warning only if there is a more immanent action required. Default goes with info and this is visible in our dashboard already, as info alerts are taken care of too.
> chore(cc3test): warn and info for cert alerts

- openstack/placement/Chart.lock
- openstack/placement/Chart.yaml
- openstack/placement/ci/test-values.yaml
- openstack/placement/templates/etc/_secrets.conf.tpl
- openstack/placement/templates/seed.yaml
We need to bump our charts, especially the `utils` chart, to get support for vault+kkv2 secret references. We enable this support inside our chart by using the `resolve_secret` helper, which can work with the old, literal values and the new vault+kkv2 references.
Bump mariadb from 0.10.1 to 0.14.1
* Add standardised labels
* bump backupv2 image version
* update mysqld_exporter to 0.15.1
* mysqld_exporter scrapes from localhost
* support secrets-injector
Bump memcached from 0.2.0 to 0.4.0
* add linkerd annotation
* add standardised labels
* bump memcached-exporter to v0.14.1
* increase default cpu limit from 0.1 to 0.5
* bump memcached from 1.6.21 to 1.6.28
Bump utils from 0.15.0 to 0.18.1
* add helm pre-upgrade weight to proxysql
* better error message on missing proxysql password
* …
> [Placement] Support secrets-injector

- openstack/neutron/templates/etc/_ml2-conf.ini.tpl
When a hostgroup overrides its vlan pool we need to pick that name for the list of network_vlan_ranges instead of the switchgroup name. This might lead to duplicate names in the list for now, but as in some cases we might also override the vlan ranges we can't just deduplicate this. As this is only relevant for qa for now we'll leave it as is and rethink this once it becomes a problem.
> [neutron] Honor override_vlan_pool in fabric config

- openstack/cronus/Chart.lock
- openstack/cronus/Chart.yaml
- openstack/cronus/ci/test-values.yaml
- openstack/cronus/templates/_helpers.tpl
- openstack/cronus/templates/cronus/secrets.yaml
- openstack/cronus/templates/nebula/secrets.yaml
- openstack/cronus/templates/rhea/secrets.yaml
* Add helper helm functions with secrets-injector resolve support
* Pass username, password and host as arguments for the helper function
* Add CI test-values
* Update rabbitmq helm dependency to 0.11.0: full secrets-injector support
Note: rabbitmq chart 0.7.3 -> 0.11.0 upgrade could require service rabbitmq statefulset removal because this chart contained the bug in version 0.6.13-0.7.5, which made upgrade impossible.
> [cronus][rabbitmq] Add support for secrets-inejctor resolve for RabbitMQ URIs

- system/unbound/templates/config.yaml
That will unset the RA bit in the NXDOMAIN response for a blocked domain.
That will help clients deduce whether an NXDOMAIN is a result of an RPZ match (RA unset) or an actual, authoritative NXDOMAIN (RA set).
> [unbound] toggle the rpz-signal-nxdomain-ra flag for the RPZ zones

- system/gatekeeper-config/templates/constraint-owner-info-on-helm-releases.yaml
These namespace and charts are used to test owner-label-injector in qa-de-1
> Add owner-label-injector-staging config to knownBrokenReleases

- openstack/sap-seeds/templates/flavor-seed.yaml
BTP requested this flavor with 8-to-1 RAM-to-CPU ratio.
While it is outside of the hardware RAM-CPU ratio, it's a small flavor, and it's high-memory which is not as TCO-sensitive as high-CPU flavors.
Create m_c4_m32_v2 for Sapphire-Rapids clusters as well.
> nova/flavors: Add m_c4_m32 for BTP

- openstack/utils/Chart.yaml
- openstack/utils/templates/_ini_sections.tpl
`utils.rabbitmq_url` takes a `host` argument, but
`default_transport_url` drops it, leaving no option to change the host for default transport url.
> [openstack/utils] Do not drop "host" from default_transport_url

- openstack/elektra/Chart.lock
- openstack/elektra/values.yaml
We recommend not pinning the image version and using the default that is hardcoded into the library chart. Updates can be received by bumping the chart dependency with `helm dep up` (which can be automated with the respective shared CI task).
> elektra: use postgresql-ng version from library chart

- openstack/limes/alerts/openstack/api.alerts
- openstack/limes/values.yaml
No idea why these alerts did not complain in QA, but they sure are complaining in Bronze.
> limes: rename several service_type constants for LIQUIDation, phase 1

- system/bind/Chart.lock
- system/bind/Chart.yaml
- system/bind/templates/etc/_nsi.key.tpl
- system/bind/templates/etc/_rndc.key.tpl
- system/bind/templates/etc/_tsig.key.tpl
With the recent version bump we got a new helper in the `utils` chart that makes it possible to support `secrets-injector` secrets will still maintaining compatibility with not-yet-migrated secret values. In this commit, we use this helper to make the `Bind` chart compatible with `secrets-injector`.
> [bind] support secret injector (auto-resolve)

- openstack/designate-nanny/ci/test-values.yaml
- openstack/designate-nanny/templates/secret.yaml
- openstack/designate/ci/test-values.yaml
- openstack/designate/templates/seeds.yaml
Seeder supports the new secrets injector as well, so initial credentials can be seeded as well.
> [designate-nanny] using secrets injector for seeder as well

- common/postgresql-ng/Chart.yaml
- common/postgresql-ng/bin/init-generate-secrets.sh
This might be why these never worked....... I saw related errors in a random controller-manager log that I was checking for a different reason.
```
E0906 11:59:09.695844      11 garbagecollector.go:406] "error syncing item" err="unable to get REST mapping for v1/Deployment." item="[v1/Secret, namespace: codimd, name: codi-pguser-metrics, uid: 0b87eb36-4a85-4f7c-9018-878a3e7c615a]"
```
If this fixes the problem of these secrets not getting cleaned up with the deployment, we can make a followup PR to get rid of the delete-secrets job hook.
> postgresql-ng: fix apiVersion in ownerReferences

- system/greenhouse-ccloud/Chart.yaml
- system/greenhouse-ccloud/templates/kube-monitoring-storage-pluginpreset.yaml
kube-state-metrics are pulled in kube-monitoring chart already, with values for kube-state-metrics subchart of kube-prometheus-stack.
> revert 1e5f8f2

- common/redis/Chart.yaml
- common/redis/templates/deployment.yaml
The mechanics of how the annotation causes the deployment to roll out is explained here - https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments.
Without this PR any changes of Redis configuaration or password require additional intervention (e.g. manual `kubectl rollout restart deployment`) to make them picked up, which doesn't scale well on frequent changes or with numerous deployments.
> redis: make Deployment roll out on configuration changes

- openstack/trust-manager/templates/exporter.yaml
This PR add cert-exporter [1] to trust manager. It reviews the configmaps created by the trust manager bundle and checks the expiration dates of the certificats. Available metrics `cert_exporter_configmap_expires_in_seconds`, `cert_exporter_configmap_not_after_timestamp` and `cert_exporter_configmap_not_before_timestamp`.
[1] https://github.com/joe-elliott/cert-exporter
> [trust-manager] monitor certs' expiration dates

- openstack/trust-manager/templates/exporter.yaml
- openstack/trust-manager/values.yaml
Have to specify it, because trust manager itself is deployed in `kube-system`.
> [trust-manager] specify namespace for exporter

- openstack/kubernikus/templates/seed.yaml
Not needed anymore after quota editing has been removed from Limes.
> kubernikus: remove cloud_resource_admin role assignment

- system/kube-monitoring-admin-k3s/Chart.lock
- system/kube-monitoring-admin-k3s/Chart.yaml
- system/kube-monitoring-kubernikus/Chart.lock
- system/kube-monitoring-kubernikus/Chart.yaml
- system/kube-monitoring-metal/Chart.lock
- system/kube-monitoring-metal/Chart.yaml
- system/kube-monitoring-virtual/Chart.lock
- system/kube-monitoring-virtual/Chart.yaml
version constraints was introduced for scaleout, this add them for the other contexts as well.
This makes sure the routing fix for `PodOOMKill` will be made available for the other clusters as well. 
If you feel this is to pushy, I am also fine with replacing the `appVersion` with `version` and setting it to latest.
> chore(kube-monitoring): use version constraint for oomkill

- openstack/cinder/values.yaml
- openstack/nova/values.yaml
We need to switch away from `localos` users to `vsphere.local` users with vSphere 8.
> Switch Nova + Cinder to `vsphere.local` users

- system/greenhouse-ccloud/Chart.yaml
- system/greenhouse-ccloud/templates/kube-monitoring-storage-pluginpreset.yaml
* preset should be maintained with the cluster selector and the cluster
* this is obfuscating what actually matches
* switch to generic label
> feat(kube-monitoring): don't manage preset externally

- system/greenhouse-ccloud/Chart.yaml
- system/greenhouse-ccloud/ci/test-values.yaml
- system/greenhouse-ccloud/templates/team-rolebindings.yaml
- system/greenhouse-ccloud/templates/team-roles.yaml
- system/greenhouse-ccloud/values.yaml
- plugin-developer teamrolebinding can be used to give devs the ability to debug in their plugin's namespace
- cluster-admin teamrole is seeded for each org by greenhouse
- add ability to specify namespaces for TeamRoleBindings
> feat(gh-ccloud): add plugin-developer TRB, remove cluster-admin

- openstack/neutron/templates/vct-nsxv3-agent-secret.yaml
- openstack/neutron/values.yaml
nsxv3-agents use the `vcenter-operator` to get deployed. The `vcenter-operator` is responsible for generating the individual agent's password with the masterpassword algorithm. While we use the user "admin" to log into the NSX-T agents, we used the current `vcenter-operator`'s user to generate the password.
With changing the `vcenter-operator`'s user to using a user from the `vsphere.local` domain, we now can't use the from there anymore. Instead, we introduce a new variable to read the user from and set the old user there.
> [Neutron] Explicitly set user for NSX-T password generation

- openstack/keystone/templates/bin/_db-sync.tpl
The --check seems to be broken upstream. Until it is fixed, lets just run the upgrade when possible. It will not re-run them if it is already done, so we should be safe.
https://bugs.launchpad.net/keystone/+bug/2080542
> keystone: do not rely on db version check

- openstack/elektra/Chart.lock
- various image rebuilds to fix security vulnerabilities
- fix ownerReferences in pguser secrets
Please set up a helm-dep-up job in your pipeline to reduce the amount of PRs like this.
> elektra: bump postgres dependencies

- openstack/ironic/values.yaml
Most often, we actually use VMDKs. Stream-optimized ones are actually smaller than QCOW2 files (presumably without compression).
> [ironic] Add VMDK to the list of permitted image formats

- openstack/keystone/templates/etc/_keystone.conf.tpl
The corresponding check is done here -
https://github.com/sapcc/keystone-extensions/blob/225d920c1b623365588a145319a060242a7b4d9d/cc/keystone/auth/plugins/cc_x509.py#L73
Additionally, see `cc/secrets/pull/15277`.
> Keystone: Remove old `SSO_CA` from trusted issuers upon SSO auth cert validation

- system/kubernikus-admin-k3s/Chart.lock
- system/kubernikus-admin-k3s/Chart.yaml
- system/kubernikus-admin-k3s/values.yaml
- system/kubernikus-metal/Chart.lock
- system/kubernikus-metal/Chart.yaml
- system/kubernikus-metal/values.yaml
Brings k8s 1.28.14, 1.29.9 and 1.30.5 which fixes the init container regression. Also bumps the kubernikus and owner-info chart.
> Bump kubernikus image

- prometheus-exporters/netapp-exporter/charts/netapp-cap-exporter/aggregations/netapp-cap.rules
- prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/Chart.yaml
- prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/aggregations/maia.yaml
- prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/etc/rest.custom_volume.yaml
- prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/etc/rest.iscsi_session.yaml
- prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/templates/_harvest.yaml.tpl
- prometheus-exporters/netapp-exporter/charts/netapp-perf-exporter/aggregations/netapp-perf.rules
prepare aggregation rules for maia using harvest metrics 
fallback to old maia metrics from capacity exporter
rolled out manually to qa
> [netapp] switch to harvest for maia

- openstack/ironic/Chart.lock
- openstack/ironic/Chart.yaml
- openstack/ironic/ci/test-values.yaml
- openstack/ironic/templates/etc/_inspector_secrets.conf.tpl
- openstack/ironic/templates/etc/_secrets.conf.tpl
* [mariadb][backup] Use resolve helper for backup_v2 secrets
* [mariadb] initdb secret is required during install
* [memcached] Use resolve for sasl-db secret string
* [mysql_metrics] Use resolve for mysql-metrics connection string
* [rabbitmq] remove unused unacknowledged alert from rename
* [utils] add helper to resolve secrets that need urlquery function
* utils: Resolve no-longer-used "identity.password_for_user"
* utils: Resolve username for mysql and F5 URls
* [utils] Add support for secrets-injector for db_url_pxc function
* [openstack/utils] Do not drop "host" from default_transport_url
> [ironic]: multiple dependency updates

- openstack/ironic/templates/seed.yaml
No longer needed for Nova. Since https://github.com/sapcc/nova/pull/493, Nova reads quota:separate from the flavors.
> [Ironic][seeds] remove quota_class_sets

- openstack/manila/templates/migration-job.yaml
remove condition for secret config.
All secrets have been moved, so it is no longer needed for
'pre-upgrade'.
And the condition is wrong for 'post-install',
because the lookup happens before install and the migration script
would fail to run without the secrets on a fresh installation now.
> [manila] cleanup migration job

- openstack/keystone/Chart.yaml
- openstack/keystone/templates/etc/_policy.yaml.tpl
- openstack/keystone/values.yaml
After https://review.opendev.org/c/openstack/keystone/+/900028 got accepted, domain-scoped tokens can no longer list all domains, only the domain of the scope will be returned. Our tempest uses scope on domain to run some tests, and it fails with the change.
Add a new value to help configure project scope for tempest. The new value .Values.tempest.adminProjectId needs to be set to the `admin` project id.
The corresponding change in tempest to use this is done in a different repo/pr.
> Keystone: switch tempest to project scope

- .github/CODEOWNERS
- ci/config.yaml
- system/percona-xtradb-cluster-crds/Chart.yaml
- system/percona-xtradb-cluster-crds/README.md
- system/percona-xtradb-cluster-crds/crds/perconaxtradbclusterbackups.pxc.percona.com.yaml
- system/percona-xtradb-cluster-crds/crds/perconaxtradbclusterrestores.pxc.percona.com.yaml
- system/percona-xtradb-cluster-crds/crds/perconaxtradbclusters.pxc.percona.com.yaml
- system/percona-xtradb-cluster-crds/get-crds
- system/percona-xtradb-cluster-crds/templates/crds.yaml
- system/percona-xtradb-cluster-crds/values.yaml
- system/percona-xtradb-cluster-operator/.helmignore
- system/percona-xtradb-cluster-operator/Chart.lock
- system/percona-xtradb-cluster-operator/Chart.yaml
- system/percona-xtradb-cluster-operator/values.yaml
* Use pxc-operator chart from Percona repository
* Provide default values
* Add percona-xtradb-cluster-operator-crds chart
It makes possible to manage pxc CRDs separately from pxc-operator
* Update CODEOWNERS
Might supersede https://github.com/sapcc/helm-charts/pull/6994
> [pxc-operator] Add percona-xtradb-cluster-operator as umbrella chart

- px/bird/templates/_helpers.tpl
If multiple host were prevented (due to miscabling) the first one would
print with a correct indent, due to the contnrol instruction being
indented, yet the second host would have a different indent. That lead
to a YAML parse error. To fix that, we are using `nindent` which inserts
a line break and then start with the values indented by `nindent`s
value.
> Fix incorrect indention for prevented host

- openstack/nova/templates/bigvm-deployment.yaml
- openstack/nova/templates/cell2-conductor-deployment.yaml
- openstack/nova/templates/conductor-deployment.yaml
- openstack/nova/templates/scheduler-deployment.yaml
With [0] the `python-agentliveness` command got the ability to cache the token and re-use it. We would like to use that functionality, because requesting a new token every liveness check a) puts more load on keystone for getting the token and b) puts more load on keystone for the service not having cached the token and thus asking keystone for its validity.
[0] https://github.com/sapcc/python-agentliveness/pull/7
---
Tested by manual deployment in a lab.
> [Nova] Enable token caching for openstack-agent-liveness

- openstack/utils/Chart.yaml
- openstack/utils/templates/_helpers.tpl
The "osprofiler" helper needs to resolve the `hmac_keys` setting from Vault.
> [openstack/utils] Use secrets-injector for osprofiler

- prometheus-exporters/openstack-exporter/Chart.yaml
- prometheus-exporters/openstack-exporter/alerts/cinder.alerts
increase the severity of openstack-exporter alert of cinder CinderShardMaxVolumeSize alert to warning instead of info
Change-Id: I9f794c1c293ed58e14fe31cc680b37a2d3e38c0e
> [Cinder]increase severity CinderShardMaxVolumeSize

- openstack/octavia/templates/etc/_octavia.conf.tpl
- openstack/octavia/values.yaml
This PR adds new options `http_request_max_retries` and `http_connect_timeout` to Octavia's configuration to control connection failures to keystone.
> Add timeout and retries options for Octavia keystone_authtoken.

- common/pxc-db/Chart.yaml
- common/pxc-db/templates/_helpers.tpl
- common/pxc-db/templates/cluster.yaml
- common/pxc-db/templates/initdb-bin.yaml
- common/pxc-db/templates/initdb-job.yaml
- common/pxc-db/templates/initdb-secret.yaml
- common/pxc-db/templates/secrets.yaml
- common/pxc-db/values.yaml
* Replace underscores with dashes in name labels
* Don't create backup user by default. System xtrabackus is being used
* Rename secrets - use pxc-db suffix consistently
> [pxc-db] Follow-up cosmetic improvements

- openstack/cinder/Chart.lock
- openstack/cinder/Chart.yaml
- openstack/cinder/ci/test-values.yaml
- openstack/cinder/templates/backup_deployment.yaml
- openstack/cinder/templates/etc/_secrets.conf.tpl
- openstack/cinder/templates/etc/_volume-secrets.conf.tpl
- openstack/cinder/templates/etc/_volume.conf.tpl
- openstack/cinder/templates/seed.yaml
For supporting resolving Vault secrets via `secrets-injector`, we have to bump the charts we're depending on. This includes the following changes:
utils 0.15.0 -> 0.18.4:
* add helm pre-upgrade weight to proxysql
* better error message on missing proxysql password
* support secrets-injector
mariadb 0.10.1 -> 0.14.2:
* Add standardised labels
* bump backupv2 image version
* update mysqld_exporter to 0.15.1
* mysqld_exporter scrapes from localhost
* support secrets-injector
mysql_metrics 0.3.2 -> 0.3.5:
* support secrets-injector
memcached 0.2.0 -> 0.5.3:
* add standardised labels
* bump memcached-exporter to v0.14.1
* increase default cpu limit from 0.1 to 0.5
* bump memcached from 1.6.21 to 1.6.28
* sasl support
rabbitmq 0.7.3 -> 0.11.1:
* switch Secret from stringData to data
* add …
> [Cinder] Support secrets-injector

- openstack/nova/Chart.lock
- openstack/nova/Chart.yaml
The `utils` chart bumped itself automatically. The changes are `secrets-injector`-related fixes we do not really need.
Bumping the `rabbitmq` chart version makes the
`AbsentComputeStorageApiNovaRabbitmqQueueMessagesUnacknowledged` go away.
> [Nova] Bump rabbitmq and utils Chart

- openstack/utils/Chart.yaml
- openstack/utils/proxysql_sidecar.md
- openstack/utils/templates/_hosts.tpl
- openstack/utils/templates/_proxysql.tpl
hostAlias and ProxySQL configuration should be identical to the db service
> [utils][pxc-db] Use db-haproxy suffix for pxc services consistently

- openstack/utils/Chart.yaml
- openstack/utils/templates/_proxysql_secret.yaml.tpl
ProxySQL configuration now could be in the following states:
- if .Values.dbType isn't set and mariadb present in chart dependencies
-> only mariadb is left in proxysql configuration
- if pxc is present in chart dependencies and proxysq.multiDestination=true:
-> both mariadb and pxc present in proxysql configuration
- if pxc is present in chart dependencies, dbType=pxc-db and proxysq.multiDestination=false
-> only pxc is left in proxysql configuration
These states will be used during data migration from one database to another.
> [utils][pxc-db] Add an option to have all DBs in ProxySQL configuration

- openstack/neutron/Chart.yaml
- openstack/neutron/templates/service-nsxv3-logstash.yaml
- openstack/neutron/templates/sftp-service.yaml
With calico BGP, we need to advertise the external service IPs /32 IP to upstream switches to make it more preferred than a summary route.
> [neutron] set external service `externalTrafficPolicy` to Local

- openstack/sap-seeds/templates/flavor-seed.yaml
Not for Sapphire-Rapids flavors yet, because the VCenters aren't upgraded to 8.0 and don't know about this CPU generation yet.
> nova/flavors: Add intel-cascadelake evc mode on GP flavors

- openstack/cinder/templates/vcenter_datacenter_cinder_secret.yaml
This patch updates the name of the cinder backend definition for cinder-volume.conf for the fcd driver and adds the proper storage profile setting.
This also adds the new extra_capability reporting for each backend called quality_type.  For vmware and fcd the quality type is set to premium.  For standard_hdd the quality type is set to standard.
This allows us to add volume type extra specs to distinguish on backend based on quality_type.
> [CINDER] update fcd name and add quality type

- openstack/limes/alerts/openstack/api.alerts
This alert is intended only for resources where regular users have no way to extend the quota themselves.
Tested on firing alert in eu-de-2, works as intended there.
> limes: remove non-growing-quota alert for committable resources

- openstack/nova/templates/etc-secret.yaml
nova-compute-ironic uses the ironic service user when talking to the Ironic API. Since this user is also used by Ironic itself, it's harder to coordinate password changes
(both Nova and Ironic need the new password at the same time). Additionally, it's not clear that Nova is talking to Ironic if the user is ironic.
> [nova] nova-compute-ironic to use the `nova` service user

- openstack/ironic/templates/etc/_api_audit_map.yaml.tpl
Update audit map with api reference additions to Ironic
If you'd like to check my work (appreciated) here is the [api reference](https://docs.openstack.org/api-ref/baremetal/)
I added chassis even though it's depercated because it's still callable. You may prefer a different decision based on the context you have for if it is still callable or usable.
> update ironic api audit map for new endpoints

- global/concourse-main/values.yaml
For reference the webhook broadcaster containers this change:
https://github.com/sapcc/webhook-broadcaster/commit/e1e02c3f0a8d5433c8b38364f77b11eb4cde6ca1
> [concourse-main]: bump webhook exporter to 0.10.0, add service to owner-info

- openstack/ironic/ci/test-values.yaml
- openstack/ironic/templates/api-deployment.yaml
- openstack/ironic/templates/etc-configmap.yaml
- openstack/ironic/templates/etc/_ironic.conf.tpl
- openstack/ironic/templates/etc/_watcher.conf.tpl
- **ironic: enable watcher in testing**
> ironic watcher

- system/cc-ceph/Chart.yaml
- system/cc-ceph/templates/ceph-config-override.yaml
- system/cc-ceph/values.yaml
This PR add a support for `accepted_admin_roles` and `accepted_reader_roles`
https://github.com/ceph/ceph/blob/b2a4bd8409dcfaaa2e84ed450a0d31126ac9b4c3/src/common/options/rgw.yaml.in#L808
> [ceph] add admin and reader roles support

- openstack/barbican/Chart.lock
- openstack/barbican/Chart.yaml
- openstack/barbican/ci/test-values.yaml
That will cause a db restart due mysqld-exporter sidecar v0.12.1 -> v0.15.1
> [barbican] Update mariadb to 0.14.2 for secrets-injector

- openstack/glance/Chart.lock
- openstack/glance/Chart.yaml
- openstack/glance/ci/test-values.yaml
That will cause a db restart due mysqld-exporter sidecar v0.12.1 -> v0.15.1
> [glance] Update mariadb to 0.14.2 for secrets-injector

- openstack/kmip/Chart.lock
- openstack/kmip/Chart.yaml
- openstack/kmip/ci/test-values.yaml
- openstack/kmip/templates/deployment.yaml
- openstack/kmip/templates/secrets.yaml
This is needed for the switch to secrets-injector. It will cause a reboot of the db due to a different sidecar image version.
> [kmip] Update mariadb chart to 0.14.2

- openstack/ironic/templates/api-deployment.yaml
The watcher change was not working. K8s was not able to mount the
watcher.conf as the /etc/ironic/ironic.conf.d path was a volume used to
add the secrets for ironic. This worked while manual editing the
deployment. Very big thanks to @I500815 who helped author this.
> ironic: fix k8s mount configmap issue

- openstack/nova/templates/hypervisors/hypervisors-vmware-deployment-vct.yaml
- openstack/nova/values.yaml
We want to ignore certain warnings from Python, especially the `SyntaxWarning`, because it gets logged for `pymemcache` seemingly outside of a `GreenThread` which can lead to services hanging in locks.
We also switch the VMware Hypervisor Deployment to use the same value `python_warnings` as we already use for any other Deployment.
> Nova: Set PYTHONWARNINGS by default

- openstack/ironic/templates/api-deployment.yaml
the indentation was wrong breaking the deployment
> ironic: fix syntax

- common/rabbitmq/CHANGELOG.md
- common/rabbitmq/Chart.yaml
- common/rabbitmq/templates/_helpers.tpl
Append urlquery in `rabbitmq.resolve_secret_urlquery` function for non-vault values
Similar to https://github.com/sapcc/helm-charts/pull/7250
> [rabbitmq] Use urlquery in `resolve_secret_urlquery` for non-vault values

- openstack/ironic/values.yaml
We somehow apparently never enabled audit. Now we enable it by default.
> ironic: enable audit as default

- openstack/manila/Chart.lock
- openstack/manila/Chart.yaml
- openstack/manila/templates/etc/_secrets.conf.tpl
* Use utils `ini_sections.default_transport_url` helper instead of rabbitmq
* Update utils chart from 0.16.0 to 0.19.4 (secrets-injector support)
* Update mysql_metrics chart to 0.3.6 (pxc-db support)
* Update redis chart to 1.5.3 (update redis-exporter version)
> [manila][rabbitmq] Use utils helper for rabbitmq transport_url

- openstack/utils/Chart.yaml
- openstack/utils/templates/_hosts.tpl
The helpers _db_url_mariadb and _db_url_pxc_db are calling itself,
which leads to resolve_secret_urlquery being called twice, as the
helper db_credentials is also calling resolve_secret_urlquery.
This urlencodes the template string {{ resolve ... }} instead of the
actual value on the second pass through resolve_secret_urlquery.
> [utils] fixing db_url_mariadb and _db_url_pxc_db double urlencoding

- openstack/neutron/templates/statefulset-network-agent.yaml
There was a typo in the neutron-dhcp-agent readiness probe call making it look for neutron-common-secrets.conff.
Introduced in commit ada6dae2ffe02438f3f1362c5896512928b679db
> [neutron] typo in conf file name for dhcp readiness probe

- px/bird/templates/_configmap-bird.tpl
- px/bird/templates/_deployment-bird.tpl
- px/bird/templates/_helpers.tpl
- px/bird/templates/_nad_multus.tpl
- px/bird/templates/_service_pxrs.tpl
- px/bird/templates/podmonitor.yaml
- px/lg/templates/configmap-communities.yaml
- px/lg/templates/configmap.yaml
- px/lg/templates/deployment.yaml
- px/lg/templates/ingress.yaml
- px/lg/templates/lg.conf.tpl
- px/lg/templates/service.yaml
I'd rather roll out multiple small changes than a single large one. Hence this is prep work in order to introduce IPv6 statefulsets to the PX deployments. Details to be found in the individual commit message.
- Use StatefulSet instead of deployments
- Simplify PX charts: Region names not put all over all places
- Use different naming for statefulset
- [PX] Set bird as default container
- Remove metricRelabelings as the same labels are already created
> First step to prep PX for IPv6

- common/pxc-db/Chart.yaml
- common/pxc-db/values.yaml
* Increase default net_read_timeout and net_write_timeout
net_write_timeout limits the max size of binlog sent to mysqlbinlog
180s in my tests were enough for 1GB binlog file
* Set connect_timeout to 30s
* Set wait_timeout and interactive_timeout to the same values as in MariaDB
> [pxc-db] Change default timeouts

- openstack/domain-seeds/templates/domain-bs-seed.yaml
- openstack/domain-seeds/templates/domain-btp-fp-seed.yaml
- openstack/domain-seeds/templates/domain-cc3test-seed.yaml
- openstack/domain-seeds/templates/domain-ccadmin-seed.yaml
- openstack/domain-seeds/templates/domain-cis-seed.yaml
- openstack/domain-seeds/templates/domain-cp-seed.yaml
- openstack/domain-seeds/templates/domain-fsn-seed.yaml
- openstack/domain-seeds/templates/domain-hcm-seed.yaml
- openstack/domain-seeds/templates/domain-hcp03-seed.yaml
- openstack/domain-seeds/templates/domain-hda-seed.yaml
- openstack/domain-seeds/templates/domain-hec-seed.yaml
- openstack/domain-seeds/templates/domain-kyma-seed.yaml
- openstack/domain-seeds/templates/domain-monsoon3-seed.yaml
- openstack/domain-seeds/templates/domain-neo-seed.yaml
- openstack/domain-seeds/templates/domain-ora-seed.yaml
- openstack/domain-seeds/templates/domain-s4-seed.yaml
- openstack/domain-seeds/templates/domain-wbs-seed.yaml
this is for our global domains in qa1 and de2
> adds tls_cacertdir: '/etc/ssl/certs/' to all domain ldap configs

- system/doop-central/alerts/infra-frontend/violation.alerts
Obsoletes #7305.
@TilmanHaupt FYI: A personal story about why the rollout of the new URL format for Greenhouse would be hugely appreciated.
> doop-central: fix interpolation of label values into Greenhouse URLs

- system/gatekeeper/templates/constrainttemplate-pod-security.yaml
- system/gatekeeper/tests/gatekeeper-policies/fixtures/pod-security/px-bird-legacy.yaml
- system/gatekeeper/tests/gatekeeper-policies/fixtures/pod-security/px-bird-transistion.yaml
- system/gatekeeper/tests/gatekeeper-policies/suite.yaml
In order to make PX v6 compatible we are adjusting our charts.
* We are removing all references to the region name from the deployments
and containers
* We are migrating each deployment to a statefulset in the first step
* In the second step we are cutting the number of statefulsets in half
by running the statefulset with replicas = 2.
Since the naming and the workload type changed gatekeeper policies must
be adjusted to handle the future and the transition state.
> Adjust gatekeeper policies to handle new PX setup

- openstack/manila/Chart.lock
- openstack/manila/Chart.yaml
owner info and linkerd-support got supported version numbers
without breaking changes
> [manila] bump deps

- system/kube-system-addons/values.yaml
- system/kube-system-admin-k3s/values.yaml
- system/kube-system-kubernikus/values.yaml
- system/kube-system-metal/values.yaml
- system/kube-system-scaleout/values.yaml
- system/kube-system-virtual/values.yaml
- system/kubernikus-admin-k3s/values.yaml
- system/kubernikus-metal/values.yaml
To reduce the number of vulnerable image alerts that are tagged as `service: none` this PR proposes to mark all kube-system charts with `service: kube-system`. Additionally added `service: kubernikus` for a few charts that are clearly kubernikus charts.
- added `service: kube-system` to owner-info of kube-system helm charts
- added `service: kubernikus` to owner-info of kubernikus charts
> fix: add service kube-system to kube-system charts

- openstack/designate/Chart.yaml
- openstack/designate/templates/central-deployment.yaml
Coordination is required for following Designate services:
- designate-central
- designate-producer
This prevents race conditions on recordset creation
See https://bugs.launchpad.net/designate/+bug/1871332
> [designate] Use pvc for file backup coordination in central service

- openstack/manila/templates/shares/_share-netapp.conf.tpl
- prometheus-exporters/openstack-exporter/alerts/manila.alerts
storage team is rebalancing on 70% usage, so we have a 5% buffer
for new share creations, e.g. to fulfil anti-affinity constraints.
Without the buffer we would get too much 'no valid host' situations.
> [manila] set reserve down to 25%

- openstack/keystone/templates/etc/_policy.yaml.tpl
We want to allow everyone to be able to create new projects. This was triggered by customers in a SCoCH ticket and agreed with Esther.
> Keystone: allow everyone to create projects

- openstack/designate/Chart.yaml
- openstack/designate/templates/api-deployment.yaml
- openstack/designate/templates/central-deployment.yaml
- openstack/designate/templates/etc/_designate.conf.tpl
- openstack/designate/templates/mdns-deployment.yaml
- openstack/designate/templates/producer-deployment.yaml
- openstack/designate/templates/worker-deployment.yaml
- openstack/designate/values.yaml
* Move worker per pod configuration to values
* Adjust the number of connections per proxysql to the number of workers
* Remove proxysql sidecar from deployments without DB usage
> [designate] Move worker per pod configuration to values

- openstack/designate/Chart.yaml
- openstack/designate/templates/api-deployment.yaml
- openstack/designate/templates/etc-wsgi-configmap.yaml
- openstack/designate/templates/etc/_mpm_event.conf.tpl
- openstack/designate/templates/etc/_wsgi-designate.conf.tpl
- openstack/designate/values.yaml
* Add mpm_event.conf with the limits similar to Keystone's
* Increase number of apache2 processes from 4 to 8
* Increase API pod memory limits for peak loads
* Increase liveness and readiness timeouts to avoid failing under load
mpm_event.conf default:
```
<IfModule mpm_event_module>
StartServers			 2
MinSpareThreads		 25
MaxSpareThreads		 75
ThreadLimit			 64
ThreadsPerChild		 25
MaxRequestWorkers	  150
MaxConnectionsPerChild   0
</IfModule>
```
New one:
```
<IfModule mpm_event_module>
ServerLimit         1024
StartServers        32
MinSpareThreads     32
MaxSpareThreads     256
ThreadsPerChild     25
ThreadLimit         720
</IfModule>
```
> [designate] Add mpm_event_module configuration for Designate wsgi

- system/plutono/Chart.lock
- system/plutono/Chart.yaml
Your previous version selection was behind by several months. I suggest setting up the helm-dep-up CI task to handle bugfix updates automatically (see Keppel pipeline for what to copy, Ctrl-F "helm-dep-up").
> plutono: bump postgres dependencies

- prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/aggregations/maia.yaml
Use the metrics if thte volume is being used by any clients.
> [netapp][maia] metrics to monitor nfs connections

- common/rabbitmq/CHANGELOG.md
- common/rabbitmq/Chart.yaml
- common/rabbitmq/templates/deployment.yaml
- common/rabbitmq/templates/service.yaml
- common/rabbitmq/templates/statefulset.yaml
Add config.linkerd.io/opaque-ports annotation to avoid protocol detection delay, 10s on every connection to RabbitMQ
https://linkerd.io/2.16/features/protocol-detection/
> [rabbitmq] Add config.linkerd.io/opaque-ports annotation

- prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/aggregations/maia.yaml
Add filer label when matching snapmirror and volume, otherwise multiple
netapp_volume_label might be found for same volume name.
> [manila][maia] update snapmirror metrics

- openstack/barbican/templates/etc/_barbican_audit_map.yaml
Add versions api endpoint to the audit map. We didn't require this before because it's just a read endpoint, but we've turned on read events, and thus it needs to be mapped accordingly.
> [barbican] add versions to audit map

- openstack/limes/alerts/openstack/api.alerts
- openstack/limes/values.yaml
Also, update the service_type to support_group mappings that I forgot about in the last few rounds of LIQUIDation.
Also also, update the resource requests on the existing LIQUID deployments based on the container metrics in prod:
```
CPU: irate(container_cpu_usage_seconds_total{container_name="liquid"}[5m])
RAM: container_memory_working_set_bytes{container_name="liquid"}
```
> limes: deploy liquid-ironic

- openstack/neutron/templates/etc/_dhcp-agent.ini.tpl
The template for the config file was missing a reference to the actual value apparently.
> [neutron] add dhcp agent config for namespace specific resolv.conf

- openstack/manila/Chart.yaml
- openstack/manila/templates/bin/_manila_api.sh.tpl
Disables the server status page of Apache.
This page contains internal information about working process.
> [manila] Disable apache2 server-status endpoint

- openstack/keystone/Chart.yaml
- openstack/keystone/templates/bin/_keystone_api.sh.tpl
Disables the server status page of Apache.
This page contains internal information about working process.
> [keystone] Disable apache2 server-status endpoint

- openstack/designate/Chart.yaml
- openstack/designate/templates/etc/_designate.conf.tpl
- openstack/designate/values.yaml
* Increase default number of rpc workers per pod from 2 to 4
* Remove unused rpc_workers option
* Enable oslo_rpc_server_ping rpc endpoint
* Increase rabbitmq heartbeat interval from 15 to 30 seconds
* Remove deprecated min_pool_size variable, it's not used since Rocky
* Move max_pool_size and max_overflow option to effective section
* Lower db_max_retry_interval from 10 to 1 second
* Set heartbeat_emitter interval, increase it from 10 to 30 seconds
> [designate] increase number of rpc central workers and other fixes

- openstack/designate/Chart.yaml
- openstack/designate/templates/api-deployment.yaml
- openstack/designate/templates/central-deployment.yaml
- openstack/designate/templates/mdns-deployment.yaml
- openstack/designate/templates/producer-deployment.yaml
- openstack/designate/templates/sink-deployment.yaml
- openstack/designate/templates/worker-deployment.yaml
- openstack/designate/values.yaml
We want to ignore certain warnings from Python, especially the `SyntaxWarning` and `Unverified HTTPS request`
> [designate] Set PYTHONWARNINGS by default

- openstack/designate/Chart.yaml
- openstack/designate/templates/central-deployment.yaml
- openstack/designate/values.yaml
Use pod-local file-based coordination by default for central
This should unblock rollout
> [designate] Use pod-local coordination by default for central

- prometheus-exporters/snmp-exporter/alerts/snmp-hsm.alerts
Alert for device down or metric absence.
> [barbican] Update snmp-hsm alerts

- openstack/castellum/templates/_utils.tpl
- openstack/castellum/templates/configmap.yaml
- openstack/keppel/templates/_utils.tpl
- openstack/keppel/templates/configmap.yaml
- openstack/limes/files/policy.yaml
- openstack/limes/templates/configmap-liquids.yaml
- openstack/limes/templates/configmap.yaml
- openstack/limes/templates/deployment-api.yaml
- openstack/limes/templates/deployment-liquids.yaml
This does not entirely remove the YAML parser library from these applications yet, but it's a prerequisite to getting there and reducing our dependency tree a little bit.
This change is immediately deployable because JSON is a subset of YAML to a sufficient extent.
> castellum, keppel, limes: use policy.json instead of policy.yaml

- openstack/designate/Chart.yaml
- openstack/designate/values.yaml
Reduce default number of workers per pod to 2
Reduce back default number of pods to 3 per region
> [designate] reduce number of central workers back to 2 by default

- px/bird/templates/_deployment-bird.tpl
- px/bird/templates/_helpers.tpl
* Currently we have a set of nodeAffinity to pin PX pods to apods that are cabled for PX. We have podAntiAffinity to make sure that a PX service does not run with a pod of the same service on the same phyiscal node. Another podAntiAffinity makes sure that an PX instance (PX has 2 instances per domain and service) of the same PX service never runs in the same AZ. This leads to the each PX Domain being spread over at least 2 AZs. 
See original issue: https://github.wdf.sap.corp/cc/px/issues/181
* Add topology spread contraints such that pods are spread over more than 2 AZs, considering each time only the pods  that belong to the same service and AFI. 
See: https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints
> [px] feat: spread pods in multiple AZs

- openstack/designate/Chart.yaml
- openstack/designate/templates/etc/_designate.conf.tpl
- openstack/designate/values.yaml
This would allow us to set a shorter time_threshold for deleted zone purge in QA environments.
In these QA environments, it might be reasonable to set a 5-day threshold (432000) instead of the default 30.
> [designate] Make periodic deleted zone purge configuration changeable

- prometheus-exporters/network-generic-ssh-exporter/alerts/asr.alerts
Removed trailing slash in the playbook [URL](https://operations.global.cloud.sap/docs/devops/alert/network/ntp/)
> i511559_remove_railing_slash

- system/bind/templates/etc/_secret_env.tpl
- system/bind/templates/secrets.yaml
IOW, if we have:
---
data:
foo: bar
john: doe
---
it's just 'bar' and 'doe' we need to encode and not the whole thing within 'data:'
> [bind] base64 encode just the key values within secret-env

- system/bind/templates/secrets.yaml
The "kubernetes.io/tls" type was a copy/paste error.
With it the deployment was failing with the following error: Error: UPGRADE FAILED: failed to create resource: Secret "bind-nsd-qa-de-1-secret-env" is invalid: [data[tls.crt]: Required value, data[tls.key]: Required value]
> [bind] the secrev-env secret is of type Opaque

- system/bind/templates/deployment.yaml
- system/bind/templates/secrets.yaml
Not all bind instances will have a secret env, so no need to create it and load it.
> [bind] do no create and load the secret-env secret if empty

- common/mariadb/Chart.yaml
- common/mariadb/templates/config/_backup_config.yaml.tpl
fixes error in AWS S3:
`InvalidArgument: The secret key was invalid for the specified algorithm.`
> fixes unnecessary quotes for sse_customer_key

- openstack/limes/values.yaml
This ought not take this much memory. I will check with a profiler when I have the chance.
> limes: temporary fix for oomkill in liquid-ironic

- prometheus-exporters/snmp-exporter/generator/f5mgmt-generator.yaml
The DNS cache function was moved from the F5s to the unbound servers in the backend.
The related DNS oids are not needed anymore.
Adding new node oid to monitor the current connection count to the unbounds.
Also removing unused oids.
> [snmp exporter] - update f5mgmt oid indexes

- openstack/designate/Chart.yaml
- openstack/designate/templates/etc/_wsgi-designate.conf.tpl
- openstack/designate/values.yaml
Reduces the number of processes from 8 per pod down to expected 4
> [designate] Use api_workers for WSGI API processes limit

- openstack/designate/Chart.yaml
- openstack/designate/bin/health-probe.py
- openstack/designate/templates/api-deployment.yaml
- openstack/designate/templates/bin-configmap.yaml
- openstack/designate/templates/central-deployment.yaml
- openstack/designate/templates/etc/_designate.conf.tpl
- openstack/designate/templates/mdns-deployment.yaml
- openstack/designate/templates/producer-deployment.yaml
- openstack/designate/templates/worker-deployment.yaml
* Add health-probe.py script
This script checks DB/RabbitMQ sockets and checks TCP connectivity
For services with RPC servers it uses oslo_rpc_server_ping call
to check, that service responds at all over messaging bug
> [designate] Health probe for Designate components

- openstack/designate/Chart.yaml
- openstack/designate/bin/health-probe.py
Unfortunately, neither RabbitMQ connection is established nor heartbeats are working before any request arrives to the wsgi apache process.
So for this check to work some of the following is required:
- Constant stream of incoming requests triggering the connection to Rabbit
- API should run as a native eventlet application (designate-api)
- API should run as uwsgi application with pthreads enabled for heartbeats
Neither of these options is good for us, so disabling this part of health probe for API service for now.
> [designate] Remove RabbitMQ connection check from API health-probe

- system/bind/templates/_helpers.tpl
- system/bind/templates/deployment.yaml
- system/bind/templates/etc/_secret_env.tpl
- system/bind/templates/secrets.yaml
It will convert the supplied secret_env structure into a name: value list consumable by envFrom.secretFrom, e.g.
```yaml
secret_env:
- name: foo
value: bar
- name: a
value: b
```
is converted to
```yaml
foo: bar
a: b
```
The values are passed thru the secrets injector and base64 encoded, too.
Also, the sshd container may also use sensitive env vars, i.e. make use of secret_env. Create the secret if that's the case.
> [bind] introducing the "setup_secret_env" helper

- system/gatekeeper/templates/constrainttemplate-prometheusrule-alert-labels.yaml
- system/gatekeeper/tests/gatekeeper-policies/suite.yaml
This is used by alerts which are only used for inhibition eg https://github.com/sapcc/helm-charts/blob/ecfe198278070e69e2b36d1d91d2d415916faa32/prometheus-rules/prometheus-kubernetes-rules/alerts/maintenance.alerts.tpl#L13
> gatekeeper: allow severity none

- prometheus-exporters/snmp-exporter/alerts/f5.alerts
Some of the F5 alerts were not firing, due to incorrect use of `$value` variable inside the `meta` field.
Thanks to @Kuckkuck for pointing that out!
> [alert][snmp-exporter] - remove value variable references from meta field

- openstack/openstack-seeder/templates/bin/_start.tpl
- openstack/openstack-seeder/values.yaml
This requires the patch from <https://github.com/sapcc/kubernetes-operators/pull/105> to be applied.
I chose to leave `ignoreNamespace` and `onlyNamespace` as stringly-typed for backwards compatibility with the existing regional values files. If desired, I can also change this to take array arguments, in which case slightly more care needs to merge and deploy this and the respective secrets PR at the same time.
I tested this with `helm diff upgrade` in eu-de-2 (both normal and global deployment) and saw the desired diff.
> openstack-seeder: allow ignoring or focusing on multiple namespaces

- common/memcached/CHANGELOG.md
- common/memcached/Chart.yaml
- common/memcached/templates/_helpers.tpl
- common/memcached/templates/alerts.yaml
- common/memcached/templates/alerts/_memcached.alerts.tpl
- common/memcached/templates/configmap.yaml
- common/memcached/templates/deployment.yaml
- common/memcached/templates/secrets.yaml
- common/memcached/templates/service.yaml
- common/memcached/values.yaml
- Memcached [1.6.31 Release Notes](https://github.com/memcached/memcached/wiki/ReleaseNotes1631)
- added alpine version tag to enforce exactly this version
- version info added to labels
- to allow gatekeeper rules based on them
- old (non-standard) labels removed
```yaml
labels:
app.kubernetes.io/name: memcached
app.kubernetes.io/instance: keystone-memcached
app.kubernetes.io/component: memcached-deployment-kvstore
app.kubernetes.io/part-of: keystone
app.kubernetes.io/version: 1.6.31
app.kubernetes.io/managed-by: "helm"
helm.sh/chart: memcached-0.6.0
```
```yaml
labels:
app: keystone-memcached
component: memcached
chart: "memcached-0.5.3"
release: "keystone"
heritage: "Helm"
type: configuration
application: keystone
```
> [memcached] version bumped to 1.6.31-alpine3.20

- common/memcached/values.yaml
- common/pxc-db/values.yaml
- common/rabbitmq/values.yaml
- common/rabbitmq_cluster/Chart.yaml
- common/rabbitmq_cluster/ci/test-values.yaml
- common/rabbitmq_cluster/templates/cluster.yaml
- common/rabbitmq_cluster/values.yaml
- global/percona_cluster/Chart.yaml
- global/percona_cluster/templates/statefulset.yaml
- system/descheduler/values.yaml
Migrate old PriorityClass to the equivalent one in the new scheme. openstack-service-critical will stay in the metal cluster for now.
> Change openstack-service-critical to critical-infrastructure PriorityClass

- common/pxc-db/Chart.yaml
- common/pxc-db/templates/_helpers.tpl
- common/pxc-db/templates/cluster.yaml
- common/pxc-db/templates/initdb-bin.yaml
- common/pxc-db/templates/initdb-job.yaml
- common/pxc-db/templates/initdb-secret.yaml
- common/pxc-db/values.yaml
owner-info injector doesn't handle them
> [pxc-db] Add ccloud labels to hook and backup resources

- openstack/utils/Chart.yaml
- openstack/utils/templates/_proxysql.tpl
Use ProxySQL 2.7.1 release as a default release if no override is set
> [utils][proxysql] Use ProxySQL 2.7.1 as a default version

- common/memcached/CHANGELOG.md
- common/memcached/Chart.yaml
- common/memcached/templates/_helpers.tpl
- common/memcached/templates/deployment.yaml
* `app` selector label returned back, because the deployment selector is immutable
> [memcached] return immutable deployment selector label

- common/rabbitmq/CHANGELOG.md
- common/rabbitmq/Chart.yaml
- common/rabbitmq/templates/_helpers.tpl
- common/rabbitmq/templates/deployment.yaml
- common/rabbitmq/templates/statefulset.yaml
* `app` selector label returned, because deployment selector is immutable
> [rabbitmq] return immutable deployment selector label

- common/mariadb/CHANGELOG.md
- common/mariadb/Chart.yaml
- common/mariadb/ci/test-values.yaml
- common/mariadb/templates/backup-v2-deployment.yaml
- common/mariadb/templates/deployment.yaml
* `app` selector label returned, because deployment selector is immutable
> [mariadb] return immutable deployment selector label

- common/pxc-db/Chart.yaml
- common/pxc-db/values.yaml
Set pxc_strict_mode to MASTER by default
This would allow:
* Sync database from MariaDB backup using go-maria-sync to allow close to zero downtime on migration
* Use database as a tooz coordination backend instead of shared coordination volume or memcached/redis, it requires GET_LOCK()
Excerpt from PXC documentation:
>MASTER: The same as ENFORCING except that the validation of [explicit table locking](https://docs.percona.com/percona-xtradb-cluster/8.0/strict-mode.html?h=strict#explicit-table-locking) is not performed. This mode can be used with clusters in which write operations are isolated to a single node.
> [pxc-db] Set pxc_strict_mode to MASTER by default

- openstack/utils/Chart.yaml
- openstack/utils/templates/snippets/_proxysql.cfg.tpl
Currently, default values are the following:
- transaction: 4h
- query: 24h
In very rare cases under high load caused by locust we've faced an issue when some sqlalchemy transactions acted as follows:
1 Began
2 Some blocking query was executed (they held a row lock)
3 No commit/rollback follows
4 Transaction continues to hang indefinitely in an idle state
5 All parallel requests modifying these rows were blocked because of (2)
This deadlock could be resolved by:
- killing this idle transaction on DB side manually
- killing application process
- killing transactions on the ProxySQL side
The proposed solution is to introduce query and transaction timeouts in the ProxySQL sidecar with the following values:
- transaction: 60s
- query: 90s
From the application perspective, after reaching these …
> [utils][proxysql] Set default transaction and query timeouts

- openstack/limes/templates/_utils.tpl
> limes: use standard naming pattern for queue name config

- openstack/castellum/alerts/openstack/errors.alerts
- openstack/keppel/alerts/openstack/api.alerts
- openstack/limes/alerts/openstack/api.alerts
- The go-bits/audittools changes have changed the metric names.
- I have been meaning to fix these stupid alert expressions for a long time.
> castellum/keppel/limes: rework audit logging failure alerts

- common/pxc-db/Chart.yaml
- common/pxc-db/templates/cluster.yaml
Use internal secret for mysql-exporter sidecar.
This is required by the updated upstream change for pods to be restarted after `monitor` user password update.
> [pxc-db] Use internal secret for mysql-exporter sidecar

- px/bird/templates/_deployment-bird.tpl
With the new looking glass image, we use a distroless image. Instead of
running and installing everything into system python as before, we need
to specify the python in the venv that we copied into the runtime
container at the build stage.
This wasn't uncovered in testing as we only ever tested that image in
the lg pod where we would rely on the ENTRYPOINT directive from the
dockerfile. As a sidecar, we start a different pyhton file though but
still called that from system python.
> [PX] Use correct python interpreter for lgproxy

- system/unbound/ci/test-values.yaml
- system/unbound/templates/service.yaml
The key has been renamed from externalIP to externalIPs. The new one is expecting a list as opposed to the literal value used by the old one.
> [unbound] switching from single service IP to multiple

- openstack/elektra/templates/deployment.yaml
This change should help prevent an Elektra pod from being restarted if we experience more than 10 concurrent requests that take longer than 5 seconds to process. By relaxing the readiness probe parameters, we allow for temporary spikes in response time without unnecessarily marking the pod as unready.
We can play also with the `timeoutSeconds` and `initialDelaySeconds`
related issue https://github.com/sapcc/elektra/issues/1466
> Elektra: more soft probes

- openstack/ironic/values.yaml
The prior settings were assuming that we rarely
change the certificates, so no need to run it often. But we also build up new hardware, and configure
it right away with redfish, so this job becomes
a dependency for the build-up.
Doing it twice a day reduces the time people
have to wait for it to work.
> [ironic] Run certrobot twice a day

- openstack/limes/ci/test-values.yaml
- openstack/limes/templates/_utils.tpl
- openstack/limes/templates/ingress-api.yaml
- openstack/limes/templates/ingress-liquids.yaml
- openstack/limes/templates/seed-catalog.yaml
The global clusters use non-standard domain naming schemes, so this commit switches to generating all domain names from the basic structure of the limes-api domain name. This is a no-op for existing deployments.
> limes: add support for deployments into the global clusters

- ci/config.yaml
Remove the `.`  in [ci/config.yaml](https://github.com/sapcc/helm-charts/blob/master/ci/config.yaml) since it's not detecting correctly the chart changes. 
Directly referring  to the top level directories does the trick and detects the chart changes correctly. Tested locally gives the correct results
> fix(gh-actions): fix chart-dirs in ct config to detect changes

- openstack/octavia/alerts/octavia.alerts
We want an alert that triggers immediately, but `changes` only triggered at the falling edge.
Use `max` instead and alert on any metric presence. If this doesn't work like I expect, I will change it again.
> [octavia] Fix OctaviaApiFailing alert: Only fires at falling edge

- openstack/designate/alerts/kubernetes/kube.alerts
- the old metric name is not available
> [designate] fix unbound missing endpoint alert

- openstack/ironic/Chart.yaml
- openstack/ironic/templates/pxe-service.yaml
Calico now uses a additional BGPFilter that will surpress service
subnets announcements (147.204.35.128/27, 130.214.232.16/28,
10.46.101.0/24). Only /32 host routes for Services will be
announced by nodes. Thus breaking TFTP/iPXE traffic. The traffic
would reach the cluster but not the service. We need to add the
`externalTrafficPolicy: local` to make this work.
Increasing the chart version to track this.
> ironic: change traffic policy for pxe-service

- openstack/utils/Chart.yaml
- openstack/utils/templates/_proxysql_secret.yaml.tpl
- openstack/utils/templates/snippets/_proxysql.cfg.tpl
* Enables monitor if DB is pxc
* Adds all cluster members to `mysql_servers` configuration
* Configures `mysql_galera_hostgroups`
* Remove `multiDestination` option: the same could be done with `force_enable`
> [utils][proxysql] Configure Galera monitor in ProxySQL sidecars

- common/thanos/Chart.yaml
- common/thanos/templates/thanos.yaml
- common/thanos/values.yaml
without this option, requests which are coming in from outside the cluster will have a malformed header in their reply.
> newer traefik requires h2c

- openstack/manila-nanny/Chart.lock
- openstack/manila-nanny/Chart.yaml
- openstack/manila-nanny/templates/secrets.yaml
- **[manila-nanny] bump deps**
- **[manila-nanny] add secrets injector support**
> [manila-nanny] add secrets injector support

- system/unbound/templates/service.yaml
- system/unbound/values.yaml
We can now expose the unbound ports (53/tcp, 53/udp) over multiple external ports.
That might came handy if the clients connecting to the unbounds are behind a load balancers and get NAT-ed. A lot of clients could cause the LB NAT tables to get exhausted.
Using multiple ports and/or multiple service IPs we can increase the service endpoints as required in order to accomodate those clients.
> [unbound] introducing multiple external ports

- prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/alerts/thanos-metal/netapp.yaml
The name for this filer (stnpca3-cp001) follows old name convention. We
use alternative name in manila-vendor.yaml than how it is configured in
netbox. Replace host label for it to avoid false alert.
> [netapp-harvest] exclude particular filer for alert

- .github/CODEOWNERS
- global/percona_cluster/Chart.yaml
- global/percona_cluster/templates/backupjob.yaml
- global/percona_cluster/templates/service-repl.yaml
- global/percona_cluster/templates/statefulset.yaml
Ports 4567 and 4568 aren't in default list of opaque ports in linkerd
> [percona_cluster] Add config.linkerd.io/opaque-ports annotations

- system/unbound/templates/config.yaml
- system/unbound/templates/deployment.yaml
- system/unbound/templates/service.yaml
The goal is to use 1-to-1 service port mappings as having multiple external ports mapping to the same backend port is not a supported feature. See:
https://github.com/kubernetes/kubernetes/issues/47222
Also, we use the interface unbound config clause as it can be specified multiple times as opposed to the port clause.
> [unbound] make unbound listen on multiple ports

- system/rook-crds/Chart.yaml
- system/rook-crds/crds/cephblockpoolradosnamespaces.ceph.rook.io.yaml
- system/rook-crds/crds/cephblockpools.ceph.rook.io.yaml
- system/rook-crds/crds/cephclusters.ceph.rook.io.yaml
- system/rook-crds/crds/cephfilesystems.ceph.rook.io.yaml
- system/rook-crds/crds/cephnfses.ceph.rook.io.yaml
- system/rook-crds/crds/cephobjectstores.ceph.rook.io.yaml
- system/rook-crds/crds/cephobjectstoreusers.ceph.rook.io.yaml
- system/rook-crds/crds/cephobjectzones.ceph.rook.io.yaml
> [ceph] update rook CRDs to v1.16

- openstack/designate/Chart.lock
- openstack/designate/Chart.yaml
* percona_cluster 1.1.8 -> 1.1.9: add linkerd opaque ports
* pxc-db 0.1.20 -> 0.1.22: update CRD to 1.15.1
> [designate] bump charts

- openstack/ironic/templates/etc/_ironic.conf.tpl
- openstack/ironic/values.yaml
The ironic-python-agent gets some config values over the lookup api as 'config' in the json.
And two values are unintuitively taken from the
conductor config section.
So, we have to set them in the api node as well,
in order to have the settings take hold in the agent.
> [ironic] Set agent relevant conductor parameters in api too

- system/cc-ceph/Chart.lock
- system/cc-ceph/Chart.yaml
- system/cc-ceph/templates/cephobjectstore-extra.yaml
- system/cc-ceph/templates/cephobjectstore-placement-pools.yaml
- system/cc-ceph/templates/certificate-extra.yaml
- system/cc-ceph/templates/record-extra.yaml
- system/cc-ceph/templates/service-extra.yaml
- system/cc-ceph/values.yaml
> [ceph] prepare upgrade to rook v1.16

- .github/CODEOWNERS
- system/percona-xtradb-cluster-operator/Chart.lock
- system/percona-xtradb-cluster-operator/Chart.yaml
- system/percona-xtradb-cluster-operator/templates/_helpers.tpl
- system/percona-xtradb-cluster-operator/values.yaml
* Add version override function to be able to set imageTag in values
* Use ccloud repository instead of mirror by default
* Bump chart version to 0.3.0
* Update CODEOWNERS
* Bump linkerd-support dependency
> [pxc-operator] Bump chart version and update CODEOWNERS

- common/pxc-db/Chart.yaml
- common/pxc-db/templates/cluster.yaml
- common/pxc-db/values.yaml
* Update operator image from 1.15.1 to 1.16.0
* Update pxc image from 8.0.36 to 8.0.39
* Use custom build image for cluster init containers
* Update default haproxy image from 2.8.5 to 2.8.11
* Use 1.16.0-pxc8.0-backup-pxb8.0.35 for backup and init jobs
* Set backup jobs activeDeadlineSeconds to 1 hour (default is infinite)
* Increase backoffLimit from 1 to 2
> [pxc-db] Update PXC CRD to v1.16.0 major release

- openstack/designate/Chart.lock
- openstack/designate/Chart.yaml
- openstack/designate/values.yaml
* Update pxc-db chart for designate
- PXC 8.0.36 to 8.0.39
- HAProxy 2.8.5 to 2.8.11
- Backup improvements and fixes
* Don't use mysql_native_password for designate user
- It's no longer needed with proxysql 2.7.1
> [designate] bump pxc-db chart

- common/pxc-db/Chart.yaml
- common/pxc-db/templates/alerts.yaml
- common/pxc-db/templates/alerts/_backup.alerts.tpl
- common/pxc-db/templates/alerts/_pxc.alerts.tpl
Add kube-state-metrics-based alerts:
* GaleraClusterResourceNotReady
* GaleraClusterBackupNotSucceeded
* GaleraClusterBackupMissing
> [pxc-db] Add kube-state-metrics-based alerts for PXC cluster

- common/pxc-db/Chart.yaml
- common/pxc-db/templates/alerts/_backup.alerts.tpl
Add binlog-collector alerts based on the last successful event timestamp
* GaleraClusterBinlogProcessingTooOld
* GaleraClusterBinlogUploadTooOld
> [pxc-db] Add binlog-collector alerts

- common/pxc-db/Chart.yaml
- common/pxc-db/templates/cluster.yaml
- common/pxc-db/values.yaml
* Make linkerd service annotation optional
* Enable pxc service exposure by default, because it's mandatory by openstack/utils
> [pxc-db] Move linkerd service annotations out of values

- common/pxc-db/Chart.yaml
- common/pxc-db/ci/test-values.yaml
- common/pxc-db/values.yaml
Use template for endpointUrl s3 backups storage configuration
This helps to avoid writing this common configuration for every service in each region
> [pxc-db] Use template for endpointUrl s3 backups storage configuration

- system/Makefile
- system/boot-operator-remote/Chart.yaml
- system/boot-operator-remote/templates/deployment.yaml
- system/boot-operator-remote/templates/remote-kubeconfig.yaml
- system/boot-operator-remote/values.yaml
- system/kustomize/boot-operator-remote/manager-remote-patch.yaml
- system/kustomize/boot-operator-remote/remote-kubeconfig.yaml
- system/kustomize/metal-operator-remote/manager-remote-patch.yaml
- system/kustomize/metal-operator-remote/remote-kubeconfig.yaml
- system/metal-operator-remote/Chart.yaml
- system/metal-operator-remote/managedresources/kustomize.yaml
- system/metal-operator-remote/templates/deployment.yaml
- system/metal-operator-remote/templates/remote-kubeconfig.yaml
- system/metal-operator-remote/values.yaml
This enables token rotation within client-go. See: client-go/transport/round_trippers.go
line 296.
> Mount ServiceAccount tokens of ironcore operators directly

- openstack/backup-replication/values.yaml
- openstack/content-repo/values.yaml
The changelog reads like there are no significant changes that are relevant to us. Mostly just library updates: https://github.com/prometheus/statsd_exporter/releases
> content-replication: bump statsd-exporter to 0.28.0

- common/memcached/CHANGELOG.md
- common/memcached/Chart.yaml
- common/memcached/values.yaml
- [changelog](https://github.com/memcached/memcached/wiki/ReleaseNotes1633)
> [memcached] version bumped to 1.6.33-alpine3.21

- openstack/ironic/Chart.lock
- openstack/ironic/Chart.yaml
mariadb:
- return immutable deployment selector label
- Update mysqld-exporter to 0.16.0
- version info added to labels
- Update MariaDB to the 10.5.27 version
- priorityClassName updated to new naming convention
-  fixes unnecessary quotes for sse_customer_key
memcached:
- [memcached] return immutable deployment selector label
- Change openstack-service-critical to critical-infrastructure PriorityClass
- memcached version bumped to 1.6.31-alpine3.20
- priorityClassName updated to new naming convention
mysql_metrics:
-Fix imageTag should be a string, not a number
- Update to the latest 0.5.8 ts build
rabiitmq:
- return immutable deployment selector label
- Change openstack-service-critical to critical-infrastructure PriorityClass
- rabbitmq version bumped to 3.13.7-management
- …
> [ironic] dependency updates

- openstack/limes/alerts/openstack/api.alerts
- openstack/limes/values.yaml
This will allow silencing this alert for specific services only, in case of known issues.
Also, wrap this alert and the overspent-quota alert in max() to avoid alert flapping because of pod restarts.
> limes: split OpenstackLimesMismatchProjectQuota alert by service type

- system/percona-xtradb-cluster-operator/Chart.yaml
- system/percona-xtradb-cluster-operator/values.yaml
Remove prometheus.io/port annotation from operator pods to avoid multiple scraping
We have multiple containers in pxc-operator pods and metrics port already named `metrics`, so this annotation is not needed
> [pxc-operator] Remove prometheus.io/port annotation from operator pods

- system/unbound/templates/deployment.yaml
- system/unbound/templates/service.yaml
This is making sure the scrape targets are not discovered twice.
We've also removed the "prometheus.io/port" annotation and relying on the metrics port definition.
This way the prometheus service discovery will be ending up with the metric container.
The monitors will have to be adjusted.
> [unbound] moved the prometheus annotations to the deployment

- openstack/designate/Chart.lock
- openstack/designate/Chart.yaml
* fixes mariadb service label selector
* updates mysql-metrics
* updates memcached and memcached-exporter
* update pxc-db alerts with links to playbooks
> [designate] bump chart dependencies

- common/prometheus-server-pre7/CHANGELOG.md
- common/prometheus-server-pre7/Chart.yaml
- common/prometheus-server-pre7/values.yaml
- common/prometheus-server/CHANGELOG.md
- common/prometheus-server/Chart.yaml
- common/prometheus-server/values.yaml
this is the bump prior to prometheus 3.x to ensure backwards tsdb compatibility
> bump thanos and prometheus version

- common/rabbitmq/CHANGELOG.md
- common/rabbitmq/Chart.yaml
- common/rabbitmq/ci/test-values.yaml
- common/rabbitmq/templates/certificate.yaml
- common/rabbitmq/templates/custom-conf-configmap.yaml
- common/rabbitmq/templates/deployment.yaml
- common/rabbitmq/templates/service.yaml
- common/rabbitmq/templates/statefulset.yaml
- common/rabbitmq/values.yaml
The option `enableSsl` configures a certificate with the same name as
the rabbitmq with the prefix `tls-`, which will in turn generate a
secret of the same name.
The only other missing value is the name of the cluster-issuer to
be specified with `certificate.issuerRef.name`
Erlang should automatically reload the certificate, when the file
changes. So, certificate rotation should also be handled.
> [rabbitmq] Option to enable SSL for amqp server

- system/cc-ceph/Chart.yaml
- system/cc-ceph/templates/certificate.yaml
split certificates using yaml `---` splitter
> ceph: fix rook cert loop delimiter

- system/cc-ceph/Chart.yaml
- system/cc-ceph/templates/certificate-extra.yaml
- system/cc-ceph/templates/certificate.yaml
- system/cc-ceph/templates/record-extra.yaml
- system/cc-ceph/templates/record.yaml
- system/cc-ceph/values.yaml
some `dnsNames` are needed to be registered on the RGW side, but they're managed separately.
> ceph: ability to skip DNS record and Cert creation for dnsNames

- openstack/ironic/Chart.lock
- openstack/ironic/Chart.yaml
* mariadb 0.15.2 to 0.15.3: fixes service selector
* memcached 0.6.1 to 0.6.3: updates memcached and memcached-exporter
* mysql-metrics: 0.4.1 to 0.4.2: updates sql-expoter to 2025-01-07
> [ironic] update chart dependencies

- common/pxc-db/Chart.yaml
- common/pxc-db/values.yaml
Lowers default value of the max_binlog_size option from 1G to 100M
This would help to avoid timeouts on binlog upload if binlog is big enough, so it couldn't be uploaded within the upload timeout
> [pxc-db] Set max_binlog_size option to 100M

- openstack/billing/templates/seeds.yaml
- openstack/billing/values.yaml
- openstack/limes/templates/_utils.tpl
- openstack/limes/templates/configmap.yaml
- openstack/limes/templates/prometheus-alerts.yaml
- openstack/limes/templates/seed-grants.yaml
- openstack/limes/values.yaml
I started touching this because billing is getting new technical users (coming from CAM instead of our own seeds; we only seed the role assignments). Then I was dissatisfied with the structure of everything.
Having the role assignments hardcoded in the billing seed makes some sense, but then this requires also maintaining the role-assignment alert on the Limes side. This commit moves all of this into the Limes chart, and changes it from hardcoded individual assignments to a configurable list. The templating in the seed is a bit of a mess, but the alert
definition and the seed do different forms of lookup, so one of them had to be a mess.
There is a related secrets PR that needs to be merged at the same time.
> limes: move all cloud_resource_* assignments from billing-seed to limes-seed

- openstack/limes/templates/seed-grants.yaml
Helm can deal with this just fine, and the seeder might be able to handle it, too, but `secrets-injector validate` chokes on `spec:` being absent (i.e. null).
> limes: do not render grants-seed if there are no grants to be made

- system/cc-cluster/Chart.yaml
- system/cc-cluster/templates/kubeadmconfigtemplate.yaml
Debian (and therefor Gardenlinux) defaults to `/usr/lib/cni` In order to stay with the upstream default, we need to specify that explicitly. For flatcar, the change should be a no-op.
For more details see:
https://github.com/containerd/containerd/issues/6600
> [cc-cluster] Set cni bin-dir explicitly

- openstack/ironic/templates/etc/_api_audit_map.yaml.tpl
This corrects the unmapped path for states/power in ironic audit events.
> [ironic] add states power to audit middleware mapping

- openstack/limes/templates/prometheus-alerts.yaml
Ref: https://convergedcloud.slack.com/archives/CE5NDBQDC/p1737365384373869
> limes: fix role-assignment alerts being confused about global vs. local

- common/pxc-db/Chart.yaml
- common/pxc-db/values.yaml
Pass binlog config values as strings to avoid scientific notation for numbers in the resulting generated config
> [pxc-db] Pass binlog config values as strings to avoid sci notation

- openstack/manila/values.yaml
this dependency is gone since
https://github.com/sapcc/helm-charts/commit/cf320ccba281405bde2109630c80c22509d5b177
> [manila] remove unused rabbitmq_notifications config

- common/pxc-db/Chart.yaml
- common/pxc-db/values.yaml
Increase net_read_timeout and net_write_timeout
Return change from PR #7290, that has been accidentally lost:
At least 180s timeout is required for binlog-collector processing of 1G
> [pxc-db] Increase net_read_timeout and net_write_timeout

- openstack/nova/console/common/token_lookup.lua
- openstack/nova/console/shellinabox/revproxy.lua
- openstack/nova/templates/console-shellinabox-deployment.yaml
Some functions were moved common/token_lookup.lua without the references for shellinabox.
The common part now also needs to trigger an update of the deployment of shellinabox deployments.
> [nova] Fix shellinabox console

- system/unbound/templates/prometheus-alerts.yaml
There are two unbound deployments - unbound1 and unbound2.
We could have a separate deployment just for the alerts or integrate the alerts into the actual unbound deployment. The latter is what we choose to do.
Also, replaced the DnsUnboundEndpointNotAvailable alert with DnsUnbound{1,2}UnexpectedNumberOfEndpoints.
The new alert will fire if the number of endpoints is not what we expect. We expect a specific number based on the number of ports exposed, the protocols and replicas.
For example, a deployment with two ports, two replicas using both TCP and UDP, should always result in 8 endpoints.
> [unbound] definde the prometheus alerts per unbound deployment

- prometheus-exporters/network-generic-ssh-exporter/templates/_config.yaml.tpl
Added new metric to see the bgp sessions in admin down state. This is need to exclude the bgp peers which are in shutdown state from the alerting.
> New metric# bgp_sessions_admin_down

- openstack/neutron/alerts/openstack/api.alerts
The alert channel is getting too many notifications for projects exceeding the neutron API limits. 
This PR changes the severity from `warning` to `info` only for alerts triggered by projects exceeding their quotas (local/per-project rate limits): 
1) no more per-project live notifications: `info` alerts do not get routed to the alerting system  
2) alerts are accessible and persisted on Thanos via GreenHouse
> [neutron] Change alert severity for API rate-limited projects

- openstack/vcenter-operator/Chart.lock
- openstack/vcenter-operator/Chart.yaml
- openstack/vcenter-operator/templates/secret.yaml
We need to support `secrets-injector` references coming from the values files. Since some values might be changed already while others may not, we bump the `utils` chart to the latest version and use its `resolve_secret` helper on every value that could be a secret. This takes care of including the proper syntax for the `secrets-injector` if the secret is a reference.
Since we haven't bumped the `utils` chart in quite some time, we will also get some other changes. Other than `resolve_secret`, we only use `helm-toolkit.snippets.kubernetes_metadata_labels` from the `utils` chart.
> [vcenter-operator] Support secrets-injector

- prometheus-exporters/network-generic-ssh-exporter/alerts/asr.alerts
neutron bgp peer down alerts updated to exclude the peerings that are in admin shut state
> Neutron_bgp_alerts

- system/cluster-api/Chart.lock
- system/cluster-api/Chart.yaml
Debian (and therefor gardenlinux) set the default bin dir to /usr/lib/cni/bin
> [cluster-api] cc-cluster update with setting cni_bin_dir explicitly

- common/rabbitmq/CHANGELOG.md
- common/rabbitmq/Chart.yaml
- common/rabbitmq/values.yaml
- major version upgrade from 3.13.x to 4.0.x to avoid having to do all these version steps later
- 3.13.x development has ended
- better AMQP performance
- RabbitMQ [4.0.5 Release Notes](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v4.0.5)
- [What's new?](https://www.rabbitmq.com/docs/whats-new)
- in [version 4.0.1](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v4.0.1) the default maximum message size reduced from `256` to `16MiB`
> [rabbitmq] version bumped to 4.0.5-management

- global/andromeda/templates/configmap-akamai.yaml
- global/andromeda/templates/deployment-akamai.yaml
- global/andromeda/templates/deployment-housekeeping.yaml
- global/andromeda/templates/deployment.yaml
- global/andromeda/templates/etc/_andromeda.yaml.tpl
- global/andromeda/templates/job-migration.yaml
- global/andromeda/templates/secret.yaml
- global/andromeda/templates/seed.yaml
- **[andromeda] switch to secrets-injector.**
- **Provide database connection string as environment variable.**
- **Added missing `DATABASE_CONNECTION` env var to housekeeping.**
- **Added missing `DATABASE_CONNECTION` env var to migration runner.**
- **Created `data.edgerc` secret key, mounted at `/etc/andromeda/edgerc.conf`...**
> andromeda secrets injector fix

- system/greenhouse-ccloud/Chart.yaml
- system/greenhouse-ccloud/templates/kube-monitoring-pluginpreset.yaml
This is the last version before Prometheus v3.
> greenhouse-ccloud: pin kube-monitoring prometheus version to v2.55.1

- openstack/utils/Chart.yaml
- openstack/utils/templates/_hosts.tpl
Required by #7779 (New Andromeda Liquid Server ingress/service/pod)
> [utils] New host entry for Andromeda Liquid Server API

- system/opensearch-logs/templates/config/_ds-ism.json.tpl
Small fix for an invalid condition in the ISM policy by replacing max_docs with min_doc_count
> fix(opensearch): replace max_docs with min_doc_count in transitions

- openstack/designate/Chart.lock
- openstack/designate/Chart.yaml
Bump Designate pxc and rabbitmq dependencies:
* pxc-db: 0.2.10 -> 0.2.13 (binlog size and timeouts fix)
* rabbitmq: 0.12.1 -> 0.14.0 (updates rabbitmq to 4.0.5)
> [designate] bump pxc and rabbitmq dependencies

- prometheus-rules/prometheus-kubernetes-rules/Chart.yaml
- prometheus-rules/prometheus-kubernetes-rules/alerts/health.alerts.tpl
This is intended to replace the last remaining alerts based on event-exporter metrics:
- PodSchedulingInsufficientCPU
- PodSchedulingInsufficientMemory
As defined in `prometheus-exporters/event-exporter/alerts/scheduling.alerts`
> prometheus-kubernetes-rules: add PodNotSchedulable alert

- system/kube-monitoring-admin-k3s/Chart.lock
- system/kube-monitoring-admin-k3s/Chart.yaml
- system/kube-monitoring-kubernikus/Chart.lock
- system/kube-monitoring-kubernikus/Chart.yaml
- system/kube-monitoring-metal/Chart.lock
- system/kube-monitoring-metal/Chart.yaml
- system/kube-monitoring-scaleout/Chart.lock
- system/kube-monitoring-scaleout/Chart.yaml
- system/kube-monitoring-virtual/Chart.lock
- system/kube-monitoring-virtual/Chart.yaml
As of prometheus-kubernetes-rules 1.10.1, all our usecases for event-exporter metrics are covered by kube-state-metrics instead.
I also saw that the owner-info dep was outdated, so I bumped that too.
> kube-monitoring-*: remove event-exporter

- openstack/billing/templates/prometheus-alerts.yaml
- openstack/billing/templates/seeds.yaml
- openstack/limes/templates/seed.yaml
This is a necessary prerequisite for adding support for these roles in the CBR masterdata API.
> billing: define cloud_masterdata_{admin,viewer} roles

- openstack/octavia/values.yaml
default values on, and with the default queue size to remove the specified lower queue size in secrets. 
Connected with this PR 
https://github.wdf.sap.corp/cc/secrets/pull/16126
> default audit to true, with default mem_queue_size

- openstack/ironic/alerts/openstack-ironic.alerts
This log now shows up in liquid-ironic instead of limes-collect-ccloud
> ironic: fix Kibana link for OpenstackIronicUnmatchedNodes alert

- openstack/manila/Chart.lock
- openstack/manila/Chart.yaml
- openstack/manila/alerts/openstack/manila.alerts
- openstack/manila/alerts/openstack/mariadb.alerts
* mariadb:
* bumped to 10.5.27
* labels updated -> hence updated the alert and moved to own group
* memcached:
* bumped to 1.6.34-alpine3.21 (Release Notes https://github.com/memcached/memcached/wiki/ReleaseNotes1634)
* exporter bumped to v0.15.0 (Release Notes https://github.com/prometheus/memcached_exporter/releases/tag/v0.15.0)
* mysql_metrics:
* bumped sql-exporter version to 0.5.9 (2025-01-07)
* rabbitmq:
* bump to 3.13.7 (Release Notes https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.13.7)
* Add options to enable ssl in rabbitmq
* redis:
* bump redis-exporter to 1.67.0
* switch to valkey
* utils:
* proxysql: Set default transaction and query timeouts
> [manila] bump dependencies

- openstack/billing/templates/prometheus-alerts.yaml
- openstack/billing/templates/seeds.yaml
Output seems to be syntactically correct (qa-de-1 diff):
```
...
annotations:
description: The Keystone role "cloud_masterdata_viewer" is assigned to more
users/groups than expected.
summary: Unexpected role assignments
expr: max(openstack_assignments_per_role{role_name="cloud_masterdata_viewer",namespace="monsoon3"})
-         > 2
+         > 3
labels:
meta: Unexpected role assignments found for Keystone role "cloud_masterdata_viewer"
playbook: docs/support/playbook/unexpected-role-assignments
service: limes
severity: info
...
billing, billing-seed, OpenstackSeed (openstack.stable.sap.cc) has changed:
...
name: billing-seed
spec:
domains:
- name: Default
users:
-     - description: Billing Service
-       name: billing
-       password: …
```
> [limes] remove old billing user, add global role for qa (srs #540)

- system/greenhouse-ccloud/Chart.yaml
- system/greenhouse-ccloud/ci/test-values.yaml
- system/greenhouse-ccloud/templates/kubeconfig-generator-plugin.yaml
In our greenhouse-qa environment we do not want to have all cluster uploaded to the registry this allows to allowlist the clusters
> feat(gh-ccloud): configurable clusters for config generator

- openstack/backup-replication/templates/cronjob.yaml
As explained in the comment, if there are multiple large files to transfer and the link is slow, we might get stuck in a loop if the replace kills the process before it can fully transfer any files.
> backup-replication: change concurrency policy

- openstack/ironic/Chart.lock
- openstack/ironic/Chart.yaml
- openstack/ironic/ci/test-values.yaml
- openstack/ironic/templates/_helpers.tpl
- openstack/ironic/templates/api-deployment.yaml
- openstack/ironic/templates/db-migration-job.yaml
- openstack/ironic/templates/etc/_inspector_secrets.conf.tpl
- openstack/ironic/templates/etc/_secrets.conf.tpl
- openstack/ironic/templates/inspector-db-migration-job.yaml
- openstack/ironic/values.yaml
Add default values for pxc-db chart dependency
Add an explicit dbType option to be able to force the usage of service DB.
Without setting pxc_db.enabled=true this PR causes no change in deployment
> [ironic][[pxc-db] Add support for PXC galera cluster: part 1

- .github/CODEOWNERS
- manila and netapp exporter: add some DevOps colleagues from Storage Operations
- remove Thomas Graichen
There are more errors, but I can't/don't want to judge those
> [CODEOWNERS] update 

- common/postgresql-ng/Chart.yaml
- common/postgresql-ng/values.yaml
Trivy found a libtasn1 vuln in the old image.
> common/postgresql: bump image

- openstack/barbican/Chart.yaml
- openstack/barbican/templates/etc/_secrets.conf.tpl
Openstack Ref : https://docs.openstack.org/barbican/latest/install/barbican-backend.html#thales-luna-network-hsm
Thales Ref : https://www.thalesdocs.com/gphsm/integrations/guides/openstack_barbican/index.html#configure-openstack-barbican-with-thales-luna-hsm-or-luna-cloud-hsm
> [Barbican] adapt barbican.conf for hsm firmware upgrade to 7.7.1 version

- openstack/manila/templates/shares/_share-netapp.conf.tpl
allow to control aggregate selection for flexgroups.
This also means the aggr-list-multiplier will default to 4
(the default of that setting, currently not changeable)
instead of something else that would be automatically set by ONTAP.
Leading to 4 times number of aggregates constituents
(i.e. often 8 in our case).
> [manila] add netapp_flexgroup_pools option

- openstack/utils/Chart.yaml
- openstack/utils/templates/_ini_sections.tpl
Add missing default value for mem_queue_size audit option.
In general, values in utils templates should be either `required` or they should have a `default` value set to avoid misconfiguration errors.
> [utils] Add missing default value for mem_queue_size audit option

- system/gatekeeper/templates/constrainttemplate-pod-security.yaml
This reverts commit c256c1a64f8a0820b5c04785b34b56c8e511e8d9.
Instead of #7891
> Revert "GkPodSecurity: restrict otel exception to the relevant clusters"

- prometheus-exporters/ns-exporter/alerts/probe.alerts
Add a a filter to NetworkNamespaceProbesFailed alert to exclude recently created routers and networks. These objects were previously filtered by the ns-exporter binary itself. Moving this filter to the alert provides more flexibility, e.g., to add monitoring to recently created routers.
> [ns-exporter] feat: add filter by age to alerts

- openstack/elektra/bin/init-generate-secrets.sh
- openstack/elektra/bin/init-generate-token-secret.sh
- openstack/elektra/templates/deployment.yaml
- openstack/elektra/templates/rbac.yaml
- openstack/elektra/values.yaml
Automated process to generate and manage a Rails token as a Kubernetes secret.
- A Kubernetes **Secret** resource is created by a script run by an **initContainer**, but only if it does not already exist. The secret will persist and will not be recreated by any deployment as long as it exists. This prevents generating a new token on each deployment and avoids consuming a Vault secret that requires rotation.  
- The script first checks if the secret exists. If it does, the process exits. If the secret is missing, the script attempts to copy the key from an existing secret containing the Vault value. If the Vault value is not found, it generates a random 128-character string.  
- A **ServiceAccount**, along with the necessary **roles** and **role bindings**, has been created to allow the …
> feat[elektra]: autogenerate rails token

- common/memcached/CHANGELOG.md
- common/memcached/Chart.yaml
- common/memcached/values.yaml
- because of a critical bugfix
- bumped memcached version
> [memcached] version bumped to 1.6.36-alpine3.21

- common/mariadb/CHANGELOG.md
- common/mariadb/Chart.yaml
- common/mariadb/values.yaml
- several fixes for INNODB and other components
- memory leaks have been fixed
- CVE-2025-21490 has been fixed
> [mariadb] version updated to 10.5.28

- common/rabbitmq/CHANGELOG.md
- common/rabbitmq/Chart.yaml
- common/rabbitmq/values.yaml
- RabbitMQ [4.0.6 Release Notes](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v4.0.6)
- several bugs have been fixed and improvements have been made in the server and Prometheus plugin
> [rabbitmq] version bumped to 4.0.6-management

- prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/aggregations/maia.yaml
..., to include the snapmirror relationships with local source endpoints
> [netapp-harvest-exporter] extend maia metrics netapp_snapmirror_labels:maia

- prometheus-exporters/ns-exporter/alerts/probe.alerts
Update the value of the "for" clause for alert "NetworkNamespaceProbesFailed": 5 min.
> [ns-exporter] fix: update clause "for" value

- openstack/cinder/values.yaml
This patch updates the helm chart for cinder to
enable api rate limiting on by default for all
regions.
> [Cinder] Enable API rate limit

- common/mariadb/CHANGELOG.md
- common/mariadb/Chart.yaml
- common/mariadb/templates/backup-v2-deployment.yaml
- common/mariadb/templates/backup-v2-secret.yaml
- common/mariadb/templates/secret.yaml
`mariadb-servicename` deployment is annotated to be restarted after `mariadb-servicename` secret change, but oauth credentials are only being used in `mariadb-backup`, so these oauth secrets should be moved to separate secret.
> [mariadb] move backup-v2 oauth secret to a separate secret

- system/cc-ceph/Chart.yaml
- system/cc-ceph/templates/cephobjectstore-extra.yaml
- system/cc-ceph/templates/cephobjectstore.yaml
- system/cc-ceph/values.yaml
supprt helm templates for rgw instace config overrides.
See: https://rook.io/docs/rook/v1.16/CRDs/Object-Storage/ceph-object-store-crd/?h=rgwcon#advanced-configuration
```yaml
spec:
gateway:
rgwConfig:
debug_rgw: "10" # int
rgw_s3_auth_use_ldap: "true" # bool
rgwCommandFlags:
rgw_dmclock_auth_res: "100.0" # float
rgw_d4n_l1_datacache_persistent_path: /var/log/rook/rgwd4ncache # string
rgw_d4n_address: "127.0.0.1:6379" # IP string
```
> add rgw custom config to ceph chart

- openstack/neutron/templates/rbac-ovn-db-raft.yaml
This adds the following kinds used by ovn:
* ClusterRole
* ClusterRoleBinding
* Role
* RoleBinding
* ServiceAccount
> [neutron] add rbac related parts for ovn

- global/prometheus-alertmanager-operated/Chart.yaml
- global/prometheus-alertmanager-operated/templates/am-config-route-slack.yaml
`msg="skipping alertmanagerconfig" error="route[35]: json: cannot unmarshal bool into Go struct field Matcher.matchers.value of type string"`
> alertmanager: fix bedrock slack route

- openstack/manila/templates/shares/_share-netapp.conf.tpl
- openstack/manila/templates/type-seeds.yaml
- openstack/manila/values.yaml
for standard and hypervisor_storage types.
We need to make a map out of the bool kind 'share_types',
but also want to keep backwards compatible to not necessarily have
to coordinate the value changes at the same time.
> [manila] allow share type extra specs overrides

- openstack/nova/templates/bump-compute-service-version-xena.yaml
The key `db_password_cell2` was indented wrongly.
> [Nova] Fix bump-compute-service-version Secret

- openstack/nova/templates/bump-compute-service-version-xena.yaml
The job definition had a bug, where we would add an additional `}` to the password.
> [Nova] Fix nova-bump-service-version Job for cell2

- openstack/billing/templates/seeds.yaml
I missed this line on the initial PR.
`helm diff`:
```
billing, billing-seed, OpenstackSeed (openstack.stable.sap.cc) has changed:
name: ccadmin
projects:
- description: Billing Administration for Converged Cloud
name: billing
role_assignments:
-       - role: objectstore_admin
-         user: billing@Default
+       - group: CCADMIN_BILLING_ADMIN
+         role: admin
swift:
enabled: true
- name: cloud_admin
role_assignments:
- role: cloud_identity_viewer
```
> [limes] use new group for default access of billing@ccadmin (srs #540)

- openstack/neutron/templates/configmap-ovn-db-raft.yaml
- openstack/neutron/templates/deployment-ovn-northd.yaml
- openstack/neutron/templates/etc/_ml2-conf.ini.tpl
- openstack/neutron/templates/pdb-ovn-db-raft.yaml
- openstack/neutron/templates/rbac-ovn-db-raft.yaml
- openstack/neutron/templates/service-ovn-db.yaml
- openstack/neutron/templates/statefulset-ovn-db-raft.yaml
- openstack/neutron/values.yaml
The template is for OVN as a CNI, so had tolerations for any taints, which is not what we need or want. We want to run the services only on ready nodes.
Also remove a reference to a non-existing pull-secret.
> [neutron] Fixup ovn

- system/cc-ceph/Chart.yaml
- system/cc-ceph/templates/ceph-config-override.yaml
- system/cc-ceph/values.yaml
set empty the default `keystone.auth_order` value
> [ceph] move auth order to rgwCommandFlags

- openstack/cinder/Chart.lock
- openstack/cinder/Chart.yaml
This patch updates various chart dependencies to their latest version.  It's been a while since cinder deps have been updated.
Update:
utils 0.18.4 -> 0.22.1
mariadb 0.14.2 -> 0.15.5
mysql_metrics 0.3.5 -> 0.4.2
memcached 0.5.3 -> 0.6.4
rabbitmq 0.11.1 -> 0.14.1
redis 1.5.2 -> 1.6.2
> [Cinder] Update chart deps

- openstack/manila/Chart.yaml
- openstack/manila/values.yaml
Increase proxysql sidecar transaction timeout from 60s to 120s until services query performance is fixed or improved.
> [manila][proxysql] double proxysql transaction timeout

- openstack/placement/Chart.yaml
- openstack/placement/templates/etc/_policy.yaml.tpl
The only change we need to do is in the policy, which has switched the rules they use for validation. Since we only ever changed the generic rules that define an admin, we remove the defaults - they don't match between yoga and dalmatian and can be easily generated with `tox -e genpolicy` in Placements repo.
We set both the old (yoga) and the new (dalmatian) generic rules that define an admin to support smooth upgrading.
We also bump the `appVersion` of the chart to "dalmatian", because that's the newest we support.
> [Placement] Support dalmatian release

- common/mariadb/CHANGELOG.md
- common/mariadb/Chart.yaml
- common/mariadb/templates/_helpers.tpl
- common/mariadb/templates/client-secret.yaml
- common/mariadb/templates/config/_client.cnf.tpl
- common/mariadb/templates/deployment.yaml
With the credentials for the root user present in /root/.my.cnf we do not need to give them as parameters for the probes, avoiding problems with shell escaping and showing passwords in the processlist of the k8s nodes.
> [mariadb] remove user and password from readyness and lifeness probes

- openstack/neutron/templates/etc/_ml2-conf.ini.tpl
OVS only can resolve DNS names, when the optional unbound
package is installed, as it wants to do its own DNS resolution
for some reason.
> [neutron] Use IP instead of DNS for OVN DB connection

- openstack/ironic/templates/etc/_ironic.conf.tpl
- openstack/ironic/templates/etc/_secrets.conf.tpl
The transport_url from rabbitmq includes secrets. Having this in the
config is wrong and breaks with the switch to the secrets-injector. Thus
we move this to the secrets. Doing so is the recommended way by the
shared-services.
> [ironic] move rabbitmq url to secrets

- common/postgresql-ng/Chart.yaml
- common/postgresql-ng/templates/deployment.yaml
- common/redis/Chart.yaml
- common/redis/bin/init-generate-secrets.sh
- common/redis/templates/_helpers.tpl
- common/redis/templates/configmap.yaml
- common/redis/templates/deployment.yaml
- common/redis/templates/metrics-deployment.yaml
- common/redis/templates/pvc.yaml
- common/redis/templates/rbac.yaml
- common/redis/templates/secrets.yaml
- common/redis/templates/svc.yaml
- common/redis/values.yaml
Most of the changes are as described in the `Chart.yaml` diff.
Removing the label clutter from the metrics deployment podspec cannot be done as an in-place edit (in Deployment objects, `.spec.selector.matchLabels` is immutable for good reason), so this renames the deployment from "redis-metrics" to "redis-exporter" to allow the cleanup to proceed.
The password autogeneration capability is mostly copied from the respective capability in the `common/postgresql-ng` chart. The name pattern is slightly different in case users want to deploy multiple separate Redis instances (i.e., multiple instances of this chart) inside a single application chart.
> common/redis: cleanup clutter, add password autogeneration on first startup

- system/cc-ceph/Chart.yaml
- system/cc-ceph/templates/rgw-exporter-deployment.yaml
otherwise the service account is being kept from the previous deployment
> [ceph] remove rgw exporter service account

- openstack/ironic/py/ironic-node-update.py
The idrac-redfish-kvm console is much more powerful than the serial
console but sadly it's also not properly working. We get logging issue
all the time so we switch back to the serial-console for dell nodes
which seems to work much better.
> [ironic] switch to serial console for dell nodes

- openstack/billing/ci/test-values.yaml
- openstack/billing/templates/seeds.yaml
- openstack/limes/ci/test-values.yaml
- openstack/limes/templates/seed.yaml
- openstack/limes/templates/support_seed.yaml
I checked the diff and if you redact the ordering changes between the lists, the two diffs come out like this:
[limesdiff.txt](https://github.com/user-attachments/files/18863172/limesdiff.txt)
[billingdiff.txt](https://github.com/user-attachments/files/18863173/billingdiff.txt)
executive summary:
* there are only role additions, if I looked correctly nothing is missing afterwards
* billing: add roles `[DOMAIN]_API_SUPPORT`, `[DOMAIN]_COMPUTE_SUPPORT`, `[DOMAIN]_NETWORK_SUPPORT`, `[DOMAIN]_STORAGE_SUPPORT`, `[DOMAIN]_SERVICE_DESK` for `btp_fp, hcm, hcp03, kyma, iaas-... (bedrock)` domains
* limes: 
* add roles `[DOMAIN]_DOMAIN_RESOURCE_ADMINS` for `ora, iaas-... (bedrock)` domains
* add roles `[DOMAIN]_API_SUPPORT`,  `[DOMAIN]_COMPUTE_SUPPORT`, `[DOMAIN]_NETWORK_SUPPORT`, …
> [limes+billing] use global.domain_seeds.customer_domains (srs #485)

- openstack/limes/alerts/openstack/api.alerts
We got a false positive here for a resource that only existed in limes-global, because the left side of the != operator looked at limes-global and the right side looked at regular limes.
> limes: fix misfiring OpenstackLimesIncompleteProjectResourceData alert

- system/logs/templates/opentelemetry-logs-collector.yaml
In-case of OpenSearch (logs sink) is experiencing any kind of downtimes we sometimes get errors such as:
```
error    internal/base_exporter.go:139    Exporting failed. Rejecting data.    {"kind": "exporter", "data_type": "logs", "name": "opensearch/failover_a"....
```
The [failover connector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/failoverconnector) will retry this with a backoff of `retry_interval` and `retry_gap`. This PR reduces both of these parameters in favour of having quicker retry attempts, both when backing off (test-sleep-test) and attempting secondary failover credentials (a-sleep-b).
> fix(logs): changes failover retry

- openstack/billing/templates/seeds.yaml
- openstack/limes/templates/support_seed.yaml
```
0219 14:05:30.933068      11 controller.go:437] ERROR: dependency 'monsoon3/domain-btp_fp-seed' of 'billing/billing-seed' not found
```
> [limes+billing] fix domain_seeds.customer_domains requires (srs #547)

- common/mariadb/CHANGELOG.md
- common/mariadb/Chart.yaml
- common/mariadb/templates/configmap-mariadb-maintenance.yaml
- common/mariadb/templates/cronjob-mariadb-maintenance.yaml
* fix names of the maintenance cronjob resources
* make names unique
> [mariadb] fix maintenance cronjob resource names

- system/unbound/templates/prometheus-alerts.yaml
The previous expression was using the avg() aggregation which was not handling downtimes, pod restarts very well.
Switched to sum() now.
Also, falling back to 0 if there's a gap in the data.
> [unbound] make the DnsUnbound{1,2}LowTraffic alert more robust

- openstack/keystone/Chart.yaml
- openstack/keystone/ci/test-values.yaml
- openstack/keystone/templates/_helpers.tpl
- openstack/keystone/templates/etc/_secrets.conf.tpl
remove unused rabbitmq from templates, because it was removed in PR #3859
> [keystone][rabbitmq] remove unused rabbitmq from templates

- openstack/billing/templates/seeds.yaml
- openstack/keppel/templates/support_seed.yaml
- openstack/limes/templates/support_seed.yaml
And next round of errors hopefully gone:
* ora missing projects
* kyma missing projects
* old non-existing billing technical user
```
20.02.2025 12:53:14 ERROR:root:project ora/storage_support not found
20.02.2025 12:53:14 WARNING:root:project storage_support@ora not found, skipping role assignment..
20.02.2025 12:53:15 ERROR:root:project ora/service_desk not found
20.02.2025 12:53:15 WARNING:root:project service_desk@ora not found, skipping role assignment..
20.02.2025 16:01:54 ERROR:root:user cc3test/TEST_D060501_02 not found
20.02.2025 16:01:54 WARNING:root:user TEST_D060501_02@cc3test not found, skipping role assignment..
20.02.2025 16:01:54 ERROR:root:user cc3test/TEST_D060501_01 not found
20.02.2025 16:01:55 WARNING:root:user TEST_D060501_01@cc3test not found, skipping role …
```
> [limes+billing+keppel] remove role seeds for kyma + ora (srs #485)

- common/mariadb/CHANGELOG.md
- common/mariadb/Chart.yaml
- common/mariadb/templates/alerts/_backup-v2.alerts.tpl
Fix backup-v2 maria_backup_status alerts.
There never were `release` labels on a backup-v2 deployment.
`app_kubernetes_io_instance` should be used, same as for mysqld-exporter alerts.
> [mariadb] Fix maria_backup_status alerts

- common/mariadb/CHANGELOG.md
- common/mariadb/Chart.yaml
- common/mariadb/templates/etc-configmap.yaml
Add "lost+found" directory to the ignored list to avoid it being displayed as a database.
> [mariadb] set default ignore_db_dirs value

- openstack/keystone/Chart.lock
- openstack/keystone/Chart.yaml
- openstack/keystone/values.yaml
- to be able to use the new maintenance job feature
- job options added to values.yaml (disabled by default)
> [keystone] MariaDB chart version bumped to 0.16.3

- openstack/octavia/templates/etc/_octavia.conf.tpl
The option was wrongly named, see [1]
This change does not have any effect, because .Values.worker is not defined (don't confuse it with .Values.workers!) and so this defaults to 1, which is also the default value defined by Octavia[1]. So it doesn't change, it's just explicitly defined now.
[1] https://github.com/sapcc/octavia/blob/600b5bae7537bc2fcf36c597818bfc4b7d48de10/octavia/common/config.py#L458-L460
> [Octavia] octavia.conf: Fix typo

- prometheus-rules/prometheus-vmware-rules/Chart.yaml
- prometheus-rules/prometheus-vmware-rules/alerts/host.alerts
- prometheus-rules/prometheus-vmware-rules/templates/_helper.tpl
- prometheus-rules/prometheus-vmware-rules/templates/prometheus-alerts.yaml
- Updated regex in `prometheus-alerts.yaml` to match expresssions like `expr: mymetric1 > mymetric2` correctly in past the regex produced wrong output.
_Example_
```bash
expr: |   
> mymetric2...
```
- Updated `_helper.tpl` replace `expr: >` to `expr: |` for bedrock alertings
> Fixed bedrock alerting template

- global/concourse-main/alerts/concourse.alerts
- prometheus-exporters/opensearch-logs-query-exporter/aggregations/snmp.rules
- prometheus-exporters/opensearch-logs-query-exporter/alerts/concourse.alerts
- prometheus-exporters/opensearch-logs-query-exporter/alerts/opensearch-logs-query.alerts
- prometheus-exporters/opensearch-logs-query-exporter/files/defaults.cfg
- prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_database.cfg
- prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_dbconnection_error.cfg
- prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_dboperational_error.cfg
- prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_esxi_exporter_login_error.cfg
- prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_jump.cfg
- prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_jump_ldap_error.cfg
- prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_kubernikus.cfg
- prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_kubernikus_csi_error.cfg
- prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_kubernikus_expired_client.cfg
- prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_logsds_derby_error.cfg
- prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_logstash_derby_error.cfg
- prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_manila.cfg
- prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_memcached_toozconnection_error.cfg
- prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_octobus_exporter_error.cfg
- prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_opensearch.cfg
- prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_openstack_glance.cfg
- prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_px_bird.cfg
- prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_rabbitmq_econnrefused_error.cfg
- prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_rabbitmq_timeout_error.cfg
- prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_rabbitmq_vhost_connect_error.cfg
- prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_scaleout.cfg
- prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_scaleout_csi_error.cfg
- prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_siem_error.cfg
- prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_snmp.cfg
- prometheus-exporters/opensearch-logs-query-exporter/files/opensearch_logs_syslog.cfg
- refactor(opensearch-logs-query-exporter): migrates from ES labels to OS
This changes the ES labels, keywords etc. to canonical OpenSearch ones. For some situations there are not log hits due to OtelCol not ingesting them yet.
- refactor(opensearch-logs-query-exporter): adds a partial migration for 'query_opensearch'
A partial fix as 'fault_detection.keyword' and 'opensearch_name.keyword' are labels that have not been seen/indexed by logs-ds at this moment. So this might be revised in the future
- refactor(opensearch-logs-query-exporter): renames 'query_elasticsearch_' to 'query_opensearch_' for all queries
> [prometheus-exporters] Migrate queries from logstash->OpenTelemetry / ElasticSearch->OpenSearch

- common/postgresql-ng/Chart.yaml
- common/postgresql-ng/ci/test-values.yaml
- common/postgresql-ng/templates/prometheus-alerts.yaml
- common/postgresql-ng/values.yaml
- common/redis/Chart.yaml
- common/redis/ci/test-values.yaml
- common/redis/templates/prometheus-alerts.yaml
- common/redis/values.yaml
To ensure PCI/DSS compliance for those credentials.
> postgresql-ng, redis: add alerts when auto-issued secrets expire

- prometheus-exporters/ns-exporter/alerts/probe.alerts
As we're now alerting after 5 minutes for problematic networks our alert message should also say 5 minutes.
> [ns-exporter] Fix time in ns-prober alert message

- openstack/castellum/Chart.lock
- openstack/keppel/Chart.lock
- openstack/keppel/values.yaml
- openstack/limes/Chart.lock
This is not automated because Keppel needs a values.yaml change.
> all srs: bump postgresql-ng and redis charts

- common/mariadb/CHANGELOG.md
- common/mariadb/Chart.yaml
- common/mariadb/values.yaml
* update `pod-readiness` container image to 2025-02-25 to fix violations
> [mariadb] update pod-readiness container image

- openstack/keystone/Chart.lock
- openstack/keystone/Chart.yaml
- configmap name for the maintenance job fixed
> [keystone] MariaDB chart version bumped to 0.16.8

- openstack/limes-campfire/templates/deployment.yaml
I have read through the `helm diff` for global-qa and this appears to be the only remaining bug.
> limes-campfire: fix CRONUS_USERNAME

- openstack/swift-utils/ci/test-values.yaml
- openstack/swift-utils/templates/seed.yaml
- openstack/swift/ci/test-values.yaml
- openstack/swift/templates/support_seed.yaml
partly a replacement to shorten the seed, partly extending to the new domains (`iaas-...`) as with billing/ limes/ keppel.
`h3 diff`: [swiftdiff.txt](https://github.com/user-attachments/files/18966113/swiftdiff.txt)
> [swift] use global.domain_seeds.customer_domains (srs #547)

- openstack/limes/templates/configmap.yaml
- Lab regions do not have a Campfire because there is no CBR.
- Global regions are disabled temporarily until we figure out the credential situation for Campfire.
> limes: disable mail notifications in lab regions and global regions

- system/cc-cluster/Chart.yaml
- system/cc-cluster/templates/kubeadmconfigtemplate.yaml
This allows to add extra labels to clusters. This would allow dedicated
labels to be added e.g. for metal3 clusters.
The values syntax needs to be an array like following:
```
extraLabels:
- key=value
- asdf=qwer
```
> [system/cc-cluster] Allow extra node-labels for clusters

- prometheus-exporters/opensearch-logs-query-exporter/Chart.yaml
- prometheus-exporters/opensearch-logs-query-exporter/templates/deployment.yaml
- prometheus-exporters/opensearch-logs-query-exporter/templates/secrets.yaml
- prometheus-exporters/opensearch-logs-query-exporter/values.yaml
Add two more `env` for failover credentials used in https://github.com/sapcc/prometheus-es-exporter/pull/2
> feat(opensearch-logs-query-exporter): add secondary auth fallback mechanism

- common/mariadb/CHANGELOG.md
- common/mariadb/Chart.yaml
- common/mariadb/scripts/mariadb-cronjob-maintenance.sh
- common/mariadb/values.yaml
- if enabled the reponse from MariaDB will be added to the logs like here
```
{"@timestamp":"2025-02-27T11:58:00+UTC","ecs.version":"1.6.0","log.logger":"/usr/bin/mariadb-cronjob-maintenance.sh","log.origin.function":"analyzeTable","log.level":"info","message":"analyze table `keystone`.`project`"}
Table	Op	Msg_type	Msg_text
keystone.project	analyze	status	Engine-independent statistics collected
keystone.project	analyze	status	OK
{"@timestamp":"2025-02-27T11:58:00+UTC","ecs.version":"1.6.0","log.logger":"/usr/bin/mariadb-cronjob-maintenance.sh","log.origin.function":"analyzeTable","log.level":"info","message":"analyze table `keystone`.`project` done"}
```
> [mariadb] verbose logging option for the analyzetables job

- openstack/keystone/templates/sentry.yaml
- 6/17 regions dont have DSN in secrets, we need to standardise
> [Keystone] enforce sentryProject creation for keystone

- openstack/limes-campfire/templates/deployment.yaml
Campfire aims to resolve projectIDs of subprojects recursively in order to retrieve possible mail recipients.
If the top level project also does not include any data, the domain level will be queried.
This list contains the exclusions where this query should be avoided."
> [campfire] add domain exclusion list

- openstack/keystone/templates/etc/_secrets.conf.tpl
The new secret-injector validator throws an error, we need to resolve the secret in cc_radius
> [keystone] include resolve_secret in cc_radius

- openstack/limes-campfire/templates/secret.yaml
- openstack/limes/templates/configmap.yaml
- openstack/limes/templates/seed-campfire.yaml
Because of the way that the Vault permissions are set up, it's easier if we use passwords that are stored under the region where the Campfire is running.
Also, this temporarily limits Limes' usage of Campfire to qa-de-1, in order to enable a rollout to prod while Campfire is not deployed to prod yet.
> limes-campfire: seed users for global regions in a different way

- common/pxc-db/Chart.yaml
- common/pxc-db/ci/test-values.yaml
- common/pxc-db/templates/cluster.yaml
- common/pxc-db/templates/initdb-bin.yaml
- common/pxc-db/templates/initdb-job.yaml
- common/pxc-db/templates/initdb-rbac.yaml
- common/pxc-db/templates/initdb-secret.yaml
- common/pxc-db/templates/initdb/_init.sql.tpl
- common/pxc-db/templates/secrets.yaml
- common/pxc-db/values.yaml
* Use operator custom resource to create and set application user password
init-db job is still being used to create grants because the operator can't handle `ALL PRIVILEGES` grant
> [pxc-db] Use operator custom resource option to create users

- openstack/nova/ci/test-values.yaml
We do not require this value to be set anymore and thus remove it to not confuse anybody searching for that string.
> [Nova] Remove ironic_service_password from CI values

- openstack/ironic/templates/etc/_inspector_secrets.conf.tpl
- openstack/ironic/templates/etc/_netrc.tpl
- openstack/ironic/templates/etc/_nginx.conf.tpl
- openstack/ironic/templates/etc/_secrets.conf.tpl
- openstack/ironic/templates/redfish-certrobot-secret.yaml
Add missing resolve_secret everywhere the validator complains about.
Found with the help of the secrets-inejector-validator:
helm-template-app ironic | secrets-injector-validator -kinds=OpenstackSeed
> [ironic] fix secrets-injector syntax

- openstack/manila/Chart.yaml
- openstack/manila/templates/type-seeds.yaml
- openstack/manila/values.yaml
This PR moves customisation of share type's extra_specs to value files.
We merge `share_type_extra_specs` into `share_types.*.extra_specs`, with latter takes precedence.
The share type name is used as `share_backend_name` if otherwise not specified.
We can also set bool value to any item in the share type list,
but then default `share_type_extra_specs` is used, and  any customisation would be lost.
> [manila] rework share type seeding

- common/postgresql-ng/Chart.yaml
- common/postgresql-ng/templates/prometheus-alerts.yaml
- common/postgresql-ng/values.yaml
- common/redis/Chart.yaml
- common/redis/templates/prometheus-alerts.yaml
- common/redis/values.yaml
The need to deploy without `PrometheusRule` comes from the cases where the corresponding CRDs aren't registered - typically, in local throw-away development clusters.
> postgresql, redis: support no alerts

- openstack/neutron/templates/etc/_networking_interconnection_secrets.conf.tpl
Our interconnection user might be a vault reference, so we need to make sure to resolve it in the given secret.
> [neutron] Resolve interconnection user in secret

- common/mariadb/CHANGELOG.md
- common/mariadb/Chart.yaml
- common/mariadb/templates/initdb/_configuredb.sh.tpl
- common/mariadb/templates/pre-change-job.yaml
- common/mariadb/values.yaml
* use `shared-app-images/alpine-kubectl` image for a pre-change job instead of the outdated `unified-kubernetes-toolbox`
> [mariadb] use `shared-app-images/alpine-kubectl` for pre-change job

- openstack/nova/values.yaml
Clean pre_change_hook from the nova chart values
These values were left after https://github.com/sapcc/helm-charts/pull/3660
> [nova] remove pre_change_hook from nova chart values

- system/Makefile
- system/argora-operator-remote/.helmignore
- system/argora-operator-remote/Chart.yaml
- system/argora-operator-remote/ci/test-values.yaml
- system/argora-operator-remote/managedresources/kustomize.yaml
- system/argora-operator-remote/templates/_helpers.tpl
- system/argora-operator-remote/templates/deployment.yaml
- system/argora-operator-remote/templates/managedresource.yaml
- system/argora-operator-remote/templates/remote-kubeconfig.yaml
- system/argora-operator-remote/values.yaml
- system/kustomize/argora-operator-managedresources/kustomization.yaml
- system/kustomize/argora-operator-remote/kustomization.yaml
- system/kustomize/argora-operator-remote/managedresource.yaml
- system/kustomize/argora-operator-remote/manager-remote-patch.yaml
- system/kustomize/argora-operator-remote/remote-kubeconfig.yaml
- system/kustomize/argora-operator/kustomization.yaml
* Adds new make target for `argora-operator-remote` in similar way as other operators, based on kustomize from extern repos and helmify
> Add argora-operator-remote make target and helm templates

- common/redis/templates/prometheus-alerts.yaml
This PR changes the PostgreSQL names in the prometheus alerts to Redis.
> Chore: Rename PostgreSQL to Redis in prometheus-alerts.yaml

- openstack/nannies/templates/cinder-nanny-secrets.yaml
- openstack/nannies/templates/nova-nanny-secrets.yaml
- openstack/nannies/templates/seed.yaml
The cinder and nova nanny are no longer maintained by the observability team
but by the cinder and nova team, respectively. To simplify password and
rotation management, we replace the master password used for keystone password
generation with the actual keystone passwords.
> [nannies] Replace master password with keystone passwords

- global/andromeda/Chart.lock
version 0.17.3 specifically will allow the `root` user password to be rotated in Vault and, with a chart redeployment, it will be applied to the MariaDB server without further manual intervention.
> [andromeda] mariadb bump

- global/andromeda/Chart.lock
the `utils` bump is not necessary but my previous commit was created incorrectly so the `mariadb` bump cannot be applied yet.
> [andromeda] dep bump

- openstack/swift/ci/test-values.yaml
- openstack/swift/templates/support_seed.yaml
`helm diff` was empty - this is homologous to the old expression
> [swift] use c_domains_without_support_projects (srs #485)

- system/logs/vendor/logstash-external/templates/configmap.yaml
This got accidentally removed in https://github.com/sapcc/helm-charts/pull/8186. Until the jump server has migrated I will re-add this section
---------
> fix(logs): adds jump.json configmap for logstash to keep backwards compatibility in the transition phase

- openstack/ironic/Chart.lock
- openstack/ironic/Chart.yaml
mariadb ~0.15.3  to ~0.17.3
- set root password on every database start
- use shared-app-images/alpine-kubectl for pre-change job
- use passwordless local connections for healthchecks and exporter
- use custom entrypoint script for mariadb deployment
- verbose logging option for the analyzetables job
- maintenance job configmap condition fixed
- update pod-readiness container image
- mysqld_exporter updated to 0.17.1
- set default ignore_db_dirs value
- Fix maria_backup_status alerts
- fix maintenance cronjob resource names
- maintenance job added
- enquote password in my.cnf
- remove user and password from readyness and lifeness probes
- move backup-v2 oauth secret to a separate secret
- version updated to 10.5.28
pxc-db ~0.2.13  to ~0.3.0
- Use operator custom resource option to create …
> [ironic] multiple dependency updates

- common/rabbitmq/CHANGELOG.md
- common/rabbitmq/Chart.yaml
- common/rabbitmq/templates/users-secret.yaml
- common/rabbitmq/values.yaml
Creation of the `metrics` user with `monitoring` tag no longer coupled with enabling prometheus metrics
Native Prometheus RabbitMQ metrics don't rely on any user
To create `metrics` user, if needed, set:
`.Values.rabbitmq.monitoring.addMetricsUser: true`
> [rabbitmq] don't create metrics user if not needed

- common/rabbitmq/CHANGELOG.md
- common/rabbitmq/Chart.yaml
- common/rabbitmq/values.yaml
- bugfix and reduced mem usage for the classic queue
> [rabbitmq] version bumped to 4.0.7-management

- system/logs/templates/alerts/_otel-alerts.tpl
We received redundant alerts for the 'debug' and the 'deployments' exporters. The former is
not a exporter we care about in a prod environment, and the latter receives inconsistent and very little
traffic (<1 log per h).
---------
> fix(logs): changes alert rule to exlude 'debug', 'deployment' exporters

- prometheus-exporters/ns-exporter/alerts/probe.alerts
* agent_id is currently empty because we do not consider the label in the aggregation function. We remove it from the message as it only pollutes the message.
* fix missing router ID
> fix: message in neutron ns-exporter alerts

- prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/alerts/thanos-metal/netapp.yaml
We can ignore the alert when filer being decommissioned or in build.
> [netapp-harvest-exporter] improve alert NetappHarvestManilaFilerNotScraped

- openstack/utils/Chart.yaml
- openstack/utils/templates/_hosts.tpl
Add support for different db types in `utils.db_url` helper by passing an optional sixth item
This change is required for `nova`, `placement` and `ironic-inspector` database url configuration
> [utils] Add support for different db types in `utils.db_url` helper

- openstack/designate/Chart.lock
- openstack/designate/Chart.yaml
* increase maximum rabbitmq message size from 16M to 256M
* in rabbitmq 4.0 this default value has been changed from 256M to 16M
* bump rabbitmq chart to 0.17.1
* updates rabbitmq to 4.0.7
* add user-credential-updater sidecar
> [designate][rabbitmq] increase maximum rabbitmq message size to 256M

- prometheus-rules/prometheus-vmware-rules/Chart.yaml
- prometheus-rules/prometheus-vmware-rules/alerts/datastore.alerts
Increased threshold for DatastoreHostCountMismatch Alert from 30 minutes to 60 minutes and bumped the chart version
> Change threshold for DatastoreHostCountMismatch Alert

- openstack/barbican/Chart.lock
- openstack/barbican/Chart.yaml
- openstack/barbican/ci/test-values.yaml
- openstack/barbican/templates/_helpers.tpl
- openstack/barbican/templates/api-deployment.yaml
- openstack/barbican/templates/etc/_secrets.conf.tpl
- openstack/barbican/templates/migration-job.yaml
- openstack/barbican/values.yaml
Add support for PXC galera cluster URL
Update mysql-metrics and utils charts to support galera cluster
> [barbican][pxc-db] Add support for PXC galera cluster: part 1

- openstack/kmip/Chart.lock
- openstack/kmip/Chart.yaml
- openstack/kmip/ci/test-values.yaml
- openstack/kmip/values.yaml
Add default values for pxc-db chart dependency
Without setting pxc_db.enabled=true this PR causes no change in deployment
> [kmip][pxc-db] Add support for PXC galera cluster: part 1

- openstack/manila/Chart.lock
- openstack/manila/Chart.yaml
- openstack/manila/ci/test-values.yaml
- openstack/manila/templates/_helpers.tpl
- openstack/manila/templates/api-deployment.yaml
- openstack/manila/templates/migration-job.yaml
- openstack/manila/templates/scheduler-deployment.yaml
- openstack/manila/templates/shares/_netapp-deployment.yaml.tpl
- openstack/manila/templates/shares/_netapp-ensure-deployment.yaml.tpl
- openstack/manila/values.yaml
Add default values for pxc-db chart dependency
Update utils charts to support galera cluster
> [manila][pxc-db] Add support for PXC galera cluster: part 1

- common/thanos/Chart.yaml
- common/thanos/templates/_thanos_helpers.tpl
This pattern is inflexible: `thanos-%s-grpc.%s.%s`
> thanos: allow more store naming patterns

- openstack/designate/Chart.yaml
- openstack/designate/templates/etc/_designate.conf.tpl
- openstack/designate/templates/etc/_secrets.conf.tpl
[osprofiler] configuration contains hmac_keys option, that should be resolved by secrets-injector and moved to secret resource
another change required to switch to secrets-injector is tempest_accounts.yaml, tempest_deployment_config.json and tempest_extra_options in `designate-etc`, they might be changed in future pull requests
> [designate] move osprofiler config section to secrets

- .github/CODEOWNERS
No point in Ivo getting spammed on topics he isn't involved with.
> [hermes] rm Ivo from codeowners

- system/unbound/templates/deployment.yaml
Also, implemented the ability to disable the sidecars as such and run the containers along the main one.
This is all in the context of
https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/
> [unbound] the sidecar capability logic is a bit more complex

- openstack/hermes/ci/test-values.yaml
- openstack/hermes/templates/keystone-seed.yaml
- openstack/maia/ci/test-values.yaml
- openstack/maia/templates/seed.yaml
In an attempt to make deployment of new domains easier, @majewsky recently introduced global.domain_seeds.customer_domains. As this could replace the old skip_hcm_domain, poses the opportunity to distinguish between internal and external domains in future and accommodate other specialties we would like to suggest this on seeds of other services too.
The expressions are technically equal, only the ora domain was added for Maia and fsn, kyma, ora for Hermes. If they were excluded on purpose, let me know and I can change it. I excluded `iaas-` for now.
I ran `h3 diff` with `dyff` option against qa-de-1 and eu-de-1, you can have a look at the output here:
[maiaDE1diff.txt](https://github.com/user-attachments/files/19349459/maiaDE1diff.txt) …
> [hermes+maia] seed generic domains using global.domains_seeds

- openstack/elektra/ci/test-values.yaml
- openstack/elektra/templates/seed.yaml
In an attempt to make deployment of new domains easier, @majewsky recently introduced global.domain_seeds.customer_domains. As this could replace the old skip_hcm_domain, poses the opportunity to distinguish between internal and external domains in future and accommodate other specialties we would like to suggest this on seeds of other services too.
The expressions are technically equal, only the ora domain was added. If this is on purpose, I can introduce an exception. I excepted iaas- (external) domains already, as I thought they are probably missing on purpose, but I could also add those if desired.
I ran h3 diff against qa-de-1 and deduplicated the things which just switched their order, you can have a look at the output here: …
> [elektra] seed generic domains using global.domains_seeds

- common/mariadb/CHANGELOG.md
- common/mariadb/Chart.yaml
- common/mariadb/scripts/mariadb-credential-updater.py
- common/mariadb/values.yaml
* add missing headers to the mariadb-credential-updater.py
* remove unused `credentialUpdater.enabled` option from values, this sidecar is non-optional
> [mariadb] add missing license headers and remove unused option

- common/memcached/CHANGELOG.md
- common/memcached/Chart.yaml
- common/memcached/templates/service.yaml
- needed for calico rollout
- also bump chart
> [memcached] if using external ip set externalTrafficPolicy: Local

- openstack/designate/Chart.lock
- openstack/designate/Chart.yaml
* bump pxc-db chart to 0.3.1
moves user creation to operator configuration via crd
* bump mariadb chart to 0.18.0
allows to update root password and add user-credential-updater sidecar
* bump utils to 0.23.0
* bump memcached to 0.6.6
updates memcached and memcached-exporter
> [designate][shared] bump service dependency

- openstack/manila/Chart.lock
- openstack/manila/Chart.yaml
* adds user-credential-updater sidecars to both services
* allows to update root user password in mariadb
* allows to use secrets-injector for backup-v2 secrets
* bumps mariadb and rabbitmq to latest bugfix releases
> [manila][shared] update mariadb and rabbitmq chart dependencies

- openstack/elektra/ci/test-values.yaml
- openstack/elektra/templates/seed.yaml
Reverts sapcc/helm-charts#8215
Need to find the cause of
```
INFO:root:create group 'btp_fp/BTP_FP_SUPPORT_TOOL_VIEWERS'
ERROR:root:seed failed: You are not authorized to perform the requested action. (HTTP 403) (Request-ID: req-38a5a302-b2f7-490a-8374-11878bd94543)
ERROR: failed to seed 'elektra/elektra-seed' - version 4121910297: exit status 1
```
> Revert "[elektra] seed generic domains using global.domains_seeds"

- openstack/nova/Chart.lock
- openstack/nova/Chart.yaml
- openstack/nova/ci/test-values.yaml
* update mariadb chart to 0.18.2
* updates user-credential-updater.py
* update memcached chart to 0.6.8
* updates memcached to latest bugfix release
> [nova] minor helm dependencies bump

- openstack/utils/Chart.yaml
- openstack/utils/templates/_helpers.tpl
Add a helper to configure sentry. This will configure SENTRY_DSN. If the variable sentry.release is specified, a SENTRY_RELEASE environment variable will be set as well.
> [utils] Add helper to configure sentry

- openstack/placement/Chart.lock
- openstack/placement/Chart.yaml
- openstack/placement/values.yaml
Bump mariadb 0.14.1 to 0.18.2
* standardize labels
* fixed service selector
* update mariadb app 10.5.17 to 10.5.28
* fix vulnerabilities against DOS attacks and other exploits:
* CVE-2022-47015
* CVE-2024-21096
* CVE-2023-22084
* CVE-2025-21490
* configurable enablement of AWS backup storage
* avoid showing passwords in processlist of k8s nodes
* add maintenance job to boost performance
* add `.Values.mariadb.job` values for maintenance job configuration
* fix `maria-back-me-up` alert rules
* allow to change root password without intermittent check failure
* update root password on database start
* add `credential-updater` sidecar
* `.Values.mariadb.initdb_secret` becomes redundant
* configurable enablement of Swift backup storage
* remove support for value …
> [placement] Bump chart dependencies to newest versions

- prometheus-exporters/openstack-exporter/Chart.lock
- prometheus-exporters/openstack-exporter/Chart.yaml
Bump utils 0.18.4 to 0.24.1
* use `project` instead of `tenant` for user logging
* add `system_scope` to user logging
Bump linkerd-support 1.0.0 to 1.1.0
* delete hook job before creating it to fix helm rollbacks
* switch from bitnami/kubectl to internal kubectl image
Bump owner-info 0.2.0 to 1.0.0
* add configmap delete hook on `post-delete`
> [openstack-exporter] Bump chart dependencies to newest versions

- openstack/cinder/Chart.lock
- openstack/cinder/Chart.yaml
- openstack/cinder/values.yaml
Bump mariadb 0.15.5 to 0.18.2
* configurable enablement of AWS backup storage
* avoid showing passwords in processlist of k8s nodes
* add maintenance job to boost performance
* add `.Values.mariadb.job` values for maintenance job configuration
* fix `maria-back-me-up` alert rules
* allow to change root password without intermittent check failure
* update root password on database start
* add `credential-updater` sidecar
* `.Values.mariadb.initdb_secret` becomes redundant
* configurable enablement of Swift backup storage
* remove support for value `.Values.mariadb.credentialUpdater.enabled`
Bump rabbitmq 0.14.1 to 0.17.1
* default to not creating a `metrics` user even with `metrics` enabled
* add `.Values.rabbitmq.metrics.addMetricsUser` to enable `metrics` user
* bump rabbitmq app 4.0.6 …
> [cinder] Bump chart dependencies to newest versions

- system/kubernikus-monitoring/Chart.yaml
- system/kubernikus-monitoring/alerts/kluster.alerts
As discussed with @majewsky it does not make sense to alert customers, because they cannot raise quota themselves anymore. I will update the playbook to link the support staff how to create a quota override.
> [kubernikus] remove mail sending for quota alert

- openstack/kmip/Chart.lock
- openstack/kmip/Chart.yaml
* bumps mariadb chart to 0.18.2
adds user-credential-updater sidecar and allows to update root password
> [kmip][shared] bump kmip dependencies

- openstack/glance/Chart.lock
- openstack/glance/Chart.yaml
* mariadb 0.15.3 to 0.18.2
* updates mariadb and mysqld-exporter to the latest bugfix releases
* adds user-credential-updater sidecar
* allows to update mariab root password
* memcached 0.6.3 to 0.6.9
* updates to the latest bugfix versions
* utils 0.19.6 to 0.25.0
> [glance][shared] bump service dependencies

- .github/CODEOWNERS
We got a couple of new colleagues that should get notified and able to approve work on the helm-charts of the services managed by compute-storage-api.
> Extend compute-storage-api services' CODEOWNERS

- openstack/keystone/Chart.lock
- openstack/keystone/Chart.yaml
- openstack/keystone/ci/test-values.yaml
- openstack/keystone/templates/_helpers.tpl
- openstack/keystone/templates/deployment-api.yaml
- openstack/keystone/templates/deployment-cron.yaml
- openstack/keystone/templates/etc/_keystone.conf.tpl
- openstack/keystone/templates/etc/_secrets.conf.tpl
- openstack/keystone/templates/job-bootstrap.yaml
- openstack/keystone/templates/job-migration.yaml
- openstack/keystone/values.yaml
* Add support for PXC galera cluster URL
* Update mysql-metrics and utils charts to support galera cluster
* Remove mariadb-galera support
* Remove unused helm helper functions db_host and keystone_db_host
* Update linkerd-support and owner-info to release versions
> [keystone][pxc-db] Add support for PXC galera cluster

- openstack/nova/templates/etc/_nova-scheduler.conf.tpl
- openstack/nova/values.yaml
We need to keep external customers on specific hosts for licensing reasons. We do this in `nova-scheduler` by prefix-matching domain names in a special filter, which adds the `CUSTOM_EXTERNAL_CUSTOMER_SUPPORTED` to filter hosts in Placement.
This commit configures the default for all regions to "iaas-".
---
This is configuring the feature we add in https://github.com/sapcc/nova/pull/536
> [Nova] Set external_customer_domain_name_prefixes

- openstack/ironic/ci/test-values.yaml
- openstack/ironic/templates/seed.yaml
In an attempt to make deployment of new domains easier, @majewsky recently introduced global.domain_seeds.customer_domains. As this could replace the old skip_hcm_domain, poses the opportunity to distinguish between internal and external domains in future and accommodate other specialties we would like to suggest this on seeds of other services too.
The expressions are technically equal, only the ora domain was added. If they were excluded on purpose, let me know and I can change it. I excluded `iaas-` for now.
I ran `h3 diff` with `dyff` option against qa-de-1 and eu-de-1 you can have a look at the output here:
[ironicDE1diff.txt](https://github.com/user-attachments/files/19349338/ironicDE1diff.txt)
[ironicQA1diff.txt](https://github.com/user-attachments/files/19349339/ironicQA1diff.txt)
> [ironic] seed generic domains using global.domains_seeds

- openstack/designate/templates/etc/_designate_audit_map.yaml
Our DRAFT external documentation had unmapped endpoints in the list. This led me to check the full mapping, and many endpoints are missing. This is updated, and I've communicated the DRAFT documentation required correction.
> [designate] update hermes audit map file with unmapped endpoints

- openstack/glance/Chart.yaml
- openstack/glance/templates/etc/_glance-api.conf.tpl
- openstack/glance/templates/etc/_secrets.conf.tpl
osprofiler configuration contains a secret hmac value, so it should be in the secret instead of a configmap
> [glance] move osprofiler configuration to secrets

- openstack/manila/Chart.yaml
- openstack/manila/templates/etc/_manila.conf.tpl
- openstack/manila/templates/etc/_secrets.conf.tpl
> [manila] move osprofiler configuration to secrets

- openstack/glance/Chart.lock
- openstack/glance/Chart.yaml
- openstack/glance/ci/test-values.yaml
- openstack/glance/templates/_helpers.tpl
- openstack/glance/templates/deployment.yaml
- openstack/glance/templates/migration-job.yaml
- openstack/glance/values.yaml
Add support for PXC galera cluster URL
> [glance][pxc-db] Add support for PXC galera cluster: part 1

- openstack/placement/Chart.yaml
- openstack/placement/templates/etc/_placement.conf.tpl
- openstack/placement/templates/etc/_secrets.conf.tpl
> [placement] move osprofiler configuration to secrets

- global/andromeda/Chart.yaml
- global/andromeda/templates/etc/_policy.json.tpl
if the user's domain ID is default doesn't mean it should have an access to andromeda resources.
> [andromeda] limit andromeda access rights

- openstack/barbican/Chart.lock
- openstack/barbican/Chart.yaml
- openstack/barbican/ci/test-values.yaml
- openstack/barbican/templates/_helpers.tpl
- openstack/barbican/templates/etc/_secrets.conf.tpl
- openstack/barbican/values.yaml
* bump mariadb chart dependency
adds support for root password update and user-credential-updater sidecar
* remove rabbitmq dependency
it seems to be not being used
> [barbican][shared] bump mariadb chart dependency and remove rabbitmq

- openstack/designate/ci/test-values.yaml
- openstack/designate/templates/seeds.yaml
In an attempt to make deployment of new domains easier, @majewsky recently introduced `global.domain_seeds.customer_domains`. As this could replace the old `skip_hcm_domain`, poses the opportunity to distinguish between internal and external domains in future and accommodate other specialties we would like to suggest this on seeds of other services too. 
The expressions are technically equal, only the `ora` domain was added. If this is on purpose, I can introduce an exception. I excepted `iaas-` (external) domains already, as I thought they are probably missing on purpose, but I could also add those if desired. 
I ran `h3 diff` against `qa-de-1`, you can have a look at the output here: [designatediff.txt](https://github.com/user-attachments/files/19233309/designatediff.txt)
> [designate] seed generic domains using global.domains_seeds

- openstack/octavia/Chart.lock
- openstack/octavia/Chart.yaml
- openstack/octavia/ci/test-values.yaml
- openstack/octavia/templates/_helpers.tpl
- openstack/octavia/templates/etc/_secrets.conf.tpl
- openstack/octavia/templates/octavia-migration-job.yaml
- openstack/octavia/values.yaml
* Add support for PXC galera cluster URL
* Update mysql-metrics and utils charts to support galera cluster
* mysql-metrics 0.3.5 -> 0.4.2, minimum 0.3.6 is required because of the https://github.com/sapcc/helm-charts/pull/7130
* utils  0.19.7 -> 0.23.0, minimum 0.21.0 is required because of the https://github.com/sapcc/helm-charts/pull/7505
> [octavia][pxc-db] Add support for PXC galera cluster: part 1

- global/prometheus-alertmanager-operated/Chart.yaml
- global/prometheus-alertmanager-operated/templates/am-config-route-slack.yaml
- global/prometheus-alertmanager-operated/values.yaml
- system/gatekeeper-config/values.yaml
- Use support group from values.
- adds `coredns` support group
- Ignore support groups which do have a dedicated slack webhook for critical alerts.
```diff
prometheus-alertmanager, route-slack, AlertmanagerConfig (monitoring.coreos.com) has changed:
...
- continue: true
matchers:
- matchType: =
name: severity
value: critical
- matchType: =~
name: region
value: global|ap-ae-1|ap-au-1|ap-cn-1|ap-jp-1|ap-jp-2|ap-sa-1|ap-sa-2|eu-de-1|eu-de-2|eu-nl-1|la-br-1|na-ca-1|na-us-1|na-us-2|na-us-3
- matchType: =~
name: support_group
-         value: src|network-data|network-security|network-lb|network-wan|storage|capacity-ops
+         value: capacity-ops|coredns|network-data|network-lb|network-security|network-wan|src|storage|workload-management
receiver: support_group_alerts_critical
- continue: …
```
> alertmanager: use support groups from values

- openstack/keppel/templates/seed.yaml
Concourse currently uses an application credential issued from my personal account, so the audit log looks like I'm pushing everything. I would like to get rid of this.
Also, the newer Keppel accounts will be configured so that only this specific user may push.
This user is only provisioned in eu-de-1 because every other region only holds replica accounts where pushing does not work.
> keppel: add technical user for pushing from Concourse CI

- openstack/elektra/templates/ingress_public.yaml
This pull request introduces an exception to the Elektra ingress configuration to bypass OIDC (OpenID Connect) authentication for the path /verify-auth-token. This adjustment is necessary because the path is utilized by the Keystone federation for authentication purposes, and OIDC should not interfere with its operation.
> chore(elektra): add exception for keystone federation

- openstack/keystone/Chart.yaml
- openstack/keystone/templates/deployment-api.yaml
- openstack/keystone/templates/etc/_federation-oidc.conf.tpl
- openstack/keystone/templates/etc/_keystone.conf.tpl
- openstack/keystone/templates/etc/_sso_callback_template.html.tpl
- openstack/keystone/templates/etc/_wsgi-keystone.conf.tpl
- openstack/keystone/templates/federation.yaml
- openstack/keystone/templates/ingress-api.yaml
- openstack/keystone/values.yaml
* Implemented support for Keystone federation using OpenID Connect (OIDC).
* Updated the Keystone Chart to version 0.10.0 reflecting the new feature.
* Added a new _federation-oidc.conf.tpl template to support OIDC configurations.
* Modified the wsgi-keystone.conf.tpl to add location blocks for OIDC endpoints.
* Created a new federation.yaml file to manage OIDC-related secrets within
Kubernetes.
* Extended ingress configuration in ingress-api.yaml to handle session affinity
required for browser-based federation workflows.
* Updated values.yaml to include federation configuration options with
placeholders for provider, client_id, client_secret, and crypto_passphrase.
* Update keystone.conf to include the necessary federation bits
Right now the setup makes several assumptions:
* SAP IAS …
> Settings for keystone federation via OIDC

- common/mariadb/CHANGELOG.md
- common/mariadb/Chart.yaml
- common/mariadb/templates/_helpers.tpl
- common/mariadb/templates/secret.yaml
* Remove the following internal helm template helper functions:
* `keystone_url`
* `mariadb.db_host`
* `mariadb.root_password`
* `mariadb.resolve_secret`
> [mariadb] remove unused internal functions

- openstack/manila/templates/shares/_share-netapp.conf.tpl
double the setting, we observed a vol move that took longer.
The setting is just there to have it not pending indefinitely,
apparently 1 hour is not enough.
> [manila] add netapp_volume_move_cutover_timeout option

- openstack/ironic/Chart.yaml
- openstack/ironic/templates/etc/_ironic.conf.tpl
- openstack/ironic/templates/etc/_secrets.conf.tpl
> [ironic] move osprofiler configuration to secrets

- openstack/designate/templates/etc/_pools.yaml.tpl
- we don't need it in pools.yaml
> [designate] old akamai v1 driver is not supported since long time

- system/unbound/templates/prometheus-alerts.yaml
Normally we expoect both unbounds to get close to 50% of the total traffic. IOW it should be evenly devided between the two unbounds.
The default tolerance is 10%, meaning that the alert will fire if the traffic drops below 40% or jumps above 60%.
We can change that by setting ```$.Values.unbound.tolerable_traffic_distribution_deviation```
> [unbound] introducing the DnsUnbound{1,2}DisproportionateAmountOfTraffic

- common/mariadb/CHANGELOG.md
- common/mariadb/Chart.yaml
- common/mariadb/scripts/mariadb-set-root-password.sh
* `set-root-password` init container now always tries to create `'root'@'localhost'` and `'root'@'%'` user if it doesn't exist
This helps to avoid lock-out issue, if this user was previously deleted
> [mariadb] always try to create root user on pod init

- openstack/octavia/Chart.lock
- openstack/octavia/Chart.yaml
- openstack/octavia/ci/test-values.yaml
* mariadb 0.14.2 -> 0.19.1
* memcached 0.5.3 -> 0.6.9
* mysql-metrics 0.3.5 -> 0.4.3
* rabbitmq 0.11.1 -> 0.17.1
* utils 0.19.7 -> 0.25.0
This change:
* adds user-credential-updater sidecars to mariadb and rabbitmq services
* allows to update root user password in mariadb
* allows to use secrets-injector for backup-v2 secrets
* bumps mariadb, rabbitmq, mysql-metrics, memcached to latest bugfix releases
> [octavia][shared] bump service dependencies

- system/greenhouse-ccloud/ci/test-values.yaml
- system/greenhouse-ccloud/templates/cert-manager-pluginpreset.yaml
- system/greenhouse-ccloud/values.yaml
Adds `cert-manager` webhook timeout option to plugin preset
> chore(greenhouse): Adds cert-manager webhook timeout

- openstack/designate-nanny/ci/test-values.yaml
- openstack/designate-nanny/templates/_helpers.tpl
- openstack/designate-nanny/templates/deployment.yaml
- openstack/designate-nanny/values.yaml
- openstack/designate/ci/test-values.yaml
- openstack/designate/templates/_helpers.tpl
- openstack/designate/templates/api-deployment.yaml
- openstack/designate/templates/api-ingress.yaml
- openstack/designate/templates/api-service.yaml
- openstack/designate/templates/etc-configmap.yaml
- openstack/designate/templates/etc/_designate.conf.tpl
- openstack/designate/templates/etc/_designate_audit_map.yaml
- openstack/designate/templates/prometheus-alerts.yaml
- openstack/designate/templates/seeds.yaml
- openstack/designate/values.yaml
When working on https://github.com/sapcc/helm-charts/pull/8193 I noticed that the `global_setup` variable is misplaced so I created `global.is_global_region` in the values.
This handles all usages of this new variable in designate service.
Additionally, I added here the fix for the designate seed to only seed `global` from `eu-de-2` to prevent the missing dependency errors in the seeder.
The diff is in line with the current diff in the pipe for global + DE2. 
related:
https://github.com/sapcc/helm-charts/pull/8384
https://github.com/sapcc/helm-charts/pull/8383
> [designate] switch Values.global_setup to Values.global.is_global_region

- openstack/keystone/ci/test-values.yaml
- openstack/keystone/templates/_helpers.tpl
- openstack/keystone/templates/bin/_bootstrap.tpl
- openstack/keystone/templates/deployment-2faproxy.yaml
- openstack/keystone/templates/etc/_keystone.conf.tpl
- openstack/keystone/templates/ingress-api.yaml
- openstack/keystone/templates/seed.yaml
- openstack/keystone/templates/service-api.yaml
- openstack/keystone/values.yaml
When working on https://github.com/sapcc/helm-charts/pull/8193 I noticed that the `global_setup` variable is misplaced so I created `global.is_global_region` in the values.
This handles all usages of this new variable in keystone service.
The diff is in line with the current diff in the pipe for global + DE2. 
related:
https://github.com/sapcc/helm-charts/pull/8385
https://github.com/sapcc/helm-charts/pull/8383
> [keystone] switch Values.global_setup to Values.global.is_global_region

- openstack/utils/Chart.yaml
- openstack/utils/templates/_hosts.tpl
- openstack/utils/templates/_ini_sections.tpl
This change introduces an option to select the default user for RabbitMQ and MariaDB template function:
* `ini_sections.default_transport_url`
* `utils.db_url` with sub-functions
Currently, these functions select the default user the following way:
* RabbitMQ selects the 'default' user.
* MariaDB selects the `first` defined database and then chooses the key from users with the same name as the database.
After this change, `defaultUser` option (`.Values.rabbitmq.defaultUser` or `.Values.mariadb.defaultUser`) could be used to select another user when required.
After this change, this user could be selected two ways:
* `defaultUser` option (`.Values.rabbitmq.defaultUser`, `.Values.mariadb.defaultUser`) could be used in service values to select another user when required
* …
> [utils] add an option to select default user for rabbitmq and db

- openstack/keppel-trivy/templates/deployment-api.yaml
- openstack/keppel-trivy/templates/deployment-server.yaml
- openstack/keppel/templates/deployment-api.yaml
- openstack/keppel/templates/deployment-janitor.yaml
Why are there two annotations 💀
> keppel: move reloader annotation to correct annotation

- system/unbound/templates/prometheus-alerts.yaml
The allowed limits in the summary were calculated incorrectly if using defaults. The filter expression was fine.
> [unbound] fixed the DnsUnbound{1,2}DisproportionateAmountOfTraffic summary

- openstack/nova/Chart.yaml
- openstack/nova/templates/_console_deployment.yaml.tpl
- openstack/nova/templates/api-deployment.yaml
- openstack/nova/templates/api-metadata-deployment.yaml
- openstack/nova/templates/bigvm-deployment.yaml
- openstack/nova/templates/cell2-conductor-deployment.yaml
- openstack/nova/templates/conductor-deployment.yaml
- openstack/nova/templates/etc-secret.yaml
- openstack/nova/templates/etc/_nova.conf.tpl
- openstack/nova/templates/hypervisors/_ironic-deployment.yaml.tpl
- openstack/nova/templates/hypervisors/_kvm-deployment.yaml.tpl
- openstack/nova/templates/hypervisors/hypervisors-vmware-deployment-vct.yaml
- openstack/nova/templates/scheduler-deployment.yaml
This change moves [osprofiler] configuration section to a separate `osprofiler.conf` file in `nova-etc-secret` and mounts it into containers.
> [nova] move osprofiler configuration to secrets

- openstack/limes/templates/_utils.tpl
- openstack/limes/templates/ingress-api.yaml
- openstack/limes/templates/ingress-liquids.yaml
- openstack/limes/templates/prometheus-alerts.yaml
- openstack/limes/templates/seed-catalog.yaml
- openstack/limes/templates/seed-grants.yaml
- openstack/limes/templates/seed.yaml
- openstack/limes/templates/support_seed.yaml
- openstack/limes/values.yaml
* use `global.is_global_region` instead of deriving this info from the `limes_url`
* use `customer_domains = ["global"]` from the values for the global region (less special logic)
* replace `contains "iaas-"` with `hasPrefix "iaas-"` for more robustness
> [limes] use global.is_global_region in helm-charts

- openstack/keystone/Chart.lock
- openstack/keystone/Chart.yaml
Updates mariadb chart from 0.16.9 to 0.19.1:
* adds user-credential-updater sidecar
* allows to update root user password without database downtime
Updates mysql-metrics chart to 0.4.3:
* adds option to set vpa main container
> [keystone][mariadb] bump chart dependency

- openstack/nova/values.yaml
sql_exporter needs the labels to be strings,
so we convert it beforehand.
Fixes:
"column 'id' must be type text (string)"
Metric is consumed by OpenstackNovaComputeServiceVersionsMismatch alert
> [nova] fix openstack_compute_service_version metric

- system/opensearch-logs/templates/config/_ds-alerts-ism.json.tpl
- system/opensearch-logs/templates/config/_ds-audit-ism.json.tpl
- system/opensearch-logs/templates/config/_ds-compute-ism.json.tpl
- system/opensearch-logs/templates/config/_ds-deployments-ism.json.tpl
- system/opensearch-logs/templates/config/_ds-jump-ism.json.tpl
- system/opensearch-logs/templates/config/_ds-logs-ism.json.tpl
- system/opensearch-logs/templates/config/_ds-logs-swift-ism.json.tpl
- system/opensearch-logs/templates/config/_ds-otel-ism.json.tpl
- system/opensearch-logs/templates/config/_ds-storage-ism.json.tpl
- system/opensearch-logs/templates/config/_install-ds-templates.sh.tpl
- system/opensearch-logs/templates/security-config-secrets.yaml
- system/opensearch-logs/values.yaml
Override values for `min_index_age`, `min_size` and `min_doc_count` in secrets values to allow specific values per region.
> feat(opensearch): override ism policy in values

- common/mariadb/CHANGELOG.md
- common/mariadb/Chart.yaml
- common/mariadb/templates/configmap-mariadb-credential-updater.yaml
- common/mariadb/templates/deployment.yaml
- common/mariadb/templates/etc-configmap.yaml
Remove version label from mariadb deployment pod template and related configmaps to avoid unnecessary database restarts on simple chart version update.
> [mariadb] remove version label from mariadb deployment pod template

- global/andromeda/templates/etc/_policy.json.tpl
Unfortunately the [previous change](https://github.com/sapcc/helm-charts/pull/8381) makes the Andromeda Liquid Server
unable to perform requests on behalf of Limes. A different rule will
have to be applied.
> [andromeda] reverted Oslo policy hardening.

- common/mariadb/CHANGELOG.md
- common/mariadb/Chart.yaml
- common/mariadb/templates/initdb/_init.sql.tpl
Previously, init.sql script was creating a pair of users: 'username'@'%' and 'username'@'localhost'.
The second one stopped being managed since the introduction of the granular user configuration.
See https://github.com/sapcc/helm-charts/pull/3598
These @'localhost' users will be removed now.
> [mariadb] delete unmanaged localhost users

- openstack/limes/templates/configmap.yaml
- openstack/limes/templates/deployment-collect.yaml
Due to the fact that the updated LimesUI is available in elektra prod, we can now enable the mailing functionality in Limes.
I'm unsure if we should leave global out or enable it as well, a hint would be appreciated.
> [limes] Add mailing for expiring commitments

- openstack/designate/Chart.lock
- openstack/designate/Chart.yaml
Bump database dependency chart version 0.19.1 -> 0.22.0:
> [designate][mariadb] bump database dependency chart version

- common/redis/Chart.yaml
- common/redis/templates/deployment.yaml
Explicitly setting the redisPassword, not relying on an auto-generated PW, does not create the ServiceAccount, Role and RoleBinding causing the deployment to fail.
In case as PW is explicitly set, we simply ignore the SerivceAcount.
> [Redis] Ignore ServiceAccount for custom redisPW

- system/secrets-injector/Chart.yaml
- system/secrets-injector/templates/webhook.yaml
This avoids issues with certificates
during chart installation.
> Exclude cert-manager owned secrets from secrets-injector webhook

- common/pgbackup/Chart.yaml
- common/pgbackup/templates/deployment.yaml
- common/pgbackup/values.yaml
- common/pgmetrics/Chart.yaml
- common/pgmetrics/templates/deployment.yaml
- common/pgmetrics/values.yaml
- common/postgresql-ng/Chart.yaml
- common/postgresql-ng/bin/init-generate-secrets.sh
- common/postgresql-ng/templates/deployment.yaml
- common/postgresql-ng/values.yaml
- common/redis/Chart.yaml
- common/redis/bin/init-generate-secrets.sh
- common/redis/templates/deployment.yaml
- common/redis/templates/metrics-deployment.yaml
- common/redis/values.yaml
The PR adds values to control [`reloader`](https://github.com/stakater/Reloader) annotations:
* of generated (user) password Secrets in `postgresql-ng` and `redis` charts
* and of the consuming Deployments in `pgbackup`, `pgmetrics`, `redis/metrics-deployment`
When both are configured, would cause the the consuming Deployments (`pgbackup`, `pgmetrics`, `redis/metrics-deployment`) to be restarted when the password secret changes (is regenerated) in `postgresql-ng` and `redis`.
> Add support of `reloader` annotations in postgresql and redis

- openstack/billing/ci/test-values.yaml
- openstack/billing/templates/prometheus-alerts.yaml
- openstack/billing/templates/seeds.yaml
- openstack/billing/values.yaml
This does a few things:
* add new role for listing flavors
* use `is_global_region` from values (needs pipeline change)
* fix `missing project api_support@global` error in global region
* remove `masterdata_scanner` from global (probably not in use ATM)
* remove `iaas-` support seeding (not necessary according to @majewsky )
[billingDE1diff.txt](https://github.com/user-attachments/files/19503967/billingDE1diff.txt)
[billingGlobalDE2diff.txt](https://github.com/user-attachments/files/19503969/billingGlobalDE2diff.txt)
> [billing] seed new billing role and cleanup seeding to global

- openstack/manila/Chart.lock
- openstack/manila/Chart.yaml
Bump database dependency chart version 0.19.1 -> 0.22.0:
> [manila][mariadb] bump database dependency chart version

- common/pgbackup/Chart.yaml
- common/pgbackup/ci/test-values.yaml
- common/pgbackup/templates/deployment.yaml
- common/pgbackup/templates/secret.yaml
For the `global` region, it is necessary to distinguish the "virtual region" (global) from the real region where the db is running and to be backed up (which has e.g. a storage service available). We already introduced the variable but this should be downwards compatible for all usecases where the `$REGION/values/globals.yaml` is not used.
> [pgbackup] add option to use db_region to fix limes in global

- prometheus-exporters/openstack-exporter/templates/openstack-exporter-openstack-config.yaml
- prometheus-exporters/openstack-exporter/values.yaml
This adds the ability to change the 2 following values for the cinderbackend collector:
expected_sharding_backends
allow_unexpected_backends
> [Openstack-exporter] add values config for cinder

- openstack/limes/files/commitment_mail.tpl
- openstack/limes/templates/configmap.yaml
Mails for expiring commitments can include a link to the dashboard.
> [limes] Add dashboard link to expiring commitment mail

- system/cc-ceph/Chart.yaml
- system/cc-ceph/templates/cephobjectstore-extra.yaml
- system/cc-ceph/templates/cephobjectstore.yaml
otherwise the cert rotation is not reflected in rgw pods
> [ceph] reload storage deployment on cert update

- system/greenhouse-ccloud/Chart.yaml
- system/greenhouse-ccloud/templates/team-roles.yaml
this role is needed to give out permissions to view logs
access to the logs is required for the observability team
to be able to develop the specific log parser for kvm/ceph
> feat(greenhouse): add pod log viewer teamrole

- openstack/octavia/Chart.yaml
- openstack/octavia/templates/etc/_octavia.conf.tpl
- openstack/octavia/templates/etc/_secrets.conf.tpl
osprofiler configuration contains a secret hmac value, so it should be in the secret instead of a configmap
> [octavia] move osprofiler configuration to secrets

- common/mariadb/CHANGELOG.md
- common/mariadb/Chart.yaml
- common/mariadb/templates/backup-v2-deployment.yaml
- common/mariadb/templates/backup-verify-deploy.yaml
Add reloader annotation for maria-back-me-up, so backup-v2 deployment always uses updated credentials
> [mariadb][backup-v2] add reloader annotation for maria-back-me-up

- openstack/neutron/Chart.yaml
- openstack/neutron/templates/etc/_neutron.conf.tpl
- openstack/neutron/templates/etc/_server_agent_shared_secrets.ini.tpl
> [neutron] move osprofiler configuration to secrets

- openstack/manila/templates/etc/_manila_audit_map.yaml
child cannot be a string, but must be a dict
Since we are touching it anyway, noticed that we can also add metadata.
> [manila] fix audit for subnets

- prometheus-rules/prometheus-vmware-rules/alerts/datastore.alerts
- prometheus-rules/prometheus-vmware-rules/alerts/virtualmachine.alerts
pull request to add nfs datastore type from vrops exporter and also a temp fix of nfs in datastore name until it's pushed to the vrops exported in production
as required by multiple false positive alert of datastore space usage on NFS datastore, we are excluding them in the alerting for datastore space usage
also removed most of vvol reference since there are no more vvol in production
> Nfs datastore exclusion

- system/unbound/templates/config.yaml
We can now blocklist/allowlist zones if need be.
Also, the server identity is now based on the release name.
We can now distinguish between parallel, independent deployments.
> [unbound] firewall support, server identity

- openstack/neutron/Chart.lock
- openstack/neutron/Chart.yaml
* `set-root-password` init container now always tries to create `'root'@'localhost'` and `'root'@'%'` user if it doesn't exist
Bump mysql-metrics chart to 0.4.3: adds option to set vpa main container
> [neutron][mariadb] bump database dependency chart version

- openstack/barbican/Chart.lock
- openstack/barbican/Chart.yaml
Bump mysql-metrics chart to 0.4.3: adds option to set vpa main container
> [barbican][mariadb] bump database dependency chart version

- openstack/glance/Chart.lock
- openstack/glance/Chart.yaml
> [glance][mariadb] bump database dependency chart version

- openstack/kmip/Chart.lock
- openstack/kmip/Chart.yaml
> [kmip][mariadb] bump database dependency chart version

- openstack/manila/aggregates/storage/limes.rules
- openstack/manila/alerts/storage/ec2.alerts
Some setups have more than one snapmirror destination endpoint,
so we multiply now by the number of snapmirror relationships.
But only those that are not under control of manila,
i.e. only if the share server does not follow the naming pattern of
`ma_<UUID>`
> [manila] snapmirror capacity for multiple targets

- global/andromeda/templates/deployment-akamai-reports.yaml
- global/andromeda/templates/deployment-akamai.yaml
- global/andromeda/templates/deployment-housekeeping.yaml
This annotation has been recently added to `andromeda-liquid-server` and now it's applied to the remaining deployments.
> [andromeda] auto-reload deployments upon secret update

- system/unbound/templates/prometheus-alerts.yaml
..and not the hardcoded value of "dns-recursor".
> [unbound] use the built-in Release.Namespace variable

- common/pxc-db/Chart.yaml
- common/pxc-db/values.yaml
Update pxc-db database chart to 1.17.0 pxc-operator release tags
> [pxc-db] update to 1.17 pxc-operator release image version

- global/thanos-global/Chart.lock
- global/thanos-global/Chart.yaml
- openstack/prometheus-openstack/Chart.lock
- openstack/prometheus-openstack/Chart.yaml
- system/infra-monitoring/Chart.lock
- system/infra-monitoring/Chart.yaml
- system/prometheus-infra/Chart.lock
- system/prometheus-infra/Chart.yaml
- system/prometheus-kubernetes/Chart.lock
- system/prometheus-kubernetes/Chart.yaml
- system/storage-monitoring/Chart.lock
- system/storage-monitoring/Chart.yaml
- system/thanos-metal/Chart.lock
- system/thanos-metal/Chart.yaml
- system/thanos-scaleout/Chart.lock
- system/thanos-scaleout/Chart.yaml
- system/vmware-monitoring/Chart.lock
- system/vmware-monitoring/Chart.yaml
v0.38.0 introduces new flags and `--store` is not available anymore. However, once a query is enabled, it will automatically pull in a single argument with given cli param
> rebump to last working version

- openstack/nova/templates/etc/_nova_audit_map.yaml.tpl
The unmapped resources are deprecated in the nova api, but they are still being called in production environments and require mapping.
> [nova] update hermes audit map with unmapped resources

- openstack/nova/templates/etc/_nova_audit_map.yaml.tpl
It's not valid YAML and thus Nova fails to start.
> [Nova] Fix audit map

- system/unbound/templates/prometheus-alerts.yaml
Show the discovered value in the alert description/summary where it makes sense.
Also, use ```$.Release.Name``` instead of ```$.Values.unbound.name``` in order to be able to distinguish between different setups.
> [unbound] tidy up the prometheus alerts and make them more informative

- common/mysql_metrics/CHANGELOG.md
- common/mysql_metrics/Chart.yaml
- common/mysql_metrics/templates/deployment.yaml
Add reloader annotation to the sql-exporter deployment, so it will be restarted on the database secret update
> [mysql_metrics] add reloader annotation

- system/unbound/templates/config.yaml
No need to maintain a static list of AS112 zones in hosts.conf.
Let's generate as112.conf dynamically based on what has been exposed.
Each AS112 zone, global or regional, stub or forward, will have
to be explicitly exposed by having the ```expose_as112``` value set
to one of the types listed in [1], normally ```transparent``` or
```nodefault```.
[1] https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#unbound-conf-local-zone
> [unbound] getting ready to purge the AS112 zones from hosts.conf

- system/unbound/templates/config.yaml
These zones are being exposed in ```as112.conf``` if so configured now.
> [unbound] purge the RFC1918 zones from hosts.conf

- system/vmware-monitoring/Chart.yaml
- system/vmware-monitoring/templates/collector-configmap.yaml
- added vmware-hostsystem metric for custom tag `IAAS-HostGroup` on exporter configmap
> [vmware-monitoring] Expose customTag:IAAS-HostGroup

- system/metis/Chart.lock
- system/metis/Chart.yaml
Update mariadb chart to 0.23.0:
* add user-credential-updater sidecar, that can update credentials after a secret update by secrets-injector
> [metis][mariadb] update database chart dependency

- openstack/barbican/ci/test-values.yaml
- openstack/barbican/templates/seed.yaml
In an attempt to make deployment of new domains easier, @majewsky recently introduced `global.domain_seeds.customer_domains`. As this could replace the old `skip_hcm_domain`, poses the opportunity to distinguish between internal and external domains in future and accommodate other specialties we would like to suggest this on seeds of other services too.
The expressions are technically equal, only the `ora` domain was added. If it was excluded on purpose, let me know and I can change it. I excluded iaas- for now.
I ran h3 diff with dyff option against qa-de-1 and eu-de-1 you can have a look at the output here:
[barbicanQA1diff.txt](https://github.com/user-attachments/files/19487805/barbicanQA1diff.txt)
[barbicanDE1diff.txt](https://github.com/user-attachments/files/19487806/barbicanDE1diff. …
> [barbican] seed generic domains using global.domains_seeds

- common/rabbitmq/CHANGELOG.md
- common/rabbitmq/Chart.yaml
- common/rabbitmq/values.yaml
- performance improvements
- upgrades from 4.0.x and 3.13.x are supported
- rabbitmqadmin has been updated to 2.0 but is not yet included in the image
- RabbitMQ nodes now provide a Prometheus histogram for message sizes published by applications
> [rabbitmq] version bumped to 4.1.0-management

- openstack/backup-replication/templates/cronjob.yaml
- openstack/backup-replication/templates/deployment-statsd.yaml
- openstack/backup-replication/values.yaml
When deploying from an OCM bundle, we want for the image refs in the OCM bundle to take precedence over our usual mirror selection logic based on `.Values.global.registry` and friends.
I am not sure if this is a pattern that we will recommend to everyone. For now, backup-replication is our field test for OCM bundles, and we will see how this pattern feels.
> openstack/backup-replication: add .Values.image_refs

- system/greenhouse-ccloud/templates/kvm-monitoring-pluginpreset.yaml
change the namespace for the KVM monitoring plugin to use it's own namespace instead of using the kube-monitoring namespace
> greenhouse - change kvm monitoring namespace

- openstack/ironic/Chart.lock
- openstack/ironic/Chart.yaml
Bump rabbitmq, memcached and mysql-metrics chart to latest releases
> [ironic][mariadb] bump database dependency chart version

- openstack/limes-campfire/ci/test-values.yaml
- openstack/limes-campfire/templates/deployment.yaml
- openstack/limes-campfire/templates/ingress.yaml
- openstack/limes-campfire/templates/secret.yaml
- openstack/limes-campfire/values.yaml
This needs a companion PR for the pipeline, because it relies on `global:globals` values.
> [campfire] utilize global.is_global_region

- system/cc-ceph/templates/prysm-rgw-sidecar-webhook-mutating-webhook.yaml
- objectSelector added to handle only rgw deployments with label prysm-sidecar=yes/no
> [prysm-wh] objectSelector added

- openstack/keppel/templates/_utils.tpl
This is made possible by the speed improvements in sapcc/keppel#530, which do not appear to have resulted in higher DB load according to metrics.
> openstack/keppel: increase ratelimits

- common/mariadb/CHANGELOG.md
- common/mariadb/Chart.yaml
- common/mariadb/scripts/docker-entrypoint.sh
- common/mariadb/templates/deployment.yaml
- common/mariadb/templates/etc-configmap.yaml
- common/mariadb/values.yaml
* MariaDB has been updated to the 10.6.21 version
* delete removed `innodb_thread_concurrency` variable from my.cnf
See related documentation at https://mariadb.com/kb/en/upgrading-from-mariadb-10-5-to-mariadb-10-6/
The default value of the `old_mode` variable is `UTF8_IS_UTF8MB3` until MariaDB 11.2.
> [mariadb] Update database to the 10.6 release

- openstack/cronus-seed/ci/test-values.yaml
- openstack/cronus-seed/templates/seed.yaml
In an attempt to make deployment of new domains easier, @majewsky recently introduced `global.domain_seeds.customer_domains`. As this could replace the old `skip_hcm_domain`, poses the opportunity to distinguish between internal and external domains in future and accommodate other specialties we would like to suggest this on seeds of other services too.
I think the change in the below seed is small enough, that looking at diffs of various regions is not necessary.
**Please review, but don't merge.** This depends on a pipeline change that was not `fly`d yet.
> [cronus] seed generic domains using global.domain_seeds

- openstack/ironic/py/ironic-node-update.py
In ap-cn-1 the kos is running into an error because:
Error executing kos crd: ('KosQuery', 'monsoon3', 'ironic-node-update').
Error: Error executing query: generator didn't yield
So it seems that whenever kos is unable to set a node to maintenace the
kos itself fails and it then also fails to update deployments. So we
also yield in an error case.
> kos crd: always yield

- prometheus-exporters/octobus-query-exporter/Chart.lock
- prometheus-exporters/octobus-query-exporter/Chart.yaml
- prometheus-exporters/octobus-query-exporter/values.yaml
- prometheus-exporters/octobus-query-exporter/vendor/octobus-query-exporter-global/Chart.yaml
- prometheus-exporters/octobus-query-exporter/vendor/octobus-query-exporter-global/templates/_helper.tpl
- prometheus-exporters/octobus-query-exporter/vendor/octobus-query-exporter-global/templates/deployment.yaml
- prometheus-exporters/octobus-query-exporter/vendor/octobus-query-exporter-global/templates/secret.yaml
- prometheus-exporters/octobus-query-exporter/vendor/octobus-query-exporter-global/values.yaml
- prometheus-exporters/octobus-query-exporter/vendor/octobus-query-exporter/Chart.yaml
- prometheus-exporters/octobus-query-exporter/vendor/octobus-query-exporter/templates/_helper.tpl
- prometheus-exporters/octobus-query-exporter/vendor/octobus-query-exporter/templates/deployment.yaml
- prometheus-exporters/octobus-query-exporter/vendor/octobus-query-exporter/templates/secret.yaml
- prometheus-exporters/octobus-query-exporter/vendor/octobus-query-exporter/values.yaml
Reverts the change that introduced an additional header option for a failover password. Parsing multiple headers caused issues and requires a different approach.
> fix(octobus-query-exporter): Rollback secondary header support for failover password

- openstack/keystone/templates/bin/_db-sync.tpl
The script is pretty important and we must act if it fails. Otherwise we
shall live with unupgraded database for years before we find that out, and
upgrading it might be impossible.
We don't add any logic here, but rather expect keystone to fail loudly
if something goes wrong.
> Keystone: fail db-sync script if subcommands fail

- openstack/keystone/templates/etc/_secrets.conf.tpl
- openstack/keystone/values.yaml
The feature is described here - https://docs.openstack.org/keystone/latest/admin/event_notifications.html#example-notification-invalid-password-authentication.
Requires: https://github.com/sapcc/keystone/pull/31
> Keystone: Add configuration for `report_invalid_password_hash`

- openstack/nova/templates/hypervisors/hypervisors-vmware-deployment-vct.yaml
We've set the annotation on the `VCenterTemplate` instead of on the resulting `Deployment` rendered from the template and thus it never had an effect.
> [Nova] Fix vpa-butler main-container for nova-compute

- openstack/nova/Chart.lock
- openstack/nova/Chart.yaml
Bump mysql-metrics chart to 0.4.4: adds an option to set vpa main container and reloader annotation
(though will not be used in Nova)
> [nova][mariadb] bump database dependency chart version

- common/ovsdb/Chart.yaml
- common/ovsdb/templates/service.yaml
- openstack/neutron/Chart.lock
- openstack/neutron/Chart.yaml
- openstack/neutron/values.yaml
this is needed since the switch to Calico to make externalIPs accessible
from outside the cluster.
> [neutron/ovsdb] make externalTrafficPolicy configurable for Calico

- openstack/cinder/ci/test-values.yaml
- openstack/cinder/templates/seed.yaml
In an attempt to make deployment of new domains easier, @majewsky recently introduced `global.domain_seeds.customer_domains`. As this could replace the old `skip_hcm_domain`, poses the opportunity to distinguish between internal and external domains in future and accommodate other specialties we would like to suggest this on seeds of other services too.
The expressions are technically equal, only the ora domain was added to the seed. If it was excluded on purpose, let me know and I can change it. I excluded iaas- for now.
I ran h3 diff with dyff option against qa-de-1 and eu-de-1, you can have a look at the output here:
[cinderDE1diff.txt](https://github.com/user-attachments/files/19389140/cinderDE1diff.txt)
[cinderQA1diff.txt](https://github.com/user-attachments/files/19389142/cinderQA1di …
> [cinder] seed generic domains using global.domains_seeds

- openstack/keystone/Chart.lock
- openstack/keystone/Chart.yaml
Bump database dependency chart version 0.19.1 -> 0.23.0:
> [keystone][mariadb] bump database dependency chart version

- openstack/sap-seeds/ci/test-values.yaml
- openstack/sap-seeds/templates/flavor-seed.yaml
To ensure that the diff is actually useful.
> sap-seeds: write flavor seed in deterministic order

- prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/aggregations/snapmirror.yaml
Add destination_cluster label, which is just the filer where the metrics
generated from. NetApp only reports source_cluster in the snapmirror
metrics.
> [netapp-exporter] enhance snapmirror metrics

- prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/aggregations/snapmirror.yaml
the helper metrics `netapp_volume_labels:enhanced` should include the
backup targets as well, not just volumes known to manila.
> snapmirror

- prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/aggregations/maia.yaml
- prometheus-exporters/netapp-exporter/charts/netapp-metrics-federation/templates/configmap.yaml
Federating in global thanos using promquery exporter, we fetch detail info
for the snapmirror relationship from target regions. Include lag time and transfer
duration/size as well.
> [netapp-exporter][snapmirror] maia metrics with enriched labels

- system/kube-system-metal/Chart.lock
- system/kube-system-metal/Chart.yaml
- system/kube-system-metal/values.yaml
* bump reloader chart to 2.1.3
* bump secrets-injector chart to 1.1.11
* add default `reloader.image.repository` value
> [kube-system-metal][reloader] update helm chart and add default repository

- openstack/cinder/templates/cinder-nanny-lockfiles.yaml
- openstack/cinder/values.yaml
A cronjob template that executes the newly added `cinder-manage sap clean_old_lock_files`command daily. See https://github.wdf.sap.corp/cc/secrets/pull/16725 also.
> [cinder] Add new lockfile cinder nanny cronjob

- openstack/content-repo/templates/cronjob.yaml
- openstack/content-repo/templates/deployment-check.yaml
- openstack/content-repo/templates/deployment-statsd.yaml
- openstack/content-repo/values.yaml
When deploying from an OCM bundle, we want for the image refs in the OCM bundle to take precedence over our usual mirror selection logic based on `.Values.global.registry` and friends.
I am not sure if this is a pattern that we will recommend to everyone. For now, content-repo and backup-replication are our field test for OCM bundles, and we will see how this pattern feels.
cf. https://github.com/sapcc/helm-charts/pull/8575 (the same change for openstack/backup-replication)
For alpine-curl, going with `image_refs` switches the imagePullPolicy to IfNotPresent, because we are not going to use the "latest" tag there. "latest" is fundamentally incompatible with how `ocm transfer ctf --copy-resources` copies images: It will refuse to copy the current "latest" image if a different image with …
> openstack/content-repo: add .Values.image_refs

- openstack/neutron/templates/deployment-rpc-server.yaml
- openstack/neutron/templates/deployment-server.yaml
This is a needed because python OVS library fails indefinitely due to the 10s delay of linkerd's protocol detection
https://linkerd.io/2-edge/features/protocol-detection/#marking-ports-as-skip-ports
> [neutron] annotate neutron pods skip protocol detection for OVSdb

- openstack/hermes/values.yaml
Trying to fix the user credential sidecar, it shouldn't be in init containers, and is failing.
> hermes: adjust user sidecar for rabbitmq

- common/postgresql-ng/Chart.yaml
- common/postgresql-ng/values.yaml
This is the first proper image for the v2 series. A weird consequence of us holding the Dockerfile for this image inside the chart is that we needed to merge the PR with the content updates first, and then we could build the image. In hindside, #8644 should not have bumped the chart version yet...
> postgresql-ng: bump image

- openstack/cinder/Chart.lock
- openstack/cinder/Chart.yaml
Bump mysql-metrics chart to 0.4.4: adds an option to set vpa main container
and reloader annotation
> [cinder][mariadb] bump database dependency chart version

- system/plutono/Chart.lock
- system/plutono/values.yaml
The chart now supports multiple databases in the same server, which requires moving some variables around. Full changelog is in `common/postgresql-ng/Chart.yaml`. This also removes several obsolete values settings that the respective charts do not recognize anymore.
> plutono: upgrade to postgresql-ng chart 2.0.x

- openstack/archer/Chart.lock
- openstack/archer/values.yaml
The chart now supports multiple databases in the same server, which requires moving some variables around. Full changelog is in `common/postgresql-ng/Chart.yaml`. This also removes several obsolete values settings that the respective charts do not recognize anymore.
> archer: upgrade to postgresql-ng chart 2.0.x

- global/ccloud-hedgedoc/Chart.lock
- global/ccloud-hedgedoc/ci/test-values.yaml
- global/ccloud-hedgedoc/values.yaml
- openstack/castellum/values.yaml
- openstack/keppel/Chart.lock
- openstack/keppel/values.yaml
- openstack/limes/Chart.lock
- openstack/limes/values.yaml
- system/tenso/Chart.lock
- system/tenso/values.yaml
The chart now supports multiple databases in the same server, which requires moving some variables around. Full changelog is in `common/postgresql-ng/Chart.yaml`.
- The big changes on `customMetrics` are only indentation changes. I recommend to view with `?w=1`.
- This has been tested on the Castellum deployment. The one remaining change on Castellum is to remove a setting which has not been recognized by pgbackup for a long time (backup-tools enumerates databases by itself, so an explicit declaration is not necessary).
> all srs: upgrade to postgresql-ng chart 2.0.x

- openstack/designate/templates/etc/_designate-policy.yaml.tpl
Configuration of new policy `create_sub_zone_other_project` to allow zone creation in other tenants. 
Designate policy implementation: https://github.com/sapcc/designate/pull/42
> [designate] Add new policy create_sub_zone_other_project to create zone in other tenants

- openstack/cinder/Chart.lock
- openstack/cinder/Chart.yaml
- openstack/cinder/ci/test-values.yaml
- openstack/cinder/templates/_helpers.tpl
- openstack/cinder/templates/api-deployment.yaml
- openstack/cinder/templates/backup_deployment.yaml
- openstack/cinder/templates/migration-job.yaml
- openstack/cinder/templates/scheduler-deployment.yaml
- openstack/cinder/templates/vcenter_datacenter_cinder_deployment.yaml
- openstack/cinder/values.yaml
Add default values for pxc-db chart dependency
> [cinder][pxc-db] Add support for PXC galera cluster: part 1

- openstack/octavia/Chart.lock
- openstack/octavia/Chart.yaml
Bump database dependency chart version 0.19.1 -> 0.23.0:
Bump mysql-metrics chart to 0.4.4: adds reloader annotation
> [octavia][mariadb] bump database dependency chart version

- common/mariadb/CHANGELOG.md
- common/mariadb/Chart.yaml
- common/mariadb/templates/etc-configmap.yaml
* Set `max_connect_errors` option in my.cnf to maximal possible value of `4294967295`.
* Set `skip_name_resolve` option to `ON` and `host_cache_size` to 0.
This will prevent blocking database connections because of the failed monitor checks or other network issues.
See related documentation at https://mariadb.com/kb/en/server-system-variables/#max_connect_errors
> [mariadb] Set `max_connect_errors` config option to the maximum value

- system/opensearch-logs/Chart.lock
- system/opensearch-logs/Chart.yaml
- system/opensearch-logs/values.yaml
- system/opensearch-logs/vendor/prober/Chart.yaml
- system/opensearch-logs/vendor/prober/templates/probe.yaml
Adjust rollover values for datastreams to avoid undersized shards, improve shard efficiency and resource utilization
Previous: 30 GB per index (4 shards ≈ 7–8 GB per shard)
New: 80 GB per index (4 shards ≈ 20 GB per shard)
Exclude / reduce low volume / testing indexes `alerts`, `otel` and `audit`.
> chore(opensearch-logs): fine tune rollover values for datastreams

- openstack/neutron/Chart.lock
- openstack/neutron/Chart.yaml
* update mariadb chart from 0.24.0 to 0.24.1
Sets max_connection_errors options to avoid prevent blocking database connections because of the failed monitor checks or other network issues.
* update mysql-metrics chart to 0.4.4
Adds reloader annotation to sql-exporter deployment
> [neutron] update database dependencies

- openstack/designate/Chart.lock
- openstack/designate/Chart.yaml
* bump rabbitmq chart: updates rabbitmq to 4.1.0
* bump mariadb chart: updates mariadb to 10.6.21
* bump pxc-db chart: updates cluster to 1.17.0 pxc-operator release
> [designate] bump chart shared dependencies

- openstack/ironic/Chart.lock
- openstack/ironic/Chart.yaml
Updates mariadb to 10.6.21 and set max_connection_errors options to avoid prevent blocking database connections because of the failed monitor checks or other network issues
* update rabbitmq to 0.18.0
Updates RabbitMQ to 4.1.0 release
> [ironic] bump shared dependencies

- global/prometheus-alertmanager-operated/Chart.yaml
- global/prometheus-alertmanager-operated/templates/am-config-route-slack.yaml
Removed region filter `qa-de-1` for bedrock alerting channels:
- `slack_bedrock_critical`
- `slack_bedrock_warning`
- `slack_bedrock_info`
> [prometheus-alertmanager-operated] - Slack alerting for bedrock removed region filter

- prometheus-rules/prometheus-vmware-rules/Chart.yaml
- prometheus-rules/prometheus-vmware-rules/templates/prometheus-alerts.yaml
The current code just templates the expression we need to add also the label for bedrock.
Testing done:
When `bedrock: nil`, the label simply doesn't appear in Alertmanager, which is acceptable.
Can you confirm that the same behavior is implemented across all environments except `qa-de-1`?
> [prometheus-rules] - prometheus-vmware-rules | Updated template for bedrock labeling

- openstack/elektra/templates/seed.yaml
As a cloud admin, the dashboard user should be granted the `resource_service` role to allow usage of the Lime email service. The role is granted via the group CCADMIN_CLOUD_ADMINS@ccadmin.
> chore(elektra): assign resource_service role to dashboard user as cloud-admin

- openstack/placement/values.yaml
memcached v0.6.10 introduced the option to set memcached as the main container of the deployment to provide it more resources than the corresponding sidecar containers. We activate this setting.
> [placement] set memcached main container

- system/audit-logs/values.yaml
- system/audit-logs/vendor/audit-poller/values.yaml
- system/audit-logs/vendor/fluent-audit-container/templates/daemonset.yaml
- system/audit-logs/vendor/fluent-audit-container/values.yaml
- system/audit-logs/vendor/fluent-audit-systemd/templates/daemonset.yaml
- system/audit-logs/vendor/fluent-audit-systemd/templates/prometheus-alerts.yaml
- system/audit-logs/vendor/fluent-audit-systemd/values.yaml
- system/audit-logs/vendor/logstash-audit-external/templates/_logstash.conf.tpl
- system/audit-logs/vendor/logstash-audit-external/templates/configmap.yaml
- system/audit-logs/vendor/logstash-audit-external/templates/secret.yaml
- system/audit-logs/vendor/logstash-audit-external/templates/statefulset.yaml
- system/audit-logs/vendor/logstash-audit-external/values.yaml
- system/audit-logs/vendor/ocb-datain-static-probes/values.yaml
- system/auditbeat/templates/auditbeat-daemonset.yaml
- Adds affinities to the pods to disable hanging scheduling onto unready nodes.
- Adds secrets and changes default values.
> [audit-logs] Adds node affinities, default values, secret names

- openstack/manila/Chart.lock
- openstack/manila/Chart.yaml
Updates mariadb to 10.6.21 and set max_connection_errors options to avoid prevent blocking database connections because of the failed monitor checks or other network issues
Adds reloader annotation for maria-back-me-up
* update mysql-metrics to 0.4.4
Adds reloader annotation to sql-exporter deployment
* update memcached to 0.6.10
Adds option to set vpa main container
* update rabbitmq to 0.18.0
Updates RabbitMQ to 4.1.0 release
* update redis to 2.2.6
Updates valkey to 8.1.1, makes rbacs for the current namespace only, updates redis exporter to v1.72.0
> [manila] update shared dependencies

- system/sentry/Chart.lock
- system/sentry/Chart.yaml
- system/sentry/values.yaml
The chart now supports multiple databases in the same server, which requires moving some variables around. Full changelog is in `common/postgresql-ng/Chart.yaml`.
- This also removes several obsolete values settings that the respective charts do not recognize anymore.
- This removes the manual override of `postgresql.imageTag`. Manipulating this value is dangerous because the scripts in the image need to match the templates in the Helm chart. Please only use the imageTag specified by the postgresql-ng chart.
> sentry: upgrade to postgresql-ng chart 2.0.x

- openstack/neutron/templates/daemonset-metadata-agent.yaml
- openstack/neutron/templates/deployment-aci-agent.yaml
- openstack/neutron/templates/deployment-cc-fabric-agent.yaml
- openstack/neutron/templates/deployment-ironic-agent.yaml
- openstack/neutron/templates/deployment-nsxv3-logstash.yaml
- openstack/neutron/templates/deployment-ovn-northd.yaml
- openstack/neutron/templates/deployment-rpc-server.yaml
- openstack/neutron/templates/deployment-server.yaml
- openstack/neutron/templates/sftp-deployment.yaml
- openstack/neutron/templates/statefulset-network-agent-apod.yaml
- openstack/neutron/templates/statefulset-network-agent.yaml
- openstack/neutron/templates/statefulset-swift-injector.yaml
- openstack/neutron/templates/vct-nsxv3-agent-deployment.yaml
Set kubectl.kubernetes.io/default-container for all neutron related
containers. This will ease calls to exec and log.
> [neutron] set default container

- system/secrets-injector/Chart.yaml
- system/secrets-injector/values.yaml
Gardener expects webhook timeouts to be `15sec`:
```
gardener.cloud/warning: |-
ATTENTION: This webhook configuration has been modified by Gardener since it does not follow the best practices recommended by Kubernetes (https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#best-practices-and-warnings) and might interfere with the cluster operations. Please make sure to follow these recommendations to prevent future interventions. When you are done, please remove this annotation. See also https://github.com/gardener/gardener/blob/master/docs/usage/shoot/shoot_status.md#constraints for further information.
The following modifications have been made:
- timeoutSeconds of webhook "secrets-injector.cloud.sap" was set to 15
```
I would suggest to align on this …
> feat(secrets-injector): Set webhook timeout to expected gardener default

- openstack/neutron/templates/vct-nsxv3-agent-deployment.yaml
This annotation has previously been introduced in #6500. However, it was added a second time in #8750.
> [neutron][nsxv3-agent] Remove duplicate default container annotation

- system/greenhouse-ccloud/Chart.yaml
- system/greenhouse-ccloud/ci/test-values.yaml
- system/greenhouse-ccloud/templates/kube-monitoring-pluginpreset.yaml
some types of clusters do not have a common naming convention
this allows to override the region for these clusters.
> fix(greenhouse-ccloud): add region override

- openstack/elektra/templates/seed.yaml
Campfire does not look at this role anymore since #8770.
> elektra: revert cloud_resource_admin assignment

- openstack/keystone/Chart.lock
- openstack/keystone/Chart.yaml
Updates mariadb to 10.6.21 and seta max_connection_errors options to prevent blocking database connections because of the failed monitor checks or other network issues
* update mysql-metrics to 0.4.4
Adds reloader annotation to sql-exporter deployment
> [keystone] bump database dependencies

- openstack/barbican/Chart.lock
- openstack/barbican/Chart.yaml
Updates mariadb to 10.6.21 and set max_connection_errors options to avoid prevent blocking database connections because of the failed monitor checks or other network issues
* update mysql-metrics to 0.4.4
Adds reloader annotation to sql-exporter deployment
> [barbican] bump database dependencies

- openstack/utils/Chart.yaml
- openstack/utils/templates/_proxysql.tpl
Add restartPolicy option, which is enabled when the `proxysql.native_sidecar` option is set.
This would allow us to move the proxysql sidecar from the `containers` deployment section to `initContainers` and run it as a native sidecar.
> [utils][proxysql] Add restartPolicy to support native sidecar mode

- common/postgresql-ng/Chart.yaml
- common/postgresql-ng/bin/init-generate-secrets.sh
- common/redis/Chart.yaml
- common/redis/bin/init-generate-secrets.sh
The feature originally introduced in #6396 was not working properly because of the conditional always mistakenly evaluating to false.
```console
$ docker run --rm -it keppel.eu-de-1.cloud.sap/ccloud/shared-app-images/alpine-kubectl:latest-latest ash -c '[[ "true" -eq "true" ]] && echo "yes" || echo "no"'
ash: true: out of range
no
```
The issue appears to be `ash` specific.
```console
$ bash -c '[[ "true" -eq "true" ]] && echo "yes" || echo "no"'
yes
```
> postgresql, redis: fix annotateGeneratedSecrets

- openstack/kmip/Chart.yaml
- openstack/kmip/templates/deployment.yaml
Add reloader annotations to the service deployment.
This would ensure that services are restarted on the respective DB or RabbitMQ credentials update.
Annotations added:
* `secret.reloader.stakater.com/reload` - list of secrets to track
* `deployment.reloader.stakater.com/pause-period` - pause interval before deployment rollout. E.g., if we have different credentials changed within one minute, then only one restart would be triggered. This will also help with kubelet sync interval, on which the time to apply vault change depends
> [reloader][kmip] add reloader annotations

- openstack/keystone/Chart.yaml
- openstack/keystone/templates/deployment-api.yaml
- openstack/keystone/templates/deployment-cron.yaml
Add reloader annotations to the service deployments.
This would ensure that services are restarted on the respective DB or RabbitMQ credentials update.
Annotations added:
* `secret.reloader.stakater.com/reload` - list of secrets to track
* `deployment.reloader.stakater.com/pause-period` - pause interval before deployment rollout. E.g., if we have different credentials changed within one minute, then only one restart would be triggered. This will also help with kubelet sync interval, on which the time to apply vault change depends
> [reloader][keystone] add reloader annotations

- openstack/ironic/Chart.yaml
- openstack/ironic/templates/_conductor-deployment.yaml.tpl
- openstack/ironic/templates/api-deployment.yaml
- openstack/ironic/templates/inspector-deployment.yaml
Add reloader annotations to the service deployments.
This would ensure that services are restarted on the respective DB or RabbitMQ credentials update.
Annotations added:
* `secret.reloader.stakater.com/reload` - list of secrets to track
* `deployment.reloader.stakater.com/pause-period` - pause interval before deployment rollout. E.g., if we have different credentials changed within one minute, then only one restart would be triggered. This will also help with kubelet sync interval, on which the time to apply vault change depends
> [reloader][ironic] add reloader annotations

- openstack/designate/Chart.lock
- openstack/designate/Chart.yaml
- openstack/designate/templates/central-deployment.yaml
- openstack/designate/templates/mdns-deployment.yaml
- openstack/designate/templates/sink-deployment.yaml
- openstack/designate/templates/worker-deployment.yaml
- openstack/designate/values.yaml
This would ensure that proxysql container is always stopped after the main container on each deployment.
> [designate][proxysql] use native sidecars for proxysql

- common/postgresql-ng/Chart.yaml
- common/postgresql-ng/templates/rbac.yaml
- common/redis/Chart.yaml
- common/redis/templates/rbac.yaml
Follow-up for #8816.
Without `patch` it fails with:
```
Error from server (Forbidden): secrets "<release>-pguser-backup" is forbidden: User "system:serviceaccount:<release-ns>:<release>-postgresql" cannot patch resource "secrets" in API group "" in the namespace "<release-ns>"
```
`update` is added for the sake of completeness - e.g. if `kubectl` decides to switch to `update` when annotating in future, or if something else is added to the script that might require `update`.
> Update RBAC to allow annotation of Secrets

- openstack/nova/values.yaml
We usually have enough free space and it's way more important to us how much RAM/VCPUs we have free on a host than how much disk we have free.
With vastly differing disk space usage of up to 50% this has some impact.
> [Nova] Disable considering free disk during scheduling

- openstack/octavia/templates/etc/_octavia.conf.tpl
- openstack/octavia/values.yaml
Our Octavia F5 provider driver is measuring the availability of its backend (F5 devices) regularly [via a GET request to /](https://github.com/sapcc/octavia-f5-provider-driver/blob/4a82c96f8a2797a19682fbac956c811c7d665f2b/octavia_f5/restclient/bigip/bigip_restclient.py#L86) with a [default timeout of five seconds](https://github.com/sapcc/octavia-f5-provider-driver/blob/4a82c96f8a2797a19682fbac956c811c7d665f2b/octavia_f5/common/config.py#L229).
We're seeing lots of instances where devices have such high CPU load that they fail to respond within this default timeout.
Override the default timeout with a higher value (10s).
> [octavia] Add failover_timeout and raise it from default 5s to 10s

- openstack/ironic/Chart.yaml
- openstack/ironic/templates/redfish-certrobot-cronjob.yaml
- openstack/ironic/values.yaml
Add the timezone to the cronjob, so it runs everywhere at the same time.
> [ironic] add TZ to certrobot

- openstack/openstack-seeder/values.yaml
added ns: maia-global, hermes-global, cc3test-global.
> [seeder] extend ignore ns list for regional openstack-seeder

- openstack/cinder/templates/volumes/_volume-deployment.yaml.tpl
Cinder needs certain permissions to mount a volume locally (within the container). The priviledges are selectively escalated with `oslo.privsep`.
> [cinder] Add cinder permissions for mounting volumes

- openstack/octavia/Chart.yaml
- openstack/octavia/templates/octavia-api-deployment.yaml
- openstack/octavia/templates/octavia-housekeeping.yaml
- openstack/octavia/templates/octavia-worker-deployment.yaml
Add reloader annotations to the service deployments.
This would ensure that services are restarted on the respective DB or RabbitMQ credentials update.
Annotations added:
* `secret.reloader.stakater.com/reload` - list of secrets to track
* `deployment.reloader.stakater.com/pause-period` - pause interval before deployment rollout. E.g., if we have different credentials changed within one minute, then only one restart would be triggered. This will also help with kubelet sync interval, on which the time to apply vault change depends
> [reloader][octavia] add reloader annotations

- common/rabbitmq/CHANGELOG.md
- common/rabbitmq/Chart.yaml
- common/rabbitmq/values.yaml
- faster startup with empty classic queues
- classic queue compaction performance improvements
> [rabbitmq] version bumped to 4.1.1-management

- system/surveyor/Chart.lock
- system/surveyor/Chart.yaml
- system/surveyor/ci/test-values.yaml
- system/surveyor/templates/_utils.tpl
- system/surveyor/templates/configmap.yaml
- system/surveyor/templates/deployment-frontend.yaml
- system/surveyor/templates/deployment-worker.yaml
- system/surveyor/templates/ingress-frontend.yaml
- system/surveyor/templates/pvc-cache.yaml
- system/surveyor/templates/secret.yaml
- system/surveyor/templates/service-frontend.yaml
- system/surveyor/values.yaml
Ironically, Surveyor is not deployed as an OCM bundle for now, because that would require making changes to all the PostgreSQL subcharts. Those have not been done, and will not be done until we have fully settled on how we propagate image versions through the OCM bundles.
> system/surveyor: init

- system/opensearch-logs/Chart.yaml
- system/opensearch-logs/alerts/opensearch.alerts
This will currently fire in eu-de-1 as the problem was present there last week. We can create a silence for the affected indices until they are deleted (~1 month)
> [opensearch-logs] add alert if a index rollover failed

- system/gatekeeper/templates/constrainttemplate-pod-security.yaml
- system/greenhouse-ccloud/templates/logs-pluginpreset.yaml
- system/logs/Chart.lock
- system/logs/Chart.yaml
- system/logs/templates/external-service.yaml
- system/logs/templates/opentelemetry-logs-collector.yaml
- system/logs/values.yaml
- This is necessary so the reference to the upstream chart becomes more clear.
- Also includes a change of a gatekeeper policy for OTel
> [logs] fix naming for operator to align be align with upstream chart

- system/gatekeeper/templates/constrainttemplate-pod-security.yaml
- system/gatekeeper/tests/gatekeeper-policies/fixtures/pod-security/cinder-volume-kvm-stnpca2-st051.yaml
- system/gatekeeper/tests/gatekeeper-policies/fixtures/pod-security/cinder-volume-netapp.yaml
Change the volume pod detection regex and add required capability to cinder volume-pods.
Include tests
> Change gatekeeper policy to allow kvm, netapp deployments

- system/gatekeeper/templates/constrainttemplate-pod-security.yaml
This was not needed as the operator name is a combination of `<namespace>` and `operator`
> [gatekeeper] revert changes introduced in #9006

- openstack/designate/values.yaml
- return back the tempest/performance-testing project to the whitelist
> [designate] enable rate limiting by default

- openstack/manila/Chart.lock
- openstack/manila/Chart.yaml
- openstack/manila/templates/api-deployment.yaml
- openstack/manila/templates/migration-job.yaml
- openstack/manila/templates/scheduler-deployment.yaml
- openstack/manila/templates/shares/_netapp-deployment.yaml.tpl
- openstack/manila/templates/shares/_netapp-ensure-deployment.yaml.tpl
- openstack/manila/values.yaml
Update openstack/utils helm chart to 0.27.0 version with native sidecar support for proxysql
> [manila][proxysql] use native sidecars for proxysql

- openstack/manila/templates/migration-job.yaml
The current openstack/utils sidecar option enables restartPolicy=Always for all proxysql sidecars within a chart, so not only deployments but jobs also needs to be modified.
> [manila][proxysql] fix migration-job proxysql sidecar configuration

- openstack/cinder/templates/cinder-nanny-quota-sync.yaml
- openstack/cinder/values.yaml
Cinder nannies are moved into the cinder helm chart. The helm chart executes the sap quota_sync command which is a wrapper of the openstack cinder-manage quota sync command. The old nanny quota_sync command executed a non-open stack custom script.
> [cinder] Add quota sync nanny helm chart

- openstack/octavia/templates/etc/_octavia-worker.conf.tpl
This is needed for any rSeries worker activations.
> [octavia] worker configmap: Set vcmp_series flag for rSeries models

- system/absent-metrics-operator/Chart.yaml
- system/absent-metrics-operator/ci/test-values.yaml
- system/absent-metrics-operator/templates/deployment.yaml
- system/absent-metrics-operator/values.yaml
updating registry to ghcr to deprecate concourse build pipeline for absent metrics operator
> [absent-metrics-operator] update registry to ghcr

- common/rabbitmq/CHANGELOG.md
- common/rabbitmq/Chart.yaml
- common/rabbitmq/templates/certificate.yaml
- common/rabbitmq/values.yaml
The common name could become too long and isn't needed. We use a different clusterissuer resource in the group certmanager.cloud.sap instead of cert-manager.io
> [rabbitmq] Fix certificate for ssl mode

- openstack/netapp-credential-rotator/templates/secrets.yaml
> [netapp-credential-rotator] remove resolve functions for secrets

- openstack/cinder/templates/volumes/volumes.yaml
The volumes template loop was not giving the iteration of the loop a newline, so when it printed out the next ConfigMap entry it put the --- on the end of the previous line, making an invalid deployment for the first pass through the loop.
> [Cinder] fix volumes template loop

- openstack/neutron/Chart.lock
- openstack/neutron/Chart.yaml
- openstack/neutron/values.yaml
This only enables it on the rabbitmq server,
but not the clients.
> [neutron] Enable ssl for rabbitmq

- openstack/ironic/Chart.lock
- openstack/ironic/Chart.yaml
- openstack/ironic/templates/_conductor-deployment.yaml.tpl
- openstack/ironic/templates/api-deployment.yaml
- openstack/ironic/templates/inspector-conductor-deployment.yaml
- openstack/ironic/templates/inspector-deployment.yaml
- openstack/ironic/values.yaml
> [ironic][proxysql] use native sidecars for proxysql

- openstack/designate/templates/etc/_designate.conf.tpl
- if there is a connection problem or 5xx error code we will retry 20 times for 10 seconds.
> [designate] use the option to retry on connection errors to Keystone

- common/rabbitmq/CHANGELOG.md
- common/rabbitmq/Chart.yaml
- common/rabbitmq/templates/certificate.yaml
Our certificate provider doesn't support these IPs, so that part never worked. If you want to add them still, you can do that explicitly by adding them via `certificate.ipAddresses`
> [common/rabbitmq] No externalIPs in certificates

- openstack/designate/templates/etc/_designate.conf.tpl
- because for large DNS zones the client will use a lot of API requests if not specifing the limit explicitely to be more than default 20.
- this becomes a problem with rate limiting enabled and large DNS zones holding 1000s of records as the rate limiting budget runs out quickly.
> [desginate] increase default_limit_v2 from 20 to 200.

- openstack/manila/templates/shares/_helpers.tpl
- openstack/manila/templates/shares/_netapp-deployment.yaml.tpl
- openstack/manila/templates/shares/_netapp-ensure-deployment.yaml.tpl
Include credential for remote filers, which are needed for replica
related operations.
> [manila] fix backend secrets

- openstack/manila/templates/shares/_helpers.tpl
In case multiple share services run on same filer, we need to create
different var names.
> [manila] fix env variable name

- openstack/nova/alerts/openstack/nova.alerts
Adding OpenstackNovaLiveMigrationError warning alert, based on the openstack_compute_errored_live_migration_gauge metric.
> [nova] add alert for errored live migrations

- openstack/nova/Chart.lock
- openstack/nova/Chart.yaml
- Bump mysql_metrics chart 0.4.4 to 0.5.0
- Bump sql-exporter 0.5.9 to 0.6.0
- Add new optional `connections` value for multiple database targets
- Remove unused `customSources` value
> [nova] Bump chart dependencies

- openstack/keystone/Chart.yaml
- openstack/keystone/templates/bin/_db-sync.tpl
Don't fail on the warning in the Keystone db upgrade check
https://docs.openstack.org/keystone/latest/cli/keystone-status.html#categories-and-commands
>At least one check encountered an issue and requires further investigation. This is considered a warning but the upgrade may be OK.
> [keystone] don't fail on warning in db upgrade check

- openstack/nova/Chart.lock
- openstack/nova/Chart.yaml
- Bump mariadb chart 0.24.2 to 0.25.0:
- Bump mariadb 10.6.22 to 10.11.13
- Bump mysqld-exporter 0.17.1 to 0.17.2
> [nova] Bump mariadb

- openstack/utils/Chart.yaml
- openstack/utils/templates/_proxysql.tpl
Revert https://github.com/sapcc/helm-charts/pull/9097
This reverts commit https://github.com/sapcc/helm-charts/commit/4de4d1f342b4c956b9912bc405359c15d7fb2137.
Unfortunately, it's still better to have pkill proxysql, when proxysql is a native sidecar, because of the following jobs' behaviour when linkerd is enabled and it is not a native sidecar:
1. The main job container finishes and sends a shutdown signal to linkerd-proxy
2. Linkerd has `config.linkerd.io/shutdown-grace-period` with a default 120s
3. Linkerd stops responding to liveness/readiness checks after shutdown
4. ProxySQL continues to run, because the non-native sidecar linkerd-proxy is still running
5. After 30 seconds, the liveness check causes linkerd-proxy sidecar container to be marked as dead _and restarts it_
6. The job …
> Revert "[utils][proxysql] don't use pkill if proxysql is a native sidecar"

- openstack/designate/Chart.lock
- openstack/designate/Chart.yaml
* Upgrades MariaDB to 10.11.13
* Upgrades RabbitMQ to 4.1.1
* Upgrades sql-exporter to 0.6 2025-06-10
> [designate] bump shared chart dependencies

- system/opensearch-logs/Chart.yaml
- system/opensearch-logs/alerts/opensearch.alerts
Previously the alert message printed out the index multiple times (for each shard). This reduces the message to one line per index.
> [opensearch-logs]: refactor indexsize alert

- common/prometheus-server/Chart.yaml
- common/prometheus-server/values.yaml
- prometheus-rules/prometheus-kubernetes-rules/Chart.yaml
- prometheus-rules/prometheus-kubernetes-rules/alerts/pod.alerts.tpl.disabled
This PR adds `container_threads` metric to prometheus-server and adds a new alert `ContainerHighNumberOfThreads` -- with info criticality as it is newly added.
> [prometheus-kubernetes-rules] add ContainerHighNumberOfThreads 

- openstack/octavia/values.yaml
Adding a helper metric `octavia_listeners` to expose `listener_name` and `loadbalancer_name` labels.
This is required to enrich Maia load balancing metrics with listener name and loadbalancer name, requested by BTP to ease filtering within their monitoring system.
Code contributed by @BenjaminLudwigSAP
> [octavia] Add listeners SQL metric

- openstack/nova-hypervisor-agents/templates/_kvm-configmap.yaml.tpl
- openstack/nova-hypervisor-agents/templates/hypervisors-kvm-daemonset.yaml
The labels cannot be changed on daemonset without re-rereating it, so it requires a manual step.
The labels and configmap are now (hopefully) chosen in a way that two releases can run in parallel, such as having one for qemu and another for cloudhypervisor.
> [nova-hypervisor-agents] Breaking change to allow multiple release

- openstack/nova-hypervisor-agents/templates/hypervisors-kvm-daemonset.yaml
The 'untyped' hostpath doesn't do any checks. The ones with type do, and should give the operator clearer indications of what went wrong.
> [nova-hypervisor-agents] Annotate hostpaths with type for better errors

- openstack/tempest/manila-tempest/templates/bin/_tempest-functions.sh.tpl
- openstack/tempest/manila-tempest/templates/bin/_tempest-start-and-cleanup.sh.tpl
- openstack/tempest/manila-tempest/templates/configmap-bin-tempest.yaml
From antelope, Share networks may have multiple subnets. The share
network can be deleted when there is only one subnet.
> [manila-tempest] cleanup subnets before deleting share networks

- openstack/nova/alerts/openstack/vmware-rebalancer.alerts
Consuming the newly introduced metrics from VMware Rebalancer, this change set will alert somebody to take action when VCs run critically low on resources.
> [nova][vmware-rebalancer] introduce alert for (almost) full vCenters

- prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/aggregations/castellum.yaml
Use `max()` instead of `sum()` to select the labels.
> [netapp-exporter] fix castellum rules

- openstack/neutron/templates/etc/_neutron.conf.tpl
- Without this setting all reverse zones created when providing dns options for floating IPs are created with default "hostmaster@example.com" e-mail address.
> [neutron] set ptr_zone_email for reverse zones created by Neutron

- openstack/nova/Chart.lock
- openstack/nova/Chart.yaml
The certificate CRD in the prior release contained external ips, which the certificate provider didn't accept. The change does not pull in new versions of rabbitmq, so is non-disruptive by itself.
> [nova] Bump rabbitmq to fix certificate

- global/andromeda/templates/etc/_liquid-policy.json.tpl
This is being added by sapcc/go-bits#239. I will also do the respective code change in Andromeda once the go-bits PR is merged, but this is safe to apply right away.
> global/andromeda: add policy rule for liquid:change_commitments

- system/liquid-ceph/templates/configmap.yaml
This is being added by sapcc/go-bits#239. I can assist with the code change that is necessary in liquid-ceph, once the go-bits PR is merged, but this is safe to apply right away.
> system/liquid-ceph: add policy rule for liquid:change_commitments

- prometheus-rules/prometheus-vmware-rules/Chart.yaml
- prometheus-rules/prometheus-vmware-rules/templates/_helper.tpl
Switch from vSphere tags to VMware hostgroups for Bedrock host identification
Replaced the use of `vrops_hostsystem_vsphere_tags ` with `vrops_hostsystem_hostgroups ` as the primary identifier for Bedrock hosts, aligning with affinity rule usage in Nova. Tags were previously managed manually, which posed a risk of incomplete or inconsistent host coverage.
> [prometheus-vmware-alerting] - improvement of bedrock alerting 

- openstack/nova-hypervisor-agents/bin/nova-compute-init
- openstack/nova-hypervisor-agents/templates/hypervisors-kvm-daemonset.yaml
All hosts have been migrated. This eliminates the need to have an api call during startup, which is another error source and requires the api to be up before creating compute nodes.
> [nova-hypervisor-agents] Only support predictable hash

- openstack/neutron/Chart.lock
- openstack/neutron/Chart.yaml
The certificate CRD in the prior release contained external ips, which the certificate provider didn't accept, and a wrong issuer name.
The change does not pull in new versions of rabbitmq, so is non-disruptive by itself.
> [neutron] Bump rabbitmq to fix certificate

- common/mariadb/CHANGELOG.md
- common/mariadb/Chart.yaml
- common/mariadb/templates/etc-configmap.yaml
- common/mariadb/values.yaml
* MariaDB `userstat` plugin is enabled
* mysqld-exporter now collects user statistics
> [mariadb] collect user statistics

- openstack/nova-hypervisor-agents/ci/test-values.yaml
- openstack/nova-hypervisor-agents/templates/_helpers.tpl
- openstack/nova-hypervisor-agents/templates/etc-secret.yaml
The nova chart uses dual-user password rotation and has a couple of helpers defined to accommodate that. We copy the helpers over to be able to consume Nova's values the same way to define the transport_url for rabbitmq.
> [nova-hypervisor-agents] Support Nova's password rotation

- system/ldap-named-user/Chart.yaml
- system/ldap-named-user/templates/secret.yaml
- system/ldap-named-user/values.yaml
The default for the services is moved to the values.yaml and includes
nss, pam and ssh. In case no services should be started or only being
socket activated then these values need to be set to an empty list,
i.e.:
```
sssd:
startServices: []
```
> [ldap-named-user] make sssd services configurable via values

- openstack/keppel/values.yaml
We don't do anything with slower queries and it just spams the log.
> openstack/keppel: increase log_min_duration_statement

- common/rabbitmq/CHANGELOG.md
- common/rabbitmq/Chart.yaml
- common/rabbitmq/values.yaml
> [rabbitmq] version bumped to 4.1.2-management

- openstack/utils/Chart.yaml
- openstack/utils/proxysql_sidecar.md
- openstack/utils/templates/_proxysql.tpl
Add support for setting max_transaction_time and default_query_timeout variables to default large values, which can be used in Jobs, in which some transactions or queries might run longer than 60-120s.
For example, it might be useful for some ALTER TABLE queries.
> [utils][proxysql] add support for unlimited transactions time in jobs

- system/kube-monitoring-admin-k3s/Chart.lock
- system/kube-monitoring-admin-k3s/Chart.yaml
- system/kube-monitoring-kubernikus/Chart.lock
- system/kube-monitoring-kubernikus/Chart.yaml
- system/kube-monitoring-virtual/Chart.lock
- system/kube-monitoring-virtual/Chart.yaml
We removed an obsolete alerting on quota from the `kubernikus-monitoring` chart.
> [kube-monitoring-*] bump kubernikus-monitoring

- openstack/cinder/alerts/openstack-cinder.alerts
We add a new Prometheus alert that fires when Nova nanny cronjobs are continuously failing or not completing.
> [cinder] Add nanny failure alert

- openstack/designate/Chart.lock
- openstack/designate/Chart.yaml
* pxc-db: 0.4.0 -> 0.4.1
Fixes linkerd annotations and backups
* mariadb: 0.25.0 -> 0.26.1
Updates maria-back-me-up, sets default-container annotations, enables userstat metrics
* mysql-metrics: 0.5.0 -> 0.5.2
Updates sql-exporter version to 0.8.0 (2025-07-07)
* rabbitmq: 0.18.4 -> 0.18.5
Updates RabbitMQ from 4.1.1 to 4.1.2
> [designate] bump shared dependencies

- openstack/keystone/Chart.lock
- openstack/keystone/Chart.yaml
- openstack/keystone/templates/deployment-api.yaml
- openstack/keystone/templates/deployment-cron.yaml
- openstack/keystone/templates/job-bootstrap.yaml
- openstack/keystone/templates/job-migration.yaml
- openstack/keystone/values.yaml
Update openstack/utils helm chart to 0.27.2 version with native sidecar support for proxysql
> [keystone][proxysql] use native sidecars for proxysql

- openstack/nova/templates/console-mks-secret.yaml
- openstack/nova/templates/console-shellinabox-secret.yaml
- openstack/nova/templates/etc-secret.yaml
- openstack/nova/templates/etc/_api-db.conf.tpl
- openstack/nova/templates/etc/_cell0.conf.tpl
- openstack/nova/templates/etc/_cell1.conf.tpl
- openstack/nova/templates/etc/_cell2.conf.tpl
- openstack/nova/templates/etc/_keystoneauth-secrets.conf.tpl
- openstack/nova/templates/etc/_nova-api-metadata-secrets.conf.tpl
Switch nova Secret templates from stringData to data attribute to resolve Vault secrets-injector compatibility issues. Using stringData is broken by design as removing keys from stringData does not remove them from data.
> nova: switch Secret templates from stringData to data with base64

- openstack/castellum/files/policy.yaml
Ref: https://github.com/sapcc/castellum/pull/353
The naming of `nsf-shares-types` is the more correct one of both naming schemes.
> fix policy for share types

- openstack/nova/templates/api-metadata-deployment.yaml
- openstack/nova/templates/api-metadata-secret.yaml
- openstack/nova/templates/etc-secret.yaml
- openstack/nova/templates/etc/_nova-api-metadata-secrets.conf.tpl
nova-api-metadata pods will automatically restart through reloader, when the newly-introduce nova-api-metadata k8s Secret changes. This Secret contains the shared metadata secret Neutron also knows.
It should be safe to restart nova-api-metadata on Vault secret change, because it's a multi-replica service. Changing MariaDB/RabbitMQ secrets requires an explicit rollout, so these wouldn't be picked up with the restart. The only change it could pick, is Keystone credentials, but those won't change for a while and even then switch to application credentials and by that should support old/new dual-credentials like with MariaDB/RabbitMQ and what we try to build here.
We also support setting multiple secrets here, because Nova gets support for that in our fork. This enables smoother secret …
> [Nova] api-metadata multi-secret with auto-restart

- openstack/limes/values.yaml
I tested all the SQLs manually. This is to fix the alert on `limes_project_resources_by_type_count`, because this is old and new projects were created in the meantime.
> [limes] fix alert metric definitions for DB schema v2

- openstack/neutron/templates/configmap-bin.yaml
- openstack/neutron/templates/configmap-etc-api.yaml
- openstack/neutron/templates/configmap-etc-apod.yaml
- openstack/neutron/templates/configmap-etc-cc-fabric.yaml
- openstack/neutron/templates/configmap-etc-vendor.yaml
- openstack/neutron/templates/configmap-etc.yaml
- openstack/neutron/templates/deployment-aci-agent.yaml
- openstack/neutron/templates/deployment-cc-fabric-agent.yaml
- openstack/neutron/templates/deployment-nsxv3-logstash.yaml
- openstack/neutron/templates/deployment-rpc-server.yaml
- openstack/neutron/templates/deployment-server.yaml
- openstack/neutron/templates/ingress-server.yaml
- openstack/neutron/templates/prometheus-alerts.yaml
- openstack/neutron/templates/sentry.yaml
- openstack/neutron/templates/service-nsxv3-logstash.yaml
- openstack/neutron/templates/service-server.yaml
- openstack/neutron/templates/sftp-deployment.yaml
This patch ensures a more consistent format of the neutron manifests, removing redundant whitespace.
> [neutron] remove redundant whitespace in templates

- openstack/nova/Chart.lock
- openstack/nova/Chart.yaml
* Updates RabbitMQ version to 4.1.2
* Updates user-credential-updater sidecar image:
* underscore in user key bugfix
* fixes MEDIUM CVEs in the image
> [nova][rabbitmq] bump rabbitmq chart dependency

- common/mariadb/CHANGELOG.md
- common/mariadb/Chart.yaml
- common/mariadb/ci/test-values.yaml
- common/mariadb/templates/initdb/_init.sql.tpl
* Added an option to drop the database user using the values configuration
Example:
```yaml
mariadb:
users:
test:
enabled: false
```
This will result in the `test` user being dropped from the MariaDB.
> [mariadb] add and option to disable a user

- common/rabbitmq/CHANGELOG.md
- common/rabbitmq/Chart.yaml
- common/rabbitmq/templates/_helpers.tpl
- common/rabbitmq/templates/certificate.yaml
Without setting the commonName to something, the first DNS name is used, which may be too long. By setting it to a shortened version, we cover the issue that the certificate may not be provisioned due to a overly long common name.
> [rabbitmq] Limit default common name to 64 chars

- openstack/nova/Chart.lock
- openstack/nova/Chart.yaml
The old chart was not specifying the commonName,
and it defaulted to the first dns-name, which could get too long. The new chart shortens it in these
circumstances.
> [nova] Bump rabbitmq to fix too long CommonName

- openstack/cinder/Chart.lock
- openstack/cinder/Chart.yaml
- openstack/cinder/templates/api-deployment.yaml
- openstack/cinder/templates/backup_deployment.yaml
- openstack/cinder/templates/cinder-nanny-consistency.yaml
- openstack/cinder/templates/cinder-nanny-db-purge.yaml
- openstack/cinder/templates/cinder-nanny-lockfiles.yaml
- openstack/cinder/templates/cinder-nanny-quota-sync.yaml
- openstack/cinder/templates/migration-job.yaml
- openstack/cinder/templates/scheduler-deployment.yaml
- openstack/cinder/templates/vcenter_datacenter_cinder_deployment.yaml
- openstack/cinder/templates/volumes/_volume-deployment.yaml.tpl
- openstack/cinder/values.yaml
Update openstack/utils helm chart to 0.27.2 version with native sidecar support for proxysql
> [cinder][proxysql] use native sidecars for proxysql

- openstack/utils/Chart.yaml
- openstack/utils/templates/snippets/_proxysql.cfg.tpl
Skip database users in ProxySQL configuration:
* with `password` value set to `null`
* with `enabled` value set to `false`
Examples:
```yaml
mariadb:
users:
test:
password: null
```
```yaml
mariadb:
users:
test:
password: secret
enabled: false
```
Currently, in MariaDB chart we don't create users with `null` password, but utils/proxysql chart doesn't support this and causes template failure.
This change fixes this problem and adds two ways to remove a user from ProxySQL config.
> [utils][proxysql] skip disabled database users and null password

- openstack/octavia/values.yaml
This fixes #9432
Turns out, the values need to use the subchart alias, which in this case for `redis` is `api-ratelimit-redis`, as defined in Chart.yaml
I was able to reproduce the templating error locally and check that this fix works.
> [octavia] Fix values.yaml: Subchart values not using subchart alias

- prometheus-rules/prometheus-vmware-rules/Chart.yaml
- prometheus-rules/prometheus-vmware-rules/alerts/vccluster.alerts
VCClusterFailoverHostCountMismatch alert is added by extending the existing VCenterWrongHALevelConfiguration alert.
> [prometheus-vmware-rules] Add VCClusterFailoverHostCountMismatch alert

- prometheus-rules/prometheus-kubernetes-rules/Chart.yaml
- prometheus-rules/prometheus-kubernetes-rules/alerts/kubelet.alerts.tpl
Latest conclusion is that these alerts do not bring any benefit:
- each app performance should have its own monitoring
- if the node is down, it's down and we have another alert for that
> [prometheus-kubernetes-rules] rm goroutines alerts

- common/pgbackup/Chart.yaml
- common/pgbackup/templates/prometheus-alerts.yaml
- common/postgresql-ng/Chart.yaml
- common/postgresql-ng/templates/prometheus-alerts.yaml
- common/redis/Chart.yaml
- common/redis/templates/prometheus-alerts.yaml
- openstack/backup-replication/alerts/backup-replication.alerts
- openstack/billing/templates/prometheus-alerts.yaml
- openstack/castellum/alerts/openstack/errors.alerts
- openstack/content-repo/alerts/content-repo.alerts
- openstack/keppel/alerts/openstack/api.alerts
- openstack/keppel/alerts/openstack/roleassignment.alerts
- openstack/limes/alerts/openstack/api.alerts
- openstack/limes/templates/prometheus-alerts.yaml
- openstack/swift/alerts/openstack/api.alerts
- openstack/swift/templates/prometheus-alerts.yaml
This is split from #9446 because that PR has an extremely large set of code owners, so merging it seems very unlikely. This commit touches only the alerts that my workgroup can approve.
Also, #9446 missed several playbook links in our charts.
Also also, clean up some irrelevant changelog entries in library charts. (The changelogs there are only for significant changes, not every random bugfix.)
> all srs: switch playbook links to absolute URLs

- openstack/manila/values.yaml
Due to table schema changes in the manila database, the `share_servers`
table does not have the `share_network_subnet_id` column. Instead, the
mappings are done via the `share_server_share_network_subnet_mappings`
table.
> [manila] fix: SQL metrics with share server and share network

- system/greenhouse-ccloud/Chart.yaml
- system/greenhouse-ccloud/templates/kvm-monitoring-pluginpreset.yaml
Added `support_group`: `kvm` to prometheus.AlertLabels to match slack routing.
**Old Slack channels:**
- `#alert-kvm-test`
**Slack channels:**
- `#alert-kvm-info`
- `#alert-kvm-warning`
- `#alert-kvm-critical`
Ref. https://github.com/sapcc/helm-charts/pull/9453
> [greenhouse-ccloud] - Updated kvm-monitoring pluginpreset with kvm support_group 

- openstack/cinder/templates/api-deployment.yaml
- openstack/cinder/templates/etc/_api-paste.ini.tpl
- openstack/cinder/templates/secret-cinder-ratelimit.yml
- openstack/cinder/values.yaml
The Redis helm chart enforces the access via a password. If no password is set, a random pw is created by container start automatically.
So far the openstack-ratelimit middleware does not support connecting to a Redis backend with a password set. Requires https://github.com/sapcc/openstack-rate-limit-middleware/pull/29 The middleware loads the backend password from a file. With this PR we mount the Redis password into the neutron-server so it will be picked up by the ratelimit middleware.
reference:
https://github.com/sapcc/helm-charts/pull/8408
> [Cinder] Support password ratelimit backend

- openstack/octavia/values.yaml
This PR fixes default Octavia's rate-limits:
- use `read` instead of `read/limit` for sibgle-obejct requests
- add rate-limit for `create` to correct level of API
- add `stats`, `status` and `failover` rate-limits
- rename `write` group to `delete_or_update` for better debugging
> Fix default rate-limits for Octavia API

- openstack/cinder/alerts/kubernetes/cinder.alerts
- openstack/cinder/alerts/openstack/cinder.alerts
- openstack/cinder/templates/prometheus-alerts.yaml
- openstack/cinder/values.yaml
Added subdirectories to cinder/alerts directory that correspond to the respective prometheus instance. E.g. Alerts in cinder/alerts/kubernetes use the kubernetes prometheus instance.
> [cinder] Make nanny alerts report to correct prometheus instance

- system/bind/templates/config.yaml
It was missing the closing bracket.
> [bind] fix the catalog-zones directive

- openstack/octavia/templates/octavia-api-deployment.yaml
- openstack/octavia/templates/octavia-f5-as3-deployment.yaml
- openstack/octavia/templates/octavia-housekeeping.yaml
- openstack/octavia/templates/octavia-migration-job.yaml
- openstack/octavia/templates/octavia-worker-deployment.yaml
The value of the `kubectl.kubernetes.io/default-container` annotation is the container name that is default for the Pod. It will be picked up by commands such as `kubectl logs` or `kubectl exec` if no `-c/--container` flag is specified.
Ref: https://kubernetes.io/docs/reference/labels-annotations-taints/#kubectl-kubernetes-io-default-container
> [octavia] add default-container annotation to all pods

- openstack/octavia/Chart.lock
- openstack/octavia/Chart.yaml
- openstack/octavia/ci/test-values.yaml
- openstack/octavia/templates/octavia-api-deployment.yaml
- openstack/octavia/templates/octavia-housekeeping.yaml
- openstack/octavia/templates/octavia-migration-job.yaml
- openstack/octavia/templates/octavia-worker-deployment.yaml
- openstack/octavia/values.yaml
Update openstack/utils helm chart to 0.27.2 version with native sidecar support for proxysql
> [octavia][proxysql] use native sidecars for proxysql

- openstack/octavia/Chart.lock
- openstack/octavia/Chart.yaml
* Updates MariaDB to 10.11.14
* Updates RabbitMQ to 4.1.3
* Updates memcached to 1.6.39
* Updates maria-back-me-up to 2025-07-22
* Updates sql-exporter to 0.8.0 (2025-07-07)
* Updates utils chart
> [octavia] bump shared chart dependencies

- .github/CODEOWNERS
We introduce this chart to begin the replacement of the ns-exporter.
> [neutron-netns-prober] update codeowners

- prometheus-exporters/neutron-netns-prober/templates/daemonset.yaml
- prometheus-exporters/neutron-netns-prober/templates/secret.yaml
Adding the user to the secret facilitates the rotation of credentials.
> neutron-netns-prober: add username to secret

- openstack/keppel/templates/daemonset-keep-image-pulled.yaml
- openstack/swift/templates/keep-image-pulled-daemonset.yaml
While we were chatting about the resource crunch in qa-de-1, I noticed that our keep-image-pulled daemonsets allow autoscaling, which in this case means autowasting resources. This is not a problem in QA because we do not deploy those there at all, but let's try not wasting prod resources, too.
> keppel/swift: do not autoscale keep-image-pulled daemonsets

- openstack/keystone/templates/daemonset-keep-image-pulled.yaml
In a discussion about the ongoing resource crunch in qa-de-1, we noticed that getting rid of the keep-image-pulled daemonsets can be a quick win, since we do not have the same strict availability requirement as for prod there. (We already did the same for Keppel and Swift years ago for similar reasons.)
> keystone: skip keep-image-pulled in QA, do not autoscale in prod

- openstack/nova/Chart.lock
- openstack/nova/Chart.yaml
Bump shared dependencies to allow MariaDB and RabbitMQ deletion.
* Bump mariadb chart to 0.27.1
- updates mariadb to 10.11.14
- updates maria-back-me-up
- enables userstat metrics `mysql_info_schema_user_statistics_*`
* Bump rabbitmq chart to 0.19.1
- updates rabbitmq to 4.1.3
* Bump utils chart to 0.29.0
- add an option to remove deleted user from proxysql sidecar config
> [nova] bump shared dependencies to allow db and rabbit user deletion

- openstack/placement/Chart.lock
- openstack/placement/Chart.yaml
* Bump mariadb chart to 0.27.1
- updates mariadb to 10.11.14
- updates maria-back-me-up
- enables userstat metrics `mysql_info_schema_user_statistics_*`
* Bump utils chart to 0.29.0
- add an option to remove deleted user from proxysql sidecar config
> [Placement] Bump shared dependencies to allow db user deletion

- openstack/barbican/Chart.lock
- openstack/barbican/Chart.yaml
* Updates MariaDB to 10.11.14
* Updates sql-exporter to 2025-07-07
* Updates memcached to 1.6.39
> [barbican] update shared chart dependencies

- common/mariadb/CHANGELOG.md
- common/mariadb/Chart.yaml
- common/mariadb/templates/initdb/_init.sql.tpl
Add missing secret resolve, so the generated comment would contain actual username instead of the vault reference
> [mariadb] add missing secret resolve in drop comment line

- openstack/designate/templates/seeds.yaml
We introduced a  new OpenStack rule for zone backups -- this commit assigns it to the service user.
> [designate] assign new openstack role to the nanny service user

- openstack/kmip/Chart.yaml
- openstack/kmip/templates/etc/_kmip-server.conf.tpl
Change database_path in kmip to use credentials actually configured on `kmip-mariadb` MariaDB instance.
This would make password rotation possible, because now we will reference the same secrets in two places, where secret is supposed to be the same.
> [kmip] use mariadb kmip credentials for kmip service configuration

- openstack/neutron/ci/test-values.yaml
- openstack/neutron/templates/seed.yaml
In an attempt to make deployment of new domains easier, @majewsky recently introduced `global.domain_seeds.customer_domains`. As this could replace the old `skip_hcm_domain`, poses the opportunity to distinguish between internal and external domains in future and accommodate other specialties we would like to suggest this on seeds of other services too.
The expressions are technically equal, only the `ora` domain was added. If it was excluded on purpose, let me know and I can change it. I excluded iaas- for now.
I ran h3 diff with dyff option against qa-de-1 and eu-de-1 you can have a look at the output here:
[neutronQA1diff.txt](https://github.com/user-attachments/files/19488580/neutronQA1diff.txt)
[neutronDE1diff.txt](https://github.com/user-attachments/files/19488581/neutronDE1diff.txt) …
> [neutron] seed generic domains using global.domain_seeds

- global/concourse-main/values.yaml
fixes false alerts when a remote branch is not found
> Bump git-proxy image

- openstack/nova/values.yaml
We added code into the vmwareapi driver that allows us to check the host more thoroughly in https://github.com/sapcc/nova/pull/578
> [Nova] Remove CpuInfoMigrationFilter

- openstack/nova/Chart.yaml
- openstack/nova/values.yaml
* Disable `monitoring` user in nova's RabbitMQ, as this read-only user isn't being used
* Remove obsolete `metrics.sidecar` values
> [nova][rabbitmq] don't create unused monitoring user

- openstack/nova/templates/etc-secret.yaml
When switching from stringData to data in 8844453cf19, we in some regions also rolled out the change to move
nova-api-metadata-secrets.conf to its own Secret. This left stale data in the clusters, because you cannot remove keys via removing them from stringData - and since we didn't add it to `data`, it also couldn't get removed there.
Therefore, we now temporarily add the `nova-api-metadata-secrets.conf` key back with some garbage value. It's not consumed by anyone anyways. We will remove it again after we rolled this through all regions.
> [Nova] Temporarily add key back to nova-etc Secret

- prometheus-exporters/network-generic-ssh-exporter/alerts/asr.alerts
This alert is applicable to firmware versions prior to 17.15.x. In version 17.6.3, the metric is used to verify the NAT port chunks downloaded to the data plane. At router bootup, 45K ports were immediately downloaded from the Port-Manager.
From version 17.15.x onward, NAT requests all 45K ports from the Port-Manager, but the ports are downloaded to the data plane only when traffic requires them.
This alert applies only to Neutron routers running firmware version 17.6.3.
> Updating NAT port allocation alert

- openstack/cinder/alerts/kubernetes/cinder.alerts
Alerts adjusted to only alert on db-purge, lock-files and quota-sync nannies. Consistency nanny is excluded as it runs on a different schedule (weekly). There is no extra alert required for the consistency nanny because it mostly logs stuff, is not important for platform operation and it may get deprecated.
> [cinder] Make cinder nanny alerts more explicit

- openstack/nova/values.yaml
This filter prevents resizes with too large volumes into other shards for projects having the `restrict-resize-by-volume-size` tag.
> [Nova] Enable VolumeSizeSameShardResizeFilter

- common/rabbitmq/CHANGELOG.md
- common/rabbitmq/Chart.yaml
- common/rabbitmq/values.yaml
- RabbitMQ updated to `4.1.4` version
- `rabbitmq-user-credential-updater` updated to `20250904100127` version
- Chart version bumped
> [rabbitmq] update to 4.1.4 release

- openstack/placement/Chart.yaml
- openstack/placement/ci/test-values.yaml
- openstack/placement/templates/_helpers.tpl
- openstack/placement/templates/db-migrate-job.yaml
- openstack/placement/templates/db-online-migrate-job.yaml
- openstack/placement/templates/etc/_secrets.conf.tpl
- openstack/placement/templates/placement-api-deployment.yaml
- openstack/placement/values.yaml
Use a custom helper template function to create db connection URL.
Currently, placement chart can utilize only `.Values.mariadb` values, including `.Values.mariadb.name`
This PR makes it possible to use another map for db url configuration, which might help to create a separate database using values like `.Values.mariadb` while keeping an old configuration with `.Values.mariadb_nova_api`
> [placement] use custom helper function for db url

- prometheus-rules/prometheus-vmware-rules/Chart.yaml
- prometheus-rules/prometheus-vmware-rules/alerts-scaleout-ruler/host.alerts
updated host in maintenance mode for 10 days to exclude host with less than 60 minutes uptime to remove some false positive that would come from a reinstall avec a break and fix intervention
> updated hostinmaintenacemode alert

- openstack/manila/aggregates/openstack/castellum.rules
Part of the fix for INC15375812.
Once this is deployed in all prod regions, https://github.com/sapcc/castellum/pull/361 may be merged and deployed.
> manila: ensure that the Castellum exclusion-reasons metric is populated

- system/greenhouse-ccloud/Chart.yaml
- system/greenhouse-ccloud/ci/test-values.yaml
- system/greenhouse-ccloud/templates/cert-manager-pluginpreset.yaml
- system/greenhouse-ccloud/templates/digicert-issuer-pluginpreset.yaml
- system/greenhouse-ccloud/templates/disco-plugins.yaml
- system/greenhouse-ccloud/templates/ingress-plugins.yaml
with kube 1.33 we need to temporarily add certain controller deployed in kube-system on shoot clusters to network policies, so that they can reach the apiserver. mid-term the plugins will be move to another namespace
requires #9689 & #9688
> feat(gh-ccloud): enable setting gardener netpo labels on controller

- openstack/nova/templates/console-shellinabox-deployment.yaml
- openstack/nova/values.yaml
As bitnami/openresty is going away we are switching to the official openresty image from docker hub.
> [console-shellinabox] switch to openresty/openresty image

- system/logs/Chart.lock
- system/logs/Chart.yaml
- system/logs/templates/alerts/_otel-alerts.tpl
This pull request adds an alert that will notify devs if the exporting of logs is failing below 90% in a 1h timeframe. 
TODO: add playbook
> [logs] export failed alert for otel logs

- prometheus-exporters/octobus-query-exporter/Chart.lock
- prometheus-exporters/octobus-query-exporter/Chart.yaml
- prometheus-exporters/opensearch-logs-query-exporter/Chart.lock
- prometheus-exporters/opensearch-logs-query-exporter/Chart.yaml
- prometheus-exporters/snmp-exporter/Chart.lock
- prometheus-exporters/snmp-exporter/Chart.yaml
- system/audit-logs/Chart.lock
- system/audit-logs/Chart.yaml
- system/jupyter-cron-reports/Chart.lock
- system/jupyter-cron-reports/Chart.yaml
- system/jupyterhub/Chart.lock
- system/jupyterhub/Chart.yaml
- system/logs/Chart.lock
- system/logs/Chart.yaml
- system/opensearch-logs/Chart.lock
- system/opensearch-logs/Chart.yaml
switching to linkerd 1.1.1 to ensure pulling our own kubectl image (instead of bitnami)
see here: https://github.com/sapcc/helm-charts/pull/7317
> fix(dependencies): update deps for log services using outdated linkerd chart

- prometheus-exporters/netapp-exporter/charts/netapp-harvest-exporter/aggregations/maia.yaml
This metrics provide a overview to customers of the extra snapshot
usages, in additional to manila snapshots, i.e., backend snapshots
created for snapmirror relationships.
> [manila] maia metrics for snapshot size induced by snapmirror relationships

- global/percona_cluster/Chart.yaml
- global/percona_cluster/templates/bin/_entrypoint.sh.tpl
Set `safe_to_bootstrap: 1` even when cluster member is already a primary
when PXC_FORCE_BOOTSTRAP is set
> [percona-cluster] make force recovery option to work for primary

- global/thanos-global/Chart.yaml
- global/thanos-global/values.yaml
global pods should be killed once stepping over limits to avoid scheduling issues
> fix(thanos): fix endpoint and put limits to resources

- .github/CODEOWNERS
With the helm requirements change, i need many more code owners to potentially approve prs.
> [hermes/maia] add more codeowners

- openstack/nova-hypervisor-agents/templates/_helpers.tpl
this is needed since the index.html uses relatives paths to request
dependencies, but the link (...cell1/serial?token=bla) would resolve to
`cell1/depndency.css` instead of `cell1/serial/dependency.css`, breaking
the ingress path rule.
> [nova-hypervisor-agents] serial-console: add slash to the end

- global/percona_cluster/Chart.yaml
- global/percona_cluster/templates/bin/_livenessprobe.sh.tpl
- global/percona_cluster/templates/config-map_startup-scripts.yaml
- global/percona_cluster/templates/statefulset.yaml
Add pxc-operator-based liveness probe script with timeout check, which uses monitor credentials and can be bypassed if needed with created `/var/lib/mysql/sleep-forever` file
> [percona-cluster] add custom liveness probe script

- global/thanos-global/Chart.yaml
- global/thanos-global/values.yaml
- system/thanos-metal/Chart.yaml
- system/thanos-metal/values.yaml
- system/thanos-scaleout/Chart.yaml
- system/thanos-scaleout/values.yaml
distributed query should be turned on everywhere
turn off thanos query engine because it would only show last 6h of data
> chore(thanos): unify thanos settings

- openstack/nova/Chart.lock
- openstack/nova/Chart.yaml
- openstack/nova/values.yaml
Update redis chart dependency to version 2.2.18:
* Updates valkey to 8.1.4 with CVE fixes
> [nova][redis] Bump redis chart dependency to 2.2.18

- openstack/neutron/Chart.lock
- openstack/neutron/Chart.yaml
Bump redis for CVE-2025-49844. I also had a noop-linkerd-chart lying around and included that in an extra commit.
Superseeds #9847 which uses 2.2.18 (thanks though for directly creating a PR @s10 ).
> Neutron bump redis for CVE (and linkerd)

- system/thanos-metal/Chart.yaml
- system/thanos-metal/values.yaml
- system/thanos-scaleout/Chart.yaml
- system/thanos-scaleout/values.yaml
all overarching Queries are profitting of the distribution setting. Having overlapping enabled, they shall work as expected
> chore(thanos): enable distribution for overarching queries
