- system/prometheus/charts/prometheus-alertmanager/templates/config.yaml
- system/prometheus/charts/prometheus-collector/templates/config.yaml
> Prometheus alertmanager

- openstack/elektra/charts/postgres/templates/backup-configmap.yaml
- openstack/elektra/charts/postgres/templates/deployment.yaml
- openstack/elektra/charts/postgres/templates/service.yaml
- openstack/elektra/charts/postgres/values.yaml
See Topic.
@BugRoger can you lease review this and the secret repo?
Thanks, Josef
> Create backup option for elektra - postgres *review need*

- openstack/monasca/templates/etc/monasca-agent/conf.d/_prometheus.yaml.tpl
> import Prometheus metrics for Swift into Monasca

- openstack/grafana-author
- openstack/grafana-dev
to keep deployment script simple
> Add grafana-author and grafana-dev as links to grafana 

- openstack/lyra/charts/postgresql/templates/deployment.yaml
- openstack/lyra/charts/postgresql/values.yaml
@databus23 can you please review and merge?
> Add lyra backup

- system/sentry/charts/postgresql/templates/deployment.yaml
- system/sentry/charts/postgresql/values.yaml
@databus23 can you please review and merge?
> Add sentry backup

- openstack/arc/charts/postgresql/templates/deployment.yaml
- openstack/arc/charts/postgresql/values.yaml
@databus23 can you please review and merge?
> Add arc backup

- openstack/content-repo/templates/configmap.yaml
- openstack/content-repo/values.yaml
* Add option to specify number of worker threads per repo
* Remove optional region name
> Content-Repo: Add worker thread option for swift-http-import

- global/prometheus/values.yaml
- system/kube-monitoring/charts/prometheus-collector/prometheus.yaml
- system/kube-monitoring/charts/prometheus-collector/values.yaml
- system/kube-monitoring/charts/prometheus-frontend/values.yaml
Already happily running in staging. Looks good to merge @majewsky?
/cc @BugRoger
> Prometheus v1.5.0

- openstack/content-repo/templates/configmap.yaml
- openstack/content-repo/templates/deployment.yaml
- openstack/content-repo/templates/service.yaml
- openstack/content-repo/values.yaml
- system/kube-monitoring/charts/prometheus-frontend/templates/config.yaml
As always, your feedback regarding conventions and naming is highly appreciated
> Statsd metrics for content-repo

- openstack/content-repo/templates/_utils.tpl
- openstack/content-repo/templates/job.yaml
- openstack/content-repo/values.yaml
* Pod spec is reused across jon and scheduledjob definition
> Remove code duplication

- global/prometheus/values.yaml
- system/kube-monitoring/charts/prometheus-collector/values.yaml
- system/kube-monitoring/charts/prometheus-frontend/values.yaml
Another bugfix release of prometheus. Will test tomorrow in staging, merge the PR and helm upgrade if it's happy.
Any objections @majewsky?
> prometheus v1.5.2

- system/kube-monitoring/charts/prometheus-frontend/kubernetes.alerts
Need to merge the playbook before this PR.
Besides, fine this way @majewsky?
> NodeNotReady is critical and added playbook

- global/prometheus/prometheus.rules
- system/kube-monitoring/charts/prometheus-frontend/kubernetes.alerts
> [WIP] Tuning kube monitoring

- openstack/backup-replication/.helmignore
- openstack/backup-replication/Chart.yaml
- openstack/backup-replication/templates/_from.env.tpl
- openstack/backup-replication/templates/_helpers.tpl
- openstack/backup-replication/templates/_to.env.tpl
- openstack/backup-replication/templates/deployment.yaml
- openstack/backup-replication/templates/replica-configmap.yaml
- openstack/backup-replication/values.yaml
Adds a helm chart for backup-replication that replicate backups across the regions.
> Add backup-replication

- common/postgresql/values.yaml
@databus23 check please the changes and merge asap :)
> set dabase dimension name as all other pg metrics. Added unit bytes to the metric name.

- common/postgresql/values.yaml
- openstack/arc/charts/postgresql/values.yaml
- openstack/elektra/charts/postgresql/values.yaml
- openstack/lyra/charts/postgresql/values.yaml
- system/sentry/charts/postgresql/values.yaml
- system/sentry/values.yaml
this fix close a bug with the backup
@reimannf @databus23
> URGENT: update default backup version to v0.5.5

- system/kube-monitoring/charts/prometheus-frontend/templates/_kubernetes.alerts.tpl
> add NodeDiskPressure, NodeMemoryPressure alerts

- openstack/elektra/templates/deployment.yaml
- openstack/elektra/values.yaml
> add env variables need for two factor authentication

- openstack/monasca/templates/bin/_wall-e-start.tpl
- openstack/monasca/templates/bin/util/_create-kibana-audit-indexes.sh.tpl
- openstack/monasca/templates/bin/util/_elasticsearch-test.py.tpl
- openstack/monasca/templates/etc/monasca-agent/conf.d/_prometheus.yaml.tpl
- openstack/monasca/templates/etc/monasca-agent/conf.d/_vcenter.yaml.tpl
- openstack/monasca/templates/etc/monasca-health/_healthcheck.conf.tpl
- openstack/monasca/templates/monasca-agent-deployment.yaml
- openstack/monasca/templates/monasca-agent-etc-configmap.yaml
- openstack/monasca/templates/monasca-es-client-deployment.yaml
- openstack/monasca/templates/monasca-es-data-petset.yaml
- openstack/monasca/templates/monasca-es-master-deployment.yaml
- openstack/monasca/templates/monasca-fluent-daemonset.yaml
- openstack/monasca/templates/monasca-wall-e-bin-configmap.yaml
- openstack/monasca/templates/monasca-wall-e-deployment.yaml
- openstack/monasca/values.yaml
* change canaries to use statsd instead of the wildcard exporter
* vcenter metrics in monasca agent
* monasca canary relalerting to region channel
* automatically create audit-* indexes in kibana via wall-e
> Monasca agent

- openstack/content-repo/templates/_utils.tpl
- openstack/content-repo/templates/configmap.yaml
- openstack/content-repo/values.yaml
New options for swift-http-import:
* except
* only
* immutable
Some naming clean ups.
> Repo cleanup

- global/prometheus-alertmanager/templates/config.yaml
- global/prometheus-alertmanager/values.yaml
will test after lunch before merging
> prometheus alertmanager v0.6.0

- openstack/swift/templates/etc/_nginx.conf.tpl
* add http_version 1.1 to avoid buffering for chunked transfer encodings
* set X-Forwarded- headers
> [swift] nginx tuning

- openstack/monasca/templates/etc/monasca-agent/conf.d/_prometheus.yaml.tpl
@thgrs 
Hi Thomas,
Please review the dimensions for networking-dvs.
> Adding networking-dvs metrics

- system/kube-monitoring/charts/prometheus-frontend/automation.alerts
- system/kube-monitoring/charts/prometheus-frontend/designate.alerts
- system/kube-monitoring/charts/prometheus-frontend/elektra.alerts
- system/kube-monitoring/charts/prometheus-frontend/limes.alerts
- system/kube-monitoring/charts/prometheus-frontend/templates/config.yaml
hi @auhlig - can you please have a look and lets add the corresponding routing then tomorrow ...
> add automation and elektra alerts to prometheus

- openstack/elektra/templates/seed.yaml
@ruvr syntax question: do I really have to always repeat the project?
> [elektra] make dashboard user real cloud admin

- openstack/maia/templates/prometheus-config.yaml
- openstack/maia/values.yaml
Prometheus v1.7.1 allows discovering and scraping nova instances. Do we want to try that @thgrs @Kuckkuck @jobrs?
/cc @Carthaca
> Maia prometheus openstack sd

- openstack/limes/files/policy.json
- openstack/limes/templates/seed.yaml
@reimannf Please roll out after https://github.com/sapcc/openstack-helm/commit/69bd719a206faad13833c307a2d28ce4c4a9845b has made it into all regions.
@ruvr FYI
> define cloud_resource_viewer role

- openstack/billing/templates/seeds.yaml
@ruvr can you have a final look?
> cloud_resource_viewer for billing service user

- openstack/lyra/templates/seed.yaml
@databus23 is that something for you? @ruvr`s seeder supports now swift container meta data.
> seed temp_url key for automation-artifacts swift container

- system/kube-system/charts/ingress/templates/ingress-controller-deployment.yaml
As discussed @databus23.
If this looks in general good to you, I would test in staging, before merging.
> ing ctrl deployment instead of ds

- system/kube-monitoring/charts/prometheus-collector/templates/deployment.yaml
- system/kube-monitoring/charts/prometheus-frontend/templates/deployment.yaml
- system/kube-monitoring/charts/prometheus-frontend/templates/pvc.yaml
- system/kube-monitoring/charts/prometheus-frontend/values.yaml
As simple as this? Ok to test in staging?
Please **do not merge** yet.
> prometheus frontend as deployment

- system/kube-monitoring/charts/prometheus-frontend/openstack-cinder.alerts
@auhlig 
Please review the Cinder Alert definition and help in configuring the cinder alerts to openstack-cinder channel to slack.
> Creating OpenstackCinderVolumeStuck Alert

- openstack/maia/templates/maia-service.yaml
- openstack/maia/templates/prometheus-service.yaml
- openstack/maia/values.yaml
- system/kube-monitoring/charts/prometheus-frontend/templates/config.yaml
* update to maia image with scrape endpoint
* enable discovery of maia and prometheus components
* enable federation of maia_.* metrics to prometheus-frontend
> Maia instrumentation

- system/kube-monitoring/charts/kube-state-metrics/values.yaml
- system/kube-monitoring/charts/prometheus-frontend/templates/_kubernetes.alerts.tpl
- system/kube-monitoring/charts/prometheus-frontend/templates/_node.alerts.tpl
Will merge and roll out to staging tomorrow
> update kube-state-metrics to v1.0.0

- openstack/swift/templates/caretaker-configmap.yaml
- openstack/swift/templates/seeds.yaml
- openstack/swift/values.yaml
Must be merged with adopted values file
> seed swift-account-caretaker user

- openstack/swift/templates/caretaker-configmap.yaml
- openstack/swift/templates/etc/_dispersion.conf.tpl
- openstack/swift/templates/seeds.yaml
- openstack/swift/values.yaml
Merge after value files are adopted
> Remove usage of test_admin

- openstack/backup-replication/templates/deployment.yaml
> Add checksum for backup-replication

- system/kube-monitoring/charts/prometheus-frontend/openstack-cinder.alerts
@auhlig @fwiesel 
Please validate the alert and approve accordingly.
Regards,
Rajiv
> Adding OpenstackCinderVolumeDetach & OpenstackCinderVolumeAttach Metrics

- openstack/maia/templates/snmp-exporter-service.yaml
- openstack/maia/templates/vcenter-exporter-service.yaml
* use other scrape label for Maia exporters
> Disentangle kubemon maia

- system/kube-monitoring/charts/prometheus-frontend/openstack-nova.alerts
@auhlig @Carthaca 
Please validate the OpenstackNovaInstanceStuck alerts.
> Adding OpenstackNovaInstanceStuck alerts

- system/kube-monitoring/charts/prometheus-frontend/openstack-cinder.alerts
- system/kube-monitoring/charts/prometheus-frontend/openstack-nova.alerts
@Carthaca 
Please validate the alerts meta label.
> Adding meta label to cinder, nova alerts

- system/kube-monitoring/charts/prometheus-frontend/openstack-manila.alerts
- system/kube-monitoring/charts/prometheus-frontend/templates/config.yaml
adding alert routing for manila stuck shares
> adding alert routing for manila stuck shares

- system/kube-monitoring/values.yaml
Test in staging before merging this
> it shall be prom/prometheus:v1.7.2

- openstack/elk/templates/etc/_fluent.conf.tpl
- openstack/elk/templates/etc/_pattern.tpl
Take that grok, also brain was flushed
> Swift grok pattern

- global/prometheus/templates/_prometheus.yaml.tpl
- system/kube-monitoring/charts/prometheus-frontend/aggregation.rules
Hi @auhlig 
Could you please validate and approve.
> Adding openstack_compute_instances metric to prometheus-global

- openstack/swift/bin/swift-start
- openstack/swift/templates/_utils.tpl
- openstack/swift/templates/account-caretaker-collect-daemonset.yaml
- openstack/swift/templates/account-caretaker-mergify-deployment.yaml
- openstack/swift/templates/object-expirer-deployment.yaml
- openstack/swift/templates/proxy-deployment.yaml
- openstack/swift/templates/rsyncd-daemonset.yaml
- openstack/swift/values.yaml
Merge this when the dust has settled after the image migration.
> swift: remove Kolla cruft

- global/prometheus/templates/_prometheus.yaml.tpl
- system/kube-monitoring/charts/prometheus-frontend/aggregation.rules
Hi @auhlig 
Hope this fits better ?
> Adding openstack_compute_instances_total metric

- openstack/swift/bin/swift-start
See rationale in sapcc/swift#2.
> swift: start to replace busybox-syslogd with syslog-stdout

- openstack/content-repo/templates/_utils.tpl
Can we discuss about this. still searching for an inline replacement for this...
> Repo - allow to switch only selected repos into debug

- .gitignore
- system/kube-monitoring/charts/node-exporter/templates/daemonset.yaml
- system/kube-monitoring/charts/ntp-exporter/templates/daemonset.yaml
- system/kube-system/charts/container-linux-update-orchestrator/Chart.yaml
- system/kube-system/charts/container-linux-update-orchestrator/templates/update-agent.yaml
- system/kube-system/charts/node-problem-detector/Chart.yaml
- system/kube-system/charts/node-problem-detector/templates/daemonset.yaml
- system/kube-system/charts/sysctl/templates/sysctl_ds.yaml
daemonsets need tolerations in kube 1.7 else they will not deploy on tainted nodes
> Kube17 ds tolerations

- openstack/hermes/templates/etc/_log4j2.properties.tpl
- openstack/hermes/templates/etc/_logstash.conf.tpl
- openstack/hermes/templates/logstash-deployment.yaml
- openstack/hermes/values.yaml
have hermes-logstash poll nova audit events
> Hermes nova

- openstack/cinder-db-purge/.helmignore
- openstack/cinder-db-purge/Chart.yaml
- openstack/cinder-db-purge/templates/bin/_cinder-db-purge-start.tpl
- openstack/cinder-db-purge/templates/bin/_cinder-db-purge.tpl
- openstack/cinder-db-purge/templates/cinder-db-purge-bin-configmap.yaml
- openstack/cinder-db-purge/templates/cinder-db-purge-deployment.yaml
- openstack/cinder-db-purge/values.yaml
- openstack/nova-db-purge/.helmignore
- openstack/nova-db-purge/Chart.yaml
- openstack/nova-db-purge/templates/bin/_nova-db-purge-start.tpl
- openstack/nova-db-purge/templates/bin/_nova-db-purge.tpl
- openstack/nova-db-purge/templates/nova-db-purge-bin-configmap.yaml
- openstack/nova-db-purge/templates/nova-db-purge-deployment.yaml
- openstack/nova-db-purge/values.yaml
add purging of "marked as deleted" entries in nova and cinder
> Nova db purge

- openstack/blackbox/charts/blackbox-tests-canary/templates/_project-canary-seed.yaml
- openstack/blackbox/charts/blackbox-tests-datapath/templates/_project-datapath-seed.yaml
- openstack/blackbox/charts/blackbox-tests-regression/templates/_project-regression-seed.yaml
grant audit_viewer rights to the test_admin, so that changes can be inspected easily
> cc3test: audit_viewer rights for test_admin

- openstack/designate/templates/seeds.yaml
> designate-seed: added remaining designate relevant seeds

- system/kube-monitoring/charts/prometheus-frontend/openstack-limes.alerts
WIP - Will merge tomorrow when the code change is in prod.
> Limes: add alerts for failed project/domain discovery

- openstack/neutron/templates/etc/_neutron-policy.json.tpl
from member to compute_admin or network_admin
> [neutron] move permission for security group mgmt

- openstack/elektra/templates/ingress.yaml
- openstack/elektra/values.yaml
> probe elektra

- openstack/manila/values.yaml
Hi @Carthaca 
Could you please validate the metric.
Regards,
Rajiv
> Adding openstack_manila_snapshot_stuck metric

- openstack/manila/values.yaml
Hi @Carthaca 
Please validate the query & Approve, i will update the grafana dashboard next.
Regards,
Rajiv
> Adding Host label to openstack_manila_shares metric

- openstack/barbican/templates/seed.yaml
- openstack/barbican/values.yaml
Hi @Carthaca 
I have added barbican seeds file, please validate. helm template --values (>>>>) doesnt show any error message.
> [Barbican] Adding file seeds.yaml

- openstack/lyra/templates/db-pruner.yaml
- openstack/lyra/templates/runs-pruning.yaml
- openstack/lyra/values.yaml
We need a sort of cron job to run a cleanup task and remove old automation runs.
> Added chart to run the lyra runs cleanup task

- system/kube-system/charts/ingress/templates/ingress-controller-deployment.yaml
- system/kube-system/charts/ingress/values.yaml
upgrade the ingress ctrl next week. will test in staging beforehand.
> ingress controller 0.10.2

- openstack/billing/templates/seeds.yaml
- openstack/billing/values.yaml
- openstack/domain-seeds/templates/domain-cc3test-seed.yaml
- openstack/domain-seeds/templates/domain-cc3test2-seed.yaml
- openstack/domain-seeds/values.yaml
@artherd42  @majewsky maybe you can add your changes (if there are any) so we can do the flip in a consistent manner on staging ASAP?
> relocate the cc3test domain and support CAM provided test users

- openstack/glance/Chart.yaml
- openstack/glance/requirements.lock
- openstack/glance/requirements.yaml
- openstack/glance/templates/_helpers.tpl
- openstack/glance/templates/bin-configmap.yaml
- openstack/glance/templates/db-init-configmap.yaml
- openstack/glance/templates/db-maintain-configmap.yaml
- openstack/glance/templates/deployment.yaml
- openstack/glance/templates/etc-configmap.yaml
- openstack/glance/templates/etc/_glance-api.conf.tpl
- openstack/glance/templates/etc/_glance-registry.conf.tpl
- openstack/glance/templates/etc/_swift-store.conf.tpl
- openstack/glance/templates/ingress.yaml
- openstack/glance/templates/migration-job.yaml
- openstack/glance/templates/pvc.yaml
- openstack/glance/templates/seed.yaml
- openstack/glance/templates/seeds.yaml
- openstack/glance/templates/sentry.yaml
- openstack/glance/templates/service.yaml
- openstack/glance/values.yaml
Hi @Carthaca 
Time to move glance to helm-charts now.
I am not sure if https://github.com/rajivmucheli/helm-charts/blob/fa00ceb3cd794db2e49d8683009ae4927228d4e6/openstack/glance/templates/seed.yaml#L29 is correct? since this is not reachable.
Please validate & comment.
Regards,
Rajiv
> [Glance] moving to helm-charts

- openstack/hermes/Chart.yaml
- openstack/hermes/templates/elasticsearch-deployment.yaml
init null annotation not working, will fix manually across regions, and issue should be solved. tested.
> remove null annotation

- openstack/neutron/templates/seed.yaml
@abattye @martink2 Could you please have a look if this makes any sense at all?
> added support team neutron role assignments

- openstack/glance/templates/nanny-deployment.yaml
- openstack/manila/requirements.lock
- openstack/manila/requirements.yaml
- openstack/manila/templates/api-deployment.yaml
- openstack/manila/templates/etc-configmap.yaml
- openstack/manila/templates/etc/_api-paste.ini.tpl
- openstack/manila/templates/etc/_manila.conf.tpl
- openstack/manila/templates/etc/_manila_audit_map.yaml
- openstack/manila/values.yaml
- openstack/neutron/values.yaml
* brings audit trail to to Manila
* activated via another PR in cc/secrets
> Audit manila

- openstack/neutron/templates/agents/deployment-network_agents.yaml
- openstack/neutron/templates/daemonset-network_agents.yaml
- openstack/neutron/values.yaml
added neutron agent daemonset as region configurable option (should not break anything without region-specific additions)
> Neutron agent daemonset

- openstack/limes/templates/support_seed.yaml
- Adding resource_admin to the supprt team projects
- Inherit resource_viewer for all domains
> Limes support team seed

- openstack/manila/templates/seeds.yaml
inspired by https://github.com/sapcc/helm-charts/commit/613ea6684d94e3e5b716d5aafc1313528efeeea8
@ruvr okay?
> [manila] added support team role assignments

- system/kube-monitoring/charts/blackbox-exporter/templates/_blackbox.yaml.tpl
- system/kube-monitoring/charts/blackbox-exporter/templates/configmap.yaml
- system/kube-monitoring/charts/blackbox-exporter/templates/deployment.yaml
- system/kube-monitoring/charts/prometheus-collector/templates/_prometheus.yaml.tpl
Hi @auhlig 
Please validate the http_manila_ca module, i am not sure how i need to link the cert.
> Adding http_ca module to help probe static targets

- openstack/hermes/templates/keystone-seed.yaml
Added information for hermes support roles. Once merged I will deploy to staging, and look at the seeder pod logs to see if there are any issues.
@ruvr Would you mind looking this over? Thanks.
> Hermes support roles

- system/kube-monitoring/values.yaml
https://ci.global.cloud.sap/teams/main/pipelines/kube-monitoring/jobs/validate/builds/754
> [kube-monitoring]: fixes build issue missing value

- openstack/hermes/templates/elasticsearch-deployment.yaml
- openstack/hermes/templates/logstash-deployment.yaml
- system/kube-monitoring/charts/prometheus-frontend/templates/config.yaml
> Hermes logstash exporter

- openstack/manila/templates/api-deployment.yaml
- openstack/manila/templates/etc-configmap.yaml
- openstack/manila/templates/etc/_api-paste.ini.tpl
- openstack/manila/templates/etc/_watcher.yaml.tpl
- openstack/manila/values.yaml
> add openstack-watcher-middleware to manila. disabled by default.

- openstack/hermes/requirements.lock
- openstack/hermes/requirements.yaml
- openstack/hermes/values.yaml
Add hermes rabbitmq for smaller services to use for auditing
> Hermes rabbitmq

- openstack/neutron/templates/bin/_neutron-server-start.tpl
- openstack/neutron/templates/configmap-etc.yaml
- openstack/neutron/templates/etc/_api-paste.ini.tpl
- openstack/neutron/templates/etc/_watcher.yaml.tpl
- openstack/neutron/values.yaml
> add openstack-watcher-middleware to neutron. disabled by default.

- openstack/swift/templates/etc/_proxy-server.conf.tpl
- openstack/swift/values.yaml
> [swift] enable watcher on all clusters by default

- system/kube-monitoring/charts/prometheus-frontend/baremetal-sensor.alerts
- system/kube-monitoring/charts/prometheus-frontend/openstack-ironic.alerts
Not sure if those alerts belong here. Need feedback. Thanks!
> [kube-monitoring] adds hw ipmi sensor alerts

- global/prometheus-alertmanager/slack.tmpl
- global/prometheus-alertmanager/templates/config.yaml
- global/prometheus-alertmanager/templates/deployment.yaml
- global/prometheus-alertmanager/templates/service.yaml
- global/prometheus-alertmanager/values.yaml
needs testing due to some breaking changes in alertmanager. added new grouping of playbook, grafana, etc. links to slack template
> upgrade alertmanager to v0.15.1

- openstack/domain-seeds/templates/domain-ccadmin-seed.yaml
- openstack/ironic/templates/seed.yaml
creates project used for spawning vendor konsoles
lcxa flavor
> baremetal monitoring flavor and project creation

- global/prometheus-alertmanager/templates/deployment.yaml
- global/prometheus-alertmanager/templates/pvc.yaml
- global/prometheus-alertmanager/values.yaml
- avoids forgetting silences
- reloads config on change using sidecar
- increase am-cluster timeouts
> adds persistence for silences to am and configmap reload sidecar

- openstack/glance/templates/etc/_glance-policy.json.tpl
https://docs.openstack.org/glance/latest/admin/interoperable-image-import.html
> Enable image import

- system/kube-monitoring/charts/prometheus-frontend/openstack-limes.alerts
Alert for FailedCapacityScrapes
> [kube-monitoring][limes] FailedCapacityScrapes

- openstack/designate/templates/seeds.yaml
Hi Rudolf, as we discussed, here is the designate seed.
> Added seed for domains with dns_ops and dns_support roles

- openstack/octobus/.helmignore
- openstack/octobus/Chart.yaml
- openstack/octobus/README.md
- openstack/octobus/templates/_helpers.tpl
- openstack/octobus/templates/seeds.yaml
- openstack/octobus/values.yaml
I have added the [helm chart](https://github.com/businessbean/helm-charts/tree/master/openstack/octobus) for Octobus and i have a few questions.
- Which requirements [do i have to maintain](https://github.com/businessbean/helm-charts/blob/master/openstack/octobus/templates/seeds.yaml#L11)
- As of now we expose no services. What does it mean for the [services section](https://github.com/businessbean/helm-charts/blob/master/openstack/octobus/templates/seeds.yaml#L18)?
- How should we define the needed initial quotas?
- Can we preconfigure the Kubernikus deployment?
- Can we preconfigure DNS zones?
> add OctoBus project seed

- system/kube-monitoring/charts/prometheus-frontend/openstack-backup.alerts
See: https://github.com/sapcc/helm-charts/pull/414
> [backup-replication] update alerts

- global/prometheus-alertmanager/templates/config.yaml
- global/prometheus-alertmanager/values.yaml
Reverts sapcc/helm-charts#454
theres a wrong indentation somewhere -.-
> Revert "Rework alertmanager routing"

- global/prometheus-alertmanager/templates/config.yaml
> rework alertmanager routing

- openstack/octobus/templates/seeds.yaml
- [User role](https://github.com/businessbean/helm-charts/blob/master/openstack/octobus/templates/seeds.yaml#L64)
- [Group role #1](https://github.com/businessbean/helm-charts/blob/master/openstack/octobus/templates/seeds.yaml#L94)
- [Group role #2](https://github.com/businessbean/helm-charts/blob/master/openstack/octobus/templates/seeds.yaml#L118)
> [octobus] Added automation permission to roles

- global/prometheus-alertmanager/slack.tmpl
- global/prometheus-alertmanager/templates/config.yaml
- global/prometheus-alertmanager/values.yaml
> step 1: interactive alerts for staging

- global/prometheus-alertmanager/templates/config.yaml
- system/kube-monitoring/charts/prometheus-frontend/concourse.alerts
Hi @auhlig please advise if this makes sense or can be improved.
> Add inital alerts für concourse

- openstack/swift/templates/seeds.yaml
> remove unnecessary swiftreseller role assignments

- openstack/nova/values.yaml
> [nova] adds dbUser to globals. Fixes pgmetrics auth error!

- openstack/vcenter-utilities/templates/vasa-exporter-configmap.yaml
- openstack/vcenter-utilities/templates/vasa-exporter-deployment.yaml
- openstack/vcenter-utilities/templates/vasa-exporter-service.yaml
- openstack/vcenter-utilities/values.yaml
> vc operator for vasa

- common/postgresql/templates/etc/_pg_hba.conf.tpl
- common/postgresql/templates/etc/_postgresql.conf.tpl
- common/postgresql/values.yaml
Postgres
* use image with required plugins
* enable logical write-ahead logging
* permit WAL consumers to connect and consume WAL segments
Open Issues
> *WIP* Enable Debezium Change-Data-Capture on Postgres and MariaDB

- openstack/maia/templates/_snmp-exporter-f5.yaml.tpl
Added metrics for memory utilization.
> Updated config for F5 metrics

- openstack/grafana-new/templates/_ldap.toml.tpl
- openstack/grafana-new/values.yaml
- openstack/grafana/templates/_ldap.toml.tpl
- openstack/grafana/values.yaml
see https://issues.wdf.sap.corp/browse/CCM-8184
> grafana: introduce dedicated editor and admin group mappings

- openstack/vcenter-utilities/templates/vasa-exporter-configmap.yaml
- openstack/vcenter-utilities/values.yaml
added vvol credentials for vvol related monitoring.
> vasa-exporter: added vvol credentials

- openstack/glance/values.yaml
Hi @Carthaca 
Please review this PR and approve.
Regards,
Rajiv
> [Glance] Adding image metrics

- openstack/neutron/templates/asr_config_agents/_deployment-asr1k.yaml.tpl
- openstack/neutron/templates/bin/_neutron-openvswitch-agent-start.tpl
- openstack/neutron/templates/configmap-bin.yaml
- openstack/neutron/templates/daemonset-network_agents.yaml
- openstack/neutron/templates/deployment-aci-agent.yaml
- openstack/neutron/templates/deployment-ucs-bm-ml2-agent.yaml
- openstack/nova/templates/hypervisors/_kvm-deployment.yaml.tpl
- openstack/utils/templates/snippets/_network-container-agent.tpl
Using the newest neutron image (needs to be rolled-out everywhere), this will introduce agent liveness checks.
> Neutron liveness check

- system/kube-monitoring/charts/prometheus-collector/templates/deployment.yaml
- system/kube-monitoring/charts/prometheus-collector/values.yaml
- system/kube-monitoring/charts/prometheus-frontend/templates/deployment.yaml
- system/kube-monitoring/charts/prometheus-frontend/values.yaml
This PR moves prometheus resource values to helm values file. I need to overwrite these values, eg. in scaleout klusters.
> Refactor prometheus resource values

- openstack/barbican/templates/api-deployment.yaml
- openstack/barbican/templates/migration-job.yaml
- openstack/barbican/values.yaml
- openstack/glance/templates/deployment.yaml
- openstack/glance/templates/migration-job.yaml
- openstack/glance/values.yaml
Hi @Carthaca,
Could you please validate this PR, this changes have been introduced wrt CCM-8654. 
Regards,
Rajiv
> [Barbican][Glance] Editing helm-template 

- openstack/cinder/requirements.lock
- openstack/cinder/requirements.yaml
- openstack/nova/requirements.lock
- openstack/nova/requirements.yaml
Hi @joker-official.
Regards,
Rajiv
> [Cinder][Nova] Adding common/region-check/ to requirements

- openstack/swift-utils/templates/account-caretaker-mergify-deployment.yaml
- openstack/swift-utils/values.yaml
- openstack/swift/templates/_utils.tpl
- openstack/swift/templates/memcached-deployment.yaml
- openstack/swift/templates/memcached-service.yaml
- openstack/swift/templates/object-expirer-deployment.yaml
- openstack/swift/templates/proxy-deployment.yaml
- openstack/swift/values.yaml
- system/kube-monitoring/charts/prometheus-frontend/openstack-swift.alerts
* swift proxy deployment pod in QoS class guaranteed
* account caretaker deployment resources
* alerts for schedluing issues and oom
> [swift] resource request and limits

- common/rabbitmq_cluster/.helmignore
- common/rabbitmq_cluster/Chart.yaml
- common/rabbitmq_cluster/templates/_helpers.tpl
- common/rabbitmq_cluster/templates/etc-configmap.yaml
- common/rabbitmq_cluster/templates/etc/_definitions.json.tpl
- common/rabbitmq_cluster/templates/etc/_enabled_plugins.tpl
- common/rabbitmq_cluster/templates/etc/_rabbitmq.conf.tpl
- common/rabbitmq_cluster/templates/pvc.yaml
- common/rabbitmq_cluster/templates/service.yaml
- common/rabbitmq_cluster/templates/statefulset.yaml
- common/rabbitmq_cluster/values.yaml
rabbitmq now uses statefulset and k8s auto discovery to create a
federation if scaled above one replica
also, introduces global rabbitmq that replaces the openstack-helm charts
one
> rabbitmq clustering with k8s auto discovery

- openstack/neutron/templates/_helpers.tpl
- openstack/neutron/templates/asr_config_agents/_deployment-asr1k.yaml.tpl
- openstack/neutron/templates/daemonset-network_agents.yaml
- openstack/neutron/templates/deployment-aci-agent.yaml
- openstack/neutron/templates/deployment-rpc-server.yaml
- openstack/neutron/templates/deployment-secgroup-entanglement-exporter.yaml
- openstack/neutron/templates/deployment-server.yaml
- openstack/neutron/templates/deployment-ucs-bm-ml2-agent.yaml
- openstack/neutron/templates/job-migration.yaml
- openstack/neutron/templates/loadbalancers/_deployment-f5.yaml.tpl
- openstack/neutron/templates/nanny-deployment.yaml
- openstack/neutron/templates/vct-nsxv3-agent-deployment.yaml
- openstack/neutron/values.yaml
this will preprare the neutron charts for shared pipeline usage
> [neutron] refactor secret variables

- openstack/hermes/templates/api-deployment.yaml
- openstack/hermes/templates/elasticsearch-deployment.yaml
- openstack/hermes/templates/elasticsearch-pvclaim.yaml
- openstack/hermes/templates/elasticsearch-service.yaml
- openstack/hermes/templates/etc/_curator.yml.tpl
- openstack/hermes/templates/etc/_delete_indices.yml.tpl
- openstack/hermes/templates/etc/_elasticsearch.yaml.tpl
- openstack/hermes/templates/logstash-deployment.yaml
- openstack/hermes/templates/wall-e-deployment.yaml
- openstack/hermes/values.yaml
Merge required values changes.
> Hermes required

- openstack/elk/templates/bin/_create-kibana-indexes.sh.tpl
- openstack/elk/templates/bin/_es-disable-sync.sh.tpl
- openstack/elk/templates/bin/_es-enable-sync.sh.tpl
- openstack/elk/templates/es-bin-configmap.yaml
- openstack/elk/templates/es-data.yaml
- openstack/elk/templates/es-manager-deployment.yaml
- openstack/elk/templates/etc/_fluent.conf.tpl
- openstack/elk/templates/etc/_jvm.options.tpl
- openstack/elk/templates/etc/_kibana.yml.tpl
switch to new curator image for elk-elasticsearch-manager to fix broken rest calls.
> switch to new curator image

- openstack/designate/requirements.lock
- openstack/designate/requirements.yaml
- openstack/designate/templates/api-deployment.yaml
- openstack/designate/templates/central-deployment.yaml
- openstack/designate/templates/mdns-deployment.yaml
- openstack/designate/templates/migration-job.yaml
- openstack/designate/templates/pre-upgrade-forced-cleanup.yaml
- openstack/designate/templates/producer-deployment.yaml
- openstack/designate/templates/sink-deployment.yaml
- openstack/designate/templates/tests/tempest-validation.yaml
- openstack/designate/templates/worker-deployment.yaml
- openstack/designate/values.yaml
Hi @dhoeller 
Please validate and approve this PR.
Regards,
Rajiv
> [Designate] adding required to image values in helm template

- openstack/designate/requirements.lock
- openstack/designate/requirements.yaml
Hi @dhoeller 
Please validate and approve this PR.
Regards,
Rajiv
> [Designate] Add region-check to requirements

- global/prometheus-alertmanager/slack.tmpl
For increased brevity this replaces Prometheus, Playbook, Grafana, Sentry, Kibana, Cloudops links with fitting emoji
> Replace common link text with emoji

- system/kube-monitoring/charts/prometheus-frontend/openstack-nova.alerts
> New Alert OpenstackDVSSecurityGroupTooManyRules

- openstack/sap-seeds/templates/flavor-seed.yaml
Added two new private flavors by Davids and Gergelys request.
Flavor x1.32xlarge 128 vCPU / 1.9TB of RAM
Flavor x1e.16xlarge 64vCPU / 1.9TB of RAM
> Two new flavors added

- system/kube-monitoring/requirements.lock
> [kube-monitoring] updates req lock file

- system/kube-system/templates/ingress-external-public-service.yaml
- system/kube-system/values.yaml
something for tomorrow. cc @dhoeller
> re-adds ingress-controller-public-service

- openstack/maia/values.yaml
latest maia version includes a performance fix desperately needed in e.g. eu-de-1
> raise maia version to include 1000 projects fix

- openstack/maia/templates/_maia.conf
- openstack/maia/values.yaml
remove openstack discovery leftovers
missed one variable ref when renaming
> Maia cleanup

- openstack/arc/templates/seed.yaml
- openstack/barbican/templates/seed.yaml
- openstack/billing/templates/seeds.yaml
- openstack/cinder/templates/seed.yaml
- openstack/designate/templates/seeds.yaml
- openstack/domain-seeds/templates/domain-cp-seed.yaml
- openstack/elektra/templates/seed.yaml
- openstack/hermes/templates/keystone-seed.yaml
- openstack/ironic/templates/seed.yaml
- openstack/limes/templates/seed.yaml
- openstack/limes/templates/support_seed.yaml
- openstack/maia/templates/seed.yaml
- openstack/manila/templates/seeds.yaml
- openstack/neutron/templates/seed.yaml
- openstack/nova/templates/seed.yaml
- openstack/sap-seeds/templates/nova-seed.yaml
- openstack/swift-utils/templates/seed.yaml
Added seeds for the new CP openstack domain.
Please check if additional service and domain specific entries might be missing.
https://issues.wdf.sap.corp/browse/CCM-9504
> added cp domain seeds

- openstack/swift/templates/support_seed.yaml
> [swift] adding cp domain to support seed

- openstack/backup-replication/templates/replication-deployment.yaml
- openstack/content-repo/templates/mirror-deployment.yaml
Do not merge before [#37](https://github.com/sapcc/swift-http-import/pull/37)
FYI @reimannf
> swift-http-import: switch to tini

- openstack/cinder/templates/api-deployment.yaml
- openstack/cinder/templates/db-cleanup-cronjob.yaml
- openstack/cinder/templates/db-init-configmap.yaml
- openstack/cinder/templates/db-maintain-configmap.yaml
- openstack/cinder/templates/migration-job.yaml
- openstack/cinder/templates/nanny-deployment.yaml
- openstack/cinder/templates/scheduler-deployment.yaml
- openstack/cinder/templates/vcenter_datacenter_cinder_deployment.yaml
- openstack/cinder/templates/volumes/_netapp-deployment.yaml.tpl
- openstack/cinder/templates/volumes/_volume-deployment.yaml.tpl
- openstack/cinder/values.yaml
Hi @joker-official 
Regards,
Rajiv
> [Cinder] adding required value to the templates

- global/prometheus-alertmanager/slack.tmpl
- system/kube-monitoring/charts/prometheus-frontend/network-asr.alerts
Component hast the ‘snmp_exporter’ in its name - devicename is correct.
NetworkAsrNatTableIsNearlyFull got an SPC Ticket Create Link as PoC.
> Change from component to device name && add a Create SPC Ticket Link

- openstack/tempest/glance-tempest/.helmignore
- openstack/tempest/glance-tempest/Chart.yaml
- openstack/tempest/glance-tempest/requirements.lock
- openstack/tempest/glance-tempest/requirements.yaml
- openstack/tempest/glance-tempest/templates/bin/_tempest-start-and-cleanup.sh.tpl
- openstack/tempest/glance-tempest/templates/configmap-bin-tempest.yaml
- openstack/tempest/glance-tempest/templates/configmap-etc-tempest.yaml
- openstack/tempest/glance-tempest/templates/etc/_tempest_accounts.yaml.tpl
- openstack/tempest/glance-tempest/templates/etc/_tempest_deployment_config.json.tpl
- openstack/tempest/glance-tempest/templates/tempest-pod.yaml
- openstack/tempest/glance-tempest/values.yaml
Hi @unmerkbar,
Please validate.
Regards,
Rajiv
> [Glance] Adding glance tempest

- openstack/glance/values.yaml
Hi @Scsabiii,
Please approve this PR. This is wrt Jira# CCM-8658.
Regards,
Rajiv
> [Glance] Enable resource limits

- global/prometheus-alertmanager/templates/config.yaml
- activates canary regions for alert bm error handling
> [alertmanager] switches to global wham url

- openstack/elk/templates/etc/_delete_indices.yml.tpl
- openstack/hermes/templates/_create-kibana-indexes.sh.tpl
- openstack/hermes/templates/_wall-e-start.tpl
- openstack/hermes/templates/elasticsearch-deployment.yaml
- openstack/hermes/templates/elasticsearch-etc-configmap.yaml
- openstack/hermes/templates/etc/_audit.json.tpl
- openstack/hermes/templates/etc/_delete_indices.yml.tpl
- openstack/hermes/templates/etc/_elasticsearch.yml.tpl
- openstack/hermes/templates/etc/_logstash.conf.tpl
- openstack/hermes/templates/kibana-deployment.yaml
- openstack/hermes/templates/logstash-deployment.yaml
ES 6 upgrade, All issues look to be solved outside of kibana which can be handled after the fact. Each region will need to be manually upgraded and watched to validate. 
Plan to start this tomorrow and upgrade all regions. If there are any issues with a regional upgrade, will space them out a bit. Will start with the smallest regions, with the least data.
> [hermes] ES 6 Upgrade

- global/concourse/templates/daemonset.yaml
Otherwise we collect zombies until the system is out of resources.
> Re-add dumb-init to worker container

- openstack/domain-seeds/templates/domain-ccadmin-seed.yaml
Do not reference old name  CCADMIN_BAREMETALMONITORING_ADMIN
> Change the ccadmin domain seeding to CCADMIN_BAME_ADMIN

- system/kube-monitoring/charts/prometheus-rules/alerts/node.alerts
This PR adds an alert for disk usage above 85%. It is routed to info channel for now. //cc @SchwarzM
> Add disk usage alert

- openstack/hermes/templates/etc/_logstash.conf.tpl
- openstack/hermes/templates/logstash-deployment.yaml
Had to remove the liveliness probe as much as I don't want to, data will definitely be lost in the process with it. We need to add some storage to the logstash instance ultimately to protect against data loss in this part of the pipeline.
This adds the s3/swift config, and fixes the cc of certain audit events to a project.
> [hermes] add s3/swift config, fix cc projects

- system/sentry/aggregations/sentry.rules
- system/sentry/alerts/openstack-sentry.alerts
- system/sentry/charts/postgresql/templates/svc.yaml
- system/sentry/templates/prometheus-aggregations.yaml
- system/sentry/templates/prometheus-alerts.yaml
- system/sentry/values.yaml
> [Sentry-Alerts] Moving alerts to Prom-OS tier

- system/infra-monitoring/requirements.yaml
- system/infra-monitoring/values.yaml
- system/infra-monitoring/vendor/ironic-exporter/Chart.yaml
- system/infra-monitoring/vendor/ironic-exporter/templates/deployment.yaml
- system/infra-monitoring/vendor/ironic-exporter/values.yaml
to be rm from kube-monitoring!
> [infra-monitoring] adds ironic-exporter to infra pipeline

- system/kube-monitoring/charts/prometheus-frontend/openstack-nova.alerts
Playbook link provided by B1 was added to alert.
> Add a playbook link for OpenstackDVSSecurityGroupTooManyRules

- openstack/castellum/Chart.yaml
- openstack/castellum/alerts/errors.alerts
- openstack/castellum/files/policy.json
- openstack/castellum/requirements.lock
- openstack/castellum/requirements.yaml
- openstack/castellum/templates/_utils.tpl
- openstack/castellum/templates/api-deployment.yaml
- openstack/castellum/templates/api-ingress.yaml
- openstack/castellum/templates/api-service.yaml
- openstack/castellum/templates/configmap.yaml
- openstack/castellum/templates/observer-deployment.yaml
- openstack/castellum/templates/prometheus-alerts.yaml
- openstack/castellum/templates/seed.yaml
- openstack/castellum/templates/worker-deployment.yaml
- openstack/castellum/values.yaml
> add chart for Castellum

- common/pgmetrics/Chart.yaml
- common/pgmetrics/templates/_helpers.tpl
- common/pgmetrics/templates/alerts.yaml
- common/pgmetrics/templates/alerts/_database.alerts.tpl
- common/pgmetrics/templates/deployment.yaml
- common/pgmetrics/values.yaml
Default set of Prometheus alerts for the pgmetrics common chart.
> default pgmetrics alerts

- global/quay/alerts/quay.alerts
- system/kube-monitoring/charts/prometheus-frontend/kubernetes-quay.alerts
- Current volume size 360 GB
- Alert when db size reaches 300 GB
> Quay database size alert

- openstack/designate/templates/etc/_designate.conf.tpl
troubleshoot issues with designate deployment in NA-US-2
> Reverting changes from d60a2b0763a09c7d12d5a71963d7355794bf9968 to

- openstack/designate/templates/etc/_designate.conf.tpl
back to d60a2b0763a09c7d12d5a71963d7355794bf9968
> Revert changes from c3e86a8ef1d4e3762471794432a9df8663e5608f

- openstack/swift/templates/etc/_proxy-server.conf.tpl
> [swift] setting s3 secret caching time

- system/kube-monitoring/Chart.yaml
> bump chart version

- system/kube-monitoring/charts/prometheus-frontend/admin-velero-backup.alerts
- system/kube-monitoring/charts/prometheus-frontend/templates/config.yaml
- system/velero/alerts/admin-backup-failure.alerts
- system/velero/templates/prometheus-alerts.yaml
- system/velero/values.yaml
This PR adds an alert for failing full backups in admin cluster. //cc @databus23
> Add alert for admin cluster velero full backup

- openstack/sap-seeds/templates/flavor-seed.yaml
consulting team. Flavor is created as private.
> Added new flavor with 150GB root disk requested by

- openstack/swift/templates/etc/_proxy-server.conf.tpl
as reading other users credentials is not possible with our current keystone policy setup, deactivate it
> [swift] remove s3 secret caching

- openstack/nova/values.yaml
Change to nova scheduling filters.
> [nova] add AggregateInstanceExtraSpecsFilter for Big VMs scheduling

- openstack/nova/templates/create-bigvm-aggregates-job.yaml
P.S. those are the scripts from Friday in container. We need a better solution in the future.
> [nova][bigvm] a cron job to auto-create nova aggregates for bigVMs

- openstack/keystone/ci/test-values.yaml
- openstack/keystone/values.yaml
Hi @ruvr 
Initial PR.
Regards,
Rajiv
> [Chart-testing][Keystone] Fix truthy value

- openstack/barbican/ci/test-values.yaml
> [Chart-testing][Barbican] Adding ci/test-values.yaml

- openstack/glance/ci/test-values.yaml
> [Chart-testing][Glance] Adding ci/test-values.yaml

- openstack/nova/ci/test-values.yaml
- openstack/nova/values.yaml
Hi @joker-official,
Please approve this PR.
Regards,
Rajiv
> [Chart-testing][Nova] Fix indentation and truthy value

- openstack/domain-seeds/templates/domain-neo-seed.yaml
> [Neo-domain-seeds] Adding domain-neo-seed.yaml file

- openstack/barbican/templates/seed.yaml
- openstack/billing/templates/seeds.yaml
- openstack/cinder/templates/seed.yaml
- openstack/ironic/templates/seed.yaml
- openstack/manila/templates/seeds.yaml
- openstack/neutron/templates/seed.yaml
- openstack/nova/templates/seed.yaml
- openstack/swift/templates/support_seed.yaml
> [Neo-Seeds] removing cc-demo project and adding neo to swift support-seed

- system/infra-monitoring/requirements.yaml
- system/infra-monitoring/values.yaml
> [infra-monitoring] added vasa-exporter to values and requirements

- prometheus-rules/prometheus-controlplane-rules/Chart.yaml
- prometheus-rules/prometheus-controlplane-rules/alerts/kubernetes-etcd.alerts
- system/kube-monitoring/templates/_frontend-prometheus.yaml.tpl
This PR adds etcd-backup-restore alert to admin cluster.
> Add etcdbr alert to admin cluster

- system/infra-monitoring/requirements.yaml
- system/infra-monitoring/templates/_prometheus-infra-collector.yaml.tpl
- system/infra-monitoring/values.yaml
- system/infra-monitoring/vendor/alertmanager-exporter/Chart.yaml
- system/infra-monitoring/vendor/alertmanager-exporter/alerts/alertmanager.alerts
- system/infra-monitoring/vendor/alertmanager-exporter/templates/alerts.yaml
- system/infra-monitoring/vendor/thousandeyes-exporter/alerts/thousandeyes.alerts
prepare scraping of alertmanager metrics + alerting;
fix typo in thousandeyes
> [infra-monitoring] add alertmanager metrics exportation

- global/concourse-worker/values.yaml
> Upgrade the default concourse image

- system/infra-monitoring/templates/_prometheus-infra-collector.yaml.tpl
> [infra-monitoring] added vasa-exporter to prometheus template

- system/infra-monitoring/vendor/vasa-exporter/templates/configmap.yaml
- system/infra-monitoring/vendor/vasa-exporter/values.yaml
> [infra-monitoring] vasa-exporter: fixed indention and added credentials

- system/infra-monitoring/vendor/vasa-exporter/templates/deployment.yaml
> [infra-monitoring] vasa deployment: removed quotes

- system/infra-monitoring/vendor/vasa-exporter/templates/configmap.yaml
- system/infra-monitoring/vendor/vasa-exporter/templates/deployment.yaml
- system/infra-monitoring/vendor/vasa-exporter/templates/service.yaml
- system/infra-monitoring/vendor/vasa-exporter/values.yaml
due to consistency reasons
@viennaa
> [infra-monitoring] vasa-exporter: renamed port 

- system/infra-monitoring/templates/_prometheus-infra-collector.yaml.tpl
@viennaa
I guess that should be the right approach. It's been inspired by the snmp and cp/netbox jobs.
> [infra-monitoring] vasa-exporter: edited relabeling

- global/prometheus-alertmanager/slack.tmpl
Added a line of code to render a button which could directly forwards to a corresponding AWX job
> added AWX button to slack template

- openstack/designate/ci/test-values.yaml
- openstack/designate/templates/api-deployment.yaml
- openstack/designate/templates/api-ingress.yaml
- openstack/designate/templates/mdns-deployment.yaml
- openstack/designate/templates/migration-job.yaml
- openstack/designate/templates/tests/tempest-validation.yaml
- openstack/designate/values.yaml
> fix desginate chart

- system/kube-flannel/Chart.yaml
- system/kube-system-virtual/Chart.yaml
- system/kube-system-virtual/requirements.yaml
- system/kube-system-virtual/values.yaml
kube-system umbrella chart for v-clusters
> [kube-system] add kube-system-virtual

- system/kube-system-virtual/Chart.yaml
- system/kube-system-virtual/values.yaml
for `container-linux-update-operator`
> [kube-system-virtual] fix values to enable rbac

- openstack/maia/requirements.lock
- openstack/maia/requirements.yaml
- openstack/maia/templates/etc/_maia.conf
> [maia] thanos changes, new prometheus_url

- system/infra-monitoring/vendor/vasa-exporter/values.yaml
> [infra-monitoring] vasa-exporter: added image version to values.yaml

- openstack/barbican/requirements.lock
- openstack/barbican/requirements.yaml
- openstack/barbican/values.yaml
- openstack/cinder/requirements.lock
- openstack/cinder/requirements.yaml
- openstack/cinder/values.yaml
- openstack/designate/requirements.lock
- openstack/designate/requirements.yaml
- openstack/designate/values.yaml
- openstack/glance/requirements.lock
- openstack/glance/requirements.yaml
- openstack/glance/values.yaml
- openstack/octavia/requirements.lock
- openstack/octavia/requirements.yaml
- openstack/octavia/values.yaml
Follow-up to https://github.com/sapcc/helm-charts/pull/955
It needs to be merged before this PR and then this PR's dependencies updated
> added mariadb pvc names for chart V 0.1.2

- openstack/hermes/README.md
- openstack/hermes/elktools/.helmignore
- openstack/hermes/elktools/Chart.yaml
- openstack/hermes/elktools/README.md
- openstack/hermes/elktools/templates/elasticsearch-restore.yaml
- openstack/hermes/elktools/values.yaml
> Hermes elktools es restore

- system/infra-monitoring/templates/_prometheus-infra-collector.yaml.tpl
- system/infra-monitoring/vendor/vasa-exporter/values.yaml
> [infra-monitoring] vasa-exporter: changed image and increased query time

- openstack/maia/values.yaml
see https://github.com/sapcc/maia/pull/60
> [maia] adopt new label/*/values API impl.

- openstack/sap-seeds/templates/flavor-seed.yaml
requested by S4 and requested through
https://issues.wdf.sap.corp/browse/CCM-10948
> Flavor changes

- openstack/hermes/templates/_hermes.conf
Enables new gophercloud authentication style.
> [hermes] add project_domain_name to conf

- openstack/glance/values.yaml
Enable audit globally for glance
> [glance] enable audit globally

- prometheus-exporters/watchcache-exporter/Chart.yaml
- prometheus-exporters/watchcache-exporter/README.md
- prometheus-exporters/watchcache-exporter/alerts/watchcache.alerts
- prometheus-exporters/watchcache-exporter/templates/_helpers.tpl
- prometheus-exporters/watchcache-exporter/templates/clusterrole.yaml
- prometheus-exporters/watchcache-exporter/templates/clusterrolebinding.yaml
- prometheus-exporters/watchcache-exporter/templates/deployment.yaml
- prometheus-exporters/watchcache-exporter/templates/prometheus-alerts.yaml
- prometheus-exporters/watchcache-exporter/templates/serviceaccount.yaml
- prometheus-exporters/watchcache-exporter/values.yaml
This PR adds watchcache exporter chart, see https://github.com/sapcc/kubernetes-watchcache-exporter
> Add watchcache exporter

- system/infra-monitoring/vendor/vasa-exporter/alerts/vasa.alerts
Playbook: https://operations.global.cloud.sap/docs/devops/alert/vcenter/#vasa_filesystem_usage_high
> [infra-monitoring] vasa-exporter: filesystem alert

- system/kube-proxy/Chart.yaml
- system/kube-proxy/alerts/kube-parrot.alerts
- system/kube-proxy/templates/alerts.yaml
- system/kube-proxy/values.yaml
`enable` switch will be in the umbrella chart
> [kube-parrot] add alerts

- openstack/ironic/templates/seed.yaml
> adding supervisor flavor

- global/prometheus-alertmanager/slack.tmpl
- global/prometheus-alertmanager/templates/config.yaml
remove the silence buttons in slack; 
add link in slack template for supernova for silencing there; 
add global region in routing for API managed service (thousandeyes http alerts of stargate and supernova need it)
> [alerting] rm silence buttons; add supernova way

- system/infra-monitoring/vendor/cablecheck-exporter/values.yaml
script will now handle, if no bm server is available in region
> updated image to v9

- openstack/manila/ci/test-values.yaml
- openstack/manila/values.yaml
Hi @chuan137 
This PR is related to https://github.com/sapcc/helm-charts/tree/master/ci, i fixed most of the os services. 
Regards,
Rajiv
> [Chart-testing][Manila] Adding ci/test-values.yaml and fixing indent

- prometheus-exporters/esxi-exporter/Chart.yaml
- prometheus-exporters/esxi-exporter/templates/deployment.yaml
- prometheus-exporters/esxi-exporter/templates/service.yaml
- prometheus-exporters/esxi-exporter/values.yaml
> [prometheus-exporters] added esxi-exporter

- openstack/ironic/values.yaml
Hi @BerndKue,
Please validate this PR. Its related to https://ci.eu-de-2.cloud.sap/teams/services/pipelines/chart-test/jobs/check-pull-request/builds/204
Regards,
Rajiv
> [Ironic] Pleasing chart-testing

- common/rabbitmq/templates/alerts/_rabbitmq.alerts.tpl
check https://github.wdf.sap.corp/cc/secrets/compare/d072896_rabbitmq_alerts_mod?expand=1, too
> [rabbitmq] templating alert to adopt the hardcoded values

- prometheus-exporters/esxi-exporter/templates/deployment.yaml
> [esxi-exporter] Values quoted

- openstack/swift/alerts/swift-api.alerts
> swift: hardcode service for playbook routing

- system/dynomite/templates/deployment.yaml
- system/dynomite/values.yaml
Only needed if warmup doesn't work. 
It involves a manual `kubectl edit deployment` to change the command for `powder-monkey`.
> [dynomite] poor mans restore via init-container on request

- global/prometheus-alertmanager-operated/.gitignore
- global/prometheus-alertmanager-operated/Chart.yaml
- global/prometheus-alertmanager-operated/ci/test-values.yaml
- global/prometheus-alertmanager-operated/requirements.yaml
- global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl
- global/prometheus-alertmanager-operated/values.yaml
**DO NOT MERGE**
Planned for next week.
> **DO NOT MERGE** Activate new Alertmanagers

- openstack/barbican/requirements.lock
- openstack/barbican/requirements.yaml
- openstack/barbican/templates/api-deployment.yaml
- openstack/barbican/templates/etc-configmap.yaml
- openstack/barbican/templates/etc/_barbican-api-paste.ini.tpl
- openstack/barbican/templates/etc/_barbican.conf.tpl
- openstack/barbican/templates/etc/_barbican_audit_map.yaml
- openstack/barbican/values.yaml
Rajiv, Here is the new branch that we can test on cleanly. Please take a glance to let me know if I missed anything.
> Barbican Audit enablement

- openstack/ironic/alerts/openstack-ironic.alerts
Only merge after the internal convergedcloud-opsdocu-ui/pull/429 was merged
> Added Playbook link for OpenstackIronicNodeInErrorState

- system/cc-rbac/Chart.yaml
- system/cc-rbac/templates/dex-ldap.yaml
- system/cc-rbac/values.yaml
allow new users and groups to be added by values
/cc @databus23 
follow up task of https://github.com/sapcc/kubernikus/pull/510
> [cc-rbac] allow adding new users and groups

- system/kube-system/Chart.yaml
- system/kube-system/requirements.yaml
- system/kube-system/values.yaml
Currently being tested in qa-de-1
> [kube-system] bump ingress

- openstack/ironic/alerts/openstack-ironic.alerts
Playbook for Failed state seems to be applicable here as well. See these error from time to time but don't think there is anything else to do yet.
> Added Playbook for IronicNodeInDeployFailedState

- system/infra-monitoring/vendor/atlas/templates/configmap.yaml
This is required for discovery to work again since  netbox changed status=1 to status=active
> Adjust status to Netbox 2.7 non-numerical api

- openstack/swift/alerts/openstack/api.alerts
Agreement to roll this out next week with BM team
> [swift] disk failures alerts to #alert-metal-warning

- common/mariadb/templates/_helpers.tpl
- common/mariadb/templates/backup-etc-configmap.yaml
- common/mariadb/templates/deployment.yaml
- common/mariadb/templates/initdb/_init.sh.tpl
- common/mariadb/templates/secret.yaml
- use masterpassword mechanism if passwords are not overriden
- for ease of use: add MYSQL_PWD env
> [mariadb] fallback to derived passwords

- openstack/manila/ci/test-values.yaml
- openstack/manila/values.yaml
merge after https://github.com/sapcc/helm-charts/pull/1243
> [manila] more descriptive ci valuee, db passwords are optional

- openstack/domain-seeds/ci/test-values.yaml
- openstack/domain-seeds/templates/domain-default-seed.yaml
- openstack/domain-seeds/values.yaml
- openstack/maia/ci/test-values.yaml
- openstack/maia/requirements.lock
- openstack/maia/templates/seed.yaml
- openstack/maia/values.yaml
for creating application credentials to make maia accessible in
grafana as a service
> [maia][gaas] add grafana as a service user

- openstack/neutron/ci/test-values.yaml
- openstack/neutron/templates/deployment-aci-agent.yaml
This will get the aci pod to also restart on aci config changes
> Add configmap hashes to aci deployment

- common/mariadb/ci/test-values.yaml
- common/mariadb/templates/_helpers.tpl
- common/mariadb/templates/backup-etc-configmap.yaml
- common/mariadb/templates/deployment.yaml
- common/mariadb/templates/initdb/_init.sh.tpl
- common/mariadb/templates/secret.yaml
- common/mysql_metrics/ci/test-values.yaml
- common/mysql_metrics/templates/_helpers.tpl
- openstack/utils/templates/_hosts.tpl
and allow for derived password
> [utils] fallback to derived password for mariadb connection

- common/mariadb/templates/alerts/_mysql.alerts.tpl
moved MariaDBSlowQueries from Manila section to general database section
> [database] move playbook MariaDBSlowQueries

- openstack/barbican/ci/test-values.yaml
> [Barbican] make linter happy again

- openstack/blackbox/charts/blackbox-tests-certificates/alerts/certificates.alerts
- openstack/blackbox/values.yaml
- openstack/manila/alerts/openstack-manila.alerts
- warning only 14 days before (not 30)
- link to netapp cert playbook mentioning to highlight storage team
> [blackbox][manila] split out filer cert alerts

- openstack/barbican/ci/test-values.yaml
- openstack/barbican/templates/api-deployment.yaml
- openstack/barbican/values.yaml
> [Barbican] Set resources and replicas values

- system/infra-monitoring/templates/_prometheus-infra-collector.yaml.tpl
- system/infra-monitoring/values.yaml
- system/infra-monitoring/vendor/bm-cablecheck-exporter/Chart.yaml
- system/infra-monitoring/vendor/bm-cablecheck-exporter/templates/_helpers.tpl
- system/infra-monitoring/vendor/bm-cablecheck-exporter/templates/deployment.yaml
- system/infra-monitoring/vendor/bm-cablecheck-exporter/templates/service.yaml
- system/infra-monitoring/vendor/bm-cablecheck-exporter/values.yaml
added helm for bm-cablecheck-exporter
created new job for custom scraping of more than 1 minute as default
> added helm for bm-cablecheck-exporter

- openstack/keystone/templates/deployment-api.yaml
- openstack/keystone/templates/deployment-cron.yaml
- openstack/keystone/templates/ingress-api.yaml
Hi @Carthaca,
Please validate.
Regards,
Rajiv
> [Keystone] Add conditional apps/v1

- openstack/manila/templates/api-deployment.yaml
- openstack/manila/templates/api-ingress.yaml
- openstack/manila/templates/scheduler-deployment.yaml
- openstack/manila/templates/shares/_netapp-deployment.yaml.tpl
Hi @Carthaca 
Please validate.
Regards,
Rajiv
> [Manila] Add conditional apps/v1

- system/dynomite/alerts/dynomite.alerts
- system/dynomite/templates/_helpers.tpl
- system/dynomite/templates/deployment.yaml
- system/dynomite/values.yaml
* Option to specify the warmup rack
* Setting dashboard in alert
> [dynomite] - Warmup Rack specification

- prometheus-rules/prometheus-kubernetes-rules/Chart.yaml
- prometheus-rules/prometheus-kubernetes-rules/alerts/node.alerts.tpl
> fix Grafana URL for NodeHostHighCPUUsage

- openstack/blackbox/charts/blackbox-tests-integrity/Chart.yaml
- openstack/blackbox/charts/blackbox-tests-integrity/alerts/neutron-integrity.alerts
- openstack/neutron/Chart.yaml
- openstack/neutron/alerts/neutron.alerts
> fix playbook URL's for OpenstackNeutronIntegrityOutOfFIPs

- system/infra-monitoring/vendor/netapp-cap-exporter/alerts/netapp-capacity.alerts
remove value from label
to not get a new alert everytime the value changes (I hope)
> [netapp-cap-exporter] ManilaStorageAggregateHighUsage alert

- system/infra-monitoring/vendor/vpod-cablecheck-exporter/values.yaml
please merge and redeploy in qa-de-1
> [vpod-cablecheck-exporter: rebuild image v3 (debugging)

- openstack/manila/values.yaml
Provides share_id <-> share_instance_id mapping
> [manila] Manila share instance metric

- openstack/manila/values.yaml
* share_instance_id
* remove GROUP BY ...
> [manila] Add share_instance_id field to manila_shares_size_gauge

- openstack/nova/templates/_console_deployment.yaml.tpl
- openstack/nova/templates/api-deployment.yaml
- openstack/nova/templates/api-ingress.yaml
- openstack/nova/templates/api-metadata-deployment.yaml
- openstack/nova/templates/bigvm-deployment.yaml
- openstack/nova/templates/cell2-conductor-deployment.yaml
- openstack/nova/templates/conductor-deployment.yaml
- openstack/nova/templates/console-ingress.yaml
- openstack/nova/templates/consoleauth-deployment.yaml
- openstack/nova/templates/hypervisors/_ironic-deployment.yaml.tpl
- openstack/nova/templates/hypervisors/_kvm-deployment.yaml.tpl
- openstack/nova/templates/hypervisors/hypervisors-vmware-deployment-vct.yaml
- openstack/nova/templates/placement-api-deployment.yaml
- openstack/nova/templates/placement-ingress.yaml
- openstack/nova/templates/scheduler-deployment.yaml
- openstack/nova/templates/vspc-deployment.yaml
Hi @joker-official,
Please validate.
Regards,
Rajiv
> [Nova] Add conditional apps/v1

- prometheus-exporters/vrops-exporter/alerts/virtual_machine.alerts
Multiple alert conditions which indicates an inaccessible shadow vm.
> [vrops-exporter] Added InaccessibleShadowVM alert

- global/prometheus-alertmanager-operated/ci/test-values.yaml
- global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl
vmware alerts should be able to trigger actions in awx
pls check related secrets change, too
> [alertmanager] add awx routing

- system/infra-monitoring/vendor/bm-cablecheck-exporter/values.yaml
- system/infra-monitoring/vendor/vpod-cablecheck-exporter/values.yaml
> [bm-cablecheck-exporter] [vpod-cablecheck-exporter] 

- system/infra-monitoring/vendor/netapp-cap-exporter/alerts/netapp-capacity.alerts
the storage team is usung this metric for their alerting so lets use the same one here too
> [netapp exporter] revert back to non physical metric

- openstack/elastiflow/values.yaml
> [elastiflow] upgrade to beta 4.0

- openstack/octobus/templates/seeds.yaml
> openstack permissions updated

- system/infra-monitoring/vendor/bios-exporter/alerts/bios-controlplane.alerts
- system/infra-monitoring/vendor/bios-exporter/alerts/bios-esxi.alerts
- system/infra-monitoring/vendor/bios-exporter/alerts/bios-ironic.alert
- system/infra-monitoring/vendor/bios-exporter/values.yaml
Hi,
Adjusted the alerts and image version to match the new bios_exporter version.
> adjusted alerts and added new image version

- openstack/manila/templates/etc/_manila.conf.tpl
- openstack/manila/templates/shares/_share-netapp.conf.tpl
- openstack/manila/values.yaml
- openstack/nannies/values.yaml
> [manila] train

- openstack/keystone/requirements.lock
- openstack/keystone/requirements.yaml
Hi @Carthaca,
Please approve this PR, CI is blocked.
Regards,
Rajiv
> [Keystone][mysql_metrics] bump version

- openstack/cinder/requirements.lock
- openstack/cinder/requirements.yaml
This patch updates the mysql_metrics version
for cinder.
> [cinder] update mysql_metrics version

- openstack/sre/ci/test-values.yaml
- openstack/sre/templates/prometheus-aggregations.yaml
- openstack/sre/templates/prometheus-alerts.yaml
- openstack/sre/values.yaml
- replace the useless sophisticated by simple availability (last hour) alerts to trigger action
- this lead to changes in the aggregation and a shift to percentage SLO values
> [SRE] clean up & housekeeping

- global/prometheus-infra/templates/_prometheus.yaml.tpl
- system/infra-monitoring/vendor/bm-cablecheck-exporter/values.yaml
- system/infra-monitoring/vendor/vpod-cablecheck-exporter/values.yaml
- system/prometheus-infra/templates/_prometheus-infra.yaml.tpl
> [cablechecker] changed metric name

- openstack/glance/templates/etc/_glance-policy.json.tpl
- openstack/glance/templates/seeds.yaml
Hi @Carthaca 
Regarding Jira task CCM-13726, please validate.
Regards,
Rajiv
> [Glance] Add communitize_image policy and image_community_admin role

- system/infra-monitoring/vendor/bios-exporter/values.yaml
According to ssh connection close
> new image version

- system/infra-monitoring/requirements.lock
- system/infra-monitoring/requirements.yaml
- system/infra-monitoring/templates/_prometheus-infra-collector.yaml.tpl
- system/infra-monitoring/values.yaml
- system/infra-monitoring/vendor/firmware-exporter/Chart.yaml
- system/infra-monitoring/vendor/firmware-exporter/templates/deployment.yaml
- system/infra-monitoring/vendor/firmware-exporter/templates/service.yaml
- system/infra-monitoring/vendor/firmware-exporter/values.yaml
- system/prometheus-infra/templates/_prometheus-infra.yaml.tpl
New Prometheus firmware-exporter.
> adding firmware-exporter

- global/prometheus-alertmanager-operated/Chart.yaml
- global/prometheus-alertmanager-operated/ci/test-values.yaml
- global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl
- global/prometheus-alertmanager-operated/values.yaml
> [alertmanager] add parallel loading to prepare pagerduty migration

- prometheus-exporters/vrops-exporter/alerts/virtualmachine.alerts
Added playbook and increased severity to warning.
> set shadowvm alert to warning

- global/prometheus-alertmanager-operated/Chart.yaml
- global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl
> [alertmanager] add octavia service routing

- system/infra-monitoring/vendor/vpod-cablecheck-exporter/templates/deployment.yaml
- system/infra-monitoring/vendor/vpod-cablecheck-exporter/values.yaml
Reverts sapcc/helm-charts#1684
> Revert "[cablechecker] added mtu-check, V15"

- system/infra-monitoring/requirements.lock
- system/infra-monitoring/requirements.yaml
- system/infra-monitoring/vendor/firmware-exporter/Chart.yaml
- system/infra-monitoring/vendor/firmware-exporter/values.yaml
> new docker image version

- prometheus-exporters/vcsa-exporter/alerts/service.alerts
> adjustes service alert expr

- system/infra-monitoring/vendor/netapp-perf-exporter/aggregations/netapp-perf.rules
openstack_manila_share_avg_latency -> openstack_manila_share_avg_latency_miliseconds
> [netapp-perf] append metric unit to the aggregated netapp filer performance metrics

- global/prometheus-alertmanager-operated/Chart.yaml
- global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl
- global/prometheus-alertmanager-operated/values.yaml
removal of the old pd instance to avoid notification fails after August 1st - removal of secret keys follows separately .
+ some minor sre routing
> D072896 am rm pd

- openstack/manila/Chart.yaml
- openstack/manila/templates/type-seeds.yaml
- openstack/manila/values.yaml
Seed share type for CCIaaS project. https://issues.wdf.sap.corp/browse/CCM-14493
> [manila] share type seeding for CCIaaS

- prometheus-exporters/vrops-exporter/alerts/vcenter.alerts
> removed value variable

- prometheus-exporters/vrops-exporter/alerts/vcenter.alerts
@artherd42 Handover to InfraOps team done by Thomas Thimm in his m3oscore meeting on August 4th.
> VCenter SSL Certificate Alert: set severity to warning/critical

- prometheus-exporters/vcsa-exporter/alerts/service.alerts
@artherd42  Handover to InfraOps team done by Thomas Thimm in his m3oscore meeting on August 4th.
> vcsa service alerts: increased severity to warning/critical

- openstack/neutron/alerts/nsxt.alerts
corrected NSXT_ExporterScrapeOlder_OneHour alert paybook link
> corrected NSXT_ExporterScrapeOlder_OneHour alert paybook link

- openstack/keystone/Chart.yaml
- openstack/keystone/requirements.lock
- openstack/keystone/requirements.yaml
- openstack/keystone/templates/deployment-api.yaml
- openstack/keystone/templates/deployment-cron.yaml
- openstack/keystone/templates/etc/_keystone.conf.tpl
- openstack/keystone/templates/ingress-api.yaml
- openstack/keystone/templates/job-bootstrap.yaml
- openstack/keystone/templates/job-migration.yaml
- openstack/keystone/templates/job-pre-upgrade.yaml
- openstack/keystone/templates/pdb.yaml
- openstack/keystone/templates/rbac.yaml
- openstack/keystone/templates/seed.yaml
- openstack/keystone/templates/sentry.yaml
- openstack/keystone/templates/service-api.yaml
- openstack/keystone/templates/serviceaccount.yaml
- openstack/keystone/values.yaml
in templates; bump chart version and requirements.
> [keystone] use variables for resource naming; dynamic requirements

- openstack/keystone/Chart.yaml
- openstack/keystone/templates/seed.yaml
- openstack/keystone/templates/service-api.yaml
specify both public/internal external service IPs; bump chart.
> [keystone] deploy seeds if it is 1st install; fix seed naming; allow to

- openstack/content-repo/alerts/content-repo.alerts
> openstack/content-repo: alert for missing metrics

- system/infra-monitoring/vendor/bios-exporter/values.yaml
New build number 20200828135408
> Adopted new build due to recent changes

- system/kube-monitoring-admin-k3s/Chart.lock
- system/kube-monitoring-admin-k3s/Chart.yaml
- system/kube-monitoring-admin-k3s/values.yaml
- system/kube-monitoring-admin/Chart.lock
- system/kube-monitoring-admin/Chart.yaml
- system/kube-monitoring-admin/values.yaml
- system/kube-monitoring-kubernikus/Chart.lock
- system/kube-monitoring-kubernikus/Chart.yaml
- system/kube-monitoring-kubernikus/values.yaml
- system/kube-monitoring-scaleout/Chart.lock
- system/kube-monitoring-scaleout/Chart.yaml
- system/kube-monitoring-scaleout/values.yaml
- system/kube-monitoring-virtual/Chart.lock
- system/kube-monitoring-virtual/Chart.yaml
- system/kube-monitoring-virtual/values.yaml
/cc @BugRoger @databus23 
This PR only adds the operator. I will enable the operator on a regional basis as per the bronzer, silver, and gold tier pattern.
> Add absent metrics operator to all cluster types

- system/ccauth/Chart.yaml
- system/ccauth/templates/ingress.yaml
This PR switches ingress from vice-president to cert-manager for certificate issuance.
> Switch ccauth ingress to cert manager

- prometheus-exporters/ns-exporter/Chart.yaml
- prometheus-exporters/ns-exporter/ci/test-values.yaml
- prometheus-exporters/ns-exporter/templates/daemonset.yaml
- prometheus-exporters/ns-exporter/values.yaml
> prometheus-exporters/ns-exporter: switch to Keppel

- system/infra-monitoring/vendor/bm-cablecheck-exporter/templates/deployment.yaml
- system/infra-monitoring/vendor/bm-cablecheck-exporter/values.yaml
- system/infra-monitoring/vendor/vpod-cablecheck-exporter/templates/deployment.yaml
- system/infra-monitoring/vendor/vpod-cablecheck-exporter/values.yaml
Moved to new Docker image registry. Therefore adjusted image.
> updated image registry

- common/postgresql/templates/pgbouncer-deployment.yaml
- openstack/nova/ci/test-values.yaml
- openstack/nova/requirements.lock
- openstack/nova/requirements.yaml
- openstack/nova/values.yaml
Related secrets changes: https://github.wdf.sap.corp/cc/secrets/pull/4126
> Nova more keppel

- openstack/arc/charts/postgresql/values.yaml
The version should be upgraded since keppel has 0.6.5
> bakcup tool version upgrade

- openstack/neutron/requirements.lock
- openstack/neutron/requirements.yaml
- openstack/neutron/templates/asr_config_agents/_deployment-asr1k.yaml.tpl
- openstack/neutron/templates/daemonset-metadata-agent.yaml
- openstack/neutron/templates/deployment-aci-agent.yaml
- openstack/neutron/templates/deployment-f5-agent.yaml
- openstack/neutron/templates/deployment-ironic-agent.yaml
- openstack/neutron/templates/deployment-rpc-server.yaml
- openstack/neutron/templates/deployment-server.yaml
- openstack/neutron/templates/deployment-ucs-bm-ml2-agent.yaml
- openstack/neutron/templates/job-migration.yaml
- openstack/neutron/templates/job-octavia-migration.yaml
- openstack/neutron/templates/nanny-deployment.yaml
- openstack/neutron/templates/statefulset-network-agent.yaml
- openstack/neutron/templates/vct-nsxv3-agent-deployment.yaml
please merge after nsx-t-exporter bump
> [neutron] use keppel images

- openstack/sre/templates/prometheus-alerts.yaml
Description in the commit messages.
> [SRE] Push alerts to more service channels

- openstack/keystone/templates/ingress-api.yaml
- openstack/keystone/values.yaml
> [Keystone] switch vice-president to kubernetes.io/tls-acme

- openstack/cronus/Chart.yaml
- openstack/cronus/templates/cronus/_config.yaml.tpl
Changing the docker image tage
> change the docker image tag to latest

- prometheus-exporters/vrops-exporter/alerts/datastore.alerts
https://issues.wdf.sap.corp/browse/CCM-14564
> [vrops-exporter] Splitted datastore alert in critical and warning

- openstack/ironic/ci/test-values.yaml
- openstack/ironic/templates/seed.yaml
This reverts commit a8284f4ad40099313fc96f2780b346d5c071b5ed.
No longer needed.
> Revert "Update Seed.yaml (#1718)"

- openstack/nova/alerts/openstack/nova.alerts
Removed the wrong placed slash
> fix links to nova playbooks

- prometheus-exporters/jumpserver-exporter/alerts/jumpserver.alerts
The link to the playbook was not working
> fix link for jumpserver RSA playbook

- system/disco/templates/clusterrole.yaml
a requirement for https://github.com/sapcc/kubernetes-operators/pull/28
> [disco]: update disco clusterrole to watch for services

- openstack/designate/ci/test-values.yaml
- openstack/designate/templates/seeds.yaml
- openstack/domain-seeds/templates/domain-default-seed.yaml
with designate cloud read permissions, requested for Core DNS Team
coreDnsRegistryServicePassword password needs to be set
> [designate][seed] add core_dns_registry

- prometheus-exporters/vrops-exporter/alerts/datastore.alerts
@artherd42 Playbook attached and roll out to InfraOps happend on October 6th.
> Datastoredisconnected

- openstack/cinder/requirements.lock
- openstack/cinder/requirements.yaml
Update the mariadb chart version to 0.2.7
> [Cinder]  Bump the mariadb version to 0.2.7

- global/pulsar/Chart.yaml
- global/pulsar/values.yaml
> [pulsar] replace vice-president

- global/prometheus-alertmanager-operated/Chart.yaml
- global/prometheus-alertmanager-operated/ci/test-values.yaml
- global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl
- global/prometheus-alertmanager-operated/values.yaml
- system/jaeger-operator/templates/openstack-jaeger.yaml
add one service desk pagerduty service on request for monitor of monitors - check with MR was done
pls-check/merge kube-secret on values before
> [alertmanager] add OSD pagerduty keys

- openstack/nova/templates/etc/_nova-scheduler.conf.tpl
- openstack/nova/templates/etc/_nova.conf.tpl
- openstack/nova/values.yaml
Deprecation warnings found in Rocky are cleaned up here.
> Nova cleanup deprecations

- prometheus-exporters/esxi-exporter/templates/deployment.yaml
- prometheus-exporters/esxi-exporter/templates/service.yaml
- prometheus-exporters/esxi-exporter/values.yaml
- system/infra-monitoring/requirements.lock
- system/infra-monitoring/templates/_prometheus-infra-collector.yaml.tpl
- system/infra-monitoring/values.yaml
@richardtief prepared my deployment file for the esxi-exporter per collector. 
Could you please have a look, if this is all I need?
We can also talk about it in person.
> [esxi-exporter] Deployment per Collector

- prometheus-exporters/ucs-exporter/templates/ucs-exporter-deployment.yaml
- system/infra-monitoring/templates/_prometheus-infra-collector.yaml.tpl
- system/infra-monitoring/values.yaml
Signed-off-by: Mithun Gore <mithun.gore@sap.com>
> Add ucs_exporter scrape configs

- prometheus-exporters/ucs-exporter/templates/ucs-exporter-deployment.yaml
Signed-off-by: Mithun Gore <mithun.gore@sap.com>
> Remove liveness probe for ucs-exporter

- prometheus-exporters/apic-exporter/templates/deployment.yaml
- prometheus-exporters/blackbox-exporter/templates/deployment.yaml
- prometheus-exporters/event-exporter/templates/deployment.yaml
- prometheus-exporters/k8s-secrets-certificate-exporter/templates/deployment.yaml
- prometheus-exporters/ns-exporter/templates/daemonset.yaml
- prometheus-exporters/ntp-exporter/templates/daemonset.yaml
- prometheus-exporters/oomkill-exporter/templates/daemonset.yaml
- prometheus-exporters/openstack-exporter/templates/openstack-exporter-deployment.yaml
- prometheus-exporters/ucs-exporter/templates/ucs-exporter-deployment.yaml
- prometheus-exporters/vcsa-exporter/templates/vcsa-exporter-deployment.yaml
- prometheus-exporters/vrops-exporter/templates/vrops-exporter-deployment.yaml
- system/absent-metrics-operator/templates/deployment.yaml
- system/disco/templates/deployment.yaml
- system/node-problem-detector/templates/daemonset.yaml
- system/tiller/templates/deployment.yaml
- system/vice-president/templates/deployment.yaml
This can be merged once the admin cluster is decommissioned. @defo89 FYI
> remove extensions/v1beta1 support everywhere

- common/mariadb/Chart.yaml
- common/mariadb/values.yaml
- improved ui
- adds possibility to start/stop backup via ui
- adds possibility to trigger incremental backup via ui
- adds backup status to ui
- reduces number of files for validation checks
- improves checksum validation
> [mariadb] backup: bumps image

- global/prometheus-alertmanager-operated/Chart.yaml
- global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl
QA regions shall be handled like prod regions for HW break&fix
> [alertmanager] metal : handle QA regions like all prod regions

- prometheus-exporters/esxi-exporter/alerts/service.alerts
Alert if critical service 'hostd' on ESXi is down.
> [esxi-exporter] hostd alert

- openstack/octavia/templates/etc/_esd.json.tpl
Adjusted the template to reflect the CCloud custom "cc_tcp_profile"
> Corrected tcp profile name

- prometheus-exporters/vrops-exporter/alerts/datastore.alerts
split severity by Type //ref: meeting 17.Nov20
fyi @killermoehre @DEiselt
> [vrops-exporter]  split severity DataStoreCapacityCritical

- openstack/cronus/templates/cronus/_config.yaml.tpl
- openstack/cronus/templates/nebula/_config.yaml.tpl
- openstack/cronus/values.yaml
enable audit config support for cronus an nebula
> [cronus]: reflect audit config

- prometheus-exporters/ucs-exporter/alerts/portlicense.alerts
- prometheus-exporters/ucs-exporter/alerts/ucsmchassisfaults.alerts
- prometheus-exporters/ucs-exporter/alerts/ucsmcrcerrors.alerts
Added info alert for CRC errors.
Signed-off-by: Mithun Gore <mithungore@gmail.com>
> Add CRC error alert definition

- system/infra-monitoring/values.yaml
as requested we reviewed the scrapeTimeout
> Adjusted scrapeTimeout for bios and cablechecker

- prometheus-exporters/ucs-exporter/alerts/ucsmcrcerrors.alerts
Signed-off-by: Mithun Gore <mithungore@gmail.com>
> Modify expression for CRC alert

- prometheus-exporters/ucs-exporter/alerts/portlicense.alerts
- prometheus-exporters/ucs-exporter/alerts/ucsmchassisfaults.alerts
- prometheus-exporters/ucs-exporter/alerts/ucsmcrcerrors.alerts
Signed-off-by: Mithun Gore <mithungore@gmail.com>
> Add max_over_time to ucs alerts.

- openstack/swift-utils/templates/account-caretaker-collect-daemonset.yaml
- openstack/swift-utils/templates/account-caretaker-mergify-deployment.yaml
- openstack/swift-utils/templates/caretaker-configmap.yaml
- openstack/swift-utils/templates/secret.yaml
> openstack/swift-utils: use Secret for passwords

- prometheus-exporters/esxi-exporter/alerts/syslog.alerts
- prometheus-exporters/vcsa-exporter/alerts/syslog.alerts
https://issues.wdf.sap.corp/browse/CCM-16485
> Added LostSyslogConnection alert for ESXi and vCSA

- prometheus-exporters/elastic-query-exporter/files/exporter.cfg
> [elastic-query-exporter] Add ES query for node.nodename

- prometheus-exporters/elastic-query-exporter/templates/deployment.yaml
This is a workaround until SSO cert for technical user is available.
> [elastic-query-exporter] Replace pw with apikey authentication

- openstack/swift/templates/proxy-deployment.yaml
* increase resources for proxy
* anti affinity for swift proxies
> Swift refinement

- common/prometheus-server/CHANGELOG.md
- common/prometheus-server/Chart.yaml
upgrade chart, changelog look right?
> [thanos] change to keppel mirror, chart ver, changelog

- openstack/blackbox/charts/blackbox-tests-api/alerts/api.alerts
> added alert of f5 from info to critical

- openstack/blackbox/charts/blackbox-tests-api/alerts/api.alerts
> moved f5 alert from info to critical

- openstack/blackbox/charts/blackbox-tests-api/alerts/api.alerts
> f5 endpoints proper display on slack alert

- prometheus-exporters/vrops-exporter/alerts/virtualmachine.alerts
Updated code for getting alert VROpsDiskpaceUsageCritical.
Please review and approve. -Thanks
> updating alert for vrops db diskspace

- prometheus-exporters/elastic-query-exporter/alerts/logs.alerts
> [elastic-query-exporter] Fix alert expression

- openstack/swift/templates/proxy-deployment.yaml
Reverts sapcc/helm-charts#2210
> Revert "[swift] more power for proxy running on storage nodes"

- openstack/nannies/alerts/vcenter/nanny-vcenter.alerts
> adjusted host_overbooked alert

- system/datahub/values.yaml
- system/elastiflow/vendor/logstash/templates/_jdbc_filter.tpl
- system/elk/vendor/fluent/templates/_fluent.conf.tpl
Now also information from nova is used to enrich the Logs processed by Fluent and Elastiflow.
> [Elastiflow|Fluent] Enhances openstack enrichment

- openstack/cronus/templates/cronus/_config.yaml.tpl
- openstack/cronus/values.yaml
> [cronus]: introduce a "blockedDomains" config list

- prometheus-exporters/vrops-exporter/templates/vrops-inventory-deployment.yaml
- prometheus-exporters/vrops-exporter/values.yaml
inventory is way faster now and we can go all in
> [vrops-exporter] adding new sleep and timout defaults

- system/sentry/templates/_env.tpl
Add more env variables to configure cronus
> [cronus]: use cronus to send sentry emails

- openstack/swift/alerts/openstack/api.alerts
See here https://prometheus-openstack.eu-nl-1.cloud.sap/graph?g0.expr=sum(increase(swift_proxy_count%7Bpolicy%3D%22all%22%2C%20status%3D%22503%22%7D%5B5m%5D))%20by%20(os_cluster)&g0.tab=0&g0.stacked=0&g0.range_input=1h
> [swift] More accurate 503 alerting

- openstack/cronus/templates/cronus/deployment.yaml
- openstack/cronus/values.yaml
* Switch cronus to a deployment method
* Allow maxSurge while a new deployment is released
> Cronus new deployment method

- system/kube-system-metal/Chart.yaml
- system/kube-system-metal/values.yaml
Ensuring the podAntiAffnity with updated label key
> [kube-system-metal] fix antiAffinity label keys

- openstack/cronus/files/nginx.tmpl
- openstack/cronus/values.yaml
Add a support for realIP in streams section
> [cronus]: add support for real IP in nginx stream section

- openstack/arc/templates/seed.yaml
- openstack/barbican/requirements.lock
- openstack/barbican/templates/seed.yaml
- openstack/billing/templates/seeds.yaml
- openstack/cinder/templates/seed.yaml
- openstack/designate/templates/seeds.yaml
- openstack/domain-seeds/templates/domain-cis-seed.yaml
- openstack/elektra/templates/seed.yaml
- openstack/hermes/templates/keystone-seed.yaml
- openstack/ironic/templates/seed.yaml
- openstack/keppel/templates/seed.yaml
- openstack/keppel/templates/support_seed.yaml
- openstack/limes/templates/seed.yaml
- openstack/limes/templates/support_seed.yaml
- openstack/maia/templates/seed.yaml
- openstack/manila/templates/seeds.yaml
- openstack/neutron/templates/seed.yaml
- openstack/nova/templates/seed.yaml
- openstack/sap-seeds/templates/nova-seed.yaml
- openstack/swift-utils/templates/seed.yaml
- openstack/swift/templates/support_seed.yaml
Hi @Carthaca,
Please validate the PR.
Regards,
Rajiv
> [Domain-Seeds] Adding CIS Domain seeds

- openstack/nannies/values.yaml
> [vm_balance]: fix vm_restart issue

- openstack/elektra/ci/test-values.yaml
- openstack/elektra/templates/seed.yaml
> [Elektra][Seeds] Adding CIS Domain

- openstack/nannies/values.yaml
> [nannies]: to monitor server_creation time

- openstack/domain-seeds/README.md
- openstack/domain-seeds/ci/test-values.yaml
- openstack/domain-seeds/templates/domain-bs-seed.yaml
- openstack/domain-seeds/templates/domain-cis-seed.yaml
- openstack/domain-seeds/templates/domain-cp-seed.yaml
- openstack/domain-seeds/templates/domain-fsn-seed.yaml
- openstack/domain-seeds/templates/domain-global-seed.yaml
- openstack/domain-seeds/templates/domain-hcm-seed.yaml
- openstack/domain-seeds/templates/domain-hcp03-seed.yaml
- openstack/domain-seeds/templates/domain-hec-seed.yaml
- openstack/domain-seeds/templates/domain-kubernikus-seed.yaml
- openstack/domain-seeds/templates/domain-monsoon3-seed.yaml
- openstack/domain-seeds/templates/domain-neo-seed.yaml
- openstack/domain-seeds/templates/domain-s4-seed.yaml
- openstack/domain-seeds/templates/domain-wbs-seed.yaml
- openstack/domain-seeds/values.yaml
keystone and designate deployment; update readme.
Related to https://github.com/sapcc/helm-charts/commit/0918fc72b02cd596c80c8c1764921c68c44b9453
> [seeds] adds global domain and configures a switch for multi-regional

- openstack/cronus/templates/cronus-simulator/_config.yaml.tpl
The change is in cronus-simulator, adding new flags to support v0.0.3
> add new flags to cronus-simulatior to support changes in version v0.0.3

- prometheus-exporters/ucs-exporter/alerts/ucsmcrcerrors.alerts
- prometheus-exporters/ucs-exporter/templates/ucs-config.yaml
- prometheus-exporters/ucs-exporter/templates/ucs-exporter-deployment.yaml
- system/infra-monitoring/values.yaml
crc error alert definition modified to notify absent alerts and
to get increased value by 100 in 30 min.
Scrape interval is reduced since cacheing is happening.
Config is changed from yaml to json
Signed-off-by: Mithun Gore <mithungore@gmail.com>
> Modify alert definition, scrape interval, config type

- common/mariadb/templates/_helpers.tpl
https://github.com/sapcc/helm-charts/issues/2283
> [common][mariadb] remove derived password helper functions.

- openstack/swift/templates/etc/_haproxy.cfg.tpl
> [swift] haproxy - use different backend for s3

- openstack/neutron/templates/etc/_ironic_neutron_agent.ini.tpl
Hi @notandy,
Please validate this PR, its related to https://github.com/sapcc/helm-charts/issues/2293
Regards,
Rajiv
> [Neutron] Remove master_password

- openstack/keystone/templates/etc/_policy.yaml.tpl
Reintroduce rule:owner and rule:token_subject to fix credentials and token-validation endpoints
> [keystone] Yaml policies fix

- openstack/keystone/templates/etc/_policy.yaml.tpl
> [keystone] add default policies as comments for comparison

- openstack/barbican/alerts/openstack-barbican.alerts
Hi @developer-abhi,
Regards,
Rajiv
> [Barbican] Add Canary Alerts

- openstack/neutron/templates/etc/_ml2-conf-aci.ini.tpl
Subgroups or direct-mode hostgroups (hostgroups with setting
direct_mode = True) can now be specified. They belong to a parent group
and allow single nodes to be switched between infrastructure mode and
baremetal mode inside the ACI driver.
> [neutron] Add subgroups to ACI config

- global/prometheus-alertmanager-operated/Chart.yaml
- global/prometheus-alertmanager-operated/ci/test-values.yaml
- global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl
add prod gcp instance - please be aware of kube-secret update (new key)
please consider to merge pending PR https://github.com/sapcc/helm-charts/pull/2241 before
> [alertmanager] update route for MoM

- global/prometheus-alertmanager-operated/Chart.yaml
- global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl
follow up to https://github.com/sapcc/helm-charts/pull/2438
> [alertmanager] fix qa routing

- prometheus-exporters/vrops-exporter/templates/collector-configmap.yaml
Reverts sapcc/helm-charts#2466
> Revert "[vrops-exporter] added NSXTMmgtClusterStatsCollector to default collectors"

- openstack/neutron/templates/etc/_dnsmasq.conf.tpl
- openstack/neutron/values.yaml
Reverts sapcc/helm-charts#2444
> Revert "Add dhcp options for dnsmasq process in neutron-dhcp-agent."

- openstack/swift/ci/test-values.yaml
- openstack/swift/templates/etc/_object-expirer.conf.tpl
- openstack/swift/templates/object-expirer-deployment.yaml
- openstack/swift/values.yaml
* Introduce tasks_per_second with Wallaby to rate limit the expirer
* Support to spread out the work accross mor expirer processes
> [Swift] object-expirer

- openstack/nannies/templates/vm-balance-nanny-secrets.yaml
> [nannies]: some fix in prometheus client_key name

- openstack/nannies/templates/vm-balance-nanny-secrets.yaml
> [nannies]: adjusted handle case if prom key/cert not exist

- openstack/nannies/templates/vm-balance-nanny-deployment.yaml
- openstack/nannies/templates/vm-balance-nanny-secrets.yaml
- openstack/nannies/templates/vm-balance-nanny-vc-secrets.yaml
> [nannies]: vm_balance_nannies change in secret structure

- openstack/sap-seeds/templates/flavor-seed.yaml
I reduced the disk size by error during flavor renaming.
> [flavors] Restore disk size for m5.xlarge2hdd private flavor

- openstack/nannies/values.yaml
> [nannies]: vm_balance nannies bug fix

- openstack/nannies/values.yaml
> [nannies]: new vm_balance nannies with fix and new feature

- openstack/nannies/values.yaml
> [nannnies]: vm_balance version update with metrics value changes

- global/prometheus-alertmanager-operated/Chart.yaml
- global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl
enable alert routing  for documentation alerts to service channel
> [alertmanager-routing] add documentation service

- openstack/nannies/values.yaml
> [vm_balance]: new version of nannie with monitoring vmotion count

- openstack/nannies/values.yaml
> [vm_balance]: new version of nannies with fix

- openstack/nannies/values.yaml
> [nannies]: vm_balance new version with bug_fix

- openstack/nannies/alerts/vcenter/nanny-vcenter.alerts
> [nannies]: vm_balance alert adjusted

- openstack/nannies/alerts/vcenter/nanny-vcenter.alerts
> [nannies]: alert adjusted

- prometheus-exporters/vrops-exporter/alerts/host.alerts
Reverts sapcc/helm-charts#2527
> Revert "Revert "vrops-exporter: HostWithRunningVMsNotResponding changed running VM metric""

- prometheus-exporters/vrops-exporter/alerts/nsxt.alerts
Added alerts for NSX-T monitoring. Used 80/95% for warning/critical.
Waiting for Operations to check thresholds.
> [vrops-exporter] New NSX-T alerts

- prometheus-exporters/openstack-exporter/templates/openstack-exporter-openstack-config.yaml
- prometheus-exporters/openstack-exporter/templates/openstack-exporter-seed.yaml
This patch enables the new nova service collector.
> [openstack-exporter] Enable nova service collector

- openstack/cronus/Chart.yaml
- openstack/cronus/files/nginx.tmpl
- openstack/cronus/requirements.yaml
- openstack/cronus/values.yaml
enable starttls and proxying smtp auth: http://nginx.org/en/docs/mail/ngx_mail_proxy_module.html#proxy_smtp_auth
> [cronus]: enable starttls support for smtp

- prometheus-exporters/vrops-exporter/alerts/datastore.alerts
> vrops-exporter: changed NVMe 85% warning to 100%

- openstack/blackbox/charts/blackbox-tests-canary-nova/templates/secret.yaml
> [blackbox]: removed orphaned value from blackbox chart

- system/elastiflow/vendor/logstash/templates/_jdbc_filter.tpl
- Enrich Source IP with Openstack Data
- Enrich Destination IP with Openstack Data
- Add overarching field that that contains both (if available)
> [Elastiflow] Adds openstack enrichment to destination and source.

- openstack/nova/templates/seed.yaml
See commits for detailed description, please.
> [nova] Add cloud_volume_admin and swiftoperator roles

- system/elastiflow/vendor/logstash/alerts/elastiflow-logstash.alerts
Added an alert to detect high rate changes in pipeline events
> Added an alert to detect high rate changes in pipeline events

- openstack/cc3test-seeds/templates/project-seed.yaml
- openstack/cc3test-seeds/values.yaml
WIP, adjustment in router and rbac policy left.
> [blackbox]: project seeding for cc3test

- openstack/cc3test-seeds/templates/project-seed.yaml
- openstack/cc3test-seeds/values.yaml
> [blackbox]: project_seed in cc3test

- openstack/cc3test-seeds/templates/project-seed.yaml
> [blackbox]: some indentation fix

- openstack/cronus/templates/cronus/_config.yaml.tpl
- openstack/cronus/values.yaml
This PR introduces new SMTP backend options and new default RBAC policies.
> [cronus]: new smtp backend and policy options

- openstack/cc3test-seeds/templates/project-seed.yaml
> [blackbox]: added seperator between seeder resources

- openstack/octobus/Chart.yaml
- openstack/octobus/templates/seeds.yaml
> octobus project permissions updated

- common/prometheus-alertmanager-base/Chart.yaml
- common/prometheus-alertmanager-base/notification-templates/slack.tmpl
> [alerting] slack tmpl update; add report link

- global/prometheus-alertmanager-operated/Chart.lock
- global/prometheus-alertmanager-operated/Chart.yaml
slack template change
request by @artherd42
> [alertmanager] bump new base version

- system/sentry/templates/_env.tpl
> [sentry]: support starttls

- openstack/limes/aggregations/openstack/consolidation.rules
Needed for a new global dashboard
> [limes] aggregate per AZ metrics in global prometheus

- prometheus-exporters/vrops-exporter/alerts/datastore.alerts
- prometheus-exporters/vrops-exporter/alerts/host.alerts
- prometheus-exporters/vrops-exporter/alerts/monitoring.alerts
- prometheus-exporters/vrops-exporter/alerts/nsxt.alerts
- prometheus-exporters/vrops-exporter/alerts/vccluster.alerts
- prometheus-exporters/vrops-exporter/alerts/vcenter.alerts
- prometheus-exporters/vrops-exporter/alerts/virtualmachine.alerts
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/i520251/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/i520251/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
</head>
<body link=blue vlink=purple>
name | Priority | adapterKindKey | resourceKindKey
-- | -- | -- | --
VASA Provider(s) disconnected | 1 | VMWARE | VMwareAdapter Instance
Virtual machine disk I/O read   latency is high | 1 | …
> [vrops-exporter] added vmware alert set prio 1

- openstack/keystone/Chart.yaml
@bbobrov shall we update the chart version to 0.3.0 maybe ?
> [Keystone] update app version to train

- global/prometheus-infra/templates/_prometheus.yaml.tpl
adding vrops_cluster_cpu_contention_percentage to federation to create a global overview
> add vrops_cluster_cpu_contention_percentage

- prometheus-exporters/vrops-exporter/alerts/nsxt.alerts
added playbook for `NSXTNodeMemoryUsageOver95` alert
> [vrops-exporter] added playbook for NSXTNodeMemoryUsageOver95 alert

- openstack/hermes/alerts/hermes.alerts
> metrics moved from control plane to scaleout

- openstack/designate/alerts/api.alerts
@galkindmitrii : please approve this
> blackbox metrics moved control plane to scaleout

- system/kube-monitoring-admin-k3s/Chart.lock
- system/kube-monitoring-admin-k3s/Chart.yaml
- system/kube-monitoring-admin-k3s/values.yaml
- system/kube-monitoring-kubernikus/Chart.lock
- system/kube-monitoring-kubernikus/Chart.yaml
- system/kube-monitoring-kubernikus/values.yaml
**NOTE TO SELF**: Don't forget the kube-secrets.git values PR before deployment.
> [kube-monitoring-kubernikus][kube-monitoring-admin-k3s] bump prometheus operator dependency

- openstack/nova/requirements.lock
- openstack/nova/requirements.yaml
Also fixes a bug that breaks the restore functionality
> [nova]bump mariadb requirement to fix missing segment expiry

- prometheus-exporters/elk-query-exporter/alerts/elk-query.alerts
Hi @Kuckkuck,
Please validate/approve this PR.
Regards,
Rajiv
> [Glance] Add OpenstackGlanceReturn50xCode Alert

- common/redis/Chart.yaml
- common/redis/values.yaml
> [Redis] Set resource values for metrics containers

- prometheus-exporters/vrops-exporter/alerts/nsxt.alerts
Few NSXT alerts uplifted to Warning
> Few NSXT alerts uplifted to Warning

- openstack/nova/templates/etc/_nova-scheduler.conf.tpl
- openstack/nova/values.yaml
We want to schedule small VMs preferred on small HVs and we don't want normal/larger VMs to schedule on small HVs.
> [nova]: Scheduling small to small

- prometheus-exporters/vrops-exporter/alerts/nsxt.alerts
NSX-T Transport Node alert conditions added.
> [vrops-exporter] nsxt alert conditions added

- openstack/cinder/values.yaml
This patch changes AffinityFilter to included the 2 child filters
DifferentBackendFilter and SameBackendFilter
> [Cinder] Update Cinder filters

- openstack/cronus/templates/nebula/_config.yaml.tpl
- openstack/cronus/values.yaml
> [cronus]: email scheduling variables

- prometheus-exporters/elk-query-exporter/alerts/elk-query.alerts
- prometheus-exporters/elk-query-exporter/files/elasticsearch_octobus_exporter_error.cfg
* query: longer timeout
* query: move all conditions to filter to ensure AND and avoid scoring
* query: use term filter on keyword field
* alert: add error message from label to alert description
> [elk-query-exporter] Adjust query_elasticsearch_octobus_exporter_error

- openstack/keystone/requirements.lock
- openstack/keystone/requirements.yaml
- openstack/keystone/templates/configmap-etc.yaml
- openstack/keystone/templates/deployment-api.yaml
- openstack/keystone/templates/etc/_ratelimit.yaml.tpl
- openstack/keystone/values.yaml
Hi @bbobrov,
Please validate and approve.
> [Keystone] Enable rate-limiting middleware

- global/prometheus-kubernetes-global/values.yaml
Reverts sapcc/helm-charts#2855
> Revert "[cronus] enable cronus metrics"

- system/gatekeeper-config/templates/config-high-cpu-requests.yaml
- system/gatekeeper/templates/constraint-high-cpu-requests.yaml
Report violations exclusively on Pod level.
> system/gatekeeper: simplify GkHighCPURequests

- openstack/manila/templates/etc/_manila.conf.tpl
@galkindmitrii  @chuan137  review
> Add netapp_volume_snapshot_reserve_percent in manila.conf [default]

- openstack/nannies/values.yaml
@chuan137  @galkindmitrii  review
> [nannies] Bump manila nanny version for snapreserve

- system/gatekeeper/templates/constraint-deprecated-api-versions.yaml
- system/gatekeeper/templates/constraint-images-from-correct-registry.yaml
- system/gatekeeper/templates/constraint-ingress-annotations.yaml
- system/gatekeeper/templates/constraint-prometheus-scrape-annotations.yaml
- system/gatekeeper/templates/constraint-region-value-missing.yaml
- system/gatekeeper/templates/constraint-resource-limits.yaml
- system/gatekeeper/templates/constraint-vulnerable-images.yaml
Ran `opa fmt` and made minor syntax improvements.
> system/gatekeeper: improve rego syntax

- openstack/barbican/alerts/openstack-barbican.alerts
@rajivmucheli @geisslet : Please approve this, as metrics moved from cp to scaleout cluster
> metrics moved from cp to scaleout cluster

- openstack/elektra/charts/postgresql/values.yaml
- openstack/elektra/ci/test-values.yaml
Still supports PG 9.5 which we use in Elektra
> upgrade metric image to latest tagged with version

- openstack/manila/templates/shares/_share-netapp.conf.tpl
@chuan137 @galkindmitrii  review
> [Manila] Enable net_capacity for snapreserve

- prometheus-exporters/image-usage-exporter/Chart.yaml
version bump again for deployment to update
> FIX: data for same image was overwritten

- global/prometheus-alertmanager-operated/Chart.yaml
- global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl
on request and with permission from M.
fyi @artherd42
> [alertmanager] extend alert sending

- openstack/neutron/templates/asr_config_agents/_deployment-asr1k.yaml.tpl
- openstack/neutron/templates/bin/_neutron-asr1k-start.tpl
- openstack/neutron/templates/bin/_neutron-server-start.tpl
- openstack/neutron/templates/configmap-etc.yaml
- openstack/neutron/templates/deployment-server.yaml
- openstack/neutron/templates/etc/_asr1k-global.ini.tpl
- openstack/neutron/templates/etc/_asr1k.conf.tpl
- openstack/neutron/templates/etc/_ml2-conf-aci.ini.tpl
- openstack/neutron/templates/etc/_uwsgi.ini.tpl
- openstack/neutron/values.yaml
See commit messages for details.
Except some new lines, there is no exterior change to the rendered configmaps.
> Simplify Neutron Variable Files

- openstack/octavia/templates/etc/_policy.json.tpl
Should be fine to be merged before rollout since the new policies won't have an effect there.
> [octavia] adapt for octavia ussuri policies

- openstack/swift/values.yaml
See commit messages for release notes
> swift: upgrade memcached

- prometheus-exporters/elastic-query-exporter/alerts/logs.alerts
This reverts commit e4a679a82f14b6e8ec3b31ae51442f616b811b40.
> Revert "[elastic-query-exporter] Disable log shipping alerts for apods"

- openstack/octavia/templates/etc/_octavia-worker.conf.tpl
Works just like `sync_to_group`.
> [octavia] Template availability zone

- openstack/manila/templates/shares/_share-netapp.conf.tpl
Need to set the field to 0 for the hypervisor_storage filers.
> [manila] allow filer's individual setting: netapp_volume_snapshot_reserve_percent

- openstack/manila/templates/shares/_share-netapp.conf.tpl
@galkindmitrii @chuan137 review
> [Manila] Enable logical space reporting

- global/prometheus-infra/templates/_prometheus.yaml.tpl
- system/prometheus-infra/templates/_prometheus-infra.yaml.tpl
Reverts sapcc/helm-charts#2939
> Revert "[vrops-exporter] make vm tool version metric globally available"

- common/prometheus-server/Chart.yaml
- common/prometheus-server/templates/alerts/_prometheus.alerts.tpl
Template shenenangins are untested. Playbook is non existent.
> prometheus-server: Add alert when targets are scraped multiple times

- prometheus-exporters/elastic-query-exporter/alerts/logs.alerts
- prometheus-exporters/elastic-query-exporter/files/elasticsearch_octobus_vcsa.cfg
- prometheus-exporters/elastic-query-exporter/files/qa/elasticsearch_octobus_vcsa.cfg
* Actually alert when metric is zero
* Don't request hits
* Change query from match text field to prefix keyword field
* Search recent data
> [elastic-query-exporter] Adjust OctobusVCSALogShippingNotWorking

- openstack/cronus/templates/nebula/_config.yaml.tpl
- openstack/cronus/values.yaml
new config option for int SMTP API
new config option for deletion notification template
> [cronus]: introduce intSMTP and deletion template for nebula

- openstack/cronus-seed/templates/seed.yaml
- openstack/cronus/Chart.yaml
- openstack/cronus/templates/cronus/_config.yaml.tpl
- openstack/cronus/values.yaml
this PR enables rabbitmq queue for emails processing in cronus
> [cronus]: enable email queue config

- system/kube-system-metal/Chart.yaml
- system/kube-system-metal/templates/ingress-external-public-service-monitor.yaml
Promote alert to critical
And bump chart
> Add a link to playbook for CCM-26353.

- openstack/limes/templates/_utils.tpl
- openstack/limes/templates/api-deployment.yaml
- openstack/limes/templates/collect-deployment.yaml
- openstack/limes/templates/configmap.yaml
This PR depends on https://github.com/sapcc/limes/pull/120
> openstack/limes: use env variables for config

- prometheus-exporters/vrops-exporter/alerts/host.alerts
> Raise HADetectedAPossibleHostFailure to critical

- openstack/manila/alerts/openstack-manila.alerts
- openstack/manila/values.yaml
For share_servers stuck in creating, error, error_manage and
error_unmanage.
> [Manila] Add metric and alert for share_servers.

- global/prometheus-infra/templates/_prometheus.yaml.tpl
Adding DVS version to global Prometheus for global compute version overview.
> Adding DVS version to global federation

- openstack/manila/templates/etc/_manila.conf.tpl
Based on reading from
https://docs.openstack.org/releasenotes/manila/wallaby.html and https://docs.openstack.org/releasenotes/manila/xena.html
@galkindmitrii  check
> [Manila] Changes to support Xena release

- system/elk/values.yaml
- system/elk/vendor/logstash-audit-external/templates/_logstash.conf.tpl
- [ELK] Fixes audit index to create daily indices
- [ELK] Adds duplication of audit events to elk & octobus
> [ELK] Fixes index creation & Adds duplication of events to octobus"

- openstack/cc3test/alerts/compute.alerts
> [cc3test]: adjust alert with failed bb description

- openstack/nova/templates/console-ingress.yaml
- openstack/nova/templates/consoleauth-deployment.yaml
- openstack/nova/templates/etc/_nova.conf.tpl
- openstack/nova/values.yaml
Added a config-option for enabling individual console types
and disable vnc by default
> [nova] Console Enable/Disable, disable vnc by default

- prometheus-exporters/vrops-exporter/alerts/host.alerts
HA failover alert uplifted to critical
> HA failover alert uplifted to critical

- global/prometheus-infra/templates/_prometheus.yaml.tpl
cablecheck and bios_exporter are not around anymore
> adding jump sessions, remove obsolete

- prometheus-exporters/vrops-exporter/templates/collector-configmap.yaml
https://blogs.vmware.com/management/2020/01/rightsizing-vms-with-vrealize-operations.html
> [vrops-exporter] rightsizing vm metrics added

- prometheus-exporters/statsd-exporter/templates/deployment.yaml
@artherd42 : please approve this
> added liveness/readiness probe

- openstack/octavia/Chart.lock
- openstack/octavia/Chart.yaml
- openstack/octavia/values.yaml
This is not yet official, but it's coming soon. There is already a DOOP policy
> [octavia] Add owner metadata

- prometheus-exporters/statsd-exporter/values.yaml
> disable cert authentication for statd exporter

- openstack/cc3test/alerts/ccloud-automation.alerts
> added alert for arc_broker cert

- system/multicloudtest/templates/cronjob.yaml
> added ttl to cleanup orphaned job/pod

- prometheus-exporters/network-generic-ssh-exporter/templates/_config.yaml.tpl
> New filter added for fetching the configured ntp server details from ios-xr platform routers
> filter for the ntp server config from ios-xr

- prometheus-exporters/network-generic-ssh-exporter/templates/_config.yaml.tpl
Adjusted ntp config filter to have both peer and server details. Associated labels as well.
> adjusted ntp config filter 

- openstack/octobus/templates/seeds.yaml
This is required to complete a PCI-DSS topic for openstack swift container access
> Add technicalUserSwiftOperator to seeds

- common/rabbitmq/Chart.yaml
- common/rabbitmq/templates/_helpers.tpl
- common/rabbitmq/templates/deployment.yaml
limit number of rabbitmq restarts during kubernetes node reinstall
> [common][rabbitmq] add rabbitmq_node_reinstall_affinity

- system/infra-monitoring/values.yaml
> remove master nodes from probing target list

- prometheus-exporters/octobus-query-exporter/templates/alerts/_audit.tpl
- prometheus-exporters/octobus-query-exporter/templates/prometheus-alerts.yaml
- prometheus-exporters/octobus-query-exporter/values.yaml
- removes file suffix from PrometheusRule name
- includes audit alerts as template
> [ElasticQueryExporter] Adds alerts for audit logs

- system/infra-monitoring/vendor/atlas/templates/configmap.yaml
- system/infra-monitoring/vendor/atlas/values.yaml
to fix prometheus sd header content
> [infra-monitoring] bumps atlas image

- prometheus-exporters/vrops-exporter/alerts/vccluster.alerts
Playbook PR is already raised, will add when raising this alert to warning.
> [vrops-exporter] Cluster DRS alert

- openstack/keystone/requirements.lock
- openstack/keystone/requirements.yaml
- openstack/keystone/values.yaml
use alternate registry for memcached
> [keystone] helm outdated-dependencies update

- openstack/cronus/Chart.yaml
- openstack/cronus/templates/cronus/_config.yaml.tpl
- openstack/cronus/values.yaml
> [cronus]: introduce proxy protocol header timeout

- openstack/ironic/templates/_conductor-deployment.yaml.tpl
new livenessProbe checks if the conductor is listed as consumer in the rabbitmq.
> [ironic] changes conductor livnessprobe

- prometheus-exporters/vrops-exporter/alerts/vccluster.alerts
As requested by Operations team.
> [vrops-exporter] Raise VCClusterDRSNotFullyAutomated to warning

- prometheus-exporters/cronus-updater/templates/_config.yaml.tpl
updater didn't include CC emails from config
> [cronus]: add cc emails while interacting with support tickets

- openstack/cc3test/alerts/dns.alerts
related to https://github.wdf.sap.corp/cc/cc3test/issues/111
> dns lookup on sap name servers

- openstack/nannies/alerts/vcenter/nanny-vcenter.alerts
> [vm_balance_nannies]: disbale all alert for vm_balance nannies

- openstack/manila/templates/etc-configmap.yaml
- openstack/manila/templates/etc/_manila.conf.tpl
- openstack/manila/templates/scheduler-deployment.yaml
- openstack/manila/templates/shares/_netapp-deployment.yaml.tpl
- openstack/manila/values.yaml
to collect stats about rpc messages via oslo.messaging
> [manila] optionally add statsd to scheduler and share deployment

- prometheus-exporters/cronus-updater/templates/_config.yaml.tpl
- prometheus-exporters/cronus-updater/templates/deployment.yaml
- prometheus-exporters/cronus-updater/templates/service.yaml
- prometheus-exporters/cronus-updater/values.yaml
https://github.wdf.sap.corp/cronus/cronus-updater/commit/a124e45b20cffb52c34d0dc501f302515b779320
> Updater removing pushgateway

- prometheus-exporters/network-generic-ssh-exporter/templates/_config.yaml.tpl
- prometheus-exporters/network-generic-ssh-exporter/templates/deployment.yaml
- prometheus-exporters/network-generic-ssh-exporter/values.yaml
> Make chart compatible with ssh-exporter in version that supports lookups

- openstack/cc3test/alerts/dns.alerts
due to approval from GNOC team in https://issues.wdf.sap.corp/browse/CCM-29380
> raise severity to critical

- openstack/cc3test/alerts/compute.alerts
@artherd42 : please approve this.
> added alert for server stop_start, resize, userdata alert to info level

- openstack/nova/templates/etc-configmap.yaml
- openstack/nova/templates/etc/_nova-scheduler.conf.tpl
- openstack/nova/templates/scheduler-deployment.yaml
- openstack/nova/templates/scheduler-etc-configmap.yaml
- openstack/nova/values.yaml
Please have a look at the individual commits for more details.
> [nova] Use Placement filter instead of Availability Zone Filter

- openstack/keystone/alerts/openstack/keystone.alerts
This alert helps monitor keystone api requests ops/s
> [Keystone][Alert] Introduce OpenstackKeystoneApiRequestsExceeded

- openstack/nannies/templates/manila-nanny-deployment.yaml
- openstack/nannies/values.yaml
- Add support of handling stuck shares and snapshots
> update manila nanny version (20220420145112)

- global/prometheus-infra/templates/_prometheus.yaml.tpl
As requested by VMware for vMotion Overview Dashboard
> [prometheus-infra.global] Adding vrops cluster DRS behaviour

- openstack/tempest/cinder-tempest/Chart.yaml
- openstack/tempest/cinder-tempest/templates/bin/_tempest-start-and-cleanup.sh.tpl
- openstack/tempest/cinder-tempest/templates/configmap-etc-tempest.yaml
- openstack/tempest/cinder-tempest/templates/etc/_tempest_extra_options.tpl
- openstack/tempest/designate-tempest/Chart.yaml
- openstack/tempest/keystone-tempest/Chart.yaml
- openstack/tempest/keystone-tempest/templates/bin/_tempest-start-and-cleanup.sh.tpl
- openstack/tempest/keystone-tempest/templates/etc/_tempest_accounts.yaml.tpl
- openstack/tempest/manila-tempest/Chart.yaml
- openstack/tempest/neutron-tempest/templates/bin/_tempest-start-and-cleanup.sh.tpl
- openstack/tempest/neutron-tempest/templates/etc/_tempest_accounts.yaml.tpl
- openstack/tempest/nova-tempest/templates/bin/_tempest-start-and-cleanup.sh.tpl
- openstack/tempest/nova-tempest/templates/etc/_tempest_accounts.yaml.tpl
- openstack/tempest/nova-tempest/templates/tempest-pod.yaml
- openstack/tempest/octavia-tempest/templates/bin/_tempest-start-and-cleanup.sh.tpl
- openstack/tempest/tempest-base/templates/_tempest-pod.yaml.tpl
- openstack/tempest/tempest-base/templates/bin/_function_start_tempest_tests.tpl
- openstack/tempest/tempest-base/templates/etc/_tempest_extra_options.tpl
* Fix cleanup for keystone
* Fix cleanup for cinder
* Add api version for charts
* Fix cleanup for nova
* Add primary roles
> Multiple fixes for tempest:

- openstack/cronus/templates/cronus/_config.yaml.tpl
- openstack/cronus/values.yaml
This PR introduces a new config for identity validation
> [cronus]: introduce support for identity validation

- openstack/cronus/templates/cronus/_config.yaml.tpl
- openstack/cronus/values.yaml
To block URLs and corresponding HTTP methods
> [cronus]: add new config options for URL checks

- openstack/cronus/templates/cronus/_config.yaml.tpl
Add an ability to define global request values
> [cronus]: support global requestValidate

- openstack/cronus/templates/cronus/_config.yaml.tpl
- openstack/cronus/templates/nebula/_config.yaml.tpl
- openstack/cronus/values.yaml
> [cronus]: update hermes secrets dependencies

- openstack/cc3test/alerts/compute.alerts
> added alert for host_status in cc3test

- openstack/nova/alerts/openstack/nova.alerts
alert moved to cc3test https://github.com/sapcc/helm-charts/pull/3502/commits/5803ba927a4e7e36b9b7041d13730bff75963a0e @joker-at-work please approve this.
> compute_host_status moved to cc3test

- openstack/nannies/requirements.lock
- openstack/nannies/templates/manila-filers.yaml
- openstack/nannies/templates/manila-nanny-deployment.yaml
- openstack/nannies/templates/manila-nanny-secrets.yaml
- openstack/nannies/values.yaml
Extra secrets for netapp api user/password. And extra configmap for
netapp filers list.
> [nannies][manila] add snapshot-missing nanny

- openstack/keystone/requirements.lock
- openstack/keystone/requirements.yaml
This is needed to use a jaeger version from keppel
> [keystone] update utils version to the latest

- openstack/cronus/templates/cronus/_config.yaml.tpl
and extend sesV1CheckKeys values to support JSON lists
> [cronus]: add sesV2CheckKeys config support

- openstack/blackbox/charts/blackbox-tests-canary-nova/templates/deployment.yaml
> replica to zero

- openstack/nova/alerts/openstack/nova.alerts
@joker-at-work : please approve this.
> moved alert from blackbox to cc3test

- prometheus-exporters/cronus-updater/templates/_config.yaml.tpl
- prometheus-exporters/cronus-updater/values.yaml
Change cronus-updater config to support new internal contact list
https://github.wdf.sap.corp/cc/secrets/pull/8911
> cronus-updater - modified helm based on updater changes in contact list

- prometheus-exporters/vrops-exporter/alerts/datastore.alerts
InfraOps wants to lower the threshold.
> Alert NVMeDataStoreFullyUtilised threshold decreased

- openstack/cinder/values.yaml
This patch enable the new affinity/anti-affinity filters.
SAPSameBackendFilter
SAPDifferentBackendFilter
> [Cinder] Enable SAP Affinity filters

- openstack/cinder/requirements.lock
- openstack/cinder/requirements.yaml
This patch updates the requirements.yml for
utils
mariadb
rabbitmq
redis
> [Cinder] update helm chart requirements

- openstack/placement/Chart.lock
- openstack/placement/Chart.yaml
- openstack/placement/ci/test-values.yaml
- openstack/placement/templates/_helpers.tpl
- openstack/placement/templates/etc-configmap.yaml
- openstack/placement/templates/etc/_placement.conf.tpl
- openstack/placement/templates/etc/_uwsgi.ini.tpl
- openstack/placement/templates/placement-api-deployment.yaml
- openstack/placement/templates/placement-api-service.yaml
- openstack/placement/templates/placement-ingress.yaml
- openstack/placement/templates/prometheus-aggregations.yaml
- openstack/placement/templates/prometheus-alerts.yaml
- openstack/placement/templates/seed.yaml
- openstack/placement/templates/sentry.yml
- openstack/placement/values.yaml
This deploys the placement api service.
Currently only tested with rocky, and using the nova_api database
from the nova chart.
> Placement: Initial version

- openstack/placement/Chart.lock
- openstack/placement/Chart.yaml
- openstack/placement/values.yaml
With the updated dependency, we can remove the postgresql section
> [placement] Remove postgres item

- openstack/utils/templates/_hosts.tpl
Instead of copy and pasting the same suffix around
use a common macro
> openstack.utils: DRY fqdn expansion

- openstack/cronus-seed/templates/seed.yaml
Adjust roles with new Swift Yoga release (see #3484)
> [cronus]: update swift roles

- openstack/nova/templates/placement-db-finalize-split-job.yaml
- openstack/nova/templates/placement-db-split-job.yaml
- openstack/nova/templates/placement-db-unsplit-job.yaml
The proper registry is dockerHubMirror, not registry
> [placement] Fix registry for unified-toolbox

- openstack/cc3test/alerts/network.alerts
> added network FIP exhausted check

- prometheus-exporters/vrops-exporter/alerts/host.alerts
This alert was requested by InfraOps team to monitor storage Path for any host.
> Adding alert for  all storage Path down for  any given host.

- openstack/nova/values.yaml
Remove placement and the finalise step to finish
the split
> [nova] Disable placement

- openstack/cerebro/initial-quota.yaml
- Adjustment for sg/hm/l7policies/listeners/pools to be 2x the # of Loadbalancers
> Cerebro LB quota adjustment

- openstack/cinder/templates/etc/_cinder.conf.tpl
- openstack/cinder/values.yaml
This updates the values and the template generation for
setting the scheduler_default_weighers and the options for the
CapacityWeigher and AllocatedCapacityWeigher
> [Cinder] Add ability to change the weighers

- common/rabbitmq/ci/test-values.yaml
- common/rabbitmq/templates/bin/_rabbitmq-start.tpl
- common/rabbitmq/templates/deployment.yaml
- common/rabbitmq/templates/statefulset.yaml
- common/rabbitmq/values.yaml
Change the script to call rabbitmq less often. All the changes except on-line reconfiguration.
> [common/rabbitmq] Optimise startup script

- common/thanos/Chart.yaml
- common/thanos/ci/test-values.yaml
- common/thanos/templates/_thanos_helpers.tpl
- common/thanos/templates/ingress-internal.yaml
- common/thanos/templates/ingress.yaml
- common/thanos/templates/thanos-objectstore.yaml
- common/thanos/templates/thanos-storeendpoint.yaml
- common/thanos/templates/thanos.yaml
- common/thanos/values.yaml
values are now accessed correctly
ingress with helpers added analog to prometheus-server
> [Thanos] adding optional ingress and fixing values

- openstack/cc3test/templates/cronjob-api.yaml
- openstack/cc3test/templates/cronjob-blockstorage.yaml
- openstack/cc3test/templates/cronjob-certificate.yaml
- openstack/cc3test/templates/cronjob-compute-server.yaml
- openstack/cc3test/templates/cronjob-compute.yaml
- openstack/cc3test/templates/cronjob-datapath.yaml
- openstack/cc3test/templates/cronjob-fileshare.yaml
- openstack/cc3test/templates/cronjob-integrity.yaml
- openstack/cc3test/templates/cronjob-loadbalancer.yaml
- openstack/cc3test/templates/cronjob-neutron-fip.yaml
> change cronjob api version from v1beta to v1

- openstack/neutron/Chart.lock
- openstack/neutron/Chart.yaml
> [neutron] Update utils

- openstack/barbican/requirements.lock
- openstack/barbican/requirements.yaml
> [barbican] Update utils

- openstack/designate/requirements.lock
- openstack/designate/requirements.yaml
> [designate] Update utils

- openstack/keystone/requirements.lock
- openstack/keystone/requirements.yaml
> [keystone] Update utils

- openstack/octavia/Chart.lock
- openstack/octavia/Chart.yaml
> [octavia] Update utils

- openstack/nova/requirements.lock
- openstack/nova/requirements.yaml
> [nova] Update utils

- openstack/placement/Chart.lock
- openstack/placement/Chart.yaml
> [placement] Update utils

- prometheus-exporters/apic-exporter/alerts/apicequipments.alerts
- prometheus-exporters/apic-exporter/alerts/apichealth.alerts
- prometheus-exporters/apic-exporter/alerts/apicips.alerts
- prometheus-exporters/apic-exporter/alerts/apicprocesses.alerts
- prometheus-exporters/snmp-exporter/alerts/snmp-n9k.alerts
on request by CF because of split of responsibilities
> severity decrease for net snmp-n9k.alerts

- openstack/swift/templates/haproxy-deployment.yaml
- openstack/swift/templates/replicators-daemonset.yaml
- openstack/swift/templates/rsyncd-daemonset.yaml
- openstack/swift/templates/servers-daemonset.yaml
- openstack/swift/templates/statsd-exporter-daemonset.yaml
- openstack/swift/templates/workers-daemonset.yaml
* simplify haproxy scheduling decisions
* same matchLabels for daemonsets in ap-sa-2
> Swift cleanup

- openstack/cinder/requirements.lock
- openstack/cinder/requirements.yaml
> [cinder] Update utils

- openstack/nova/requirements.lock
- openstack/nova/requirements.yaml
> [nova] Update rabbitmq to 3.10

- openstack/designate/requirements.lock
- openstack/designate/requirements.yaml
> [designate] Update rabbitmq to 3.10

- openstack/barbican/requirements.lock
- openstack/barbican/requirements.yaml
> [barbican] Update rabbitmq to 3.10

- openstack/hermes/requirements.lock
- openstack/hermes/requirements.yaml
> [hermes] Update rabbitmq to 3.10

- openstack/cronus/Chart.yaml
- openstack/cronus/templates/cronus/_config.yaml.tpl
- openstack/cronus/templates/cronus/pvc.yaml
- openstack/cronus/templates/cronus/statefulset.yaml
- openstack/cronus/values.yaml
* add max body size
* add support for file-buffer
* smooth upgrade from deployment to statefulset
* upgrade rabbitmq (see https://github.com/sapcc/helm-charts/pull/3727)
> [cronus]: add new config options

- openstack/placement/templates/seed.yaml
> [placement] remove unused role defintion

- openstack/nova/templates/seed.yaml
> [nova] use new objectstore_admin role

- openstack/glance/templates/seeds.yaml
> [glance] use new objectstore_admin role

- openstack/cronus/templates/cronus/_config.yaml.tpl
- openstack/cronus/values.yaml
To control SMTP connection timeout
> [cronus]: add SMTP connection timeout option

- openstack/hermes/templates/seed.yaml
> [hermes] use new objectstore_admin role

- openstack/lyra/templates/seed.yaml
> [lyra] use new objectstore_admin role

- common/prometheus-server-test/CHANGELOG.md
- common/prometheus-server-test/Chart.yaml
- common/prometheus-server-test/templates/thanos/thanos-seed.yaml
- openstack/cerebro/Chart.yaml
- openstack/cerebro/templates/domain-ccadmin-seed.yaml
- openstack/octobus/Chart.yaml
- openstack/octobus/templates/seeds.yaml
closes #3750
closes #3741 
closes #3746
> [thanos, cerebro, octobus] Switch to new objectstore user

- openstack/kubernikus/templates/seed.yaml
> [kubernikus] use new objectstore_admin role

- openstack/manila/requirements.lock
- openstack/manila/requirements.yaml
> [manila] Update rabbitmq to 3.10

- openstack/ironic/templates/seed.yaml
> [ironic] use new objectstore_admin role

- openstack/tempest/octavia-tempest/ci/test-values.yaml
- openstack/tempest/octavia-tempest/templates/bin/_tempest-start-and-cleanup.sh.tpl
This commit fixes the order of deletion objects. After this fix, we will not remove any network/ports if we still have a load balancers.
> Improve Octavia tempest cleanup tests.

- openstack/blackbox/charts/blackbox-tests-canary-nova/templates/project-canary-seed.yaml
- openstack/blackbox/charts/blackbox-tests-canary/templates/project-canary-seed.yaml
- openstack/blackbox/charts/blackbox-tests-regression/templates/project-regression-seed.yaml
- openstack/cc3test-seeds/templates/project-seed.yaml
> [monitoring] use new objectstore_admin role

- common/prometheus-server/CHANGELOG.md
- common/prometheus-server/Chart.yaml
- common/prometheus-server/templates/thanos/thanos-seed.yaml
Introducing the use of the new swift user before 7.0.0 change
> [prometheus] use new objectstore_admin role

- openstack/keystone/requirements.lock
- openstack/keystone/requirements.yaml
> [keystone] Update rabbitmq-chart

- openstack/cinder/requirements.lock
- openstack/cinder/requirements.yaml
> [cinder] Update rabbitmq-chart

- openstack/octavia/Chart.lock
- openstack/octavia/Chart.yaml
- openstack/octavia/ci/test-values.yaml
> [octavia] Update rabbitmq-chart

- openstack/hermes/requirements.lock
- openstack/hermes/requirements.yaml
> [hermes] Update rabbitmq-chart

- openstack/cronus/Chart.lock
- openstack/cronus/Chart.yaml
> [cronus] Update rabbitmq-chart

- openstack/sap-seeds/templates/flavor-seed.yaml
Just to let you know. There was no way around it.
> Private flavors for HXM SQL Servers

- prometheus-exporters/vrops-exporter/alerts/vcenter.alerts
see
https://github.com/sapcc/git-cert-shim/blob/6f1dd4fe0fd9da10964277d38b354a48f147154e/cmd/git-cert-shim/main.go#L96
> [vrops-exporter] Adjust alert according to cert renewal config

- openstack/prometheus-openstack/Chart.lock
- openstack/prometheus-openstack/Chart.yaml
- system/prometheus-vmware/Chart.lock
- system/prometheus-vmware/Chart.yaml
prometheus-server-test is obsolete now
> switch to prometheus-server

- openstack/keystone/templates/_helpers.tpl
- openstack/keystone/templates/bin/_bootstrap.tpl
- openstack/keystone/templates/bin/_db-sync.tpl
- openstack/keystone/templates/bin/_repair_assignments.tpl
- openstack/keystone/templates/deployment-api.yaml
- openstack/keystone/templates/deployment-cron.yaml
- openstack/keystone/templates/etc/_keystone.conf.tpl
- openstack/keystone/templates/job-bootstrap.yaml
- openstack/keystone/templates/job-migration.yaml
- openstack/keystone/templates/proxysql-configmap.yaml
- openstack/keystone/values.yaml
This needs to be explicitly enabled via
proxysql.mode=unix_socket
> [keystone] Add ProxySql side-car

- openstack/blackbox/charts/blackbox-tests-canary/Chart.yaml
- openstack/blackbox/charts/blackbox-tests-certificates/Chart.yaml
- openstack/blackbox/charts/blackbox-tests-datapath/Chart.yaml
- openstack/blackbox/charts/blackbox-tests-integrity/Chart.yaml
- openstack/blackbox/charts/blackbox-tests-regression/Chart.yaml
> update chart version to v2

- openstack/blackbox/charts/blackbox-tests-api/Chart.yaml
> added dependencies for blackbox

- openstack/blackbox/Chart.yaml
> added dependenecy in chart.yaml blackbox

- openstack/blackbox/values.yaml
> added values for owner-info

- openstack/blackbox/charts/blackbox-tests-canary-nova/Chart.yaml
- openstack/blackbox/charts/blackbox-tests-canary/Chart.yaml
- openstack/blackbox/charts/blackbox-tests-certificates/Chart.yaml
- openstack/blackbox/charts/blackbox-tests-datapath/Chart.yaml
- openstack/blackbox/charts/blackbox-tests-integrity/Chart.yaml
- openstack/blackbox/charts/blackbox-tests-regression/Chart.yaml
> adjust values according to dependency

- openstack/blackbox/charts/blackbox-tests-api/values.yaml
- openstack/blackbox/charts/blackbox-tests-canary-nova/values.yaml
- openstack/blackbox/charts/blackbox-tests-canary/values.yaml
- openstack/blackbox/charts/blackbox-tests-certificates/values.yaml
- openstack/blackbox/charts/blackbox-tests-datapath/values.yaml
- openstack/blackbox/charts/blackbox-tests-integrity/values.yaml
- openstack/blackbox/charts/blackbox-tests-regression/values.yaml
- openstack/blackbox/values.yaml
> adjusted values file

- common/thanos/Chart.yaml
- common/thanos/ci/test-values.yaml
- common/thanos/templates/thanos.yaml
- common/thanos/values.yaml
queryDiscovery directive was not working properly
> adding clusterTypes

- openstack/ironic/templates/_conductor-configmap.yaml.tpl
- openstack/ironic/templates/_conductor-deployment.yaml.tpl
- openstack/ironic/templates/_console-ingress.yaml.tpl
- openstack/ironic/templates/_console-service.yaml.tpl
- openstack/ironic/templates/etc/_ironic_conductor.conf.tpl
- openstack/ironic/templates/hpa-api.yaml
- openstack/ironic/templates/hpa-conductor.yaml
- openstack/ironic/values.yaml
adds autoscaling for api and (unnamed) conductors
> [ironic] adds support unnamed conductors

- prometheus-exporters/network-generic-ssh-exporter/alerts/asr.alerts
Update alerts NetworkAsrNatTcpPortPreAllocationLow, NetworkAsrNatUdpPortPreAllocationLow
- raise severity from info to critical
- add link to playbook
> Updated severity and playbook for NetworkAsrNatTcpPortPreAllocationLow

- openstack/ironic/ci/test-values.yaml
- openstack/ironic/templates/seed.yaml
- openstack/ironic/values.yaml
> [Ironic][Seeds]disable project seeding of a particular domain

- openstack/neutron/ci/test-values.yaml
- openstack/neutron/templates/seed.yaml
- openstack/neutron/values.yaml
> [Neutron][Seeds]disable project seeding of a particular domain

- openstack/maia/Chart.lock
- openstack/maia/Chart.yaml
Reverts sapcc/helm-charts#3902
> Revert "[Maia] fallback prometheus-server chart"

- prometheus-exporters/vrops-exporter/alerts/host.alerts
- Playbooks linked
- raise was requested by InfraOps team
> Raise Host HA alerts to warning

- prometheus-exporters/vrops-exporter/alerts/virtualmachine.alerts
Open for alert name discussion.
> Added NSXTMgmtVMsNotWellDistributed alert

- openstack/manila/ci/test-values.yaml
- openstack/manila/templates/seeds.yaml
- openstack/manila/values.yaml
> [Manila][Seeds]disable project seeding of a particular domain

- openstack/arc/ci/test-values.yaml
- openstack/arc/templates/seed.yaml
- openstack/arc/values.yaml
> [Arc][Seeds]disable project seeding of a particular domain

- openstack/maia/Chart.lock
- openstack/maia/Chart.yaml
> bump prometheus-server version to switch swift user for OpenstackSeed

- openstack/limes/ci/test-values.yaml
- openstack/limes/templates/_utils.tpl
- openstack/limes/templates/secret.yaml
I accidentally pushed this to master and needed to revert it.
> openstack/limes: move deployment specific settings in to environment variables

- openstack/cc3test/alerts/block-storage.alerts
points to https://operations.global.cloud.sap/docs/support/playbook/cinder/alerts/
> fix playbook links

- openstack/ironic/ci/test-values.yaml
- openstack/ironic/templates/_conductor-configmap.yaml.tpl
- openstack/ironic/templates/_conductor-deployment.yaml.tpl
- openstack/ironic/templates/api-deployment.yaml
- openstack/ironic/templates/db-migration-job.yaml
- openstack/ironic/templates/etc-configmap.yaml
> [ironic] remove reference to deleted template

- openstack/cronus/templates/cronus/_config.yaml.tpl
- openstack/cronus/templates/cronus/deployment.yaml
- openstack/cronus/templates/cronus/statefulset.yaml
- openstack/cronus/values.yaml
> [cronus]: set ndots to 1

- system/gatekeeper-config/templates/constraint-region-value-mismatch.yaml
Need to make a PR because github-guard is broken and has taken away my push access.
> gatekeeper: enforce GkRegionValueMismatch in prod

- prometheus-exporters/octobus-query-exporter/alerts/events.alerts
Alert EsxiNicError uplifted to critical.
> Alert EsxiNicError uplifted to critical.

- openstack/cronus/templates/cronus/_config.yaml.tpl
new connections pool feature enablement
> [cronus]: introduce a connPool config

- openstack/nova/templates/etc/_nova-compute-ironic.conf.tpl
- openstack/nova/templates/etc/_nova-compute-kvm.conf.tpl
- openstack/nova/templates/etc/_nova-scheduler.conf.tpl
- openstack/nova/templates/etc/_nova.conf.tpl
- openstack/nova/templates/hypervisors/hypervisors-vmware-configmap-vct.yaml
- openstack/nova/values.yaml
This PR updates the Nova chart to add/remove/update settings required for Xena while keeping it compatible with Rocky.
> [Nova] Update settings for Xena

- global/prometheus-alertmanager-operated/Chart.yaml
> [alertmanager] gcp instance moves in datacenter

- openstack/nova/templates/etc/_api-paste.ini.tpl
This is a general update of the api-paste.ini to make it more in line
with upstream. There are a couple of changes we can already do for Rocky
and more changes we need to do for Xena, guarded by some conditionals.
* Removal of "noauth2"
Usage of "noauth2" is deprecated in Xena and we don't use it in Rocky
already, because it's only meant for development and circumvents any
authentication mechanism i.e. keystone. We don't need that so we remove
it.
* Move "healthcheck" from filter to app
oslo.middleware states already since at least Rocky, that healthcheck
should not be run as a filter anymore, but as an app instead [0]. This
also means that we remove "healtcheck" from any pipeline definition.
* Split API versions endpoints for Xena
While Rocky doesn't support that (the feature comes in …
> [nova] Rework api-paste.ini

- openstack/cronus/templates/cronus/_config.yaml.tpl
move global conn pool config to per backend
> [cronus]: new per backend conn pool config

- openstack/barbican/Chart.lock
- openstack/barbican/Chart.yaml
> [barbican] Remove region check

- openstack/glance/Chart.lock
- openstack/glance/Chart.yaml
> [glance] Remove region check

- openstack/nova/Chart.lock
- openstack/nova/Chart.yaml
> [nova] Remove region check

- openstack/placement/Chart.lock
- openstack/placement/Chart.yaml
> [placement] Remove region check

- openstack/manila/Chart.lock
- openstack/manila/Chart.yaml
> [manila] Remove region check

- openstack/designate/Chart.lock
- openstack/designate/Chart.yaml
> [designate] Remove region check

- openstack/utils/Chart.yaml
- openstack/utils/templates/_proxysql.tpl
See changelog: https://github.com/sysown/proxysql/releases/tag/v2.4.3
We are not using any features which have been improved.
> [utils] Bump proxysql version

- openstack/cc3test/alerts/load-balancer.alerts
> adjusted octavia flapping check

- openstack/cc3test/templates/cronjob-neutron.yaml
> remove purge pod

- openstack/cc3test/templates/cronjob-neutron.yaml
> neutron nsxt check run in 45 min interval

- openstack/cronus/Chart.lock
- openstack/cronus/Chart.yaml
bump rabbitmq helm-chart version to fix FS permissions issue
see https://github.com/sapcc/helm-charts/pull/4023
> [cronus]: bump rabbitmq

- openstack/cc3test/templates/cronjob-hermes.yaml
> added cron job for canary hermes check

- openstack/neutron/Chart.lock
- openstack/neutron/Chart.yaml
> [neutron] Remove region check

- openstack/octavia/Chart.lock
- openstack/octavia/Chart.yaml
> [octavia] Remove region check

- openstack/cc3test/templates/cronjob-neutron-fip.yaml
> added pod for neutron base checks

- openstack/cc3test/templates/cronjob-network.yaml
> refactor cron job name for neutron check

- openstack/cronus/templates/cronus/_config.yaml.tpl
new option for conn pool
cc @sapmli
> [cronus]: introduce new maxConnReleaseTimeout config option

- global/prometheus-alertmanager-operated/Chart.yaml
- global/prometheus-alertmanager-operated/templates/_alertmanager.yaml.tpl
several alertmanager routing updates
- rm eu-ru-1
- add wsus routing
- add support group routing
- rm awx (just errors in the logs - clarified)
> D072896 am routing update

- openstack/cronus/templates/nebula/_config.yaml.tpl
> [cronus]: add alternateContact config to nebula

- system/unbound/templates/config.yaml
https://nlnetlabs.nl/documentation/unbound/howto-optimise/
> [Unbound] config optimizations as suggested by docs:

- openstack/placement/templates/db-migrate-job.yaml
- openstack/placement/templates/db-online-migrate-job.yaml
- openstack/placement/templates/placement-api-deployment.yaml
These are only available starting with Yoga, so this needs to be rolled out with the Yoga update.
> [placement] Switch to loci images

- openstack/cc3test/alerts/file-shares.alerts
> update playbook links to rm html ending

- openstack/placement/templates/placement-ingress.yaml
This enables automatic creation of the Ingress' DNS entry via the disco operator.
> [placement] Add disco annotation

- openstack/cc3test/alerts/compute.alerts
@artherd42 : please review this.
> adjust vcenter_api check

- global/prometheus-kubernetes-global/alerts/federation.alerts
> update playbook links to rm html ending (hugo)

- openstack/manila/alerts/openstack/manila.alerts
> manila: update playbook links to rm html ending

- openstack/cc3test/templates/cronjob-dns.yaml
> added dns cron job
